### ISSUE TITLE
IllegalArgumentException: Date string argument is not of format yyyy-MM-dd: 2023-02

### ISSUE THREAD

**Issue by atorresveiga** [woocommerce/woocommerce-android#10172]
**Describe the bug**
On the MyStore screen, when displaying the revenue stats, we are trying to parse a date that is not in the expected format.  From our first review of this issue, we think this could be a problem of either a race condition or a collision of the cached DB keys. More context here: peaMlT-c8-p2.

This issue is for adding extra information to understand why this is happening.

> We could also consider adding some breadcrumbs to sentry when the user changes granularity -> perhaps, they might help us notice if this issue happens after granularity change which could suggest the race condition.

**Comment by Ecarrion** [comment]
Closing this as it is resolved on sentry
