### ISSUE TITLE
Order list isn't always refreshed

### ISSUE THREAD

**Issue by grigorijurasov** [woocommerce/woocommerce-android#1025]
**Is your feature request related to a problem? Please describe.**

In 1984772 zen user reports that they need to "pull down" the order list to refresh as the orders are not up to date, despite the notification

**Describe the solution you'd like**
When a notification about a new order comes in - perhaps we should have a mechanism to also update the order list

**Describe alternatives you've considered**
Not sure about alternatives

https://github.com/woocommerce/woocommerce-ios/issues/927

**Comment by AmandaRiu** [comment]
@grigorijurasov Did you verify this is a problem on Android? the logic was already built into android to refresh automatically so it wouldn't be an enhancement if it's not working - it would be a bug.

**Comment by grigorijurasov** [comment]
Oh, I didn't check it then. I was asked to open a request for Android too so I did it without testing, sorry. Closing
