### ISSUE TITLE
Impossible to type title of a product

### ISSUE THREAD

**Issue by pmusolino** [woocommerce/woocommerce-android#10387]
In the beta release 16.6 (I don't know if it also happens on previous releases), if I try on an Android device to type the title of a product, this is what happens.
Sometimes it stops after around 1 minute, but it restarts if you continue to type.
This is an urgent issue that should be fixed!

<img src="https://github.com/woocommerce/woocommerce-android/assets/495617/414c3ef2-0752-4863-ba36-aed63ef6b359" width=300 />

Ref: peaMlT-kV-p2

**Comment by shiki** [comment]
FYI @atorresveiga
