### ISSUE TITLE
Fake or wrong email are not handled correctly in the registration process

### ISSUE THREAD

**Issue by pmusolino** [woocommerce/woocommerce-android#10386]
In the Android app, when a user enters an email that is not valid for the backend (like a fake email or fake domain), the API will returns an error that is not correctly handled.

How to replicate it:
1. Try to create a new account
2. Use a fake email (generated through temp mail), like `vojep71479@jalunaki.com`
3. Notice that instead of seeing an error, like on iOS, you will move forward to the password screen.
4. Add a password and press `Continue`
5. Notice the loading spinner, then nothing happens.

This is what appears instead on iOS:
<img src="https://github.com/woocommerce/woocommerce-android/assets/495617/2d595aaf-e225-457c-9d1e-a601ef85626e" width=300 />

**Comment by JorgeMucientes** [comment]
Account creation feature was disabled from the app a while back. So I'm closing this issue for now
