### ISSUE TITLE
[Order creation] Display prices only for synced items

### ISSUE THREAD

**Issue by samiuelson** [woocommerce/woocommerce-android#10521]
In case the prices of products are set up to be entered inclusive of taxes there is a glitch in the order creation. When adding an item to the order the price (inclusive of taxes) gets overridden once the item gets synced. We can enhance the UX by displaying prices only for the already synced items. 

| prices entered including taxes | prices entered excluding taxes |
|---|---|
| <video src=https://github.com/woocommerce/woocommerce-android/assets/4527432/ca0499ec-8394-4048-940a-cfaf63f8543a width=300/> | <video src=https://github.com/woocommerce/woocommerce-android/assets/4527432/43fed1f5-4a2e-46a2-873d-6f4a30bfb4b8 width=300/> |

**Comment by backwardstruck** [comment]
Hi @samiuelson Thanks for filing this issue. I just want to clarify my understanding before attemtpting a fix. The only issue is in the video on the left (including the tax change), right?

i.e. we should not see the price change from this

<img width="383" alt="Screenshot 2024-01-19 at 16 03 31" src="https://github.com/woocommerce/woocommerce-android/assets/947561/37284330-a803-47be-9020-1cf3986aea02">


to this

<img width="383" alt="Screenshot 2024-01-19 at 16 03 56" src="https://github.com/woocommerce/woocommerce-android/assets/947561/e7a42ede-06d2-41da-bb23-6afb560ca092">

It should just show the final price, CA$32.27. If that's correct, is there anything else that needs changing?

**Comment by samiuelson** [comment]
> It should just show the final price, CA$32.27. If that's correct, is there anything else that needs changing?

Hi, @backwardstruck 👋 Yes, that's correct!

**Comment by backwardstruck** [comment]
@samiuelson how can we tell whether an item is "already synced"? Is there a field or do I need to look at the code that calculates the tax? Maybe it's something that I will need to add.

**Comment by backwardstruck** [comment]
> @samiuelson how can we tell whether an item is "already synced"? Is there a field or do I need to look at the code that calculates the tax? Maybe it's something that I will need to add.

Nevermind. It looks like it `OrderCreationProduct` has an Order item with an id != 0, then it is considered synced. 

@kidinov pointed this out in the method `sanitizeUnsyncedOrderItemsData` we are checking for `fun Order.Item.isSynced() = this.itemId != Order.Item.EMPTY.itemId`
