### ISSUE TITLE
Order List: Add individual dates

### ISSUE THREAD

**Issue by kyleaparker** [woocommerce/woocommerce-android#1057]
**Is your feature request related to a problem? Please describe.**

When trying to find an order from a specific date it can be difficult to scan through right now, as we group things into an "older than a month" category.

**Describe the solution you'd like**

Add the date to the top of each order cell:

![Android-order-cell](https://user-images.githubusercontent.com/712873/57557532-818f4300-7348-11e9-8935-97ca7f0a29a9.png)

Corresponding [iOS issue
](https://github.com/woocommerce/woocommerce-ios/issues/956)

**Comment by nbradbury** [comment]
Note: as per a discussion with @kyleaparker, we can leave off the year if it's the current one, and three-character month names are fine.

**Comment by AmandaRiu** [comment]
@nbradbury Code looks good, but just as I was about to merge I noticed there is a funkiness with the spacing inside the order list cell. I'm wondering if there should be less space between the date and the order number? Looking at the design, the vertical spacing between the 3 elements is identical, but in this implementation the date is floating farther from the rest of the text:

![Screen Shot 2019-05-14 at 6 21 04 PM](https://user-images.githubusercontent.com/5810477/57738518-718fa000-7675-11e9-8c22-8bfe12228814.png)
