### ISSUE TITLE
client cannot use "password" grant_type

### ISSUE THREAD

**Issue by Dikiniello** [woocommerce/woocommerce-android#1059]
Hi, I am trying to log into app using Jetpack. 
In readme it suggest to change "wp.oauth.app_id and secret" but in my gradle.properties there are "wc.oauth.app_id" and "wc.oauth.app_secret".. So WC, not WP
The login always fail showing a pop up "Unknown client_id"
I think there is a problem here:

> E/Volley: [493] BasicNetwork.performRequest: Unexpected response code 400 for https://public-api.wordpress.com/oauth2/token
> E/WordPress-API: Authentication error
> E/WordPress-API: onAuthenticationChanged has error: INVALID_CLIENT - Unknown client_id.
> I/WooCommerce-UTILS: 🔵 Tracked: login_failed, Properties: {"error_type":"INVALID_CLIENT","error_context":"AuthenticationErrorType","error_description":"Unknown client_id."}
> I/WooCommerce-UTILS: 🔵 Tracked: login_wpcom_background_service_update, Properties: {"login_service_is_foreground":false,"login_phase":"FAILURE"}
> I/WordPress-NUX: Received state: FAILURE
> D/EGL_emulation: eglMakeCurrent: 0x8bfd6b60: ver 2 0 (tinfo 0x8a39f1c0)
> E/WordPress-NUX: Server response: Unknown client_id.

Can you help me? Thank you

**Comment by AmandaRiu** [comment]
Interesting. I just checked my `gradle.properties` and I have both `wc.oauth.app_id` and `wp.oauth.app_id` and the associated secrets defined for both. Can you try that and see if that fixes it?

**Comment by Dikiniello** [comment]
I solved the problem client_id setting "wc.oauth.app_id" and "wc.oauth.app_secret" creating a new app on "WordPress.com applications manager".. 
Now i can login using main app account but i can't login if i try to insert user's account.
If i try to login with user's account i get this popup error 

> client cannot use "password" grant_type

How can i solve this? Thank you

**Comment by AmandaRiu** [comment]
What role is assigned to the user account you are attempting to login with? Currently the app only supports administrators and shop managers.

**Comment by Dikiniello** [comment]
Now the app supports only the administrator. For shopper manager, in this case the admin of subdomain in munltisite network, the app return "Client cannot use "password" grant_type"

in log there are two errors
```
2019-05-14 18:01:00.498 5807-5807/com.woocommerce.android E/WordPress-API: Authentication error
2019-05-14 18:01:00.500 5807-5807/com.woocommerce.android E/WordPress-API: onAuthenticationChanged has error: UNSUPPORTED_GRANT_TYPE - Client cannot use "password" grant_type
2019-05-14 18:01:00.527 5807-5807/com.woocommerce.android I/WooCommerce-UTILS: 🔵 Tracked: login_failed, Properties: {"error_type":"UNSUPPORTED_GRANT_TYPE","error_context":"AuthenticationErrorType","error_description":"Client cannot use \"password\" grant_type"}
2019-05-14 18:01:00.629 5807-5807/com.woocommerce.android I/WooCommerce-UTILS: 🔵 Tracked: login_wpcom_background_service_update, Properties: {"login_service_is_foreground":false,"login_phase":"FAILURE"}
2019-05-14 18:01:00.630 5807-5807/com.woocommerce.android I/WordPress-NUX: Received state: FAILURE
```

I want login only for the shopper manager

**Comment by AmandaRiu** [comment]
@Dikiniello Interesting. I'm able to login as a Shop Manager without any issues. To help us troubleshoot further, please open a ticket with our support option inside the app. This way we can gather more private information to assist with troubleshooting. Plus our support may better understand why this is happening.

**Comment by franc3sc0s92** [comment]
Hi, I've download the source, create de wp app and  then i'm build the app.
The app work but the acces is only for administrator of the app.
In the official app the log in is to jetpack and then the shop manager can choose his site in the list of all of his sites.
How can I grant the access of all sites?

the error is "client cannot use "password" grant_type"

**Comment by AmandaRiu** [comment]
Hello @Dikiniello  and @franc3sc0s92, I've dug into this a bit further and you will get this error if you are attempting to login with a wordpress.com user that doesn't match the OAuth2 app on developer.wordpress.com. Each Shop Manager on that site would need to build the app themselves and use their own OAuth2 creds.

**Comment by Dikiniello** [comment]
Are there other ways to login? 
Official app from google store allow all admin and shop manager login..
Thank you

**Comment by AmandaRiu** [comment]
> Are there other ways to login?
Official app from google store allow all admin and shop manager login..

Not while using a version built directly from the source. Is there a reason you don't want to just use the official version?

**Comment by Dikiniello** [comment]
Yes.. I need to add a delay to order's shipping from the app

**Comment by AmandaRiu** [comment]
I see. I recommend submitting any ideas for new functionality on our [ideas board](http://ideas.woocommerce.com/forums/133476-woocommerce/filters/new?category_id=84283). This app is still very new and we are constantly working to improve it.
