### ISSUE TITLE
Stock Fail to Update for Added/Removed Products in On-Hold Orders

### ISSUE THREAD

**Issue by erricgunawan** [woocommerce/woocommerce-android#10609]
**Describe the bug**
When modifying an On-Hold order in the application by either adding or removing products, the stock levels do not automatically update to reflect these changes. The products are correctly added or removed from the order, but the corresponding adjustment in stock quantity is not triggered immediately.

***Workaround***
To trigger the stock adjustment, it is currently necessary to change the order status from 'On-Hold' to 'Pending Payment' and then revert it back to 'On-Hold'. 

Also, updating the On-Hold Order from WP-Admin correctly adjusts to the correct stock.

**To Reproduce**
1. Go to Orders and select an existing On-Hold Order (or create a new one)
2. Edit the order by either adding a new product or removing an existing one. Or adjust the number of items purchased for an existing product in the Order.
3. Observe that the product list in the order updates correctly, but the stock quantity does not adjust accordingly in the Order Notes.

**Screenshots**

<details>
  <summary>Screen Recording:</summary>
  <br>
  There's a video recording from the user in 7570597-zen. It's in iOS version but it's also reproducible on Android app.

  The video is also uploaded to p1706168218694079/1706168063.450169-slack-C6H8C3G23
</details>

**Expected behavior**
The stock quantity should automatically update to reflect the changes (addition/removal of products) in the on-hold order without requiring a change in order status or manual update intervention.

**Isolating the problem (mark completed items with an [x]):**
- [x] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [x] This bug happens with a default WordPress theme active, or [Storefront](https://woo.com/products/storefront/).
- [x] I can reproduce this bug consistently using the steps above.

**Mobile Environment**
Please include:
- Device: Redmi Note 9 Pro
- Android version: 12 SKQ1.211019.001 | MIUI Global 14.0.1 Stable
- WooCommerce Android version: 16.9

**WordPress Environment**
<details>

```
Not sure if it's still relevant, but if one is required, please ping me and I can provide one from my testing site.
```
</details>

**Comment by rachelmcr** [comment]
Based on the investigation in https://github.com/woocommerce/woocommerce-ios/issues/11800, I'll close this issue and have reported this in https://github.com/woocommerce/woocommerce/issues/44085 for followup.

**Comment by rachelmcr** [comment]
Just a quick note that a [fix for this issue](https://github.com/woocommerce/woocommerce/pull/47784) has been merged, for release in WooCommerce core 9.1.0.

**Comment by Mehdi-YC** [comment]
hi @rachelmcr , please let me know, does this bug happens only when the status is on-hold ?
i am experiencing the same thing even in 9.1.x
i changed the quantity to 0 in some lineItems to delete them, the got deleted in the UI and order, however the changes did not happen in the stock,
tried with variable products and simple products
when reducing or adding quantity, this works (i am also using the workaround you talked about)
but the deletion does not work

**Comment by rachelmcr** [comment]
@Mehdi-YC The original issue was not limited to on-hold orders; it was an issue with any orders updated via the REST API. It sounds like the fix in https://github.com/woocommerce/woocommerce/pull/47784 isn't working when a line item is removed from the order completely — @coreymckrill could you perhaps take another look at that?

**Comment by coreymckrill** [comment]
Thanks for the heads up! I opened a new issue for this here: https://github.com/woocommerce/woocommerce/issues/49651

**Comment by coreymckrill** [comment]
Just merged [this fix](https://github.com/woocommerce/woocommerce/issues/49651), should be in the 9.3 release.
