### ISSUE TITLE
[Product Creation AI] Improvements to AI prompt and UI

### ISSUE THREAD

**Issue by selanthiraiyan** [woocommerce/woocommerce-android#10653]
We made a few improvements to product creation AI in iOS. https://github.com/woocommerce/woocommerce-ios/pull/11853

Logging this issue to make the same changes/improvements in Android.

Prompt
1. Removed newline characters and empty spaces added for human readability and use a dictionary and JSON encoding to create the prompt.
2. Added the following sentence to the prompt asking to send only JSON and nothing else.
    * “Your response should be in JSON format and don’t send anything extra.”
3. Update the wording in the prompt to mention the ISO language code clearly. 
    * Prompt changes can be viewed in https://github.com/woocommerce/woocommerce-ios/pull/11853/commits/24bbeb33713d3ae1779ced829e523bc6a4b54e43

UI
1. Make description a required field in response and show error alert if the description cannot be parsed from the AI response. This allows the user to retry from the alert.
2. Use the user entered product name if no product name is returned from AI.
3. Hide the short description field if short description returned from AI is empty. 

Language detection
1. Cache the identified language and reuse upon retrying after facing error.

**Comment by JorgeMucientes** [comment]
I don't think this applies anymore after we worked in product creation with AI iteration 2. I checked in Android and the prompt we are sending is already trimmed and uses a key value/dictionary for the product attributes: 
```
{
  "question": "You are a WooCommerce SEO and marketing expert, perform in-depth research about the product using the provided name, keywords and tone, and give your response in the below JSON format\n\nkeywords: \"pants, black, durable, trekking\"\ntone: \"Casual\"\n\nYour response should be in JSON format and don\u0027t send anything extra. Don\u0027t include the word JSON in your response:\n\"{\n   \"names\":\"An array of strings, containing three different names of the product, written in the language with ISO code \"en\"\",\n   \"descriptions\": \"An array of strings, each containing three different product descriptions of around 100 words long each in a \"Casual\" tone, written in the language with ISO code \"en\"\",\n   \"short_descriptions\": \"An array of strings, each containing three different short descriptions of the product in a \"Casual\" tone, written in the language with ISO code \"en\",\n   \"virtual\":\"A boolean value that shows whether the product is virtual or physical\",\n   \"shipping\":{\n      \"length\":\"Guess and provide only the number in cm\",\n      \"weight\":\"Guess and provide only the number in kg\",\n      \"width\":\"Guess and provide only the number in cm\",\n      \"height\":\"Guess and provide only the number in cm\"\n   },\n   \"price\":\"Guess the price in USD, do not include the currency symbol, only provide the price as a number\",\n   \"tags\":\"Given the list of available tags \"ceramic, colorful, durable, hiking, lightweight, More tags, sturdy, Subs tag, Trakking pants, trekking pants, waterproof\", suggest an array of the best matching tags for this product. You can suggest new tags as well.\",\n   \"categories\":\"Given the list of available categories \"Clothing, Home, Hoodies, Kitchenware, Men, Outdoor Adventure, pants, Shirts, Subscription, Summer, Uncategorized, Winter, Women\", suggest an array of the best matching categories for this product. You can suggest new categories as well.\"\n}\"",
  "stream": false,
  "feature": "woo_android_product_creation",
  "format": "json_object",
  "model": "gpt-4o",
  "max_tokens": 4000
}
```

Closing
