### ISSUE TITLE
[Tablet Support M2] Order listing screen just shows shimmer effect

### ISSUE THREAD

**Issue by AnirudhBhat** [woocommerce/woocommerce-android#10700]
Steps to reproduce
1. Navigate to the orders tab on tablet devices - You see a two pane layout
2. Enter into split view
3. Resize (narrow) the app window so that the layout transitions into phone layout
4. Now, you see just the order detail screen
5. Press back
6. You just see the shimmer effect and the screen does not navigate to the order listing screen.

[order_list_shimmer_effect_bug.webm](https://github.com/woocommerce/woocommerce-android/assets/1331230/71bb7b22-ae8e-4a1c-b6c0-28d741df3c46)

**Comment by samiuelson** [comment]
Duplicate – #10861
