### ISSUE TITLE
[Better Errors] Connectivity Tool logic

### ISSUE THREAD

**Issue by Ecarrion** [woocommerce/woocommerce-android#10799]
The connectivity tool should be able to measure

- [ ] Internet connectivity
- [ ] Reaching WP Servers -> Fetching mobile announcements endpoint
- [ ] Reaching the site -> Fetching the system status endpoint
- [ ] Fetching the site orders -> Fetching the orders endpoint

Additionally:

- [ ] Requests responses should be logged to app logs (success and failures with errors)
- [ ] Launch the tool when tapping the troubleshoot button from the orders list error top banner. (For all errors, not only for timeout ones)

**Comment by dangermattic** [comment]
🚫 Please add a type label (e.g. **type: enhancement**) and a feature label (e.g. **feature: stats**) to this issue.

**Comment by Ecarrion** [comment]
iOS Implementation https://github.com/woocommerce/woocommerce-ios/pull/12058
