### ISSUE TITLE
[Better Errors] Update timeout error message

### ISSUE THREAD

**Issue by Ecarrion** [woocommerce/woocommerce-android#10797]
# Tasks

- [ ] Update the message when we detect a timeout error (After the automatic retry)

![Image](https://github.com/woocommerce/woocommerce-ios/assets/562080/ecda0631-65b4-4d62-bb75-c3b7fd93c441)

**Comment by dangermattic** [comment]
🚫 Please add a type label (e.g. **type: enhancement**) and a feature label (e.g. **feature: stats**) to this issue.
