### ISSUE TITLE
[Better Errors] Automatically retry Order List timeout errors 

### ISSUE THREAD

**Issue by Ecarrion** [woocommerce/woocommerce-android#10796]
Some hosts are in some sort of sleep state until a first request arrives and wakes them up. Let's try retrying timeout errors to have more changes of users getting their data.

# Tasks

- [ ] Retry timeout errors automatically.

**Comment by dangermattic** [comment]
🚫 Please add a type label (e.g. **type: enhancement**) and a feature label (e.g. **feature: stats**) to this issue.
