### ISSUE TITLE
[Better Errors] Connectivity Tool Mock Up

### ISSUE THREAD

**Issue by Ecarrion** [woocommerce/woocommerce-android#10798]
- Experiment with a UI that serves as a connectivity tool where we will fire requests to different servers to help the users diagnose connectivity problems

- Add a place to add suggestions depending on the results of the requests.

![Image](https://github.com/woocommerce/woocommerce-android/assets/562080/c7a8a94a-414e-477d-9199-a61a230e3e57)

**Comment by dangermattic** [comment]
🚫 Please add a type label (e.g. **type: enhancement**) and a feature label (e.g. **feature: stats**) to this issue.
