### ISSUE TITLE
Blaze: Loading and Error screens for campaign creation

### ISSUE THREAD

**Issue by JorgeMucientes** [woocommerce/woocommerce-android#10808]
mBhyoV7OPhFnOugxLy6SMS-fi-2506_59205

![Screenshot 2024-02-14 at 12 19 59](https://github.com/woocommerce/woocommerce-android/assets/2663464/93e43c75-210e-41d0-b644-49aa2e3fe75c)

**Comment by dangermattic** [comment]
🚫 Please add a type label (e.g. **type: enhancement**) and a feature label (e.g. **feature: stats**) to this issue.
