### ISSUE TITLE
[Better Errors] Detect login error and redirect to app password explanations

### ISSUE THREAD

**Issue by Ecarrion** [woocommerce/woocommerce-android#10803]
## Tasks

When logging into a self-hosted site.

- [ ] Detect when an "site error" has happened and redirect the user automatically to the app password explanation screen.
- [ ] All other errors (invalid credentials, system, network, etc) should present the regular alert **without** the option of triggering the app password flow.

Current | Expected
--- | ---
![Image](https://github.com/woocommerce/woocommerce-android/assets/562080/c4425408-b084-45c2-9186-a97b71ee87bb) | ![Image](https://github.com/woocommerce/woocommerce-android/assets/562080/6cd440d1-ee21-4dd4-8ccb-f9c1dc29f752)

### Identified errors

- 4xx would need its proper error message, as it means that the user customized their login page.

- 200, here we need to perform some additional checks, we need to check for the presence of a div with the id [login_error](https://href.li/?https://github.com/WordPress/WordPress/blob/34662ac6d6bd2646b24adddb3959525e24fdbb6f/wp-login.php#L253) in the received HTML:

    - If it’s there, then this means that it’s probably an authentication issue, we can even present the message we got as the error directly without putting our own, which would be clearer to our users.

    - If it’s not, then we can’t really confirm that it’s an authentication issue, so we should have a meaningful error message to let the user know that we can’t support their website now, and that we are working on it.

**Comment by dangermattic** [comment]
🚫 Please add a type label (e.g. **type: enhancement**) and a feature label (e.g. **feature: stats**) to this issue.
