### ISSUE TITLE
[Tablet Support M2] Track type of device for some screens

### ISSUE THREAD

**Issue by AnirudhBhat** [woocommerce/woocommerce-android#10806]
The goal of this task is to analyse the impact of the project Lily-Pad M2 changes, it would be useful to know when the two pane layout is in use.

`horizontal_size_class : compact|regular`

Add a new property `horizontal_size_class` for the Below events:
`main_tab_orders_selected`
`main_tab_orders_reselected`
`payments_flow_order_collect_payment_tapped`
`order_create_button_tapped`
`order_open`

**Comment by dangermattic** [comment]
🚫 Please add a type label (e.g. **type: enhancement**) and a feature label (e.g. **feature: stats**) to this issue.
