### ISSUE TITLE
[Better Errors] Connectivity tool suggestions & resolution

### ISSUE THREAD

**Issue by Ecarrion** [woocommerce/woocommerce-android#10800]
After the connectivity tool has finished running let's offer some suggestions to the user so they can continue their trouble shoot journey.

source pe5pgL-4yi-p2#comment-3750

## No Internet connection

> It looks like you're not connected to the internet.
>
> Ensure your Wi-Fi is turned on. If you're using mobile data, make sure it's enabled in your device settings.

## Can't reach wpcom servers 

> Oops! It seems we can't connect to WordPress.com at the moment
>
> Ensure your Wi-Fi is turned on. If you're using mobile data, make sure it's enabled in your device settings.

### Timeout Error
> Oops! Your site seems to be taking too long to respond.
> 
> Contact your hosting provider for further assistance.

**Read More** navigates to [https://woo.com/document/android-ios-apps-troubleshooting-error-fetching-orders/](https://href.li/?https://woo.com/document/android-ios-apps-troubleshooting-error-fetching-orders/)

### Decoding Error
> Oops! It seems we can’t work properly with your site’s response.
> 
> But don’t worry, our support team is here to help. Contact us and we will happily assist you.

**Read More** navigates to [https://woo.com/document/android-ios-apps-troubleshooting-error-fetching-orders/](https://href.li/?https://woo.com/document/android-ios-apps-troubleshooting-error-fetching-orders/)

### Jetpack Error
> Oops! There seems to be a problem with your jetpack connection.
> 
> But don’t worry, our support team is here to help. Contact us and we will happily assist you.

**Read More** navigates to [https://jetpack.com/support/reconnecting-reinstalling-jetpack/](https://href.li/?https://jetpack.com/support/reconnecting-reinstalling-jetpack/)

### Any Other Error
> Oops! There seems to be a problem with your site.
>
> Contact your hosting provider for further assistance.

**Read More** navigates to [https://woo.com/document/android-ios-apps-troubleshooting-error-fetching-orders/](https://href.li/?https://woo.com/document/android-ios-apps-troubleshooting-error-fetching-orders/)

----

**Note that there should always be a "Contact Support" button**

**Comment by dangermattic** [comment]
🚫 Please add a type label (e.g. **type: enhancement**) and a feature label (e.g. **feature: stats**) to this issue.
