### ISSUE TITLE
[Better Errors] Show error when leaving app password approval flow

### ISSUE THREAD

**Issue by Ecarrion** [woocommerce/woocommerce-android#10804]
## Tasks

- [ ] Detect when a user wants to leave the app password login web page before approving app passwords and ask for confirmation about it.

<img src="https://github.com/woocommerce/woocommerce-android/assets/562080/db6f174a-cac2-4b6d-8e42-3d1f273b2a0e" width="365">

**Comment by dangermattic** [comment]
🚫 Please add a type label (e.g. **type: enhancement**) and a feature label (e.g. **feature: stats**) to this issue.
