### ISSUE TITLE
Grouped products selection doesn't work

### ISSUE THREAD

**Issue by kidinov** [woocommerce/woocommerce-android#10815]
**Describe the bug**
A clear and concise description of what the bug is. Please be as descriptive as possible; issues lacking detail, or for any other reason than to report a bug, may be closed without action.

Open
* Products
* Add product
* Group Product
* Add product to a group 
* Add product

Notice that there is no way to confirm selection unless you guessed that the check mark has the same color as toolbar

Actually, there are two problems:
* A check mark is not visible (but clickable), so basically, for most of people, the feature doesn't work as they don't know how to confirm the selection.
* Scan barcode icon doesn't do anything

**Screenshots**

https://github.com/woocommerce/woocommerce-android/assets/4923871/1a8c34e6-c4dc-47dc-8bff-cc65654d6482

**Comment by dangermattic** [comment]
🚫 Please add a type label (e.g. **type: enhancement**) and a feature label (e.g. **feature: stats**) to this issue.
