### ISSUE TITLE
Blaze: validate campaign requirements before starting the creation

### ISSUE THREAD

**Issue by hichamboushaba** [woocommerce/woocommerce-android#10834]
The campaign creation requires:
1. Selecting an image.
2. Entering the ad's content (title and description)

If one of the two is missing, we should let the user know, and guide them to fix the issue.

**Comment by dangermattic** [comment]
🚫 Please add a type label (e.g. **type: enhancement**) and a feature label (e.g. **feature: stats**) to this issue.
