### ISSUE TITLE
[Tablet Support M2] Navigating in split view leads to hanging loading screen

### ISSUE THREAD

**Issue by lmischner** [woocommerce/woocommerce-android#10861]
**Describe the bug**
When I add another app via split view and then use the backbutton to navigate from order details to the orders list, I get stuck in the shimmering/loading screen.

**To Reproduce**
1. In either portrait or landscape mode
2. In the Woo app, navigate to the Orders list
3. If you want, tap between orders
4. Add another app via split view
5. Use the back button in the app to keep navigating backward
6. Note the shimmering screen

**Screenshots** 
https://github.com/woocommerce/woocommerce-android/assets/103850310/bb32409a-12a7-4c8a-a989-742d9f523096

**Expected behavior**
All content loads 

**Isolating the problem (mark completed items with an [x]):**
- [x] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [X] This bug happens with a default WordPress theme active, or [Storefront](https://woo.com/products/storefront/).
- [X] I can reproduce this bug consistently using the steps above.

**Mobile Environment**
Please include:
- Device: Nexus 7 (via emulator)
- Android version: Android 14.0
- WooCommerce Android version: Better tablet orders M2

**Comment by dangermattic** [comment]
🚫 Please add a type label (e.g. **type: enhancement**) and a feature label (e.g. **feature: stats**) to this issue.
