### ISSUE TITLE
[Tablet Support M2] Searching and creating new order can make it look like store doesn't have orders anymore

### ISSUE THREAD

**Issue by lmischner** [woocommerce/woocommerce-android#10863]
**Describe the bug**
Searching and then editing an order or creating one can lead to a couple of odd outcomes:
1. the order list can show an order that doesn't match with the order details shown
2. the order list can show 0 orders even if the store does have orders

**To Reproduce**
1. Go to orders list for a store that has some orders
2. Search for something that will return a result
3. Use X is search bar to clear search results
4. Edit order in right pane
5. Note that, after refresh, returns the search result from step 2
6. Repeat 2-4, but input search term that will not return a result
7. Note that you see prompt to add a test order since your store "doesn't have" any

**Screenshots**
https://github.com/woocommerce/woocommerce-android/assets/103850310/9a58579d-fb3b-4578-b1bf-e9305e223f3d

**Expected behavior**
X'ing out of search bar results should bring user back to full order list. Even if it doesn't, trying to go back seems odd. Regardless, we shouldn't accurately reflect existing store orders

**Isolating the problem (mark completed items with an [x]):**
- [X] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [X] This bug happens with a default WordPress theme active, or [Storefront](https://woo.com/products/storefront/).
- [X] I can reproduce this bug consistently using the steps above.

**Mobile Environment**
Please include:
- Device: Nexus 7 (via emulator)
- Android version: Android 14.0
- WooCommerce Android version: Better tablet orders M2

**Comment by dangermattic** [comment]
🚫 Please add a type label (e.g. **type: enhancement**) and a feature label (e.g. **feature: stats**) to this issue.

**Comment by malinajirka** [comment]
Fixed
