### ISSUE TITLE
[Tablet Support M2] Issuing a refund doesn't immediately update order status

### ISSUE THREAD

**Issue by lmischner** [woocommerce/woocommerce-android#10864]
**Describe the bug**
Issuing a refund doesn't update the order status in the order list.

**To Reproduce**
1. Go to a completed order
2. Note order status in order list is "Completed"
3. In the order details, complete the issue refund workflow
4. Note order status in order list is still "Completed"
5. Do something to initiate a refresh manually (navigate away and come back to Orders, e.g.)
6. Note order status in order list updates to "Refunded"

**Expected behavior**
Order status should be reflected accurately.

**Isolating the problem (mark completed items with an [x]):**
- [X] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [X] This bug happens with a default WordPress theme active, or [Storefront](https://woo.com/products/storefront/).
- [X] I can reproduce this bug consistently using the steps above.

**Mobile Environment**
Please include:
- Device: Nexus 7 (via emulator)
- Android version: Android 14.0
- WooCommerce Android version: Better tablet orders M2

**Comment by dangermattic** [comment]
🚫 Please add a type label (e.g. **type: enhancement**) and a feature label (e.g. **feature: stats**) to this issue.

**Comment by samiuelson** [comment]
Looks like a general order list refresh issue. The order list is not being updated.

Related issue – https://github.com/woocommerce/woocommerce-android/issues/7166

**Comment by malinajirka** [comment]
Fixed in https://github.com/woocommerce/woocommerce-android/pull/10888
