### ISSUE TITLE
[Tablet Orders M2] Small tablets shouldn't use tablet-view in portrait mode

### ISSUE THREAD

**Issue by lmischner** [woocommerce/woocommerce-android#10860]
**Describe the bug**
On a large tablet, we can keep the new UI introduced in the better tablet orders project regardless of screen orientation because there's enough space to always display the content gracefully. On a smaller tablet, like the Nexus, elements start to overlap or split into multiple lines, making the experience feel clunky and messy.

**To Reproduce**
1. Open the app 
2. Confirm using portrait orientation
3. Navigate to orders screen

**Screenshots**
![image](https://github.com/woocommerce/woocommerce-android/assets/103850310/3e02fae7-bac4-4a1b-9f20-e6449e17961c)

**Expected behavior**
When there isn't enough space to gracefully display the information, use the non-tablet view

**Isolating the problem (mark completed items with an [x]):**
- [x] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [x] This bug happens with a default WordPress theme active, or [Storefront](https://woo.com/products/storefront/).
- [x] I can reproduce this bug consistently using the steps above.

**Mobile Environment**
Please include:
- Device: Nexus 7 (via emulator)
- Android version: Android 14.0
- WooCommerce Android version: Better tablet orders M2

**Comment by dangermattic** [comment]
🚫 Please add a type label (e.g. **type: enhancement**) and a feature label (e.g. **feature: stats**) to this issue.

**Comment by samiuelson** [comment]
Let's adjust margins to take the remaining space by the list pane.
