### ISSUE TITLE
[Tablet Support M3] Layout gets messy on narrow tablet devices

### ISSUE THREAD

**Issue by samiuelson** [woocommerce/woocommerce-android#10868]
![Image](https://github.com/woocommerce/woocommerce-android/assets/4527432/29feb6c5-e4a3-45fc-86e0-06ac56e981a2)

**Comment by dangermattic** [comment]
🚫 Please add a type label (e.g. **type: enhancement**) and a feature label (e.g. **feature: stats**) to this issue.
