### ISSUE TITLE
[Tablet Support M2] Crash on navigating to orders list with 0 orders

### ISSUE THREAD

**Issue by lmischner** [woocommerce/woocommerce-android#10862]
**Describe the bug**
In a new Woo store, if I navigate to the orders list, the app crashes.

**To Reproduce**
1. Create new store or access one without any existing orders
2. Go to the orders screen
3. Crash :( 

**Screenshots**
https://github.com/woocommerce/woocommerce-android/assets/103850310/d3cb43fb-710c-4602-ae66-ece93d61d33a

**Expected behavior**
No crash, navigated to orders list and shown indication that there aren't any existing orders

**Isolating the problem (mark completed items with an [x]):**
- [x] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [x] This bug happens with a default WordPress theme active, or [Storefront](https://woo.com/products/storefront/).
- [x] I can reproduce this bug consistently using the steps above.

**Mobile Environment**
Please include:
10861

**Comment by dangermattic** [comment]
🚫 Please add a type label (e.g. **type: enhancement**) and a feature label (e.g. **feature: stats**) to this issue.

**Comment by malinajirka** [comment]
Fixed
