### ISSUE TITLE
[Tablet Support M2] Order list's details pane displays shimmer effect in case there are no orders (e.g. newly created store)

### ISSUE THREAD

**Issue by samiuelson** [woocommerce/woocommerce-android#10881]

**Comment by dangermattic** [comment]
🚫 Please add a type label (e.g. **type: enhancement**) and a feature label (e.g. **feature: stats**) to this issue.

**Comment by lmischner** [comment]
Adding what I'm assuming is a downstream effect of this: If you navigate to the "Upgrade Now" link and then close out of the resulting in app browser, you get a blank Order Details form.


https://github.com/woocommerce/woocommerce-android/assets/103850310/6fad0677-a2d3-4199-97d2-95a9d9dace41
