### ISSUE TITLE
[Tablet Support M2] Crash: ConcurrentModificationException – ProductImageMap is not thread-safe

### ISSUE THREAD

**Issue by samiuelson** [woocommerce/woocommerce-android#10895]

**Comment by dangermattic** [comment]
🚫 Please add a type label (e.g. **type: enhancement**) and a feature label (e.g. **feature: stats**) to this issue.

**Comment by malinajirka** [comment]
Duplicate of https://github.com/woocommerce/woocommerce-android/issues/10901
