### ISSUE TITLE
Navigation is broken on product reviews.

### ISSUE THREAD

**Issue by kidinov** [woocommerce/woocommerce-android#10906]
**To Reproduce**
* Products
* Product details with reviews 
* Reviews
* Open a review

Notice that there is an endless cycle in navigation and you can not leave

https://github.com/woocommerce/woocommerce-android/assets/4923871/263a127b-ce7f-4645-987c-76bc1d86f7af

**Comment by dangermattic** [comment]
Thanks for reporting! 👍
