### ISSUE TITLE
Pressing back on Order List crashes the app

### ISSUE THREAD

**Issue by malinajirka** [woocommerce/woocommerce-android#10919]
**Describe the bug**
Branch - trunk - 1dc0d4ea5135dba9501f4874d345d3a1fcb606e6

Pressing back on the list of orders gets into an infinite loop and crashes the app - in the single pane layout mode (phone).

Tested on Pixel 8

**To Reproduce**
1. Go to Order List
2. Tap on back

cc @samiuelson  @jd-alexander

**Comment by dangermattic** [comment]
Thanks for reporting! 👍
