### ISSUE TITLE
Tablet - Two Pane Layout - Payment Selection screen remains on the backstack

### ISSUE THREAD

**Issue by malinajirka** [woocommerce/woocommerce-android#10920]
**Describe the bug**
When I create a new order and collect payment, pressing back redirects me back to the payment selection screen.

**To Reproduce**
1. Go to order list
2. Start the order creation flow
3. Add a product or a custom amount
4. Tap on Collect Payment
5. Select Cash
6. Confirm
7. Press back
8. Notice the app navigates you back to the Payment Selection screen

**Screenshots**
[Screen_recording_20240223_215437.webm](https://github.com/woocommerce/woocommerce-android/assets/2261188/0ec04513-a2ef-471e-9310-b2c6eef104a2)

**Expected behavior**
The app should navigate me to the dashboard - the payment selection screen shouldn't appear on the backstack at all.

cc @samiuelson  @jd-alexander

**Comment by dangermattic** [comment]
🚫 Please add a type label (e.g. **type: enhancement**) and a feature label (e.g. **feature: stats**) to this issue.
