### ISSUE TITLE
Add 'Update Stock Status' to Overflow Menu in Product Multi-Selection List

### ISSUE THREAD

**Issue by jd-alexander** [woocommerce/woocommerce-android#10928]
The enhancement involves adding a new menu item, 'Update Stock Status', to the overflow menu accessible in the product multi-selection list view. This update aims to facilitate bulk stock status updates directly from the multi-selection mode, improving efficiency for users managing inventory. Implementation will necessitate modifications to the layout XML files to incorporate the new menu option. Additionally, adjustments to the `ProductListViewModel` may be required to handle the action triggered upon selecting this option. The goal is to streamline the process of updating stock statuses for multiple products, reducing the number of steps and time required to perform this common task.

- **Layout Adjustments**: Update the overflow menu in the layout XML files to include the 'Update Stock Status' item.
- **ViewModel Update**: Extend the `ProductListViewModel` to handle the new action, ensuring that the stock status update process is efficiently managed.
- **User Flow Optimization**: Aim to enhance the user experience by simplifying the inventory management process, allowing for bulk updates of stock statuses with minimal navigation and effort.

**Comment by dangermattic** [comment]
Thanks for reporting! 👍
