### ISSUE TITLE
[Analytics Hub] Show custom message on Sessions card for custom date ranges

### ISSUE THREAD

**Issue by rachelmcr** [woocommerce/woocommerce-android#10946]
When a custom date range is selected, we should display the session card with an alternative message inside it:

> **Session data unavailable**
> Session analytics rely on unique visitor counts not available for custom date ranges.

See design (on the right):

![image](https://github.com/woocommerce/woocommerce-android/assets/8658164/2ca95ac2-e5af-41fa-aa28-7866ef62cfd5)

In the interest of time, if that isn't possible/takes too much to implement: When a custom date range is selected and the sessions card is the only selected card in the analytics hub, we can hide the sessions card and show an empty state (above, left).

Updated design: pe5pgL-4FA-p2#comment-3837

-----

Previous decision: p1708606044423369-slack-C02KUCFCSFP
Related discussions: pe5pgL-1p6-p2 and pe5pgL-1wE-p2

**Comment by dangermattic** [comment]
Thanks for reporting! 👍
