### ISSUE TITLE
[Analytics Hub] Add UI for Product Bundles card

### ISSUE THREAD

**Issue by rachelmcr** [woocommerce/woocommerce-android#10967]
We need to add the UI for an analytics card for the Product Bundles extension. This card should retrieve its data from the new endpoints added in https://github.com/woocommerce/woocommerce-android/issues/10966.

This card should only be visible in the Analytics Hub for stores with the Product Bundles extension active. (Stores without the extension will see it in the Customize Analytics screen but it can't be enabled.)

## Content

- Card title: Bundles
- Metrics:
   - Bundles sold (number of items)
   - Net sales (revenue)
- Percent change from previous period for each metric
- Chart with interval data for each metric
- A list (like on the existing Products card) showing the top 5 bundles sold, including the number sold and net sales for each bundle.
- "See Report" button linking to relevant report in a webview (`path` parameter in URL is `%2Fanalytics%2Fbundles`)

## Design

![Image](https://github.com/woocommerce/woocommerce-android/assets/8658164/de3b189b-117e-43e5-a7eb-19ff8f1c1985)

**Comment by dangermattic** [comment]
Thanks for reporting! 👍
