### ISSUE TITLE
Show attribution info in order details screen

### ISSUE THREAD

**Issue by hichamboushaba** [woocommerce/woocommerce-android#10960]
Show order attribution fields in the order details screen
Internal - pe5sF9-2sD-p2
![image](https://github.com/woocommerce/woocommerce-ios/assets/524475/f832491c-088e-40ce-b902-9da30a0f8ce3)

```[tasklist]
### Tasks
- [ ] https://github.com/woocommerce/woocommerce-android/issues/10961
- [ ] https://github.com/woocommerce/woocommerce-android/issues/10962
- [ ] https://github.com/woocommerce/woocommerce-android/issues/10990
```

**Comment by dangermattic** [comment]
Thanks for reporting! 👍

**Comment by pmusolino** [comment]
@hichamboushaba can we close this issue?

**Comment by hichamboushaba** [comment]
Yes, thank you for the reminder.
