### ISSUE TITLE
[Better Errors] Differentiate invalid credential errors

### ISSUE THREAD

**Issue by Ecarrion** [woocommerce/woocommerce-android#10975]
# Context

Currently, there is not a specific way to know if an error was due to invalid credentials.

However, the server injects a `shake` pattern when an invalid credential error is found.

For the time being, we will use that pattern as a guess for an invalid credential error message.

## Patern

```
document.querySelector('form').classList.add('shake')
```

- [Source]( https://github.com/WordPress/WordPress/blob/master/wp-login.php#L65-L67)
- [iOS Implementation](https://github.com/woocommerce/woocommerce-ios/pull/12230)

# Task

- [ ] Differentiate invalid credential errors from other errors
- [ ] Do not launch the app password tutorial for invalid credential errors.

**Comment by dangermattic** [comment]
Thanks for reporting! 👍
