### ISSUE TITLE
[Better Tablet Products] Add toolbar to Variations Details Fragment

### ISSUE THREAD

**Issue by kidinov** [woocommerce/woocommerce-android#10977]
![Image](https://github.com/woocommerce/woocommerce-android/assets/4923871/932ca06d-c48a-4270-aa9e-418a4e444ff2)

**Comment by dangermattic** [comment]
🚫 Please add a type label (e.g. **type: enhancement**) and a feature label (e.g. **feature: stats**) to this issue.
