### ISSUE TITLE
[Better Tablet Products] Fix margins on some screens

### ISSUE THREAD

**Issue by kidinov** [woocommerce/woocommerce-android#10999]
* Product Settings -> Product Status
* Product slug background
* Product note
* Menu Order
* Add more details

![Image](https://github.com/woocommerce/woocommerce-android/assets/4923871/815218a6-fca5-4192-9ebc-7db09aae8b10)

![Image](https://github.com/woocommerce/woocommerce-android/assets/4923871/c8dae3cc-ab4b-41c8-8969-d977a9756358)

![Image](https://github.com/woocommerce/woocommerce-android/assets/4923871/509b6867-7cd5-4dde-a32b-831b3a82384e)

**Comment by dangermattic** [comment]
Thanks for reporting! 👍
