### ISSUE TITLE
Custom range tab content

### ISSUE THREAD

**Issue by JorgeMucientes** [woocommerce/woocommerce-android#11006]
Display the selected custom range in Stats view following this design for now: 

![Screenshot 2024-03-05 at 13 52 34](https://github.com/woocommerce/woocommerce-android/assets/2663464/6f53a7c8-0db7-419d-acd0-7cb419463074)

**Comment by dangermattic** [comment]
🚫 Please add a type label (e.g. **type: enhancement**) and a feature label (e.g. **feature: stats**) to this issue.
