### ISSUE TITLE
[Better Errors] App Passwords Explanation Mock Up

### ISSUE THREAD

**Issue by Ecarrion** [woocommerce/woocommerce-android#11000]
We need to come up with a UI/UX to explain.

- [ ] Why we couldn't log in to your site
- [ ] How to approve application passwords
- [ ] Buttons to contact support and to continue with the app password login

<img width="469" alt="light" src="https://github.com/woocommerce/woocommerce-ios/assets/562080/1616c436-52c0-4f72-bacc-fc77ec2a9e13">

### Image Resources

![app-password-tutorial-1](https://github.com/woocommerce/woocommerce-ios/assets/562080/ab1c5b81-308d-4491-8a16-20b227d02c41)

**Comment by dangermattic** [comment]
Thanks for reporting! 👍
