### ISSUE TITLE
[Better Tablet Products] In landscape orientation, the Share button is hidden unless you realize you can move the sheet up to access it.

### ISSUE THREAD

**Issue by kidinov** [woocommerce/woocommerce-android#11018]
In landscape orientation, the Share button is hidden unless you realize you can move the sheet up to access it. (Tap “Share” for a product and note you can see the message box, write with AI, and learn more, but you don’t see the Share button until you drag to scroll) Let me know if you’d like a screen grab on this, might be specific to smaller size of Nexus 7

pfoUAQ-iv-p2#comment-260

**Comment by dangermattic** [comment]
🚫 Please add a type label (e.g. **type: enhancement**) and a feature label (e.g. **feature: stats**) to this issue.
