### ISSUE TITLE
[Better Tablet Products] After a new product created, then 1 pane mode is shown on a tablet

### ISSUE THREAD

**Issue by kidinov** [woocommerce/woocommerce-android#11020]

**Comment by dangermattic** [comment]
🚫 Please add a type label (e.g. **type: enhancement**) and a feature label (e.g. **feature: stats**) to this issue.

**Comment by kidinov** [comment]
Seems to be that was fixed already



https://github.com/woocommerce/woocommerce-android/assets/4923871/f63d2ab2-cbb8-4ad5-8c06-9ab05aa94ab6
