### ISSUE TITLE
Product and Customer Filters Across Store Switch in Order List should not persist when switching store

### ISSUE THREAD

**Issue by pmusolino** [woocommerce/woocommerce-android#11036]
An inconsistency has been detected in the order list filter behavior that affects merchant operations.

The Product and Customer filters that we introduced in the order list persist when merchants switch between stores.
This persistence of filters is not in line with the behavior of other existing filters, which are reset after a store change. The major concern here is that these sticky filters can display information that does not exist in the other store or display potentially existing information incorrectly.

Expect behavior: reset the filters when switching stores.

[Recording](https://drive.google.com/file/d/1m2JhKPZizmY7DaMAqmREnGDkJMt5TVGR/view?usp=sharing)

**Comment by dangermattic** [comment]
Thanks for reporting! 👍
