### ISSUE TITLE
[Better Tablet Products] Nav bar is disappearing when you go into the product details and come back

### ISSUE THREAD

**Issue by kidinov** [woocommerce/woocommerce-android#11031]
As noticed by @jd-alexander  (thanks!) https://github.com/woocommerce/woocommerce-android/pull/10996#issuecomment-1981465767 nav bar is disappearing when you go into the product details and come back

**Comment by dangermattic** [comment]
🚫 Please add a type label (e.g. **type: enhancement**) and a feature label (e.g. **feature: stats**) to this issue.
