### ISSUE TITLE
Update public documentation on "How to connect your store"

### ISSUE THREAD

**Issue by pmusolino** [woocommerce/woocommerce-android#11047]
Update our public documentation related to "how to connect your store", since it's outdated and it doesn't include how to connect the store with application passwords. -> https://woo.com/document/android/#connect-to-your-store

**Comment by dangermattic** [comment]
🚫 Please add a type label (e.g. **type: enhancement**) and a feature label (e.g. **feature: stats**) to this issue.

**Comment by JorgeMucientes** [comment]
Closing as [documentation](https://woocommerce.com/document/android/#connect-to-your-store) shows an `Option 2` section explaining login with site credentials
