### ISSUE TITLE
[Tablet Support M2] Analytics "horizontalSizeClass" key has wrong values tracked

### ISSUE THREAD

**Issue by samiuelson** [woocommerce/woocommerce-android#11066]
Wrong implementation in `OrderListViewModel::trackOrderClickEvent`

**Comment by samiuelson** [comment]
Perhaps we could track Android (material design) specific window size class names.

**Comment by dangermattic** [comment]
🚫 Please add a type label (e.g. **type: enhancement**) and a feature label (e.g. **feature: stats**) to this issue.
