### ISSUE TITLE
[Better Tablet Products] Settings -> Reviews have double toolbar

### ISSUE THREAD

**Issue by kidinov** [woocommerce/woocommerce-android#11071]
![Image](https://github.com/woocommerce/woocommerce-android/assets/4923871/7886ad38-bcdb-42c3-97b8-730f294fdaa7)

**Comment by dangermattic** [comment]
🚫 Please add a type label (e.g. **type: enhancement**) and a feature label (e.g. **feature: stats**) to this issue.
