### ISSUE TITLE
Changes to Order Status are not reflected in filtered list

### ISSUE THREAD

**Issue by malinajirka** [woocommerce/woocommerce-android#11078]
**Describe the bug**
User report
```Please work on the app again, the old version of this app was good, when you filter the order status and then select what you want example on hold, if you complete the order, it automatically goes away from the filter orders because it's no more part of it. But your recent update doesn't work like that anymore which is not good. Please work on it.```

**To Reproduce**
1. Go to Order List
2. Apply 'Status: Pending Payment' filter
3. Open an order
4. Change its status to any other status
5. Go back to the list and notice the order is still there even though its status is not `Pending Payment` anymore.

**Expected behavior**
The order should disappear from the filtered list if it doesn't match the filter.

**Comment by dangermattic** [comment]
Thanks for reporting! 👍

**Comment by malinajirka** [comment]
This issue was introduced here https://github.com/wordpress-mobile/WordPress-FluxC-Android/pull/2959
