### ISSUE TITLE
[Better Tablet Products] Detail Pane Occupies Entire Screen on Device Rotation During Search in Landscape Mode

### ISSUE THREAD

**Issue by jd-alexander** [woocommerce/woocommerce-android#11090]
**Describe the bug**
When a user conducts a search on the products screen on a mobile device in landscape mode and the search detail pane is displayed, rotating the device causes the detail pane to occupy the entire screen. This behavior is unexpected and obstructs the user's view of the search results list. Ideally, after rotating the device, the list pane showing search results should occupy the screen instead. 

**To Reproduce**
1. Open the application on a mobile device.
2. Rotate the device to landscape mode.
3. Navigate to the products screen.
4. Perform a search so that the search detail pane is displayed.
5. Rotate the device to portrait mode.
6. Notice that the detail pane occupies the entire screen instead of showing the search results list.

**Expected behavior**
Upon rotating the device to portrait mode after conducting a search in landscape mode with the detail pane displayed, the expectation is that the search results list will occupy the entire screen. This would allow users to easily view and interact with the search results.

**Comment by dangermattic** [comment]
Thanks for reporting! 👍

**Comment by kidinov** [comment]
@jd-alexander 👋

Isn't it the same on the orders? Frankly, I am not sure that the expectation is that search results will occupy the entire screen after rotation. I think it depends on the outcome of the search - if the order/product was found and a user is working with it already, then why would they need to see the search result? If not, then the search result would probably make sense, but we can not know that, so I guess the behavior here should be the same as we have now, when the search is not activated, aka we show the details pane after 2 -> 1 pane transition. Wdyt?

https://github.com/woocommerce/woocommerce-android/assets/4923871/200742fd-4ac2-4ea8-9f94-544691e880e2

**Comment by jd-alexander** [comment]
@kidinov thank you for sharing this perspective. I believe I can share some more details about the issue further as the issue description probably didn't make it clear enough and now that I have revisited it, it is more reproducible. 

If there is no product selected and you do a rotation then you cant press back to go back to the search results. Therefore, I initially thought that we could show the search results in that case. However, it would break functionality for this existing behavior that is actually fine. 

I think the best approach would then be to fix this issue we are having where when no product is selected or available the back functionality doesn't work. 

What do you think?

Check out this video below where pressing back takes me all the way back to the home screen.

https://github.com/woocommerce/woocommerce-android/assets/1509205/c9f0723d-eaec-40c6-9f54-f73c55970091

**Comment by kidinov** [comment]
@jd-alexander Just to confirm with you that my understanding is correct, fixing https://github.com/woocommerce/woocommerce-android/issues/10978 will be good enough in your opinion to fix this issue? Showing "product not selected" after configuration change is not ideal, but more like an edge case and when the back navigation will be fixed won't be a big deal anyway

**Comment by jd-alexander** [comment]
> @jd-alexander Just to confirm with you that my understanding is correct, fixing https://github.com/woocommerce/woocommerce-android/issues/10978 will be good enough in your opinion to fix this issue? 

Yes doing that fix, would actually fix this issue and yes it is an edge case and having the back button functioning as expected would give the user a way to navigate from the flow anyway, therefore the proposed approach can be closed for now. Thanks much for exploring this and linking the relevant issue. Always better to dive deep into these solutions before introducing them to the codebase. If necessary, at least this PR will be available for reference.
