### ISSUE TITLE
[REST API] Add support for WordPress.com account creation as part of Jetpack Setup

### ISSUE THREAD

**Issue by hichamboushaba** [woocommerce/woocommerce-android#11114]
Currently, in the Jetpack Setup flow, we don't support creating new accounts, which is counter-intuitive, as users who are installing Jetpack for the first time will most likely need to create a new account.

Using tracks, we can confirm this: currently, the login step is one of the biggest drops in the Jetpack Setup, as only 22% are able to finish it. From the failures, we can see that `UNKOWN_USER` is responsible for the biggest part of the cases.

###### iOS GH issue: https://github.com/woocommerce/woocommerce-ios/issues/12310

```[tasklist]
### Tasks
- [ ] https://github.com/woocommerce/woocommerce-android/issues/12918
- [ ] https://github.com/woocommerce/woocommerce-android/issues/12921
- [ ] https://github.com/woocommerce/woocommerce-android/issues/12944
```

**Comment by dangermattic** [comment]
🚫 Please add a type label (e.g. **type: enhancement**) and a feature label (e.g. **feature: stats**) to this issue.
