### ISSUE TITLE
Products Bulk Stock Status Landscape Mode UI Issue

### ISSUE THREAD

**Issue by jd-alexander** [woocommerce/woocommerce-android#11138]
**Describe the bug**
When using the app in a Pixel 7 emulator, dialog screens are forcibly shown in landscape mode, even on devices that are primarily used in portrait mode such as phones. This issue leads to a UI that appears broken, particularly noticeable in the toolbar area. The interface elements do not adjust well to the landscape orientation, resulting in a compromised user experience.

**To Reproduce**
1. Open the app in a Pixel 7 emulator in landscape.
2. Navigate to the Products screen and select multiple products.
3. Select Update Stock Status in the menu and notice that the dialog is displayed in landscape mode by default.
4. Observe the UI, especially the toolbar, appearing broken.

**Screenshots**

<img width="1018" alt="Screenshot 2024-03-21 at 8 45 51 PM" src="https://github.com/woocommerce/woocommerce-android/assets/1509205/d7f3a1fe-5cf1-471c-a7c4-4b9e595b637c">

**Expected behavior**
Dialog screens should adapt to the device's orientation. The UI, including the toolbar, should render correctly and remain user-friendly regardless of the orientation, ensuring a consistent and efficient user experience.

**Comment by dangermattic** [comment]
Thanks for reporting! 👍
