### ISSUE TITLE
[Better Tablet Products] Infinite loading

### ISSUE THREAD

**Issue by kidinov** [woocommerce/woocommerce-android#11134]
* Open Product List on Pixel 7 emulator (portrait)
* Open Detail of a product
* Press back
* Change to landscape
* Notice a two pane layout is shown but the product detail never finishes loading

Report by @malinajirka. More detail - p1711023354229269/1711023350.773419-slack-C06C3CZFHGD

**Comment by dangermattic** [comment]
🚫 Please add a type label (e.g. **type: enhancement**) and a feature label (e.g. **feature: stats**) to this issue.
