### ISSUE TITLE
Ensure start date for Blaze campaign is at least the next day from the current day

### ISSUE THREAD

**Issue by JorgeMucientes** [woocommerce/woocommerce-android#11162]
We currently don't apply any restrictions when setting Blaze start date to ensure that the date is valid. In this case we consider a valid date if it is at least one day after the current day. 

Current experience with no restrictions: 

https://github.com/woocommerce/woocommerce-android/assets/2663464/c0e021f9-46d1-4b34-a3f6-fe405b1275d3

**Comment by dangermattic** [comment]
Thanks for reporting! 👍
