### ISSUE TITLE
Product pictures can't be reordered or deleted

### ISSUE THREAD

**Issue by JorgeMucientes** [woocommerce/woocommerce-android#11182]
**Describe the bug**
Users can still drag and drop images around, but they can't "save" the reordering changes applied. What's worse is that you can't even delete images, as there's no way to save/confirm the changes anymore. 

**To Reproduce**
1. Go to product detail screen
2. Click on add photos button at the top
3. Add a few pictures and save the product
4. Open the photo picker again and try rearranging the order of those pictures
5. Check that there's no way to save or confirm the applied reordering

**Screen recording**

https://github.com/woocommerce/woocommerce-android/assets/2663464/68faf9b8-e3ff-49ef-ab1f-4af7b3cdec44

**Comment by dangermattic** [comment]
Thanks for reporting! 👍
