### ISSUE TITLE
Option to save changes in the ProductImagesFragment is not available

### ISSUE THREAD

**Issue by rossanafmenezes** [woocommerce/woocommerce-android#11181]
**Describe the bug**

When you make changes to the images of a product, there used to be an option to indicate you were done with the changes before you could return to the previous screen and save the changes. Now this option is gone and going back to the previous screen undo the changes you made. Adding new images works, but removing or rearranging them does not get saved

**To Reproduce**

1. Go to the products screen
2. open a product that has more than one image
3. drag and rearrange the images
4. Notice there's no "done" button to indicate you are done with the changes (there used to be a checkmark icon. on iOS a 'done' menu option is available. 
5. if you click on the back arrow the changes are undone

**Screenshots**

https://github.com/woocommerce/woocommerce-android/assets/30724184/24664555-00c8-4997-92c5-9d974818c0b6

**Expected behavior**

I would expect to be able to save the changes

It's on Trunk, Android only, iOS works. I was able test it on an older branch and confirmed the checkmark was there but I did not take a screenshot and now I am having issues logging into the emulator. 

Tickets: 
zd-7909692
zd-7907613
zd-7901842

**Comment by dangermattic** [comment]
🚫 Please add a type label (e.g. **type: enhancement**) and a feature label (e.g. **feature: stats**) to this issue.
