### ISSUE TITLE
Widget editor screen

### ISSUE THREAD

**Issue by JorgeMucientes** [woocommerce/woocommerce-android#11196]
Replicate the following UI used in Analytics hub:

![Image](https://github.com/woocommerce/woocommerce-android/assets/2663464/686d65e4-8002-49bd-a021-509263ed6770)

**Comment by dangermattic** [comment]
🚫 Please add a type label (e.g. **type: enhancement**) and a feature label (e.g. **feature: stats**) to this issue.
