### ISSUE TITLE
[Migrate Simple Payments] Tracking

### ISSUE THREAD

**Issue by kidinov** [woocommerce/woocommerce-android#11203]
🆕 simple_payments_migration_sheet_add_custom_amount: When tapping the Add Custom Amount CTA in the migration sheet
Then we can measure how many complete the custom amount with add_custom_amount_done_tapped/order_create_button_tapped/order_creation_success events in the funnel
🆕 simple_payments_migration_sheet_shown: When the migration sheet is shown

**Comment by dangermattic** [comment]
🚫 Please add a type label (e.g. **type: enhancement**) and a feature label (e.g. **feature: stats**) to this issue.
