### ISSUE TITLE
[Tablet Support M3] Product Variation Selector Error

### ISSUE THREAD

**Issue by jd-alexander** [woocommerce/woocommerce-android#11223]
**Describe the bug**
When you select a variation of a product when making an order, the Order Summary does not update. 

**To Reproduce**
1. Go Orders. 
2. Create a new order. 
3. Find a product with variations. 
4. Select a variation. 
5. Close the dialog. 
6. Notice the Order Summary does not update to reflect the changes.

**Screenshots**

[variation-picker_rotated.webm](https://github.com/woocommerce/woocommerce-android/assets/1509205/70e6f593-a1f0-40ee-8a85-d97ba6416006)

**Expected behavior**

The order summary should be updated to reflect the selection.

**Comment by dangermattic** [comment]
🚫 Please add a type label (e.g. **type: enhancement**) and a feature label (e.g. **feature: stats**) to this issue.

**Comment by jd-alexander** [comment]
Seems this issue was reported here https://github.com/woocommerce/woocommerce-android/issues/10867
