### ISSUE TITLE
Order form is dropping second last names unexpectedly

### ISSUE THREAD

**Issue by backwardstruck** [woocommerce/woocommerce-android#11236]
**Describe the Bug**  
When creating a user that has more than one last name, which is common in many countries, and that user is loaded onto a new order, only one of the last names is pulled. If you edit the user, only the last name was saved. The question is whether this is by design or a bug.

For additional information, reference this ticket: [https://a8c.zendesk.com/agent/tickets/7895292](https://a8c.zendesk.com/agent/tickets/7895292) and Slack [discussion](https://a8c.slack.com/archives/C06NC969ZF0/p1711115213546839).  It's not clear why this issue has not been encountered before, suggesting it may not have been reported by customers.

**To Reproduce**  
1. Create a user with more than one last name.
2. Load that user onto a new order.
3. Only one of the last names appears.
4. Edit the user.
5. Only the last name was saved.

**Screenshots**

<img src="https://github.com/woocommerce/woocommerce-android/assets/947561/3369377d-d548-4a2f-8379-286056dafe32" alt="Screenshot_20240322-094247" height="690px" width="auto">
<img src="https://github.com/woocommerce/woocommerce-android/assets/947561/357a1f05-625b-45dc-a064-a463dec3038c" alt="Screenshot_20240322-094308" height="690px" width="auto">
<img src="https://github.com/woocommerce/woocommerce-android/assets/947561/2dd947ac-cbcc-4f1b-b23b-e92e26740dd1" alt="Screenshot_20240322-094329" height="690px" width="auto">

**Expected behavior**  
When creating users with more than one last name and loading those users onto new orders, or editing them, all last names should accurately be saved and displayed.

**Isolating the problem (mark completed items with an [x]):**  
- [ ] This bug occurs with the latest version of WooCommerce Android.  
- [ ] This bug happens consistently using the steps above.

**Comment by dangermattic** [comment]
Thanks for reporting! 👍
