### ISSUE TITLE
Indicate Blaze image ad minimum size restrictions (500x500px) in the native flow

### ISSUE THREAD

**Issue by JorgeMucientes** [woocommerce/woocommerce-android#11275]
After releasing the new Blaze native flow, we noticed some users are facing errors when creating a campaign because the image they are using for the Blaze Ad is not big enough, it must be at least 500x500px or else the backend would return an error when attempting to create the campaign. 
To mitigate this we proposed the following: 
- When the product image is selected, check locally if it meets the 500x500px size requirements and show an error if it doesn't
- From the preview screen show an explanatory text stating the minimum 500x500px size requriement

**Comment by dangermattic** [comment]
Thanks for reporting! 👍
