### ISSUE TITLE
[Dynamic Dashboard] Update Stats card style

### ISSUE THREAD

**Issue by 0nko** [woocommerce/woocommerce-android#11317]
<img width="653" alt="image" src="https://github.com/woocommerce/woocommerce-android/assets/1522856/90bdeceb-3755-45fc-973b-6986189f8611">

**Comment by dangermattic** [comment]
Thanks for reporting! 👍

**Comment by hichamboushaba** [comment]
@0nko same as the other comment, should we make this as a subtask of https://github.com/woocommerce/woocommerce-android/issues/11219?

**Comment by 0nko** [comment]
Yes. I'll move it.
