### ISSUE TITLE
[Dynamic Dashboard] Replace stats tabs with a menu

### ISSUE THREAD

**Issue by 0nko** [woocommerce/woocommerce-android#11316]
<img width="763" alt="image" src="https://github.com/woocommerce/woocommerce-android/assets/1522856/c096c61e-f95d-4802-b605-62a7eb43cd9f">

The date range tabs are replaced with a range label and dropdown menu.

**Comment by dangermattic** [comment]
Thanks for reporting! 👍

**Comment by hichamboushaba** [comment]
@0nko should we make this as a subtask of https://github.com/woocommerce/woocommerce-android/issues/11219?

**Comment by 0nko** [comment]
@hichamboushaba Yeah, I guess it could be 👍
