### ISSUE TITLE
Blaze Campaign Creation Ad Image Picker

### ISSUE THREAD

**Issue by JorgeMucientes** [woocommerce/woocommerce-android#11323]
In the Edit Ad screen we currently don't provide the option for the user to directly pick an image from all the available images for the given product. 

Ideally, we'd like to offer a 4th option in this dialog, so that user can pick directly from the product images:

<img width="300"  src="https://github.com/woocommerce/woocommerce-android/assets/2663464/4f686bc8-28ee-472a-b2c8-0278a5604363">

**Comment by dangermattic** [comment]
Thanks for reporting! 👍
