### ISSUE TITLE
Blaze Budget Screen Redesign

### ISSUE THREAD

**Issue by JorgeMucientes** [woocommerce/woocommerce-android#11322]
**To be tackled as part of Blaze i4 Project**

During the User Flow Review session: pe5sF9-2Bb-p2 there was a lot of discussion revolving the current budget screen: 

<img width="200"  src="https://github.com/woocommerce/woocommerce-android/assets/2663464/56362a90-c046-4032-a4f2-24c6ba3b822d">

This design presents a number of issues. Following are the suggestions shared during the session: 

- It seems daily spending should be highlighted more. It was discussed that this could potentially be the most relevant number in the screen. Specially if, in the future, we want to support “Evergreen” (aka campaigns with no end date) campaigns.
- Campaign reach/impressions seem to also be one of the most relevant figures on the screen and are not highlighted enough.
- The current design doesn't support `Evergreen` campaigns (campaigns with no end date)

When we tackle i4 we will work alongside Joe Keenan to restructure the screen data.

**Comment by dangermattic** [comment]
🚫 Please add a type label (e.g. **type: enhancement**) and a feature label (e.g. **feature: stats**) to this issue.

**Comment by JorgeMucientes** [comment]
This issue will be tackled as part of this other one: https://github.com/woocommerce/woocommerce-android/issues/12248 where we add support for Evergreen campaigns

**Comment by JorgeMucientes** [comment]
Closing as it is duplicated to this other issue: https://github.com/woocommerce/woocommerce-android/issues/12445
