### ISSUE TITLE
Blaze i3 Quick Enhancements

### ISSUE THREAD

**Issue by JorgeMucientes** [woocommerce/woocommerce-android#11321]
After the user flow review session, a lot of good feedback came up. Full context here: pe5sF9-2Bb-p2

This issue summarizes a list of small changes that can be applied to the flow and that might have a significant impact. 
Bigger effort changes have been added to other GH issues and will be deferred to Blaze i4 Project. 

The small task added to this GHG issue can be tackled bit by bit while we work on other projects. We don't plan to allocate specific team effort for these as they should be 1h-2h changes at most. 

```[tasklist]
### Quick Enhancements
- [x] Intro screen small changes: Remove purple flames, explain what the $5 USD budget is (daily,weekly,total, etc)
- [x] Preview Screen: Add a new copy below the budget section: `Audience`
- [x] Preview Screen: Add a label on the ad preview specifying if the used content for the ad was generated by AI. Hide this label as soon as the user edits the content manually
- [x] Small redesign to the Blaze view inside My Store tab: Thd2rdNU8zSaLkyKZGsOSn-fi-77_29558 This will be tackled as part of the dynamic dashboard project
- [x] Align Blaze statuses in all platforms. Both iOS and Android should have the exact same statuses as the web displays.
- [x] Campaign displayed in the Blaze card is not the most recently created one.
- [x] Check Jetpack connection and hide Blaze for Jetpack CP sites
```

**Comment by dangermattic** [comment]
Thanks for reporting! 👍

**Comment by hafizrahman** [comment]
Hi @JorgeMucientes ! I'm looking through the enhancement items and this one stumped me:

> Preview Screen: Add a new copy below the budget section: Audience with in info icon. Tapping on the info icon will display an informative bottom sheet explaining what the audience is

My Preview Screen does not show Audience info icon, where can I find it? This is what I see:
| | |
|-|-|
|![Screenshot_20240619_180134](https://github.com/woocommerce/woocommerce-android/assets/266376/7cf58441-3be0-40a1-b6e9-711911f536a3) | ![Screenshot_20240619_180123](https://github.com/woocommerce/woocommerce-android/assets/266376/f25b56a0-d8c7-4892-ae7b-04951c03fb82) |

I also searched for "Audience" in the p2 post you linked to but found no result.
