### ISSUE TITLE
Setup WCAndroid project with WearOS module

### ISSUE THREAD

**Issue by ThomazFB** [woocommerce/woocommerce-android#11333]
The current code base for the Woo mobile app can support a separate section for the Watch app code. For the Android case, we should be able to create a module inside the WCAndroid project.

The following things need to be configured for this project:

### Build configs
- Package and APK signing matching the Phone (required to allow Phone-to-Watch connection)
- Build Flavors / Variants (Vanilla and Wasabi with the same package pattern)
- ProGuard and Lint configurations
- Android Manifest configuration

###  Libraries and Dependencies
- Hilt and Dagger
- Compose
- WearOS libraries
- DataStore libraries

### Architecture support
- Dependency Injection modules configured
- Data Store declaration and injection configured
- Coroutines scope and injection configured
- Navigation through Compose

### Wear support
- Phone-to-watch Service declaration and configuration
- Watch-to-phone Service declaration and configuration
- Default complication setup
- Default tile setup

**Comment by dangermattic** [comment]
Thanks for reporting! 👍
