### ISSUE TITLE
Introduce My Store screen

### ISSUE THREAD

**Issue by ThomazFB** [woocommerce/woocommerce-android#11338]
When the user opens the Watch app with the Store already configured, the My Store screen should be the app's landing page. 

This task should introduce the UI elements to present the My Store data correctly. The charts displayed in this design draft should be ignored, instead, we will approach the My Store section by displaying the same data we make available through the Woo widget.

![Image](https://github.com/woocommerce/woocommerce-android/assets/5920403/1d55bf7f-bfc7-4a6b-868d-5bafa8fd8e48)

![Image](https://github.com/woocommerce/woocommerce-ios/assets/5920403/d5237928-a209-4fe8-ad51-51e9636d0de0)

```[tasklist]
### Tasks
- [x] Introduce My Store screen with the Today's Revenue, Visitors, Orders and Conversion rate
- [x] Introduce UI Icons, gradient and colors
```

**Comment by dangermattic** [comment]
Thanks for reporting! 👍
