### ISSUE TITLE
Introduce Phone sync screen

### ISSUE THREAD

**Issue by ThomazFB** [woocommerce/woocommerce-android#11335]
When the user opens the WearOS app, we should be able to start a sync with the user's phone to fetch the Store Credentials.

This task is focused on introducing the UI that will be displayed during the sync.

![Image](https://github.com/woocommerce/woocommerce-android/assets/5920403/21edb2cc-e861-493c-b569-682b11670168)

```[tasklist]
### Tasks
- [x] Create Compose views for the pairing and waiting views
- [x] Create navigation route between the two views based on events
```

**Comment by dangermattic** [comment]
Thanks for reporting! 👍
