### ISSUE TITLE
Configure Watch app Theme, Icons and Colors

### ISSUE THREAD

**Issue by ThomazFB** [woocommerce/woocommerce-android#11334]
The WearOS app should follow the same theme, icons, and colors convention as the mobile app. We should configure the Wear module with the following:

- App icon
- App splash screen w/ Icon
- Dedicated compose Theme for Wear
- Dedicated Color scheme for Wear
- Dedicated Typography for Wear

**Comment by dangermattic** [comment]
Thanks for reporting! 👍
