### ISSUE TITLE
Introduce complications and tile support

### ISSUE THREAD

**Issue by ThomazFB** [woocommerce/woocommerce-android#11345]
We should allow our watch app to be accessible from a watch face complication. It should be the app icon and behave as the launcher.

![Image](https://github.com/woocommerce/woocommerce-android/assets/5920403/ffe05679-28f9-45db-86ef-e7282904418a)

```[tasklist]
### Tasks
- [x] Register the complication service/declaration in the Watch app
- [x] Configure the complication with the Woo logo and purple background
```

**Comment by dangermattic** [comment]
Thanks for reporting! 👍
