### ISSUE TITLE
[Dynamic Dashboard] Common logic to hide unavailable cards

### ISSUE THREAD

**Issue by hichamboushaba** [woocommerce/woocommerce-android#11359]
Some cards can be unavailable for adding, and therefore should be **hidden from the dashboard** and marked as unavailable in **dashboard settings**. These cards are:

- Performance and Top Performers cards: they should be hidden when the store doesn't have any stats, and they should be replaced by an empty view.
- Onboarding card: it should be hidden when the onboarding was completed.
- Blaze card: it should be hidden when the store doesn't meet the requirements.

**Comment by dangermattic** [comment]
Thanks for reporting! 👍

**Comment by hichamboushaba** [comment]
I re-opened this ticket @0nko, I still need to implement logic for Blaze and the Onboarding card.

**Comment by 0nko** [comment]
Oops, sorry.
