### ISSUE TITLE
Update Blaze image min size restrictions from 600x600 to 400x400px

### ISSUE THREAD

**Issue by JorgeMucientes** [woocommerce/woocommerce-android#11367]
The API will now handle upscaling the image when needed if the uploaded image is smaller than 600x600px but larger than 400x400px. 

The goal is to unblock users when creating Blaze ads, that have smaller product images. Full context here: p1713450773231259/1712831081.385859-slack-C069RG07W6S

**Comment by dangermattic** [comment]
Thanks for reporting! 👍
