### ISSUE TITLE
Add info about device registered for notification to App logs 

### ISSUE THREAD

**Issue by rossanafmenezes** [woocommerce/woocommerce-android#11364]
Context: p1713451172151829-slack-C06NC969ZF0

We do see a lot of tickets from users complaining they are not getting order notifications. The usual first step is to check the Jetpack connection. If everything looks good it would be helpful to know if the device is registered for push notifications or not. HEs won't have access to the debug mode of the app easily to check for the FCM Token information. So having a tracker in the logs letting us know if the device is registered or not could help.

**Comment by dangermattic** [comment]
🚫 Please add a type label (e.g. **type: enhancement**) and a feature label (e.g. **feature: stats**) to this issue.
