### ISSUE TITLE
Adding variation by scanning a barcode not working

### ISSUE THREAD

**Issue by samiuelson** [woocommerce/woocommerce-android#11379]
**Describe the bug**
`CreateOrderItem` looks for product only on local DB and fails in case the product is not present on the device. We should fetch the product from the backend as a fallback.

**To Reproduce**
1. Fresh install the app – products are not synced yet.
2. Go to Orders and click Scan Barcode icon
3. Scan barcode of variation item
4. Notice it doesn't get added to the order

**Expected behavior**
Item should be added to the order.

**Comment by dangermattic** [comment]
🚫 Please add a type label (e.g. **type: enhancement**) and a feature label (e.g. **feature: stats**) to this issue.
