### ISSUE TITLE
Variation name is not displayed after adding to an order

### ISSUE THREAD

**Issue by samiuelson** [woocommerce/woocommerce-android#11381]
When variation is added to an order it's represented as a product card with the title being the name of the parent product. It's impossible to identify the variation in the items list by name.

We should display a subtitle like in the iOS app to show variation attributes:
<img src=https://github.com/woocommerce/woocommerce-android/assets/4527432/02948bba-ccf2-4cc9-985e-df66cd414e41 width=320/>

**Comment by dangermattic** [comment]
🚫 Please add a type label (e.g. **type: enhancement**) and a feature label (e.g. **feature: stats**) to this issue.
