### ISSUE TITLE
Add shipping methods tracks M2

### ISSUE THREAD

**Issue by atorresveiga** [woocommerce/woocommerce-android#11397]
- [x] Update the event `order_creation_success`. Update the event to include the custom property `shipping_lines_count` to track the number of shipping lines within that order
- [x] Update the event `order_shipping_method_add`. Update the event to include the custom property `shipping_lines_count` to track the number of shipping lines within that order
- [ ] Add the event `order_details_shipping_methods_shown` triggered in the order details screen when the screen is displaying the shipping lines section . Add the custom property `shipping_lines_count` to track the number of shipping lines within that order

**Comment by dangermattic** [comment]
Thanks for reporting! 👍
