### ISSUE TITLE
UI to display multiple shipping lines Order Create/Edit

### ISSUE THREAD

**Issue by atorresveiga** [woocommerce/woocommerce-android#11393]
This task is about to updating the UI to being able to display multiple shipping lines.

We should:

- [x] Display the order's shipping lines in a list inside the shipping card
- [x] Add a pencil icon at the end edge of the list item to indicate that the item is editable. Pressing on the item should navigate to the Shipping screen with the selected shipping values.
- [x] Add a shipping total section to the expandable order total section with the displaying the total shipping cost (sum of each individual shipping line)

![Image](https://github.com/woocommerce/woocommerce-android/assets/18119390/ba2b44c2-b132-4ca0-a1a3-e0796f919a84)

**Comment by dangermattic** [comment]
Thanks for reporting! 👍
