### ISSUE TITLE
UI to display multiple shipping lines Order Details

### ISSUE THREAD

**Issue by atorresveiga** [woocommerce/woocommerce-android#11394]
This task is to display the list of shipping lines in the order details screen

<img width="300" src="https://github.com/woocommerce/woocommerce-android/assets/18119390/c84a73bb-5fac-46c4-969f-aa4b5d389000" />

More context about the design p1714405254754749/1714158814.179029-slack-C02KUCFCSFP

**Comment by dangermattic** [comment]
Thanks for reporting! 👍
