### ISSUE TITLE
Sound when first element change

### ISSUE THREAD

**Issue by franc3sc0s92** [woocommerce/woocommerce-android#1139]
i'm work on woocommerce-android open source.- i'm just add a function that refresh the fragmentlist(orderlist) only 1 minuts. I want now to notify with a sound, when the 1^ row of the old-list is different to the 1^ element of the refreshed list. Than i want also to delete the layout of refresh, but this is an other problem. Thanks

kotlin

 inner class RefreshRunnable : Runnable {
        override fun run() {
            presenter.loadOrders(orderStatusFilter, forceRefresh = true)
            searchHandler.postDelayed(this, AUTO_REFRESH_DELAY)
        }`
`

Now, with refresh_delay to 1 minuts the function work but don't consider the changement.

**Comment by astralbodies** [comment]
Hiya @franc3sc0s92! Unfortunately we don't have the capacity to help with code-level issues that aren't directly related to fixing bugs or implementing features that are on the roadmap for the application.

This issues does feel more like something you could reach out to general Android support groups, like StackExchange and Android Developer Forums.
