### ISSUE TITLE
[Dynamic Dashboard] Tracking

### ISSUE THREAD

**Issue by hichamboushaba** [woocommerce/woocommerce-android#11434]
Event name | Properties | Triggers
-- | -- | --
*_dynamic_dashboard_edit_layout_button_tapped |   | When the user taps the button to edit the dashboard layout
*_dynamic_dashboard_hide_card_tapped | type: top_performers \| performance \| blaze \| store_setup | When the user taps on the Hide button in the ellipsis menu of any dashboard card
~*_dynamic_dashboard_editor_reorder_card~ | type: top_performers \| performance \| blaze \| store_setup | When the user changes the order of a card in the layout editor.
~*_dynamic_dashboard_editor_show_card~ | type: top_performers \| performance \| blaze \| store_setup | When the user taps the button to include a card on the dashboard in the layout editor.
~*_dynamic_dashboard_editor_hide_card~ | type: top_performers \| performance \| blaze \| store_setup | When the user taps the button to exclude a card from the dashboard in the layout editor.
*_dynamic_dashboard_editor_save_tapped | cards: comma-separated list of section names. The list should be sorted ASC. | When the user taps the Save button to in the layout editor.
*_dynamic_dashboard_card_retry_tapped | type: top_performers \| performance \| blaze \| store_setup | When the user taps the Retry button on the error state view of any dashboard card.

**Comment by dangermattic** [comment]
🚫 Please add a type label (e.g. **type: enhancement**) and a feature label (e.g. **feature: stats**) to this issue.
