### ISSUE TITLE
[Dynamic Dashboard] M1 bugs

### ISSUE THREAD

**Issue by hichamboushaba** [woocommerce/woocommerce-android#11468]
- [x] App crashes upon tapping “View all tasks” button in the onboarding card when no tasks are loaded.
- [x] Inconsistent button titles between stats and top performers.
- [x] Wrong title for the top performers card..
- [x] Wrong title for the onboarding card.
- [x] Error view text is unreadable in dark mode.
- [x] Wrong title for the widget editor screen.

**Comment by dangermattic** [comment]
Thanks for reporting! 👍
