### ISSUE TITLE
[Woo POS] Handling Different Navigation Patterns - Exploration

### ISSUE THREAD

**Issue by kidinov** [woocommerce/woocommerce-android#11496]
What navigation pattern will we use? What are downside or limitations of using this pattern? 

Will it prevent us from navigating from/to the existing part of the codebase - What are the limitations? Are there workarounds?

And similar questions.

<img src="https://github.com/woocommerce/woocommerce-android/assets/2261188/b8628755-7f56-47f1-be5c-a2de87ad83bc" width="250px" />

p1715182330954929-slack-C070SJRA8DP

**Comment by dangermattic** [comment]
🚫 Please add a type label (e.g. **type: enhancement**) and a feature label (e.g. **feature: stats**) to this issue.

**Comment by kidinov** [comment]
Discussions - pfoUAQ-Dr-p2
