### ISSUE TITLE
[Woo POS] Test if `IsWooPosEnabled` cached result needs to be invalidated, e.g. after switching site in the app

### ISSUE THREAD

**Issue by samiuelson** [woocommerce/woocommerce-android#11520]

**Comment by dangermattic** [comment]
🚫 Please add a type label (e.g. **type: enhancement**) and a feature label (e.g. **feature: stats**) to this issue.

**Comment by kidinov** [comment]
Can confirm that switching site shows "cached" result so should be addressed
