### ISSUE TITLE
Card Reader Code - Exploration

### ISSUE THREAD

**Issue by kidinov** [woocommerce/woocommerce-android#11529]
Which parts can we re-use? 
Will we need to change the current structure?
 - how?
 - what are our options?
 - what are pros and cons of these options?

Do we have to disable other supported card readers? Can we enable the POS entry point to US only?
How do we disable the Stripe Extension?
....

Make sure to check the iOS counter-part and the discussions there - pdfdoF-51h-p2

**Comment by dangermattic** [comment]
🚫 Please add a type label (e.g. **type: enhancement**) and a feature label (e.g. **feature: stats**) to this issue.

**Comment by iamgabrielma** [comment]
Closing this one as part of M1's wrap-up.
