### ISSUE TITLE
[Woo POS] Add "new" red badge, change icon and change position for the POS button in the "more" screen

### ISSUE THREAD

**Issue by kidinov** [woocommerce/woocommerce-android#11545]
p91TBi-beb-p2

![Image](https://github.com/woocommerce/woocommerce-android/assets/4923871/525cb5e2-cff6-4ab7-b093-310e62990972)

**Comment by dangermattic** [comment]
🚫 Please add a type label (e.g. **type: enhancement**) and a feature label (e.g. **feature: stats**) to this issue.
