### ISSUE TITLE
Dynamic Dashboard: The performance card shows visitor stats for custom range of length longer than 1 day

### ISSUE THREAD

**Issue by itsmeichigo** [woocommerce/woocommerce-android#11546]
**Describe the bug**
When switching between different time ranges on the performance card, then switch to custom range, the visitor stats is displayed even though the range length is longer than 1 day.

**To Reproduce**
1. Log in to the app and enable Performance card on the My Store screen.
2. Switch to a non-custom range time range.
3. Then switch to a custom range.
4. Notice that a visitor stat is display on top of the redacted view.

**Screenshots**
<img src="https://github.com/woocommerce/woocommerce-android/assets/5533851/8154257b-8137-4107-9d8d-0cdf05b3571e" width=320 />

**Expected behavior**
Visitor stats should be hidden for custom range of length longer than 1 day.

**Comment by dangermattic** [comment]
Thanks for reporting! 👍
