### ISSUE TITLE
Resolve Discrepancies in Blaze Card Visibility with Legacy Jetpack Versions

### ISSUE THREAD

**Issue by pmusolino** [woocommerce/woocommerce-android#11568]
**Description:**

I've identified a critical issue affecting the visibility of the Blaze card, specifically when interacting with stores running on outdated Jetpack versions.

**Issue Summary:**

After the initial login to a store via the mobile app, the Blaze card displays as expected. However, upon relaunching the app, the Blaze card becomes hidden as if the store is no longer eligible to display it.

**Investigation Findings:**

- The display logic for the Blaze card depends on multiple properties, including `can_blaze`.
- The `can_blaze` property is expected from two endpoints: `me/sites` (post-login) and `sites/:id` (app startup).
- On the first app launch, `sites/:id` isn't called since `me/sites` provides all necessary information. However, subsequent launches rely on `sites/:id`.
- Testing revealed that `sites/:id` does not return the `can_blaze` property for sites with Jetpack versions older than 12.0.

**Impact:**
Users with Jetpack versions prior to 12.0 do not see the Blaze card in the app, potentially missing out on its features.

**Potential Solutions:**
1. Use the `can_blaze` property from `me/sites`, store it locally, and rely on this stored value.
2. Display an error on the Blaze card for users with Jetpack versions older than 12.0.
3. Do not display the Blaze card at all but ensure the Jetpack version is checked to prevent discrepancies during the app's initial launch or store switching.

**Preferred Solution:**
The first solution is preferred, as it would allow users with older Jetpack versions to access the Blaze card features, considering that version 12.0 of Jetpack was released approximately a year ago.

Extra info here: pe5sF9-2Gh

**Comment by dangermattic** [comment]
Thanks for reporting! 👍

**Comment by JorgeMucientes** [comment]
Closing in favor of this other agreed solution to the problem: https://github.com/woocommerce/woocommerce-android/issues/11683
