### ISSUE TITLE
[Payment Method Improvements] Update change due based on user input

### ISSUE THREAD

**Issue by backwardstruck** [woocommerce/woocommerce-android#11584]
Persist value in case user goes back exactly one screen to the payment method screen. So that we maintain the entered value if they go to payment method selection and back to cash payments. 
```[tasklist]
### Tasks
- [x] Update change due based on user input
- [x] Do we want to persist the value in case user goes back exactly one screen to the payment method screen?
```

**Comment by dangermattic** [comment]
Thanks for reporting! 👍
