### ISSUE TITLE
[Payment Method Improvements] Suggested changes from previous PR: https://github.com/woocommerce/woocommerce-android/pull/11570

### ISSUE THREAD

**Issue by backwardstruck** [woocommerce/woocommerce-android#11592]
Suggested changes from previous PR:

Have you considered using WCOutlinedTypedTextField the same as they do in OrderCreateEditProductDiscountScreen:https://github.com/woocommerce/woocommerce-android/pull/11570/files#r1616059600

The text color is wrong in the dark mode (it should be white). See WCColoredButton

It looks like it's not scrollable so a user can not reach the bottom of the screen if the keyboard is open

Background is not consistent with the rest of the screens
```[tasklist]
### Tasks
- [ ] https://github.com/woocommerce/woocommerce-android/issues/11619
```

**Comment by dangermattic** [comment]
Thanks for reporting! 👍
