### ISSUE TITLE
The app shows it's not a Woo store, but it is

### ISSUE THREAD

**Issue by kidinov** [woocommerce/woocommerce-android#11595]
The store https://anotherpaymentssite.wpcomstaging.com/shop/ shows:

![image](https://github.com/woocommerce/woocommerce-android/assets/4923871/235a191b-cea9-4528-a138-2b9d4954714f)

**Comment by dangermattic** [comment]
🚫 Please add a type label (e.g. **type: enhancement**) and a feature label (e.g. **feature: stats**) to this issue.

**Comment by hichamboushaba** [comment]
@kidinov this pfoUAQ-da-p2#comment-191 might be helpful in investigating the cause
