### ISSUE TITLE
M1 design issues detected

### ISSUE THREAD

**Issue by atorresveiga** [woocommerce/woocommerce-android#11603]
This task is for solving some design issues detected during the beta testing of M1

- [x] The font style should be `bold` in the Add shipping screen
- [x] The Remove shipping from order should be red and appear on top of the Add Shipping button
- [x] Change beetwen Add Shipping or Edit Shipping depending on the flow

**Comment by dangermattic** [comment]
🚫 Please add a type label (e.g. **type: enhancement**) and a feature label (e.g. **feature: stats**) to this issue.
