### ISSUE TITLE
[Payment Method Improvements] Background is not consistent with the rest of the screens

### ISSUE THREAD

**Issue by backwardstruck** [woocommerce/woocommerce-android#11619]
See discussion here around theming:
https://a8c.slack.com/archives/C6H8C3G23/p1716936063560139

The idea would be to apply a background of `MaterialTheme.colors.surface` to the root component of the screen, instead of using `WooThemeWithBackground`

**Comment by dangermattic** [comment]
Thanks for reporting! 👍

**Comment by backwardstruck** [comment]
Still having issues making this work 😢

**Comment by backwardstruck** [comment]
For future reference, you need to use `WooThemeWithBackground` AND `backgroundColor = MaterialTheme.colors.surface`
