### ISSUE TITLE
[Payment Method Improvements] Remove FF and related old code

### ISSUE THREAD

**Issue by backwardstruck** [woocommerce/woocommerce-android#11625]
As discussed here:

https://github.com/woocommerce/woocommerce-android/pull/11607#pullrequestreview-2088134563

...remove feature flag, OtherPaymentMethodsEnabled class and all the "old" cash collection code - dialog/tests and so on in the following PR (can be merged to the next release)

**Comment by dangermattic** [comment]
🚫 Please add a type label (e.g. **type: enhancement**) and a feature label (e.g. **feature: stats**) to this issue.
