### ISSUE TITLE
[Woo POS] Consider changing (or skipping) payment success dialog as it has "send receipt" and "show receipts" buttons

### ISSUE THREAD

**Issue by kidinov** [woocommerce/woocommerce-android#11628]
![Image](https://github.com/woocommerce/woocommerce-android/assets/947561/56598c61-b8e3-49d4-99bb-e8dbddcf8990)

**Comment by dangermattic** [comment]
🚫 Please add a type label (e.g. **type: enhancement**) and a feature label (e.g. **feature: stats**) to this issue.

**Comment by samiuelson** [comment]
Marked as blocked, because we don't have clarity if it should be done at the moment.

**Comment by kidinov** [comment]
After the discussion we decided to remove the successful payment dialog and show directly the full screen success screen

p1722869226576729-slack-C070SJRA8DP
