### ISSUE TITLE
Design recommendations

### ISSUE THREAD

**Issue by atorresveiga** [woocommerce/woocommerce-android#11637]
This task is to implement design adjustments from the design review
>  - I think we should show the banner above the total section – but we should auto-close the total section when the “Add shipping” sheet is shown. This way we avoid what’s happening in your second image. Showing it on top of the Collect Payment button would block access to it, and potentially cause accidental taps if we make the banner auto-hide.

> - Can you please use the font sizes, spacing, corner radius, colours, etc. [from these banners](https://www.figma.com/design/uycU7BYzmc3vLKX0cuHLNk/Migrate-simple-payments-to-order-creation?node-id=59-34615&t=ygaFCKzohHvp4ZvR-11)? I spent a bit of time getting the balance of elements right for those (and we never ended up using them :sweat_smile:).

**Comment by dangermattic** [comment]
🚫 Please add a type label (e.g. **type: enhancement**) and a feature label (e.g. **feature: stats**) to this issue.
