### ISSUE TITLE
Error message not showing in dark mode

### ISSUE THREAD

**Issue by rossanafmenezes** [woocommerce/woocommerce-android#11646]
**Describe the bug**

The login error dialog for the application password login does not show the error in dark mode.
I'm not sure how to trigger it, so I was not able to reproduce, but three different users sent screenshots with the same issue. 

Context: p1717186565994379-slack-C6H8C3G23

**Screenshots**

<img width="314" src=https://github.com/woocommerce/woocommerce-android/assets/30724184/2ce68301-2e76-48b5-8f2a-337798a10b8e)>

**Expected behaviour**

The light mode shows the error and the preview of the error dialog composable from LoginSiteCredentialsScreen.kt also shows the text with relatively good contrast

<img width="314" alt="Screenshot 2024-06-03 at 6 58 21 AM" src="https://github.com/woocommerce/woocommerce-android/assets/30724184/73aaad41-cd21-4080-906a-6c00a94c647e">

**Comment by dangermattic** [comment]
🚫 Please add a type label (e.g. **type: enhancement**) and a feature label (e.g. **feature: stats**) to this issue.
