### ISSUE TITLE
Intermittent Failures with Application Passwords Login

### ISSUE THREAD

**Issue by hichamboushaba** [woocommerce/woocommerce-android#11649]
During some tests, I found out that signing in with Application Passwords fails randomly where the app will take the user to the sign-in screen after finishing:

https://github.com/woocommerce/woocommerce-android/assets/1657201/6ca68686-fcf3-4354-b358-e5b7ae29ff21

To reproduce:
1. Sign in using Application Passwords.
2. Notice the app will show the prologue after finishing.

You might need to do the test multiple times for it to happen, as it's caused by a race condition.

**Comment by dangermattic** [comment]
Thanks for reporting! 👍

**Comment by hichamboushaba** [comment]
The cause of the issue is that the `SelectedSite` class is not thread safe, and with the change to make tracking done on a background thread in https://github.com/woocommerce/woocommerce-android/pull/11293, we increased the chances of having a race condition where the app will clear the selected site's ID just after sign in, and this happens in the following order:
1. After signing, the app will track this here https://github.com/woocommerce/woocommerce-android/blob/65b6cf1ce2eef081a47167d23ab8819472395669/WooCommerce/src/main/kotlin/com/woocommerce/android/ui/login/sitecredentials/LoginSiteCredentialsViewModel.kt#L390
2. Then we will save the site here https://github.com/woocommerce/woocommerce-android/blob/65b6cf1ce2eef081a47167d23ab8819472395669/WooCommerce/src/main/kotlin/com/woocommerce/android/ui/login/sitecredentials/LoginSiteCredentialsViewModel.kt#L393
3. The analytics call will happen on a separate thread, and it will call `SelectedSite#get` here: https://github.com/woocommerce/woocommerce-android/blob/7140cea3f54ebbfab4fc7d9c6168339e476942fd/WooCommerce/src/main/kotlin/com/woocommerce/android/analytics/AnalyticsTracker.kt#L118
4. Now when the race condition happens, the `get` call will be made before the site is saved, but due to the parallelism, when we reach the this check, the condition will be true: https://github.com/woocommerce/woocommerce-android/blob/7380fe366ac2730432c917a76595c1ad9a98f770/WooCommerce/src/main/kotlin/com/woocommerce/android/tools/SelectedSite.kt#L74-L76
5. The selected site's ID was removed now, so we are back to square 0, and the user has to sign in again.
