### ISSUE TITLE
[Woo POS] Implement skeleton of the i3 of the wireframes

### ISSUE THREAD

**Issue by kidinov** [woocommerce/woocommerce-android#11644]
![Image](https://github.com/woocommerce/woocommerce-android/assets/4923871/55ad7915-0c9a-460e-8c3c-f05c8d192890)

**Comment by dangermattic** [comment]
🚫 Please add a type label (e.g. **type: enhancement**) and a feature label (e.g. **feature: stats**) to this issue.
