### ISSUE TITLE
Shipment Tracking: Crash adding shipment tracking when device is set to language other than EN-US

### ISSUE THREAD

**Issue by rachelmcr** [woocommerce/woocommerce-android#1164]
**Describe the bug**

When my device is set to a language other than US English (EN-US), trying to add shipment tracking causes the app to crash.

The app can crash at two points:

1. If I tap the "Date shipped" field while adding the tracking.
2. When I tap "Add" after entering shipment details (if I don't tap the date field).

**To Reproduce**
1. Set your device language to something other than US English (e.g. UK English, Spanish).
2. Go to Orders.
3. Select an order with the Processing status.
4. Select Fulfill Order.
5. Select Add Tracking.
6. Tap on the date under "Date shipped" on the Add Tracking screen. Result: Crash.
7. Reopen the app and try to add tracking again. Enter a provider and tracking number and tap "Add" (without changing the date). Result: Crash.

**Expected behavior**

When I tap the "Date shipped" field, I expect a date picker to open. If I don't tap that field, I expect to be able to add shipment tracking with the selected date and other details I've entered.

Everything works as expected when the device is set to US English.

**Isolating the problem (mark completed items with an [x]):**
- [x] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [x] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [x] I can reproduce this bug consistently using the steps above.

**Mobile Environment**
Please include:
- Device: moto e5 play
- Android version: 8.1.0
- WooCommerce Android version: 2.1-rc-1

**Comment by nbradbury** [comment]
Fix is good :shipit:

**Comment by AmandaRiu** [comment]
Issue has been fixed and merged into the `release/2.1` branch.
