### ISSUE TITLE
[Payment Method Improvements] Bug: Fix pre-filled in value 

### ISSUE THREAD

**Issue by backwardstruck** [woocommerce/woocommerce-android#11662]
Reported during testing:

"The first time I went to the screen, I thought the pre-filled in value was just ghost text, so I was surprised that when I started typing, the “ghost value” wasn’t replaced, just added to. I like the fact that it’s prepopulated in case I am receiving exact change but if I’m not, then I suddenly have a lot of taps ahead of me to delete the existing number."

**Comment by dangermattic** [comment]
Thanks for reporting! 👍
