### ISSUE TITLE
Implement a policy to refresh FCM tokens and send to backend regularly

### ISSUE THREAD

**Issue by hichamboushaba** [woocommerce/woocommerce-android#11671]
While investigating an issue, I found out that my device's token was removed from our servers, I'm not sure what caused this and if it was because my token was expired, but regardless of the reason, we should update the logic of our app to send the token regularly, as it's a best practice recommended by Google: https://firebase.blog/posts/2023/04/managing-cloud-messaging-tokens/#updating-registration-tokens

This new policy will also ensure that stale tokens get updated when the periodic logic is executed.

**Comment by dangermattic** [comment]
Thanks for reporting! 👍
