### ISSUE TITLE
[Woo POS] Show pictures in landscape mode on tablets in card reader flows

### ISSUE THREAD

**Issue by kidinov** [woocommerce/woocommerce-android#11675]
![Image](https://github.com/woocommerce/woocommerce-android/assets/4923871/4fb7a8f8-c145-4d56-adf0-0c6f3fd175f4)

**Comment by dangermattic** [comment]
🚫 Please add a type label (e.g. **type: enhancement**) and a feature label (e.g. **feature: stats**) to this issue.
