### ISSUE TITLE
[Payment Method Improvements] Handle 0 position and fix TalkBack

### ISSUE THREAD

**Issue by backwardstruck** [woocommerce/woocommerce-android#11673]
TE testing feedback:

"Are we able to keep the “0” in the hundredths place rather than dropping it?"

"TalkBack handled the Cash received field a bit oddly the first time — it read the right information (value in the field, type of field and field name) but seemed overly verbose in the beginning (not exactly this, but close to – “60.3, replacing 0, 60.3, 60-dollars-thirty-cents edit field cash received”)"

https://corvidp2.wordpress.com/2024/05/29/draft-android-cash-payment-improvements-test-charter/#comment-618

**Comment by dangermattic** [comment]
🚫 Please add a type label (e.g. **type: enhancement**) and a feature label (e.g. **feature: stats**) to this issue.
