### ISSUE TITLE
Tracking - Exploration

### ISSUE THREAD

**Issue by kidinov** [woocommerce/woocommerce-android#11680]
How can we separate tracking for the POS section from the existing parts of the app?
Can we add a prefix to all POS events?
What can we do to start working on the implementation?

**Comment by dangermattic** [comment]
🚫 Please add a type label (e.g. **type: enhancement**) and a feature label (e.g. **feature: stats**) to this issue.

**Comment by kidinov** [comment]
That's been implemented here - https://github.com/woocommerce/woocommerce-android/issues/11517
