### ISSUE TITLE
[Woo POS] Add POS entry point asynchronously after the eligibility check completes

### ISSUE THREAD

**Issue by kidinov** [woocommerce/woocommerce-android#11703]
![Image](https://github.com/woocommerce/woocommerce-android/assets/4923871/bb8a5ded-4dd3-42c2-8089-4b033ba4caaa)

**Comment by dangermattic** [comment]
🚫 Please add a type label (e.g. **type: enhancement**) and a feature label (e.g. **feature: stats**) to this issue.
