### ISSUE TITLE
[Woo POS] Pass cancelation/error result when user cancels the flow

### ISSUE THREAD

**Issue by samiuelson** [woocommerce/woocommerce-android#11725]
`WooPoskCardReaderActivity` doesn't receive a result with the `WOO_POS_CARD_PAYMENT_REQUEST_KEY` when the card reader payment flow is canceled.

**Comment by dangermattic** [comment]
🚫 Please add a type label (e.g. **type: enhancement**) and a feature label (e.g. **feature: stats**) to this issue.
