### ISSUE TITLE
Google Play Warnings: Upgrade WooCommerce to a newer com.google.android.play:core SDK version

### ISSUE THREAD

**Issue by backwardstruck** [woocommerce/woocommerce-android#11747]
Google Play is sending us a couple warnings/emails that could impact our releases:

Update com.google.android.playWooCommerce
Jun 18, 2024 12:15
com.google.android.play:core has added this note for core:1.10.3:
Update your Play Core Maven dependency to an Android 14 compatible version! Your current Play Core library is incompatible with targetSdkVersion 34 (Android 14), which introduces a backwards-incompatible change to broadcast receivers to improve user security. As a reminder, from August 31, Google Play requires all new app releases to target Android 14. Update to the latest Play Core library version dependency to avoid app crashes: https://developer.android.com/guide/playcore#playcore-migration
You may not be able to release future versions of your app with this SDK version to production or open testing.
Affected app bundles and APKs:
version: 480 (16.4), release: [19.0](https://play.google.com/console/app/4973018994742253387/tracks/4700896441397968664/releases/221/details)
version: 480 (16.4), release: [18.9](https://play.google.com/console/app/4973018994742253387/tracks/4700896441397968664/releases/220/details)
version: 482 (16.5), release: [16.5 (482)](https://play.google.com/console/app/4973018994742253387/tracks/4700409856284621530/releases/5/details)
If you have questions about this SDK, contact the SDK provider.

Update com.google.android.playWooCommerce
Jun 18, 2024 12:15
com.google.android.play:feature-delivery has added this note for feature-delivery:2.0.1:
Update your Play Feature Delivery Maven dependency to an Android 14 compatible version! Your current Play Feature Delivery library is incompatible with targetSdkVersion 34 (Android 14), which introduces a backwards-incompatible change to broadcast receivers. As a reminder, from August 31, Google Play requires all new app releases to target Android 14. Update to the latest library version dependency to avoid app crashes: https://developer.android.com/guide/playcore#java-kotlin-feature-delivery
You may not be able to release future versions of your app with this SDK version to production or open testing.
Affected app bundles and APKs:
version: 559 (18.9), release: [18.9](https://play.google.com/console/app/4973018994742253387/tracks/4700896441397968664/releases/220/details)
version: 561 (19.0), release: [19.0](https://play.google.com/console/app/4973018994742253387/tracks/4700896441397968664/releases/221/details)
version: 562 (19.1-rc-1), release: [19.1-rc-1](https://play.google.com/console/app/4973018994742253387/tracks/4699641337367046963/releases/315/details)
If you have questions about this SDK, contact the SDK provider.

**Comment by dangermattic** [comment]
🚫 Please add a type label (e.g. **type: enhancement**) and a feature label (e.g. **feature: stats**) to this issue.

**Comment by backwardstruck** [comment]
P2 post: https://woomobilecuw.wordpress.com/2024/06/19/google-play-warnings-upgrade-woocommerce-to-a-newer-com-google-android-playcore-sdk-version/
