### ISSUE TITLE
[Woo POS] Clean up UI and Strings for Amounts and Payment Processes

### ISSUE THREAD

**Issue by backwardstruck** [woocommerce/woocommerce-android#11746]
Make sure we are following the final design and UI components needed for displaying amounts and conducting payments.

Extract all hardcoded strings to `Strings.xml`

See this comment:
https://github.com/woocommerce/woocommerce-android/pull/11738/#discussion_r1644328800

**Comment by dangermattic** [comment]
Thanks for reporting! 👍
