### ISSUE TITLE
[Woo POS] Fetch only simple products in the POS mode

### ISSUE THREAD

**Issue by malinajirka** [woocommerce/woocommerce-android#11757]
We currently fetch all products from the remote and filter them for simple products only locally. This has some downside in scenarios when all or vast majority of the products are non-simple. It might also break paging when we decide to introduce it and might make `forceRefresh` trickier to implement. Goal of this task is to filter for simple-product only in the remote instead of doing it locally.

**Comment by dangermattic** [comment]
Thanks for reporting! 👍
