### ISSUE TITLE
[Better Errors] Application Password tracks are not working properly.

### ISSUE THREAD

**Issue by ThomazFB** [woocommerce/woocommerce-android#11751]
# Summary
After the Better Errors project, we found that some tracks for the login steps are not triggering as expected and causing a huge drop into our user analytics behavior.

# Probable root cause
It seems that during the WebView transitions for the Application Password setup, some events that should trigger the existing tracks are gone. We should focus the investigation on the `ApplicationPasswordTutorialViewModel` and related flows.

**Comment by dangermattic** [comment]
Thanks for reporting! 👍

**Comment by ThomazFB** [comment]
Fixed in https://github.com/woocommerce/woocommerce-android/pull/12035
