### ISSUE TITLE
Bundle Product with Variable product won't load

### ISSUE THREAD

**Issue by malinajirka** [woocommerce/woocommerce-android#11761]
**Describe the bug**
When I attempt to add a bundled product within the order creation and the bundled product contains a variable product which has `Any` set for each of the variations, the variations are not displayed properly and the product won't load after it's added to the order.

**To Reproduce**
1. Start the order creation
2. Add a bundled product which contains a variable product that has all the variations set with `Any` for the attributes (see image below).
3. Tap to Select Variation
4. First bug: Notice all the rows contain only the thumbnail but are empty otherwise.
5. Select on of the rows
6. Add the product into the order
7. Notice the Bundled Product loads correctly, but the children won't load at all.

**Screenshots**
Watch this video and notice the first variable products (Apple) works as expected, but the second variable products which has all the variations set as "any" (see screenshot from wpadmin) has empty rows:
<img width="2034" alt="Screenshot 2024-06-21 at 9 51 38" src="https://github.com/woocommerce/woocommerce-android/assets/2261188/eb55292d-28ba-4942-8cc6-2527a559288d">

https://github.com/woocommerce/woocommerce-android/assets/2261188/ab666581-5165-4bc2-97fe-551f9d676c3f

**Expected behavior**
I would expect the rows of the variable product to be non-empty - I guess they should say "Any" and I would expect the children load correctly after the product is added to the order.

cc @atorresveiga if I recall correctly, you worked on the bundled products and might have more context.

**Comment by dangermattic** [comment]
Thanks for reporting! 👍

**Comment by atorresveiga** [comment]
The issue seems to be that we don't have support for using `Any` between the bundle variations. I will work on a fix for this

**Comment by ThomazFB** [comment]
Fixed by #12391
