### ISSUE TITLE
[Woo POS] Add "toolbar" to the cart subscreen

### ISSUE THREAD

**Issue by kidinov** [woocommerce/woocommerce-android#11762]
![Image](https://github.com/woocommerce/woocommerce-android/assets/4923871/ccf06fe1-3dd8-49e9-8dad-1da8ff467223)

![Image](https://github.com/woocommerce/woocommerce-android/assets/4923871/d7e9623a-04c3-4806-b667-61d891986928)

**Comment by dangermattic** [comment]
🚫 Please add a type label (e.g. **type: enhancement**) and a feature label (e.g. **feature: stats**) to this issue.
