### ISSUE TITLE
[Woo POS] Consider removing usage of BaseUnitTest that comes from the main app

### ISSUE THREAD

**Issue by kidinov** [woocommerce/woocommerce-android#11771]
To be discussed in the POS meeting: https://docs.google.com/document/d/10JKyruY8xHMMTV3RRGlPkVeTh-wiVMtzSaN-lgIN6DU/edit

```[tasklist]
### Tasks
- [x] WooPosRootViewModelTest
- [x] WooPosHomeViewModelTest
- [x] WooPosCartViewModelTest
- [x] WooPosProductsViewModelTest
- [x] WooPosTotalsViewModelTest
```

**Comment by dangermattic** [comment]
🚫 Please add a type label (e.g. **type: enhancement**) and a feature label (e.g. **feature: stats**) to this issue.

**Comment by backwardstruck** [comment]
Should this be moved to the `Consider after MVP category` or is it better to work on now?

**Comment by kidinov** [comment]
Probably worth discussing it first, not sure

**Comment by soundsokay** [comment]
Based on Slack discussion let's move forward with this since it decouples from the main app and is estimated to be a small amount of work.

**Comment by backwardstruck** [comment]
Maybe we should also update the base test to address that workaround:

        /**
         * This is a temporary workaround  to fix existing tests that were broken by
         * the change on kotlinx.coroutines 1.7.0 that causes tests that
         * throw exceptions to fail. Previously test methods that threw exceptions would not prevent
         * tests from passing, which was a bug in kotlinx.coroutines that has now been fixed. However,
         * significant number of our tests are currently failing because of this change.
         *
         * See the following issue for more details: https://github.com/Kotlin/kotlinx.coroutines/issues/1205.
         * The workaround below is taken from the related PR: https://github.com/Kotlin/kotlinx.coroutines/pull/3736
         * and is a solution suggested by JetBrains to disable the new behavior using non-public API
         * until we fix our tests. This should not be considered a long-term solution, rather a temporary hack.
         */

        Class.forName("kotlinx.coroutines.test.TestScopeKt")
            .getDeclaredMethod("setCatchNonTestRelatedExceptions", Boolean::class.java)
            .invoke(null, false)
