### ISSUE TITLE
[Woo POS] Bottom Bar - cut off text

### ISSUE THREAD

**Issue by kidinov** [woocommerce/woocommerce-android#11782]
The text in the bottom bar is cut-off on some devices - eg. Medium Tablet API 33

![Image](https://github.com/woocommerce/woocommerce-android/assets/2261188/4bb3b083-2200-48f6-b393-f8f54ea579f7)

![Image](https://github.com/woocommerce/woocommerce-android/assets/2261188/cb300b73-cfd8-45e0-8d3a-cb2e99085886)

**Comment by dangermattic** [comment]
🚫 Please add a type label (e.g. **type: enhancement**) and a feature label (e.g. **feature: stats**) to this issue.

**Comment by kidinov** [comment]
@malinajirka 👋

I think this maybe fix as side effect of some changes of [this PR](https://github.com/woocommerce/woocommerce-android/pull/11764). I believe I use the same emulator for test - can you double check that it's been fixed? 



![Image](https://github.com/woocommerce/woocommerce-android/assets/4923871/1267146f-5896-4749-b19f-8ab04f3a2add)

**Comment by malinajirka** [comment]
I can confirm this is fixed now! Thanks for the ping Andrei.
