### ISSUE TITLE
Update Dashboard data

### ISSUE THREAD

**Issue by Ecarrion** [woocommerce/woocommerce-android#11791]
# Task

- [x] Periodically update the data needed for the dashboard as a background task.
- [x] When opening the app update the dashboard data if it hasn't been updated in the background recently.

## Background Update Periodicity

- TBD

## Foreground Update Trigger

- Update if the data hasn't been updated in 30 minutes.

**Comment by dangermattic** [comment]
🚫 Please add a type label (e.g. **type: enhancement**) and a feature label (e.g. **feature: stats**) to this issue.
