### ISSUE TITLE
Show the last updated timestamp on the orders list

### ISSUE THREAD

**Issue by Ecarrion** [woocommerce/woocommerce-android#11796]
# Task

- [ ] Update UI to a timestamp of when the data was last updated.

# Notes

- The timestamp should also reflect the time when the orders where updated in the foreground (pull to refresh, etc)

## TODO

- [ ] Define UI Mock up

**Comment by dangermattic** [comment]
🚫 Please add a type label (e.g. **type: enhancement**) and a feature label (e.g. **feature: stats**) to this issue.
