### ISSUE TITLE
[Woo POS] Payment failure screen

### ISSUE THREAD

**Issue by kidinov** [woocommerce/woocommerce-android#11806]

**Comment by dangermattic** [comment]
🚫 Please add a type label (e.g. **type: enhancement**) and a feature label (e.g. **feature: stats**) to this issue.

**Comment by samiuelson** [comment]
As discussed p1719492112174409-slack-C070SJRA8DP we won't implement a stand alone failure screen as the reused IPP payment flow handles errors itself.
