### ISSUE TITLE
Add tracks events

### ISSUE THREAD

**Issue by Ecarrion** [woocommerce/woocommerce-android#11814]
### For this project, the following events should be added:

 - `*_background_data_synced` params: time_taken
 -  `*_background_data_sync_error` params: error
 -  `*_push_notification_order_background_synced` params: time_taken
 - `*_push_notification_order_background_sync_error` params: error
 - `*_background_updates_disabled`

**Comment by dangermattic** [comment]
🚫 Please add a type label (e.g. **type: enhancement**) and a feature label (e.g. **feature: stats**) to this issue.
