### ISSUE TITLE
Dynamic Dashboard: Add missing events for dashboard card performance

### ISSUE THREAD

**Issue by itsmeichigo** [woocommerce/woocommerce-android#11815]
Event list:

Event | Trigger | Properties
-- | -- | --
*_dynamic_dashboard_card_data_loading_started | When a dashboard card starts loading data. | `type`: card type name
*_dynamic_dashboard_card_data_loading_completed | When a dashboard card completes loading data without error | `type`: card type name
*_dynamic_dashboard_card_data_loading_failed | When a dashboard card fails to load data | `type`: card type name, `error`: error details

Internal discussion: pe5sF9-2PV-p2#comment-3718

**Comment by dangermattic** [comment]
🚫 Please add a type label (e.g. **type: enhancement**) and a feature label (e.g. **feature: stats**) to this issue.
