### ISSUE TITLE
[Woo POS] Scroll to the added item in the cart

### ISSUE THREAD

**Issue by malinajirka** [woocommerce/woocommerce-android#11817]
When multiple products are added to the cart and they no longer fit without scrolling, the newly added items are added to the bottom (non-visible area) => we should scroll to the last added item or add items to the top instead.

**Comment by dangermattic** [comment]
🚫 Please add a type label (e.g. **type: enhancement**) and a feature label (e.g. **feature: stats**) to this issue.

**Comment by samiuelson** [comment]
The functionality is implemented in the https://github.com/woocommerce/woocommerce-android/pull/11821.
