### ISSUE TITLE
[Woo POS] Add `Clear all` button to cart view

### ISSUE THREAD

**Issue by iamgabrielma** [woocommerce/woocommerce-android#11813]
Ref: p1719373464939629/1718835247.409189-slack-C070SJRA8DP

<img width="718" alt="Screenshot 2024-06-26 at 10 46 42" src="https://github.com/woocommerce/woocommerce-ios/assets/3812076/7dc4e791-a9b1-4c5f-9799-3bac7250de0c">

Upon tapping, the side effect should be to hide the cart view, since now it would be empty, rather than showing any sort of empty screen.

**Comment by dangermattic** [comment]
Thanks for reporting! 👍

**Comment by samiuelson** [comment]
On Android it's done, should we change the platform label to Android?

**Comment by iamgabrielma** [comment]
Sure, please update the labels as necessary and close the issue if it's done on Android. Thanks!

**Comment by kidinov** [comment]
Yep it's done on Android
