### ISSUE TITLE
[Woo POS] M2: Update UI based on design for success screen

### ISSUE THREAD

**Issue by backwardstruck** [woocommerce/woocommerce-android#11828]
Follow up from this PR:

https://github.com/woocommerce/woocommerce-android/pull/11812#issuecomment-2195532317

Match design for success screen

**Comment by dangermattic** [comment]
Thanks for reporting! 👍

**Comment by backwardstruck** [comment]
I guess there's still some big differences:


Design:

<img width="828" alt="Screenshot 2024-07-26 at 17 08 42" src="https://github.com/user-attachments/assets/e66906fa-9660-48e2-8098-f322f8e7c3a7">



Current implementation:


![Screenshot_20240726_170852](https://github.com/user-attachments/assets/b4ae51bd-7562-4d83-9044-4c7f5ed1e9dc)
