### ISSUE TITLE
Blaze i3: move "Generated with AI" label under description

### ISSUE THREAD

**Issue by pmusolino** [woocommerce/woocommerce-android#11834]
Following a suggestion of @itsmeichigo in [this iOS PR](https://github.com/woocommerce/woocommerce-ios/pull/13172/), we decided to move the label "Generated with AI" immediately under the description. It looks better.

<img src="https://github.com/woocommerce/woocommerce-android/assets/495617/0b079a17-ba8a-4f10-a10e-3e016ef35dcf" width=300 />

**Comment by dangermattic** [comment]
Thanks for reporting! 👍

**Comment by JorgeMucientes** [comment]
Closing. After some discussion we agreed to keep the label as is: p1727177421848799-slack-C03L1NF1EA3
