### ISSUE TITLE
[Woo POS] Bottom toolbar UI updates

### ISSUE THREAD

**Issue by samiuelson** [woocommerce/woocommerce-android#11831]

**Comment by dangermattic** [comment]
🚫 Please add a type label (e.g. **type: enhancement**) and a feature label (e.g. **feature: stats**) to this issue.

**Comment by samiuelson** [comment]
![Image](https://github.com/woocommerce/woocommerce-android/assets/4527432/c32c1e18-8143-4f57-8344-aa599767088f)
![Image](https://github.com/woocommerce/woocommerce-android/assets/4527432/746421dc-2493-44f7-a3ed-124066046bec)
