### ISSUE TITLE
Remove Blaze remote feture flag

### ISSUE THREAD

**Issue by JorgeMucientes** [woocommerce/woocommerce-android#11832]
Remove remote feature flag config and usages in the app code

**Comment by dangermattic** [comment]
🚫 Please add a type label (e.g. **type: enhancement**) and a feature label (e.g. **feature: stats**) to this issue.

**Comment by JorgeMucientes** [comment]
Closing as this was already done here: https://github.com/woocommerce/woocommerce-android/issues/12668
