### ISSUE TITLE
Changing stock status in Product Stock Daashboard card is not working

### ISSUE THREAD

**Issue by JorgeMucientes** [woocommerce/woocommerce-android#11841]
**Describe the bug**
A clear and concise description of what the bug is. Please be as descriptive as possible; issues lacking detail or for any other reason than to report a bug may be closed without action.
Changing stock status in Product Stock Daashboard card is not working.

**To Reproduce**
- Enable stock card in Dashboard screen
- Change between different stock statuses

https://github.com/woocommerce/woocommerce-android/assets/2663464/28f88416-ebe6-4627-b9c7-c94024eef1b8

**Comment by dangermattic** [comment]
🚫 Please add a type label (e.g. **type: enhancement**) and a feature label (e.g. **feature: stats**) to this issue.
