### ISSUE TITLE
Fetch campaign list

### ISSUE THREAD

**Issue by hafizrahman** [woocommerce/woocommerce-android#11858]
Endpoint: GET wc/gla/ads/campaigns
Response:

[
     {
            "id": 21401695859,
            "name": "Campaign 2024-06-21 04:26:32",
            "status": "enabled",
            "type": "performance_max",
            "amount": 30,
            "country": "US",
            "targeted_locations": [
                "US"
            ]
        }
]

**Comment by dangermattic** [comment]
🚫 Please add a type label (e.g. **type: enhancement**) and a feature label (e.g. **feature: stats**) to this issue.

**Comment by hafizrahman** [comment]
Solved in https://github.com/wordpress-mobile/WordPress-FluxC-Android/pull/3043
