### ISSUE TITLE
Clicking "collect payment" > "scan to pay" then going back before it loads causes the order to go into "Pending Payment". Completely messes up payments.

### ISSUE THREAD

**Issue by stephencomputer** [woocommerce/woocommerce-android#11855]
**Describe the bug**
I experienced this last week but didn't know how or why it happened. I have been trying to reproduce it ever since and finally cracked it today. This should probably be fixed to avoid confusing store owners.

**To Reproduce**
1. Go to a Draft order
2. Click on Collect Payment
3. Scroll down to Scan Payment
4. Go back before it loads.

**Screenshots**
[Did this on my phone - no screenshots]

**Expected behavior**

**Isolating the problem (mark completed items with an [x]):**
- [ ] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [ ] This bug happens with a default WordPress theme active,
  or [Storefront](https://woocommerce.com/products/storefront/).
- [x] I can reproduce this bug consistently using the steps above.

**Mobile Environment**
Please include:
- Device:
- Android version:
- WooCommerce Android version:

**WordPress Environment**
<details>
```
Copy and paste the system status report from **WooCommerce > System Status** in WordPress admin.
```
</details>

**Comment by dangermattic** [comment]
Thanks for reporting! 👍

**Comment by stephencomputer** [comment]
@irfano (Sorry but you are the only maintainer I can find on this)
I checked the order as completed...

**The app now thinks that I have had real purchases** - Or at least I think it does. What do I do?

**Comment by stephencomputer** [comment]
I'll mark the orders as failed for the time being.

**Comment by stephencomputer** [comment]
It doesn't seem to have affected my Wordpress site - so maybe it's just a visual bug. I don't really know.

**Comment by irfano** [comment]
Thank you for reporting this, @stephencomputer! I'm forwarding it to the relevant team to prioritize.

**Comment by irfano** [comment]
Hey @stephencomputer! I found out that the behavior you reported is intended. When the "Scan to Pay" button is tapped, the order status changes to "Pending payment" because it is expected that you will complete the payment via QR code. You can change the order status after tapping the "Scan to Pay" button. 
I'll close this issue, but let me know if I misunderstood the problem.
