### ISSUE TITLE
[Woo POS] Hide cart when payment succeed

### ISSUE THREAD

**Issue by kidinov** [woocommerce/woocommerce-android#11867]
Now we show cart on the left

![Image](https://github.com/woocommerce/woocommerce-android/assets/4923871/5e3e76b8-7e02-4320-b5bc-bf89f4996912)

**Comment by dangermattic** [comment]
🚫 Please add a type label (e.g. **type: enhancement**) and a feature label (e.g. **feature: stats**) to this issue.
