### ISSUE TITLE
[Woo POS] Add Compose card under cart and totals as per design

### ISSUE THREAD

**Issue by kidinov** [woocommerce/woocommerce-android#11861]
![Image](https://github.com/woocommerce/woocommerce-android/assets/4923871/067bdf3c-776a-4b4b-bf02-18aa2f4b7d28)

Currently we show totals and cart in 2 different cards on the checkout state.

Branch off of this PR:
https://github.com/woocommerce/woocommerce-android/pull/11879

Put a compose card underneath both totals and cart screens, by changing `WooPosHomeScreen`

**Comment by dangermattic** [comment]
🚫 Please add a type label (e.g. **type: enhancement**) and a feature label (e.g. **feature: stats**) to this issue.

**Comment by backwardstruck** [comment]
The PR is in review but the requirements for this work have changed based on [this](https://a8c.slack.com/archives/C070SJRA8DP/p1720549759203399?thread_ts=1720104580.663059&cid=C070SJRA8DP) discussion.
