### ISSUE TITLE
Logic for improving seed prompt

### ISSUE THREAD

**Issue by JorgeMucientes** [woocommerce/woocommerce-android#11862]
![image](https://github.com/woocommerce/woocommerce-ios/assets/524475/e95770db-17a1-4ac0-80d3-0725438dbeae)

1. Update suggestion message based on the length of the prompt
2. Progress bar with color

- This will be entirely local with no AI intervention.
- Define rules for the length of the progress bar.
- UI work

Logic as follows: 
```
       case 0:
            status = .start
        case 1...10:
            status = .inProgress
        case 11...19:
            status = .halfway
        case 20...30:
            status = .almostDone
        default:
            status = .completed
```

Internal - p1719205329811609-slack-C03L1NF1EA3

**Comment by dangermattic** [comment]
Thanks for reporting! 👍
