### ISSUE TITLE
[Woo POS] Handle Errors in Payment Process

### ISSUE THREAD

**Issue by backwardstruck** [woocommerce/woocommerce-android#11869]
Implement error handling for various issues that could arise during the payment process.

**Comment by dangermattic** [comment]
Thanks for reporting! 👍

**Comment by samiuelson** [comment]
In theory, all the errors are handled by the existing payment flow that we reuse. Is there any specific error or scenario we should take care of?

**Comment by backwardstruck** [comment]
> In theory, all the errors are handled by the existing payment flow that we reuse. Is there any specific error or scenario we should take care of?

No I guess I didn't have anything particular in mind. I'll close this then.
