### ISSUE TITLE
Merge product creation with AI into a single screen.

### ISSUE THREAD

**Issue by JorgeMucientes** [woocommerce/woocommerce-android#11878]
Add the UI to handle adding all the product prompt in a single screen: 

![Screenshot 2024-07-02 at 11 08 03](https://github.com/woocommerce/woocommerce-android/assets/2663464/cdd8009e-e111-4287-bcff-76fa4993fbad)

**Comment by dangermattic** [comment]
🚫 Please add a type label (e.g. **type: enhancement**) and a feature label (e.g. **feature: stats**) to this issue.
