### ISSUE TITLE
[Woo POS] Consider moving order creation logic from cart to totals subscreen

### ISSUE THREAD

**Issue by kidinov** [woocommerce/woocommerce-android#11880]

**Comment by dangermattic** [comment]
🚫 Please add a type label (e.g. **type: enhancement**) and a feature label (e.g. **feature: stats**) to this issue.

**Comment by samiuelson** [comment]
Following up on the original [discussion](https://github.com/woocommerce/woocommerce-android/pull/11840#discussion_r1661120343):

> We can do that [move order creation to totals], but we'll still need to return the result back to the cart - as we need to enable/disable the checkout button. So it will be pretty much the same as we currently have.

I think we would only need to enable/disable the checkout button based on the number of products in the cart (not the order creation request state). Whenever items in the cart are modified, we will send an event with a list of product ids, the Totals VM will cancel the ongoing order creation request, and create a new one with the latest product ids.

**Comment by kidinov** [comment]
@samiuelson 

> Whenever items in the cart are modified, we will send an event with a list of product ids, the Totals VM will cancel the ongoing order creation request, and create a new one with the latest product ids.

Yep, may work too
