### ISSUE TITLE
[Woo POS] Update cache when products are fetched

### ISSUE THREAD

**Issue by kidinov** [woocommerce/woocommerce-android#11884]
Currently if a product removed on the web, it looks like that we still show locally cached version of it and do not update cache when a new result comes from the backend

**Comment by dangermattic** [comment]
🚫 Please add a type label (e.g. **type: enhancement**) and a feature label (e.g. **feature: stats**) to this issue.

**Comment by kidinov** [comment]
That's been fixed in

**Comment by kidinov** [comment]
This is fixed in https://github.com/woocommerce/woocommerce-android/issues/11755
