### ISSUE TITLE
[Woo POS] Entry point eligibility conditions improvements

### ISSUE THREAD

**Issue by samiuelson** [woocommerce/woocommerce-android#11895]
As turned out from investigation (p1719941118168819/1719932291.622679-slack-C070SJRA8DP) the current conditions eligibility conditions are not allowing to enter POS mode in case the device is a small tablet and in portrait mode. However, in landscape POS is enabled. We should take the device orientation into account, and show POS entry point in such case.

**Comment by dangermattic** [comment]
🚫 Please add a type label (e.g. **type: enhancement**) and a feature label (e.g. **feature: stats**) to this issue.
