### ISSUE TITLE
[Woo POS] Consider in-memory storage for product selector, independent from store management mode

### ISSUE THREAD

**Issue by samiuelson** [woocommerce/woocommerce-android#11908]
Separating products' data layer from store management mode would allow performing full sync of products including wiping stale data on "pull to refresh" or during initial data loading.

**Comment by dangermattic** [comment]
🚫 Please add a type label (e.g. **type: enhancement**) and a feature label (e.g. **feature: stats**) to this issue.

**Comment by kidinov** [comment]
@samiuelson my understand that this implemented with cleaning the storage on pull to refresh so closing that. Feel free to reopen if my understanding is not correct https://github.com/woocommerce/woocommerce-android/issues/11755
