### ISSUE TITLE
EAN-13 check digit not recognized when scanning barcode in Order creation

### ISSUE THREAD

**Issue by samiuelson** [woocommerce/woocommerce-android#11919]
**Describe the bug**
A clear and concise description of what the bug is. Please be as descriptive as possible; issues lacking detail, or for any other reason than to report a bug, may be closed without action.
EAN-13 check digit not recognized when scanning barcode in Order creation. It's recognized correctly in Scan to update inventory though.

Discussion and context: p1720098058277949/1720098051.555859-slack-C6H8C3G23

**To Reproduce**
1. Generate EAN-13 barcode
2. Verify the last value is not recognised in Order creation
3. Verify the last value is correctly recognised in Scan to update inventory (Products screen)

**Expected behavior**
1. The last digit of the code should be recognised.
2. Scan to update inventory and Order creation should provide the same results when scanning.

**Comment by dangermattic** [comment]
Thanks for reporting! 👍

**Comment by zoupkat** [comment]
Another report about this 8627191-ZD
Can you please give us an update on the ETA for a fix on this (if there is one)?
Thank you!

**Comment by samiuelson** [comment]
@zoupkat we are aiming to ship the fix in the 20.3 version of the app.

**Comment by samiuelson** [comment]
The fix was merged and will be released in version `20.5`.
