### ISSUE TITLE
Success dialog after campaign creation

### ISSUE THREAD

**Issue by hafizrahman** [woocommerce/woocommerce-android#11917]
Check if site already has campaigns. If yes, show dashboard screen: /wp-admin/admin.php?page=wc-admin&path=%2Fgoogle%2Fdashboard.

Otherwise, start campaign creation flow:

Entry point: wp-admin/admin.php?page=wc-admin&path=%2Fgoogle%2Fdashboard&subpath=%2Fcampaigns%2Fcreate
Successful redirect page: /wp-admin/admin.php?page=wc-admin&path=%2Fgoogle%2Fdashboard&campaign=saved

**Comment by dangermattic** [comment]
🚫 Please add a type label (e.g. **type: enhancement**) and a feature label (e.g. **feature: stats**) to this issue.
