### ISSUE TITLE
[Woo POS] Improve unit test coverage

### ISSUE THREAD

**Issue by backwardstruck** [woocommerce/woocommerce-android#11914]
We should try to do this for all the new POS classes.

Discussed here:
https://docs.google.com/document/d/10JKyruY8xHMMTV3RRGlPkVeTh-wiVMtzSaN-lgIN6DU/edit?disco=AAABQsTmXAA

```[tasklist]
### Tasks
- [ ] https://github.com/woocommerce/woocommerce-android/issues/11928
- [x] common
- [ ] https://github.com/woocommerce/woocommerce-android/issues/11932
- [x] root: WooPosRootViewModel
- [x] util
```

**Comment by dangermattic** [comment]
🚫 Please add a type label (e.g. **type: enhancement**) and a feature label (e.g. **feature: stats**) to this issue.
