### ISSUE TITLE
[Woo POS] Adapt the UI to be usable on smaller devices

### ISSUE THREAD

**Issue by kidinov** [woocommerce/woocommerce-android#11937]

**Comment by dangermattic** [comment]
🚫 Please add a type label (e.g. **type: enhancement**) and a feature label (e.g. **feature: stats**) to this issue.

**Comment by backwardstruck** [comment]
Responsive Design: Ensure the UI adapts well to smaller screens without compromising functionality or usability.
Testing: Test the UI on various device sizes to ensure consistency.
Accessibility: Ensure that text, buttons, and interactive elements are accessible and easy to use on smaller screens.
