### ISSUE TITLE
Stats: Add new Stats to FluxC

### ISSUE THREAD

**Issue by mindgraffiti** [woocommerce/woocommerce-android#1198]
Ref: p99K0U-1iF-p2 and p99K0U-1ex-p2

We'll need separate database entries for the new stats, because we will have to support both types simultaneously. 
- add new entities
- add new models (as needed)
- add new mappers (as needed)
- add the new wc-admin v4 endpoints
- add functions that request hourly, daily, weekly, monthly, and yearly sales
- add unit tests

**Comment by anitaa1990** [comment]
Closing this issue as the related [FluxC PR](https://github.com/wordpress-mobile/WordPress-FluxC-Android/pull/1302) has been merged!
