### ISSUE TITLE
[Woo POS] M2: Implement floating bottom toolbar with reader status

### ISSUE THREAD

**Issue by samiuelson** [woocommerce/woocommerce-android#11998]
Modify existing bottom toolbar to match new design:

![Image](https://github.com/user-attachments/assets/e860e8b1-4523-4e9a-bf83-3d93969a9f86)

**Comment by dangermattic** [comment]
🚫 Please add a type label (e.g. **type: enhancement**) and a feature label (e.g. **feature: stats**) to this issue.

**Comment by kidinov** [comment]
Implemented that as part of https://github.com/woocommerce/woocommerce-android/issues/11992. Unfortunately, we may need to adjust the UI again as the design keeps changing

![Image](https://github.com/user-attachments/assets/ee9d0603-3a39-4fe4-9162-092d3d22d208)
