### ISSUE TITLE
Display company name in Shipping Address

### ISSUE THREAD

**Issue by astralbodies** [woocommerce/woocommerce-android#12]
Based on: https://github.com/woocommerce/woocommerce-mobile/issues/205

**Comment by rachelmcr** [comment]
I confirmed that the company name is appearing in the shipping address for order details:

![Screenshot_20190312-143218](https://user-images.githubusercontent.com/8658164/54208474-e870b700-44d3-11e9-99aa-50ef30e024ff.png)

Closing as resolved.
