### ISSUE TITLE
[Woo POS] M2: Update total's design

### ISSUE THREAD

**Issue by kidinov** [woocommerce/woocommerce-android#12008]
* [Design specs](https://www.figma.com/design/TfaZ4LUkEwEGrxfnEFzvJj/WooCommerce-POS?node-id=2877-89647&t=bfG3nKfkvRsb6RZo-0)

![Image](https://github.com/user-attachments/assets/7ff10c6d-436f-4d8b-ba5e-861f3d5b892b)

**Comment by dangermattic** [comment]
🚫 Please add a type label (e.g. **type: enhancement**) and a feature label (e.g. **feature: stats**) to this issue.

**Comment by backwardstruck** [comment]
Is this a duplicate of [this](https://github.com/woocommerce/woocommerce-android/issues/12139) issue or are there other changes we need to make? I didn't notice what we might be missing from the Figma design.

**Comment by backwardstruck** [comment]
This is what we have now on `trunk`:
![Screenshot_20240801_103245](https://github.com/user-attachments/assets/8adfda09-9542-4cec-a4e8-d12cfc2b194a)

**Comment by kidinov** [comment]
Yep, duplicate
