### ISSUE TITLE
[Woo POS] M2: Cart empty state and UI updates

### ISSUE THREAD

**Issue by samiuelson** [woocommerce/woocommerce-android#12000]
1. Add "empty" state:

![Image](https://github.com/user-attachments/assets/bef21a39-7ada-4651-be77-7c0278383635)

3. Remove cart pane width animation / transition between empty and non empty cart state

**Comment by dangermattic** [comment]
🚫 Please add a type label (e.g. **type: enhancement**) and a feature label (e.g. **feature: stats**) to this issue.

**Comment by kidinov** [comment]
Implemented in here - https://github.com/woocommerce/woocommerce-android/issues/11933
