### ISSUE TITLE
[Woo POS] Make sure strings are correct for order creation failure

### ISSUE THREAD

**Issue by backwardstruck** [woocommerce/woocommerce-android#12016]
Check all strings added for this feature to make sure they will be translated:
https://github.com/woocommerce/woocommerce-android/issues/11708

```[tasklist]
### Tasks
- [ ] https://github.com/woocommerce/woocommerce-android/pull/12050#discussion_r1682402697
```

**Comment by dangermattic** [comment]
🚫 Please add a type label (e.g. **type: enhancement**) and a feature label (e.g. **feature: stats**) to this issue.
