### ISSUE TITLE
[Woo POS] M2: Testing, remove reflective code used for handling coroutine exceptions

### ISSUE THREAD

**Issue by backwardstruck** [woocommerce/woocommerce-android#12012]
Per [this](https://github.com/woocommerce/woocommerce-android/pull/11976#discussion_r1678080282) discussion:

Remove the reflective code used for handling coroutine exceptions and rely on straightforward coroutine testing practices.

#### Why It's Problematic
1. **Non-Public API Use**

2. **Potentially Masking Real Issues**

#### Long-Term: Fix the Underlying Issues
Rather than relying on this workaround, a more sustainable approach would be to identify and fix the individual tests that are causing issues with coroutine exceptions. This aligns with best practices for writing robust and maintainable test code.
    - Check that all `coroutineScope` blocks are properly managing their exceptions.
    - Ensure all flows and coroutine launches are properly handled and do not leak unhandled exceptions.

**Comment by dangermattic** [comment]
🚫 Please add a type label (e.g. **type: enhancement**) and a feature label (e.g. **feature: stats**) to this issue.
