### ISSUE TITLE
[Woo POS] Correctly show error state at the right time

### ISSUE THREAD

**Issue by backwardstruck** [woocommerce/woocommerce-android#12015]
Description
Address the handling of order creation failures

Testing:
Add items to the cart.
Proceed to checkout and initiate the order creation process.
Simulate an error condition (e.g., disconnect network, simulate server error).
Observe the error handling and user feedback, including the retry option.
Retry the order creation process to verify the retry mechanism works correctly.

Covered Scenarios:
Network Failure: Simulate network disconnections during order creation.
Server Errors: Simulate server-side error responses (e.g., 500 Internal Server Error).
Validation Errors: Ensure any validation errors are also handled gracefully.

**Comment by dangermattic** [comment]
🚫 Please add a type label (e.g. **type: enhancement**) and a feature label (e.g. **feature: stats**) to this issue.
