### ISSUE TITLE
[Woo POS] Match design for order creation failure

### ISSUE THREAD

**Issue by backwardstruck** [woocommerce/woocommerce-android#12014]
<img width="660" alt="Screenshot 2024-07-23 at 17 19 17" src="https://github.com/user-attachments/assets/10e702cf-e22d-4fd9-bc70-d4253f7f4b74">

<img width="676" alt="Screenshot 2024-07-23 at 17 21 02" src="https://github.com/user-attachments/assets/5f266e36-a638-4a0c-9cc9-e155940d7ad8">

```[tasklist]
### Tasks
- [x] Fonts
- [ ] Margins
- [x] Colors
- [ ] Elevation/Shadow
```

**Comment by dangermattic** [comment]
🚫 Please add a type label (e.g. **type: enhancement**) and a feature label (e.g. **feature: stats**) to this issue.
