### ISSUE TITLE
[Woo POS] Flow broken when Activity dies

### ISSUE THREAD

**Issue by malinajirka** [woocommerce/woocommerce-android#12027]
**Describe the bug**
When the user is located on the product selection screen, they put the app into the background and the activity dies, the recreated state doesn't have `checkout` button (it seems to be in the checkout stage even though the rest of the screen is still in the product selection stage).
**To Reproduce**
1. Enable 'Don't keep activities' in dev settings
2. Open POS
3. Select a product
4. Put the app into the background
5. Bring it back to the front
6. Notice "Checkout button" is missing and the cart has "back" arrow.

**Screenshots**
![image](https://github.com/user-attachments/assets/0d00a8a6-7a79-4bb0-91e4-8d29eb7d910f)

**Expected behavior**
The state should be identical even after recreation - teh checkout button should be visible and back arrow on the cart should be hidden.

**Comment by dangermattic** [comment]
Thanks for reporting! 👍
