### ISSUE TITLE
[Woo POS] Exit POS button sometimes re-opens the POS again

### ISSUE THREAD

**Issue by malinajirka** [woocommerce/woocommerce-android#12026]
**Describe the bug**
When the user taps on the `Exit POS` button and they confirm, the app sometimes navigates the user back to the POS (Jirka's note: Or the app actually crashes and there is another instance of the app right behind it).

**To Reproduce**
1. Go to More Menu -> POS
2. Click on Exit POS
3. Confirm
4. Notice sometimes the POS is opened again.

**Screenshots**
https://video.wordpress.com/v/LGwCyZTl

**Expected behavior**
The app navigates the user to the More menu.

**Mobile Environment**
Please include: Samsung Galaxy Tab S9 FE on Android 14

**Comment by dangermattic** [comment]
Thanks for reporting! 👍

**Comment by backwardstruck** [comment]
I know this was happening when building the app to launch directly to `com.woocommerce.android.ui.woopos.root.WooPosActivity` <s>but you mean when opening the app, then navigating to POS through the more tab, right?</s>


So far I can't reproduce on the emulator. I can try on my Samsung tablet next.

**Comment by malinajirka** [comment]
@lmischner experienced this behavior during the Test Charter testing - pdcxQM-3PY-p2#comment-3026. Lindsey, I assume you weren't using Android Studio to start the app on the POS screen right?

**Comment by lmischner** [comment]
@malinajirka  -- Yes, can confirm, I was not building from Android studio. I was using [this build](https://github.com/woocommerce/woocommerce-android/pull/11901#issuecomment-2206915086)

Let me know if any other info/help is needed!

**Comment by backwardstruck** [comment]
Still can't reproduce on emulator or tablet. I think it's either fixed or very rare. Also we have updated the UI, but I don't think that would have any effect:

 Samsung Tab A9+
![Screenshot_20240821_163437](https://github.com/user-attachments/assets/e4c3c47e-b63c-40bc-b8fb-da33dc7a2130)
