### ISSUE TITLE
[Login] App shows mismatch screen when attempting to sign in using Site Credentials then going back to use WordPress.com

### ISSUE THREAD

**Issue by hichamboushaba** [woocommerce/woocommerce-android#12032]
Given a Jetpack connected website, If a user attempts to sign in using Site Credentials, then they don't finish the flow (because they decide to do so, or because of some failures), then they go back and use WordPress.com, the app would show the Account Mismatch screen.

This happens because the site will already be in the app's database, and will be fetched using WPApi, and not WPCom API, and given that the function `SiteUtils#getSiteByMatchingUrl` that we use would return the first matching website by URL, then the condition we have [here](https://github.com/woocommerce/woocommerce-android/blob/b5894d38731d5d29119cc8a86c698d9512b11078/WooCommerce/src/main/kotlin/com/woocommerce/android/ui/sitepicker/SitePickerRepository.kt#L35) would fail, and we won't return the website, which leads to the Account Mismatch screen.

**Comment by dangermattic** [comment]
Thanks for reporting! 👍
