### ISSUE TITLE
[Login] Duplicated Jetpack websites cause an issue in Android and not in iOS

### ISSUE THREAD

**Issue by hichamboushaba** [woocommerce/woocommerce-android#12037]
When signing in using WordPress.com, if the website is duplicated (due to an Identity Crisis PCYsg-Jfw-p2), the Android app fails to connect (due to this [logic](https://github.com/wordpress-mobile/WordPress-FluxC-Android/blob/025008c28331ecf1b4f69009348b01bad42bac99/fluxc/src/main/java/org/wordpress/android/fluxc/persistence/SiteSqlUtils.kt#L166-L194)), but the iOS app doesn't.

We need to investigate:
1. What's the origin of this difference in behavior?
2. What would be the side effects of removing this logic in Android?

**Comment by dangermattic** [comment]
Thanks for reporting! 👍
