### ISSUE TITLE
[Woo POS] Consider making WooPosChildrenToParentCommunication and WooPosParentToChildrenCommunication VM scoped

### ISSUE THREAD

**Issue by kidinov** [woocommerce/woocommerce-android#12036]
Now I am not sure that this is a good idea, considering that it will be 1 activity (except IPP reuse) for the whole POS, so maybe to scope those to Home VM will be better.

**Comment by dangermattic** [comment]
🚫 Please add a type label (e.g. **type: enhancement**) and a feature label (e.g. **feature: stats**) to this issue.

**Comment by kidinov** [comment]
After some thinking, I decided that it is ok to have it like that, and we don't need to create another VM that will keep communication and will be shared across our current VMs. The worst-case scenario, which is highly unlikely to happen, is that we lose an event posted just before the configuration change. For now I think the increased complexity doesn't worth the potential impact that this may bring
