### ISSUE TITLE
[Woo POS] Internal Documentation

### ISSUE THREAD

**Issue by malinajirka** [woocommerce/woocommerce-android#12044]
Not sure where, but things worth documenting for Android (p1721201757048329-slack-C025A8VV728): 
- Why we use custom navigation instead of Compose navigation for Product Selection/Cart/Checkout
     - How does this affect recomposition/performance?
     - Are we concerned the increasing number of screens will make the navigation more complex?
- How do the VMs communicate with each other? 
- Why are we re-using IPP flows at the moment? (we can probably link existing posts?)
- ....

(Documentation should be published on the FG or at least linked from there when it's directly in the codebase or on different P2s.)

**Comment by dangermattic** [comment]
Thanks for reporting! 👍

**Comment by kidinov** [comment]
PCYsg-12Hb-p2

Published on FG
