### ISSUE TITLE
Order Creation - SKU text is overflowing

### ISSUE THREAD

**Issue by malinajirka** [woocommerce/woocommerce-android#12047]
**Describe the bug**
When SKU of a product is long and the product is added to an order in the Order Creation flow, the SKU text overflows outside of the boundaries of the view it's located in.

**To Reproduce**
1. Start the order creation flow
2. Add a product with a long SKU into the order
3. Expand the added product by clicking on the chevron icon
4. Notice the SKU overflows

**Screenshots**
<img src="https://github.com/user-attachments/assets/77582771-1072-48d7-a655-d0b0aa7394b7" width="250px" />

**Expected behavior**
The SKU should be correctly constrained within the parent product card.

**Comment by dangermattic** [comment]
Thanks for reporting! 👍
