### ISSUE TITLE
[Login] The Continue button is hidden on the site picker when the user gets an Account Mismatch error

### ISSUE THREAD

**Issue by hichamboushaba** [woocommerce/woocommerce-android#12046]
If the user gets an Account Mismatch error, then goes back to the Site Picker, the "Continue" button will be hidden:

<img src=https://github.com/user-attachments/assets/e7830ac0-fa0a-4571-80f1-caf8128a4d21 width=360 />

This is caused because of the following changes:
1. During the work on this [PR](https://github.com/woocommerce/woocommerce-android/pull/7471), we added a logic to hide the button while we fetch the site information before showing the Account Mismatch screen, this was done to avoid accidental taps while the screen is loading.
This wasn't an issue initially, as we weren't allowing the user to go back to the site picker from Account Mismatch screen.
2. Later as part of this [PR](https://github.com/woocommerce/woocommerce-android/pull/9979), we allow the navigation back.
With this change, we are now having the issue explained in this PR, where the user can't choose a different website and continue.

**Comment by dangermattic** [comment]
Thanks for reporting! 👍
