### ISSUE TITLE
Add tracking events.

### ISSUE THREAD

**Issue by JorgeMucientes** [woocommerce/woocommerce-android#12054]
Tracking plan: pffQ75-yr-p2

Discussions: p1720688618431579-slack-C03L1NF1EA3

![Screenshot 2024-07-18 at 01 03 07](https://github.com/user-attachments/assets/8401ced8-ed69-4bce-be49-b55fe68829ef)

**Comment by dangermattic** [comment]
🚫 Please add a type label (e.g. **type: enhancement**) and a feature label (e.g. **feature: stats**) to this issue.
