### ISSUE TITLE
[Woo POS] Make bottom navigation bar transparent when it's gesture based, and keep it as it is in button based

### ISSUE THREAD

**Issue by kidinov** [woocommerce/woocommerce-android#12058]
![Image](https://github.com/user-attachments/assets/8c541114-2695-4a08-966f-b26ee0158bab)

![Image](https://github.com/user-attachments/assets/7fc05c73-6a16-43c2-90ec-e43ad9182022)

**Comment by dangermattic** [comment]
🚫 Please add a type label (e.g. **type: enhancement**) and a feature label (e.g. **feature: stats**) to this issue.
