### ISSUE TITLE
[Woo POS] Somehow it's possible to get the app into this state

### ISSUE THREAD

**Issue by backwardstruck** [woocommerce/woocommerce-android#12052]
Happened to me while on the totals screen. I backgrounded the app to turn off dark mode then came back to POS

![Image](https://github.com/user-attachments/assets/91b4846e-d09f-4a87-8275-deae7f2f1856)

**Comment by dangermattic** [comment]
Thanks for reporting! 👍

**Comment by backwardstruck** [comment]
FYI @kidinov and @samiuelson have you seen this happen?

**Comment by kidinov** [comment]
@backwardstruck 👋

I think this is a duplicate of that ticket - https://github.com/woocommerce/woocommerce-android/issues/12027. Feel free to reopen if you think that it's not the same case

**Comment by backwardstruck** [comment]
Yep, same one.
