### ISSUE TITLE
[Login] Improve site discovery for sites with multiple Link headers

### ISSUE THREAD

**Issue by hichamboushaba** [woocommerce/woocommerce-android#12079]
Currently, when a site returns multiple `Link` headers, the [site discovery](https://developer.wordpress.org/rest-api/using-the-rest-api/discovery/#link-header) will fail, and the app will fallback to a default URL, which could cause issues (https://github.com/woocommerce/woocommerce-android/issues/12075), while we can improve the reliability by improving our fallback URL to support sites without permalinks (https://github.com/woocommerce/woocommerce-android/issues/12043), we can also avoid having to use the fallback URL by supporting extracting the data from all the headers.

`Volley` our HTTP library already supports this https://github.com/google/volley/issues/21

**Comment by dangermattic** [comment]
Thanks for reporting! 👍
