### ISSUE TITLE
[Login] Site credentials login fails when "wp-json" response cannot be parsed

### ISSUE THREAD

**Issue by staskus** [woocommerce/woocommerce-android#12075]
User report: 8414673-zd-a8c

**Describe the bug**

Logging into the specific site with site credentials fails on Android. **The same site logins successfully on iOS.**

It happens after failing to parse response from `https://{site_url}/wp-json/?_fields=name,description,gmt_offset,url,authentication,namespaces`:

```
com.google.gson.JsonSyntaxException: java.lang.IllegalStateException: Expected BEGIN_OBJECT but was STRING at line 1 column 1 path $
[Jun-24 13:25:24:717 WP e] API StackTrace: com.android.volley.ParseError: com.google.gson.JsonSyntaxException: java.lang.IllegalStateException: Expected BEGIN_OBJECT but was STRING at line 1 column 1 path $
```

Android expects a valid JSON but the response is HTML.

It's true that for the user's site endpoint `wp-json/` returns HTML, rather than JSON with site status. However, the same site login works well on iOS so it shouldn't be a blocker.

**To Reproduce**

Check user report 8414673-zd-a8c. Logging in via site credentials to the user's site fails on Android but works on iOS.  I tested it and can reproduce it myself.

**Screenshots**

<img width="184" alt="image" src="https://github.com/user-attachments/assets/e37cc19e-4f7a-4f33-b1df-a05077f28879">

**Expected behavior**

**Isolating the problem (mark completed items with an [x]):**
- [ ] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [ ] This bug happens with a default WordPress theme active,
  or [Storefront](https://woocommerce.com/products/storefront/).
- [ ] I can reproduce this bug consistently using the steps above.

**Mobile Environment**
Please include:
- Device: Pixel 4
- Android version: API 34
- WooCommerce Android version: 19.2

**WordPress Environment**

User report: 8414673-zd-a8c

**Comment by dangermattic** [comment]
Thanks for reporting! 👍

**Comment by staskus** [comment]
@hichamboushaba as I understand it may be the same issue you reported here https://github.com/woocommerce/woocommerce-android/issues/12043?

**Comment by hichamboushaba** [comment]
@staskus thanks for the ping, I confirm, I checked the site configuration, and I found the following:
1. Site returns multiple `Link` headers, and our HTTP library picks only the last one, which doesn't match the header used to identify the REST url.
2. permalinks are disabled.

So this clearly applies to the above ticket.
In the meantime, we can suggest to the user re-enabling permalinks, but if they need to keep it disabled, then they'll need to wait for a fix on our side.

**Comment by hichamboushaba** [comment]
@staskus I logged an additional issue about this topic (https://github.com/woocommerce/woocommerce-android/issues/12079), I just found out that `Volley` supports multiple identical headers, which means we can support this case, and  this will be easier to implement as it doesn't involve any potential side effects, unlike the change to use `?rest_route=/` instead of `/wp-json` for which we'll need to do a more deeper investigation.

I'll check if I can find some time to work on this new ticket soon.

**Comment by staskus** [comment]
Thanks, @hichamboushaba for taking a look so quickly, I communicated problems with the site. I will close this one as a duplicate of https://github.com/woocommerce/woocommerce-android/issues/12043
