### ISSUE TITLE
[GLA Analytics] Add UI for Google Campaigns metrics menu

### ISSUE THREAD

**Issue by ThomazFB** [woocommerce/woocommerce-android#12072]
We need to add the UI for a menu to select the metric to display on the card:

* Row with the label `Metric` and the selected metric on the left, and an icon to open the menu on the right.
* Menu has a list of all available metrics, with a checkmark next to the selected metric.
* Tapping a new metric reloads the card data for the newly selected metric.

Metric menu (closed)|Metric menu (open)
-|-
![Image](https://github.com/woocommerce/woocommerce-android/assets/8658164/ae8281a9-7cc2-4448-9b30-fd20f7d80ac3)|![Image](https://github.com/woocommerce/woocommerce-android/assets/8658164/29b945c9-0f54-4f03-a58b-a6c7a331c39c)

**Comment by dangermattic** [comment]
Thanks for reporting! 👍
