### ISSUE TITLE
[Woo POS] Make a WooLog.T for our project

### ISSUE THREAD

**Issue by backwardstruck** [woocommerce/woocommerce-android#12083]
Per @malinajirka suggestion [here](https://github.com/woocommerce/woocommerce-android/pull/12050#discussion_r1683828636):

"we might want to consider introducing a new Woo.T for POS to make the logs a bit easier to parse."

Currently, POS-related logs use general tags which can make it difficult to filter and parse logs related specifically to the POS features. By introducing a new Woo.T.POS tag, we can streamline the logging process and improve the maintainability and debugging process for the POS module.

**Comment by dangermattic** [comment]
🚫 Please add a type label (e.g. **type: enhancement**) and a feature label (e.g. **feature: stats**) to this issue.
