### ISSUE TITLE
[Widget] When the Battery Saver is enabled the widget fails to fetch data

### ISSUE THREAD

**Issue by atorresveiga** [woocommerce/woocommerce-android#12096]
**Describe the bug**
When the Battery Saver setting is on the Widget can't fetch the today's stats.

**To Reproduce**
1. Go to  Settings and turn ON the Battery Saver setting 
2. Add the Today's stats widget to the screen
3. Check that the widget complains about not having internet connection

**Screenshots**

https://github.com/user-attachments/assets/caa34729-7c79-445e-b376-fbaf70b6df9c

**Expected behavior**
1. Go to  Settings and turn ON the Battery Saver setting 
2. Add the Today's stats widget to the screen
3. The Widget can fetch the store stats

**Comment by dangermattic** [comment]
Thanks for reporting! 👍

**Comment by atorresveiga** [comment]
Discussed on the Eagle call pe5pgL-5lC-p2:

- We want to respect the user’s battery saver setting and not try to hack a way to refresh the data while it’s on. We could look into options for updating the design to indicate why the widget isn’t working or updating, but there is also messaging from the OS we can rely on.
- We can add Tracks to track if battery saver mode is enabled (for example, when a user interacts with a widget or when the app is opened) and see how many users this might be affecting.
