### ISSUE TITLE
Don't reanimate unfilled orders card

### ISSUE THREAD

**Issue by nbradbury** [woocommerce/woocommerce-android#1209]
Right now the unfilled orders card re-animates in every time the fragment is recreated, which is very distracting. We should instead remember whether it was already showing and if so make it visible right away when the fragment is restored.

Aside: I realize we're planning to drop this card as part of the stats revamp, but this bugs me so much that I have to fix it :)

**Comment by AmandaRiu** [comment]
Very nice UX improvement @nbradbury ! 🍾
