### ISSUE TITLE
Design updates

### ISSUE THREAD

**Issue by JorgeMucientes** [woocommerce/woocommerce-android#12102]
Design - Sgacycoxaxh8EbKoi5FklH-fi-1819_38512
Discussion - p1721186923084509/1720515544.395649-slack-C03L1NF1EA3
iOS issue: https://github.com/woocommerce/woocommerce-ios/issues/13384

There has been a design update to the "Starting Information" screen.

<img width="1332" alt="image" src="https://github.com/user-attachments/assets/45ad9e37-ef74-432d-8514-a63c4b0331ca">

**Comment by dangermattic** [comment]
🚫 Please add a type label (e.g. **type: enhancement**) and a feature label (e.g. **feature: stats**) to this issue.
