### ISSUE TITLE
[Woo POS] M2: Display Simple products only information dialog 

### ISSUE THREAD

**Issue by AnirudhBhat** [woocommerce/woocommerce-android#12100]
The goal of this task is to add an icon to the products toolbar that serves as an entry point for an information dialog, educating users on why the POS displays only Simple products.

<img width="690" alt="Screenshot 2024-07-22 at 3 05 08 PM" src="https://github.com/user-attachments/assets/2ea54dd2-1e22-45e4-8b9e-1b7ae47fb6bb">
<img width="888" alt="Screenshot 2024-07-22 at 3 05 17 PM" src="https://github.com/user-attachments/assets/26e29da0-c8b9-4698-bb85-bb2a2981fec1">

**Comment by dangermattic** [comment]
Thanks for reporting! 👍
