### ISSUE TITLE
[Woo POS] Criteria for POS Simple Physical Products

### ISSUE THREAD

**Issue by AnirudhBhat** [woocommerce/woocommerce-android#12103]
We need to narrow down the criteria for what constitutes a "Simple Physical Product" in our POS system. This is crucial for usability and consistency across platforms.

Criteria:

Product type | simple
-- | --
Product status | published
Product price | Regular/Sale
Purchasable | true/false (We wouldn’t limit here)
Virtual | false
Downloadable | false
Sold individually | nil

For more context: pdfdoF-5d5-p2

**Comment by dangermattic** [comment]
Thanks for reporting! 👍
