### ISSUE TITLE
[Woo POS] Double check order creation failure classes for missing unit tests

### ISSUE THREAD

**Issue by backwardstruck** [woocommerce/woocommerce-android#12118]
The main class missing coverage is `WooPosErrorState` but in order to test that we would need to create a UI test, like `OrdersUITest`
```[tasklist]
### Tasks
- [x] Like this one: https://github.com/woocommerce/woocommerce-android/pull/6285
```

**Comment by dangermattic** [comment]
🚫 Please add a type label (e.g. **type: enhancement**) and a feature label (e.g. **feature: stats**) to this issue.
