### ISSUE TITLE
[Woo POS] Duplicate these iOS issues for Android if they don't exist already

### ISSUE THREAD

**Issue by backwardstruck** [woocommerce/woocommerce-android#12110]
@iamgabrielma created these iOS issues already:

https://a8c.slack.com/archives/C070SJRA8DP/p1720586681229939

**Comment by dangermattic** [comment]
🚫 Please add a type label (e.g. **type: enhancement**) and a feature label (e.g. **feature: stats**) to this issue.

**Comment by samiuelson** [comment]
It seems that all the issues found during test session are added now to the Android board. Is there anything still missing @backwardstruck ?

**Comment by backwardstruck** [comment]
I think we're good.
