### ISSUE TITLE
[Woo POS] Update scrolling visualisation of the lists (shadows)

### ISSUE THREAD

**Issue by kidinov** [woocommerce/woocommerce-android#12113]
https://www.figma.com/design/TfaZ4LUkEwEGrxfnEFzvJj/WooCommerce-POS?node-id=2967-79332&t=RaxwV4fdhkvzHzJR-11

Add shadows

**Comment by dangermattic** [comment]
🚫 Please add a type label (e.g. **type: enhancement**) and a feature label (e.g. **feature: stats**) to this issue.
