### ISSUE TITLE
[Woo POS] Figure out how we use cached products (if we use them)

### ISSUE THREAD

**Issue by kidinov** [woocommerce/woocommerce-android#12125]
Check `WooPosProductsDataSource::loadSimpleProducts` and `handler.loadFromCacheAndFetch`. It seems that we don't use cache at all as we don't pass `searchQuery`?

**Comment by dangermattic** [comment]
🚫 Please add a type label (e.g. **type: enhancement**) and a feature label (e.g. **feature: stats**) to this issue.

**Comment by backwardstruck** [comment]
FYI @samiuelson since you were mentioned in that PR.
