### ISSUE TITLE
Research Spike: Charts for stats

### ISSUE THREAD

**Issue by mindgraffiti** [woocommerce/woocommerce-android#1212]
For the new stats, @kyleaparker has asked if it is possible to create a scrubbing interaction similar to what is used on iOS > Stocks app [[watch the example](https://take.ms/zZq9Y0)]. 

We currently use the [MPAndroidCharts](https://github.com/PhilJay/MPAndroidChart) library to render our stats. 

- [x] Is the scrubbing gesture supported?
- [x] Can we tweak the x-axis to include more granular data points?
- [x] Report findings back to the team.

**Comment by anitaa1990** [comment]
This is definitely possible using `MpAndroidChart` and the changes needed for this implementation can be found [here](https://github.com/woocommerce/woocommerce-android/commit/a1540f4ba9c399ea4191200b711d7fc22801a37e) so closing this issue as completed
