### ISSUE TITLE
Image upload is broken for devices running on Android 9 and lower

### ISSUE THREAD

**Issue by hichamboushaba** [woocommerce/woocommerce-android#12126]
Image upload doesn't work on devices running on Android 9 and lower, and this is caused by the removal of the permissions `READ_EXTERNAL_STORAGE` and `WRITE_EXTERNAL_STORAGE` done when [migrating](https://github.com/woocommerce/woocommerce-android/pull/10141) to use the Photo Picker.

The issue happens when both picking a file from the device, or when trying to take a picture from the camera, the Camera issue is being [handled](https://github.com/wordpress-mobile/WordPress-MediaPicker-Android/issues/81) in the MediaPicker library.

##### Internal discussion peaMlT-Mq-p2

**Comment by dangermattic** [comment]
Thanks for reporting! 👍
