### ISSUE TITLE
[Woo POS] M2: Update totals subscreen

### ISSUE THREAD

**Issue by kidinov** [woocommerce/woocommerce-android#12139]
![Image](https://github.com/user-attachments/assets/ba9813e8-b875-4199-8175-c694b9a3f589)

TfaZ4LUkEwEGrxfnEFzvJj-fi-2877_89647

**Comment by dangermattic** [comment]
🚫 Please add a type label (e.g. **type: enhancement**) and a feature label (e.g. **feature: stats**) to this issue.
