### ISSUE TITLE
[GLA Analytics] Fetch and display selected metric on Google Campaigns analytics card

### ISSUE THREAD

**Issue by ThomazFB** [woocommerce/woocommerce-android#12135]
We need to fetch and display data for the selected metric on the Google Campaigns analytics card:

1. Ensure the selected metric is shown on the card (next to `Metric`) and is selected in the metrics menu.
2. When a new metric is selected, fetch the current and previous period data for that metric:
   * At the top of the card, display the totals value for the selected metric and percent change from the previous period.
   * Display a list of the top five campaigns (based on the selected metric) with their subtotal for the selected metric and their spend data.

**Comment by dangermattic** [comment]
Thanks for reporting! 👍
