### ISSUE TITLE
Illustration in IPP flows doesn't disappear in landscape mode on some phones

### ISSUE THREAD

**Issue by malinajirka** [woocommerce/woocommerce-android#12141]
**Describe the bug**
The illustration in the connection and payment flows should disappear in landscape mode when there isn't enough vertical space. However, it doesn't disappear resulting in a broken looking UI.

**To Reproduce**
1. Go to More -> Payments section
2. Tap on Manager Card Reader
3. Initiate the connection and rotate your device into landscape 
4. Notice the UI is broken

**Screenshots**
![image](https://github.com/user-attachments/assets/ae884f18-ce3f-4e57-97d1-c1458935776e)

**Expected behavior**
The illustration should be hidden when there isn't enough vertical space.

**Mobile Environment**
Please include:
- Device: Pixel 8
- Android version: Android 14
- WooCommerce Android version: 13eba9a205f629efcda3ca27f56041296dc7b857

**Comment by dangermattic** [comment]
Thanks for reporting! 👍
