### ISSUE TITLE
[Woo POS] Do not send price when create an order, only product ids

### ISSUE THREAD

**Issue by kidinov** [woocommerce/woocommerce-android#12144]
https://corvidp2.wordpress.com/2024/07/25/order-total-calculations-in-pos-ignored-prices-with-tax-settings-how-we-fixed-it/#comment-736

`WooPosTotalsRepository::createOrderWithProducts`

(we may need to set price `price = EMPTY_TOTALS_SUBTOTAL_VALUE` so somewhere down the code it won't be set to 0)

We need to test that taxes are calculated as expected too

**Comment by dangermattic** [comment]
🚫 Please add a type label (e.g. **type: enhancement**) and a feature label (e.g. **feature: stats**) to this issue.
