### ISSUE TITLE
[GLA Analytics] Add UI for Google Campaigns call to action

### ISSUE THREAD

**Issue by ThomazFB** [woocommerce/woocommerce-android#12159]
We need to display a card with a call to action (in place of the analytics card) when a merchant has no campaigns:

* Title: `Google Campaigns`
* Message (tentative): `Drive sales and generate more traffic with Google Ads.`
* Button title: `Add paid campaign`
* Button link: Open the in-app campaign creation flow

Note: When a campaign is created successfully, we should reload the card to display the latest analytics.

![Image](https://github.com/user-attachments/assets/a24f5f22-2445-47a7-ba23-5c43ca0ac011)

**Comment by dangermattic** [comment]
🚫 Please add a type label (e.g. **type: enhancement**) and a feature label (e.g. **feature: stats**) to this issue.
