### ISSUE TITLE
[Woo POS] M2: Update UI of payment successful screen

### ISSUE THREAD

**Issue by samiuelson** [woocommerce/woocommerce-android#12169]
* [M2 Designs](https://www.figma.com/design/TfaZ4LUkEwEGrxfnEFzvJj/WooCommerce-POS?node-id=2289-67728&t=o0sWumYr7EN1CHQ3-0)
* Current implementation: 
![Image](https://github.com/user-attachments/assets/e9ac965c-dcd5-4e2c-9f3d-ca3e482ebba7)
* Desired UI:
![Image](https://github.com/user-attachments/assets/6762dc4e-27d3-462e-abb3-2effbea27ea2)
Note: The success checkmark icon is preceded with an animation

**Comment by dangermattic** [comment]
🚫 Please add a type label (e.g. **type: enhancement**) and a feature label (e.g. **feature: stats**) to this issue.

**Comment by samiuelson** [comment]
Duplicate of https://github.com/woocommerce/woocommerce-android/issues/11828
We will want to implement an animated icon, however, we don't have a specification for it yet. I'm closing the issue until then.
