### ISSUE TITLE
[Woo POS] M2: Add bottom padding to products list

### ISSUE THREAD

**Issue by samiuelson** [woocommerce/woocommerce-android#12167]
Bottom padding should be added to the product list to avoid overlaying the last item in the list with the global floating menu:

![Image](https://github.com/user-attachments/assets/e945444f-f5d9-41c9-8844-aaae4dcf3270)

**Comment by dangermattic** [comment]
🚫 Please add a type label (e.g. **type: enhancement**) and a feature label (e.g. **feature: stats**) to this issue.
