### ISSUE TITLE
[Woo POS] M2: "Good bye" screen with session total earnings summary

### ISSUE THREAD

**Issue by samiuelson** [woocommerce/woocommerce-android#12171]
An additional screen should be displayed when exiting the POS mode, displaying the total earned during the session.
* [Design specs](https://www.figma.com/design/TfaZ4LUkEwEGrxfnEFzvJj/WooCommerce-POS?node-id=2298-131303&t=o0sWumYr7EN1CHQ3-0)

![Image](https://github.com/user-attachments/assets/8b5427e4-4627-434d-bfb6-cfef261b8805)

**Comment by dangermattic** [comment]
🚫 Please add a type label (e.g. **type: enhancement**) and a feature label (e.g. **feature: stats**) to this issue.

**Comment by samiuelson** [comment]
I realized it's not ready for dev.
