### ISSUE TITLE
[Woo POS] M2: Display "Couldn't load totals" (order creation failure) error

### ISSUE THREAD

**Issue by samiuelson** [woocommerce/woocommerce-android#12173]
There should be an error displayed in the totals pane in the event of order creation failure, allowing retrying the operation.

* [Design specs](https://www.figma.com/design/TfaZ4LUkEwEGrxfnEFzvJj/WooCommerce-POS?node-id=2877-87886&t=bfG3nKfkvRsb6RZo-0)

![Image](https://github.com/user-attachments/assets/112f95d2-be70-415e-a6aa-ac2d0f29618f)

**Comment by dangermattic** [comment]
🚫 Please add a type label (e.g. **type: enhancement**) and a feature label (e.g. **feature: stats**) to this issue.

**Comment by samiuelson** [comment]
This seems to be already implemented:

![Image](https://github.com/user-attachments/assets/a45a103a-d5e2-4f99-b920-ed6292e3593c)

On Android, we are not performing order updates and the error handling from the screenshot above error is sufficient.
