### ISSUE TITLE
[Woo POS] M2: Update font face

### ISSUE THREAD

**Issue by samiuelson** [woocommerce/woocommerce-android#12174]
In the M2 designs the font face was [modified](https://www.figma.com/design/TfaZ4LUkEwEGrxfnEFzvJj/WooCommerce-POS?node-id=2530-13218&t=bfG3nKfkvRsb6RZo-0) in various places. This task intends to update the font face in all the remaining places in the POS mode, likely on the WooPosTheme level.

**Comment by dangermattic** [comment]
🚫 Please add a type label (e.g. **type: enhancement**) and a feature label (e.g. **feature: stats**) to this issue.

**Comment by samiuelson** [comment]
It seems that the font change was reverted and we should use the default, Roboto font face.
