### ISSUE TITLE
[Woo POS] M2: Update UI of "Exit POS" dialog

### ISSUE THREAD

**Issue by samiuelson** [woocommerce/woocommerce-android#12170]
* [Design scpecs](https://www.figma.com/design/TfaZ4LUkEwEGrxfnEFzvJj/WooCommerce-POS?node-id=2877-88919&t=bfG3nKfkvRsb6RZo-0)

![Image](https://github.com/user-attachments/assets/f26251b8-066d-4d43-84c5-e9792875d6c7)

**Comment by dangermattic** [comment]
🚫 Please add a type label (e.g. **type: enhancement**) and a feature label (e.g. **feature: stats**) to this issue.
