### ISSUE TITLE
[Woo POS] M2: Reader not connected error in totals pane

### ISSUE THREAD

**Issue by samiuelson** [woocommerce/woocommerce-android#12172]
In case the reader is not connected, there should be an additional error message displayed in the Totals pane.
* [Design specs](https://www.figma.com/design/TfaZ4LUkEwEGrxfnEFzvJj/WooCommerce-POS?node-id=2877-87910&t=bfG3nKfkvRsb6RZo-0)

![Image](https://github.com/user-attachments/assets/dd5516b5-241d-490a-ab22-56e8c5f4ec9d)

**Comment by dangermattic** [comment]
🚫 Please add a type label (e.g. **type: enhancement**) and a feature label (e.g. **feature: stats**) to this issue.

**Comment by kidinov** [comment]
@samiuelson I don't think that this is applicable to us as we start reader connection flow if it's not connected and "collect payment" clicked. wdyt?

**Comment by samiuelson** [comment]
> @samiuelson I don't think that this is applicable to us as we start reader connection flow if it's not connected and "collect payment" clicked. wdyt?

Alright, it makes sense to me to skip showing it.
