### ISSUE TITLE
[Woo POS] M2: Hide POS Mode for ineligible users

### ISSUE THREAD

**Issue by staskus** [woocommerce/woocommerce-android#12189]
The 'Point of Sale Mode' menu row should not be visible for users who are not eligible for beta. Add remote feature flag to POS eligibility criteria.

**Comment by dangermattic** [comment]
Thanks for reporting! 👍

**Comment by samiuelson** [comment]
Context and discussions:
1. https://woomobilep2.wordpress.com/2024/07/24/pos-gating-users-into-beta/
2. https://a8c.slack.com/archives/C6H8C3G23/p1721383559637529

**Comment by malinajirka** [comment]
This is now ready to be implemented - the new remote feature flag has key `woo_pos` and is at the moment enabled for all Automattic accounts as well as the `appstestadmin`. @samiuelson could you please implement this on Android?
