### ISSUE TITLE
TTP crashes on Android 14

### ISSUE THREAD

**Issue by malinajirka** [woocommerce/woocommerce-android#12182]
**Describe the bug**

TTP is broken on Android 14 after the recent update of the targetSdkVersion. This issue appears only when minify is enabled so it is reproducible only on release builds.

**To Reproduce**
- Use a device with Android 14 which is meeting TTP requirements.
1. Open an unpaid order
2. Tap on Collect Payment
3. Select Tap to Pay
4. Notice the app crashes

**Expected behavior**

The app doesn't crash and TTP works as expected.

**Comment by dangermattic** [comment]
🚫 Please add a type label (e.g. **type: enhancement**) and a feature label (e.g. **feature: stats**) to this issue.
