### ISSUE TITLE
[Woo POS] Multiple Instances of Card Reader Connection Dialog on Repeated Clicks of "Connect to Reader" Button

### ISSUE THREAD

**Issue by AnirudhBhat** [woocommerce/woocommerce-android#12203]
**Describe the bug**
When the "Connect to Reader" button is clicked multiple times in quick succession, it triggers the card reader connection dialog to open multiple instances. This behaviour is not expected, as it can confuse users and potentially lead to unintended interactions with the card reader.

**To Reproduce**
Steps to Reproduce:

1. Navigate to the settings screen and ensure you see Point of sale option
2. Click on the point of sale option
3. Ensure you see the "Connect to Reader" button is available.
4. Click on the "Connect to Reader" button multiple times quickly.
5. Observe that multiple instances of the card reader connection dialog are opened.

**Screenshots**

https://github.com/user-attachments/assets/f22cc1e2-5793-489d-8722-bc35ba2f3647

**Expected behavior**
Clicking the "Connect to Reader" button should only open a single instance of the card reader connection dialog. Subsequent clicks should be ignored.

**Comment by dangermattic** [comment]
Thanks for reporting! 👍
