### ISSUE TITLE
[Woo POS] M2: Implement Payment success screen as per design

### ISSUE THREAD

**Issue by kidinov** [woocommerce/woocommerce-android#12222]
https://www.figma.com/design/TfaZ4LUkEwEGrxfnEFzvJj/WooCommerce-POS?node-id=2877-89385&t=B6Q2oh658RIviTet-0

![Image](https://github.com/user-attachments/assets/b7b82d52-666c-46c6-877d-1a632ca013eb)

**Comment by dangermattic** [comment]
🚫 Please add a type label (e.g. **type: enhancement**) and a feature label (e.g. **feature: stats**) to this issue.
