### ISSUE TITLE
[Woo POS] Fix error state as now it doesn't match the design

### ISSUE THREAD

**Issue by kidinov** [woocommerce/woocommerce-android#12223]
Now it has a background that doesn't work, for instance, for products.

Also, there is a divider which must be optional. And it's called `WooPosErrorState` - shell it be "screen" or "component"?

![Image](https://github.com/user-attachments/assets/268c22d5-390e-4ba9-9d97-fc99bdffd748)

![Image](https://github.com/user-attachments/assets/a532d288-c929-4794-8803-c7701de72c73)

**Comment by dangermattic** [comment]
Thanks for reporting! 👍
