### ISSUE TITLE
Toolbar appearing twice in Package details screen

### ISSUE THREAD

**Issue by AnirudhBhat** [woocommerce/woocommerce-android#12236]
**Describe the bug**
We are displaying Toolbar 2 times in package detail screen while creating Shipping label. 

**To Reproduce**
1. Navigate to order detail screen which is eligible for creating Shipping label
2. Click on Shipping Label button
3. Enter from and to address
4. Navigate to package detail screen
5. We see two toolbar instead of one

**Screenshots**
![package_details_multiple_toolbar](https://github.com/user-attachments/assets/b5128456-bc8e-4683-94a5-cc13752bbd24)

**Expected behavior**
We should be seeing just a single toolbar in Package details screen

**Comment by dangermattic** [comment]
Thanks for reporting! 👍
