### ISSUE TITLE
LearnMore in Payments is cut-off

### ISSUE THREAD

**Issue by malinajirka** [woocommerce/woocommerce-android#12241]
**Describe the bug**
The learn more section at the bottom of the payments screen is cut off on my Pixel 8 Android 14.

**To Reproduce**
1. Go to More menu
2. Click on Payments
3. Scroll down
4. Notice the last section is cut off by the screen edge.

**Screenshots**
<img src="https://github.com/user-attachments/assets/fd43cf97-52f8-41fa-8c43-fffcdb7a2220" width="250px" />

**Expected behavior**

The section is properly rendered on the screen.

**Comment by dangermattic** [comment]
Thanks for reporting! 👍

**Comment by malinajirka** [comment]
@backwardstruck  Is this please something you could look into?
