### ISSUE TITLE
UI updates to support endless campaigns (Evergreen)

### ISSUE THREAD

**Issue by JorgeMucientes** [woocommerce/woocommerce-android#12248]
Use the design updates from [this PR](https://github.com/woocommerce/woocommerce-ios/pull/13523) as reference

```[tasklist]
### UI Updates
- [x] Campaign creation flow UI updates: https://github.com/woocommerce/woocommerce-android/pull/12324
- [ ] https://github.com/woocommerce/woocommerce-android/issues/12389
```

**Comment by dangermattic** [comment]
🚫 Please add a type label (e.g. **type: enhancement**) and a feature label (e.g. **feature: stats**) to this issue.
