### ISSUE TITLE
Support text recognition for Japanese, Chinese and Korean

### ISSUE THREAD

**Issue by JorgeMucientes** [woocommerce/woocommerce-android#12242]
Currently, the Android ML kit text recognition API we are using to scan text from images when adding a product using AI doesn't work for Japanese, Chinese and Korean: 

<img width="300"  src="https://github.com/user-attachments/assets/70422296-2a08-4ea6-9571-33cd997dcded"> 

These languages require an extra dependency for each of the languages. These dependencies increase the app bundle size significantly (~4MB each) so the idea is to download them on demand, if the feature is needed. 

Using [the model from Google Play Services](https://developers.google.com/ml-kit/tips/installation-paths) the download of the package can be deferred to the moment the feature is needed for the first time. 
```
    implementation "com.google.android.gms:play-services-mlkit-text-recognition-japanese:$mlkitTextRecognitionVersion"
    implementation "com.google.android.gms:play-services-mlkit-text-recognition-chinese:$mlkitTextRecognitionVersion"
    implementation "com.google.android.gms:play-services-mlkit-text-recognition-korean:$mlkitTextRecognitionVersion"
```

When scanning an image for text, we don't know which language the text is going to be. As a best effort, what we can do is check the user's device language/locale, download the text recognition scanner for that language (Japanese, Chinese, Korean), and attempt to scan the image using the downloaded.

**Comment by dangermattic** [comment]
Thanks for reporting! 👍
