### ISSUE TITLE
[WOO POS] M2: Pull to refresh in products screen breaks pagination

### ISSUE THREAD

**Issue by AnirudhBhat** [woocommerce/woocommerce-android#12240]
**Describe the bug**

In POS mode on the products screen, the pull-to-refresh action breaks pagination, resulting in only the first page of products being loaded.

**To Reproduce**
1. Navigate to the POS mode from settings
2. Ensure you see all the products
3. Pull to refresh
4. Now, only the first page products are loaded and pagination breaks

**Screenshots**

https://github.com/user-attachments/assets/61803441-90b4-4d5e-af92-775183d72604

**Expected behavior**
Pagination shouldn't break on pull to refresh

**Comment by dangermattic** [comment]
🚫 Please add a type label (e.g. **type: enhancement**) and a feature label (e.g. **feature: stats**) to this issue.

**Comment by kidinov** [comment]
@AnirudhBhat there is a change regarding products so maybe better to fix it on top of that 

https://github.com/woocommerce/woocommerce-android/pull/12228

**Comment by AnirudhBhat** [comment]
>there is a change regarding products so maybe better to fix it on top of that

Sure. Thanks for the heads up!
