### ISSUE TITLE
[Woo POS] Transition back from the success screen to the products is not ideal

### ISSUE THREAD

**Issue by kidinov** [woocommerce/woocommerce-android#12249]
The transition proposed in the design may be too hard to implement but we can do better with our current transition - for instance, we should not hide the success state and replace it with "checkout loading" and just slide it to the right

![Image](https://github.com/user-attachments/assets/fb8276cf-e966-4458-a6b8-95a58404f5ce)

https://github.com/user-attachments/assets/09b3bb5d-b4d4-4122-90a4-2f720676079d

**Comment by dangermattic** [comment]
🚫 Please add a type label (e.g. **type: enhancement**) and a feature label (e.g. **feature: stats**) to this issue.
