### ISSUE TITLE
SKU text not ellipsized in Order Details screen

### ISSUE THREAD

**Issue by samiuelson** [woocommerce/woocommerce-android#12243]
**Describe the bug**
A clear and concise description of what the bug is. Please be as descriptive as possible; issues lacking detail, or for any other reason than to report a bug, may be closed without action.
SKU text not ellipsized in Order Details screen

**To Reproduce**
1. Create order with item having long SKU name
2. Go to Order Detail screen

**Screenshots**

<img src=https://github.com/user-attachments/assets/54e5b873-5b48-463b-ac05-706c46e2a39d width=300/>

**Expected behavior**
Long SKU should be ellipsized at the end.

</details>

**Comment by dangermattic** [comment]
Thanks for reporting! 👍
