### ISSUE TITLE
Order Creation: Item Discount is overiden by coupon

### ISSUE THREAD

**Issue by malinajirka** [woocommerce/woocommerce-android#12259]
**Describe the bug**
Both discounts and coupons can be applied to the same order but they are overiding each other - only one of them is actually applied.

**To Reproduce**
1. Create an order
2. Add a product
3. Apply an item discount
4. Apply a coupon
5. Notice only the coupon is taken into account.

**Screenshots**

https://github.com/user-attachments/assets/004d4114-5d12-4d90-b741-39bef9cc7c07

**Expected behavior**
Coupons should be disabled when a discount is applied and visa-versa.

**Comment by dangermattic** [comment]
🚫 Please add a type label (e.g. **type: enhancement**) and a feature label (e.g. **feature: stats**) to this issue.
