### ISSUE TITLE
[Woo POS] Double check padding vs physical spacing in Payment Success Screen

### ISSUE THREAD

**Issue by backwardstruck** [woocommerce/woocommerce-android#12264]
Context here:

"@backwardstruck Setting adaptive paddings to the "sizes" may not be a good idea, especially on the buttons, as those must have specific physical sizes to be easy-clickable. We may want to set it only on the padding/margins"

https://github.com/woocommerce/woocommerce-android/pull/12224#discussion_r1705282750

**Comment by dangermattic** [comment]
🚫 Please add a type label (e.g. **type: enhancement**) and a feature label (e.g. **feature: stats**) to this issue.

**Comment by kidinov** [comment]
@backwardstruck 👋

I think I fixed that already a few days ago when was implementing the success screen. Feel free to reopen if it's still there

**Comment by backwardstruck** [comment]
Yes. I think it looks good. Thank you for fixing it for me:
![Screenshot_20240809_102325](https://github.com/user-attachments/assets/ff543cdf-a149-4ce0-b1ba-7f0ad37b5c40)
