### ISSUE TITLE
[Woo POS] Move state from composable ProductsInfoDialog to VM. Wrap in with Box and hide on click outside

### ISSUE THREAD

**Issue by kidinov** [woocommerce/woocommerce-android#12268]

**Comment by dangermattic** [comment]
🚫 Please add a type label (e.g. **type: enhancement**) and a feature label (e.g. **feature: stats**) to this issue.

**Comment by AnirudhBhat** [comment]
Duplicate of https://github.com/woocommerce/woocommerce-android/issues/12291
