### ISSUE TITLE
[Woo POS] M2: Improve accessibility: TalkBack

### ISSUE THREAD

**Issue by kidinov** [woocommerce/woocommerce-android#12270]
pfoUAQ-SL-p2

* I could not take into focus the “checkout” bottom on the cart sub-screen, so I had to click on it twice, which may not be possible for some people
* I didn’t manage to scroll the list of products to the next page

**Comment by dangermattic** [comment]
🚫 Please add a type label (e.g. **type: enhancement**) and a feature label (e.g. **feature: stats**) to this issue.
