### ISSUE TITLE
Selecting a shipping service UI

### ISSUE THREAD

**Issue by atorresveiga** [woocommerce/woocommerce-android#12285]
![Image](https://github.com/user-attachments/assets/5f28366f-9cac-4835-849e-5c1ab05bfb90)

![Image](https://github.com/user-attachments/assets/805ff521-2e1c-4fae-af72-be787bb2126d)

Landscape

![Image](https://github.com/user-attachments/assets/e43ca206-fa16-4a7b-a539-092b0b0f35a9)

Design considerations:

> - After adding a package, we reveal the shipping service section and the disabled purchase button (previously hidden to reduce distractions and save space).
> - Let’s add the total cost to the purchase button.
> - Also, the screen will scroll so that the added package is at the top.
> - To save space, I’ve revised the order of elements in the service card and removed the labels from the order details – replacing them with icons.
> - Lastly, after speaking with @alejo, we decided that it would probably be possible to update the shipping services while the merchant updates the total shipment weight. This means we don’t need to add a refresh button like the web has.

**Comment by dangermattic** [comment]
Thanks for reporting! 👍
