### ISSUE TITLE
[Shipping Labels: Packages] Main task: Adding package UI

### ISSUE THREAD

**Issue by atorresveiga** [woocommerce/woocommerce-android#12282]
![Image](https://github.com/user-attachments/assets/de39b1f1-9e55-4d11-ac87-f3dce083f7fd)

![Image](https://github.com/user-attachments/assets/58a9be32-3920-456b-9158-25a7c72937fd)

Design considerations:

> - This is almost the same as what’s on the web.
> - By opening it in a sheet, we can let the lists run long without using accordions (which are always awkward on mobile and rarely used anymore).
> - Saving a package template will match the web quite closely.
This isn’t on the web, but providing a quiet way to remove saved packages feels natural.

```[tasklist]
### Tasks
- [ ] https://github.com/woocommerce/woocommerce-android/issues/12744
- [ ] https://github.com/woocommerce/woocommerce-android/issues/12745
- [ ] https://github.com/woocommerce/woocommerce-android/issues/12746
- [ ] https://github.com/woocommerce/woocommerce-android/issues/12747
```

**Comment by dangermattic** [comment]
Thanks for reporting! 👍
