### ISSUE TITLE
[Order form] Custom amounts are not fully disabled when order editing is disabled

### ISSUE THREAD

**Issue by rachelmcr** [woocommerce/woocommerce-android#12299]
**Describe the bug**

When I am editing an order with the `processing` status, some sections of the order form should not be editable. Although I see a lock icon on the Custom Amounts section, if the order doesn’t have any custom amounts I am still able to add a new amount to the order. If the order already has a custom amount, I see a pencil icon next to the amount but it doesn’t do anything.

**To Reproduce**
1. Go to the Orders tab.
2. Select an order with the `processing` status, and without a custom amount.
3. Edit the order.
4. In the order form, add a custom amount. Notice that you can add a new amount even though the section has a lock icon.
5. In the order form, notice that the added custom amount shows a pencil icon, but tapping it does nothing.

**Screenshots**

Add custom amount|Edit custom amount
-|-
![image](https://github.com/user-attachments/assets/ea0decff-2720-4ce4-a34e-919bcab36b11)|![image](https://github.com/user-attachments/assets/8fb510bb-05f8-4b35-9ecb-285e650a6528)

**Expected behavior**

I expect that for orders with limited editing (e.g. with `processing` status):

* Adding custom amounts will be disabled.
* Editing custom amounts will be disabled.

When the section has editing disabled, the UI to add/edit the custom amounts will be hidden or show a disabled status.

**Comment by dangermattic** [comment]
Thanks for reporting! 👍
