### ISSUE TITLE
[Products] Error when filtering by "Low stock" products

### ISSUE THREAD

**Issue by rachelmcr** [woocommerce/woocommerce-android#12296]
**Describe the bug**

Filtering: When I try to filter for “Low Stock” products, I get an error. The app logs show an error: `Fetching products failed, error: INVALID_PARAM: Invalid parameter(s): stock_status`.

**To Reproduce**
1. Go to the Products tab.
2. Select `Filter`.
3. Select `Stock status`.
4. Select `Low stock`.
5. Tap the `Show products` button.
6. Notice the error on the Products list.

**Screenshots**

Filter options|Error on product list
-|-
![image](https://github.com/user-attachments/assets/3e02d84f-9a11-458c-bde6-d5cd4372d9da)|![image](https://github.com/user-attachments/assets/c742d9c4-61e0-4580-85ba-30612ec571fc)

**Expected behavior**

I expect the product list to be filtered to include only low stock products, or if that isn't an option on my store, I expect to only see filter options that are supported on my store.

**Comment by dangermattic** [comment]
Thanks for reporting! 👍
