### ISSUE TITLE
[Products] Error when filtering my product types not supported on my store

### ISSUE THREAD

**Issue by rachelmcr** [woocommerce/woocommerce-android#12297]
**Describe the bug**

When I filter by product type, I see types that are not supported on my store (they require extensions I don’t have installed). When I try to filter for them, I get an error. The app logs show an error: `Fetching products failed, error: INVALID_PARAM: Invalid parameter(s): type`.

**To Reproduce**
1. Go to the Products list.
2. Select `Filter`.
3. Select `Product type`.
4. Select a product type requiring an extension not installed on your store, e.g. `Composite products` without the [composite products extensions](https://woocommerce.com/products/composite-products/).
5. Tap the `Show products` button.
6. Notice the error on the Products list.

**Screenshots**

Filter|Error on product list
-|-
![image](https://github.com/user-attachments/assets/110972af-1995-43f1-8595-9abc5ef0cdcf)|![image](https://github.com/user-attachments/assets/b8238a2a-fb1a-4e14-82b2-39feaaacde48)

**Expected behavior**

I expect to not be able to select/filter by product types that are not supported on my store. If non-supported types are visible in the list, I expect to see an `Explore` button, and tapping the row/button takes me to the extension product page.

**Comment by dangermattic** [comment]
Thanks for reporting! 👍

**Comment by rachelmcr** [comment]
It looks like this issue was specific to a particular site that had some plugin issues. I can't reproduce it on other sites and fixing/updating the plugins on this site has resolved it there. Closing as invalid.
