### ISSUE TITLE
Login: Remove extra spacing in divider bar

### ISSUE THREAD

**Issue by AmandaRiu** [woocommerce/woocommerce-android#1229]
Remove extra spacing between the site list and the bottom buttons on the login views.

<img width="445" alt="60982617-b8a4b500-a2f5-11e9-9830-5ca222043637 png (1080×2220) 2019-07-10 11-47-12" src="https://user-images.githubusercontent.com/5810477/60985068-06232100-a2fa-11e9-80ab-1dac8d5bef48.png">

**Comment by nbradbury** [comment]
Closing this as we no longer show the site list after login.
