### ISSUE TITLE
[Woo POS] M2: Refactor process death handling logic for Products info dialog

### ISSUE THREAD

**Issue by AnirudhBhat** [woocommerce/woocommerce-android#12291]
The goal of this task is to refactor process death handling logic for Products info dialog. Currently, this logic resides in the UI layer (Compose component). Move this to the view model.

**Comment by dangermattic** [comment]
Thanks for reporting! 👍

**Comment by kidinov** [comment]
@AnirudhBhat is this the same as that one https://github.com/woocommerce/woocommerce-android/issues/12268? If it is, could you please close one of this?
