### ISSUE TITLE
[Products] No discard confirmation when exiting product details

### ISSUE THREAD

**Issue by rachelmcr** [woocommerce/woocommerce-android#12298]
**Describe the bug**

There is no discard confirmation if I exit the product details with unsaved changes. My changes are just discarded with no warning.

**To Reproduce**
1. Go to the Products tab.
2. Select an existing product.
3. Change or add product details.
4. Tap the back button to exit the product details and notice there is no confirmation before the changes are discarded.

**Screenshots**

https://github.com/user-attachments/assets/d54e18b7-cd76-4cb1-a794-79c8287263ec

**Expected behavior**

I expect a discard confirmation dialog if there are unsaved changes to the product.

**Comment by dangermattic** [comment]
Thanks for reporting! 👍
