### ISSUE TITLE
It's not possible to remove a coupon from order

### ISSUE THREAD

**Issue by samiuelson** [woocommerce/woocommerce-android#12307]
**Describe the bug**
A clear and concise description of what the bug is. Please be as descriptive as possible; issues lacking detail, or for any other reason than to report a bug, may be closed without action.
This is impossible to remove a coupon, once it's added to an order.

**To Reproduce**
1. Create new order
2. Add at least one product, to enable "+ Add coupon" button
3. Tap "+Add coupon" and select a coupon from the list
4. Observe coupon being successfully applied to the order, resulting in a discount visible on the bottom Totals pane
5. Verify there is no way to remove the coupon

**Screenshots**

**Expected behavior**
There should be a way to remove a coupon from the order. Initially, we had implemented the following UX, allowing coupon removal. Unfortunately, now it's impossible to click on the coupon and redirect to the coupon details screen:
<img src=https://github.com/user-attachments/assets/e7b6c216-0810-4760-abde-5eea67bf80da width="300"/>
the video above is from version 14.9 of the app.

**Mobile Environment**
Please include:
- Device: phone and tablet
- Android version: 14
- WooCommerce Android version: 19.9

**WordPress Environment**
<details>
```
Copy and paste the system status report from **WooCommerce > System Status** in WordPress admin.
```
</details>

**Comment by dangermattic** [comment]
Thanks for reporting! 👍

**Comment by samiuelson** [comment]
This was a false alarm. After thorough testing, I confirmed it's possible to remove coupons from the order. See the video below:

https://github.com/user-attachments/assets/2677c665-2c93-4585-b247-d668ecb7ab82

I didn't spot any more issues related to coupons – the UX looks good. That said, I'm closing the issue.
