### ISSUE TITLE
Disable QR code scanner CTA from login flow. 

### ISSUE THREAD

**Issue by JorgeMucientes** [woocommerce/woocommerce-android#12301]
Full context and discussion here: p1723448778949849-slack-C01SFMVEYAK

The QR code API that was hosted by Google, that we were using for the QR code login is now defunct. This is causing a broken image link in WooCommerce mobile logins. The stopgap right now is to remove the QR code image from the login email, but in the long run we should complete this task: https://github.com/woocommerce/team-ghidorah/issues/325

<img width="1418" alt="Screenshot 2024-08-12 at 09 44 54" src="https://github.com/user-attachments/assets/9a3bed4b-f907-4042-be65-96c8f4af39a0">

**Comment by dangermattic** [comment]
Thanks for reporting! 👍

**Comment by JorgeMucientes** [comment]
Work done in the backend can be followed here: https://github.com/woocommerce/team-ghidorah/issues/343

**Comment by JorgeMucientes** [comment]
Backend changes can be tracked here: https://github.com/woocommerce/team-ghidorah/issues/343

**Comment by JorgeMucientes** [comment]
Reopening because there's one screen that still has the CTA enabled: p1725282588343009/1725282268.106619-slack-CGPNUU63E

<img width="300"  src="https://github.com/user-attachments/assets/93b41f86-e096-48bc-be79-3bd40cf779b3">

**Comment by JorgeMucientes** [comment]
Closing this. The first fix is enough and removes the "Scan QR code to log in" from everywhere.
There was some confusion about the version in which the fix was merged.
