### ISSUE TITLE
Display "undo" toast action when opening product review

### ISSUE THREAD

**Issue by JorgeMucientes** [woocommerce/woocommerce-android#12302]
Coming from the Android quality walkthrough: p1723448778949849-slack-C01SFMVEYAK

When opening a push notification for product reviews and then taking an action (e.g., Trash, Spam, Approve), the review detail screen is closed, but I don’t see any option to undo the action. I expect to see a toast message with the option to undo — especially for destructive actions like trashing/spamming that make the review unavailable in the app. (This works as expected when the review is opened from the reviews list.)

https://video.wordpress.com/v/DxGhJbsh

**Comment by dangermattic** [comment]
Thanks for reporting! 👍
