### ISSUE TITLE
[Woo POS] M2: Adjust the UI of the connection flow

### ISSUE THREAD

**Issue by kidinov** [woocommerce/woocommerce-android#12315]
~~Not decided yet - p1723552324801109-slack-C070SJRA8DP~~

* We add pictures as per design
* We make both connection and payment flow wide on the POS supported devices 
* We try to add animated SVG (time box it)

**Comment by dangermattic** [comment]
🚫 Please add a type label (e.g. **type: enhancement**) and a feature label (e.g. **feature: stats**) to this issue.

**Comment by kidinov** [comment]
So at the end we decided to not touch the flows at all for M2
