### ISSUE TITLE
[Woo POS] M2: Remove custom text style, extract overlay into reusable base in product info dialog

### ISSUE THREAD

**Issue by AnirudhBhat** [woocommerce/woocommerce-android#12322]
The goal of this task is to remove custom text style and instead use the one available from `MaterialTheme` and extract overlay used in product info dialog into reusable base for all dialogs.

Context: https://github.com/woocommerce/woocommerce-android/pull/12267#pullrequestreview-2235199513

**Comment by dangermattic** [comment]
Thanks for reporting! 👍

**Comment by kidinov** [comment]
@AnirudhBhat I also noticed that there is a huge top margin on the exit pos dialog
