### ISSUE TITLE
[Mobile Payments] Add support for `pending_verification` account status

### ISSUE THREAD

**Issue by joshheald** [woocommerce/woocommerce-android#12328]
## Description

WooPayments has a new(ish) account status, used early in an accounts lifetime: `pending_verification`. 

This was not decoded on iOS, so resulted in the merchant seeing a generic onboarding error, which was a bad first experience using WooPayments if they chose it for IPP. See https://github.com/woocommerce/woocommerce-ios/issues/13581 and https://github.com/woocommerce/woocommerce-ios/pull/13610 for context around the iOS fix.

Looking at the Android logic, it's likely that the same thing will happen in the Android app

## Repro steps

1. Create a new Jurassic Ninja site – include WooCommerce, WooPayments, and WooPayments Dev Tools
2. Link the site with your Jetpack user
3. Add a US address in WooCommerce settings
4. Activate WooPayments
5. Go through the onboarding steps in WP-Admin > Payments > Activate
6. Launch the app and switch to your new site
7. Go to `Menu > Payments`
8. Tap the `Continue` button in the onboarding notice that shows
9. Observe that you're shown a generic `Unable to verify` onboarding error (after skipping anything skippable)

Expectation – you should be able to take payments, without seeing the onboarding error.

Note that there is also another WooPayments bug which results in accounts going to `restricted` status after their first payment – so after this payment, you may see the generic onboarding error until that's fixed. Ongoing investigation around that here: https://github.com/woocommerce/woocommerce-ios/issues/13615

**Comment by dangermattic** [comment]
Thanks for reporting! 👍

**Comment by backwardstruck** [comment]
Able to reproduce:
![Screenshot_20240814_142100](https://github.com/user-attachments/assets/dfc14a5c-3c0b-4477-9aba-5620f8840ab6)
