### ISSUE TITLE
Log a case when order and store currencies mismatch

### ISSUE THREAD

**Issue by staskus** [woocommerce/woocommerce-android#12335]
## Description

For multi-currency stores, when the account has a different default currency, there can be cases when the order currency doesn't match the store's currency.

We don't handle multi-currency comprehensively in the apps:
- https://github.com/woocommerce/woocommerce-android/issues/11273
- https://github.com/woocommerce/woocommerce-ios/issues/13580

For the moment, we decided to log this particular case so it would be easier to detect and debug in the future: p91TBi-bPj-p2#comment-12874

## Task

Log when order currency doesn't match store currency when the payment method selection view is opened. See iOS implementation: https://github.com/woocommerce/woocommerce-ios/pull/13626

**Comment by dangermattic** [comment]
Thanks for reporting! 👍
