### ISSUE TITLE
[Woo POS] Products background has incorrect color. screen has rounded corners instead of being flat

### ISSUE THREAD

**Issue by kidinov** [woocommerce/woocommerce-android#12346]
![Image](https://github.com/user-attachments/assets/20dc26b2-3e90-4e72-a7d8-9d5b348ee287)

![Image](https://github.com/user-attachments/assets/4d42236a-e803-4a43-b4d9-2665d85c8244)

**Comment by dangermattic** [comment]
Thanks for reporting! 👍
