### ISSUE TITLE
Allow card-present IPP methods for FAILED order

### ISSUE THREAD

**Issue by samiuelson** [woocommerce/woocommerce-android#12348]
Context: p91TBi-bWp-p2

Following recent update of payments-server, after failed payment the order status is changed to FAILED. However, to allow collecting payment again, we need to update the card reader collectibility criteria to allow payments for FAILED orders being collected.

**Comment by dangermattic** [comment]
🚫 Please add a type label (e.g. **type: enhancement**) and a feature label (e.g. **feature: stats**) to this issue.
