### ISSUE TITLE
IPP in UK and Canada Displays Unknown Error on Incorrect PIN entry

### ISSUE THREAD

**Issue by malinajirka** [woocommerce/woocommerce-android#12350]
**Describe the bug**
When the user enters a wrong pin number or if we use `x.55` test amount in test mode, the app displays `The payment was declined for an unknown reason`.

**To Reproduce**
1. Go Order List
2. Start the order creation flow
3. Enter custom amount ending with x.55 (eg. 1.55)
4. Collect payment using a card reader
5. Notice the payment fails with an unknown error

**Screenshots**

![Screenshot_20240816-091752](https://github.com/user-attachments/assets/a8f269e7-64f2-42ad-9e7c-7397c6ee18bc)

**Expected behavior**
The app should inform the user that an incorrect PIN was entered - ~something like `Incorrect PIN entered. Please try again`~ we can use the String from ios `An incorrect PIN has been entered. Try again, or use another means of payment`

**Comment by dangermattic** [comment]
Thanks for reporting! 👍

**Comment by malinajirka** [comment]
@kidinov @AnirudhBhat Could one of you please look into this? I noticed the behavior [is consistent with iOS](https://github.com/woocommerce/woocommerce-ios/issues/13632), but seems like something we forgot to update as we expanded to UK/CA (in the US this is not necessary, since the M2 reader doesn't have a keyboard).

Update: this was fixed yesterday on iOS https://github.com/woocommerce/woocommerce-ios/pull/13606

**Comment by joshheald** [comment]
Note that we say `This card requires a PIN code and thus cannot be processed. Try another means of payment` for the following errors on iOS:

- "invalid_pin"
- "offline_pin_required"
- "online_or_offline_pin_required"

These are M2-centric error messages, i.e. there's no reader support for PIN entry. This is because when the WisePad3 is used, it handles the PIN flow without these errors being surfaced to the app.

**Comment by joshheald** [comment]
See DeclineReason [error messages](https://github.com/woocommerce/woocommerce-ios/blob/49067c123c4199045d7ac9553d6286d03b526742/Hardware/Hardware/CardReader/DeclineReason.swift#L100) and our [map of Stripe error codes to DeclineReasons](https://github.com/woocommerce/woocommerce-ios/blob/49067c123c4199045d7ac9553d6286d03b526742/Hardware/Hardware/CardReader/StripeCardReader/DeclineReason%2BStripe.swift#L7) for the logic we use on iOS

**Comment by malinajirka** [comment]
We currently use `<string name="card_reader_payment_failed_pin_required">This card requires a PIN code and thus cannot be processed</string>` for the M2 specific ones. Maybe we can add the `Try another means of payment` as part of this PR as well.

> Note that we say This card requires a PIN code and thus cannot be processed. Try another means of payment for the following errors on iOS:

I've updated the description with this phrasing. Thanks!
