### ISSUE TITLE
Error installing and activating Jetpack the plugin when sites are already Jetpack CP 

### ISSUE THREAD

**Issue by JorgeMucientes** [woocommerce/woocommerce-android#12364]
### Description 
When attempting to install and connect Jetpack, if the site already has a Jetpack CP connection the flow will always fail. 

**To Reproduce**
1. Create a jurassic.ninja site with WooCommerce and without Jetpack Plugin
2. Connect WooCommerce to Jetpack CP or install any plugin that uses Jetpack CP (WC payments, Google Ads, etc) and connect it to Jetpack CP
3. Log into the site using WP.com credentials
4. Click on on the banner and trigger Jetpack installation flow. 
5. See the error from the screen recording below. 

https://github.com/user-attachments/assets/ef7a09b4-eabd-4608-81f6-eb1bf48d14fd

**Cause**
The reason for this bug is that in this scenario, after installing and activating Jetpack plugin successfully, when checking the status of the connection for the site, the response from `me/sites` endpoint still returns:
```json
  "jetpack": false,
  "jetpack_connection": true,
```

However, if we instead get the site info from `v1.1/sites/$siteId` we'll get the correct values: 
```json
  "jetpack": true,
  "jetpack_connection": true,
```

 
I suspect the underlying reason for this behavior is probably related to the use of the cached site values (despite jetpack plugin being installed): peaMlT-GP-p2#comment-1671

**Expected behavior**
The installation flow should complete without errors after all the installation/activation steps are completed. 

https://github.com/user-attachments/assets/79e38842-a3e2-4802-ab8d-2a570f57d015

### Extra

The current flow is showing 2 of the main CTAs with the wrong color. The buttons should be updated to primary color Woo purple.

**Comment by dangermattic** [comment]
Thanks for reporting! 👍
