### ISSUE TITLE
[Blaze] Update campaign creation request to respect the ISO date format

### ISSUE THREAD

**Issue by hichamboushaba** [woocommerce/woocommerce-android#12370]
Currently, when sending the campaign creation request, the app sends the date formatted using the device's locale, which might result when using some languages such as Arabic in using digits other than regular Arabic numerals (for example: `٢٠٢٤-٠٧-٠٨`), which is not a standard ISO date format.

**Comment by dangermattic** [comment]
Thanks for reporting! 👍
