### ISSUE TITLE
[WOO POS]M2: Close icon color and margin between text is not as per design in Product info dialog

### ISSUE THREAD

**Issue by AnirudhBhat** [woocommerce/woocommerce-android#12379]
**Describe the bug**
Close icon color and margin between text is not as per design in Product info dialog

**Figma Design**
<img width="641" alt="Screenshot 2024-08-20 at 5 55 07 PM" src="https://github.com/user-attachments/assets/668ea840-2f4f-40c1-829f-3067047d6ce5">

**Implemented Design**

<img width="592" alt="Screenshot 2024-08-20 at 5 55 23 PM" src="https://github.com/user-attachments/assets/e9f928ed-708c-47a2-ad0b-69f7af497e22">

**Comment by dangermattic** [comment]
Thanks for reporting! 👍
