### ISSUE TITLE
Order Details: Update Customer Information section

### ISSUE THREAD

**Issue by mindgraffiti** [woocommerce/woocommerce-android#1238]
Update the Customer Information section to follow the Refunds i3 design:

- [ ] Investigate what is required to add a customer gravatar
- [ ] P2 findings or write a separate task if it's a quick task
- [ ] Update Customer Information section layout

<img width="454" alt="Screen Shot 2019-07-12 at 10 05 25 AM" src="https://user-images.githubusercontent.com/1062444/61138314-e2dcab00-a48c-11e9-923e-d2a46198ed70.png">

**Comment by anitaa1990** [comment]
@mindgraffiti, could we implement this as a standalone feature or is this part of the refunds project?

**Comment by anitaa1990** [comment]
@mindgraffiti @kyleaparker, I was investigating what it takes to include the customer avatar for the above design. I found the [Retrieve a customer API](https://woocommerce.github.io/woocommerce-rest-api-docs/#retrieve-a-customer) in the REST API docs. We would need to call this API to get the avatar URL.

But I'm not able to find any information that would identify whether the customer is a **New Customer** or an **Existing customer** from the response. This is the response we receive from the API:
```
{
	"data": {
		"id": 3,
		"date_created": "2019-03-18T06:09:49",
		"date_created_gmt": "2019-03-18T06:09:49",
		"date_modified": "2019-06-20T09:26:25",
		"date_modified_gmt": "2019-06-20T09:26:25",
		"email": "reallychumma1@gmail.com",
		"first_name": "Anitaa",
		"last_name": "Murthy",
		"role": "administrator",
		"username": "murthyanitaa",
		"billing": {
			"first_name": "RefundCoupon",
			"last_name": "Testing",
			"company": "",
			"address_1": "sample",
			"address_2": "",
			"city": "Chicago",
			"postcode": "94110",
			"country": "US",
			"state": "CA",
			"email": "tdroid085@gmail.com",
			"phone": ""
		},
		"shipping": {
			"first_name": "RefundCoupon",
			"last_name": "Testing",
			"company": "",
			"address_1": "sample",
			"address_2": "",
			"city": "Chicago",
			"postcode": "94110",
			"country": "US",
			"state": "CA"
		},
		"is_paying_customer": true,
		"avatar_url": "https://secure.gravatar.com/avatar/899de2e0dc94bd1dbfe2f52d2508d44a?s=96&d=mm&r=g"
	}
}
```

**Comment by kyleaparker** [comment]
I wish that included the number of orders! We can always leave that out for now - would the ```date_created``` give us a clue?

**Comment by AmandaRiu** [comment]
@kyleaparker @mindgraffiti @anitaa1990 I've opened a request to add either `orders_count` or `new_customer` to the customer API response [here](https://github.com/woocommerce/woocommerce/issues/24187).

**Comment by kyleaparker** [comment]
My thinking was that if date created matched the order date they are probably a new customer. I think that's probably a but hacky though and we should wait until we have the data we need.

**Comment by AmandaRiu** [comment]
> My thinking was that if date created matched the order date they are probably a new customer. I think that's probably a but hacky though and we should wait until we have the data we need.

That may work actually. Can you test through this option to see if we can differentiate between new and existing customers based on the `date_created`?

**Comment by pmusolino** [comment]
Hi there! I'm working on the iOS implementation and I'm reading your useful comments.
I'll do a test to check if I can use `date_created` comparing it to the current date (day granularity).

**Comment by anitaa1990** [comment]
Completed in #1373 so closing
