### ISSUE TITLE
Campaign list UI updates

### ISSUE THREAD

**Issue by JorgeMucientes** [woocommerce/woocommerce-android#12389]
Discussion: p1723791455674239-slack-C0354HSNUJH

**Agreed design:** 

<img width="300"  src="https://github.com/user-attachments/assets/9d340b00-300c-49bd-a95a-29cd2fa963f0"> 

- Budget field to be more specific like Total budget/ Remaining budget / Weekly budget  depending on  whether a campaign as an end date or not and if it's active or already finished.

**Comment by dangermattic** [comment]
🚫 Please add a type label (e.g. **type: enhancement**) and a feature label (e.g. **feature: stats**) to this issue.
