### ISSUE TITLE
[Woo POS] Products and Cart toolbars' shadows not aligned

### ISSUE THREAD

**Issue by samiuelson** [woocommerce/woocommerce-android#12394]
Products and Cart toolbars sizes (shadows) are not aligned:

![Image](https://github.com/user-attachments/assets/bcdc7410-08ad-43ca-b575-dea3e578fad2)

**Comment by dangermattic** [comment]
🚫 Please add a type label (e.g. **type: enhancement**) and a feature label (e.g. **feature: stats**) to this issue.
