### ISSUE TITLE
Google for WooCommerce: Update plugin checking to account for SSR API change

### ISSUE THREAD

**Issue by hafizrahman** [woocommerce/woocommerce-android#12396]
Due to changes in either https://github.com/woocommerce/woocommerce/pull/48709 or https://github.com/woocommerce/woocommerce/pull/50417 , the `wc/v3/system_status` response now adds a prefix `/srv/htdocs/wp-content/plugins/` to the plugin name, and this causes the check for the Google for WooCommerce plugin's existence to fail.

The checker will need to be updated to take this into account.

**Comment by dangermattic** [comment]
🚫 Please add a type label (e.g. **type: enhancement**) and a feature label (e.g. **feature: stats**) to this issue.

**Comment by hichamboushaba** [comment]
@hafizrahman I think we can close this now.
