### ISSUE TITLE
Refunds: Add Refund Amount screen

### ISSUE THREAD

**Issue by mindgraffiti** [woocommerce/woocommerce-android#1240]
Add the new Refund > Amount screen. As a user, I want to choose to refund an order by product (refund items screen) or by a specified amount (this screen).

<img width="461" alt="Screen Shot 2019-07-12 at 10 25 50 AM" src="https://user-images.githubusercontent.com/1062444/61139733-9050be00-a48f-11e9-88ee-e4eef850c618.png">

**Comment by 0nko** [comment]
Addressed in #1410.
