### ISSUE TITLE
Enable Blaze for Jetpack CP connection with full sync (like Blaze Ads plugin or Jetpack Search Plugin)

### ISSUE THREAD

**Issue by JorgeMucientes** [woocommerce/woocommerce-android#12412]
Checking if the Blaze plugin is installed requires fetching store plugins => the eligibility check need to be async again.
=> We need to revert changes to the check in all places: hub menu, dashboard, product form.

iOS issue: https://github.com/woocommerce/woocommerce-ios/issues/13487

**Comment by dangermattic** [comment]
🚫 Please add a type label (e.g. **type: enhancement**) and a feature label (e.g. **feature: stats**) to this issue.

**Comment by hichamboushaba** [comment]
> Checking if the Blaze plugin is installed requires fetching store plugins => the eligibility check need to be async again

We already [fetch](https://github.com/woocommerce/woocommerce-android/blob/a76d08ab4cc38fdbc2524938a770e35756a97c3f/WooCommerce/src/main/kotlin/com/woocommerce/android/SiteObserver.kt#L53-L55) plugins on app launches and site changes, so I think we don't need to refetch them each time we want to check for the eligibility, we need just to check the DB and see if the plugin exists like what we do for all other places in the app.
This is similar to a remark I recently [shared](https://github.com/woocommerce/woocommerce-android/pull/12398#issuecomment-2304475493) regarding Google Ads plugin check in the app.

**Comment by JorgeMucientes** [comment]
Closing. We will only enable Blaze for sites with Blaze for WooCommerce plugin. Currently, not all Jetpack CP connection will support Blaze, only those with the sync module enabled, and we do not have a mechanism to verify this. 

Enabling Blaze for sites with Blaze for WooCommerce plugin will be tackled here: https://github.com/woocommerce/woocommerce-android/issues/12146
