### ISSUE TITLE
Order Edit Screen doesn't have back button in phones

### ISSUE THREAD

**Issue by toupper** [woocommerce/woocommerce-android#12420]
## Description
When going to the the Edit screen on an order, there's no back button in the top bar. That makes it difficult to go back when the Done button is hidden. 

## Steps
1. Go to Orders
2. Tap on an Order
3. Tap on Edit
4. There's no back button on the phone (there is on the tablet).

## Video

Uploading Screen_Recording_20240826_153348_WooCommerce (Dev).mp4…

**Comment by dangermattic** [comment]
Thanks for reporting! 👍
