### ISSUE TITLE
FluxC: Add networking requests for Refunds

### ISSUE THREAD

**Issue by mindgraffiti** [woocommerce/woocommerce-android#1242]
Ref. p99K0U-1n6-p2

Per the Refunds API Research, add endpoints and API requests to FluxC so that:

- [x] a refund can be sent by specifying the amount (#1261)
- [x] the order details can be updated (if needed)
- [ ] a refund can be sent by selecting individual order items

List any other endpoints or requests needed and follow up with iOS devs to ensure they don't miss any API requests.

**Comment by 0nko** [comment]
@mindgraffiti As per Refunds API Research, the shipping-only refunds is not supported by the current API. Should we cross it out from the checklist?

**Comment by mindgraffiti** [comment]
Yep! Edited. Feel free to edit tasks to whatever makes sense, in the future.
