### ISSUE TITLE
Done CTA is hidden when deleting products

### ISSUE THREAD

**Issue by Ecarrion** [woocommerce/woocommerce-android#12426]
**Describe the bug**

When all products are deleted from an order the "Done" CTA to dismiss the order edition form is not visible.

- Creates an order with a product, reduces product stock ✅
- Updates order to remove the product, increases stock ✅
- "Done" CTA disappears and user has to tap the phone back button ❌

iOS always shows the "Done" CTA

https://github.com/user-attachments/assets/3db0d5ac-43d1-45b5-b273-94f54ca07dca

**Comment by dangermattic** [comment]
Thanks for reporting! 👍

**Comment by toupper** [comment]
We decided that the Done button is not necessary when there are no products. The back button is added with this [issue](https://github.com/woocommerce/woocommerce-android/issues/12420), so I close this one as it's not necessary.
