### ISSUE TITLE
[Woo POS] WooPosCardReaderActivity blocking the app when reader connection flow canceled with back-press

### ISSUE THREAD

**Issue by samiuelson** [woocommerce/woocommerce-android#12425]
Steps to repro:

1. Tap "Connect your reader" in floating toolbar
2. When the connecting dialog shows up, perform the system "back" press
3. Notice the dialog disappeared, however, the screen is not responsive

The reason is that transparent WooPosCardReaderActivity is still alive on top of the WooPosActivity. It looks like we need to return the result in the event the flow is canceled on the back press. It's not possible to cancel the flow by clicking outside of the dialog and probably that's why we haven't discovered it sooner.

https://github.com/user-attachments/assets/305fd4e5-02b7-40ce-9aaf-ed20e80fc0bd

**Comment by dangermattic** [comment]
🚫 Please add a type label (e.g. **type: enhancement**) and a feature label (e.g. **feature: stats**) to this issue.
