### ISSUE TITLE
Tapping on "Collect Payment" in the order creation navigates me to the order detail instead of the payment selection

### ISSUE THREAD

**Issue by samiuelson** [woocommerce/woocommerce-android#12431]
**Describe the bug**

When I tap on Collect Payment from the order creation flow, the app navigates me to the order detail instead of the payment selection screen.  

The issue appeared first in the 20.1-rc-1 version available in Google Play on the open testing track.

**To Reproduce**
1. Go to order creation form
2. Add product
3. Click "Collect payment"
4. Notice the app redirects to the Order Detail screen instead of payment method selection screen

**Expected behavior**
The app should redirect to the "Take payment" screen after tapping "Collect payment" in the order creation form.

**Isolating the problem (mark completed items with an [x]):**
- [x] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [x] This bug happens with a default WordPress theme active,
  or [Storefront](https://woocommerce.com/products/storefront/).
- [x] I can reproduce this bug consistently using the steps above.

**Mobile Environment**
Please include:
- Device: Pixel 8
- Android version: 14
- WooCommerce Android version: 20.1-rc-1

**WordPress Environment**
<details>
```
Copy and paste the system status report from **WooCommerce > System Status** in WordPress admin.
```
</details>

**Comment by dangermattic** [comment]
🚫 Please add a type label (e.g. **type: enhancement**) and a feature label (e.g. **feature: stats**) to this issue.

**Comment by samiuelson** [comment]
Brainstorming: p1724752391339309-slack-C025A8VV728

**Comment by samiuelson** [comment]
Closed by https://github.com/woocommerce/woocommerce-android/pull/12436
