### ISSUE TITLE
Refunds: add Custom Refund Amount screen

### ISSUE THREAD

**Issue by mindgraffiti** [woocommerce/woocommerce-android#1244]
Tapping on the amount in the Product refunds will navigate to a new screen. Create the Product Refunds screen.

- [ ] Follow up with Kylea, as the Product Refunds screen design appears to be missing for Android
- [ ] Create the Product refunds screen
- [ ] Add navigation to reach the screen

<img width="251" alt="Screen Shot 2019-07-12 at 12 04 51 PM" src="https://user-images.githubusercontent.com/1062444/61145591-7322ec00-a49d-11e9-806b-f1d444bae659.png">

<img width="287" alt="Screen Shot 2019-07-12 at 11 59 43 AM" src="https://user-images.githubusercontent.com/1062444/61145593-74541900-a49d-11e9-9b5b-030c5f410484.png">

<img width="287" alt="Screen Shot 2019-07-12 at 12 08 58 PM" src="https://user-images.githubusercontent.com/1062444/61145760-de6cbe00-a49d-11e9-823e-f1a0fc4f7516.png">

<img width="461" alt="Screen Shot 2019-07-12 at 10 25 50 AM" src="https://user-images.githubusercontent.com/1062444/61139733-9050be00-a48f-11e9-88ee-e4eef850c618.png">

**Comment by 0nko** [comment]
Addressed in #1410.
