### ISSUE TITLE
Research if `CallThrottler` can be implemented without assumption on 200ms

### ISSUE THREAD

**Issue by kidinov** [woocommerce/woocommerce-android#12458]
Currently, there is an assumption that a navigation starts without 200ms, which may be correct all the time or maybe not, e.g. we assume that this flow is not possible:
* Click
* 200ms passed
* Click again
* Double navigation

We also recently had an issue related to this time based approach too

p1724752391339309-slack-C025A8VV728

Check if:
* https://github.com/woocommerce/woocommerce-android/issues/12458#issuecomment-2321259503
* There is an actually generic solution here, e.g. we can simply check if navigation has started already and then ignore new navigation request
* Or may what we actually want is to ignore duplicated events within 200ms instead of ignoring all events

**Comment by dangermattic** [comment]
🚫 Please add a type label (e.g. **type: enhancement**) and a feature label (e.g. **feature: stats**) to this issue.

**Comment by malinajirka** [comment]
One more trap of the current implementation is that if we navigate multiple times as a reaction to a single user input, only the first navigation is always taken into account while others might be ignored depending on the 200ms race condition. 

Imagine a scenario where I want to navigate from Order Creation -> Order Detail -> Payment Selection screen. In this scenario, the navigation to order Detail happens every time but the navigation to Payment Selection happens only if 200ms have passed. We can fix this behavior by manually passing `ignoreThrottle=true` flag, however, this is very error prone and difficult to discover. Ideal solution would IMO ignore/throttle only duplicated navigation events but would proceed with processing events that have a different target destination. Alternative solution would be to stop using a single static instance of CallThrottle as we do now.

**Comment by samiuelson** [comment]
We may also want to check if the current version of navigation component is not handling this on its own, allowing us to delete the throttling code:

> The improvements related to handling consecutive navigation actions and preventing `IllegalArgumentException` during rapid navigation interactions were addressed in multiple updates of the Android Navigation Component. Specifically, the key updates include:
> 1. **Version 2.3.0 (August 2020)** - Introduced better handling of consecutive navigation actions by ensuring that multiple navigation requests are queued correctly and processed sequentially to avoid overlapping actions, which often led to `IllegalArgumentException`.
> 2. **Version 2.4.0 (October 2021)** - Further improvements were made to prevent crashes related to fast consecutive navigations. This version included bug fixes that reduced the likelihood of navigation actions being triggered in an illegal state, which was a common cause of such exceptions.
> 3. **Version 2.5.0 (June 2022)** - Additional enhancements were introduced to manage navigation backstack more effectively, which included fixes for issues where the backstack could get corrupted due to rapid or simultaneous navigation requests.
> These versions reflect a progressive effort to address and improve the stability of the navigation component in scenarios involving quick user interactions.

—LLM
