### ISSUE TITLE
Bugfix: Switch the order in which impressions and clicks are displayed for Blaze campaigns. 

### ISSUE THREAD

**Issue by JorgeMucientes** [woocommerce/woocommerce-android#12470]
We currently updated the UI for Blaze campaigns to display the click-though rate [here](https://github.com/woocommerce/woocommerce-android/issues/12389). However, in that liked PR I applied some changes coming from feedback suggestions. In those changes I accidentally introduced a bug: https://github.com/woocommerce/woocommerce-android/pull/12433/commits/ee27a142b1c15ed3a74b31ad0b420752e7897997 and now clicks are displayed before impressions, when it should be the other way around: 

 <img width="300"  src="https://github.com/user-attachments/assets/97dcaaf2-ceac-4d99-9cfe-9b3d72d0ebe0"> 
 <img width="300"  src="https://github.com/user-attachments/assets/95b2f57f-4cc4-403d-aa3b-eef1be1a7cdf">

**Comment by dangermattic** [comment]
🚫 Please add a type label (e.g. **type: enhancement**) and a feature label (e.g. **feature: stats**) to this issue.
