### ISSUE TITLE
Enhance Login Flow: Retain Site URL After Email Typo

### ISSUE THREAD

**Issue by pmusolino** [woocommerce/woocommerce-android#12483]
@malinajirka raised an issue regarding an improvement needed in the login flow.

1. Enter the site address.
2. Enter an email with a typo.
3. An error screen is shown, but it always redirects the user to the initial page of the app. This means the user needs to enter the site URL again, even though they just made an innocent typo in the email address.

Expected behavior: The user should be taken back to the email/URL screen, not the initial page.

**Comment by dangermattic** [comment]
🚫 Please add a type label (e.g. **type: enhancement**) and a feature label (e.g. **feature: stats**) to this issue.
