### ISSUE TITLE
[Woo POS] Cannot reconnect to Reader after turning internet off and on

### ISSUE THREAD

**Issue by staskus** [woocommerce/woocommerce-android#12497]
**Describe the bug**
A clear and concise description of what the bug is. Please be as descriptive as possible; issues lacking detail, or for any other reason than to report a bug, may be closed without action.

Cannot reconnect to Reader after turning the internet off and on. I tested on a simulator with a simulated card reader, so this issue may be invalid.

**To Reproduce**
1. Open POS
2. Connect to reader
3. Turn off internet
4. Disconnect reader by tapping on floating button
5. Turn on internet
6. Notice card reader button and "Collect payment" doesn't work anymore

**Screenshots**

https://github.com/user-attachments/assets/eda393e7-4189-47ed-aefd-7f0239b6c57e

**Isolating the problem (mark completed items with an [x]):**
- [ ] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [ ] This bug happens with a default WordPress theme active,
  or [Storefront](https://woocommerce.com/products/storefront/).
- [ ] I can reproduce this bug consistently using the steps above.

**Mobile Environment**
Please include:
- Device:
- Android version:
- WooCommerce Android version:

**WordPress Environment**
<details>
```
Copy and paste the system status report from **WooCommerce > System Status** in WordPress admin.
```
</details>

**Comment by dangermattic** [comment]
Thanks for reporting! 👍
