### ISSUE TITLE
Refresh Blaze campaign list when a campaign is cancelled

### ISSUE THREAD

**Issue by JorgeMucientes** [woocommerce/woocommerce-android#12494]
When opening Blaze campaign detail from Campaign list screen and cancelling the campaign, navigating back to campaign list won't show refresh the status of the campaign to "Cancelled". 

Ideally, we want to intercept the cancelling URL from the webview and trigger a campaign list refresh when navigating back from the campaign detail webview. If intercepting the cancel operation in the webview is not feasible, we can maybe trigger the refresh action whenever user navigates back from the campaign detail screen.

**Comment by dangermattic** [comment]
Thanks for reporting! 👍

**Comment by pmusolino** [comment]
Related iOS issue: https://github.com/woocommerce/woocommerce-ios/issues/13795
