### ISSUE TITLE
[Woo POS] Total is wrongly rounded with product prices inclusive in tax

### ISSUE THREAD

**Issue by staskus** [woocommerce/woocommerce-android#12496]
**Describe the bug**

Totals are wrongly rounded with product prices inclusive of tax. This at least partially looks like a POS bug since the card payment modal shows a correct price.

**To Reproduce**

### Settings

<img src="https://github.com/user-attachments/assets/1c2840b0-d632-4c2c-9f80-1d5acf839487" width="350">

I used two Taxable products with Standard rate.

Example steps:

1. Configure store tax settings
2. Open POS
3. Add 2 x $0.01 and 1x $16 products
4. Observe total is $16.03
5. Collect card payment
6. Observe total is $16.02 

**Screenshots**

#### Card Payment Modal shows a different price

![image](https://github.com/user-attachments/assets/fd6ab749-ba59-458c-84d7-58f9467b7a6f)

#### iOS POS vs Android POS vs Web

![image](https://github.com/user-attachments/assets/749eac80-f627-4f21-8c85-91392d6b0546)
![image](https://github.com/user-attachments/assets/7b5d3649-0c10-4e2a-83de-5b28387bf64e)

**Expected behavior**

**Isolating the problem (mark completed items with an [x]):**
- [ ] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [ ] This bug happens with a default WordPress theme active,
  or [Storefront](https://woocommerce.com/products/storefront/).
- [ ] I can reproduce this bug consistently using the steps above.

**Mobile Environment**
Please include:
- Device:
- Android version:
- WooCommerce Android version:

**WordPress Environment**
<details>
```
Copy and paste the system status report from **WooCommerce > System Status** in WordPress admin.
```
</details>

**Comment by dangermattic** [comment]
Thanks for reporting! 👍
