### ISSUE TITLE
Adding a product in the order creation on phones lags/freezes for 1 second

### ISSUE THREAD

**Issue by samiuelson** [woocommerce/woocommerce-android#12490]
**Describe the bug**
A clear and concise description of what the bug is. Please be as descriptive as possible; issues lacking detail, or for any other reason than to report a bug, may be closed without action.
* Adding a product in the order creation on phones lags/freezes for 1 second.
* Adding more products increases the delay even more.

Discussion: p1725284759189029-slack-C025A8VV728

**To Reproduce**
1. Create new order
2. Open product selector and add a few products
3. Notice the network call-related delay before the order is updated

**Screenshots**

https://github.com/user-attachments/assets/91b92857-a2f1-440d-a486-838cca926c07

**Expected behavior**
Adding products to the order should not cause a delay.

**Mobile Environment**
Please include:
- Device: pixel 7 pro
- Android version: 14
- WooCommerce Android version: 20.1

**WordPress Environment**
<details>
```
Copy and paste the system status report from **WooCommerce > System Status** in WordPress admin.
```
</details>

**Comment by dangermattic** [comment]
🚫 Please add a type label (e.g. **type: enhancement**) and a feature label (e.g. **feature: stats**) to this issue.
