### ISSUE TITLE
Broken Order List Pagination

### ISSUE THREAD

**Issue by malinajirka** [woocommerce/woocommerce-android#12491]
**Describe the bug**
The order list sometime refreshes and resets the scrolling position when scrolling down. Moreover, it seems that afterwards it sometimes stops loading more pages.

**To Reproduce**
1. Clear apps data
2. Login
3. Open Order List and scroll down
4. Observe that a PTR animation (the small circle indicator at the top) appears at certain point.
5. Wait until it completes -> notice the scrolling position resets back to 0.

**Screenshots**

https://github.com/user-attachments/assets/155c495f-852d-497d-8340-d68cd87f38fc
https://github.com/user-attachments/assets/eece001f-8a60-40bf-9575-c5a23618b79f

**Expected behavior**
The pagination should keep loading more pages until I reach the last order and shouldn't reset my scrolling position.

**Isolating the problem (mark completed items with an [x]):**
- [x] I can reproduce this bug consistently using the steps above.

**Mobile Environment**
Please include:
- Device: Pixel 8
- Android version: Android 14 and 15
- WooCommerce Android version: 10.1.1

**Comment by dangermattic** [comment]
Thanks for reporting! 👍
