### ISSUE TITLE
[Product Variations] Product Details variation counter not updated after creating new variations

### ISSUE THREAD

**Issue by ThomazFB** [woocommerce/woocommerce-android#12507]
Summary
==========
When editing a Variable Product with valid Attributes, any time a new Variation is created, the Product Details is not immediately updated with the variation amount, creating a confusing experience to the user, especially when it's a brand new Product with no previous Variation.

Screen Capture
==========
https://github.com/user-attachments/assets/6647b4d9-0481-4393-8f07-73d3a5abdb18

Steps to Reproduce
==========
1. Create a brand new Variable Product configured with Attributes to enable Variation creation
2. Enter the Product Details section and select `Add variations`
3. Click in the `Generate Variations` option
4. After the creation is done, hit back and verify that the `Add variation` button is still there, where it should be a `Variations` label with the number of variations associated with that product.

**Comment by dangermattic** [comment]
Thanks for reporting! 👍
