### ISSUE TITLE
[Woo POS] Issue with the card reader connection flow

### ISSUE THREAD

**Issue by backwardstruck** [woocommerce/woocommerce-android#12506]
Steps to Reproduce:

Tap the “Connect your reader” button in the floating toolbar.
When the connecting dialog appears, press the system “back” button.
Observe that the dialog disappears, but the screen becomes unresponsive.

Context:

https://wp.me/p91TBi-c2x#comment-12935

Let's also address this issue in the same PR:
 It looks like we don't handle the update needed + low batter event during IPP flow properly

https://wp.me/pdfdoF-5iv

**Comment by dangermattic** [comment]
🚫 Please add a type label (e.g. **type: enhancement**) and a feature label (e.g. **feature: stats**) to this issue.

**Comment by backwardstruck** [comment]
Seems to work fine on this screen in the main app:

![Screenshot_20240903_211211](https://github.com/user-attachments/assets/eacbb593-70cf-4366-a094-18ba84e213dd)

**Comment by backwardstruck** [comment]
I suspect the reason that this is NOT happening on the `CardReaderDetailFragment` is because we _disable_ the back button as soon as `CardReaderConnectDialogFragment` is launched. So you can only get out of that dialog by hitting the cancel button within it.

**Comment by samiuelson** [comment]
There's been another issue reported for this: https://github.com/woocommerce/woocommerce-android/issues/12425

**Comment by backwardstruck** [comment]
> There's been another issue reported for this: #12425

Thanks! Closing this one as a duplicate.
