### ISSUE TITLE
[Woo POS] We still not always correctly determine "gesture" navigation on some devices

### ISSUE THREAD

**Issue by kidinov** [woocommerce/woocommerce-android#12501]
@staskus noticed that bottom padding set on gesture navigation patter here

p91TBi-c11-p2#comment-12973

**Comment by dangermattic** [comment]
Thanks for reporting! 👍

**Comment by kidinov** [comment]
I briefly checked that and it looks like that on Pixel tablet they have 32dp bottom navigation panel in the gesture navigation mode, while we are using 24dp as determination height we may just change this number
