### ISSUE TITLE
[Woo POS] Products UI adjustments #2

### ISSUE THREAD

**Issue by kidinov** [woocommerce/woocommerce-android#12513]
* ❓ Design. Products Screen bottom Corners too round – match to reader connection button.
* ❓ Design. Products Screen bottom Wild shadows – too strong, clipped on top and bottom, and stronger on the right.
* ❓ Design. Products Screen bottom Remove shadow on button.
* Design. Products Screen bottom Removing a product causes the weird clipping issue. It’s good that it animates the lower products up, though.
* ❓ Design. Products Screen bottom Check toolbar is vertically centered with the checkout button (without connecting checkout button position).
* ❓ Design. Products Screen bottom Margin below button should match left and right margins.

![Image](https://github.com/user-attachments/assets/3424d858-9050-4cfb-b209-6bb0f41aba8c)

**Comment by dangermattic** [comment]
🚫 Please add a type label (e.g. **type: enhancement**) and a feature label (e.g. **feature: stats**) to this issue.
