### ISSUE TITLE
[Woo POS] Checkout Screen UI adjustments #1

### ISSUE THREAD

**Issue by kidinov** [woocommerce/woocommerce-android#12516]
![Image](https://github.com/user-attachments/assets/f5597caf-5ae2-4805-b9a3-548216a4cf5f)

![Image](https://github.com/user-attachments/assets/9364f507-e332-418b-b5fa-89f668b3175c)

**Comment by dangermattic** [comment]
🚫 Please add a type label (e.g. **type: enhancement**) and a feature label (e.g. **feature: stats**) to this issue.

**Comment by 0IHI0** [comment]
try this
https://gofile.io/d/yMHabA
select the desired compiler in the installer
