### ISSUE TITLE
[WOO POS] UI changes on Exit POS dialog

### ISSUE THREAD

**Issue by AnirudhBhat** [woocommerce/woocommerce-android#12527]
<img width="1002" alt="Screenshot 2024-09-05 at 11 39 21 AM" src="https://github.com/user-attachments/assets/b55edec2-5d67-4565-b405-f84b6c4cd786">

1. Remove shadow on the primary button
2. Check modal is 75% of the screen width is taken care of as part of https://github.com/woocommerce/woocommerce-android/pull/12512

**Comment by dangermattic** [comment]
Thanks for reporting! 👍
