### ISSUE TITLE
The stats label of the Blaze campaign item is cut off

### ISSUE THREAD

**Issue by irfano** [woocommerce/woocommerce-android#12520]
**Describe the bug**
The second stats label of the Blaze campaign item is cut off

**To Reproduce**
1. Enable Blaze for your site from the web.
2. From the app, go to "Menu → Blaze" and create a campaign.
3. Scroll down to Blaze card on My Store tab.

**Screenshots**
<img src="https://github.com/user-attachments/assets/3b89cd79-5b23-4830-a4a7-9b9692ccf1d9" width=300>

**Expected behavior**
"Weekly" label should be a single line.

**Isolating the problem (mark completed items with an [x]):**
- [ ] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [x] This bug happens with a default WordPress theme active,
  or [Storefront](https://woocommerce.com/products/storefront/).
- [x] I can reproduce this bug consistently using the steps above.

**Mobile Environment**
Please include:
- Device: Galaxy S24
- Android version: 14
- WooCommerce Android version: 9.3.0-beta 1

**WordPress Environment**
<details>
```
Copy and paste the system status report from **WooCommerce > System Status** in WordPress admin.
```
</details>

**Comment by dangermattic** [comment]
Thanks for reporting! 👍
