### ISSUE TITLE
Filtering by Variation Product returns always an error

### ISSUE THREAD

**Issue by atorresveiga** [woocommerce/woocommerce-android#12526]
**Describe the bug**
Filtering by Variation Product returns always an error. Furthermore, when trying again, it returns an empty list. On iOS there’s no such Variation Product filter value. We have to check if this is an issue on Core or the app.

**To Reproduce**
1. Go to the Products tab
2. Tap on Filters
3. Tap on product type
4. Tap on Variation product
5. Apply the filter (press Show products button)
6. Check that the app displays a Error fetching product message

**Screenshots**

https://github.com/user-attachments/assets/d8a40978-70fb-407c-acc8-c8cf15220e73

**Expected behavior**
All product-type filter should be selectable and display the expected information

**Isolating the problem (mark completed items with an [x]):**
- [x] I can reproduce this bug consistently using the steps above.

**Mobile Environment**
Please include:
- Device: Pixel 6
- Android version: Android 14
- WooCommerce Android version: 20.2-rc-2

**Comment by dangermattic** [comment]
Thanks for reporting! 👍
