### ISSUE TITLE
Stats Improvements Step 3: Add scrubbing interaction to charts

### ISSUE THREAD

**Issue by anitaa1990** [woocommerce/woocommerce-android#1252]
As defined in the master thread [here](https://github.com/woocommerce/woocommerce-android/issues/1199), step 3 of the stats improvements include tweaking the interaction on the chart bars to update the stats. This involves adding a scrubbing interaction similar to the changes implemented [here](https://github.com/woocommerce/woocommerce-android/commit/a1540f4ba9c399ea4191200b711d7fc22801a37e).

<img width="300" src="https://user-images.githubusercontent.com/22608780/61261022-feea9000-a79d-11e9-9b24-567b273c6672.gif">

**Comment by anitaa1990** [comment]
When adding this scrubbing interaction to the app, we would need to update the visitor stats as well. But we are not storing the visitor stats for each date, just fetching the total count for the given date range and displaying it in the UI. 

For this scrubbing to work, I was thinking of storing the visit stats in a local db, similar to how we store the revenue/order stats now in `WcOrderStatsModel`.  I believe it should be relatively straightforward to store and retrieve the visitor details after that. @AmandaRiu @nbradbury what do you think?

**Comment by AmandaRiu** [comment]
@anitaa1990 I really like the idea of a caching mechanism - especially since the user would likely hit the same bar multiple times while scrubbing

**Comment by mindgraffiti** [comment]
Closing. Completed in 2.5, #1334
