### ISSUE TITLE
[Order Tracking] Duplicated toolbar in the Carrier List

### ISSUE THREAD

**Issue by toupper** [woocommerce/woocommerce-android#12536]
## Description 

As shown below, the toolbar in the Carriers List is duplicated

## Steps
With [WC Shipment Tracking](https://woocommerce.com/products/shipment-tracking/) installed

1. Go to Orders
2. Go to an existing order details that contains products other than virtual
3. Tap on Add Tracking
4. Check that there's a selected carrier. If not, select one
5. Tap again on Carrier to open the carriers list
6. The toolbar is duplicated

## Screenshot
<img src=https://github.com/user-attachments/assets/f2b34a6a-d08d-44b5-b538-29f1d1ddbc3c width="375">

**Comment by dangermattic** [comment]
Thanks for reporting! 👍
