### ISSUE TITLE
[Order Tracking] Coming back from carrier list removes the previously set carrier 

### ISSUE THREAD

**Issue by toupper** [woocommerce/woocommerce-android#12534]
## Description
In the Add Order Tracking screen, we remove the carrier when coming back from the carrier list by tapping on the back button. That's erroneous, as the user didn't select any new carrier.

## Steps to reproduce

With [WC Shipment Tracking](https://woocommerce.com/products/shipment-tracking/) installed

1. Go to Orders
2. Go to an existing order details that contains products other than virtual
3. Tap on Add Tracking
4. Check that there's a selected carrier. If not, select one
5. Tap again on Carrier to open the carriers list
6. Tap on the back button.
7. Bug: the carrier is removed (it shouldn't)

https://github.com/user-attachments/assets/16f51410-eeab-4c97-ba06-1e1918dfc825

**Comment by dangermattic** [comment]
Thanks for reporting! 👍
