### ISSUE TITLE
[Woo POS] Error message doesn’t feel right when failing to collect the payment due to the lack of network

### ISSUE THREAD

**Issue by backwardstruck** [woocommerce/woocommerce-android#12542]
❓ The error message doesn’t feel like the right one when failing to collect the payment due to the lack of network (we show error fetching order – so not sure if it’s a bad message and worth doing anything about)

https://wp.me/pdfdoF-5iv

In addition, if the card reader is not connected yet, we don't show any error message while in airplane mode.

This change will also affect existing payment flows since we're using the same dialog.

**Comment by dangermattic** [comment]
🚫 Please add a type label (e.g. **type: enhancement**) and a feature label (e.g. **feature: stats**) to this issue.

**Comment by backwardstruck** [comment]
![Screenshot_20240905_134351](https://github.com/user-attachments/assets/5f528c96-02b2-4801-a749-df0546aa3a5f)
