### ISSUE TITLE
Clicking on Promote Again button from campaign detail webview should trigger the native flow. 

### ISSUE THREAD

**Issue by JorgeMucientes** [woocommerce/woocommerce-android#12547]
Currently, clicking on `Promote Again` button from campaign details webview screen triggers the Blaze webview flow to create a campaign. 

https://github.com/user-attachments/assets/4cfefbb5-ec30-400b-8670-7ff4e4fba84f

**Comment by dangermattic** [comment]
Thanks for reporting! 👍
