### ISSUE TITLE
[Woo POS] Orders created in POS don’t show product names when reviewed in IPP later on

### ISSUE THREAD

**Issue by kidinov** [woocommerce/woocommerce-android#12550]
* Complete a transaction in POS
* Go to orders
* Review the details of the order
* Result: The right number of products and their respective quantities/prices are correct, but the names of the products aren’t passed through

p91TBi-c2x-p2#comment-13033

**Comment by dangermattic** [comment]
Thanks for reporting! 👍

**Comment by backwardstruck** [comment]
Screenshots of issue:

![Screenshot_20240913_162040](https://github.com/user-attachments/assets/6e68514a-10b3-48ca-a957-e02d0de6a031)
![Screenshot_20240913_162114](https://github.com/user-attachments/assets/b4b67abf-accb-409d-97dd-3721249564cb)

**Comment by backwardstruck** [comment]
The items should be coming in to the order in `OrderCreateEditRepository#createOrUpdateOrder` just like in the regular app flow:

```
Item(itemId=1332, productId=15, name=Garment-dyed Super Soft Slub Cotton Hoodie in Ash, price=70, sku=, quantity=1.0, subtotal=70.00, totalTax=1.05, total=70.00, variationId=0, attributesList=[], parent=null, configuration=null, configurationKey=null)
```
