### ISSUE TITLE
Dashboard menu items cut off

### ISSUE THREAD

**Issue by JorgeMucientes** [woocommerce/woocommerce-android#12559]
**Describe the bug**
A clear and concise description of what the bug is. Please be as descriptive as possible; issues lacking detail, or for any other reason than to report a bug, may be closed without action.

If the dashboard card title is long, it will get cut off in the dismiss option menu. Make the menu option 2 lines if this happens. 

**To Reproduce**
1. Load the app dashboard and enable the "Most recent reviews" card. 
2. Switch app language to Spanish (this bug will likely happen in other languages, but in Spanish is were I first saw it)
3. Click on the 3 dots menu of the "Most recent reviews" card. 
4. See the item is cut off. 

**Screenshots**
![Screenshot 2024-09-09 at 08 54 06](https://github.com/user-attachments/assets/33d6c198-88a5-4a6f-adce-52384173a272)
add screenshots to help explain your problem.

**Expected behavior**

Make the item 2 lines if the text is long. 

**Isolating the problem (mark completed items with an [x]):**
- [x] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [x] This bug happens with a default WordPress theme active,
  or [Storefront](https://woocommerce.com/products/storefront/).
- [x] I can reproduce this bug consistently using the steps above.

**Mobile Environment**
Please include:
- Device: Pixel 8 
- Android version: 14
- WooCommerce Android version: 20.2

</details>

**Comment by dangermattic** [comment]
🚫 Please add a type label (e.g. **type: enhancement**) and a feature label (e.g. **feature: stats**) to this issue.
