### ISSUE TITLE
[Woo POS] Design: Products Screen changes

### ISSUE THREAD

**Issue by backwardstruck** [woocommerce/woocommerce-android#12556]
https://wp.me/pdfdoF-5iv

<s>❓ Design. Products Screen bottom Move reader connection behind screen.

and

❓ Design. Products Screen bottom Shadow appears after card.</s>

I moved those two to a separate GH issue: https://github.com/woocommerce/woocommerce-android/issues/12587

❓ Design. Products Screen bottom Adding to the top is good (it didn’t make it clear in the design), but please animate the products moving down. The shift is too sudden.

**Comment by dangermattic** [comment]
🚫 Please add a type label (e.g. **type: enhancement**) and a feature label (e.g. **feature: stats**) to this issue.

**Comment by backwardstruck** [comment]
Context from Figma:

<img width="331" alt="Screenshot 2024-09-06 at 15 51 15" src="https://github.com/user-attachments/assets/c438de05-9e6b-4e4e-a222-7519892d8a61">

<img width="450" alt="Screenshot 2024-09-06 at 15 52 19" src="https://github.com/user-attachments/assets/61dbc0f2-b1a8-4552-a938-71f031b6758a">

<img width="729" alt="Screenshot 2024-09-06 at 15 52 55" src="https://github.com/user-attachments/assets/e3ae2476-2c56-46f9-a14c-d4c0074717ba">
