### ISSUE TITLE
Product Attribute Rename Validations Are Not Case Sensitive

### ISSUE THREAD

**Issue by JorgeMucientes** [woocommerce/woocommerce-android#12561]
**Describe the bug**
A clear and concise description of what the bug is. Please be as descriptive as possible; issues lacking detail or for any other reason than to report a bug may be closed without action.

When renaming product attributes, we check if the name was edited. However, this check is not case-sensitive

**To Reproduce**
1. Attempt to rename a product attribute by just changing any number of characters from lower case to upper case. 
2. Then navigate back
3. See a toast stating that the product attribute 
4. The product attribute won't be renamed and you'll have to remove it and add it again with the correct letter case. See screen recording for extra details. 

**Screenshots**

https://github.com/user-attachments/assets/8067bc19-3f1b-4a21-b259-2a1153807b43

**Expected behavior**

The product attribute name should be updated with the new lettercase. 

**Isolating the problem (mark completed items with an [x]):**
- [ ] I can reproduce this bug consistently using the steps above.

**Mobile Environment**
Please include:
- Device: Pixel 8
- Android version: 14
- WooCommerce Android version: 20.2

**Comment by dangermattic** [comment]
Thanks for reporting! 👍
