### ISSUE TITLE
Missing Blaze impressions info icon when the impressions label copy is very long

### ISSUE THREAD

**Issue by JorgeMucientes** [woocommerce/woocommerce-android#12562]
**Describe the bug**
In Blaze edit budget screen, the label displayed above the impressions number should display an info icon. Tapping in that info icon would explain users, what impressions are. This is the expected behavior when the language is set to English: 

https://github.com/user-attachments/assets/6100b9b7-44b3-436c-a7e5-e3504484f041

However, when setting app language to a different local where this label becomes longer than 1 lines, the icon is missing. 

![image](https://github.com/user-attachments/assets/417b9df0-de72-43cb-b827-55062d12bba8)

**Expected behavior**
The info icon should always be displayed.

**Comment by dangermattic** [comment]
Thanks for reporting! 👍
