### ISSUE TITLE
Update README.md with Security and Resources sections

### ISSUE THREAD

**Issue by jaclync** [woocommerce/woocommerce-android#1257]
It would be nice to add Security and Resources sections to the README like in [WCiOS README](https://github.com/woocommerce/woocommerce-ios/blob/develop/README.md) so that both docs have more consistent structure :)

**Comment by AmandaRiu** [comment]
Thanks @jaclync! I'll be working on documentation all week for WCAndroid and have this in my list. I'll take this ticket and get it implemented <3
