### ISSUE TITLE
[Woo POS] More Products Screen changes

### ISSUE THREAD

**Issue by backwardstruck** [woocommerce/woocommerce-android#12587]
Related to this issue:
https://github.com/woocommerce/woocommerce-android/issues/12556

https://wp.me/pdfdoF-5iv

❓ Design. Products Screen bottom Move reader connection behind screen:

[Image](https://private-user-images.githubusercontent.com/947561/365290193-e3ae2476-2c56-46f9-a14c-d4c0074717ba.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjY1MTkyMTMsIm5iZiI6MTcyNjUxODkxMywicGF0aCI6Ii85NDc1NjEvMzY1MjkwMTkzLWUzYWUyNDc2LTJjNTYtNDZmOS1hMTRjLWQ0YzAwNzQ3MTdiYS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwOTE2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDkxNlQyMDM1MTNaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1lYWNjNGJlMzQyZWY3OTY0OThiZmMwMmZlMWRlZDIxYjAzNjkwMzI2NDIwNzNhYzUxNjAzMzkwYmExMjBkYmJiJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.TdqpIYCGw2DKA3En9_LotAA25u3gVqzu_i55Hbrp_EU)

and

❓ Design. Products Screen bottom Shadow appears after card. This one will probably be addressed in this PR:
https://github.com/woocommerce/woocommerce-android/pull/12557

**Comment by dangermattic** [comment]
🚫 Please add a type label (e.g. **type: enhancement**) and a feature label (e.g. **feature: stats**) to this issue.
