### ISSUE TITLE
[Shipping labels] Shipping weight calculated incorrectly with multiples of the same product

### ISSUE THREAD

**Issue by rachelmcr** [woocommerce/woocommerce-android#12596]
**Describe the bug**

In the existing (legacy) shipping labels flow: If I have multiples of the same product in one package, the shipping weight is calculated incorrectly. Only the weight for one of each product is included in the calculation, so my package weight is lower than it should be. This means the shipping rate is incorrect (too low) and the shipping carrier will have to make an adjustment.

User report: paJDVv-46s-p2#comment-4626 / p1726084617554959-slack-C7U3Y3VMY

**To Reproduce**
1. Enable the WooCommerce Shipping & Tax extension and set it up on your store.
2. Make sure you have at least one product with the weight defined in the product's shipping settings.
3. Create an order and add the product to it with a quantity of 2 or more.
4. In order details, tap "Create shipping label" to start the shipping label flow.
5. Confirm the shipping addresses.
6. In the package selection screen, notice that the package weight is correct.
7. Select a package and notice that the package weight is incorrect — it is now the sum of the package weight and a single product.

**Screenshots**

Quantity of 1 each|Quantity of 2 each (no package selected)|Quantity of 2 each (after selecting package)
-|-|-
![Screenshot_20240912-110431](https://github.com/user-attachments/assets/9a73f5b8-288f-4b87-83b6-0f2da46cb459)|![Screenshot_20240912-110735](https://github.com/user-attachments/assets/43731ab5-396a-4d37-8c2a-07671c1ec27f)|![Screenshot_20240912-110740](https://github.com/user-attachments/assets/b74d2b9d-caa3-49a8-99ac-371b8e9be143)

**Mobile Environment**
Reproduced the issue with:
- Device: Google Pixel 6
- Android version: Android 14
- WooCommerce Android version: WCAndroid 20.3-rc-2

**Comment by dangermattic** [comment]
Thanks for reporting! 👍
