### ISSUE TITLE
[Woo POS] UI issues with the cart screen

### ISSUE THREAD

**Issue by kidinov** [woocommerce/woocommerce-android#12618]
* Broken top shadow and maybe a missing bottom shadow for the cart products list
* The fade-out animation is too long -> get it back to 300
* The animation of the back arrow is too long -> get it back to 300
* And the cart not aligned with the products again

https://github.com/user-attachments/assets/d0c3ea8e-6eaa-4e4a-a53f-6accac400e8a

**Comment by dangermattic** [comment]
🚫 Please add a type label (e.g. **type: enhancement**) and a feature label (e.g. **feature: stats**) to this issue.
