### ISSUE TITLE
Applied coupon showing just in bottom details sheet

### ISSUE THREAD

**Issue by malinajirka** [woocommerce/woocommerce-android#12619]
I applied the coupon on an order and it shows in the details bottom sheet but I would expect it to show also where the “Add Coupon” is.

<img src="https://github.com/user-attachments/assets/73088cd7-c08e-4e4f-9990-5ed913670bc5" width="250px" />

We can take the Shipping section as reference and review with Joe if necessary. pe5pgL-5G4-p2#comment-4489

**Comment by dangermattic** [comment]
Thanks for reporting! 👍

**Comment by backwardstruck** [comment]
Thanks for the P2 link @malinajirka So just to confirm:

It currently looks like this on Android (as well as iOS, basically)  
<img src="https://github.com/user-attachments/assets/da7e4b9d-f9ba-42c0-8906-e68059ac4529" alt="current_coupon_display" height="420">

Instead it will look like the shipping row. We should show the coupons that were applied in a similar way to how shipping is shown under the coupon button, not just in the totals drawer:

<img src="https://github.com/user-attachments/assets/e2e5ecce-34dc-4d53-87f8-47032c2c60cc" alt="shipping_row_example"  height="420">  
<img src="https://github.com/user-attachments/assets/80d60419-4842-4eb0-acb4-bebe433a8742" alt="details_example" height="420">

**Comment by backwardstruck** [comment]
Also, we should create an iOS copy of this issue right?

**Comment by iamgabrielma** [comment]
> Also, we should create an iOS copy of this issue right?

Cross-referencing: https://github.com/woocommerce/woocommerce-ios/issues/13861
