### ISSUE TITLE
[Mobile Payments] "What is tap to pay" screen instruction not correct

### ISSUE THREAD

**Issue by AnirudhBhat** [woocommerce/woocommerce-android#12626]
**Describe the bug**
Point 4 of “What is Tap to Pay” screen states, “Your customer holds their card horizontally at the top of your phone,” which may be slightly confusing since the Stripe Tap to Pay screen instructs customers to tap the card on the back of the phone, which is what the customers need to do.

**To Reproduce**
1. Ensure you are on a device that is eligible for TTP (Reader with NFC enabled)
2. Navigate to payments settings (more menu -> payments)
3. Click on "What is tap to pay" option
4. Read point number 4 which asks to hold card on top of the phone
5. Now, try collecting the payment via TTP wherein Stripe screen asks us to tap the card on the back of the phone.

**Expected behavior**
Instruction should be changed to what the Stripe screen says as that's what users must eventually do to process the payments.

**Comment by dangermattic** [comment]
Thanks for reporting! 👍

**Comment by backwardstruck** [comment]
Can you add a screenshot for this bug @AnirudhBhat ? I don't see a “What is Tap to Pay” section on the payments screen.

Is it this?

<img width="551" alt="Screenshot 2024-09-17 at 17 01 45" src="https://github.com/user-attachments/assets/6ca60772-7958-4db8-90a7-0755020954c0">

**Comment by AnirudhBhat** [comment]
Sorry, it's called `What is tap to pay` on iOS. On Android, it's called `About Tap to Pay`

![Screenshot_20240919-095203](https://github.com/user-attachments/assets/77eb7ea8-7da3-4a9e-9387-bbb5d5db1dc2)
