### ISSUE TITLE
[Mobile Payments] Inconsistencies in the way we open a web view

### ISSUE THREAD

**Issue by AnirudhBhat** [woocommerce/woocommerce-android#12625]
**Describe the bug**
I noticed inconsistency in the way we display web view when clicked on any of the “learn more” links in the payments settings. The web view in “Manage Card Reader” and “What is Tap to Pay?” opens partially (which is expected), while the web view from Payment Settings opens in full screen.

**To Reproduce**
1. Navigate to payments settings (More menu -> Payments)
2. Click on "Manage card reader" or "What is Tap to Pay" option
3. Click on the "Learn more" link and see web view opens in half initially (Expected)
4. Now, come back to the payment settings, scroll down and click on "Learn more"
5. See that the web view opens in a full screen.

https://github.com/user-attachments/assets/8945b888-b6dd-4283-8b80-9919e9720618

**Expected behavior**
Web view should open in half on every screens.

**Comment by dangermattic** [comment]
Thanks for reporting! 👍
