### ISSUE TITLE
[Woo POS] Animate transition to "Get support" screen

### ISSUE THREAD

**Issue by samiuelson** [woocommerce/woocommerce-android#12628]
The goal is to update the enter and exit animation to match design specs.

Animation specs: https://wp.me/p6riRB-aNq

**Comment by dangermattic** [comment]
🚫 Please add a type label (e.g. **type: enhancement**) and a feature label (e.g. **feature: stats**) to this issue.

**Comment by samiuelson** [comment]
https://github.com/woocommerce/woocommerce-android/pull/12630
