### ISSUE TITLE
Google for WooCommerce: `woocommerceandroid_googleads_flow_error` never triggered

### ISSUE THREAD

**Issue by hafizrahman** [woocommerce/woocommerce-android#12627]
While checking data for HTTP issue when using the webview to open Google for WooCommerce, the error tracking is never triggered.

This was working properly [when tested in the PR](https://github.com/woocommerce/woocommerce-android/pull/12098) so we need to figure out what went wrong.

Testing step:
> Turn off the internet connection and tap on the entry point again. After the loading fails, confirm that googleads_flow_error is tracked with the correct source property and error details.

**Comment by dangermattic** [comment]
🚫 Please add a type label (e.g. **type: enhancement**) and a feature label (e.g. **feature: stats**) to this issue.

**Comment by hafizrahman** [comment]
This was found to be an issue in Tracks and it has since been fixed p91TBi-cxn-p2
