### ISSUE TITLE
[Order filtering] Filtering orders by product screen contains a filter button that is broken

### ISSUE THREAD

**Issue by AnirudhBhat** [woocommerce/woocommerce-android#12623]
Filtering orders by product screen contains a filter button that is not working when clicked.

**Steps to reproduce**
1. Go to the orders tab
2. Click on `Filters` option
3. Select `Products` from the filter options
4. We see another `Filter` option on the product selection screen that does nothing when clicked.

**Expected Behaviour**
1. Filter button should open product selection filter screen

https://github.com/user-attachments/assets/58df1e22-4430-42ee-a8c0-850d92a9321a

**Comment by dangermattic** [comment]
Thanks for reporting! 👍

**Comment by backwardstruck** [comment]
Yes, it should open up the product filter screen with stock status, product status, product type and product category filters.

**Comment by backwardstruck** [comment]
Looks like I also need to fix the filter for dark mode:
![Screenshot_20240918_175237](https://github.com/user-attachments/assets/fbc87ccb-93fa-4d4e-a428-fad47c090b0b)

**Comment by backwardstruck** [comment]
Slack discussion here:

p1726870233211919-slack-C025A8VV728
