### ISSUE TITLE
Notification for disabled Application Password error with support options

### ISSUE THREAD

**Issue by pmusolino** [woocommerce/woocommerce-android#12647]
The Android app does not notify users when they face a "Disabled Application Password" situation during login, unlike the iOS app https://github.com/woocommerce/woocommerce-ios/issues/14004. Additionally, the app does not offer a contact support button or guide users to troubleshooting documentation.

More here: peaMlT-U4

**Steps to Reproduce:**
1. Attempt to log in with a disabled application password.
2. Observe the lack of notification and support options.

**Expected Behavior:**
The app should notify users about the "Disabled Application Password" error, provide a "Contact Support" button, and include a link to troubleshooting documentation.

**Actual Behavior:**
No notification or support options are provided.

**Proposed Solution:**
- Implement a notification feature to inform users about the "Disabled Application Password" error.
- Enhance the notification to include more detailed information about the issue.
- Add a "Contact Support" button to the error notification.
- Include a link to troubleshooting documentation in the notification.

![screenshot-3](https://github.com/user-attachments/assets/733ceb14-8c74-43f0-b703-109b960e8c1f)

**Comment by dangermattic** [comment]
Thanks for reporting! 👍

**Comment by hichamboushaba** [comment]
After investigating this, we found out that the Android app already provides an error screen when Application Passwords are disabled, there is just one issue where the screen wouldn't be shown if the site had an issue that prevents signing in, which leaves the user on a confusing state. More information here peaMlT-U4-p2#comment-2277
