### ISSUE TITLE
[Notifications] Replace mutable map with Thread safe map for storing all active notifications

### ISSUE THREAD

**Issue by AnirudhBhat** [woocommerce/woocommerce-android#12654]
While fixing `ConcurrencyModificationException` https://github.com/woocommerce/woocommerce-android/pull/12646, we came to conclusion that replacing `mutableMap` with Thread safe map would benefit in the long run. This ticket is to do that.

**Comment by dangermattic** [comment]
🚫 Please add a type label (e.g. **type: enhancement**) and a feature label (e.g. **feature: stats**) to this issue.

**Comment by AnirudhBhat** [comment]
Closing this issue: https://github.com/woocommerce/woocommerce-android/pull/12655#issuecomment-2477879578
