### ISSUE TITLE
Weird animation of toolbar when switching from Payments to Manage card reader screen

### ISSUE THREAD

**Issue by kidinov** [woocommerce/woocommerce-android#12659]
**Describe the bug**
A clear and concise description of what the bug is. Please be as descriptive as possible; issues lacking detail, or for any other reason than to report a bug, may be closed without action.
The same issue happens to other screens when we assumebly going from activity toolbar to the local toolbar

Please check the video for better understanding

**To Reproduce**
1. Go to More -> Payments
2. Open Manager card reader -> Notice that the whole list goes down due to double toolbar
3. Go back -> notice Toolbar jumping

**Screenshots**

<img width="610" alt="image" src="https://github.com/user-attachments/assets/28cd5e76-181e-4ce7-8da1-eaf4e951bda6">

https://github.com/user-attachments/assets/e30ca54e-28e1-4ef8-a5e6-a32bc6ce3eab

**Comment by dangermattic** [comment]
Thanks for reporting! 👍

**Comment by backwardstruck** [comment]
Also happening on landscape.

**Comment by backwardstruck** [comment]
Also happens when you tap Card Reader Manuals but _not_ when tapping Change Payment Provider.
