### ISSUE TITLE
[Barcode Scanner] Improve barcode scanner reading accuracy

### ISSUE THREAD

**Issue by AnirudhBhat** [woocommerce/woocommerce-android#12656]
There have been issues reported p1724846800296649-slack-C013AAPA4G0 regarding barcode scanners reading inaccuracy when scanning barcodes.

The goal of the task is to research and come up with potential solutions on improving the barcode scanners reading accuracy.

**Comment by dangermattic** [comment]
🚫 Please add a type label (e.g. **type: enhancement**) and a feature label (e.g. **feature: stats**) to this issue.
