### ISSUE TITLE
[Product AI] Make API requests in parallel when saving the product as draft

### ISSUE THREAD

**Issue by hichamboushaba** [woocommerce/woocommerce-android#12664]
When saving the product as draft, we execute 3 preparation requests to get the IDs of the resources before being able to use them:
1. Product Tags
2. Product Categories
3. Upload the local image.

This creates a long delay, we can reduce the delay by making the requests in parallel.

###### Internal discussion: pdfdoF-5pQ-p2#comment-6480

**Comment by dangermattic** [comment]
Thanks for reporting! 👍
