### ISSUE TITLE
Text cut off in the "Get paid" screen when the text is long. 

### ISSUE THREAD

**Issue by JorgeMucientes** [woocommerce/woocommerce-android#12662]
**Describe the bug**
In "Get paid" screen (opened when creating a new order using IPP), if the language of the app is set to Spanish or any other language where the text is longer than one line, it will get cut. 

**To Reproduce**
1. With IPP enabled and the language set to Spanish (for example)
2. From orders tab, click on create order
3. Add a product to the order
4. Click on collect payment
5. Select Cash
6. Notice how the text gets cut off

**Screenshots**

![Screenshot 2024-09-23 at 13 16 10](https://github.com/user-attachments/assets/b34633f9-bc53-4e45-bb7c-047b464966ce)

**Comment by dangermattic** [comment]
Thanks for reporting! 👍
