### ISSUE TITLE
Odd text alingment in IPP bottom sheet description

### ISSUE THREAD

**Issue by JorgeMucientes** [woocommerce/woocommerce-android#12666]
**Describe the bug**

When the app is set to a language different from English, like Spanish, the alignment of the text in the following bottomsheet description is odd. 

<img width="300"  src="https://github.com/user-attachments/assets/149fb93f-2eb4-4bf3-bff6-9ee11ef95ebe">

**Comment by dangermattic** [comment]
Thanks for reporting! 👍

**Comment by samiuelson** [comment]
Could you please share the path to display that bottom sheet @JorgeMucientes?

**Comment by JorgeMucientes** [comment]
Sure @samiuelson. Sorry, I should've provided it from the start. 

https://github.com/user-attachments/assets/6b6f3aff-c8f9-4d68-a418-f9ef715ed1cd
