### ISSUE TITLE
Wear app: Order Details screen does not account for an empty Product list

### ISSUE THREAD

**Issue by ThomazFB** [woocommerce/woocommerce-android#12672]
**Describe the bug**
The Wear Order Details screen does not account for the scenario where an Order doesn't contain any products. Instead, it displays the Product loading error message when it should simply hide the product list section.

**To Reproduce**
1. In the Wear app, open an Order Details with no products.
2. Verify at the bottom of the Order Details that a Product loading error message is displayed.

**Screenshots**
![image](https://github.com/user-attachments/assets/e0fa1e71-ac07-4c56-829d-e307498cfa5f)

**Comment by dangermattic** [comment]
Thanks for reporting! 👍
