### ISSUE TITLE
Double toolbar when setting free trial period for subscription product

### ISSUE THREAD

**Issue by JorgeMucientes** [woocommerce/woocommerce-android#12679]
**Describe the bug**
When opening Free trial section for a subscription product, 2 toolbars are displayed. 

**To Reproduce**
1. Open a subscription product detail
2. Click on Free trial row
3. See the 2 toolbars

**Screenshots**

https://github.com/user-attachments/assets/13914e91-3182-4bc8-9ab6-cb15f140e8af

**Comment by dangermattic** [comment]
Thanks for reporting! 👍
