### ISSUE TITLE
Review page blank when store is changed after clicking on a review detail notification

### ISSUE THREAD

**Issue by anitaa1990** [woocommerce/woocommerce-android#1268]
When clicking on a Review Detail notification, The review detail page is opened. When changing the store from the Settings, the review Detail page is blank.

### Steps to reproduce
- Add a review from a test site.
- Click on the review notification from the app. Notice that the Review Detail page is opened.
- Click on the Settings menu button and switch the store.
- Click on the back button. Notice that the Review page is blank.

The same steps can be reproduced for a new order notification as well.
- Create a new order from a test site.
- Click on the new order notification from the app. Notice that the Order detail page for that order is opened.
- Click on the Settings menu button and switch the store.
- Click on the back button. Notice that the error snacker is displayed (before the page is trying to refresh with the order number (received in the notification for the previous store). Since that order number is not available for the current store, the error message is received.

### Screenshots
<img width="300" src="https://user-images.githubusercontent.com/22608780/61505680-4de23080-a9fd-11e9-973b-e4ed6333d3ff.gif">

**Comment by nbradbury** [comment]
Note that what should happen in this situation is the back stack is cleared and the user is returned to the dashboard.

**Comment by nbradbury** [comment]
Additional steps to repro:

* Make sure "Don't keep activities" is enabled
* The app must be force quit before generating the push

**Comment by nbradbury** [comment]
I've spent a ridiculous amount of time looking into this. I can reproduce the problem but have been unable to fix it. I'm pretty sure if I step away from it for a while I'll realize there's a painfully simple solution :)

**Comment by anitaa1990** [comment]
I am no longer able to reproduce this
