### ISSUE TITLE
[Woo POS] Adjust shadows again

### ISSUE THREAD

**Issue by kidinov** [woocommerce/woocommerce-android#12693]
pdfdoF-5iv-p2#comment-6514

> They aren’t quite right on either card. They are too small on the product cards and too small and too heavy on the cart cards.

Implementation:
![Image](https://github.com/user-attachments/assets/f41acd3d-147f-435a-9119-164ad734aecf)

Design:

![Image](https://github.com/user-attachments/assets/250cb5d3-79de-4a3c-9c82-4c2e3d0a7626)

**Comment by dangermattic** [comment]
🚫 Please add a type label (e.g. **type: enhancement**) and a feature label (e.g. **feature: stats**) to this issue.
