### ISSUE TITLE
Add SmartLock support

### ISSUE THREAD

**Issue by aforcier** [woocommerce/woocommerce-android#127]
One other piece of login implementation that wasn't part of the shared login library code is SmartLock support - there are stubbed out methods for this in `LoginActivity`, and we should be able to reuse some of the existing code in WPAndroid.

**Comment by anitaa1990** [comment]
There is active work going on to implement this feature as part of the [Unified Login](https://github.com/woocommerce/woocommerce-android/projects/14) project. This issue is tracked in #2819 so closing this one.
