### ISSUE TITLE
After purchasing a shipping label logic

### ISSUE THREAD

**Issue by atorresveiga** [woocommerce/woocommerce-android#12707]
The purchase label probably won't happen immediately, and it passes through different states: PURCHASE_IN_PROGRESS and then PURCHASED. To display the status of the shipping labels, we should pull the label status using the endpoint `GET /wcshipping/v1/label/purchase/{order_id} `

We should follow this pull strategy:

<img width="400" src="https://github.com/user-attachments/assets/83f75133-dd56-47db-a55e-0d65801c4dc3" />

We should have the mocks on how the UI will behave while the status is different than `PURCHASED`, but in the mean time these are the design recommendations:

>  I should mock this up but in the meantime, can you put the print button here into a loading state, and change the top text to something about loading

More context:
https://a8c.slack.com/archives/C05VBLKHHV1/p1727367981691889
https://woomobilep2.wordpress.com/2021/03/18/shipping-labels-purchase-api/
https://a8c.slack.com/archives/C02KUCFCSFP/p1724411724439349?thread_ts=1724258545.625349&cid=C02KUCFCSFP

**Comment by dangermattic** [comment]
Thanks for reporting! 👍
