### ISSUE TITLE
[Mobile Payments] Incorrect Pay In Person learn more link

### ISSUE THREAD

**Issue by AnirudhBhat** [woocommerce/woocommerce-android#12729]
Pay In Person learn more link on the payment settings opens incorrect url. 

We open https://woocommerce.com/document/woopayments/in-person-payments/getting-started-with-in-person-payments/#add-cod-payment-method which was proper at the time of implementation but now, it seemed to be have moved here: https://woocommerce.com/document/cash-on-delivery/

**Steps to Reproduce**
1. Navigate to Payments settings (More menu -> Payments)
2. Click on the Learn more link under Pay in Person setting
3. Observe that the opened link has no connection about "Pay in Person"

**Expected Behaviour**
Open https://woocommerce.com/document/cash-on-delivery/ when clicked on Learn more under Pay in Person setting

**Comment by dangermattic** [comment]
Thanks for reporting! 👍

**Comment by malinajirka** [comment]
@AnirudhBhat ~I'm not sure I understand the placement of this link. Why would we want to open COD documentations on generic Payments section of the app? Isn't the correct link perhaps https://woocommerce.com/document/woopayments/in-person-payments/getting-started-with-in-person-payments/?~ Ignore me, I see that it's a different link than I thought.
