### ISSUE TITLE
[Woo POS] Remove shadow from the check icon and from the button on the payment success screen

### ISSUE THREAD

**Issue by kidinov** [woocommerce/woocommerce-android#12731]
https://github.com/woocommerce/woocommerce-android/pull/12719#issuecomment-2381890544

> Looks good, but there’s a couple small things – can you please remove the drop-shadow on the green check circle, and on the button?

**Comment by dangermattic** [comment]
🚫 Please add a type label (e.g. **type: enhancement**) and a feature label (e.g. **feature: stats**) to this issue.
