### ISSUE TITLE
[Shipping Labels: Packages] Add Package Opening UI Section

### ISSUE THREAD

**Issue by ThomazFB** [woocommerce/woocommerce-android#12747]
Summary
==========
Once the Package UI flow is functional, we should allow it to be actioned from the main Shipping Labels creation flow, this task focus on this feature by introducing an opening view within the main form.

Designs
==========
![Image](https://github.com/user-attachments/assets/dc8cf6cc-8f4c-469f-b07f-0aee80c0393e)
![Image](https://github.com/user-attachments/assets/ead263f9-ef36-434c-9c79-2576eb233d88)

**Comment by dangermattic** [comment]
Thanks for reporting! 👍

**Comment by ThomazFB** [comment]
This was already implemented through task #12281
