### ISSUE TITLE
[Woo POS] Entry point won't appear unless I restart the app

### ISSUE THREAD

**Issue by malinajirka** [woocommerce/woocommerce-android#12740]
When I install the app and login, I don't see the POS entry point, which is expected. However, when I complete IPP Onboarding, the POS entry point is still hidden. I have to restart the app for it too appear. I experienced this behavior when I tested the build for Woo DM on WooDM Swag store.

Comment from Andrei:
`Yep, I reproduced this too. I briefly checked the code, and it looks like we fetch FFs only when the app starts, and as the app’s start happens in the case of login flow when a user is not logged in, I’d assume that there is no way to white list based on the account name`

**Comment by dangermattic** [comment]
Thanks for reporting! 👍
