### ISSUE TITLE
[Shipping Labels: Packages] Add Saved Package UI

### ISSUE THREAD

**Issue by ThomazFB** [woocommerce/woocommerce-android#12746]
Summary
==========
The Package management feature should allow the user to select a package through three options:
1. Custom package defined by the user
2. Carrier-provided package options
3. Package options saved and available in the store

**This task focuses on delivering the UI for Saved packages.**

Designs
==========
![Image](https://github.com/user-attachments/assets/f3656903-28d7-48a4-9d7c-97c170e97932)

**Comment by dangermattic** [comment]
Thanks for reporting! 👍
