### ISSUE TITLE
[Shipping Labels: Packages] Add Carrier Package UI

### ISSUE THREAD

**Issue by ThomazFB** [woocommerce/woocommerce-android#12745]
Summary
==========
The Package management feature should allow the user to select a package through three options:
1. Custom package defined by the user
2. Carrier-provided package options
3. Package options saved and available in the store

**This task focuses on delivering the UI for Carrier-provided packages.**

Designs
==========
![Image](https://github.com/user-attachments/assets/6c782450-f9ff-4fe8-8230-2539daf79b32)

**Comment by dangermattic** [comment]
Thanks for reporting! 👍
