### ISSUE TITLE
[Shipping Labels: Packages] Add Custom Package UI

### ISSUE THREAD

**Issue by ThomazFB** [woocommerce/woocommerce-android#12744]
Summary
==========
The Package management feature should allow the user to select a package through three options:
1. Custom package defined by the user
2. Carrier-provided package options
3. Package options saved and available in the store

**This task focuses on delivering the UI for Custom packages.**

Designs
==========
![Image](https://github.com/user-attachments/assets/ee2e23df-9ad0-49ea-a1ba-e1e72da02477)

**Comment by dangermattic** [comment]
Thanks for reporting! 👍
