### ISSUE TITLE
[Wear App] Orders List with inconsistent sorting logic

### ISSUE THREAD

**Issue by ThomazFB** [woocommerce/woocommerce-android#12755]
Context
==========
Currently, the Wear app displays the Orders list with two sorting strategies when it should have only one. The sorting strategy issue happens depending on the data source used by the app.

The Wear app has three strategies to display data:
1. Internet connection
2. Phone connection
3. Cached data

This is also done in a prioritized way; it will always attempt to connect to the internet first. 

The internet and phone connection are retrieving the Orders in a new-to-old sorting, the correct way, but the cached data is retrieving the orders in an old-to-new sorting, which is incorrect.

How to fix
==========
We must ensure that when we resort to the Cached data, that data is sorted following the new-to-old strategy. This is currently being handled in the `FetchOrders` use case, through the `selectOrdersDataSource` function.

How to Test
==========
1. Disable the Wear app internet connection and sever the Phone connection to force the cached data to be used.
5. Make sure that the app has already had a chance to sync data from the store at least once.
6. Open the app and navigate to the Orders List. Please verify that the list displays orders from old to new, where it should be new to old.

**Comment by dangermattic** [comment]
Thanks for reporting! 👍
