### ISSUE TITLE
Product AI creation fails frequently

### ISSUE THREAD

**Issue by hichamboushaba** [woocommerce/woocommerce-android#12768]
Product AI creation fails frequently, and the cause is that OpenAI is returning the JSON code wrapped in a Markdown code block: 
`"```json ....  ```"`

This is actually an expected behavior of the API, and was happening for quite some time, but now it seems to be happening more frequently, see: https://community.openai.com/t/why-do-some-responses-message-content-start-with-json/573289

**Comment by dangermattic** [comment]
Thanks for reporting! 👍
