### ISSUE TITLE
Fix navigation to Blaze campaign from product details

### ISSUE THREAD

**Issue by JorgeMucientes** [woocommerce/woocommerce-android#12762]
**Describe the bug**
A clear and concise description of what the bug is. Please be as descriptive as possible; issues lacking detail, or for any other reason than to report a bug, may be closed without action.
When triggering Blaze campaign from product detail we are always showing the intro screen, even when users have several campaigns already created. 

**To Reproduce**
1. Log into a site eligible for Blaze that has at least one campaign created. 
2. Open product detail
3. Click on Blaze cta from product detail
4. Notice how the intro screen is always shown. 

**Screenshots**

**Expected behavior**
Intro screen should only be shown if the user doesn't have any prior experience with Blaze, that is, it doesn't have any campaign created yet.

**Comment by dangermattic** [comment]
Thanks for reporting! 👍
