### ISSUE TITLE
[Mobile Payments]Duplicate back arrow when editing default "customer provided note" when trying Tap to Pay

### ISSUE THREAD

**Issue by AnirudhBhat** [woocommerce/woocommerce-android#12778]
**Steps to reproduce**
1. Navigate to the payments hub menu (more menu -> Payments)'
2. Click on "Try Tap to Pay" option
3. Click on "Try payment" option
4. In this screen, try editing the customer provided note
5. Observe the duplicate back arrow button

https://github.com/user-attachments/assets/f964ff6e-2eac-44d5-b598-c84a1a646770

**Comment by dangermattic** [comment]
Thanks for reporting! 👍
