### ISSUE TITLE
[Products]Trashed product appears on first pull-to-refresh. Disappears on subsequent pull-to-refresh as expected.

### ISSUE THREAD

**Issue by AnirudhBhat** [woocommerce/woocommerce-android#12777]
**Steps to reproduce**

1. Navigate to product details screen

2. From the 3 dots in the toolbar, trash the product

3. The screen dismisses with a message saying that the product has been trashed.

4. Pull to refresh

5. Observe that the trashed product re-appears. However, on pull to refreshing again, the product disappears as expected.

https://github.com/user-attachments/assets/546d9360-e8bc-4829-b7e8-dc0d7f9f6a18

**Comment by dangermattic** [comment]
Thanks for reporting! 👍
