### ISSUE TITLE
[Products]Trashing a newly created duplicate product doesn't work.

### ISSUE THREAD

**Issue by AnirudhBhat** [woocommerce/woocommerce-android#12776]
**Steps to reproduce**

1. Navigate to product details screen

2. From the 3 dots in the toolbar, duplicate the product

3. On the duplicate product screen, use the 3 dots from the toolbar to trash the product

4. The screen just dismisses and the product never gets trashed.

https://github.com/user-attachments/assets/7e21b083-534d-4c3b-ae89-668ca7c4ac4b

**Comment by dangermattic** [comment]
Thanks for reporting! 👍
