### ISSUE TITLE
[Custom Fields] Changing text format in Aztec is not detected until we change the text as well

### ISSUE THREAD

**Issue by hichamboushaba** [woocommerce/woocommerce-android#12783]
Reported by @selanthiraiyan in the beta testing: "When I edit a custom field and change the type from “Text” to “HTML” the “Done” button is not enabled. I tried making some changes to the HTML using the buttons. The “Done” button is not enabled until I alter the text. Is this expected?"

https://github.com/user-attachments/assets/cc5fc37c-6363-4d59-895b-51fe769ce303

p1728992309521619/1728992304.294829-slack-C03L1NF1EA3

**Comment by dangermattic** [comment]
🚫 Please add a type label (e.g. **type: enhancement**) and a feature label (e.g. **feature: stats**) to this issue.
