### ISSUE TITLE
Inconsistent Shipping details in product detail screen for subscription products

### ISSUE THREAD

**Issue by JorgeMucientes** [woocommerce/woocommerce-android#12785]
**Describe the bug**
When enabling `One time Shipping` for a subscription product, if we then set a `Subscription free trial` the one time shipping option should automatically be disabled. However, it will be shown as enabled in the product detail screen and disabled in the Shipping details screen. Se the scree recording:

https://github.com/user-attachments/assets/83150b88-83cd-450f-89ac-6fc52f2ea995

**To Reproduce**

Follow the screen recording instructions above to reproduce the bug. 

**Expected behavior**
The product detail screen should reflect the new disabled state for `One-time Shipping` as soon as the subscription free trial is enabled.

**Comment by dangermattic** [comment]
Thanks for reporting! 👍
