### ISSUE TITLE
Receipt is not attached to text message

### ISSUE THREAD

**Issue by rossanafmenezes** [woocommerce/woocommerce-android#12793]
context - p1729079516266729-slack-C6H8C3G23

When using the share option for an order receipt in the app, instead of sharing the actual receipt we share only a text as opposed to the actual file like we do on other apps:

| <img src="https://github.com/user-attachments/assets/4252506b-470a-497e-8444-7ab0777a477f" width="350"/> | <img src="https://github.com/user-attachments/assets/e4f1f6bc-faad-4e54-8c3c-f5d94e005c81" width="350"/> |

If sharing the receipt via SMS is not possible we should hide the messaging app from the dialog where the sharing options are displayed.

**Comment by dangermattic** [comment]
🚫 Please add a type label (e.g. **type: enhancement**) and a feature label (e.g. **feature: stats**) to this issue.

**Comment by malinajirka** [comment]
@kidinov Could you please look into this issue (based on the new process, high priority bugs should be fixed within 2 weeks)? I tested this briefly a few weeks ago and it seemed that specifying the content type of the share intent to `html` fixed the issue.

**Comment by kidinov** [comment]
@malinajirka Sure, I'll take a look soon

@rossanafmenezes 👋

 jfyi, we do not have control over what the system shows as sharing options -> it just confirms what apps can handle specific intent we are firing, but apparently, that messaging app doesn't handle files we share along with that

**Comment by rossanafmenezes** [comment]
Thanks, @kidinov 

Yeah, I tested here and it works on everything except the SMS (which is expected to a point) but as I mentioned in the slack thread, sending text, at least here in Canada, supports sending files. No idea what happens in the background, but we are able to send PDFs, pics, etc. However, I was not able to send the receipt.
