### ISSUE TITLE
Support AVIF Image format

### ISSUE THREAD

**Issue by ThomazFB** [woocommerce/woocommerce-android#12810]
Summary
==========
As WordPress added native support for the AVIF image format, some WCAndroid users started reporting issues displaying Products containing this image format, making it hard to identify items within orders.

After some research, we found that Android only natively [supports AVIF rendering from Android 14 and above](https://developer.android.com/media/platform/supported-formats#image-formats), so there's a chance this is happening because our image-loading libraries simply don't support it below that version. But we also tested this on an Android 14 device; and it's not working either. So, even in a version that supports AVIF, the problem persists.

Screen Capture
==========
https://github.com/user-attachments/assets/0b5c68f6-4d60-4d9d-afba-8e6f6400a9d1

Steps to Reproduce
==========
1. Edit a product to contain a image of the AVIF format
2. Open the app and go to an Order with that following product or that Product details screen
3. Verify that the image is only displayable when rendered in full screen.

**Comment by dangermattic** [comment]
🚫 Please add a type label (e.g. **type: enhancement**) and a feature label (e.g. **feature: stats**) to this issue.
