### ISSUE TITLE
Order Details: Inconsistent Currency Display in Shipping Section and Order Totals

### ISSUE THREAD

**Issue by toupper** [woocommerce/woocommerce-android#12849]
When a product is purchased in a different currency than the store's default currency, the Order Details shows different currencies on the Shipping Section (default one) and Order Totals (order currency). The valid one should be the order one:

![Image](https://github.com/user-attachments/assets/1b2000b1-f5a5-4623-92fb-388029c27adc)

(Screenshot for iOS but also applicable to Android)

**Comment by dangermattic** [comment]
Thanks for reporting! 👍
