### ISSUE TITLE
[POS][Non-Simple Product type] Detect variable products and add variation quantity

### ISSUE THREAD

**Issue by AnirudhBhat** [woocommerce/woocommerce-android#12842]
The goal of this task is to detect variable products in the items list and add variation quantity under the item name to differentiate between simple products and variable products.

![Image](https://github.com/user-attachments/assets/fa2259b3-5dd1-4330-9fbd-0a6ec73a0bda)

**Comment by dangermattic** [comment]
Thanks for reporting! 👍
