### ISSUE TITLE
[Coupons] Unify "Add coupon" button visibility in case order contains custom amount only

### ISSUE THREAD

**Issue by samiuelson** [woocommerce/woocommerce-android#12848]
Discussion: https://wp.me/pdfdoF-5IP#comment-6772

Android and iOS apps are not consistent in the way we handle coupons. In case the order contains only a custom amount Android app allows adding a coupon to the order and iOS does not. 

The goal of that issue is to make decision whether we should adjust Android app to follow the iOS implementation and update the conditions for showing the "Add coupon" button in the order creation screen.

**Comment by dangermattic** [comment]
Thanks for reporting! 👍

**Comment by malinajirka** [comment]
I accidentally fixed this as part of [this PR](https://github.com/woocommerce/woocommerce-android/pull/12855) which was focused on bringing consistency to how the coupons are displayed in the order. I don't see a usecase in which someone would want to apply a coupon to an order which has only custom amount. Let's go with the iOS behavior for now and adjust if we here complains. This shouldn't block any users flows as they can always adjust the custom amount manually.

**Comment by malinajirka** [comment]
Fixed in [[Order creation] Update coupons display order details #12855](https://github.com/woocommerce/woocommerce-android/pull/12855)
