### ISSUE TITLE
[POS][Non-Simple Products] Refactor existing products list to be more generic

### ISSUE THREAD

**Issue by AnirudhBhat** [woocommerce/woocommerce-android#12841]
The goal of this task is to refactor existing products list to be more generic. Right now, it can hold only type of "Product". Sooner or later, we will start adding all types of items such as coupons, discounts, custom amounts, Variable products, variations, categories ...etc into the product list. It would greatly benefit us if we make the list as generic as possible so that we could accommodate all types of categories on our home screen.

Since the work to support Variable product has started. This is a good time to refactor and get it ready for future changes.

**Comment by dangermattic** [comment]
Thanks for reporting! 👍
