### ISSUE TITLE
Shipping Lines in Order Creation are editable at all times

### ISSUE THREAD

**Issue by malinajirka** [woocommerce/woocommerce-android#12869]
**Describe the bug**
The shipping lines in the order creation/order edit flows, are editable at all times. For example, when the order is being refreshed, I'm able to edit the shipping lines even though all the other features on the other are disabled. I'm also able to edit shipping lines when I enter the edit mode on a paid order.

**To Reproduce**
1. Go to Order List
2. Click on Create Order
3. Add a product
5. Notice `Add shipping` button is disabled when the order is refreshed (this is expected behavior)
6. Add a shipping line
7. 🐛 Notice the added shipping line is editable when the order is refreshed
8. Add a product
9. 🐛  Notice `Add shipping` button is enabled when the order is refreshed (this is not expected)

1. Open detail of a paid order with a shipping line
2. Tap on Edit
3. Notice you can edit shipping lines even though the order is not editable

**Expected behavior**
Shipping line should be disabled when editing paid orders or when the order is being updated in the background in the order creation. The behavior should be consistent with Coupons when [this PR is merged](https://github.com/woocommerce/woocommerce-android/pull/12855).

**Isolating the problem (mark completed items with an [x]):**
- [x] I can reproduce this bug consistently using the steps above.

**Comment by dangermattic** [comment]
Thanks for reporting! 👍
