### ISSUE TITLE
[Order List / Details] Rotating the device forcefully enters an Order details screen and reloads the Order List.

### ISSUE THREAD

**Issue by ThomazFB** [woocommerce/woocommerce-android#12862]
Summary
==========
The consolidated UI for the Order List and Order Details is triggering multiple unexpected behaviors when rotating the device screen:

1.  Forcefully navigates the user to the Order Details screen of the first order in the list
2. Reloads the Order List every time it enters landscape mode

Instructions to reproduce
==========
1. Make sure you're using the app on a Phone device with a standard screen aspect ratio (avoid foldable with tablet-like screens)
2. Go to the Order List screen in portrait mode
3. Rotate the device screen to landscape and back to portrait again
4. Verify that you're no longer in the Order List screen but in the Order Details of the first order in the list
5. Also, verify that the Order List makes a new refresh request for every time the landscape mode is activated

Screen Capture
==========
https://github.com/user-attachments/assets/20bf2100-cdd4-4d45-a5fa-8837398b4593

Environment
==========
Please include:
- Device: Pixel 7a
- Android version: Android 14
- WooCommerce Android version: 20.9

**Comment by dangermattic** [comment]
Thanks for reporting! 👍

**Comment by malinajirka** [comment]
Context - p91TBi-crS#comment-13506-p2

**Comment by malinajirka** [comment]
This behavior is expected and implementing a proper solution feels too risky and costly to maintain.
