### ISSUE TITLE
Validate that Blaze campaign images are square

### ISSUE THREAD

**Issue by JorgeMucientes** [woocommerce/woocommerce-android#12879]
Blaze campaign ads support square images only. We currently only check that the image meets some size requirements, but we don't enforce it to be square. 

- We can either show an error if the image is not a square
- Or automatically crop the image to square and display the cropped image in the Ad preview. If the user is ok with that, let them proceed with creating the campaign.

**Comment by dangermattic** [comment]
🚫 Please add a type label (e.g. **type: enhancement**) and a feature label (e.g. **feature: stats**) to this issue.

**Comment by JorgeMucientes** [comment]
Image cropping is handled in the backend side, so closing for now.
