### ISSUE TITLE
Date Ranges picked using the date picker across the app can result in shifted dates in some timezones

### ISSUE THREAD

**Issue by hichamboushaba** [woocommerce/woocommerce-android#12885]
Currently, the app has a few features that use a date range picker; we use the official material one, `MaterialDatePicker`, but the component has an issue with timezones that result in shifted dates when the timezone has a negative offset, this was reported as bug here https://github.com/material-components/material-components-android/issues/882, and although the ticket is closed, the issue is still reproducible.

<img width=360 src=https://github.com/user-attachments/assets/547a8a52-476f-48a6-9fe3-fedf27500ad6/>
<img width=360 src=https://github.com/user-attachments/assets/71976de2-5ed4-455f-b337-779aad88cab6/>

##### Issue reported internally here p1730982809165539-slack-C6H8C3G23

**Comment by dangermattic** [comment]
Thanks for reporting! 👍
