### ISSUE TITLE
[Woo POS - payments onboarding] Add analytics events

### ISSUE THREAD

**Issue by kidinov** [woocommerce/woocommerce-android#12903]
Two new events:

* `pos_payments_onboarding_shown`: when the onboarding is shown in POS, after the user taps to connect to a card reader if onboarding is not completed.
* `pos_payments_onboarding_dismissed`: when the onboarding is dismissed manually by the user in POS. Event property: onboarding_state: string for the onboarding state – we will analyze the most common states that the user dismisses for potential improvements.

**Comment by dangermattic** [comment]
🚫 Please add a type label (e.g. **type: enhancement**) and a feature label (e.g. **feature: stats**) to this issue.
