### ISSUE TITLE
[Mobile Payments] Not possible to fix some onboarding errors via authenticated WebView

### ISSUE THREAD

**Issue by kidinov** [woocommerce/woocommerce-android#12907]
It looks like some time ago, the Stripe site started to open in a pop-up in a browser, and our authenticated web view doesn't support it on Android, so a user ends up in an endless loading state. Check the video for a better understanding.

https://github.com/user-attachments/assets/440885c9-7bb4-4cd0-b7d8-fd1bad84cf15

**Comment by dangermattic** [comment]
Thanks for reporting! 👍

**Comment by jaclync** [comment]
iOS is having a similar issue not being able to get to the Stripe form in the onboarding webview https://github.com/woocommerce/woocommerce-ios/issues/14303, we reverted the authenticated webview. The fix would probably require accommodating popups in a webview, which feels a bit hacky.

**Comment by kidinov** [comment]
@jaclync 

> The fix would probably require accommodating popups in a webview, which feels a bit hacky.

I tried that, but they do some magic regarding passing auth between and that didn't work either 🥺
