### ISSUE TITLE
[Woo POS - payments onboarding] Handle case when we don't know country and currency

### ISSUE THREAD

**Issue by kidinov** [woocommerce/woocommerce-android#12904]
Discussion - p1731318083758239-slack-C070SJRA8DP

for instance, a merchant in the UK disables the WooPayments plugin. As we now check country and currency using payments/acccounts endpoint we end up with:
* Onboarding state -> WcpayNotActivated
* Country and Currency -> we don't know as the endpoint returns 404 in this case
So the question do we want to allow a user to enter the POS or not

**Comment by dangermattic** [comment]
🚫 Please add a type label (e.g. **type: enhancement**) and a feature label (e.g. **feature: stats**) to this issue.
