### ISSUE TITLE
Migrate events that use `error` property

### ISSUE THREAD

**Issue by JorgeMucientes** [woocommerce/woocommerce-android#12924]
All tracked event that use the `error` property on Android are not being tracked. 
Context on this: p1731584513235259-slack-C03L1NF1EA3

So we are migrating away from using any property named `error` and instead when tracking errors use the following [track()](https://github.com/woocommerce/woocommerce-android/blob/03c32c095ecd5fa9fde0294929f9ec4815a1728f/WooCommerce/src/main/kotlin/com/woocommerce/android/analytics/AnalyticsTracker.kt#L713-L722) function.

**Comment by dangermattic** [comment]
🚫 Please add a type label (e.g. **type: enhancement**) and a feature label (e.g. **feature: stats**) to this issue.

**Comment by JorgeMucientes** [comment]
Waiting for further investigation on the issue from the data team. 

###### Context: p1731595922091499/1731593700.993889-slack-C03DKP1JP

**Comment by JorgeMucientes** [comment]
The issue was fixed in Tracks API and sending properties using `error` key is not perfectly fine.
