### ISSUE TITLE
Could not find a product in new order flow

### ISSUE THREAD

**Issue by kidinov** [woocommerce/woocommerce-android#12940]
* Create a variable product
* Start order creating flow
* Notice that newly created product is not in the list

https://github.com/user-attachments/assets/fcd20bfa-fcd7-4a01-9573-20aa5a2cd93c

**UPD: I understood why it's not on the list. I tried to add that product via barcode, and the reason was explained - there is no price set for this product. I am wondering if we still should show products like that in the product selection list but showing the same toast message with explanation that the products without the price are not eligible**

**Comment by dangermattic** [comment]
Thanks for reporting! 👍

**Comment by malinajirka** [comment]
The current decisions is to mark this issue as `won't fix` until we receive explicit user feedback with reasoning why non-purchasable products should be shown in the order creation flow - peaMlT-10l#comment-2567-p2.
