### ISSUE TITLE
Infinite Loading Receipt Indicator

### ISSUE THREAD

**Issue by malinajirka** [woocommerce/woocommerce-android#12949]
**Describe the bug**
When the request to fetch IPP receipt fails, the app keeps showing an infinite loading indicator.

**To Reproduce**
1. Create an order and add a product
2. Select Collect Payment and choose Card Reader option
3. Collect the payment
4. Tap on Print Receipt and notice a loading indicator is shown => it doesn't get dismissed when the network request to fetch the receipt fails (you can simulate this either by intercepting the request or by using WooCommerce-9.5-beta-1 which contains a bug on the receipt endpoint.

**Screenshots**

https://github.com/user-attachments/assets/21af67ce-3860-47f1-978f-22d6f81a0825

**Expected behavior**
The app should navigate back to the Successful Payment state.

**Comment by dangermattic** [comment]
Thanks for reporting! 👍
