### ISSUE TITLE
[Mobile Payments] Crash when Shop Managers tries to install/activate WooPayments

### ISSUE THREAD

**Issue by kidinov** [woocommerce/woocommerce-android#12957]
**Describe the bug**

Shop Manager role cannot manage plugins of a store. When the store doesn't have WooPayments installed/activated, "plugin not installed/activated" onboarding error is shown with a CTA. If the Shop Manager user taps on the CTA to install/activate the plugin, a generic error is shown without mentioning the root cause (they don't have permission) so they know the next steps.

**To Reproduce**

Prerequisite: the store doesn't have Stripe Extension installed & activated, and WooPayments is either not installed or activated. The store has at least one Shop Manager user.

* Log in to the store with Shop Manager user
* Go to Menu > Payments
* Tap Continue setup --> after loading, "plugin not installed/activated" onboarding error should be shown
* Tap on the CTA to install/activate the plugin --> notice that a generic error view is shown that doesn't mention the actual reason (Shop Manager role doesn't have permission to manage plugins)

**Comment by dangermattic** [comment]
Thanks for reporting! 👍

**Comment by kidinov** [comment]
Comes from @jaclync report 

pdfdoF-5MC-p2#comment-6917
