### ISSUE TITLE
Remove outdated coupons banner from coupon list screen

### ISSUE THREAD

**Issue by JorgeMucientes** [woocommerce/woocommerce-android#12956]
iOS counterpart issue: https://github.com/woocommerce/woocommerce-ios/issues/14467

Coupons feature has been enabled for more than a year now. The current banner from the screen feels outdated and doesn't make sense anymore. Also the banner is shown when the search icon is tapped. 

https://github.com/user-attachments/assets/48e96398-fbdb-4aa3-83df-d2c255a11474

**Comment by dangermattic** [comment]
Thanks for reporting! 👍
