### ISSUE TITLE
[Woo POS - payments onboarding] Stripe account with overdue requirements loading after going back

### ISSUE THREAD

**Issue by kidinov** [woocommerce/woocommerce-android#12951]
(This feels like a higher-priority issue if it’s reproducible elsewhere) When I tap collect card payment after adding some products and submitting cart, then tap back from the fullscreen onboarding view without entering any information into the webview, the spinner starts blocking and never stops. I have to exit the app to get unstuck. This doesn’t happen if I tap connect your reader cta and then back. This is reproducible on my device

pdfdoF-5MC-p2#comment-6917

**Comment by dangermattic** [comment]
🚫 Please add a type label (e.g. **type: enhancement**) and a feature label (e.g. **feature: stats**) to this issue.
