### ISSUE TITLE
Customer detail email button is unresponsive

### ISSUE THREAD

**Issue by JorgeMucientes** [woocommerce/woocommerce-android#12954]
The email icon/button displayed from more menu -> Customers -> Customer detail is unresponsive. Tapping on the button doesn't do anything on Android.

![Image](https://github.com/user-attachments/assets/94673b26-aa3a-4dd9-b6a6-fb83b551a587)

We should replicate the behavior from order detail: 

https://github.com/user-attachments/assets/376eddcc-eb3f-49b8-8046-3f07648cb83e

**Comment by dangermattic** [comment]
🚫 Please add a type label (e.g. **type: enhancement**) and a feature label (e.g. **feature: stats**) to this issue.
