### ISSUE TITLE
Remove WCModel dependency from fetching Shipment Tracking Providers

### ISSUE THREAD

**Issue by AmandaRiu** [woocommerce/woocommerce-android#1296]
The FluxC endpoint to [FetchOrderShipmentProvidersPayload](https://github.com/wordpress-mobile/WordPress-FluxC-Android/blob/94352a045c5accedfcc4d375a48c435e505720bb/plugins/woocommerce/src/main/kotlin/org/wordpress/android/fluxc/store/WCOrderStore.kt#L244) requires passing in the entire `WCOrderModel`, but only the order's `remoteOrderId` is used for this process. In order to make this endpoint more flexible, let's remove the requirement for the entire `WCOrderModel` from FluxC and update the UI to use this newly updated endpoint. 

##TODO
- [ ] Update FluxC - remove the need for `WCOrderModel` and replace with `remoteOrderId`
- [ ] Update WCAndroid to use these changes

**Comment by anitaa1990** [comment]
Closing since this has been addressed in #2873 as part of the Order detail refactor.
