### ISSUE TITLE
[Woo POS - payments onboarding] There is a visible loading indicator right before connection dialog appears in the payment flow

### ISSUE THREAD

**Issue by kidinov** [woocommerce/woocommerce-android#12975]
https://github.com/user-attachments/assets/0780c5a2-ec22-4093-9b00-605b4973f986

And toolbar is also visible

**Comment by dangermattic** [comment]
🚫 Please add a type label (e.g. **type: enhancement**) and a feature label (e.g. **feature: stats**) to this issue.

**Comment by jaclync** [comment]
@kidinov 👋 It looks like this issue can be closed from the PR https://github.com/woocommerce/woocommerce-android/pull/13008? It wasn't closed by the PR probably because it was targeting the release branch.

**Comment by kidinov** [comment]
Yep, should be closed. @jaclync  thanks!
