### ISSUE TITLE
Media library fails to load if the site has a small media

### ISSUE THREAD

**Issue by hichamboushaba** [woocommerce/woocommerce-android#12989]
WordPress by default generates smaller alternative versions of uploaded media, when the uploaded media is already small, it doesn't, and this leads to an error: The property `media_details.sizes` will be empty, and instead of being returned as an empty object, it's returned as an array: https://a8c.sentry.io/issues/3946742926

~~This wasn't occurring frequently, but with the last update to switch to the `/wp/v2` endpoint (#12836), this will become more serious.~~
This issue happens only when using Jetpack CP, so the last change in #12836 won't cause any spike.

The issue was identified here https://github.com/woocommerce/woocommerce-ios/pull/14444#issuecomment-2493786382

**Comment by dangermattic** [comment]
Thanks for reporting! 👍

**Comment by hichamboushaba** [comment]
Reduced the priority since this impacts only Jetpack CP connections, and the recent PR #12836 won't cause any spike.
