### ISSUE TITLE
WooCommerce plugin version text field overlapping in smaller screens or larger fonts

### ISSUE THREAD

**Issue by rossanafmenezes** [woocommerce/woocommerce-android#12996]
**Describe the bug**
I noticed that because I'm on Beta for WooCommerce, the version of the plugin overlaps the title text on a smaller screen (just switched from a Pixel 7 Pro to a Pixel 9 and it's a big difference in size.) So I tested with an account that is not on Beta and the same happens if you increase the font size. 

**Screenshots**
| Beta | Regular version w/ increased font |
|-|-|
| <img src="https://github.com/user-attachments/assets/9ea3d27d-b077-45a9-ae72-7d9c1b674f03" width="350"/> | <img src="https://github.com/user-attachments/assets/319ee782-9250-4294-95b0-9d3dae547ba7" width="350"/> |

**Expected behavior**
I expect the text to adapt to the screen/font size without overlapping

**Mobile Environment**
Please include:
- Device: Pixel9
- Android version: 14

**Comment by dangermattic** [comment]
🚫 Please add a type label (e.g. **type: enhancement**) and a feature label (e.g. **feature: stats**) to this issue.

**Comment by rossanafmenezes** [comment]
I was playing around and sort of "fixed" it by changing the TextView for the WooCommerce plugin and version into a `com.woocommerce.android.ui.prefs.WCSettingsOptionValueView` But I did not push anything since I'm not sure if this would be a good approach. 

![Image](https://github.com/user-attachments/assets/87ca98d0-3693-4188-bd4e-8b1e9662c549)

Even if you increase the font the text won't overlap
![Image](https://github.com/user-attachments/assets/7284e0f5-716a-43de-902e-a77183066abf)
