### ISSUE TITLE
Connecting UI with real data

### ISSUE THREAD

**Issue by atorresveiga** [woocommerce/woocommerce-android#12998]
This task is for connecting real data with the new shipping flow.

- [x] Connecting products. https://github.com/woocommerce/woocommerce-android/pull/12981
- [x] Connecting shipping details https://github.com/woocommerce/woocommerce-android/pull/13029
- [x] Connecting addresses (full address support will be included in M2) https://github.com/woocommerce/woocommerce-android/pull/13036
- [x] Connecting shipping rates https://github.com/woocommerce/woocommerce-android/pull/13105
- [x] Shipment calculation  https://github.com/woocommerce/woocommerce-android/pull/13153

**Comment by dangermattic** [comment]
Thanks for reporting! 👍
