### ISSUE TITLE
[POS] Infinite Loading in POS Onboarding when back pressed

### ISSUE THREAD

**Issue by malinajirka** [woocommerce/woocommerce-android#13009]
**Describe the bug**
The app ends up in an infinite loading when I press the back button when the `choose payment provider` screen is displayed in the POS.

**To Reproduce**
Steps to reproduce the behavior - use site with both WooPayments and Stripe extension installed
1. Go to POS
2. Add products and tap on checkout
3. Tap on collect payment
4. Notice Choose payment gateway screen is shown
5. Tap on back
6. Notice the bug

**Expected behavior**
The app should go back to the checkout screen which should be fully visible.

https://github.com/user-attachments/assets/16664d0d-6046-4698-a497-0b2a4d7a0056

**Comment by dangermattic** [comment]
🚫 Please add a type label (e.g. **type: enhancement**) and a feature label (e.g. **feature: stats**) to this issue.

**Comment by kidinov** [comment]
That fixed as part of the onboarding project, but then fixed in another way in this PR, as the original fix has side effect 

https://github.com/woocommerce/woocommerce-android/pull/13008
