### ISSUE TITLE
[POS TPV Tracking] Send ipp_channel metadata in payment intent for IPP/POS

### ISSUE THREAD

**Issue by jaclync** [woocommerce/woocommerce-android#13000]
Technical plan: pdfdoF-5QB-p2
Equivalent iOS issue: https://github.com/woocommerce/woocommerce-ios/issues/14478 / PR: https://github.com/woocommerce/woocommerce-ios/pull/14479

Send `ipp_channel` metadata in the payment intent for IPP/POS with value `mobile_store_management`/`mobile_pos` respectively.

**Comment by dangermattic** [comment]
Thanks for reporting! 👍

**Comment by jaclync** [comment]
Now that the plugin & server changes are merged and server changes deployed, feel free to test the Android changes by creating orders using IPP and POS in the JN store using secret store with ID 12613 (no shorthand for this). The channel should show `In-Person (POS)` for POS transactions in wp-admin > Payments > Transactions. Alternatively, you can use Jetpack beta for the WooPayments plugin and use a branch that has the latest `develop` commit from Dec 5.

**Comment by jaclync** [comment]
Update: plugin zip is available now for installation in any sites: https://github.com/Automattic/woocommerce-payments/releases/tag/8.7.0-test-1 (under the Assets)
