### ISSUE TITLE
[Woo POS][non-simple products] Items list doesn't delete stale products

### ISSUE THREAD

**Issue by AnirudhBhat** [woocommerce/woocommerce-android#13015]
After successfully checking out order that contains variations from POS, it seems like we create stale variation products in the database and these needs to be deleted on items fetch in the items list.

**Steps to reproduce:**
1. Navigate to POS (More menu -> POS)
2. Add variations to cart and checkout
3. Ensure the payment is success
4. Navigate to the orders tab and ensure those variations are listed in the order detail screen
5. Now, come back to the POS items list screen
6. You see stale variation products listed in the items list

Note: You can also observe the stale variation products for a second if you navigate to the products tab. Since on first visit, we delete the stale products in the products screen, those get removed within few seconds.

**Expected behaviour**
Remove the stale products from the items list in POS.

**Comment by dangermattic** [comment]
Thanks for reporting! 👍
