### ISSUE TITLE
One time shipping label remains visible when the product is changed to a simple product

### ISSUE THREAD

**Issue by irfano** [woocommerce/woocommerce-android#13027]
**Describe the bug**
One time  shipping label is a feature for subscriptions. When a product is changed from a subscription to a simple product, the one-time shipping label remains visible.

**To Reproduce**
1. Go to Products tab.
2. Open an existing subscription product.
3. Tap "+ ADD MORE DETAILS" and add "Shipping".
4. Enable "One time shipping." and navigate back.
5. Tap "Product type."
6. Tap "Simple physical product" and select "YES, CHANGE" from the dialog.
7. Notice "One time shipping: Enabled" label.

**Screenshots**
<img src="https://github.com/user-attachments/assets/8ab2600c-7959-4af7-ad10-0905cdefeb64" width=300>

**Expected behavior**
"One time shipping: Enabled" label should be gone.

**Isolating the problem (mark completed items with an [x]):**
- [ ] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [x] This bug happens with a default WordPress theme active,
  or [Storefront](https://woocommerce.com/products/storefront/).
- [x] I can reproduce this bug consistently using the steps above.

**Mobile Environment**
Please include:
- Device: Pixel 9 Pro Emulator
- Android version: 14
- WooCommerce Android version: 21.2-rc-2

**Comment by dangermattic** [comment]
🚫 Please add a type label (e.g. **type: enhancement**) and a feature label (e.g. **feature: stats**) to this issue.
