### ISSUE TITLE
Given product details with "one time shipping" enabled but no other shipping values entered, when switching to simple product, Shipping card disappears.

### ISSUE THREAD

**Issue by hafizrahman** [woocommerce/woocommerce-android#13033]
# Steps to reproduce

1. Create a Simple Subscription product,
2. Go to Add More Details > Shipping,
3. Enable "One time shipping" but don't fill in another values, then press back,
4. Confirm that "Shipping" card is shown with "One time shipping: Enabled" text shown,
4,Publish the product,
5. Once published, tap "Product Type" card and switch to "Simple Physical Product", confirm the change,
6. "Shipping" is now missing and if you tap "Add More Details", it's not listed there too.

This makes it impossible to edit Shipping values anymore.

# Expected
on step 6, either "Shipping" card should still exist without any label, or be selectable from "Add more details".

**Isolating the problem (mark completed items with an [x]):**
- [ ] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [x] This bug happens with a default WordPress theme active,
  or [Storefront](https://woocommerce.com/products/storefront/).
- [x] I can reproduce this bug consistently using the steps above.

**Mobile Environment**
Please include:
- Device: Pixel 8 Emulator
- Android version: 14
- WooCommerce Android version: 21.2-rc-2

**Comment by dangermattic** [comment]
Thanks for reporting! 👍
