### ISSUE TITLE
Fix tracking for dashboard performance card and top performers when selecting custom range

### ISSUE THREAD

**Issue by JorgeMucientes** [woocommerce/woocommerce-android#13055]
Fix tracking for dashboard performance card and top performers when selecting custom range. 

In Android we are tracking some of the custom range dashboard interaction using a legacy event that should've been removed back when we worked on the dynamic dashboard project. The event is `dashboard_stats_custom_range_tab_selected` and was used back when the dashboard had tabs to select the date ranges. 
We track this event every time the user clicks on the drop-down and selectect `custom`. Note the first time the user selects `custom` the event `dashboard_stats_custom_range_add_button_tapped` will be fired. But after adding a custom range subsequent taps on `custom range` option will trigger the legacy event. 

Extra context: pe5sF9-3o5-p2#comment-4155

**Comment by dangermattic** [comment]
🚫 Please add a type label (e.g. **type: enhancement**) and a feature label (e.g. **feature: stats**) to this issue.
