### ISSUE TITLE
Tracks: setting_changed_fail event issue

### ISSUE THREAD

**Issue by AmandaRiu** [woocommerce/woocommerce-android#1305]
Reported by @anitaa1990 : `setting_change_failed` – Simulated by switching off the internet when toggling privacy settings. Verified that the event is being received in Tracks. But there are no event props for the event. I can see the event props being sent from the Logcat and there are no errors but not able to see this in Tracks.

**Comment by anitaa1990** [comment]
Update: Looking in Tracks, I noticed that it takes a while for the event details to be updated 🤦‍♀. I am able to see two of the event props:`error_type` and `error_context`. The `error_message` was empty so the `error_message` prop was not sent.

@AmandaRiu should we try to simulate the `error_message` prop to ensure that it is being received before we validate the event?

**Comment by AmandaRiu** [comment]
> should we try to simulate the error_message prop to ensure that it is being received before we validate the event?

@anitaa1990 I think that's a great idea, just to be sure.

**Comment by anitaa1990** [comment]
Verified that the `error_message`, if available if sent along with the other event props and validated the event in Tracks. So closing this issue
