### ISSUE TITLE
Many (incl old) releases tagged on GitHub

### ISSUE THREAD

**Issue by keunes** [woocommerce/woocommerce-android#13089]
Hello

I'm interested in following the new Android releases. However, regularly new pre-releases (release candidates) get tagged of older app versions. For example:
![Screenshot_20241207-083526.png](https://github.com/user-attachments/assets/2566a737-8643-4c31-93d3-d036d59f063b)

As far as I know, Android doesn't support point releases for older versions (?) If that's indeed the case, then I don't understand also why there are multiple versions tagged (20.5 & 20.6 while 21.0 is tagged also)

**Comment by dangermattic** [comment]
🚫 Please add a type label (e.g. **type: enhancement**) and a feature label (e.g. **feature: stats**) to this issue.

**Comment by keunes** [comment]
I selected the label 'releases' when creating the issue but it was removed/did not get saved and I am not allowed to add one now.

**Comment by hichamboushaba** [comment]
Hi @keunes, thanks for filing the bug report, this was just a one incident, multiple release candidate versions were accidentally kept in the draft state for few weeks, and when we published them, Github notified you, please use just the last version, the old ones are older versions.

I'm closing the ticket.
