### ISSUE TITLE
[Woo POS][non-simple products] Updated designs for "retry pagination error"

### ISSUE THREAD

**Issue by AnirudhBhat** [woocommerce/woocommerce-android#13114]
<img width="310" alt="Image" src="https://github.com/user-attachments/assets/1eeb2b39-e517-4d5e-aa5a-49b8539b8e87" />

The goal of this task is to update the "retry pagination error" UI on both products and variations screen.

**Comment by dangermattic** [comment]
🚫 Please add a type label (e.g. **type: enhancement**) and a feature label (e.g. **feature: stats**) to this issue.
