### ISSUE TITLE
[Woo POS][Cash & Receipts] Reimlement the UI of the cash payment screen as per new design

### ISSUE THREAD

**Issue by kidinov** [woocommerce/woocommerce-android#13121]
p1733995736575739-slack-C070SJRA8DP

<img width="1204" alt="Image" src="https://github.com/user-attachments/assets/d7ce7924-b115-4fc0-af55-524cc9c32f1d" />

**Comment by dangermattic** [comment]
🚫 Please add a type label (e.g. **type: enhancement**) and a feature label (e.g. **feature: stats**) to this issue.
