### ISSUE TITLE
[Woo POS][Cash & Receipts] Reimplement the payment success screen as per changed design

### ISSUE THREAD

**Issue by kidinov** [woocommerce/woocommerce-android#13129]
rNAclWFAdQRw7EXEcsNVai-fi-3248_6346

<img width="783" alt="Image" src="https://github.com/user-attachments/assets/f8abaa48-9276-4492-a800-5c347992fb25" />

**Comment by dangermattic** [comment]
🚫 Please add a type label (e.g. **type: enhancement**) and a feature label (e.g. **feature: stats**) to this issue.
