### ISSUE TITLE
[Woo POS] Crash when connecting reader, after backgrounding the app, and restoring state

### ISSUE THREAD

**Issue by samiuelson** [woocommerce/woocommerce-android#13146]
Sentry: https://a8c.sentry.io/issues/6138913717/?project=1459556
Discovery: https://wp.me/pdfdoF-5ZI#comment-7145

Description:

In Woo POS a crash occurs when connecting reader. 

Steps to repro
1. Go to Woo POS (More > Point Of Sale)
2. Add items to cart
3. > Checkout
4. Click "Connect to reader"
5. Wait for reader connection dialog
6. Move app to background
7. Observe crash

Logs:
```kotlin
java.lang.ClassCastException: com.woocommerce.android.ui.woopos.home.totals.WooPosTotalsViewModel$$ExternalSyntheticLambda0 cannot be cast to java.io.Serializable
                                                                                                    	at com.woocommerce.android.ui.woopos.home.totals.WooPosTotalsViewState$ReaderStatus$Disconnected.writeToParcel(Unknown Source:22)
```

**Comment by dangermattic** [comment]
🚫 Please add a type label (e.g. **type: enhancement**) and a feature label (e.g. **feature: stats**) to this issue.
