### ISSUE TITLE
[Woo POS][Cash & Receipts] Implement UI changes

### ISSUE THREAD

**Issue by kidinov** [woocommerce/woocommerce-android#13176]
* Copy on the success screen
  * A card payment of...
  * A cash payment of...
* Change due color - secondary

p1734692882782219/1734615162.822509-slack-C070SJRA8DP

**Comment by dangermattic** [comment]
🚫 Please add a type label (e.g. **type: enhancement**) and a feature label (e.g. **feature: stats**) to this issue.
