### ISSUE TITLE
[Woo POS][non-simple products] Add tests for Variations data source and remove virtual filtering

### ISSUE THREAD

**Issue by AnirudhBhat** [woocommerce/woocommerce-android#13189]
The objective of this task is to enhance test coverage by adding unit tests for the `WooPosVariationsDataSource` class. Additionally, the filtering logic for variations will be moved into this class. As part of this task, virtual variations will also be included, aligning with the ongoing discussion.

**Comment by dangermattic** [comment]
Thanks for reporting! 👍
