### ISSUE TITLE
Order push notifications removed when reviews tab becomes active

### ISSUE THREAD

**Issue by nbradbury** [woocommerce/woocommerce-android#1319]
When the user switches to the reviews tab [we remove all push notifications](https://github.com/woocommerce/woocommerce-android/blob/19cbe4a4e0d0a279db32ca91e2a74992045907e7/WooCommerce/src/main/kotlin/com/woocommerce/android/ui/main/MainActivity.kt#L510) from the system bar. Likewise, when the user taps the "Mark all read" icon on the reviews tab, all notifications are removed.

This made sense when it was the notifications tab, but now that we only show reviews we should only be removing review push notifications from the system bar.

@kyleaparker Related to this, I'm wondering if we should remove order push notifications when the user switches to the order tab? Otherwise the order notification remains until the user manually taps it.

**Comment by nbradbury** [comment]
This one should probably be tackled at the same time as #1313

**Comment by kyleaparker** [comment]
>@kyleaparker Related to this, I'm wondering if we should remove order push notifications when the user switches to the order tab? Otherwise the order notification remains until the user manually taps it.

Yes I think this makes sense
