### ISSUE TITLE
Store Stats: Negative column showing in stats chart

### ISSUE THREAD

**Issue by rachelmcr** [woocommerce/woocommerce-android#1348]
**Describe the bug**

I see a negative column showing in my store stats chart. This corresponds with a refund I did on an order, but in the chart I can't see any date or amount so it's unclear what it refers to. (I had to check my store in a web browser to confirm what it was.)

**To Reproduce**
1. Refund one or more orders in your store, until you have refunded more than you earned today (for example, by refunding orders from previous days).
2. In the app, go to the store dashboard.
3. Refresh the screen to get the latest stats.
4. Note that today's column is now negative in the stats chart.

**Screenshots**

<img src="https://user-images.githubusercontent.com/8658164/63039306-efed1f80-beba-11e9-93de-fda04e621ab2.png" width="50%">

**Expected behavior**

I expect the stats chart to at least be legible for negative amounts, e.g. to have the date and amount visible when I tap on that column in the chart.

**Isolating the problem (mark completed items with an [x]):**
- [ ] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [x] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [x] I can reproduce this bug consistently using the steps above.

**Mobile Environment**
Please include:
- Device: moto e5 play
- Android version: 8.1
- WooCommerce Android version: 2.5-rc-1

**Comment by anitaa1990** [comment]
Update: this is fixed as part of the stats UI improvements [here](https://github.com/woocommerce/woocommerce-android/pull/1372) that will be released in sprint 2.7.

### Sample interaction
<img width="300" src="https://user-images.githubusercontent.com/22608780/63743553-3d558d80-c8ba-11e9-97db-6389de01bd77.gif">

**Comment by anitaa1990** [comment]
Closing issue via #1372
