### ISSUE TITLE
“Cannot connect to..” error message can still happen despite the new login flow and on that screen "view connected sites" and "try another account" buttons don’t work

### ISSUE THREAD

**Issue by grigorijurasov** [woocommerce/woocommerce-android#1356]
**Describe the bug**
“Cannot connect to..” error message can still happen despite the new login flow and on that screen "view connected sites" and "try another account" buttons don’t work

**To Reproduce**
1. Credentials in 2285617-zen
2. Enter site URL and login credentials
3. See the "cannot connect to.." error message
4. It is possible to press the physical Android "Back" key but if the app is closed and re-opened - that doesn't work anymore and the only way to get out of that screen is to re-install the app.

**Expected behavior**
"View connected sites" and "try another account" buttons should still work.

**Isolating the problem (mark completed items with an [x]):**
- [ ] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [ ] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [x] I can reproduce this bug consistently using the steps above.

**Mobile Environment**
Please include:
- Device: Android simulator
- Android version: 8.0.0
- WooCommerce Android version: 2.4

**Comment by mindgraffiti** [comment]
I can log in with iOS, v 2.6 / `develop` branch. Strange that there were two of the same stores listed, one with `www` in the address and one without it.

**Comment by AmandaRiu** [comment]
This was an issue with an installed plugin (Custom Login Page Customizer). The user uninstalled this plugin and the issue was fixed.

**Comment by AmandaRiu** [comment]
This was an issue with an installed plugin (Custom Login Page Customizer). The user uninstalled this plugin and the issue was fixed.

**Comment by AmandaRiu** [comment]
Reopening as the real issue that was being reported was that when the user clicked on the buttons "Login with a different account" and "View connected stores", nothing would happen. Maybe a network connection issue we're not handling?
