### ISSUE TITLE
Empty view no longer stretching to fill view

### ISSUE THREAD

**Issue by AmandaRiu** [woocommerce/woocommerce-android#1384]
**Describe the bug**
"No orders" and "No reviews" empty view no longer stretches to fill view

**To Reproduce**
Login to a store with no orders and no reviews

**Screenshots**
<img src="https://user-images.githubusercontent.com/5810477/63813569-e0ba9880-c8e2-11e9-8823-5d408f88bfd9.png" width="300"/> <img src="https://user-images.githubusercontent.com/5810477/63813572-e0ba9880-c8e2-11e9-878d-145f7bc6bba9.png" width="300"/>

**Expected behavior**
Empty view fills the view

**Comment by anitaa1990** [comment]
Update: this is fixed as part of this [Order list redesign PR](https://github.com/woocommerce/woocommerce-android/pull/1404#issuecomment-528440199)

**Comment by anitaa1990** [comment]
Fixed as part of the [Order list redesign PR](https://github.com/woocommerce/woocommerce-android/pull/1404#issuecomment-528440199) and the [Product Reviews feature PR](https://github.com/woocommerce/woocommerce-android/pull/1440)
