### ISSUE TITLE
Notifications by order type, "processing", or "awaiting payment" would sound different from the order.

### ISSUE THREAD

**Issue by chukran** [woocommerce/woocommerce-android#1415]
Notifications by order type, "processing", or "awaiting payment" would sound different from the order.

This could also have in email settings if we could customize emails as the payment type changes the email sent.

Finally I live in Brazil that has a form of payment called "Boleto Bancário" is a type of payment widely used here and accepted in many places, we pay all bills via barcode, including the card bill, finally people pay in the bank and it takes a few days to process, but if you had notifications for changing the status of orders this would be very helpful because it would order, but would make an order notification sound received and when the payment was paid and changed the status to " processing "would have a notification with a sound each status could have a different notification.

Because sometimes it is a false request, since often the person issues the bill but does not pay.

**Comment by chukran** [comment]
I forgot to mention, have multi-notifications, because when we have more than 1 request if the notification of the phone stays there the sound does not play, and does not have that stack of notifications which is interesting to have or a grouping of notifications and each new one. , be played a sound and given total order value, and total billing value, would be a nice parameter to be see in the app, because notifications is a part that stimulates in an online store, thanks

**Comment by AmandaRiu** [comment]
Thank you for using the Woo Mobile app! Feature requests are not currently processed in GitHub. Please go to [this link](http://ideas.woocommerce.com/forums/133476-woocommerce?category_id=84283) to either up-vote this feature on the ideas board, or to add a new feature request if it doesn't already exist.
