### ISSUE TITLE
login to multiple stores in the same app

### ISSUE THREAD

**Issue by chukran** [woocommerce/woocommerce-android#1416]
It is a feature that I missed that could be very interesting, since many people have several stores and various domains would be very interesting!

**Comment by AmandaRiu** [comment]
Thank you for using the Woo Mobile app! Feature requests are not currently processed in GitHub. Please go to [this link](http://ideas.woocommerce.com/forums/133476-woocommerce?category_id=84283) to either up-vote this feature on the ideas board, or to add a new feature request if it doesn't already exist.
