### ISSUE TITLE
Improve Subscription Order Details

### ISSUE THREAD

**Issue by zwiesman31** [woocommerce/woocommerce-android#1418]
**Is your feature request related to a problem? Please describe.**
Normally, [WooCommerce Subscriptions](https://woocommerce.com/products/woocommerce-subscriptions/?aff=10486&cid=1131038) orders include a `Related Orders` section so the Store Admin can see more information about the subscription: 

![https://cld.wthms.co/LJiDV5](https://cld.wthms.co/LJiDV5+)
Image link: https://cld.wthms.co/LJiDV5

The app does not include that information, so it's hard to manage subscriptions.

**Describe the solution you'd like**
A way to bring the `Related Orders` information into the app.

**Describe alternatives you've considered**
A link to the individual order in the WP Admin so the user can click that link for more info (if needed).

**Additional context**
Since we now own [WooCommerce Subscriptions](https://woocommerce.com/products/woocommerce-subscriptions/?aff=10486&cid=1131038), I feel that we should look to include order functionality for it instead of thinking about this as an `enhancement`.

**Comment by shiki** [comment]
This is being considered and we'll split out the work into separate issues when the designs and planning have completed. For now, I will close this feature request to clean up the backlog.
