### ISSUE TITLE
Submit Refund

### ISSUE THREAD

**Issue by astralbodies** [woocommerce/woocommerce-android#142]
**User Story**
I would like to have the option to refund any payments on the current order.

![orderDetail_payment_info.png](https://images.zenhubusercontent.com/5a4ff713a016c5b034bc30f9/516c4ac4-36e8-48bf-bd9e-ed35125fa511)

**Comment by AmandaRiu** [comment]
New refunds designs are actively being worked on. The designs in this ticket should be updated as soon as those designs are finished and approved.

**Comment by AmandaRiu** [comment]
Closing this ticket as a new one will be created when the designs are finished and approved, and the project is ready to be developed on.
