### ISSUE TITLE
i can't receiving notification in app when new order comes ?

### ISSUE THREAD

**Issue by ArslanKathia** [woocommerce/woocommerce-android#1424]
when i install the app in device i got this error in log 
> **FirebaseInstanceId: Token retrieval failed: INVALID_PARAMETERS** 

and also getting this
> **WooCommerce-NOTIFS: Empty FCM token, can't register the id on remote services**

even when i refresh the order screen comes but the notification for new order isn't coming.
please let me know where i am wrong how to resolve this issue.

**Comment by AmandaRiu** [comment]
Hello! In order to get notifications working you'd have to have access to your own FCM server/account. We don't publish those credentials to the public.
