### ISSUE TITLE
Push Notification to App

### ISSUE THREAD

**Issue by NASMAK-Technologies** [woocommerce/woocommerce-android#1434]
I am not getting push notifications into the app. I have created the firebase account and places the JSON into google-services.json-example. where I can place the firebase key on the web server? Or do I need to install any specific plugin on the WooCommerce website to push the notification to the app?

**Comment by AmandaRiu** [comment]
> where I can place the firebase key on the web server?

I'm not sure honestly, we didn't set up the web server in mobile. The google docs for firebase should help you in that area. 

> do I need to install any specific plugin on the WooCommerce website to push the notification to the app

The WooCommerce site should have Jetpack installed and connected to a WordPress.com account - you'd log into the app with this same WordPress.com account. Other than that, there are no special plugins required. 

The woocommerce-android mobile team is very small so we're unable to provide troubleshooting assistance for outside developers currently.
