### ISSUE TITLE
Reviews: Review detail is blank after opening a review push notification when app is closed

### ISSUE THREAD

**Issue by rachelmcr** [woocommerce/woocommerce-android#1463]
**Describe the bug**

After opening a review push notification when the app is completely closed, the review detail screen appears but never loads.

1. Working: Opening a review push notification when the Woo app is still running in the background.
2. Not working: Opening a review push notification when the Woo app is completely closed.

**To Reproduce**

1. Completely close the Woo app.
2. Receive a review push notification.
3. Tap the push notification to open the app.

Result: The app opens on the Reviews tab, but all I see is a placeholder.

If I tap the back arrow in the top left, I'm taken to the Reviews list where I can see the new review at the top of the list. From there, I can tap to open the review.

**Screenshots**
<img src="https://user-images.githubusercontent.com/8658164/66652195-04386900-ec2d-11e9-94b9-425bf2987f16.png" width="50%">

**Isolating the problem (mark completed items with an [x]):**
- [ ] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [x] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [x] I can reproduce this bug consistently using the steps above.

**Mobile Environment**
Please include:
- Device: moto e5 play
- Android version: 8.1.0
- WooCommerce Android version: 2.8-rc-1

Logs from the app:

```
[Oct-11 12:31 WP d] API Dispatching action: WCProductAction-FETCH_SINGLE_PRODUCT_REVIEW
[Oct-11 12:31 WP d] API Dispatching action: WCProductAction-FETCHED_SINGLE_PRODUCT_REVIEW
[Oct-11 12:31 UTILS i] 🔵 Tracked: review_loaded, Properties: {"id":762,"blog_id":137210602,"is_wpcom_store":true}
[Oct-11 12:31 WP d] API Dispatching action: WCProductAction-FETCH_SINGLE_PRODUCT
[Oct-11 12:31 UTILS i] 🔵 Tracked: back_pressed, Properties: {"context":"MainActivity"}
[Oct-11 12:31 REVIEWS e] Exception encountered while fetching a single product - exception: Job was cancelled
[Oct-11 12:31 REVIEWS e] StackTrace: kotlinx.coroutines.JobCancellationException: Job was cancelled; job=JobImpl{Cancelling}@54dad73
```

**Comment by AmandaRiu** [comment]
Fixed in #1466. Closing.
