### ISSUE TITLE
Improve order data storage in FluxC

### ISSUE THREAD

**Issue by aforcier** [woocommerce/woocommerce-android#147]
The initial implementation of order list fetching in FluxC ~will take~ took the same approach as posts (clearing out stored orders every time the most recent orders are re-fetched). It would be better to think about a different approach and persist more order data for offline access. This raises some issues about data staleness that will require some extra implementation and planning.

WPAndroid switched to using a custom suite of list management tools designed by @oguzkocer which not only makes list management faster, but also takes care of caching and updating lists as needed.

**Comment by AmandaRiu** [comment]
Note: as part of hack week, @oguzkocer and I finished the FluxC side of implementing the new order list management system for order lists. This is a new feature and will require changes on the front end to make use of the new code. The FluxC PRs relevant to this are:
- 1: https://github.com/wordpress-mobile/WordPress-FluxC-Android/pull/1235
- 2: https://github.com/wordpress-mobile/WordPress-FluxC-Android/pull/1237
- 3: https://github.com/wordpress-mobile/WordPress-FluxC-Android/pull/1238
and as of this writing are still awaiting review.

**Comment by anitaa1990** [comment]
Closed via #1559
