### ISSUE TITLE
Orders: Order count for status filters is not updated until app is relaunched

### ISSUE THREAD

**Issue by rachelmcr** [woocommerce/woocommerce-android#1488]
**Describe the bug**

If I change the status on one or more orders, and then open the Orders search, the list of status filters shows an outdated count for orders with that status. The count isn't updated until the app is relaunched.

**To Reproduce**
1. Go to the Orders section.
2. Check the count for Processing orders on the Orders badge.
3. Tap the search icon and note that the count next to Processing matches.
4. Go to the Processing tab in Orders and fulfill an order.
5. Note that the Orders badge count is updated (decreased by 1).
6. Tap the search icon and note that the count next to Processing is unchanged.
7. Close and relaunch the app, and note that when you tap the search icon the count next to Processing is updated to match the Orders badge count.

**Screenshots**

I started with 13 Processing orders, and then fulfilled one order.

The Orders badge count correctly reflects the updated number (12):

<img src="https://user-images.githubusercontent.com/8658164/67281021-66fbf100-f4c6-11e9-8b91-7253856c36cb.png" width="50%">

The count for the Processing status filter still shows the old number (13):

<img src="https://user-images.githubusercontent.com/8658164/67281043-754a0d00-f4c6-11e9-98ae-e88849b523e0.png" width="50%">

**Expected behavior**

I expect the count on the status filters to update when an order changes status.

**Isolating the problem (mark completed items with an [x]):**
- [ ] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [x] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [x] I can reproduce this bug consistently using the steps above.

**Mobile Environment**
Please include:
- Device: moto e5 play
- Android version: 8.1.0
- WooCommerce Android version: 2.9-rc-1

**Comment by anitaa1990** [comment]
Closed via #1491
