### ISSUE TITLE
Orders: Order unexpectedly appears on Search orders screen after rotating device

### ISSUE THREAD

**Issue by rachelmcr** [woocommerce/woocommerce-android#1489]
**Describe the bug**

After viewing an order status filter and rotating the device to landscape, going back to the list of order statuses (on the "Search orders" screen) and rotating the device again shows an order at the bottom of the list of order statuses.

**To Reproduce**
1. Go to the Orders section.
2. Tap on the search icon.
3. Select a status from the Order status list.
4. Rotate your device to landscape.
5. Tap the back arrow to go back to the Search orders screen.
6. Rotate your device back to portrait.

Result: An order appears at the bottom of the Order status list.

**Screenshots**

<img src="https://user-images.githubusercontent.com/8658164/67281817-32893480-f4c8-11e9-958b-a4fa65f0df4f.png" width="50%">

**Expected behavior**

I expect to see only the Order status list, with no other content on that screen.

**Isolating the problem (mark completed items with an [x]):**
- [ ] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [x] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [x] I can reproduce this bug consistently using the steps above.

**Mobile Environment**
Please include:
- Device: moto e5 play
- Android version: 8.1.0
- WooCommerce Android version: 2.9-rc-1

**Comment by anitaa1990** [comment]
Closed via #1491
