### ISSUE TITLE
Orders: Processing shows all orders instead of empty message after viewing order status filters

### ISSUE THREAD

**Issue by rachelmcr** [woocommerce/woocommerce-android#1490]
**Describe the bug**

On a store with no Processing orders, after viewing an Order status filter the Processing tab will show all orders.

**To Reproduce**
1. Open a store in the app with no orders with the `Processing` status.
2. Go to the Orders section.
3. Confirm the Processing tab shows the "All orders have been processed" message.
4. Tap the search icon.
5. Select an Order status filter.
6. Tap the back arrow twice to exit the search and return to the Processing tab. Note that the tab now shows all orders.
7. Pull to refresh and note that the tab doesn't change.
8. Switch to All Orders and back to Processing and note that the Processing tab now shows the correct message (as in step 3).

**Screenshots**

<img src="https://user-images.githubusercontent.com/8658164/67283040-dd025700-f4ca-11e9-9fa9-ef64fa330c88.png" width="50%">

**Expected behavior**

I expect the Processing tab to show the empty message every time I return to it. (This works as expected when I do a regular search and then go back.)

**Isolating the problem (mark completed items with an [x]):**
- [ ] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [x] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [x] I can reproduce this bug consistently using the steps above.

**Mobile Environment**
Please include:
- Device: moto e5 play
- Android version: 8.1.0
- WooCommerce Android version: 2.9-rc-1

**Comment by anitaa1990** [comment]
Closed via #1491
