### ISSUE TITLE
Beta bug: Order count in filter/search screen not updating

### ISSUE THREAD

**Issue by AmandaRiu** [woocommerce/woocommerce-android#1492]
**Describe the bug**
If status changes to orders happen outside the app, the order count for that status in the Filter/Search section does not refresh even though the request was sent to get the new counts and a response was returned with the valid count. Usually takes clicking on various screens to finally get it to update. 

**To Reproduce**
1. Go to **Orders** tab, note the total # of orders in "Processing" for the badge. 
2. Open the search screen. Note the total order count for "processing". 
3. Log into the test store's wp-admin. Do a batch update to move all "processing" orders to "waiting approval" (or whatever change you want to make - this just makes it really easy to spot).
4. Go back to the app and do a "pull-to-refresh". Notice the badge count updates appropriately.
5. Open the search screen. Note the total order count for "processing" has not changed.

**Expected behavior**
The total order count for the filtered item updates

**Comment by AmandaRiu** [comment]
cc: @anitaa1990

**Comment by anitaa1990** [comment]
Fixed via #1493
