### ISSUE TITLE
Grouped Products

### ISSUE THREAD

**Issue by AmandaRiu** [woocommerce/woocommerce-android#1516]
Grouped products are not being displayed correctly in the app. I have a group named "Logo Outfit" that contains 3 different products ranging from $18 - $45:

![Screen Shot 2019-10-30 at 4 55 54 PM](https://user-images.githubusercontent.com/5810477/67907807-73bbbd00-fb36-11e9-9252-473fa3a7b803.png)

In the app it just shows this grouped product as a single product with a price of $18:

<img src="https://user-images.githubusercontent.com/5810477/67907819-8209d900-fb36-11e9-89d4-585d4b715395.png" width="300"/>

cc: @nbradbury since you are actively working on this project

**Comment by anitaa1990** [comment]
Closing this since we are revamping the grouped products screen in the next release
