### ISSUE TITLE
Invalid currency behavior

### ISSUE THREAD

**Issue by AmandaRiu** [woocommerce/woocommerce-android#152]
If the currency code provided in WCOrderModel is invalid, what should the default behavior be for displaying a currency symbol? Currently #130 is just putting a "?" as a placeholder for the currency symbol (see screenshot below). 

Should we keep this as-is or default to "USD"? 

![screenshot_1518560135](https://user-images.githubusercontent.com/5810477/36177267-6529b576-10d2-11e8-947e-b51cc2ba4ff7.png)

**Comment by anitaa1990** [comment]
I noticed, we migrated the currency formatting to Fluxc, sometime ago.

> Quick answer for temporary fix: In this scenario, we should remove "?", and leave just the units. The store owner should have enough context about their store and setup they chose to know the currency type.
We are already doing this at the moment [here](https://github.com/wordpress-mobile/WordPress-FluxC-Android/blob/d19ad4c3aa3670626ebc8a75a341ba45517299aa/plugins/woocommerce/src/main/kotlin/org/wordpress/android/fluxc/utils/WCCurrencyUtils.kt#L43). 

#### Screenshot on the current implementation:
<img width="300" src="https://user-images.githubusercontent.com/22608780/59407520-13b6bb00-8dcf-11e9-9d0b-86e3890de17e.png">

I'm not sure if this is how Woo Core handles it though. Should we close this issue as implemented or confirm with someone from Woo core and implement a proper solution from there?

**Comment by AmandaRiu** [comment]
@anitaa1990 I'm going to close this issue as implemented since the area the ticket is covering is implemented.
