### ISSUE TITLE
Refunds: Backspacing in the manual refund amount field deletes 2 characters at a time

### ISSUE THREAD

**Issue by rachelmcr** [woocommerce/woocommerce-android#1539]
**Describe the bug**

When I enter an amount in the manual refund amount field, and then backspace to remove a character, it deletes 2 characters at a time instead of 1.

**To Reproduce**
1. Go to the Orders tab.
2. Select a completed order.
3. Scroll down to the Payment section and tap Issue Refund.
4. Enter an amount for the refund.
5. Tap the backspace button once.
6. Notice that the last 2 numbers were deleted.

**Screenshots**

Refund amount entered (12.34):

<img src="https://user-images.githubusercontent.com/8658164/68391375-636f9780-015f-11ea-87ae-1b39dc5fb9dc.png" width="50%">

Refund amount after tapping the backspace button once (0.12):

<img src="https://user-images.githubusercontent.com/8658164/68391475-a16cbb80-015f-11ea-91f0-dd9db3f78aa2.png" width="50%">

**Expected behavior**

I expected 1 number to be deleted at a time.

**Isolating the problem (mark completed items with an [x]):**
- [ ] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [x] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [x] I can reproduce this bug consistently using the steps above.

**Mobile Environment**
Please include:
- Device: moto e5 play
- Android version: 8.1.0
- WooCommerce Android version: 3.0-rc-1

**Comment by rachelmcr** [comment]
Just a note that this also occurs in the new editable product details section, in the price fields. (Products > Select a product > Select Price > backspace in the `Regular price` or `Sale price` fields.)

Tested on moto e5 play, Android 8.1.0 Woo Android 3.8-rc-1

**Comment by 0nko** [comment]
Tested on Pixel 4 (Android 11) and different Android versions on an emulator and I can't reproduce this bug anymore.
