### ISSUE TITLE
Add tracks events for product images

### ISSUE THREAD

**Issue by nbradbury** [woocommerce/woocommerce-android#1556]
Now that we've added support for adding & removing product images, we should track these events. I've updated our [tracks spreadsheet](https://docs.google.com/spreadsheets/d/17cKoFpHQpUMNo-stHSIyEyHbOZ30AIikTHWf9GKVwI0/edit#gid=86001244) with these two new events.

**Comment by JavonDavis** [comment]
Hey! Bumping this to `3.2`, if you'd like to get it in for this release please merge this into release/3.1 and then DM me to release a new Beta version.`

**Comment by nbradbury** [comment]
Closed via #1560
