### ISSUE TITLE
Change product image service to only upload images

### ISSUE THREAD

**Issue by nbradbury** [woocommerce/woocommerce-android#1557]
Right now the product image service handles both uploading and removing images, which complicates its use. Removing images isn't a long-running task and can be handled elsewhere to simplify the service.

**Comment by JavonDavis** [comment]
Hey! Bumping this to `3.2`, if you'd like to get it in for this release please merge this into release/3.1 and then DM me to release a new Beta version.`

**Comment by nbradbury** [comment]
Closed via #1561
