### ISSUE TITLE
v4 stats issue: Endpoint moved in wc-admin v0.22

### ISSUE THREAD

**Issue by AmandaRiu** [woocommerce/woocommerce-android#1570]
In [this wc-admin PR](https://github.com/woocommerce/woocommerce-admin/pull/3204), the namespace was moved from the  `wc/v4` API namespace to `wc-analytics`. Since the v4 stats is still a beta feature, we'll need to do the following:
- update the endpoints to use `wc-analytics`
- check the version of `wc-admin` and only support version >= 0.22
- if the user has been using the v4 stats but has not upgraded `wc-admin` to the latest version, display this in the message card: “Stats has been reverted to the non-beta version. To use the beta v4 stats please upgrade the wc-admin plugin to  version v0.22 or higher.“ 

**NOTE** This fix should be applied to the current beta release.

**Comment by AmandaRiu** [comment]
cc: @anitaa1990

**Comment by JavonDavis** [comment]
Hey! Bumping this to `3.2`, if you'd like to get it in for this release please merge this into release/3.1 and then DM me to release a new Beta version.`

**Comment by anitaa1990** [comment]
Closed via #1575
