### ISSUE TITLE
Login: Lost Password link on self-hosted credentials screen doesn't work

### ISSUE THREAD

**Issue by rachelmcr** [woocommerce/woocommerce-android#1576]
**Describe the bug**

When you choose to log in with your self-hosted site credentials, the "Lost your password?" link doesn't work. Instead, when you tap on it a toast message pops up with this error:

> Unable to open the link

Based on the error messages, the link is malformed: If I enter the site address `example.com` it tries to open the lost password link at `example.comwp-login.php?action=lostpassword`.

cc @anitaa1990 

**To Reproduce**
1. Open the app while logged out, and select Log In.
2. Enter the URL for a WooCommerce store with Jetpack connected.
3. Select the option to "log in with site credentials."
4. On the site credentials screen, select "Lost your password?" and note the message that appears.

**Screenshots**

![Screenshot_20191119-111818](https://user-images.githubusercontent.com/8658164/69165797-0f16d100-0aea-11ea-880d-2cdb4335e114.png)

**Expected behavior**

I expect the app to open the correct lost password page for my site. (I confirmed that this works as expected if I go through the WordPress.com credentials flow and use the lost password link for WordPress.com.)

**Isolating the problem (mark completed items with an [x]):**
- [x] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [x] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [x] I can reproduce this bug consistently using the steps above.

**Mobile Environment**
Please include:
- Device: moto e5 play
- Android version: 8.1
- WooCommerce Android version: 3.1-rc-1

**Comment by anitaa1990** [comment]
Closed via #1589
