### ISSUE TITLE
Dark Mode: Add new setting option

### ISSUE THREAD

**Issue by AmandaRiu** [woocommerce/woocommerce-android#1583]
Add new settings option to configure Dark Mode. This includes:
- New option and shared prefs
- Tracks event to track changes

Per the [Android docs](https://developer.android.com/guide/topics/ui/look-and-feel/darktheme#changing_themes_in-app), the options should be slightly different on devices running Android 9 or earlier.

### API 29+ (Android 10 or higher)
- Light
- Dark
- **System default** (recommended default)

### API 28 and lower
- Light
- Dark
- **Set by Battery Saver** (recommended default)

![Screen Shot 2019-11-19 at 9 21 12 PM](https://user-images.githubusercontent.com/5810477/69209107-4352b780-0b13-11ea-9be0-30fa6e4485e9.png)

![Screen Shot 2019-11-19 at 9 21 17 PM](https://user-images.githubusercontent.com/5810477/69209111-464da800-0b13-11ea-8898-25ba3a48c6b8.png)

**Comment by AmandaRiu** [comment]
@kyleaparker While working on the changes needed for this part of the project I discovered that the designs have the colors flipped for this "Appearance" dialog. In the designs the radio button is using the "primaryColor" and the buttons are using the "secondaryColor", but per the material design guidelines it's supposed to be the other way around:

Dialog Theme: 
![Screen Shot 2019-12-21 at 8 34 47 PM](https://user-images.githubusercontent.com/5810477/71316724-21aa6000-2432-11ea-95ce-03c22cccc584.png)

Checkbox Theme: 
![Screen Shot 2019-12-21 at 8 36 57 PM](https://user-images.githubusercontent.com/5810477/71316726-240cba00-2432-11ea-9b74-c177511f533b.png)

Android picks these colors automatically and applies them to my dialog so I don't have much leeway unless I want to throw out the theme stuff and manually apply them on the view (I'd prefer not to do that). Can we swap the colors?

**Comment by AmandaRiu** [comment]
@kyleaparker This is how it looks when I create the dialog using material theming:

![Screen Shot 2019-12-21 at 8 45 47 PM](https://user-images.githubusercontent.com/5810477/71316756-f116f600-2432-11ea-8c93-6e5794551cf8.png)

**Comment by kyleaparker** [comment]
We might need to switch the primary and secondary colours for Android, all buttons should be using the pink colour. 

Pinging @Garance91540 for feedback on this

**Comment by AmandaRiu** [comment]
> We might need to switch the primary and secondary colours for Android, all buttons should be using the pink colour.

If we do that though the app toolbar will be pink since that uses the primary color.

**Comment by AmandaRiu** [comment]
@Garance91540 Here is a preview of the changes I made. Focus on the toolbar and the app setting dialog. The rest is still a WIP so new themes haven't been applied app-wide. 

![ezgif com-video-to-gif](https://user-images.githubusercontent.com/5810477/71381408-ad3a0300-2590-11ea-98ca-d72b63b928e3.gif)

**Comment by Garance91540** [comment]
Hi @AmandaRiu !

Here are my notes:
- Let's keep our buttons pink as Kylea recommended (or else it would be really inconsistent with iOS and core) 

- Ideally we'd keep the toolbar purple out of consistency but it's extra work the pink toolbar doesn't bother me either! 

<img width="520" alt="Screen Shot 2019-12-24 at 1 28 33 PM" src="https://user-images.githubusercontent.com/28450084/71413196-66601200-2651-11ea-9c24-6da494244f8b.png">

- Regarding the Settings screen, we have different sections separated by titles ("Selected store", "about the app"). Out of consistency I think it should match the reviews designs which components (list components on grey cards, titles directly on black background). So I updated the designs slightly:

<img width="267" alt="Screen Shot 2019-12-24 at 1 30 55 PM" src="https://user-images.githubusercontent.com/28450084/71413334-0322af80-2652-11ea-8019-ea6b21de8dee.png">

- Lastly, I think we should add a CTA "apply" or "save" on the appearance modal, since the only current button is "CANCEL", so it feels like the only option I have is to cancel my choice, but no way for me to save my changes. 

Let me know your thoughts and happy holidays!

**Comment by kyleaparker** [comment]
>Lastly, I think we should add a CTA "apply" or "save" on the appearance modal, since the only current button is "CANCEL", so it feels like the only option I have is to cancel my choice, but no way for me to save my changes.

@Garance91540 just for context, the Google apps I tested don't include a save or an apply option for this setting (WPiOS is doing the same thing too), they automatically change on tap

<img width="458" alt="Screenshot_20191224-115435 png 2019-12-24 11-55-33" src="https://user-images.githubusercontent.com/712873/71420648-51c94d00-2644-11ea-82d4-a7fe572c0749.png">

**Comment by AmandaRiu** [comment]
@Garance91540

> Regarding the Settings screen, we have different sections separated by titles (“Selected store”, “about the app”). Out of consistency I think it should match the reviews tab design which has the same components (list components on grey cards, titles directly on black background). So I updated the designs slightly

I love the new settings design! The only thing I would change is the color of the section headings since that would lead me to believe as a user that they were clickable, and they don’t match the rest of the app since all the label-related font is just various shades of `colorOnSurface` values which are all black or white depending on the applied theme.

> Lastly, I think we should add a CTA “apply” or “save” on the appearance modal, since the only current button is “CANCEL”, so it feels like the only option I have is to cancel my choice, but no way for me to save my changes.

I agree with @kyleaparker here that this is a fairly standard practice in Android since switching themes should not require any type of confirmation. The user can just switch it back if they don’t like it.

**Comment by AmandaRiu** [comment]
@Garance91540 oh and since those settings options are clickable, should they be pink?

**Comment by Garance91540** [comment]
> The only thing I would change is the color of the section headings since that would lead me to believe as a user that they were clickable, and they don’t match the rest of the app since all the label-related font is just various shades of colorOnSurface values which are all black or white depending on the applied theme.

👍

> I agree with @kyleaparker here that this is a fairly standard practice in Android since switching themes should not require any type of confirmation. The user can just switch it back if they don’t like it.

I was missing that the selection automatically saved itself.  Looking at Material design guidelines, it seems like single dialog without action elements should not have text buttons at all: The choice itself is actionable when tapped and users can tap anywhere outside the dialog to close it. Based on this, I'd suggest to remove the cancel CTA altogether if it's not too much work!
https://material.io/components/dialogs/#simple-dialog
(Kylea shared a screenshot from a Google app that wasn't following this pattern so it's ok if we leave it alone!)

>since those settings options are clickable, should they be pink?
@AmandaRiu I'm not quite sure which components you are referring to? the radio buttons?

**Comment by AmandaRiu** [comment]
Implemented in PR #1755 . Closing ticket.

**Comment by AmandaRiu** [comment]
@Garance91540 

> The choice itself is actionable when tapped and users can tap anywhere outside the dialog to close it. Based on this, I'd suggest to remove the cancel CTA altogether if it's not too much work!

Absolutely this is totally doable! I'll add it to my list to update in a different ticket. 

> since those settings options are clickable, should they be pink?
@AmandaRiu I'm not quite sure which components you are referring to? the radio buttons?

I was referring to the clickable options in the main settings view:
![Screen Shot 2020-01-02 at 7 47 27 PM](https://user-images.githubusercontent.com/5810477/71704961-586d6800-2d9a-11ea-8968-a2110a356ee0.png)

Since all of the options are clickable, I was curious if all the text should be pink, but I took a look at the material guidelines for settings and I don't think that needs to be the case. I was just curious about that since on Android we don't get the cool little ">" indicator that tells us you can click to drill into an option. 

While reviewing the [material docs for settings](https://material.io/design/platform-guidance/android-settings.html#label-secondary-text) I did notice the current designs are not following the "All labels should align with the left edge of the screen title" which would be really nice.
