### ISSUE TITLE
Implement Material Design typography guidelines

### ISSUE THREAD

**Issue by AmandaRiu** [woocommerce/woocommerce-android#159]
Read and implement the material typography designs and font. https://material.io/guidelines/style/typography.html#

Todo:
- [x] add roboto to main app
- [x] update login library to use roboto

**Comment by anitaa1990** [comment]
@AmandaRiu, again sorry to bug you but since you worked on the dark mode project, would you happen to know if this is implemented in the login lib as well and Can we close this issue or is this stiill a pending item?

**Comment by AmandaRiu** [comment]
@anitaa1990 yup, this can be closed :)
