### ISSUE TITLE
Add detail field to line items in order detail view

### ISSUE THREAD

**Issue by aforcier** [woocommerce/woocommerce-android#160]
**User Story**
I would like to be able to see the variation details for each line item in an order.

![product-details.png](https://images.zenhubusercontent.com/5a0ae8908a75884b908759ea/f462cfe5-97f5-4553-b5d0-8fc9282d0492)

The first iteration of the order details view won't include a details field, instead including the variations info in the name of the product:

> Candle - Green, Large

The API's `name` field comes like that. In order to break out the variation details ("Blue, Medium") into a separate UI element, we'll need to parse the `name` field and extract them. This is made a bit trickier since the product name itself as well as a variation name may contain a dash. The API for orders does not return the 'pure' product name, though it does return meta data with a list of the variants (for each product in an order), which we should be able to rely on to filter out the title:

```js
"meta_data": [
  {
     "id": 58,
     "key": "color",
     "value": "Green"
  },
  {
    "id": 59,
    "key": "size",
    "value": "Large"
  }
],
```

**Comment by AmandaRiu** [comment]
This was added in #984. Closing
