### ISSUE TITLE
Add/Edit Product Release 1: Update product title

### ISSUE THREAD

**Issue by anitaa1990** [woocommerce/woocommerce-android#1615]
Add support to update a product title.

<img width="238" alt="Screenshot 2019-11-29 at 1 18 37 PM" src="https://user-images.githubusercontent.com/22608780/69852645-d07fd400-12aa-11ea-8b4e-ce83e56d011a.png"> . <img width="235" alt="Screenshot 2019-11-29 at 1 18 49 PM" src="https://user-images.githubusercontent.com/22608780/69852650-d4abf180-12aa-11ea-9152-fdd34ee218b2.png">

**Comment by AmandaRiu** [comment]
Moving to milestone 3.4. If this needs to go into 3.3, please submit a hotfix targeting the `release/3.3` branch.
