### ISSUE TITLE
My Store: Scrolling over charts

### ISSUE THREAD

**Issue by AmandaRiu** [woocommerce/woocommerce-android#1625]
**Describe the bug**
Scrolling in the **My Store**  tab is frustrating now that scrubbing is enabled on the charts. Unless the user knows where on the view to attempt a vertical scroll, the page will not scroll and instead the gesture will be consumed for scrubbing. This experience is not ideal especially largest section of the `My Store` page _is_ the chart, and the chart is typically located in the center of the view when the app is first loaded which is usually where the user would swipe to scroll.

**To Reproduce**
1. Go to 'My Store'
2. Attempt to scroll to the bottom of the view from different points on the page including over the charts.
3. Notice how scrolling will not happen unless it happens outside the chart.

**Expected behavior**
The vertical fling gesture is recognized inside the chart as a request to scroll, not scrub. We should be able to accomplish this by tracking the type of gesture being used. If horizontal (with slight vertical tolerance), then scrub, if vertical and fast - then scroll. There are ways of identifying a fling vs. a scrub in Android. [See this page](https://developer.android.com/training/gestures/detector).

**Comment by nbradbury** [comment]
I noticed this just yesterday and it bugged me enough to want to fix it :)
