### ISSUE TITLE
Products: Deleted products aren't removed from product list

### ISSUE THREAD

**Issue by rachelmcr** [woocommerce/woocommerce-android#1631]
**Describe the bug**

When I delete a product from my store, and pull to refresh the product list in the app, the deleted product isn't removed from the list.

**To Reproduce**
1. In the app, enable the Products beta feature.
2. Open the Products tab to load your products list.
3. In WP Admin on the web, go to Products and delete a product from your store.
4. In the app, pull to refresh the products list. The deleted product is still there.
5. Optional: Add a new product to your store and then pull to refresh the products list. The new product is listed but the deleted product is still there.

**Isolating the problem (mark completed items with an [x]):**
- [x] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [x] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [x] I can reproduce this bug consistently using the steps above.

**Mobile Environment**
Please include:
- Device: moto e5 play
- Android version: 8.1
- WooCommerce Android version: 3.2-rc-1

**Comment by nbradbury** [comment]
Note: this is actually [a FluxC issue](https://github.com/wordpress-mobile/WordPress-FluxC-Android/issues/1437), but WCAndroid will need to update the FluxC hash once it's fixed.
