### ISSUE TITLE
Move state-related tracking in OrderListFragment over to the ViewModel

### ISSUE THREAD

**Issue by AmandaRiu** [woocommerce/woocommerce-android#1647]
Move state-related variables from the `OrderListFragment` to `OrderListViewModel` for better testing and MVVM pattern adherence. With the `SavedState` changes, we'll get the state-saving for free.

The product list/search was refactored  [the same way](https://github.com/woocommerce/woocommerce-android/pull/1522/files#diff-e690f46c042e8e0b50edad1ebc18a5b7) .::

The search handler should also be replaced with a coroutine + delay() ( [product search does this](https://github.com/woocommerce/woocommerce-android/blob/develop/WooCommerce/src/main/kotlin/com/woocommerce/android/ui/products/ProductListViewModel.kt#L90) , too).

**Comment by anitaa1990** [comment]
This was fixed as part of the Order list filters project so will close it for now
