### ISSUE TITLE
Navigation: Bottom nav labels can be cut off

### ISSUE THREAD

**Issue by rachelmcr** [woocommerce/woocommerce-android#1648]
**Describe the bug**

If the font size is increased or the device uses a non-English language, it's very easy for a label to be cut off especially on small screen sizes.

On the "My store" tab this can mean the word "store" not appearing at all, or the label being shortened. @nbradbury The behavior doesn't seem to match the behavior in https://github.com/woocommerce/woocommerce-android/pull/1408 — I still see labels appearing on all the tab icons when one is cut off.

**To Reproduce**
1. Go to the device Settings app > Accessibility and increase the font size to the largest available size.
2. Open the app.
3. Tap on the "My store" tab. Note that the word "store" disappears and no other labels change.
4. Tap on the "Reviews" tab and note that it becomes "Re-" and no other labels change.

You can also go to the Settings app > System > Languages & input and change the device language to observe similar behavior with long non-English labels at a regular font size.

**Screenshots**

<img src="https://user-images.githubusercontent.com/8658164/70242655-19cb9a00-1769-11ea-88b6-42e9b61f1563.png" width="50%">
<img src="https://user-images.githubusercontent.com/8658164/70242659-1a643080-1769-11ea-88cf-e71aac36ad98.png" width="50%">

**Isolating the problem (mark completed items with an [x]):**
- [x] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [x] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [x] I can reproduce this bug consistently using the steps above.

**Mobile Environment**
Please include:
- Device: moto e5 play
- Android version: 8.1.0
- WooCommerce Android version: 3.2-rc-2

**Comment by nbradbury** [comment]
Note to self: after looking into this, I believe the problem is due to the active tab having a font size that's 2sp larger than inactive. We're doing our measurements using the inactive size, so text on an active tab may still wrap.
