### ISSUE TITLE
MockedProductDetailViewModel is broken

### ISSUE THREAD

**Issue by nbradbury** [woocommerce/woocommerce-android#1679]
`MockedProductDetailViewModel` overrides product detail's `viewStateData`, but that's marked as `final` in product detail. If I remove the `final` declaration, I get this warning: "Accessing non-final property viewStateData in constructor."

cc: @0nko I figured I should assign this to you since I'm sure you have a better understanding of how to resolve this.

<img width="784" alt="Screen Shot 2019-12-11 at 9 58 23 AM" src="https://user-images.githubusercontent.com/3903757/70632589-1d45a200-1bfd-11ea-8a08-26b94292277c.png">

**Comment by anitaa1990** [comment]
Closed via #2205
