### ISSUE TITLE
v4 Revenue Stats: Update naming for methods to reflect hotfix changes

### ISSUE THREAD

**Issue by AmandaRiu** [woocommerce/woocommerce-android#1687]
Update the naming conventions to reflect the changes in this hotfix so the code remains easy to read and follow: https://github.com/wordpress-mobile/WordPress-FluxC-Android/pull/1446

**Comment by AmandaRiu** [comment]
Moving to milestone 3.4

**Comment by anitaa1990** [comment]
This will be handled as part of the rework we are doing on our Analytics screen so closing this one for now 👍
