### ISSUE TITLE
Products: Shows single entry in some cases

### ISSUE THREAD

**Issue by astralbodies** [woocommerce/woocommerce-android#1695]
**Describe the bug**
Following a specific set of actions I'm able to get the product list to only show the first product. Force refresh reloads everything as expected.

**To Reproduce**
1. Click on Products. Verify the contents.
2. Click on Reviews.
3. Hit the Back button to pop back to the main screen.
4. Go back into the app. (My Store shows incorrectly, filing a separate issue for that).
5. Tap Reviews.
6. Tap Products.

**Screenshots**
Video: https://d.pr/v/BM7gsZ

**Expected behavior**
Products should show entire list on device.

**Mobile Environment**
Please include:
- Device: Pixel 2 XL
- Android version: 10
- WooCommerce Android version: 3.2-rc3

**Comment by anitaa1990** [comment]
I'm not sure if this is related to the same issue but I faced the same issue when I was trying to fetch a list of products from a site (while there was maybe 1 product stored locally already). 

**Steps to reproduce:**
- Click on any order with a product OR click on any product in the Top Earners tab. The product detail screen is displayed. 
- Click on Products tab now.
- Notice there is one product in the list and there is no loading indicator.
- Wait a while and the product list is loaded with the fetched data. 

<img width="300" src="https://user-images.githubusercontent.com/22608780/70787444-aa7f2700-1db4-11ea-943d-a73099d52ac0.gif">
