### ISSUE TITLE
Shipment Tracking Providers showing up twice

### ISSUE THREAD

**Issue by AmandaRiu** [woocommerce/woocommerce-android#1697]
Per @kyleaparker :

> For stores with the Shipment tracking extension installed, when fulfilling an order and selecting “Add Tracking” > “Carrier”, all shipping providers are displayed twice.
 
![screenshot_20191122-144011](https://user-images.githubusercontent.com/5810477/70764537-1742e480-1d15-11ea-892b-7d8b2001a40b.png)

**Comment by nbradbury** [comment]
@kyleaparker I've been trying to reproduce this but can't with two different stores. Does this always happen to you?

**Comment by kyleaparker** [comment]
>@kyleaparker I've been trying to reproduce this but can't with two different stores. Does this always happen to you?

It looks like it resolved itself in the latest update 🤷‍♀
