### ISSUE TITLE
Last selected tab isn't remembered

### ISSUE THREAD

**Issue by nbradbury** [woocommerce/woocommerce-android#1709]
If you're viewing a tab other than "My Store" and then back out of the app, the app doesn't remember the tab you were last viewing. Instead, it opens to "My Store" again.

**Comment by nbradbury** [comment]
I spent some time looking into how other apps handle the back button on the main screen, and I'm seeing three different approaches.

1. Hitting back on the main screen closes the app, regardless of the active nav position. The nav position is restored when returning to the app.

> * Google Drive
> * Google Clock
> * Google Files
> * WordPress

2. Hitting back on the main screen closes the app, regardless of the active nav position. The nav position is **not** restored when returning to the app.

> * Google Photos
> * Google Fit
> * Google Home
> * WooCommerce

3. Hitting back on the first nav position closes the app, hitting back on any other tab moves to the first tab. Hitting back again closes the app.

> * Google News
> * YouTube
> * Facebook
> * Twitter

I think any of these options is fine.

@kyleaparker Any thoughts on this? On Slack it was decided that we'd restore the previous position when returning to the app after the back button is tapped, but we'd default to the Dashboard when a new app session is launched. I think that's also fine, but I haven't seen any other apps behave this way.

**Comment by kyleaparker** [comment]
Pinging @Garance91540 to weigh in on this

**Comment by Garance91540** [comment]
Hi @nbradbury, thanks for this exhaustive review of back buttons behaviors on other apps!  

I think most users use the back button to access their previous screen, so I think solution 3 makes most sense here. I personally get pretty frustrated when I go to tab 1, then tab 2, then click back expecting to land on tab 1 and instead have to leave the app. 

In terms of workflow, I can see why users would want to be able to access the tab they were looking at quickly (example processing orders), and not have to go find it via my Store when you open the app again, but you can do this by minimizing the app with the home button/pull and drop interaction. 

What do you think?
