### ISSUE TITLE
Orders duplicate in order list

### ISSUE THREAD

**Issue by Dikiniello** [woocommerce/woocommerce-android#1715]
Ho, i've a problema.
When i receive a notification i do this
`(activity as? TopLevelFragmentRouter)?.showOrderList("processing)`
Log says fetch_orders and 3 times fetched_order

The app, on new order, randomly duplicates orders in the list.. Someone can help me?
Thanks you

**Comment by AmandaRiu** [comment]
Hello! Since we're still a very small team working on this product, we don't offer developer assistance at this point as we don't have the manpower.
