### ISSUE TITLE
Toolbar title text size is reduced after rotating the product images 

### ISSUE THREAD

**Issue by anitaa1990** [woocommerce/woocommerce-android#1731]
Weird bug when testing products. The toolbar title is reduced when clicking on a product image and rotating the screen. 

#### To test
- Click on a product image from the product detail page.
- Rotate the screen.
- Click back button from the full screen product image screen.
- Notice the toolbar title has shrunk 😕

Note that I had `Do not keep activities` enabled while testing .

<img width="300" src="https://user-images.githubusercontent.com/22608780/71055803-fa773880-217c-11ea-9653-10b50ef8e203.gif">

**Comment by nbradbury** [comment]
Looks like this is due in part to using `android:configChanges="orientation|screenSize"` for our main activity. Removing that corrects the problem, but I'm not sure we want to do that.

**Comment by nbradbury** [comment]
Closed via #1747
