### ISSUE TITLE
Use built-in bottom navigation badging

### ISSUE THREAD

**Issue by nbradbury** [woocommerce/woocommerce-android#1734]
When we first implemented the bottom navigation view we used our own badging because it wasn't supported by the component. [Newer versions](https://developer.android.com/reference/com/google/android/material/bottomnavigation/BottomNavigationView#getorcreatebadge) of the component support badging, so we should use that and drop our custom badging.

**Comment by nbradbury** [comment]
Putting this on hold for now since badging is currently only supported in the `alpha02` version of the component.

**Comment by nbradbury** [comment]
We updated to a version of the component that supports badging, so we can use the built-in badging now. Note that there's a newer, stable release than the one we currently use (we're using `2.2.0-rc04` but `2.2.0` is available).

**Comment by nbradbury** [comment]
Note: in the dark mode we updated the component, and we should implement this as part of that feature since the updated component requires using the material theme.

**Comment by anitaa1990** [comment]
Closed via #1942
