### ISSUE TITLE
Add Order Detail tests: Page, Order Info and Customer Note

### ISSUE THREAD

**Issue by AmandaRiu** [woocommerce/woocommerce-android#174]
Create tests for #144, #134, #170 

## Order Detail Page
* [ ] Click on an order in the Orders list. Expected: Main view switches to Order Detail view.
* [ ] The title is set to `Order #...` in the Order Detail View
* [ ] The `up` button is displayed
* [ ] RTL support

## Order Info Card
* [ ] Populate card
* [ ] Parsing `dateCreated` into one of the following friendly time-based labels to generate the `Created <friendly date category> at <time>` message:
  * Today
  * Yesterday
  * Older than 2 days
  * Older than a week
  * Older than a month
* [ ] Order status label
  * Parsing value to label and color
  * Handling status values not included in main set

## Customer Provided Note Card
* [ ] customer note populated successfully
* [ ] `customerNote` is empty - Hide Customer Note card
* [ ] `customerNote` is NOT empty - show the customer note card

**Comment by anitaa1990** [comment]
Fixed in this [PR](https://github.com/woocommerce/woocommerce-android/pull/1041) so closing
