### ISSUE TITLE
Leak in old stats view

### ISSUE THREAD

**Issue by nbradbury** [woocommerce/woocommerce-android#1757]
Similar to #1749, we have a leak in the "old" stats view which _may_ be caused by an unremoved listener.

**Update:** Removing the listener, as we did in #1753 for the new stats view, doesn't fix the leak.

![Screenshot_1577196951](https://user-images.githubusercontent.com/3903757/71416400-3ce1bf00-262e-11ea-8393-8159312bc645.png)

**Comment by anitaa1990** [comment]
Fixed in #2454
