### ISSUE TITLE
Woo: app audit fixes

### ISSUE THREAD

**Issue by anitaa1990** [woocommerce/woocommerce-android#1761]
- In the Material Design guidelines, all buttons default states are flat, and dragged states are raised. All of our buttons follow this pattern except the contained buttons, which we’d like to make all flat (so we’ll need to remove all drop shadows).

<img width="720" alt="screen-shot-2019-11-26-at-10 35 40-am" src="https://user-images.githubusercontent.com/22608780/71478156-22693a80-2814-11ea-92ad-ed2beade6ad4.png">

- We currently are using two different types of icons + text buttons on order details and add product screen. We should use the one in our Material components library everywhere (see “Suggested” above)

<img width="794" alt="screen-shot-2019-11-26-at-10 48 07-am-1" src="https://user-images.githubusercontent.com/22608780/71478171-37de6480-2814-11ea-931c-5e7a67aaa24b.png">

- On the product details screen, the bottom borders height of the first and second cards should be similar to the other dividers’ height.

<img width="385" src="https://user-images.githubusercontent.com/22608780/71478180-47f64400-2814-11ea-8a1f-d5d6ae53025e.png">

- We noticed that we are using “provider” and “carrier” interchangeably. Out of consistency, let’s replace all instances of “provider” by “carrier”.

**Comment by anitaa1990** [comment]
@garance, for this issue:

```
On the product details screen, the bottom borders height of the first and second cards should be similar to the other dividers’ height.
``` 
Debugging this further on how we are implementing this in the app, I found that we are setting the divider height to 16dp for all the cards in the product detail page. And the bqackground color set to the divider is `#f7f7f7`. Ii'm not sure (and I could be completely wrong here) if there is anything to fix here?

**Comment by Garance91540** [comment]
Hi @anitaa1990 thanks for working on this! How can I test these new changes?

Regarding the product screen card borders, as we are implementing new designs for this page this should fix itself!
