### ISSUE TITLE
Add/Edit Product Release 1: Update product shipping settings

### ISSUE THREAD

**Issue by anitaa1990** [woocommerce/woocommerce-android#1775]
Add support to update a product shipping settings.

<img width="214" src="https://user-images.githubusercontent.com/22608780/71567851-1ddca480-2ae8-11ea-91b6-ae7351c8ac12.png"> . <img width="215" src="https://user-images.githubusercontent.com/22608780/71567850-1ddca480-2ae8-11ea-8525-0dda1690ac13.png"> . <img width="307" src="https://user-images.githubusercontent.com/22608780/71567849-1ddca480-2ae8-11ea-9f69-11e97e71612b.png">

**Comment by nbradbury** [comment]
Closed via #1846
