### ISSUE TITLE
Add Orders List Instrumentation Tests

### ISSUE THREAD

**Issue by AmandaRiu** [woocommerce/woocommerce-android#178]
Create tests for #21 

## Order List
* [ ] Populate orders listview with the results of fetch order
* [ ] Pull-down to refresh functionality
* [ ] Parsing `dateCreated` into one of the following friendly time-based labels:
  * Today
  * Yesterday
  * Older than 2 days
  * Older than a week
  * Older than a month
* [ ] Placing order items into the appropriate list group based friendly time label
* [ ] RTL support

## Order List Item
* [ ] Order number
* [ ] Customer name
  * Empty first or last name handling
  * Extra long names and wrap
* [ ] Order total
  * Formatting w/ different currencies
  * Formatting error handling
  * Invalid data error handling
* [ ] Order status label
  * Parsing value to label and color
  * Handling status values not included in main set
* [ ] RTL support

**Comment by AmandaRiu** [comment]
Assigning to @anitaa1990 since she has PRs open to address this ticket.

**Comment by anitaa1990** [comment]
Fixed in this [PR](https://github.com/woocommerce/woocommerce-android/pull/1041) so closing
