### ISSUE TITLE
Add Order Detail Tests: Customer Info Card

### ISSUE THREAD

**Issue by AmandaRiu** [woocommerce/woocommerce-android#179]
Tests for #137 

## Populating the Form
* [ ] Populating customer name
* [ ] Populating shipping details
* [ ] Populating billing details
* [ ] if `hasSeparateShippingDetails()` use shipping info, if not, use billing info.
* [ ] Address formatting for different locales
* [ ] Billing phone formatting
* [ ] Billing phone formatting for different locales
* [ ] Empty billing phone number

## Expand/Minimize View
* [ ] onLoad - view is condensed and `VIEW MORE` button is visible
* [ ] click `VIEW MORE`:
  * Expand to full view
  * Label change to `VIEW LESS`
* [ ] click `VIEW LESS`:
  * Condense view
  * Label changes to `VIEW MORE`

## Action Buttons
* [ ] email customer
  * test w/ no email
  * test w/ failure
* [ ] call customer
  * valid phone number
  * invalid phone number
  * missing phone number
  * error handling
* [ ] text customer
  * valid phone number
  * invalid phone number
  * missing phone number
  * error handling

**Comment by anitaa1990** [comment]
Fixed in this [PR](https://github.com/woocommerce/woocommerce-android/pull/1041) so closing
