### ISSUE TITLE
Add Order Detail Tests: Payments Card

### ISSUE THREAD

**Issue by AmandaRiu** [woocommerce/woocommerce-android#180]
Tests for #136 

## Populating the form
* [ ] currency formatting for currency-related fields
* [ ] payment message

## Discounts
* [ ] multiple discounts
* [ ] no discounts (should hide discount line)
* [ ] single discount

## Refunds
* [ ] no refunds - hide refunds section
  * update card title to `Payment`
* [ ] has refund:
  * show and populate refund section
  * update card title to `Payment - Refunded`

**Comment by AmandaRiu** [comment]
Assigning to @anitaa1990 since she has PRs open to address this ticket.

**Comment by anitaa1990** [comment]
Fixed in this [PR](https://github.com/woocommerce/woocommerce-android/pull/1041) so closing
