### ISSUE TITLE
Add Order Detail Tests: Products Card

### ISSUE THREAD

**Issue by AmandaRiu** [woocommerce/woocommerce-android#181]
Tests for #135 

## Populate Form
* [ ] test with 1 product and several products
* [ ] SKU empty - hide sku line item
* [ ] SKU not empty - show and populate sku
* [ ] Currency formatting
* [ ] Product total message creation

**Comment by anitaa1990** [comment]
Fixed in this [PR](https://github.com/woocommerce/woocommerce-android/pull/1041) so closing
