### ISSUE TITLE
1 px vertical space along right edge of the Reviews List

### ISSUE THREAD

**Issue by AmandaRiu** [woocommerce/woocommerce-android#1814]
**Describe the bug**
It's difficult to see, but there is a 1px vertical space along the right edge of the Reviews List view. I eventually figured out it was being added by the `UnreadItemDecoration`, but haven't figured out why it's happening. It's easier to see in dark mode which is why it was only now discovered.

**Screenshots**

![Screen Shot 2020-01-10 at 2 29 13 PM](https://user-images.githubusercontent.com/5810477/72187758-c545bb00-33b5-11ea-83e2-4f295399183c.png)

![Screenshot_1578691699](https://user-images.githubusercontent.com/5810477/72187780-d393d700-33b5-11ea-8770-f4d66a2f02ce.png)

**Comment by hafizrahman** [comment]
Looking at this while familiarizing myself with the codebase :)

**Comment by hafizrahman** [comment]
Running out of time today, but so far I discovered that I can replicate the bug if I replace the custom `UnreadItemDecoration`, with a basic `DividerItemDecoration` with a vertical orientation, like so:

```
            val dummyDecor = DividerItemDecoration(activity as Context, 0);
            addItemDecoration(dummyDecor)
```

Will continue digging further.

**Comment by hafizrahman** [comment]
Done in #3541
