### ISSUE TITLE
Order Status: Remove `Refunded` as an editable option

### ISSUE THREAD

**Issue by mindgraffiti** [woocommerce/woocommerce-android#1837]
**Is your feature request related to a problem? Please describe.**
This is an edge case that could cause deeper issues. If a user edits the status of an order in the mobile app, and selects `Refunded`, there is no flow to force the user to add details. It is sent to the API, and the API treats it as a manual refund by amount. Since the full order was refunded by amount, the API to get order details doesn't report any refunded products. This can cause the UI to render an order without the order items section and without the refunded items section.

**Describe the solution you'd like**
Remove `Refunded` as an option for editing order statuses. 

**Describe alternatives you've considered**
We can "fake it" and pretend the order items still exist, and then convert them to refunded items. We would have to artificially create the refunded items. I'm not confident that doing this would be a good idea.

**Additional context**
Ref. p1579633740013200-slack-C6H8C3G23

**Comment by pmusolino** [comment]
In our current release 3.8, I can't see anymore the option. I'm closing this issue.

![Simulator Screen Shot - iPhone 11 Pro - 2020-03-23 at 12 30 33](https://user-images.githubusercontent.com/495617/77312624-9ecfc480-6d02-11ea-9cf9-d23e826dc27a.png)

**Comment by 0nko** [comment]
This is still an issue on Android.
