### ISSUE TITLE
Bug: Product review notification is fired too often

### ISSUE THREAD

**Issue by AmandaRiu** [woocommerce/woocommerce-android#1839]
The `notification_open` even should only be fired for a product review when opened from a **Notification**. 

### TODO
- [x] Update logic to only fire `notification_open` when a product review is opened from a notification
- [ ] Notate the event in Tracks too so we know why it changed on a certain release.

### Background

We send the `notification_open` event when:
- An order is opened from a new order notification
- A review is opened from a product review notification
- AND anytime a review is opened into the detail view <— this is an issue

The `notification_open` track event has an `already_read` property that gets populated because originally this event was to track every time the user opened a `notification` either from the system tray, or from what used to be the **Notifications tab** in the app. The `already_read` property tracked if the user was opening the notification multiple times on the device (which could only happen from the Notifications tab). This functionality remained when we switched the Notifications tab to being the Reviews tab.

**Comment by nbradbury** [comment]
Fixed via #1847
