### ISSUE TITLE
Empty search query param causing empty results when fetching orders

### ISSUE THREAD

**Issue by AmandaRiu** [woocommerce/woocommerce-android#1841]
While troubleshooting a support issue where orders were not loading for a user, I discovered the reason was due to the empty `search=` query parameter passed while fetching order summaries from the API, for example:

`https://public-api.wordpress.com/rest/v1.1/jetpack-blogs/<site_id>/rest-api/?path=/wc/v3/orders/&_method=get&per_page=60&offset=0&status=any&_fields=id,date_created_gmt,date_modified_gmt&search=`

This has never been a problem for other stores, but is an issue for this store for some reason. My only guess at this point is that it probably has something to do with a plugin. 

The fix will be to exclude the `search` query param if the arguments will be empty.

See 2627677-zen for additional information.

**Comment by nbradbury** [comment]
Fixed via #1484
