### ISSUE TITLE
Dark Mode: Apply new styles to Zendesk Activities

### ISSUE THREAD

**Issue by AmandaRiu** [woocommerce/woocommerce-android#1854]
Just as WPAndroid discovered in [this ticket](https://github.com/wordpress-mobile/WordPress-Android/issues/11111), it seems Zendesk does not respect Dark mode styles. We need to explore other options like possibly overriding their styles - which is a pain and would require a lot of overhead to make sure it doesn't break between Zendesk releases.

**EDIT**
it looks like there is a new version of Zendesk out (4.0.0) so maybe it will be fixed there? https://developer.zendesk.com/embeddables/docs/android-support-sdk/release_notes

Opened a [separate ticket to upgrade the app](https://github.com/woocommerce/woocommerce-android/issues/1877) to using version 4.0.0 of Zendesk. Once that's complete then dark mode can be implemented.

**Comment by nbradbury** [comment]
Note: We upgraded to Zendesk in #1878 so we can look into this now.
