### ISSUE TITLE
Products empty state: empty view is displayed in products after switching store

### ISSUE THREAD

**Issue by anitaa1990** [woocommerce/woocommerce-android#1871]
While testing, I noticed that when we switch store and click on the `Products` tab, the empty view is displayed the first time even though there are products available in the store. When trying pull to refresh again, the products are loaded correctly.

<img width="300" src="https://user-images.githubusercontent.com/22608780/73424918-21b54e00-4356-11ea-8846-5d69627fee1b.gif">

cc @nbradbury

**Comment by nbradbury** [comment]
@anitaa1990 I've tried everything I can think of to reproduce this but I'm not able to. When I change stores and switch to Products, it shows a skeleton and then shows all the products. I've tried clearing the database at startup just in case that would help, but even after doing that I can't repro it.

![ezgif-3-41cf5962eae5](https://user-images.githubusercontent.com/3903757/73680017-868be380-4689-11ea-9468-bcaf5e7aa305.gif)

**Comment by anitaa1990** [comment]
@nbradbury sorry to waste your time on a non issue 🙇‍♀! I tested this in android Pixel 3, API 29 emulator and opened this issue. Turns out the emulator was really slow and the request was timing out hence the empty screen. I tested in a new emulator Pixel 4 emulator and in an actual Moto device and it is working correctly. Sorry once again for wasting on this!
