### ISSUE TITLE
Dark Mode: Web views

### ISSUE THREAD

**Issue by AmandaRiu** [woocommerce/woocommerce-android#1873]
Apply dark mode on `WebView`s throughout the app. [Here's an interesting article.](https://joebirch.co/2020/01/24/enabling-dark-theme-in-android-webviews/)

**Comment by nbradbury** [comment]
Note: this will require updating the browser library to [v1.2.0](https://developer.android.com/jetpack/androidx/releases/browser#1.2.0).

**Comment by nbradbury** [comment]
The article mentioned in the description is for `WebViews` rather than Chrome Custom Tabs (my mistake). We should instead use [setColorScheme](https://developer.android.com/reference/androidx/browser/customtabs/CustomTabsIntent.Builder.html#setColorScheme(int)).

**Comment by nbradbury** [comment]
Following up here: `setColorScheme` simply changes the theme for the chrome around the web content, not the web content itself. So for now this isn't possible.
