### ISSUE TITLE
Fulfillment: Customer note shows up in two different sections

### ISSUE THREAD

**Issue by astralbodies** [woocommerce/woocommerce-android#1892]
**Describe the bug**
When a customer provides a note when placing an order, that note shows up in two different sections on the fulfillment screen.

**To Reproduce**
1. Place an order with a note.
2. View the order in the app.
3. Tap Begin Fulfillment.
4. See the duplicated note.

**Screenshots**
![image000000-1](https://user-images.githubusercontent.com/373903/73784530-4301aa00-475b-11ea-93fc-491394127e05.jpeg)

**Expected behavior**
Note should only show up in one place.

**Mobile Environment**
Please include:
- Device: Pixel 2 XL
- Android version: 10
- WooCommerce Android version: 3.5-rc-2

**Comment by AmandaRiu** [comment]
This was fixed in PR #1977 and will be released in 4.2 (currently in beta)
