### ISSUE TITLE
Order Details Paid By Customer section hidden if no date_paid returned

### ISSUE THREAD

**Issue by astralbodies** [woocommerce/woocommerce-android#1900]
To match Core behavior, let's update the app to show/hide the "Paid by customer" section in order details based on there being a date paid or not.

Core: https://github.com/woocommerce/woocommerce/pull/25504#discussion_r375455622

Verify payment details show up properly when using the "Cash on delivery" option.

cc: @LevinMedia

iOS issue: https://github.com/woocommerce/woocommerce-ios/issues/1827

**Comment by anitaa1990** [comment]
@astralbodies is this still a valid issue? I see that if the order is a cash on delivery order, then the app displays the `Awaiting payment` text.

<img src="https://user-images.githubusercontent.com/22608780/122195940-6a6e9800-ceb4-11eb-93a6-8b0933acaaed.PNG" width="300"/>

**Comment by astralbodies** [comment]
I'll close it for now; I bet we addressed it and didn't close the issue at the time. 😄
