### ISSUE TITLE
Stats UI: empty view displayed when there are stats available for last 30 days

### ISSUE THREAD

**Issue by anitaa1990** [woocommerce/woocommerce-android#1927]
A user in zen-2705381 reported that they are able to see the Stats charts for 5 seconds before it disappears and is replaced with the empty view.

<img width="300" src="https://user-images.githubusercontent.com/22608780/74214504-ac396e00-4cc3-11ea-9207-69c49e8cc6c5.png">. <img width="300" src="https://user-images.githubusercontent.com/22608780/74214505-acd20480-4cc3-11ea-9827-0e63327573be.png">

When debugging the issue, I notice that we are using a [separate API to determine if a site has orders or not](https://github.com/woocommerce/woocommerce-android/blob/bfe298fc4997f81fa7ceb314d0c94ff2a289a13c/WooCommerce/src/main/kotlin/com/woocommerce/android/ui/dashboard/DashboardPresenter.kt#L125-L124). This API is returning an empty array as a response which is the reason we are displaying an empty view. But the site does have orders over the past 30 days. Need to debug on why the has orders API is returning 0.

**Comment by anitaa1990** [comment]
Update: I was able to reproduce this on my test site by deleting all the orders on my site and refreshing the app. So even though there might be revenue generated previously, since those orders are deleted,  the app displays the empty view.

**Comment by astralbodies** [comment]
@anitaa1990 I suspect that deleting an order isn't properly updating the old store stats views on WordPress.com. I'd defer to how core woo handles it and if the new WCAdmin dashboard removes those from the sales reports, that makes the most sense. I don't think we'll go back and fix anything with wpcom at this point unless people complain. 😄

**Comment by anitaa1990** [comment]
This is not an issue with the current Woo `wc-analytics` API that we're using in the app so closing this issue.
