### ISSUE TITLE
Refunds: Refund option available on unpaid orders

### ISSUE THREAD

**Issue by AmandaRiu** [woocommerce/woocommerce-android#1936]
**Describe the bug**
The `ISSUE REFUND` option is available on orders with the status of `payment-pending` (unpaid order). 

**To Reproduce**
1. Open an unpaid order. Notice the `ISSUE REFUND` button is visible.
2. Click on 'ISSUE REFUND'. Select some products to refund and submit. 
3. The request will complete in error (see gif below).

**Screenshots**
![ezgif com-video-to-gif](https://user-images.githubusercontent.com/5810477/74385816-a91cab80-4db1-11ea-9afa-200df43cf9f4.gif)

**Expected behavior**
The `ISSUE REFUND` option is not available if no money has been paid.

**Comment by 0nko** [comment]
We used to prevent issuing refunds for unpaid orders but core allows it so I removed that condition.

**Comment by shiki** [comment]
Considering the comment above https://github.com/woocommerce/woocommerce-android/issues/1936#issuecomment-585610477, I'll close this for now.
