### ISSUE TITLE
Badge count not updating after a PTR on the orders list

### ISSUE THREAD

**Issue by AmandaRiu** [woocommerce/woocommerce-android#1944]
The currently logic for refreshing the badge count is in `MainPresenter.onOrderChanged` where one of the events that used to refresh the order count was `FETCH-ORDERS`. Now that we use the `ListStore` to manage the list, the `FETCH-ORDERS` event never gets called so the orders badge count does not get updated. 

There's also some logic to artificially update the order badge count when an order status changes, but that's unnecessary since the unfilled count will get updated with the `ORDER_STATUS_CHANGE` event.

**Comment by anitaa1990** [comment]
I am no longer able to reproduce this issue. I am able to see the updated badge count when refreshing the order list using PTR so closing this issue for now. We can always reopen this if we find it is not yet fixed 😅
