### ISSUE TITLE
Dark Mode: Update icon color on Privacy Settings

### ISSUE THREAD

**Issue by Garance91540** [woocommerce/woocommerce-android#1946]
Icon color on both dark and light mode should be updated to “On Surface / Medium Emphasis ”

<img width="441" alt="Screen Shot 2020-02-05 at 11 45 48 AM" src="https://user-images.githubusercontent.com/28450084/74523649-cbcbd300-4f1d-11ea-8a50-44a7ff757f50.png">

**Comment by AmandaRiu** [comment]
Thanks for opening this ticket @Garance91540!

**Comment by AmandaRiu** [comment]
@Garance91540 It looks like this was already fixed somewhere along the way. Both icons in this view are already using On surface/medium emphasis: 

| Light | Dark |
| --- | --- |
![Screenshot_1582581378](https://user-images.githubusercontent.com/5810477/75194800-0996db80-5716-11ea-8484-479e1b575dcd.png)|![Screenshot_1582581406](https://user-images.githubusercontent.com/5810477/75194805-0b609f00-5716-11ea-86ed-5f4a83398b0a.png)

Does this look good to you?

**Comment by Garance91540** [comment]
Yes perfect!
