### ISSUE TITLE
Stats: Default to v4 stats for sites with Woo Core 4.0+

### ISSUE THREAD

**Issue by rachelmcr** [woocommerce/woocommerce-android#1947]
**Is your feature request related to a problem? Please describe.**

When I have the WooCommerce Core 4.0 beta (which includes WooCommerce Admin) installed on my site, the app still defaults to the old stats with a prompt to try the new stats.

**Describe the solution you'd like**

Sites with WooCommerce Core 4.0 and higher should default to the newer (v4) stats.

**Additional context**
Internal discussion: p5T066-1az-p2#comment-4283

**Comment by anitaa1990** [comment]
Another issue was opened to address this in #2539 by @AmandaRiu so closing this one for now
