### ISSUE TITLE
Add Order Detail Tests: Order Notes Card

### ISSUE THREAD

**Issue by AmandaRiu** [woocommerce/woocommerce-android#195]
Tests for #138 

# Populating the Note List Item View

- [ ] Populate proper note date/time stamp 
- [ ] Populate note
- [ ] Appropriate note type is populated (private/public)
- [ ] Appropriate note icon is displayed (private/public)

# Populating the Note List View

- [ ] Progress view is hidden once initView() is called on the card
- [ ] List of notes properly populated and displayed
- [ ] Notes are displayed in reverse-chronological order

**Comment by AmandaRiu** [comment]
Assigning to @anitaa1990 since she has PRs open to address this ticket.

**Comment by anitaa1990** [comment]
Fixed in this [PR](https://github.com/woocommerce/woocommerce-android/pull/1041) so closing
