### ISSUE TITLE
Reviews: Overflow menu can disappear on Reviews tab after viewing review details

### ISSUE THREAD

**Issue by rachelmcr** [woocommerce/woocommerce-android#1950]
**Describe the bug**

The overflow menu (Help/Support) on the Reviews tab can disappear if you rotate the device while viewing review details or after opening review details from a push notification.

**To Reproduce**
1. Open the Reviews tab and notice the overflow menu appears in the top right.
2. Tap on a review to open the review details.
3. Rotate your device between portrait and landscape.
4. Go back to the reviews list and notice the overflow menu is gone.
5. Tap to another tab in the bottom nav and tap back to the Reviews tab, and notice the overflow menu is back.

**Screenshots**

<img src="https://user-images.githubusercontent.com/8658164/74554080-99879900-4f50-11ea-85c9-73005dc8fbd1.png" width="50%">

Screencast: https://cloudup.com/cY87WzWnj57

**Expected behavior**

I expect the overflow menu to always be visible on the Reviews tab.

**Isolating the problem (mark completed items with an [x]):**
- [x] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [x] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [x] I can reproduce this bug consistently using the steps above.

**Mobile Environment**
Please include:
- Device: moto e5 play
- Android version: 8.1.0
- WooCommerce Android version: 3.6-rc-1

**Comment by nbradbury** [comment]
Problems appears to be due to [this change](https://github.com/woocommerce/woocommerce-android/blob/develop/WooCommerce/src/main/kotlin/com/woocommerce/android/ui/main/MainActivity.kt#L180-L187) in `MainActivity`:

```
override fun onCreateOptionsMenu(menu: Menu?): Boolean {
    // don't show the options menu unless we're at the root
    if (isAtNavigationRoot()) {
        menuInflater.inflate(R.menu.menu_action_bar, menu)
        return true
    } else {
        return false
    }
}
```

When this is called after returning from review detail, `isAtNavigationRoot()` returns `false` so no menu is created. Why this is only happening from reviews is still a mystery.

**Comment by nbradbury** [comment]
Found the cause. Both the order list and product list force the menu to be drawn after returning from a child fragment. The review list doesn't do this.
