### ISSUE TITLE
Chart handling of negative values - show zero x-axis

### ISSUE THREAD

**Issue by AmandaRiu** [woocommerce/woocommerce-android#1955]
The current chart doesn't display negative numbers very well because there is no $0 line on the x-axis:

![Screen Shot 2020-02-18 at 7 34 32 PM](https://user-images.githubusercontent.com/5810477/74796415-bc35ec80-5285-11ea-94fa-c672d7009873.png)

Add a $0 line on the X-Axis to make this more readable

**Comment by anitaa1990** [comment]
Thanks so much for creating this issue @AmandaRiu!

@Garance91540 updated the designs to add support for negative revenue:
<img width="1024" alt="screen-shot-2020-02-12-at-11 38 20-am" src="https://user-images.githubusercontent.com/22608780/74800086-6b131080-52f8-11ea-8d74-00632c676465.png">

**Comment by Garance91540** [comment]
Thanks for jumping on this @anitaa1990 and @AmandaRiu . Here is the Figma file for more context: https://www.figma.com/file/JCbo1C7AKprTKGsCFkQo0Sk9/My-store---Stats-Improvements?node-id=104%3A0

I want to point out that on top of showing the zero x axis, we need to show a positive and negative x-axis as well on top/below it. Which means we'll have to add a third data point on the y axis (even if the revenue is positive). So here is a recap of changes needed:
1. add a third data point on the y axis that's at the same level as the x-axis
2. to be able to show this data point without crowding the legend, we need to right-align the legend of the x axis (currently left-align), so there's enough space in between https://d.pr/i/n38G8d (in this example, we are right-aligning the x axis legend to make space between the -$500 and the 2am)

Let me know if you have any questions!
