### ISSUE TITLE
Order Detail: Customer Info Card UI Issues

### ISSUE THREAD

**Issue by AmandaRiu** [woocommerce/woocommerce-android#1960]
The customer info card in the order detail view will load incorrectly with empty views if address information is not provided, but then if you back out to the order list and reopen the order, the card will suddenly load correctly:

<img src="https://user-images.githubusercontent.com/5810477/74869113-9e639880-5314-11ea-8a5d-0f9e5dd38a4d.gif" width="350"/>

# Screenshots:

### First Load

<img src="https://user-images.githubusercontent.com/5810477/74869273-e4206100-5314-11ea-873b-f55c5b027c37.png" width="330"/>

### Subsequent Loads

<img src="https://user-images.githubusercontent.com/5810477/74869293-f0a4b980-5314-11ea-8615-59dc103381c7.png" width="330"/>

**Comment by anitaa1990** [comment]
@0nko working on this issue in #2495 so closing this one

**Comment by 0nko** [comment]
Thanks @anitaa1990. I was looking for "billing" to see if there is an open issue and didn't find anything.
