### ISSUE TITLE
Pre-fetch order notes for significant orders

### ISSUE THREAD

**Issue by aforcier** [woocommerce/woocommerce-android#197]
We currently (#196) fetch notes for orders when opening the order detail view for an order.

We might want to look into a small optimization where we pre-fetch up to some number of notes for important orders (processing primarily, perhaps recent failed ones too), so they're instantly available when the order is opened (and will be available if the order is opened offline).

The WP API has some batching capabilities - perhaps we'd be able to bundle the order fetches up into a single call when the order list is loaded and do it in the background.

iOS counterpart: https://github.com/woocommerce/woocommerce-ios/issues/47

**Comment by anitaa1990** [comment]
I am going to close this issue for now — given our current architecture (local cache, bg fetching, etc), this doesn't appear like something that is required. We will be looking into ways to optimise the order detail screen (currently fetching 10 separate API requests) and as part of that, the order notes refactor will also be taken into account 👍
