### ISSUE TITLE
Tablet dimensions for new style and theme

### ISSUE THREAD

**Issue by AmandaRiu** [woocommerce/woocommerce-android#1970]
Implement tablet dimensions

**Comment by AmandaRiu** [comment]
This one is going to take a bit more thought due the way margins and padding are configured and may require tweaks to most views in the app. Since we don't have an official tablet design as of yet this one can wait till after v1.

**Comment by AmandaRiu** [comment]
Removing myself as assigned as this is lower priority (we don't have tablet designs yet) and can be taken on by anyone at a later date.

**Comment by shiki** [comment]
I'm going to close this for now. We can reopen when we start looking at tablets for Android.
