### ISSUE TITLE
Refunds: Customize the refund tax/shipping notice according to tax and shipping costs

### ISSUE THREAD

**Issue by rachelmcr** [woocommerce/woocommerce-android#2000]
**Is your feature request related to a problem? Please describe.**

On an order with only virtual products (no shipping involved) the refund screen doesn't show a line for Shipping but there is still a notice that mentions shipping refunds:

> You can refund shipping and tax amounts in your store admin

**Describe the solution you'd like**

Ideally that notice wouldn't mention shipping if there's no shipping involved in the order, e.g. orders with only virtual products (since the Shipping amount doesn't appear either).

Beyond orders with only virtual products, it might be nice to check for $0 amounts for both the Shipping and Tax and customize the notice accordingly — only mention shipping if there's a shipping charge, only mention tax if there's a tax charge, and don't show the notice at all if there's neither. That might be a more involved change, though, and potentially not worth the effort.

**Additional context**
<img src="https://user-images.githubusercontent.com/8658164/75246015-d3fdfb00-57c6-11ea-8176-ce9322c98e4e.png" width="50%">

**Comment by anitaa1990** [comment]
This was actually fixed during the refund shipping PR in #3935 so closing this issue 🎉
