### ISSUE TITLE
 Shimmer effect and empty view are superposed on the comments tab.

### ISSUE THREAD

**Issue by maxme** [woocommerce/woocommerce-android#2035]
**Describe the bug**
Shimmer effect and empty view are superposed on the comments tab.

**To Reproduce**
1. Open the app.
2. Switch tabs until it's done loading.
3. Go to the Comments tab.
4. Notice the Shimmer effect and empty view are superposed.

There might be some other way to get this behavior, but this one was the most reliable. IIRC, the first time I got this issue, I was coming back from the "Settings" screen to the main view. The loading state seems correct (the loading indicator is not showing).

**Screenshots**

![Screenshot_20200311_102453_com woocommerce android](https://user-images.githubusercontent.com/40213/76401827-cf1e7700-6382-11ea-8376-a0820abc5737.jpg)

Demo video: https://bia.is/s/qHGh/VID_20200311_102533.mp4

**Expected behavior**
Only the empty view should be showing if there is nothing to see and the loading is done

**Isolating the problem (mark completed items with an [x]):**
- [x] I can reproduce this bug consistently using the steps above.

**Mobile Environment**
Please include:
- Device:  Huawei
- Android version: Android 9 
- WooCommerce Android version:  3.6

**Comment by anitaa1990** [comment]
Closed via #2090
