### ISSUE TITLE
Mitigate 5-second timeout issue with Jetpack tunnel requests

### ISSUE THREAD

**Issue by aforcier** [woocommerce/woocommerce-android#204]
The requests to the Jetpack tunnel have a 5 second timeout, which is occasionally tripped for certain endpoints (`/product/`s especially) and/or when multiple requests are made at once. Where possible we should account for this, perhaps by identifying the timeout error in FluxC and retrying (where the request is idempotent) or verifying the server state in case it's not.

TODO:
- [ ] Add retry capability for POST/PUT/PATCH/DELETE requests.

**Comment by astralbodies** [comment]
I'm closing this for now. The proxy is now 30 seconds long which should help us out a great deal. In fact it's been like that since April 2019 and I haven't seen a ton of reports of failed requests.
