### ISSUE TITLE
Store Stats: supporting negative revenue - design fixes

### ISSUE THREAD

**Issue by anitaa1990** [woocommerce/woocommerce-android#2040]
As @Garance91540 mentioned in this [PR](https://github.com/woocommerce/woocommerce-android/pull/1989#issuecomment-598062459), there are a few design changes in the stats charts required, for supporting negative revenue.

<img width="408" alt="Screen Shot 2020-03-05 at 2 21 11 PM" src="https://user-images.githubusercontent.com/28450084/76022367-9c8cfe00-5eec-11ea-91c0-e1f98ffdafac.png">

1. The `zeroline` for the chart should be a dashed line as per the design.
2. The y-axis label count should always be 3. It should include the min revenue value, 0 as the second value and the max revenue value.
3. Similarly, only 2 grid lines should be displayed for the y-axis: one of the min y-axis value and one of the max y-axis value.

I spent some time last week trying to debug if both design fixes were possible and I'm not entirely sure there is a straight forward fix in the MPAndroidChart to support it. Will need to debug if there is a hack that is possible.

**Comment by Garance91540** [comment]
Updating the design request here:
- The zeroline for the chart should be a dashed line as per the design.

**- The y-axis label count should always be 3. It should include the min revenue value, 0 as the second value and the max revenue value.**
> let's make it 4 when there's the zero axis.

<strike> Similarly, only 2 grid lines should be displayed for the y-axis: one of the min y-axis value and one of the max y-axis value.</strike>

**Comment by anitaa1990** [comment]
This was fixed as part of the new design changes in the home screen updates project so will mark this issue as closed
