### ISSUE TITLE
Zendesk: Populate selected site if available

### ISSUE THREAD

**Issue by astralbodies** [woocommerce/woocommerce-android#2044]
The WP apps list the currently selected site if one is selected which is helpful to support personnel. Replicate that functionality in the Woo app and use the same field that WP uses.

iOS: https://github.com/woocommerce/woocommerce-ios/issues/1951

**Comment by anitaa1990** [comment]
This functionality is implemented on android. We populate the "Current Site" field on Zendesk if available. So will close this issue 👍
