### ISSUE TITLE
Edit Product Release M2: add a read only product settings screen 

### ISSUE THREAD

**Issue by anitaa1990** [woocommerce/woocommerce-android#2047]
As per designs, we would need to provide a new option in product detail menu to display product settings.

<img width="188" alt="Screenshot 2020-03-13 at 12 21 53 PM" src="https://user-images.githubusercontent.com/22608780/76596912-4d1a8380-6525-11ea-8825-1b9b55d56c40.png">

**Comment by anitaa1990** [comment]
I'll unassign myself from this since @nbradbury is working on it.

**Comment by nbradbury** [comment]
> I'll unassign myself from this since @nbradbury is working on it.

Sorry, @anitaa1990 - I hadn't noticed you'd assigned yourself to this task.

**Comment by anitaa1990** [comment]
No worries 😄 Thanks for taking this one!

**Comment by nbradbury** [comment]
Feature branch is merged so this can be closed.
