### ISSUE TITLE
Edit Product Release 2: provide option to update product catalog visiblity

### ISSUE THREAD

**Issue by anitaa1990** [woocommerce/woocommerce-android#2049]
As part of the Edit products M2 release, we would need to provide the option to update the product catalog visibility from product settings screen.

<img width="475" alt="Screenshot 2020-03-13 at 12 28 24 PM" src="https://user-images.githubusercontent.com/22608780/76597311-2446be00-6526-11ea-9453-d97cee2871a4.png">

**Comment by nbradbury** [comment]
Closed via #2250
