### ISSUE TITLE
Edit Product Release 2: provide option to update product slug

### ISSUE THREAD

**Issue by anitaa1990** [woocommerce/woocommerce-android#2050]
As part of the Edit products M2 release, we would need to provide the option to update the product slug from product settings screen.

<img width="474" alt="Screenshot 2020-03-13 at 12 30 10 PM" src="https://user-images.githubusercontent.com/22608780/76597411-6a038680-6526-11ea-9878-8424ec851126.png">

**Comment by nbradbury** [comment]
Closed via #2258
