### ISSUE TITLE
Edit Product Release 2: provide option to update product status

### ISSUE THREAD

**Issue by anitaa1990** [woocommerce/woocommerce-android#2051]
As part of the Edit products M2 release, we would need to provide the option to update the product status from product settings screen.

<img width="467" alt="Screenshot 2020-03-13 at 12 32 51 PM" src="https://user-images.githubusercontent.com/22608780/76597566-c36bb580-6526-11ea-822b-9ae28c39aa60.png">

**Comment by nbradbury** [comment]
Closed via #2240
