### ISSUE TITLE
Products: Can't tell which price field is selected

### ISSUE THREAD

**Issue by rachelmcr** [woocommerce/woocommerce-android#2054]
**Describe the bug**

When editing a product's details, there's no way to tell which price field is selected. No cursor or other highlighting appears to show what has focus (or whether a field has focus).

**To Reproduce**

1. Go to the Products tab.
2. Select a product.
3. Select "Price."
4. Tap in the `Regular price` or `Sale price` fields and edit the amount there.

**Screenshots**

<img src="https://user-images.githubusercontent.com/8658164/76640028-210ffa00-6547-11ea-8684-69c5c4da6498.png" width="50%">

**Mobile Environment**
First device:
- Device: moto e5 play
- Android version: 8.1.0
- WooCommerce Android version: 3.8-rc-1

Second device:
- Device: HTC Nexus 9
- Android version: 7.1.1
- WooCommerce Android version: 3.8-rc-1

**Comment by nbradbury** [comment]
Looks like this is caused by setting `isCursorVisible = false` [here](https://github.com/woocommerce/woocommerce-android/blob/6ebdf891da9a63d0fde8f2b48881de4b929d26c7/WooCommerce/src/main/kotlin/com/woocommerce/android/widgets/CurrencyEditText.kt#L34).
