### ISSUE TITLE
Products: Shipping settings show the selected shipping class slug instead of its name

### ISSUE THREAD

**Issue by rachelmcr** [woocommerce/woocommerce-android#2056]
**Describe the bug**

When I select a shipping class for my product, I expect the name of the shipping name (e.g. `Free shipping`) to be displayed. Instead, the shipping class slug (e.g. `free-shipping`) is displayed.

**To Reproduce**

1. Go to the Products tab.
2. Select a physical product.
3. Select Shipping.
4. Select Shipping Class and then select a shipping class.
5. On the Shipping settings screen, notice that the shipping class slug is showing instead of the name.

**Screenshots**

<img src="https://user-images.githubusercontent.com/8658164/76643813-b910e200-654d-11ea-9428-d90521233199.png" width="50%">
<img src="https://user-images.githubusercontent.com/8658164/76643818-ba420f00-654d-11ea-829f-b38c4b871abf.png" width="50%">

**Mobile Environment**
Please include:
- Device: moto e5 play
- Android version: 8.1.0
- WooCommerce Android version: 3.8-rc-1

**Comment by anitaa1990** [comment]
Closed via #2062
