### ISSUE TITLE
Products: In inventory settings, empty SKU field is filled with Quantity value when device is rotated

### ISSUE THREAD

**Issue by rachelmcr** [woocommerce/woocommerce-android#2057]
**Describe the bug**

In the product inventory settings: If the SKU field is empty and I rotate my device, the SKU field is filled with the value from the Manage stock > Quantity field.

**To Reproduce**

1. Go to the Products tab.
2. Select a product.
3. Select Inventory.
4. Delete all text from the SKU field.
5. Rotate your device. Notice it is now filled with a number that matches the number in the Manage stock > Quantity field.
6. Delete all text from the SKU field again.
7. Change the value in Manage stock > Quantity.
8. Rotate your device. Notice it is again filled with a number that matches the updated number in the Manage stock > Quantity field.

**Screenshots**

<img src="https://user-images.githubusercontent.com/8658164/76644673-633d3980-654f-11ea-83ab-8de7ef071943.png" width="50%">

**Mobile Environment**
Please include:
- Device: moto e5 play
- Android version: 8.1.0
- WooCommerce Android version: 3.8-rc-1

**Comment by anitaa1990** [comment]
Closed via #2064
