### ISSUE TITLE
Products: Inventory settings for stock status don't display as expected

### ISSUE THREAD

**Issue by rachelmcr** [woocommerce/woocommerce-android#2058]
**Describe the bug**

When I change a product's inventory settings, the stock status looks right on the inventory details screen but not in the Inventory section on the product details screen. Things that can be incorrect there:

* When `Manage stock` is disabled, the `Stock status` setting isn't shown in product details.
* When `Manage stock` is enabled, the `Stock status` setting isn't shown on the inventory settings screen but it does appear on the product details screen. That can lead to conflicting information (e.g. a positive stock quantity but also an "Out of stock" status).

I think the correct behavior is:

* If `Manage stock` is disabled, the `Stock status` setting should be shown in product details.
* When `Manage stock` is enabled, the `Stock status` setting shouldn't be shown in product details.

**To Reproduce**

1. Go to the Products tab.
2. Select a product.
3. Select Inventory.
4. With `Manage stock` disabled, set the `Stock status` to "Out of stock."
5. Enable `Manage stock` and enter a quantity (e.g. "10").
6. Tap "Done" and check the Inventory section. Notice that it now says "Stock status: Out of stock" but also "Stock quantity: 10."

**Screenshots**

Manage stock disabled | No stock status
--- | ---
![Screenshot_20200313-172930](https://user-images.githubusercontent.com/8658164/76645359-c2e81480-6550-11ea-8b5e-0cdab358b6e4.png) | ![Screenshot_20200313-172933](https://user-images.githubusercontent.com/8658164/76645326-b19f0800-6550-11ea-9174-35a0787de9da.png)

Manage stock enabled | Stock status + quantity
--- | ---
![Screenshot_20200313-172940](https://user-images.githubusercontent.com/8658164/76645330-b368cb80-6550-11ea-856d-9111df7a3c78.png) | ![Screenshot_20200313-172945](https://user-images.githubusercontent.com/8658164/76645351-bd8aca00-6550-11ea-9842-30a424cc9793.png)

**Mobile Environment**
Please include:
- Device: moto e5 play
- Android version: 8.1.0
- WooCommerce Android version: 3.8-rc-1

**Comment by anitaa1990** [comment]
Closed via #2063
