### ISSUE TITLE
Products: Sale can be scheduled with start date after end date

### ISSUE THREAD

**Issue by rachelmcr** [woocommerce/woocommerce-android#2059]
**Describe the bug**

When I schedule a sale for a product, I can select a start date that is past the end date. This is probably ok while I'm editing the sale details (see https://github.com/woocommerce/woocommerce-ios/issues/1952 for a potential problem if we're too strict about that) but I shouldn't be able to save those details.

Possible solutions could be to auto-update the end date or display an error about the end date when I save those settings.

**To Reproduce**

1. Go to the Products tab.
2. Select a product.
3. Select Price.
4. Enable "Schedule sale."
5. In the "From" field, select a date in the future (e.g. 1 April 2020).
6. In the "To" field, select a date prior to the date you selected in the "From" field (e.g. 13 March 2020).
7. Tap Done. Notice that on the product details screen, it shows the impossible sale dates (e.g. "Sale dates: Apr 1 - Mar 13, 2020).
8. Open that product in WP Admin web and notice that the end date is set to match the start date.

**Screenshots**

<img src="https://user-images.githubusercontent.com/8658164/76646125-5a9a3280-6552-11ea-9f08-3735a5107fe2.png" width="50%">
<img src="https://user-images.githubusercontent.com/8658164/76646153-65ed5e00-6552-11ea-9a05-35f23b30e6d2.png" width="50%">

Web:

![Screenshot 2020-03-13 17 38 31](https://user-images.githubusercontent.com/8658164/76646185-756ca700-6552-11ea-9f01-77a009f29054.png)

**Mobile Environment**
Please include:
- Device: moto e5 play
- Android version: 8.1.0
- WooCommerce Android version: 3.8-rc-1

**Comment by anitaa1990** [comment]
Closed via #2067
