### ISSUE TITLE
Stats 4.0: changes required to stop support for the old v3 stats UI

### ISSUE THREAD

**Issue by anitaa1990** [woocommerce/woocommerce-android#2068]
After we retire the old stats (date to be confirmed as to when this will take place), if site version is <4.0 or WC admin manually disabled, we would need to display an empty screen to the user:

<img width="300"  src="https://user-images.githubusercontent.com/22608780/76737494-e4ceda80-678e-11ea-879a-f95c228182c8.png">

**Comment by anitaa1990** [comment]
@ThomazFB, I noticed that when a store has WooCommerce version < 4.0, we currently just display the old stats UI but ideally, we should be displaying the screen mentioned in this issue description. Is this something you are currently working on?

**Comment by ThomazFB** [comment]
Hey @anitaa1990! When I started the code removal of the Stats V3 I forgot to include this error screen. Bu @Garance91540 reminded me about this during the discussion around this PR: https://github.com/woocommerce/woocommerce-android/pull/2973. I'll assign myself to this issue and tag it to the current Stats V3 code removal PR, thanks for your ping!
