### ISSUE TITLE
Add stock information to product list

### ISSUE THREAD

**Issue by Garance91540** [woocommerce/woocommerce-android#2078]
I noticed that we are not showing stock information on our Product list ("in stock", "out of stock", "on backorder", etc)
<img width="273" alt="Screen Shot 2020-03-17 at 2 37 35 PM" src="https://user-images.githubusercontent.com/28450084/76861510-ff6f8500-685c-11ea-8795-939a91c96182.png">

**Comment by anitaa1990** [comment]
> I noticed that we are not showing stock information on our Product list ("in stock", "out of stock", "on backorder", etc)

Looking at the logic currently implemented in the app, it looks like we do show `stock status` of a product, _if `managestock` is enabled for the product_. 

But the logic in Core is to display the stock status only if `Manage Stock` is _disabled_. This is the same logic we have implemented in the Product inventory screen too. Should we update the same logic for the product list and display the stock information only if the manage stock option is enabled?


##### Current implementation in app
<img src="https://user-images.githubusercontent.com/22608780/76927123-2e8d0180-6904-11ea-8db8-88f8b7d99266.png" width="300">

cc @Garance91540

**Comment by Garance91540** [comment]
Hi @anitaa1990, is it possible to use the same logic as what we are doing on iOS?

![IMG_1C0BA20877E3-1](https://user-images.githubusercontent.com/28450084/76948670-af99c800-6907-11ea-9da3-241788536a28.jpeg)

It seems like we are displaying stock info when "manage stock" is enabled for a product AND if "manage stock" is disabled.

**Comment by anitaa1990** [comment]
>  is it possible to use the same logic as what we are doing on iOS?

yup, we can do that 👍
