### ISSUE TITLE
Update bottom divider of "View product in store"

### ISSUE THREAD

**Issue by Garance91540** [woocommerce/woocommerce-android#2091]
The bottom divider of the "view product in store" row appears very dark and thick:
<img width="519" alt="Screen Shot 2020-03-20 at 4 55 03 PM" src="https://user-images.githubusercontent.com/28450084/77181437-99d50000-6acb-11ea-8002-18b4df3f82be.png">

It should look like the separators on the Order Details screen:
<img width="453" alt="Screen Shot 2020-03-20 at 4 57 16 PM" src="https://user-images.githubusercontent.com/28450084/77181607-e02a5f00-6acb-11ea-92ec-aba75e571bc3.png">

**Comment by anitaa1990** [comment]
Closing this issue since it is [fixed in the new dark mode changes](https://github.com/woocommerce/woocommerce-android/pull/2100#issuecomment-603191350) branch: `feature/dark-mode` which will be live in the next release.
