### ISSUE TITLE
Upgrade Gradle Plugin to 3.6.1

### ISSUE THREAD

**Issue by AmandaRiu** [woocommerce/woocommerce-android#2095]
This SO page has some really good info on fixing a common issue: https://stackoverflow.com/questions/60500781/android-studio-3-6-1-with-gradle-plugin-version-3-6-1-and-gradle-version-5-6-4-n

**Comment by anitaa1990** [comment]
Closed since the latest gradle version in the [app is 4.0.2](https://github.com/woocommerce/woocommerce-android/pull/3014)
