### ISSUE TITLE
Edit Product > Price Settings: support zero sale price

### ISSUE THREAD

**Issue by jaclync** [woocommerce/woocommerce-android#2099]
Current behavior:
- in product details (edit product main screen), if a sale price is zero, the sale price isn’t shown at all
- ~in price settings, the sale price isn't saved even after entering 0 into the sale price text field~

In core, a zero sale price is possible and might have some use cases when a product is free for a period of time.

To support zero sale price:
- in product details (edit product main screen), show the sale price even if it's zero
- ~in price settings, allow the sale price to be saved as zero~

**Comment by anitaa1990** [comment]
Update: we already support the option to update the sale price if it is zero so just updated the issue description
