### ISSUE TITLE
Products: provide option to publish/unpublish products

### ISSUE THREAD

**Issue by anitaa1990** [woocommerce/woocommerce-android#2118]
As per design specifications, we want to provide the option to publish or unpublish multiple products.

![Screenshot on 2020-03-25 at 10_48_51](https://user-images.githubusercontent.com/22608780/77504427-53deba00-6e86-11ea-8a78-dee720a013ef.png)

![Screenshot on 2020-03-25 at 10_52_45](https://user-images.githubusercontent.com/22608780/77504596-c5b70380-6e86-11ea-8c91-613242e0e84a.png)

<img src="https://user-images.githubusercontent.com/22608780/77504431-56411400-6e86-11ea-8c20-ed946462c819.png" width="300" />

**Comment by astralbodies** [comment]
De-prioritizing publish/unpublish (and multi-select) to not M2.

**Comment by shiki** [comment]
Looks like this part of Products that we've never considered to be critical. I'll close this for now. We can always reopen it later if we want.
