### ISSUE TITLE
App review prompt appears too soon after selecting "Later"

### ISSUE THREAD

**Issue by rachelmcr** [woocommerce/woocommerce-android#2129]
**Describe the bug**

I saw the app review prompt and selected "Later." Then, after taking just a few actions in the app (at most a few minutes later) I saw the app review prompt again. This was much earlier than I expected, although I'm not sure what the exact expected wait time is.

**To Reproduce**

I'm not sure how to trigger the rating prompt initially, but here's how I reproduced the issue after that:

1. When the app review prompt appears, choose "Later."
2. Open the app settings.
3. Go to Beta features and enable products.
4. Go back to the My store screen and notice that the prompt appears again. Choose "Later."
5. Open the app settings.
6. Go to Beta features and disable products.
7. Go back to the My store screen and notice that the prompt appears again. Choose "Later."
8. Rotate the screen to landscape and notice that the prompt appears again. Choose "Later."
9. Rotate the screen back to portrait and notice that the prompt appears again.

**Screenshots**

Screencast: https://cloudup.com/cyKvX7G3Xjt

**Expected behavior**

I expect that choosing "Later" will dismiss the app review prompt for a longer period of time.

**Mobile Environment**
Please include:
- Device: moto e5 play
- Android version: 8.1.0
- WooCommerce Android version: 3.9-rc-1

**Comment by anitaa1990** [comment]
@rachelmcr since we implemented the new feedback rating feature in the app, a lot of changes have gone into the app review prompt and I am no longer able to reproduce this issue. But would like to confirm with you before closing this issue. Are you still able to reproduce this?

**Comment by rachelmcr** [comment]
I tested and I think the changes to the new feedback rating feature have resolved this, so I'll go ahead and close the issue. Thanks!
