### ISSUE TITLE
Products: Product edits lost after navigating between tabs before updating product

### ISSUE THREAD

**Issue by rachelmcr** [woocommerce/woocommerce-android#2131]
**Describe the bug**

If I navigate between tabs in the bottom nav bar while editing a product (before updating that product), my product edits are lost.

**To Reproduce**

1. Go to app Settings > Beta features > enable Products.
2. Go to the products tab.
3. Select a product to open the product details.
4. Edit any of the product details (title, description, price, etc).
5. Tap any of the other bottom nav tabs: My store, Orders, Reviews.
6. Tap the products tab again and notice you're back on the products list.
7. Select the same product and notice that your previous edits are gone without warning.

**Screenshots**

Screencast: https://cloudup.com/cujs8Ed_zmj

**Expected behavior**

I expect that I'll never be able to discard my product edits without warning. A couple ways I could imagine this working:

* The bottom nav could be hidden while I'm editing a product, so I can't navigate to another tab until I close the product details.
* If I try to navigate to another tab while editing a product, I could get the "discard changes" warning.

**Mobile Environment**
Please include:
- Device: moto e5 play
- Android version: 8.1.0
- WooCommerce Android version: 3.9-rc-1

**Comment by anitaa1990** [comment]
> The bottom nav could be hidden while I'm editing a product, so I can't navigate to another tab until I close the product details.

I believe we could implement this logic where we just hide the bottom nav bar similar to how we handle refunds now. But would like to confirm with @Garance91540 first 👍

**Comment by nbradbury** [comment]
@anitaa1990 I believe your idea is the best solution. I'll go ahead and submit a PR which makes that change, then ask @Garance91540 for a design review.

**Comment by Garance91540** [comment]
> I believe we could implement this logic where we just hide the bottom nav bar similar to how we handle refunds now. But would like to confirm with @Garance91540 first 👍

Sounds like the best solution to me too! Ideally the nav bar is only on parent screens.

**Comment by nbradbury** [comment]
> Ideally the nav bar is only on parent screens.

@Garance91540 Oh, so hide the nav bar unless the user is on one of the four primary fragments? If so,  I'm all in favor of it.

**Comment by Garance91540** [comment]
> > Ideally the nav bar is only on parent screens.
> 
> @Garance91540 Oh, so hide the nav bar unless the user is on one of the four primary fragments? If so, I'm all in favor of it.

if possible yes :)

**Comment by anitaa1990** [comment]
Closed via #2139
