### ISSUE TITLE
My store: Chart labels cut off

### ISSUE THREAD

**Issue by 0nko** [woocommerce/woocommerce-android#2158]
**Describe the bug**
The bottom X-axis labels of the My store charts are cut off.

**Screenshots**
![image](https://user-images.githubusercontent.com/1522856/77904190-6ab94e00-7284-11ea-92f9-0f58ea45f6cb.png)

**Mobile Environment**
- Device: Pixel 4
- Android version: 10.0
- WooCommerce Android version: 3.9-rc-2

**Comment by anitaa1990** [comment]
This looks to be fixed during the stats 4.0 changes:

<img src="https://user-images.githubusercontent.com/22608780/97006351-5fe64380-155d-11eb-96a3-ee1965cbc860.png" width="300"/>
