### ISSUE TITLE
Edit Products M3 - Product Categories Step 2: update product categories

### ISSUE THREAD

**Issue by anitaa1990** [woocommerce/woocommerce-android#2186]
After [step 1 here](https://github.com/woocommerce/woocommerce-android/issues/2185), we should provide the option to update existing product categories.

<img src="https://user-images.githubusercontent.com/22608780/78359465-bd6f6e80-75d2-11ea-80d3-d94cb2ae199c.png" width="300" />. <img src="https://user-images.githubusercontent.com/22608780/78359764-530afe00-75d3-11ea-8d1f-b6dfcc44340f.png" width="300" />

**Comment by mhaqs** [comment]
The PRs for this issue are waiting review:

FluxC: https://github.com/wordpress-mobile/WordPress-FluxC-Android/pull/1572
Woo: https://github.com/woocommerce/woocommerce-android/pull/2378

This work will contribute towards #2187
