### ISSUE TITLE
Edit Products M3 - Product Categories Step 3: add new categories to the product

### ISSUE THREAD

**Issue by anitaa1990** [woocommerce/woocommerce-android#2187]
After [step 1](https://github.com/woocommerce/woocommerce-android/issues/2185) and [step 2](https://github.com/woocommerce/woocommerce-android/issues/2186), we should provide the option to add a new category to the product.

![Annotation on 2020-04-03 at 17-46-46](https://user-images.githubusercontent.com/22608780/78359674-27881380-75d3-11ea-93b0-c3bd9933c22a.png)

**Comment by mhaqs** [comment]
I've started working on this issue. I have a question about this one @Garance91540 :

- How is the list display, when the drop down is clicked? For example, is it hierarchical as well?

**Comment by Garance91540** [comment]
> How is the list display, when the drop down is clicked? For example, is it hierarchical as well?

Good question @mhaqs ! And the answer is yes, let's keep the hierarchical display as well ([here's ](https://d.pr/i/AQo5mE)an example of how G docs display the docs outline)
