### ISSUE TITLE
Edit Products M1: price is displayed incorrectly in the product detail screen

### ISSUE THREAD

**Issue by anitaa1990** [woocommerce/woocommerce-android#2213]
While testing the app, I noticed that `regular_price` of a product is displayed as zero, even when there is a `regular_price` defined for the product. I believe this might also be causing the discard dialog to be displayed in the Pricing screen, even when no changes have been made to the prices.

- I _believe_ the product `regular_price` and `sale_price` should be displayed in the Product detail screen, even if the sale price is 0. 
- Discard dialog should only be displayed if there were any changes made to the product pricing screen.

<img src="https://user-images.githubusercontent.com/22608780/78741522-252d0d00-7977-11ea-9692-9017cc86263e.gif" width="300"/>

**Comment by anitaa1990** [comment]
@0nko since you worked on this during the navigation tests, would you mind taking a look at it?

**Comment by 0nko** [comment]
Yes, it's on my list :). Thanks for filing a bug for it @anitaa1990!
