### ISSUE TITLE
Minor changes to order list item

### ISSUE THREAD

**Issue by nbradbury** [woocommerce/woocommerce-android#2220]
We currently show this:

![Screenshot_1586360609](https://user-images.githubusercontent.com/3903757/78804622-5f55d900-798e-11ea-81c3-8d0d1819a3ce.png)

But we should show this:

<img width="360" alt="Screen Shot 2020-04-08 at 11 42 03 AM" src="https://user-images.githubusercontent.com/3903757/78804561-49481880-798e-11ea-968b-5e82d5e26b37.png">

– Timestamp and order number are shown first. Timestamp only displays the date of creation (or time if order created the same day)
– Customer’s name is emphasized, without the order number which appears in the screen’s title anyway

**Comment by anitaa1990** [comment]
Closing since this has already been implemented in the app
