### ISSUE TITLE
Push notification opens orders instead of reviews

### ISSUE THREAD

**Issue by nbradbury** [woocommerce/woocommerce-android#2223]
From @rachelmcr: 

> I had a weird experience with a review push notification. I received the push notification, tapped on it, and instead of opening the review detail it opened the Orders tab. I noticed that at that point my new orders that weren’t loading before ([this issue](https://href.li/?https://github.com/woocommerce/woocommerce-android/issues/2219)) all loaded on the All Orders tab.

> When I tested receiving a review a second time, tapping the review push notification opened the review detail as expected.

> It seems like the unexpected Order list behavior is linked to how we used to use the Reviews tab for all > new activity, including new orders, and is likely also linked to [this issue](https://github.com/woocommerce/woocommerce-android/issues/1944).

**Comment by anitaa1990** [comment]
This should be fixed with the refactor to the notifications handling on android in #4655 so closing this for now 👍
