### ISSUE TITLE
Edit Product Release M2: provide option to update product visibility

### ISSUE THREAD

**Issue by pmusolino** [woocommerce/woocommerce-android#2228]
As part of Product Settings, we want to allow a user to edit the product's visibility.

Tasks (feel free to add new subtasks):
- [ ] Add the new cell "Visibility" in Product Settings
- [ ] Add the new screen "Visibility"

## Screenshots
| Visibility screen             |  Product Settings |
:-------------------------:|:-------------------------:
![Schermata 2020-04-09 alle 15 30 44](https://user-images.githubusercontent.com/495617/78900428-204f8280-7a77-11ea-9ddc-ae7c7ddff17c.png) | ![Schermata 2020-04-09 alle 15 30 54](https://user-images.githubusercontent.com/495617/78900459-29405400-7a77-11ea-8858-b3ec6d9b194e.png)

**Comment by anitaa1990** [comment]
Closed via #2317
