### ISSUE TITLE
Edit Product Release 2: provide option to update product's purchase note

### ISSUE THREAD

**Issue by pmusolino** [woocommerce/woocommerce-android#2229]
As part of Product Settings, we want to allow a user to edit the product's purchase note.

Tasks (feel free to add new subtasks):
- [ ] Add the new cell "Purchase Note" in Product Settings
- [ ] Add the new screen "Purchase note"

| Product Settings        |  Purchase note screen |
:-------------------------:|:-------------------------:
![Schermata 2020-04-09 alle 15 44 28](https://user-images.githubusercontent.com/495617/78901703-057e0d80-7a79-11ea-8fc9-c07dccf1743c.png) | ![Schermata 2020-04-09 alle 15 44 07](https://user-images.githubusercontent.com/495617/78901711-0747d100-7a79-11ea-96ee-a9e15b0592ea.png)

**Comment by pmusolino** [comment]
Check the figma design before implementing it, the view has undergone some changes! 👍

**Comment by anitaa1990** [comment]
Closing since another issue was opened and worked on in #2272
