### ISSUE TITLE
Edit Product Release M2: provide option to update product's order (product positioning in the catalog)

### ISSUE THREAD

**Issue by pmusolino** [woocommerce/woocommerce-android#2230]
As part of Product Settings, we want to allow a user to edit the product positioning in the catalog.

Tasks (feel free to add new subtasks):
- [ ] Add the new cell "Menu Order" in Product Settings
- [ ] Add the new screen "Menu Order" (this will be redesigned shortly. Check Figma for the final design)

| Product Settings        |  Menu Order screen (this will be redesigned shortly. Check Figma for the final design) |
:-------------------------:|:-------------------------:
![Schermata 2020-04-09 alle 15 52 39](https://user-images.githubusercontent.com/495617/78902526-33178680-7a7a-11ea-8227-57d6f9dea8e4.png) | ![Schermata 2020-04-09 alle 15 52 53](https://user-images.githubusercontent.com/495617/78902531-34e14a00-7a7a-11ea-8d07-bf59015bdfcf.png)

**Comment by pmusolino** [comment]
Since we decided to maintain this design (discussion [here](https://a8c.slack.com/archives/CGPNUU63E/p1587541699000300)), I'm moving this task to Milestone 2.

**Comment by nbradbury** [comment]
Closed via #2298
