### ISSUE TITLE
Product name editor jumps to the end

### ISSUE THREAD

**Issue by nbradbury** [woocommerce/woocommerce-android#2233]
To reproduce, use a real device:

* Open product detail
* Tap in the middle of the product name
* Type a letter

After you type, the cursor will jump to the end.

**Comment by rachelmcr** [comment]
A beta tester using 4.2-rc-1 just reported the same issue:

> The cursor position moves to last while editing product title, after inputting a single character from middle or start. This is frustrating. Kindly fix the bug.
