### ISSUE TITLE
Products infinite scroll jumps around with lowercase & non-alpha products

### ISSUE THREAD

**Issue by astralbodies** [woocommerce/woocommerce-android#2235]
**Describe the bug**
If your store contains a product starting with a non-alpha character like a quotation mark or a lowercase character, that product is always pinned to the bottom. As you scroll the products will fill in between.

**To Reproduce**
1. Load a store with product having a lowercase letter or quotation mark as the first character of the name. There should be at least 20 other products to show the scrolling behavior.
2. Tap on the Products tab.
3. Scroll to find your test product - it should be at the end.
4. Keep scrolling and notice that test product keeps going to the bottom.

**Expected behavior**
The sort of the API response should match the sort of the UI to keep the idea of paging aligned better as more pages are loaded.

**Mobile Environment**
Please include:
- Device: Pixel 2 XL
- Android version: 10 
- WooCommerce Android version: 4.0-rc1

</details>

**Comment by nbradbury** [comment]
Note that there are two issues here, both of which needs to be fixed on the FluxC side.

1. WellSQL doesn't provide case-insensitive sorting, so products are returned with lowercase names at the end.
2. Products names that start with a non-alpha character are returned by the server at the beginning, but SQLite sorts them to the end locally.
