### ISSUE TITLE
Products M1 release: remove end date option is displayed when there is no end date

### ISSUE THREAD

**Issue by anitaa1990** [woocommerce/woocommerce-android#2247]
While testing this [PR](https://github.com/woocommerce/woocommerce-android/pull/2231), I noticed that the `Remove end date` option in Product pricing screen is displayed when there is no end date for the sale. I'm pretty sure this was fixed in [this PR](https://github.com/woocommerce/woocommerce-android/pull/2125) so maybe the changes were missed or reverted during dark mode changes 🤷 

<img src="https://user-images.githubusercontent.com/22608780/79314098-f25aba00-7f1e-11ea-8d5f-78c1cb83a5b0.png" width="300"/>

**Comment by anitaa1990** [comment]
@0nko since you worked on this change would you be able to take a look at this?

**Comment by 0nko** [comment]
Definitely. Thanks for the ping!
