### ISSUE TITLE
Products M2 release: images params are getting updated when updating a product from M1 release

### ISSUE THREAD

**Issue by anitaa1990** [woocommerce/woocommerce-android#2248]
While testing the products M1 release, I noticed that the image params are also included when we try to update a product section, unrelated to images.

<img width="823" alt="Screenshot 2020-04-15 at 1 52 12 PM" src="https://user-images.githubusercontent.com/22608780/79316114-84fc5880-7f21-11ea-8849-79eb98c6b9fb.png">

cc @nbradbury, not sure how critical this is or but perhaps you could take a look at it?

**Comment by nbradbury** [comment]
I opened a FluxC issue [here](https://github.com/wordpress-mobile/WordPress-FluxC-Android/issues/1547) since the bug is on the FluxC side.
