### ISSUE TITLE
Verify/Fix behavior when using social login with an unconnected Google account

### ISSUE THREAD

**Issue by aforcier** [woocommerce/woocommerce-android#225]
Reported here by @astralbodies: https://github.com/woocommerce/woocommerce-android/pull/216#issuecomment-393517325

It looks like the problem is that there's no messaging and Google login silently fails under this condition:

> it only seems to happen when connecting a Google account for the first time on a device that's sharing the e-mail address of a WordPress.com that hasn't been connected to Google.

Some further testing is required to pin down the exact issue.

**Comment by AmandaRiu** [comment]
Closing this issue as we already have a more detailed issue open #903
