### ISSUE TITLE
All Orders tab should not show future-dated orders

### ISSUE THREAD

**Issue by shiki** [woocommerce/woocommerce-android#2252]
## Describe the Bug

The All Orders tab shows some, **but not all**, orders that are dated in the future. 

Processing Tab | All Orders Tab
--------|-------
<img src="https://user-images.githubusercontent.com/198826/79391971-c267e280-7f2f-11ea-9c4f-0219b47d8a02.png" width="320">        |       <img src="https://user-images.githubusercontent.com/198826/79391978-c431a600-7f2f-11ea-9e8e-8eda39897b5f.png" width="320">

These screenshots were taken on April 15th, 2020. 

## To Reproduce

1. In wp-admin, create orders that are dated (`dateCreated`) tomorrow (morning time). 
2. Create an order that is dated 5 days in the future. 
3. Navigate to Orders → All Orders

## Expected Behavior

Based on p99K0U-1X8-p2, the All Orders Tab should not show an "Upcoming" section at all. In the screenshots above, notice that some orders are shown in the All Orders tab. But the April 17 order was not shown. 

## Notes

It looks like in [OrderListItemDataSource](https://github.com/woocommerce/woocommerce-android/blob/2b7b8c559364af5411515cb03ce94673e75571d8/WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/list/OrderListItemDataSource.kt#L115-L122), we use `DateUtils.isAfterDate` to determine if an order is in the future. But it looks like that function uses rounding which may be the cause for this bug. 

Here’s a sample evaluation of `DateUtils.isAfterDate` returning `false` when comparing a **today** Date and a **tomorrow** Date.

![image](https://user-images.githubusercontent.com/198826/79392334-7a958b00-7f30-11ea-8f71-57dc4c273b4d.png)

## Isolating the Problem 

- [ ] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [ ] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [x] I can reproduce this bug consistently using the steps above.

## Mobile Environment

- Device: Pixel 3
- Android version: 10
- WooCommerce Android version: 4.0-rc.2

**Comment by shiki** [comment]
@AmandaRiu FYI, @Garance91540 mentioned in p5T066-1i2-p2#comment-4879 that she _agrees_ that we should **show future orders** in the All Orders tab. So this issue might be affected by that.

**Comment by AmandaRiu** [comment]
@shiki Great point. I'm going to close this ticket and open a new one to update the code to always show future-dated orders on both tabs. Thank you!
