### ISSUE TITLE
Order Detail Payment Card: show customer paid amount for payment pending

### ISSUE THREAD

**Issue by AmandaRiu** [woocommerce/woocommerce-android#2254]
On iOS and core when there’s an order with the “Payment pending” status, we also show the “Paid by Customer = $0”. Could we do the same on Android?

**Comment by anitaa1990** [comment]
It looks like this has already been implemented

<img src="https://user-images.githubusercontent.com/22608780/83129445-75fcee80-a0fa-11ea-9464-75e3ea7f064c.png" width="300"/>

Marking the issue as closed.
