### ISSUE TITLE
Product Settings: Move radio to the right

### ISSUE THREAD

**Issue by AmandaRiu** [woocommerce/woocommerce-android#2261]
Update the alignment of the radio buttons to the right like the design below. @nbradbury I assigned this one directly to you since you are working on this screen. I recommend using the `CheckedTextView` component since it has a theme level style applied so you only need to set the margins and it will be light/dark compatible 👍 

![Screen Shot 2020-04-16 at 4 07 09 PM](https://user-images.githubusercontent.com/5810477/79515043-72a31d00-7ffc-11ea-8453-b36bf02fd4f8.png)

**Comment by nbradbury** [comment]
Closed via #2269
