### ISSUE TITLE
Product image upload tweaks to match iOS

### ISSUE THREAD

**Issue by nbradbury** [woocommerce/woocommerce-android#2267]
- If the user taps “Done” while some images are still being uploaded, we will keep track of the images that are in-progress, display the in-progress UI (blurred image + circle spinner) for these images on the Edit Product screen, and then update the UI for these images once they are uploaded

- When the user taps “Update” on the Edit Product screen, we first show the in-progress UI, wait for all images to be uploaded and then update the Product remotely.

- When the user navigates away from the Edit Product screen, no changes are made to the Product and these images keep being uploaded in the background. In this situation, we show the discard dialog.

-  If the user navigates away from the Edit Product Images screen while some images are still being uploaded, these images keep being uploaded in the background but they won’t be added to the Product.

**Comment by anitaa1990** [comment]
We made some changes to the image upload process to ensure that it continues to happen in the background. Most of the UI enhancements here are related to moving away from the Product screen and since this is now possible, I'll mark this issue as closed.
