### ISSUE TITLE
Edit Product Release M2: enable reviews

### ISSUE THREAD

**Issue by nbradbury** [woocommerce/woocommerce-android#2271]
As per designs, we need to add "Enable reviews" to the product settings screen.

<img width="188" alt="Screenshot 2020-03-13 at 12 21 53 PM" src="https://user-images.githubusercontent.com/22608780/76596912-4d1a8380-6525-11ea-8825-1b9b55d56c40.png">

**Comment by anitaa1990** [comment]
Hey @nbradbury just wanted to point out that updating menu order is scheduled to be part of M3 release and an [issue](https://github.com/woocommerce/woocommerce-android/issues/2191) has already been filed and added to the [Add/Edit Products release 3](https://github.com/woocommerce/woocommerce-android/projects/9) kanban board so closing this one. I have assigned you to that issue in #2191 though. Hope that's ok 👍
