### ISSUE TITLE
Copy order details to clipboard (addresses, phone, e-mail address)

### ISSUE THREAD

**Issue by astralbodies** [woocommerce/woocommerce-android#23]

**Comment by rachelmcr** [comment]
There isn't a quick/one-tap way to copy order details to clipboard. However, I confirmed that from the order details I can:

* Manually select/copy the address, phone, and email
* Call/message the phone number
* Email the email address

**Comment by mindgraffiti** [comment]
Closing because we have the main interactions complete.
