### ISSUE TITLE
Dark mode: About screen alignment issues

### ISSUE THREAD

**Issue by anitaa1990** [woocommerce/woocommerce-android#2303]
When testing dark mode, I noticed that the About screen in the app aligns the privacy policy and Terms items are aligned differently when compared to the designs.

#### DESIGN
<img width="300" src="https://user-images.githubusercontent.com/22608780/80078428-899dbe00-856c-11ea-8a2b-929ab50fce8f.png"/>

#### CURRENT SCREEN
<img src="https://user-images.githubusercontent.com/22608780/80078431-8b678180-856c-11ea-8af1-4a621f3499af.png" width="245"/>

**Comment by AmandaRiu** [comment]
This design and the final screen implementation were [discussed in the original PR](https://github.com/woocommerce/woocommerce-android/pull/1835#issuecomment-577294823). Originally I was trying to keep with the material design standards for preferences and the custom components written to conform to those standards while implementing all the settings options, but now that the project is finished I think having this screen not following those conventions wouldn't be a big deal. It's not really an option setting anyway. I can get it updated. cc: @Garance91540
