### ISSUE TITLE
Login: Can't auto-fill my WordPress.com credentials from password manager

### ISSUE THREAD

**Issue by rachelmcr** [woocommerce/woocommerce-android#2305]
**Describe the bug**

When I try to log in to the app by auto-filling my credentials from my password manager (LastPass), it only offers my WooCommerce.com credentials. This happens throughout the login process, whether I am on the email screen or email/password screen (WordPress.com credentials) or the site address username/password screen (self-hosted credentials).

**To Reproduce**

1. Make sure your WordPress.com and self-hosted credentials are saved in a password manager on your device.
2. In the app, starting logged out, tap on "Log In."
3. Long tap in the Email Address field until the contextual menu appears.
4. Tap the 3-dots and select Auto-fill. (If needed, confirm that you want to auto-fill from your password manager.)
5. Notice that your WordPress.com credentials don't appear. If you have credentials saved for WooCommerce.com, those credentials are offered but don't work for login to the app.

You can repeat the same steps in any part of the login flow, and notice that the appropriate credentials are never offered for auto-fill.

**Screenshots**

Auto-fill menu:

<img src="https://user-images.githubusercontent.com/8658164/80095042-307b5d80-855f-11ea-9069-00557d9a580b.png" width="50%">

Credentials available to auto-fill:

<img src="https://user-images.githubusercontent.com/8658164/80095072-3ec97980-855f-11ea-943a-14c518621e29.png" width="50%">

**Expected behavior**

When auto-fill is available, I expect to be able to auto-fill:

* My WordPress.com credentials wherever I am in a WordPress.com login flow (e.g. email screen, email/password screen)
* My self-hosted credentials in the self-hosted username/password screen

I don't expect to see WooCommerce.com credentials offered, since they can't be used in the app.

**Mobile Environment**
Please include:
- Device: moto e5 play
- Android version: 8.1.0
- WooCommerce Android version: 4.1-rc-1

**Comment by rossanafmenezes** [comment]
Tested. It currently works with both lastpass and 1Password.
