### ISSUE TITLE
Dark Mode: Product image placeholder is black on black in Top Performers

### ISSUE THREAD

**Issue by rachelmcr** [woocommerce/woocommerce-android#2313]
**Describe the bug**

Under My store > Top performers, the product image placeholder (if a product doesn't have an image) is black on a black background in dark mode.

**To Reproduce**

1. Add a product to your store with no product image.
2. Receive enough orders for that product so it appears in the top performers section on the My store tab.
3. With the app in light mode, view the top performers section and notice that product has an image placeholder that is black on a white background.
4. Go to Settings > Appearance and switch to Dark.
5. Go back to the My store tab and notice the image placeholder is now black on a black background.

**Screenshots**

Light|Dark
-|-
![Screenshot_20200424-114936](https://user-images.githubusercontent.com/8658164/80205311-4bfb6c80-8622-11ea-8806-4059671c006d.png)|![Screenshot_20200423-201228](https://user-images.githubusercontent.com/8658164/80205312-4e5dc680-8622-11ea-9fe8-05d105ff05d2.png)

**Mobile Environment**
Please include:
- Device: moto e5 play
- Android version: 8.1.0
- WooCommerce Android version: 4.1-rc-1

**Comment by AmandaRiu** [comment]
@rachelmcr I'm unable to reproduce this one:

![image](https://user-images.githubusercontent.com/5810477/80262923-cbe5fe80-8643-11ea-8a47-eabbe637413c.png)


Are other icons in the app not appearing properly in dark mode? The same coloring logic is used for the "no image" icon in products list, and item icons like the Price, Inventory, and Shipping:

![image](https://user-images.githubusercontent.com/5810477/80262964-fa63d980-8643-11ea-884d-731a7b18b3d2.png)

**Comment by rachelmcr** [comment]
Huh, interesting.

> Are other icons in the app not appearing properly in dark mode?

No, this is the only place where icons aren't appearing properly in dark mode. Everywhere else they appear as expected, with light icon on dark background (item icons and the same products in the Products list).

I know you said the same coloring logic is used here, but in case it's relevant I am using a light system theme (with a version of Android that doesn't natively support dark theme) with the dark theme selected in the app settings.

**Comment by AmandaRiu** [comment]
@rachelmcr This is a puzzle. Can you do me a favor and post a screenshot of that same product in the products list tab, and product detail views? I'm curious how the image looks in other areas.

**Comment by AmandaRiu** [comment]
Also, is it possible that your product is using that placeholder image as its own image?

**Comment by AmandaRiu** [comment]
@rachelmcr nm...I loaded 8.1 on a non-google device and yup, I see it now too. This will help me get to the bottom of it 👍
