### ISSUE TITLE
Products: Banner on Products screen overlaps empty search results message

### ISSUE THREAD

**Issue by rachelmcr** [woocommerce/woocommerce-android#2314]
**Describe the bug**

The "Limited editing available" banner persists on the Product search screen. It works fine with product search results, but if there are no search results the banner overlaps the "We're sorry, we couldn't find results for X" message.

**To Reproduce**

1. Open the Products tab.
2. Tap the search icon to search products. Notice the "Limited editing available" banner is visible.
3. Search for a product in your store. Notice the banner appears above the results.
4. Search for a non-matching keyword. Notice the banner overlaps the "no results" message.

**Screenshots**

<img src="https://user-images.githubusercontent.com/8658164/80208086-5d934300-8627-11ea-9a05-7e89eb2b70af.png" width="50%">

**Mobile Environment**
Please include:
- Device: moto e5 play
- Android version: 8.1.0
- WooCommerce Android version: 4.1-rc-1

**Comment by 0nko** [comment]
Can't reproduce anymore.
