### ISSUE TITLE
Dark Mode v2: Notification icon coloring

### ISSUE THREAD

**Issue by AmandaRiu** [woocommerce/woocommerce-android#2318]
The "W" icon in the notification is using the old purple:

![image](https://user-images.githubusercontent.com/5810477/80261437-43655f00-863f-11ea-81bb-9361acc5651f.png)

![image](https://user-images.githubusercontent.com/5810477/80261464-524c1180-863f-11ea-96d8-f26fdf13987e.png)

![image](https://user-images.githubusercontent.com/5810477/80261486-609a2d80-863f-11ea-887a-4e1f9bc436f4.png)

**Comment by AmandaRiu** [comment]
@Garance91540 What do you think about changing the notification icon to the woo bubble version? I don't have an svg version of the "W" version and it seems weird anyway because that's not used anywhere else in the app. 

![image](https://user-images.githubusercontent.com/5810477/80267854-2426fb80-8658-11ea-8bf2-ffe43aa24654.png)

**Comment by Garance91540** [comment]
Hi @AmandaRiu , sounds good to me if doesn't take too much space in the row! Can you send me a screenshot of how it looks in dark/light mode?

**Comment by AmandaRiu** [comment]
@Garance91540 Absolutely, I'll get it swapped and post a screenshot so you can see how it looks.

**Comment by AmandaRiu** [comment]
@Garance91540 Here's what it looks like if I change it to the woo bubble icon. Note that I have two different versions of the app running on my test device so you can see how they contrast:

System bar | Light | Dark 
-- | -- | -- 
![Screen Shot 2020-04-27 at 12 07 22 PM](https://user-images.githubusercontent.com/5810477/80410805-04721c00-8880-11ea-9a04-343dab9e3b4a.png)|![Screen Shot 2020-04-27 at 12 03 43 PM](https://user-images.githubusercontent.com/5810477/80410810-063bdf80-8880-11ea-9cfe-6cf1221d0bda.png)|![Screen Shot 2020-04-27 at 12 03 54 PM](https://user-images.githubusercontent.com/5810477/80410824-0b009380-8880-11ea-9f1a-30140270a6a9.png)

**Comment by Garance91540** [comment]
Looking good 😍
