### ISSUE TITLE
Edit Products M3 - edit an existing grouped product

### ISSUE THREAD

**Issue by pmusolino** [woocommerce/woocommerce-android#2323]
As part of Products M3, we should provide a way to edit an existing grouped product.

Feel free to split this issue into more subtasks.

This is the entire flow:
![android grouped products](https://user-images.githubusercontent.com/495617/80396393-d9ee8600-88b4-11ea-9f54-96708f38dcd8.jpg)

**Comment by anitaa1990** [comment]
Closed via #2626 and since the last part of editing a grouped product (selecting products) is being worked on in #2630
