### ISSUE TITLE
Edit Products M3 - edit an existing external product

### ISSUE THREAD

**Issue by pmusolino** [woocommerce/woocommerce-android#2324]
As part of Products M3, we should provide a way to edit an existing external product.

Feel free to split this issue into more subtasks.

This is the flow:
![external products android](https://user-images.githubusercontent.com/495617/80397289-31412600-88b6-11ea-82cd-2697b347c3f0.jpg)

**Comment by anitaa1990** [comment]
Closed via #2626 and #2658
