### ISSUE TITLE
Login Epilogue: Changes to buttons and background

### ISSUE THREAD

**Issue by AmandaRiu** [woocommerce/woocommerce-android#2342]
The following changes are needed to the button bar in the Login Epilogue screen:

- Button styling
- Remove button bar background

![Screen Shot 2020-04-28 at 11 56 13 AM](https://user-images.githubusercontent.com/5810477/80526271-5af65d80-8947-11ea-9f0f-31230883f6ed.png)

**Comment by AmandaRiu** [comment]
@Garance91540 these changes will also effect the button look on the site selector screen since this is all the same view:

![Screen Shot 2020-04-28 at 11 54 52 AM](https://user-images.githubusercontent.com/5810477/80526404-8b3dfc00-8947-11ea-8528-b7b5c90e5eed.png)

Please confirm these changes are ok.

**Comment by Garance91540** [comment]
Looking good! Thank you!

**Comment by AmandaRiu** [comment]
This was completed and merged. Closing.
