### ISSUE TITLE
Edit Products M2: add tracking events for images and product settings

### ISSUE THREAD

**Issue by anitaa1990** [woocommerce/woocommerce-android#2351]
There are a few events that were missed the first time in #2339. Thanks for drafting the names @jaclync! 

### Product Images

- I want to manage my product's images.

event name | trigger | properties
-- | -- | --
*_product_detail_add_image_tapped | User tapped on the "+" button in the Product Detail screen to update product images. | n/a
*_product_image_settings_add_images_button_tapped | User tapped on the Add Photos button in the product image settings screen. | n/a
*_product_image_settings_add_images_source_tapped | User tapped on the image source menu button in the product image settings screen. | n/a
*_product_image_settings_delete_image_button_tapped | User tapped on the trash button in the product image screen. | n/a 

### More Product Menu

- I want to view my product webpage.

event name | trigger | properties
-- | -- | --
*_product_detail_view_product_button_tapped | User tapped on the View Product in Store option in the product detail menu | n/a

### Product Settings

- I want to change the status of my product.

event name | trigger | properties
-- | -- | --
*_product_settings_status_tapped | User tapped on the status row in the product settings screen | n/a

- I want to modify the catalog visibility of my product.

event name | trigger | properties
-- | -- | --
*_product_settings_catalog_visibility_tapped | User tapped on the catalog visibility row in the product settings screen | n/a

- I want to edit my product's URL in my store.

event name | trigger | properties
-- | -- | --
*_product_settings_slug_tapped | User tapped on the slug row in the product settings screen | n/a

- I want to edit my product's purchase note

event name | trigger | properties
-- | -- | --
*_product_settings_purchase_note_tapped | User tapped on the purchase note row in the product settings screen | n/a

- I want to edit my product's visibility

event name | trigger | properties
-- | -- | --
*_product_settings_visibility_tapped | User tapped on the visibility row in the product settings screen | n/a

- I want to set an order for my product in the Menu Order

event name | trigger | properties
-- | -- | --
*_product_settings_menu_order_tapped | User tapped on the menu order row in the product settings screen | n/a

### Product List Sorting/Filtering

- I want to sort products by ascending/descending name/date

event name | trigger | properties
-- | -- | --
*_product_list_view_sorting_options_tapped | User tapped on the sorting button in the Product List screen | `order={name/date},{ascending/descending}` (e.g. `order=name,ascending`)

**Comment by anitaa1990** [comment]
@nbradbury I assigned this issue to you since you worked on the product images and product settings screen. Hope that is ok!

**Comment by nbradbury** [comment]
> I assigned this issue to you since you worked on the product images and product settings screen. Hope that is ok!

@anitaa1990 No problem at all - I was planning to make this my next task already!

**Comment by nbradbury** [comment]
@anitaa1990 For `product_image_settings_add_images_source_tapped`, shouldn't we pass which source the user chose?

**Comment by anitaa1990** [comment]
Apologies for the late reply Nick! I completely missed the notification for this.

> For product_image_settings_add_images_source_tapped, shouldn't we pass which source the user chose?

Good point! Feel free to add that event property. 

> Also, are we sure the event for viewing your product in the store is PRODUCT_DETAIL_VIEW_PRODUCT_BUTTON_TAPPED, because we already have the event PRODUCT_DETAIL_VIEW_EXTERNAL_TAPPED for that?

Ohh, I missed that we already had an event for this. My bad! In that case, we can use the old one and remove the `PRODUCT_DETAIL_VIEW_PRODUCT_BUTTON_TAPPED`.

> Last but not least, right now we already track PRODUCT_LIST_VIEW_SORTING_OPTIONS_TAPPED when the user taps the sorting button to show the sort order bottom sheet. I checked the spreadsheet and it looks like that event should be tracked after the user chooses the sort order, but I wanted to verify with you since you wrote that code.

I had added the `PRODUCT_LIST_VIEW_SORTING_OPTIONS_TAPPED` to track when the user taps the sorting button. I think we might need to add an additional event to track the sorting option selected by the user. How about: `*_product_sorting_list_option_selected` and the event property can be `order="name/date,ascending,descending"`?

cc @jaclync and @pmusolino since we might need to make changes to iOS as well for the above scenarios.

**Comment by nbradbury** [comment]
Thanks, @anitaa1990. I'll make those changes and submit a PR assigned to you. However, rather than `product_sorting_list_option_selected` I think we should use `product_list_sorting_option_selected` for consistency with the other product list events (such as `product_list_view_sorting_options_tapped`
