### ISSUE TITLE
Notifications: Review push notification opens blank My store screen

### ISSUE THREAD

**Issue by rachelmcr** [woocommerce/woocommerce-android#2386]
**Describe the bug**

Tapping a review push notification should open the review detail, but instead it opens a blank My store screen. I consistently see this behavior when I have the battery saver enabled on my device; I don't see it with the battery saver disabled, so this is likely a contributing factor.

**To Reproduce**

1. Enable the battery saver on your device.
2. Close the app completely (don't just background it).
3. Receive a review on your store.
4. Tap the review push notification.
5. Notice that you are taken to a blank My store screen.
6. Disable the battery saver and repeat steps 2-4; notice that this time the review detail opens as expected.

**Screenshots**
<img src="https://user-images.githubusercontent.com/8658164/81190434-bf509700-8faf-11ea-8583-a9379648600d.png" width="300px">

**Mobile Environment**
Please include:
- Device: moto e5 play
- Android version: 8.1.0
- WooCommerce Android version: 4.2-rc-1

**Comment by designsimply** [comment]
Tested and confirmed, using WCAndroid 5.9-rc-3, that review push notifications do no open the review detail if Battery Saver is on. The My Store screen displayed normally for me though and was not blank. ([3m16s](https://cloudup.com/cLTKknrf88g))

Battery Saver on|Device Notifications|Landed on filled-in My Store screen
---|---|---
![Screen Shot 2021-02-04 at Feb 4 11 28 23 AM](https://user-images.githubusercontent.com/1119271/106938493-4a47f480-66dc-11eb-8efa-6a58582ffe91.png)|![Screen Shot 2021-02-04 at Feb 4 11 28 37 AM](https://user-images.githubusercontent.com/1119271/106938484-4916c780-66dc-11eb-942d-03a9f03e1fb4.png)|![Screen Shot 2021-02-04 at Feb 4 11 28 45 AM](https://user-images.githubusercontent.com/1119271/106938478-487e3100-66dc-11eb-9623-af56acf838f0.png)

<sup>Tested with WCAndroid 5.9-rc-3 on Pixel 3 Android 11 on comparative-moth.jurassic.ninja (WP 5.6 JP 9.4 WC 5.0.0-rc.1) logged in as testuser01121.</sup>

**Comment by designsimply** [comment]
I also tested order notifications and the order detail opened properly. ([1m51s](https://cloudup.com/c1sYctNFn6N))
<sup>Tested with WCAndroid 5.9-rc-3 on Pixel 3 Android 11 on comparative-moth.jurassic.ninja (WP 5.6 JP 9.4 WC 5.0.0-rc.1) logged in as testuser01121.</sup>

**Comment by anitaa1990** [comment]
I tested using v8.7 and I can no longer reproduce this issue. It must be fixed with the latest Hub menu changes we made to the app. I'll mark this as closed.
