### ISSUE TITLE
Products: Product list sort order changed unexpectedly

### ISSUE THREAD

**Issue by rachelmcr** [woocommerce/woocommerce-android#2387]
**Describe the bug**

The product list on the Products tab is no longer sorted alphabetically. It doesn't look like that was an expected change in this release, and I can't tell what the intended sort order is (it isn't alphabetical or the default sort order I see in WP Admin).

@anitaa1990 could this be an unintended change related to the sorting and filtering changes you are working on?

**To Reproduce**

1. Open the Products tab.
2. Scroll through the products tab and notice the products are not in alphabetical order anymore.
3. Compare the product list to WP Admin and notice that it isn't the same as that order, either.

**Screenshots**

<img src="https://user-images.githubusercontent.com/8658164/81192185-d2646680-8fb1-11ea-9a8f-b90b67de56d4.png" width="300px">

WP Admin with default sort order:

![Screenshot 2020-05-06 15 51 39](https://user-images.githubusercontent.com/8658164/81192318-faec6080-8fb1-11ea-8a00-3993def8f6b3.png)

**Mobile Environment**
Please include:
- Device: moto e5 play
- Android version: 8.1.0
- WooCommerce Android version: 4.2-rc-1

**Comment by anitaa1990** [comment]
Thanks for flagging this @rachelmcr! 

It looks like the Product list are sorted by date desc i.e. `Newest` first by default. I think if the user switches on the `Product Editing` switch from `Settings` screen, by default the products are sorting by date desc. If the Product editing switch is off, we should probably sort the products by name asc 🤔
