### ISSUE TITLE
Settings: Woo launch screen appears after changing Improved Stats beta setting

### ISSUE THREAD

**Issue by rachelmcr** [woocommerce/woocommerce-android#2388]
**Describe the bug**

After toggling the Beta features > improved stats setting, going back to the My store screen displays the Woo launch screen before the My store screen reloads.

**To Reproduce**

1. Open Settings > Beta features.
2. Toggle the Improved stats setting.
3. Go back to the My store screen and notice the app launch screen appears before the My store screen reloads.

**Screenshots**

Screencast: https://cloudup.com/c73x7s8jlZd

**Expected behavior**

I expect to see a loading screen (with skeletons) if needed, but not the app launch screen.

**Mobile Environment**
Please include:
- Device: moto e5 play
- Android version: 8.1.0
- WooCommerce Android version: 4.2-rc-1

**Comment by 0nko** [comment]
Not applicable anymore (feature changed and out is out of beta).
