### ISSUE TITLE
Order Details screen says Order #null while loading

### ISSUE THREAD

**Issue by astralbodies** [woocommerce/woocommerce-android#2389]
**Describe the bug**
When tapping on an order push notification the view temporarily says "Order #null" in the title while the data loads.

I have a test site with a lot of orders and products, so it's a shade slower than normal.

**To Reproduce**
1. Exit the app.
1. Place a new order.
2. Wait for the push notification.
3. Tap it to launch the app.
4. See the Order #null placeholder while the skeleton is showing and the order data is loading.

**Screenshots**
Didn't have time to grab one, but can do it if needed.

**Expected behavior**
Loading order or something maybe?

**Mobile Environment**
Please include:
- Device: Pixel 2 XL
- Android version: 10
- WooCommerce Android version: latest beta - 4.2

**Comment by shiki** [comment]
Is this the same as #1939?

**Comment by astralbodies** [comment]
Derp, it is @shiki. Clearly my eyes are not working today!
