### ISSUE TITLE
Product Details: add product type row

### ISSUE THREAD

**Issue by jaclync** [woocommerce/woocommerce-android#2406]
iOS issue: https://github.com/woocommerce/woocommerce-ios/issues/2262

Let's add a product type row to product form based on the design:

<img width="192" alt="Screen Shot 2020-05-11 at 8 34 53 PM" src="https://user-images.githubusercontent.com/1945542/81562389-56aa5580-93c7-11ea-83bb-d77f4b3a2e1c.png">

- Simple product (`type` is `simple`)
- Variable product (`type` is `variable`)
- Grouped product (`type` is  `grouped`)
- External product (`type` is `external`)
- Custom product type name (e.g. subscriptions)

**Comment by anitaa1990** [comment]
@Garance91540 since the editing products feature is only enabled for Simple products, at the moment, this read only product type would just display `Simple Product`. Does it make sense to add this to the M2 release? Or can we move this to M3 where we can also provide the option to edit variations and product type as well?

**Comment by Garance91540** [comment]
> Or can we move this to M3 where we can also provide the option to edit variations and product type as well?

Let's wait for M3!

**Comment by jaclync** [comment]
ℹ️ update - after chatting with @Garance91540 via DM, we will differentiate physical and virtual products from simple products whenever we handle product type in Add/Edit Products context (readonly or edit options). the possible product type options are now:

- Physical product (`type` is `simple`, `virtual` field is off)
- Virtual product (`type` is `simple`, `virtual` field is on)
- Variable product (`type` is `variable`)
- Grouped product (`type` is  `grouped`)
- External product (`type` is `external`)
- (readonly, not a product type option in the action sheet) custom product type (e.g. subscriptions)

(related iOS issue https://github.com/woocommerce/woocommerce-ios/issues/2262)
