### ISSUE TITLE
Orders → Processing Tab Should Show “Waiting for your first order”

### ISSUE THREAD

**Issue by shiki** [woocommerce/woocommerce-android#2408]
## Is your feature request related to a problem? Please describe.

As mentioned by @Garance91540 in https://github.com/woocommerce/woocommerce-ios/pull/2245#pullrequestreview-406383796, we should show the “Waiting for your first order” screen in the Processing Tab if there are no orders.

Right now, we only show “All orders have been fulfilled”. 

<img src="https://user-images.githubusercontent.com/198826/81593045-196ca600-937c-11ea-8b04-88bd61eed75c.gif" width="320">

## Describe the solution you'd like

I'm thinking the spec may be:

Is Processing tab empty? | Is All Orders tab empty? | Message to show
--------|-------|-
yes        |       yes  | Waiting for your first order
yes | no | All orders have been fulfilled

Is this correct, @Garance91540?

**Comment by Garance91540** [comment]
> Is this correct, @Garance91540?

That is correct @shiki ! Another way of saying this is that the "waiting for your first order" should not be shown again after user received their first order.

**Comment by hafizrahman** [comment]
This is already the case in my test just now, although I'm not sure which PR fixed this. I'm closing for now.

**Comment by shiki** [comment]
Thanks for cleaning up, @hafizrahman! 🙏
