### ISSUE TITLE
OutOfMemoryError crashes

### ISSUE THREAD

**Issue by shiki** [woocommerce/woocommerce-android#2417]
This is a collection of all the OutOfMemoryError crashes in Sentry. There are multiple events but with different stack traces.

**Comment by nbradbury** [comment]
Note that all the [InflateExceptions](https://sentry.io/organizations/a8c/issues/?project=1459556&query=is%3Aunresolved+inflateexception&statsPeriod=14d) in Sentry are also OutOfMemoryExceptions.

**Comment by AmandaRiu** [comment]
Some of these may also be released to an issue with setting the app theme dynamically in MainActivity described and fixed in #2457

**Comment by anitaa1990** [comment]
I'm not seeing any out of memory crashes anymore in Sentry 🎉 So closing this issue! Thanks to @AmandaRiu and @nbradbury for taking care of this one!
