### ISSUE TITLE
Update home indicator color to black

### ISSUE THREAD

**Issue by Garance91540** [woocommerce/woocommerce-android#2430]
Currently, our Home indicator is grey:
![Screenshot_20200514-142604](https://user-images.githubusercontent.com/28450084/81935726-64dbba00-95f1-11ea-9d06-b02acd8d0667.png)

Could we update it to black so it blends with the screen black borders?

I took a quick look at other apps and it seems to be the common color choice:

<img width="941" alt="Screen Shot 2020-05-14 at 2 43 43 PM" src="https://user-images.githubusercontent.com/28450084/81935814-82108880-95f1-11ea-9819-5a4f04bc4b42.png">

**Comment by AmandaRiu** [comment]
@Garance91540 Are you referring to the device navigation bar? 

![Screenshot_1589492237](https://user-images.githubusercontent.com/5810477/81988668-1500f100-95f9-11ea-9d4f-faa7141b9815.png)

If so, yup, we can update it to always be black. Another option would be to follow the way WPAndroid does it:

Light | Dark 
-- | --
![Screenshot_1589492530](https://user-images.githubusercontent.com/5810477/81989001-acfeda80-95f9-11ea-96bf-85f2e2a5256e.png)|![Screenshot_1589492538](https://user-images.githubusercontent.com/5810477/81989005-ae300780-95f9-11ea-8578-3357c245149f.png)

They use the same color scheme for the gesture based version used in your screenshots as well:
<img src="https://user-images.githubusercontent.com/5810477/81989403-665db000-95fa-11ea-8924-a392e11e7607.png" width="400"/>

**Comment by Garance91540** [comment]
@AmandaRiu I'm referring to the [home indicator/home button](https://d.pr/i/vlyFr8) but this also applies for the navigation bar you shared.

**Comment by AmandaRiu** [comment]
@Garance91540 

> 'm referring to the home indicator/home button but this also applies for the navigation bar you shared.

Cool, that's what I thought :)

> WordPress white bar also works! I just wanted to remove the grey bar for more unity

Awesome! I think it will look really nice in the app.

**Comment by hafizrahman** [comment]
Looking.

**Comment by hafizrahman** [comment]
Done in #3548
