### ISSUE TITLE
Add padding between the banner and the first product on the product list

### ISSUE THREAD

**Issue by Garance91540** [woocommerce/woocommerce-android#2432]
Can we add 8px vertical padding between the "Limited editing available" banner and the first product? 

**Current:**
![Screenshot_20200514-123223](https://user-images.githubusercontent.com/28450084/81948455-0cf97f00-9602-11ea-9ad1-39afa740318c.png)

**Design**
<img width="551" alt="Screen Shot 2020-05-14 at 4 41 38 PM" src="https://user-images.githubusercontent.com/28450084/81948520-1e428b80-9602-11ea-8bcd-a3656dfe062c.png">

**Comment by anitaa1990** [comment]
@Garance91540, thank you so much for filing this issue! I tried replicating this on my test site with the latest changes made in `develop` branch and it looks like the padding issue is fixed, along with the sort and filter option and will be released in the next app update 😄  

<img src="https://user-images.githubusercontent.com/22608780/82019593-269fd280-96a5-11ea-952b-935798e1c027.png" width="300"/>. <img src="https://user-images.githubusercontent.com/22608780/82019602-29022c80-96a5-11ea-80c3-d5fabceaf9c6.png" width="300"/>

**Comment by anitaa1990** [comment]
Closing this issue since it's fixed and scheduled for the next release
