### ISSUE TITLE
Review List: Bottom margin missing if review has no stars

### ISSUE THREAD

**Issue by AmandaRiu** [woocommerce/woocommerce-android#2453]
**Describe the bug**
The bottom margin of a review list item is missing if the review has no stars specified. 

**Screenshots**
<img src="https://user-images.githubusercontent.com/5810477/82366249-25d1ae00-99cf-11ea-8923-cce80b249b26.jpg" width="330"/>

**Expected behavior**
Margin should be visible

**Comment by SiobhyB** [comment]
I'm going to try my hand at this one. :)
