### ISSUE TITLE
Product Details: No sale start date shows inconsistent in the app

### ISSUE THREAD

**Issue by astralbodies** [woocommerce/woocommerce-android#2476]
**Describe the bug**
I have a product with no start date for a sale and an end date set in wp-admin. In the app it shows today's date for the start and when editing the product it shows the end date for the start date.

**To Reproduce**
1. Edit a product in wp-admin and set a sale end date with no start date. 
2. Save the product.
3. Load the product in the app.
4. Review the from date in the product detail screen and in the edit details screen.

**Screenshots**
![Screenshot_20200521-204108](https://user-images.githubusercontent.com/373903/82622842-60d90a80-9ba4-11ea-95cf-af5bb9b9063f.png)

**Expected behavior**
There should be no date set for the start of the sale.

**Isolating the problem (mark completed items with an [x]):**
- [x] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [x] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [x] I can reproduce this bug consistently using the steps above.

**Mobile Environment**
Please include:
- Device: Pixel 2 XL
- Android version: 10
- WooCommerce Android version: 4.3-rc1

**Comment by anitaa1990** [comment]
@astralbodies, I don't think this is a bug but rather a conscious decision from our end. We had discussed with Kylea and G and added logic in both platforms to display the start date to today, if there is no start date set. The discussion for that can be found in `p99K0U-2iz#comment-4592`. Pasting that discussion below:

```
if a start date is not entered, but an end date is entered, the start date would default to today. If a start date is entered but not an end date I would assume they want the sale to last indefinitely from a particular day. 
```

**Comment by astralbodies** [comment]
@anitaa1990 That makes sense. I do like how it's handled on iOS a bit more though - it is less jarring to the user. I was more curious to know how something went on sale today because I didn't edit the product today. On iOS it obscures the start date entirely in the details screen and says "until" the end date:

![IMG_9247](https://user-images.githubusercontent.com/373903/82671902-37040000-9c05-11ea-8838-a002de64c6f3.png)

I think there's still a bug on the editing screen as the start date should be empty when editing, not filled in with the end date.

**Comment by anitaa1990** [comment]
> I think there's still a bug on the editing screen as the start date should be empty when editing, not filled in with the end date.

Good point! Thanks @astralbodies! I tested on the iOS side and found that we need to update the following on the android side: 
- When there is no start date for a sale, it should not be displayed in the product detail screen. (We should display `Until {end date}`.
- When there is no start date for a sale, the start date should be set to the current day in the Pricing screen, **IF the end date is > the start date**. Otherwise, it should be empty.
- When there is no end date for a sale, it should not be displayed in the product detail screen or the pricing screen.
