### ISSUE TITLE
Products: Don't use rich text editor for purchase notes

### ISSUE THREAD

**Issue by rachelmcr** [woocommerce/woocommerce-android#2480]
**Describe the bug**

The designs for editing a product Purchase Note (e.g. in https://github.com/woocommerce/woocommerce-android/issues/2272) don't include a rich text editor. Because the web also doesn't use a rich text editor for purchase notes, we shouldn't offer rich text editing in the app.

Internal ref: p5T066-1j5-p2#comment-4988
@Garance91540 also pinging you here as an FYI in case you want to keep it as-is.

**To Reproduce**

1. Enable Product Editing under Settings > Beta Features.
2. Go to the Products tab.
3. Select a product.
4. Go to the ellipsis menu > Product Settings.
5. Select Purchase Note.

**Screenshots**

Android|iOS|Web
-|-|-
![image](https://user-images.githubusercontent.com/8658164/82684943-5160cc80-9c4b-11ea-89b2-0d56e63ab5b0.png)|![image](https://user-images.githubusercontent.com/8658164/82684958-56be1700-9c4b-11ea-986c-dde14e02edba.png)|![image](https://user-images.githubusercontent.com/8658164/82684966-5aea3480-9c4b-11ea-896b-ccb47532b185.png)

**Mobile Environment**
Please include:
- Device: moto e5 play
- Android version: 8.1.0
- WooCommerce Android version: 4.3-rc-1

**Comment by nbradbury** [comment]
I'm fine to remove this, but wanted to point out that when I coded this I noticed that the web didn't offer rich text, but the actual purchase note after placing an order does.

<img width="483" alt="Screen Shot 2020-05-22 at 12 36 46 PM" src="https://user-images.githubusercontent.com/3903757/82689793-0df56680-9c29-11ea-84fc-609920a54f0c.png">

**Comment by Garance91540** [comment]
I'm ok keeping it as-is, as long as all notes that have rich formatting added in the app can be read well on the web!

**Comment by anitaa1990** [comment]
Should this issue be closed now that we can keep rich editing in purchase notes?

**Comment by nbradbury** [comment]
Yep, I think we can close this.
