### ISSUE TITLE
Add unique id's to username and password fields on login via Site credentials page

### ISSUE THREAD

**Issue by tapanshah21** [woocommerce/woocommerce-android#2515]
**Is your feature request related to a problem? Please describe.**
The username and password fields on the Login via Site credentials page use the same id's i.e. `R.id.input`. This makes automating a simple flow **complex** as we'd be potentially required to use a custom matcher to locate both the fields.

<img width="399" alt="Screen Shot 2020-05-31 at 10 01 06 pm" src="https://user-images.githubusercontent.com/18731379/83599636-09796800-a5b0-11ea-8021-3ac07f1ba031.png">

**Describe the solution you'd like**
From a testability point of view, a simple solution is to add a unique id to both the input fields
`R.id.username` and `R.id.password` would make automating this flow very simple.

**Additional context**
A practice that is becoming increasingly common in the world of web UI automation is adding a unique attribute to an element like `data-test` or `data-uitest` or anything else that is dedicated to locating elements. This means that even if a class name is changed, the test will not fail as the test uses the unique attribute. It also indicates to anyone touching that bit of code, that a particular element is being used for UI testing and they should not change the specific attribute. Now, I am no expert in mobile development, but I feel introducing such a practice could improve the app testability.

**Comment by anitaa1990** [comment]
This has been fixed in the latest trunk version of the app so I'll close this issue
