### ISSUE TITLE
[Product Details] [Shipping] Display weight and size units

### ISSUE THREAD

**Issue by Garance91540** [woocommerce/woocommerce-android#2525]
On the Shipping section of the Product details screen, we should display the weight and dimensions units in the Shipping screen field labels and in the Product details:

Current:
<img width="634" alt="Screen Shot 2020-06-08 at 11 59 04 AM" src="https://user-images.githubusercontent.com/28450084/84017827-82e1d380-a97f-11ea-83c3-c31eea131642.png">

Design:
<img width="726" alt="Screen Shot 2020-06-08 at 11 55 06 AM" src="https://user-images.githubusercontent.com/28450084/84017842-88d7b480-a97f-11ea-8055-46649e6b0315.png">

**Comment by anitaa1990** [comment]
Hey @Garance9154, I was looking into this issue and it looks like we already display the dimension unit for the shipping fields in Product detail and when editing shipping fields.

<img src="https://user-images.githubusercontent.com/22608780/85275515-11854300-b49e-11ea-8c28-4603c8f0ab25.png" width="300"/>. <img src="https://user-images.githubusercontent.com/22608780/85275523-134f0680-b49e-11ea-8779-fc8bc4569ab3.png" width="300"/>

The only cases where we don't really display the units is when we are not able to fetch them from the site 🤔 Would you be able to check the site you used for testing and let me know if you are able to reproduce the issue? I am not able to reproduce the issue using my test site! Thank you 🙇‍♀️

**Comment by Garance91540** [comment]
mmm that's weird I can now see it on my store! Not sure of what changed, but it probably was a bug!

**Comment by anitaa1990** [comment]
Thanks G! It might be for some reason, the dimensions were unavailable and that's the reason the app didn't display it. I'll mark it as closed for now and if you face the issue again or if any of us do, we can always reopen it 🙇‍♀️
