### ISSUE TITLE
v4 Top Performers: Add FluxC API access

### ISSUE THREAD

**Issue by AmandaRiu** [woocommerce/woocommerce-android#2537]
Add the necessary components in FluxC to start using the v4-analytics API to fetch the top products (a.k.a Top Performers): `\wc-analytics\leaderboards`. This endpoint supports the following parameters for a `GET`:
```
"endpoints": [
	{
		"methods": [
			"GET"
		],
		"args": {
			"page": {
				"required": false,
				"default": 1,
				"description": "Current page of the collection.",
				"type": "integer"
			},
			"per_page": {
				"required": false,
				"default": 5,
				"description": "Maximum number of items to be returned in result set.",
				"type": "integer"
			},
			"after": {
				"required": false,
				"description": "Limit response to resources published after a given ISO8601 compliant date.",
				"type": "string"
			},
			"before": {
				"required": false,
				"description": "Limit response to resources published before a given ISO8601 compliant date.",
				"type": "string"
			},
			"persisted_query": {
				"required": false,
				"description": "URL query to persist across links.",
				"type": "string"
			}
		}
	}
],
```

**Comment by ThomazFB** [comment]
Hey @anitaa1990 and @AmandaRiu. There's a lot of points that right now I'm trying to cover around this issue, several points depends if we'll handle those leaderboards flow inside the current `Stats` classes or create a new group of FluxC classes with the `Leaderboards` context. I'm not sure if the Leaderboards are considered some kind of Stats, so I thought it would be best to discuss it here. Here are the points I've taken notes:

1. The `Leaderboards` endpoint URL looks like entirely new to the FluxC, so I would say we need to add the `/leaderboards/` path as a completely different group.

2. Should we create a new WCStore entity for the Leaderboards...maybe? Something like `WCLeaderboardsStore` :thinking:? Or should we handle it as a Stats and implement the requests method into the `WCStatsStore`? At least from the endpoint description, it looks like there are not many parameters to be handled. The downside of using the current `WCStatsStore` is the fact that's a class using the old Dispatcher->Payload->Response flow.

3. We should handle the Rest API calls inside a `RestClient` class, maybe the `OrderStatsRestClient`? Or maybe a new one following a Leaderboard class group? 

4. Following the coroutines implementation pattern, I would say we don't need to declare any kind of Payloads, only a `LeaderboardResponse`, and return it as a `WooPayload`.

5. Should the leaderboards be persisted? If yes, it looks like we'll have the same decision from the previous items to be made, use the current `WCStatsSqlUtils` or create a `WCLeaderboardsSqlUtils`. Nevertheless, I'm guessing that the leaderboard endpoints will be returned as a list of `WCProductModel`, so it would be easy to map those inside the SQLite database with the current code base, but I'm not sure if we should create a new table just for Leaderboards or create some kind of a `Ranking` column on the current Product table.

6. After all this flow, we should finally use the `WooResult` to return the response back to the app.

Let me know your impressions! Thanks a lot for your time! 😬

**Comment by anitaa1990** [comment]
Hey @ThomazFB! Looking at the items you've described it would make more sense to create new entities, classes, rest clients  and stores for the leaderboard implementation. We don't really have anything like this before and leaderboards can include data not strictly related to the old stats `WCStatsStore`. Also it would give us a chance to implement it using Coroutines 😄 We followed the same routine for `Shipping Labels`, `Taxes` and `Refunds` so it's 👍 from me.

**Comment by shiki** [comment]
An API enhancement was requested here. For now, we decided to do a workaround (also discussed in that issue): woocommerce/woocommerce#32274
