### ISSUE TITLE
Broken label in refunds

### ISSUE THREAD

**Issue by 0nko** [woocommerce/woocommerce-android#2563]
A label that should not be visible (it's used in a refund flow) is displayed incorrectly in the Refunded products list.

![Screenshot_1592823403](https://user-images.githubusercontent.com/1522856/85280476-7fbf0b00-b488-11ea-808a-4272e9a12ca6.png)

**To test**
1. Go to Orders
2. Tap on an order with refunded products
3. Tap on the Refunded products button
4. Notice the label shown

**Comment by anitaa1990** [comment]
Closed via #2565
