### ISSUE TITLE
Product card: Remove the "Details" section for manually fulfilled order

### ISSUE THREAD

**Issue by Garance91540** [woocommerce/woocommerce-android#2584]
When an order is manually fulfilled, we display a "Details" section in the Order Details screen. 

I don't really see the benefit of this "Details" screen, it seems like all the information that is shown there is also displayed on the Order Details screen. 

https://d.pr/i/rbi9Gv
https://d.pr/i/Wbr1xI

Are there elements that are only displayed on the Details screen that I am missing? If not, let's remove this screen to align with the "WCS-fulfilled" Order Details screen

**Comment by anitaa1990** [comment]
Addressed in #2878
