### ISSUE TITLE
Vendor admin login when using 'product vendors' plugin

### ISSUE THREAD

**Issue by EmadBustati** [woocommerce/woocommerce-android#2587]
I have installed and enabled Product Vendors plugin from WooCommerce extensions.

When any vendor admin is trying to log in from the app to monitor his products and orders he got this message  "it looks like `my store name` is not a WooCommerce site. 

At the same time, admin or shop manager users can log in from the app.

So what's going wrong and what's I need to fix in order to make vendor admins able to use the app?

**Comment by AmandaRiu** [comment]
Hello @EmadBustati, I'm sorry to hear you are experiencing some issues with login. We'd be happy to help troubleshoot. Please either open a support ticket either via the HELP menu inside the app or by sending an email to mobile-support@woocommerce.com (please be use to include your site URL in the email).
