### ISSUE TITLE
Product settings: add placeholder text for password-protected product

### ISSUE THREAD

**Issue by Garance91540** [woocommerce/woocommerce-android#2608]
Currently, when selecting "Password-protected", there's a blank text input field. Can we add a text label placeholder to guide users more about what they should be doing?
<img width="364" alt="Screen Shot 2020-07-02 at 5 37 18 PM" src="https://user-images.githubusercontent.com/28450084/86379424-1fe81180-bc8b-11ea-9ae1-d95e6dab8ab7.png">

1. Select a product
2. Open product Settings
3. Select "Visibility"
4. Select "Password protected"

**Comment by anitaa1990** [comment]
Closed via #2806
