### ISSUE TITLE
[Product Settings] [Visibility] Remove keyboard after changes are dismissed

### ISSUE THREAD

**Issue by Garance91540** [woocommerce/woocommerce-android#2609]
When I select the password-protected option, edit the field and dismiss my changes, I keep seeing the keyboard overlapping the Settings screen. 

To Reproduce:
1. Select a product
2. Open Product Settings
3. Select "Visibility"
4. Select "Password Protected"
5. Edit Password
6. Select back button
7. Select dismiss changes

![Screenshot_20200702-174147](https://user-images.githubusercontent.com/28450084/86380015-e8c63000-bc8b-11ea-96f8-46c89481e83b.png)

**Comment by anitaa1990** [comment]
Closed via #2806
