### ISSUE TITLE
Orders: Searching for order number doesn't work with # as a prefix in the search

### ISSUE THREAD

**Issue by rachelmcr** [woocommerce/woocommerce-android#2621]
**Describe the bug**

Searching orders for an order number only works if you search for the plain order number (e.g. `123`). The search doesn't return any results if you prefix the order number with a `#` symbol (e.g. `#123`).

**To Reproduce**

1. Open the Orders tab.
2. Tap the search icon to start a search.
3. Search for an existing order number, such as `123`.
4. Verify the search results show that order.
5. Search for the same order number with the `#` symbol included in the search, such as `#123`.
6. Notice that the search doesn't have any results.

**Screenshots**

Search with correct results (no `#`)|Search with incorrect results (with `#`)
-|-
![Screenshot_20200714-130651](https://user-images.githubusercontent.com/8658164/87425307-513ed680-c5d5-11ea-8792-253e79226859.jpg)|![Screenshot_20200714-130659](https://user-images.githubusercontent.com/8658164/87425322-5734b780-c5d5-11ea-8dd3-56056c58a358.jpg)

**Expected behavior**
Since we show the order numbers in the Orders list with the `#` symbol as a prefix, we should also be able to handle searching for orders with the `#` as a prefix.

**Mobile Environment**
Please include:
- Device: moto e5 play
- Android version: 8.1.0
- WooCommerce Android version: 4.6-rc-3

Source: Original report from a public beta tester, reproduced internally (internal ref: p5T066-1o1-p2#comment-5345)

Related iOS issue: https://github.com/woocommerce/woocommerce-ios/issues/2506

**Comment by hafizrahman** [comment]
To echo what @shiki [mentioned here](https://github.com/woocommerce/woocommerce-ios/issues/2506#issuecomment-683100497):

> It looks like searching “#123” in Core also does not return the existing order number 123 in the results. It's just empty. Searching for “123” returns the correct order.

I tested this and the same case still happens in core. Should we maybe just truncate the search keyword if it's started with "#", before sending it to the API?

**Comment by joshbetz** [comment]
> I tested this and the same case still happens in core. Should we maybe just truncate the search keyword if it's started with "#", before sending it to the API?

I would say +1 to removing the # before sending to the API.

**Comment by joshbetz** [comment]
Removed the label to make triaging the API backlog easier, but if there are objections I'm more than happy to discuss.

**Comment by shiki** [comment]
Removing the "#" sounds like a good idea!
