### ISSUE TITLE
Review section gives no empty feedback after list is fully deleted 

### ISSUE THREAD

**Issue by ThomazFB** [woocommerce/woocommerce-android#2623]
**Describe the bug**
If I discard the single last review on the Review List, the UI takes some seconds to refresh with no user feedback, and after that, the list gets empty without the “no review” feedback, only if I pull down to refresh the feedback comes up.

**To Reproduce**
1. Go to the Reviews section
2. Make sure at least one review is available
3. Delete all reviews from the list
4. Verify the UI getting empty without proper feedback for the user

**Screenshots**
| With single review | After the last review is deleted  | Empty list without feedback for the user |
| ------------- | ------------- | ------------- |
| ![Screenshot_20200702-195919_WooCommerce](https://user-images.githubusercontent.com/5920403/87500221-5d0cb600-c632-11ea-94a1-8ffa735ba07f.jpg) | ![Screenshot_20200702-195935_WooCommerce](https://user-images.githubusercontent.com/5920403/87500252-6b5ad200-c632-11ea-9258-86401770d27e.jpg) | ![Screenshot_20200702-195939_WooCommerce](https://user-images.githubusercontent.com/5920403/87500268-731a7680-c632-11ea-882d-b17adf36237b.jpg)

**Expected behavior**
When the review list is empty the following feedback should be presented to the user
<img width="234" alt="Screen Shot 2020-07-15 at 12 35 09 AM" src="https://user-images.githubusercontent.com/5920403/87500600-461a9380-c633-11ea-9e6c-d93163094d72.png">

**Comment by irfano** [comment]
I tested the problem. It seems the problem is fixed already. When the last review is deleted, the expected empty view screen is being presented.

https://user-images.githubusercontent.com/2471769/162448428-6da1a91f-97fe-4841-b859-ca209d83e11e.mp4
