### ISSUE TITLE
Pressing back switches to previous bottom nav tab instead of exiting app

### ISSUE THREAD

**Issue by rachelmcr** [woocommerce/woocommerce-android#2634]
**Describe the bug**

While debugging instrumentation test failures, I noticed that `pressingBackAfterBottomNavOptionChangeExitsApp` currently fails with a legitimate bug (unless the expected behavior has changed).

According to that test, we expect that when you navigate from one tab to another in the bottom nav, and then press back, it will exit the app. However, pressing back currently takes you to the previous tab.

**To Reproduce**
1. Open the app.
2. In the bottom nav, select a different tab to open that section.
3. Press the device back button.
4. Notice that the app doesn't exit; instead, you are taken to the same tab you saw in step 1.

**Comment by anitaa1990** [comment]
Thanks for flagging this issue @rachelmcr! I remember wee changed the behaviour in the app so that when you navigate from one tab to another in the bottom nav, and then press back takes you to the previous tab and will only exit when on the"My Store" tab.

**Comment by rachelmcr** [comment]
Ah, that's great! As long as that was an intentional change, we're ok. We removed the `pressingBackAfterBottomNavOptionChangeExitsApp` test (along with the other instrumentation tests we decided not to keep) so I don't think there's anything more we need to do. I'll close this issue since the app is working as expected.
