### ISSUE TITLE
Orders: Hide shipping address for order with only virtual products

### ISSUE THREAD

**Issue by rachelmcr** [woocommerce/woocommerce-android#2635]
**Describe the bug**

While debugging instrumentation test failures, I noticed that `verifyCustomerInfoCardShippingHiddenWhenProductVirtual` currently fails with a legitimate bug (unless the expected behavior has changed).

When an order contains only virtual products, the shipping address should be hidden. Currently, however:

* if the order has a shipping address, the shipping address is shown.
* if the order doesn't have an address, the shipping details section shows "No address specified."

This matches with the changes made in https://github.com/woocommerce/woocommerce-android/pull/2500, but that PR didn't discuss the expected behavior for orders with only virtual products. (Since I wouldn't _expect_ shipping details on an order for virtual products, I wouldn't expect the shipping details section to be shown in that case.)

@0nko @Garance91540 what do you think the expected behavior should be here?

**To Reproduce**
1. Create a new order with only virtual products.
2. Go to Orders in the app.
3. Select the order in the order list to open its details.
4. Scroll down to the Customer Information section and notice that the Shipping details section still appears there.

**Screenshots**

Current behavior (as shown in https://github.com/woocommerce/woocommerce-android/pull/2500 - e.g. when the order has no shipping address):
<img width="300" src="https://user-images.githubusercontent.com/1522856/83137167-fb77a300-a0e8-11ea-8343-2c8be3408a5d.png">

Previous behavior (as shown in https://github.com/woocommerce/woocommerce-android/pull/1171 - only billing info is shown):
<img width="300" src="https://user-images.githubusercontent.com/22608780/60489774-c7221980-9cc2-11e9-8d2f-96bca92b04e1.png">

**Comment by Garance91540** [comment]
Hi @rachelmcr ! When the product is virtual, we should hide the shipping address section on the Product page as you mentioned.

**Comment by anitaa1990** [comment]
It looks like this got fixed during the Order detail refactor. I am no longer seeing the Shipping address section if the order contains only virtual products.

<img src="https://user-images.githubusercontent.com/22608780/97000688-b733e600-1554-11eb-92af-df70d0efb596.png" width="300"/>. <img src="https://user-images.githubusercontent.com/22608780/97000569-85228400-1554-11eb-8701-15b4152a4ba2.png" width="300"/>
