### ISSUE TITLE
Orders: Extra divider appears in billing section with partial billing details

### ISSUE THREAD

**Issue by rachelmcr** [woocommerce/woocommerce-android#2636]
**Describe the bug**

While debugging instrumentation test failures, I noticed that `verifyOrderDetailCardViewWithBillingPhonePopulatedSuccessfully` currently fails with a legitimate bug.

When an order has only partial billing details (no email address) an extra divider appears between the billing details and the "Hide billing" section.

**To Reproduce**
1. Create an order with no billing email address.
2. Go to the Orders tab in the app.
3. Select the order in the order list to open the details.
4. Scroll down to the "Customer information" section.
5. Tap on "Show billing" to view the billing details.
6. Notice there's a double divider line at the bottom of the billing details. This doesn't appear if the billing details include an email address.

**Screenshots**

Expected behavior (with all billing details) | No billing email | No billing email or phone
-|-|-
![Screenshot_20200722-174321](https://user-images.githubusercontent.com/8658164/88204896-e2502600-cc43-11ea-8a3a-b04c3e8f00ae.jpg)|![Screenshot_20200722-174410](https://user-images.githubusercontent.com/8658164/88204919-eb40f780-cc43-11ea-90b9-adf26fee083d.jpg)|![Screenshot_20200722-174433](https://user-images.githubusercontent.com/8658164/88204924-eda35180-cc43-11ea-924c-7320f2b4ad54.jpg)

**Comment by 0nko** [comment]
Can't reproduce anymore.
