### ISSUE TITLE
Graph/asset bleed between screens

### ISSUE THREAD

**Issue by AmandaRiu** [woocommerce/woocommerce-android#2637]
While monitoring the app store reviews I've noticed several reports of the graph from the "My Store" tab still being visible while switching tabs and having other assets bleed (stay visible) between screens. There haven't been any official tickets opened yet but it definitely looks like something we should look into. I'm thinking maybe we need to set the background to `@color/color_surface` on the main fragments.

**Comment by anitaa1990** [comment]
This was fixed a while back in #3311 and #3395 so closing this one!
