### ISSUE TITLE
[IAFeedback] Add Tracking

### ISSUE THREAD

**Issue by shiki** [woocommerce/woocommerce-android#2638]
Part of the In-app Feedback project. Ref p91TBi-2RL-p2.

Add Tracks events and track them when the following scenarios happen. 

### Prompt

This prompt is shown only after the user has passed some conditions (e.g. 3 months usage). See p91TBi-2Af-p2 for the conditions. 

<img src="https://user-images.githubusercontent.com/198826/88227116-57aefd00-cc2a-11ea-80e3-c7e0e8428881.png" width="240">

Event Name | Trigger | Custom Properties
--------|-------|---
`app_feedback_prompt`  |  When the “Enjoying the WooCommerce app?” and the buttons are displayed to the user. | `action="shown"`
`app_feedback_prompt` | When the **I Like It** button is activated. | `action="liked"`
`app_feedback_prompt` | When the **Could Be Better** button is activated. | `action="didnt_like"`

### Dialog

This dialog is shown after activating the **I Liked It** button. 

<img src="https://user-images.githubusercontent.com/198826/88228701-c9884600-cc2c-11ea-94ce-dbabbc74f444.png" width="240">

Event Name | Trigger | Custom Properties
--------|-------|----
`app_feedback_rate_app` | When the **Later** button is activated. | `action="later"`
`app_feedback_rate_app` | When the **No Thanks** button is activated. | `action="declined"`
`app_feedback_rate_app` | When the **Rate Now** button is activated. | `action="rated"`

### Survey Screen

This screen is shown after activating the **Could Be Better** button. 

<img src="https://user-images.githubusercontent.com/198826/88229532-1fa9b900-cc2e-11ea-9419-c95fb991ea87.png" width="240">

Event Name | Trigger | Custom Properties
--------|-------|---
`survey_screen` | When the screen is shown. | `context="general"` <br> `action="opened"`
`survey_screen` | When the user closes the screen without finishing the survey.  | `context="general"` <br> `action="canceled"`

### Survey Completion Screen

This screen is shown when the user successfully submitted the answers to the survey.

<img src="https://user-images.githubusercontent.com/198826/88229663-597abf80-cc2e-11ea-9f9e-e737bb94bfcd.png" width="240">

Event Name | Trigger | Custom Properties
--------|-------|---
`survey_screen` | When this survey completion screen is shown.  | `context="general"` <br> `action="completed"`

### Banner

This banner is shown for WIP features. The Products feature is just an example and we might have similar banners for other features in the future. 

<img src="https://user-images.githubusercontent.com/198826/88230329-75329580-cc2f-11ea-9b74-19fb4bc0381d.png" width="240">

Event Name | Trigger | Custom Properties
--------|-------|--
`feature_feedback_banner` | When the **Give Feedback** button is activated. | `context="products_m3"` <br> `action="gave_feedback"`
`feature_feedback_banner` | When the **Dismissed** button is activated. | `context="products_m3"` <br> `action="dismissed"`

### Survey

The survey screen flow is shown after pressing the **Give Feedback** button. The survey flows similarly to the App Feedback Survey. The same event names are used but with different custom property values. 

Starting Screen | Completion Screen
--------|-------
<img src="https://user-images.githubusercontent.com/198826/88231289-34d41700-cc31-11ea-8901-83743ba54414.png" width="240">        |       <img src="https://user-images.githubusercontent.com/198826/88231311-40274280-cc31-11ea-9c2a-4f8e7cdc0e7f.png" width="240">

Event Name | Trigger | Custom Properties
--------|-------|---
`survey_screen` | When the survey screen is shown. | `context="products_m3"` <br> `action="opened"`
`survey_screen` | When the user closes the survey screen without finishing the survey.  | `context="products_m3"` <br> `action="canceled"`
`survey_screen` | When this survey completion screen is shown.  | `context="products_m3"` <br> `action="completed"`

---

Corresponding iOS issue: https://github.com/woocommerce/woocommerce-ios/issues/2548

**Comment by AmandaRiu** [comment]
@shiki These look good to me!

**Comment by AmandaRiu** [comment]
@shiki Updated versions are even better!! 💯

**Comment by shiki** [comment]
@ThomazFB I renamed `context="products"` to `context="products_m3"` since that one is supposed to be very specific. And we might confuse ourselves in the future about what `"products"` means. 😬
