### ISSUE TITLE
Add warning to variation detail and variations list when price is missing

### ISSUE THREAD

**Issue by 0nko** [woocommerce/woocommerce-android#2680]
There are some design changes on the variation for and variation list:

## Variation detail

- [x] Change the title of the visibility switch to "Enabled"/"Disabled"
- [x] Make the whole visibility row clickable
- [x] If a variation is enabled but doesn't have a price set, let's update the following:
  - [x] update the price row to be warning color "Add Price" 
  - [x] add a warning banner row below

<img width="300" src="https://user-images.githubusercontent.com/1522856/89502330-1d666380-d7c5-11ea-964f-b8821802cc13.png">

## Variations list

- [ ] Update variation item UI based on the follow states:
  - Variation is disabled: "Disabled" is shown instead of "Hidden"
  - Variation is enabled and has a price: the price is shown as before
  - Variation is enabled but doesn't have a price: "No price set" is shown in warning color
- [x] Add a warning banner on top of the variations if there are any variations without a price set

<img width="300" src="https://user-images.githubusercontent.com/1522856/89502481-5bfc1e00-d7c5-11ea-862e-2512e5890fba.png">

**Comment by anitaa1990** [comment]
@0nko is this issue completed? I see the below tasks already completed in the app but you might have more context 😅 :
- Variation is disabled: "Disabled" is shown instead of "Hidden"
- Variation is enabled and has a price: the price is shown as before
- Variation is enabled but doesn't have a price: "No price set" is shown in warning color

**Comment by 0nko** [comment]
Yes, all of those are done. It's weird the issue's still open since `Fixes #2680` should automatically close it 🤷.
