### ISSUE TITLE
Products: Adding new products

### ISSUE THREAD

**Issue by 0nko** [woocommerce/woocommerce-android#2706]
As part of the M4 release, we should be able to add new products:

- [x] [Simple product](https://github.com/woocommerce/woocommerce-android/issues/2707)
- [ ] Variable product
- [ ] Grouped product
- [ ] [External product](https://github.com/woocommerce/woocommerce-android/issues/2906)

![image](https://user-images.githubusercontent.com/1522856/89677035-f5721f80-d8ec-11ea-9714-2af59dc9c826.png)

**Comment by anitaa1990** [comment]
Closed via #2906 and #2842.
