### ISSUE TITLE
Products: Add a new Simple product

### ISSUE THREAD

**Issue by 0nko** [woocommerce/woocommerce-android#2707]
![image](https://user-images.githubusercontent.com/1522856/89677481-d0ca7780-d8ed-11ea-8100-5ccf264f0f26.png)

After tapping on the FAB in the product list and choosing the Simple product type as pictured above, we want to be able to show an empty product detail screen where the users will be able to fill out the product information:

<img width="300" src="https://user-images.githubusercontent.com/1522856/89677570-f8b9db00-d8ed-11ea-8a08-43c503b2e1d9.png" />

Tapping on the product image placeholder will open up the media picker.

The **Add more details** button will show a bottom sheet with the list of following options available to add:

<img width="300" src="https://user-images.githubusercontent.com/1522856/89677994-ae852980-d8ee-11ea-8ac0-10ec0ff71a07.png" />

Tapping on any detail type will open up the respective edit screen. Finally, clicking on the Publish toolbar button will save the new product.

**Comment by anitaa1990** [comment]
Closed via #2842
