### ISSUE TITLE
Stats: Refunded order appears as negative orders/spend in Top Performers section

### ISSUE THREAD

**Issue by rachelmcr** [woocommerce/woocommerce-android#2724]
**Describe the bug**

If a product shows up in my Top Performers list but was refunded, the "total orders" and "total spend" for the product appear as negative values instead of 0 even if both the purchase and refund happened in that time period (so the net performance was 0 orders and 0 spend).

**To Reproduce**

1. Receive orders for a product, putting it in your Top Performers section. (I happened to see this on a day where I had orders for only 3 different products, so all 3 products were Top Performers for the day.)
2. Refund the orders for that product.
3. Check My Store > Top Performers in the app and notice the negative values for total orders and total spend on that product.

**Screenshots**

WC Admin (web)|Woo Android (app)
-|-
![Screen Shot 2020-08-13 at 2 10 12 PM](https://user-images.githubusercontent.com/8658164/90138333-c0dbe900-dd6e-11ea-9efa-c55886e914f8.png)|![Screenshot_20200813-140250](https://user-images.githubusercontent.com/8658164/90138389-d7824000-dd6e-11ea-9919-5379e553ba4c.jpg)

**Expected behavior**
I expect the orders and spend to be 0 (matching WC Admin), at least if the order and the refund happened in the same time period. (Ultimately I wouldn't really expect a product that only had refunds to appear in the top performers section, but that might require changes in WC Admin as well since it also appears there.)

**Mobile Environment**
Please include:
- Device: moto e5 play
- Android version: 8.1.0
- WooCommerce Android version: 4.8-rc-1

**Comment by AmandaRiu** [comment]
NOTE: Top Performers is actively being reworked to use the new WCAdmin endpoints (right now it doesn't match the web because it's using the old endpoints to fetch the stats data). This change should be complete by the end of this sprint (4.9). [Here's the relevant issue](https://github.com/woocommerce/woocommerce-android/issues/2538).

**Comment by rachelmcr** [comment]
Ah, that's right, thanks! I confirmed that iOS shows the expected values (with the related updates to the WCAdmin endpoints), so I expect that this will be fixed once the change is complete in Android. I can retest to confirm next sprint, if needed.

**Comment by anitaa1990** [comment]
Tested this issue with the steps provided by Rachel after the changes to the top performers using WC admin endpoints and it works as expected 👍
