### ISSUE TITLE
Disable product type editing for custom types

### ISSUE THREAD

**Issue by 0nko** [woocommerce/woocommerce-android#2778]
Some product types cannot be changed and produce an error. The API doesn’t know about this constraint and we can still change the product type to a core product type in the app. The editing should therefore be disabled for these.

![image](https://user-images.githubusercontent.com/1522856/91203557-73af2e00-e703-11ea-9209-bc228278660a.png)

**Comment by nbradbury** [comment]
This is fixed as part of #3022.
