### ISSUE TITLE
Products: Product Type selector shows wrong options for product type

### ISSUE THREAD

**Issue by rachelmcr** [woocommerce/woocommerce-android#2781]
**Describe the bug**

I expect to have four options for a product type:

* Simple
* Variable
* Grouped
* External

However, right now the product type selector always shows these four options:

* Physical
* Virtual
* Grouped
* External

A few issues with this:

1. Based on the designs, Physical and Virtual should be grouped as Simple in the product type selector. I should be able to switch a simple product between physical and virtual using the virtual product option in Product Settings.
2. I never see the Variable option, so I can't change a product to variable.
3. I can see and select the current product type in that selector. I get a prompt asking me if I'm sure I want to change the product type, even though it doesn't actually change anything if I'm choosing the current product type.

**To Reproduce**

1. Go to Settings > Beta Features and enable Product Editing.
2. Go to the Products tab.
3. Open a simple product.
4. Tap on Product Type. Notice you see Physical and Virtual (instead of Simple) and Variable is not in the list.
5. Select the same product type (for example, if it's a physical product choose Physical).
6. Notice you get an "Are you sure you want to change the product type?" prompt. Select "Yes, change." Notice nothing changes.

**Screenshots**

Example of the product type selector for a simple, physical product:

<img src="https://user-images.githubusercontent.com/8658164/91321987-1f658600-e7b7-11ea-99d0-4063e985ff3b.jpg" width="300px">

**Mobile Environment**
Please include:
- Device: moto e5 play
- Android version: 8.1.0
- WooCommerce Android version: 4.9-rc-1

**Comment by anitaa1990** [comment]
Closed via #2791

**Comment by rachelmcr** [comment]
Reopening this issue since @jaclync observed that it's a problem again in the 5.2 beta. Is it possible the fix in 4.9 didn't get merged back?

**Comment by anitaa1990** [comment]
Opened a fix #2997 targeting the release branch. Thanks for flagging this @jaclync and @rachelmcr

**Comment by anitaa1990** [comment]
> I can see and select the current product type in that selector. I get a prompt asking me if I'm sure I want to change the product type, even though it doesn't actually change anything if I'm choosing the current product type.

☝️ one has also been reverted but since this is not a "critical" change I thought of opening a new PR just to fix this issue, targeting the `develop` branch.

**Comment by shiki** [comment]
@anitaa1990 Are you still planning on working on this or would you like to unassign yourself for now? 🙂

**Comment by anitaa1990** [comment]
Dup of #3904
