### ISSUE TITLE
Products: Show inventory card for variable product

### ISSUE THREAD

**Issue by rachelmcr** [woocommerce/woocommerce-android#2784]
**Describe the bug**

I noticed that variable products don't have an Inventory section at the product detail level, only at the variations level. It looks like that was intentionally disabled in https://github.com/woocommerce/woocommerce-android/issues/1563, but core has Inventory settings (including SKU and Manage Stock settings) at the parent product level:

<img src="https://user-images.githubusercontent.com/8658164/91332178-af113180-e7c3-11ea-8d1e-5c7743444c06.png" width="450px">

In core, when I don’t have that Inventory > Manage Stock setting enabled at the parent product level, I then have the option to change the stock status for a variation on the web:

<img src="https://user-images.githubusercontent.com/8658164/91332188-b3d5e580-e7c3-11ea-9d2e-7ade3e39318a.png" width="450px">

It would be good to match the core behavior here, and show the inventory card at the variable parent product level. We can then allow stock status to be managed at the variation level based on that product-level settings, like in core.

**Mobile Environment**
Please include:
- Device: moto e5 play
- Android version: 8.1.0
- WooCommerce Android version: 4.9.0.0

**Comment by 0nko** [comment]
Fixed by #2899.
