### ISSUE TITLE
Products: "View Product in Store" link disappears after navigating beyond product details

### ISSUE THREAD

**Issue by rachelmcr** [woocommerce/woocommerce-android#2785]
**Describe the bug**

When I first open the product details for a product, if that product is visible on my store I'll see a "View Product in Store" link in the ellipsis menu.

However, after I view the Product Settings or open one of the cards in the product details (e.g. Price, Inventory, Shipping), when I go back to the product details screen I no longer see "View Product in Store" even if I haven't changed any product details or settings.

**To Reproduce**

1. Open the Products tab.
2. Select a product.
3. Tap the ellipsis menu and confirm you see a "View Product in Store" link.
4. Select "Product Settings."
5. Tap the X button to close the product settings screen without making any changes.
6. Tap the ellipsis menu again and notice you no longer see the "View Product in Store" link.

You can repeat the steps above, but at step 4 open any card on the product details screen (e.g. Price, Inventory, Shipping) and get the same results.

**Screenshots**

Product details ellipsis menu (first view)|Product details ellipsis menu after opening product settings
-|-
![Screenshot_20200826-175647](https://user-images.githubusercontent.com/8658164/91333585-ac174080-e7c5-11ea-9b10-b7a6bae3b819.jpg)|![Screenshot_20200826-175652](https://user-images.githubusercontent.com/8658164/91333584-aae61380-e7c5-11ea-90d6-8d3b69eb93ad.jpg)

**Mobile Environment**
Please include:
- Device: moto e5 play
- Android version: 8.1.0
- WooCommerce Android version: 4.9-rc-1

**Comment by anitaa1990** [comment]
Closed via #2806
