### ISSUE TITLE
Product details: Add "No variations" warning

### ISSUE THREAD

**Issue by 0nko** [woocommerce/woocommerce-android#2789]
Display a message when a variable product doesn't contain any variations.

**Comment by anitaa1990** [comment]
@0nko, I remember we had already implemented this option in the app but wanted to confirm with you. Should we close this issue?

**Comment by 0nko** [comment]
Actually we haven't implemented adding variable products/variations is not enabled/implemented in M3 and we decided to move it to M4, if I remember correctly.

**Comment by nbradbury** [comment]
@0nko Is there a design for this? I was going to tackle this one but I wasn't sure how & where the message should be shown.

**Comment by 0nko** [comment]
There's screen with a button. So I guess you could just hide it for now and modify the message a bit:

![image](https://user-images.githubusercontent.com/1522856/95454471-cd468180-096c-11eb-85ee-68d4c1d6e4ab.png)

**Comment by 0nko** [comment]
@nbradbury I just found that there already exists an empty view that wasn't being used since the _Variations_ property was not displayed if there were no variations.

**Comment by nbradbury** [comment]
@0nko I'm not sure what you mean. Does that mean we should close this?

**Comment by anitaa1990** [comment]
@0nko @nbradbury, this looks to be already implemented in the app. I tested by clicking on a variable product that does not have any variations:

<img src="https://user-images.githubusercontent.com/22608780/98664854-e9c14980-2370-11eb-8a08-6c11a9843bd2.png" width="300"/>. <img src="https://user-images.githubusercontent.com/22608780/98664862-ec23a380-2370-11eb-8d2e-484b870ed9c8.png" width="300"/>

I'm closing this issue but feel free to open it in case this issue refers to something other than what I had mentioned ☝️
