### ISSUE TITLE
Shipment tracking: Show option to add tracking in order details if plugin is available

### ISSUE THREAD

**Issue by rachelmcr** [woocommerce/woocommerce-android#2800]
**Describe the bug**

In the 4.8 release I noticed that I’m not seeing the Add shipment tracking section in the order details, even if my store has the Shipment Tracking plugin/extension. I only see the Add shipment tracking section in the order fulfillment screen.

There was a bug fix in https://github.com/woocommerce/woocommerce-android/pull/2673 to remove that from order details if there aren't any shipment trackings to display. But in https://github.com/woocommerce/woocommerce-android/pull/2396 (included in the 4.3 release), we intentionally added Shipment Tracking to the order detail screen even if there aren’t any trackings for the order.

We should display the Add Tracking section in Order detail, when the plugin is available. (But still hide it whenever the plugin isn't available.)

Internal ref: p5T066-1so-p2#comment-5575

I noticed this is still an issue in the 4.9 beta. cc @anitaa1990

**Comment by anitaa1990** [comment]
Closed via #2807
