### ISSUE TITLE
Products: M3 banner message always visible, even when beta (M3) features are disabled

### ISSUE THREAD

**Issue by rachelmcr** [woocommerce/woocommerce-android#2802]
**Describe the bug**

As described in https://github.com/woocommerce/woocommerce-android/pull/2756, by default (when Product Editing is disabled under Settings > Beta Features) when you go to the Products tab --> the top banner should show the M2 messaging (`We've added more editing functionalities to products! You can now update images, see previews and share your products.`)

However, the M3 messaging always appears instead (`You can now edit grouped, external and variable products, ...`).

**To Reproduce**

1. Go to Settings > Beta Features and make sure Product Editing is disabled.
2. Go to the Products tab.
3. Expand the banner at the top of the screen and check the message there.

**Mobile Environment**
Please include:
- Device: moto e5 play
- Android version: 8.1.0
- WooCommerce Android version: 4.9-rc-2

**Comment by anitaa1990** [comment]
Closed via #2824
