### ISSUE TITLE
App not showing Turkish city names

### ISSUE THREAD

**Issue by rossanafmenezes** [woocommerce/woocommerce-android#2820]
**Describe the bug**

User is seeing cities' license plate code instead of the Turkish real city name in the WC app. For example

34 instead of Istanbul
06 instead of Ankara
01 instead of Adana.

This does not happen on WP-Admin

**To Reproduce**

1 - Go to a test site 

2 - select a product and proceed to checkout

3 - use a Turkish address (I used the one for the Museum of Anatolian Civilizations 
Kale, Gözcü Sk. No:2, 06240 Ulus/Altındağ/Ankara, Turkey)

4 - on the app, check the new orders and the billing and/or shipping information

**Screenshots**

This one is from the user (the entire screen is on the ticket but I cropped this part so it does not show everything)

![Screenshot on 2020-09-03 at 09_11_16](https://user-images.githubusercontent.com/30724184/92120522-2b5cd380-edc7-11ea-8de1-08004e60eabb.png)

This one is from my fake purchase on my test site:

![IMG_20200903_093138_541](https://user-images.githubusercontent.com/30724184/92121442-4aa83080-edc8-11ea-9ddd-a01268619d64.jpg)

**Expected behavior**

I expected the app to show the city name just like it does on the browser as opposed to a code, which according to the user is their licence's plates codes.

**Isolating the problem (mark completed items with an [x]):**
- [ x ] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [ x ] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [ x ] I can reproduce this bug consistently using the steps above.

**Mobile Environment**
Please include:
My test:
- Device: Pixel 2
- Android version: 10
- WooCommerce Android version: 4.9-rc-3

User's 👍  

- Device: xiaomi mi note 10 lite
- Android version:  Did not say, asking again
- WooCommerce Android version: 4.9-rc-2

3255763-zen

**Comment by azollafox** [comment]
User's devices is Android Version 10
