### ISSUE TITLE
Unified login: SIWA

### ISSUE THREAD

**Issue by AmandaRiu** [woocommerce/woocommerce-android#2883]
Add support for signing in with an Apple ID. This also includes creating a new account if there isn't a matching WPcom account found. 

![Continue with Apple - Returning Apple ID usersiwa](https://user-images.githubusercontent.com/5810477/93812221-4c268500-fc1f-11ea-8b87-d305b1db0653.png)

**Comment by AmandaRiu** [comment]
It looks like at least for now we may not implement this flow in WCAndroid.

**Comment by shiki** [comment]
I'm cleaning the backlog. 😄 It's probably best to close this issue for now since we don't have plans to work on it yet. We can reopen when we do.
