### ISSUE TITLE
Add the ability to delete (trash) a product

### ISSUE THREAD

**Issue by nbradbury** [woocommerce/woocommerce-android#2889]
Users need the ability to send a product to the trash. Note that the trash menu item should only be shown when product detail is called from the product list. Designs below.

![trash](https://user-images.githubusercontent.com/3903757/93865089-d4467200-fc93-11ea-83ab-2ae1febd7c18.png)

[Related FluxC issue](https://github.com/wordpress-mobile/WordPress-FluxC-Android/issues/1695)

**Comment by astralbodies** [comment]
Moved this to release 5.
