### ISSUE TITLE
Refactor order detail sub screens to MVVM

### ISSUE THREAD

**Issue by anitaa1990** [woocommerce/woocommerce-android#2892]
The Order detail screen has been refactored to MVVM and the only sub screens that are pending a refactor is the
- Add Order note fragment
- Add shipment Tracking fragment

**Comment by hichamboushaba** [comment]
Progress so far:
- [x] AddOrderNoteFragment #3288 
- [x] AddOrderShipmentTrackingFragment #3306 
- [x] AddOrderTrackingProviderListFragment #3315
