### ISSUE TITLE
Unified Login: Store address login flow refers to "site address" instead of "store address"

### ISSUE THREAD

**Issue by rachelmcr** [woocommerce/woocommerce-android#2894]
**Describe the bug**

After selecting the "Enter your store address" option for login, I expect to see consistent references to my "store address" in the UI but instead some text refers to my "site address" (the terminology used in the WordPress login flow).

**To Reproduce**

1. Start logged out of the app.
2. Tap the "Enter your store address" button.
3. Notice the field is called "Site address" (not "Store address").
4. Notice the link says "Find your site address" (not "Find your store address").
5. Tap the "Find your site address" link and notice the modal copy consistently refers to the "site" and "site address." (I don't see this modal in the unified login designs but I expect the copy to be consistent with the other screen.)

**Screenshots**

Design:
(Note: It looks like the email address and text at the top of the screen are not what's expected here, but this design does show the term "store address" rather than "site address" for the field and link.)

<img src="https://user-images.githubusercontent.com/8658164/94000221-c9bcd300-fd8e-11ea-887c-028fd75274f4.png" width="300px">

Actual:

<img src="https://user-images.githubusercontent.com/8658164/94000237-cfb2b400-fd8e-11ea-9207-861b773d4525.png" width="300px">
<img src="https://user-images.githubusercontent.com/8658164/94000240-d17c7780-fd8e-11ea-9a13-327ba8a1c230.png" width="300px">

**Mobile Environment**
Please include:

- Device: moto e5 play
- Android version: 8.1.0
- WooCommerce Android version: 5.1-rc-1

cc @AmandaRiu

**Comment by AmandaRiu** [comment]
Fixed in #2917. Closing ticket.
