### ISSUE TITLE
Unified Login: Missing styles on the contact support name/email dialog (or incorrect dialog shown) from store address screen

### ISSUE THREAD

**Issue by rachelmcr** [woocommerce/woocommerce-android#2895]
**Describe the bug**

When contacting support during login, you have to enter your personal details (email or name/email) before writing your message to support. Tapping "Find your site address" (on the store address screen) > "Need more help?" opens a dialog asking for your name and email, but it's missing styles so it's hard to see the text entry fields.

**To Reproduce**

1. Start logged out of the app. (It can also help to start with a fresh install of the app, to ensure you're asked for your contact details.)
2. Tap the "Enter your store address" button.
3. Tap the link that says "Find your site address."
4. In the modal that appears, tap "Need more help?"
5. Notice that the dialog has "Name" and "Email" fields but those fields aren't outlined so it's hard to know where to tap to enter those details.

**Screenshots**

<img src="https://user-images.githubusercontent.com/8658164/94002495-df7fc780-fd91-11ea-868d-594c97a61335.jpg" width="300px">

**Expected behavior**

In most cases during login, you are directed to the Help & support screen > tap "Contact support" > see "Please enter your email address" dialog (asking for only your email address).

<img src="https://user-images.githubusercontent.com/8658164/94002508-e3abe500-fd91-11ea-97fb-c91a8004ea4d.jpg" width="300px">

Ways to get to that flow:

* Tap the (?) in the top right during login.
* Select "Enter your store address" > Enter your store address > tap "Find your connected email" > tap "Need more help?"

I'd expect the same in this case, so tapping "Find your site address" > "Need more help?" should redirect to the Help & support screen. Otherwise, though, the name/email dialog that appears should have styles that outline those fields.

**Mobile Environment**
Please include:
- Device: moto e5 play
- Android version: 8.1.0
- WooCommerce Android version: 5.1-rc-1

cc @AmandaRiu

**Comment by AmandaRiu** [comment]
This one must've been fixed somewhere along the way when different styles were added. Closing ticket. 
<img src="https://user-images.githubusercontent.com/5810477/102143959-b885de80-3e32-11eb-861c-1d703c6ec95c.png" width="320"/>
