### ISSUE TITLE
Unified Login: Text and buttons overlap/don't scroll on "Enter email address" screen in landscape on small device screens

### ISSUE THREAD

**Issue by rachelmcr** [woocommerce/woocommerce-android#2897]
**Describe the bug**

This bug occurs on small devices in landscape view:

On the "Enter email address" screen in the store address login flow, the "Find your connected email" link overlaps with the "Continue" button:

* When "Continue" is disabled, the link is visible but doesn't respond to taps.
* When "Continue" is enabled, the link is hidden by the button and the screen doesn't scroll to view/tap it.

**To Reproduce**

1. Use a device with a small screen size, and rotate the device to landscape.
2. Start logged out of the app.
3. Select "Enter your store address."
4. Enter your store address and select "Continue."
5. On the "Enter email address" screen, try to tap the "Find your connected email" link. Notice it overlaps the disabled "Continue" button and doesn't respond to taps.
6. Enter your email address. Notice the "Continue" button is now enabled and the "Find your connected email" link is not visible.
7. Try to scroll the screen to view that link and notice it doesn't scroll.

**Screenshots**

<img src="https://user-images.githubusercontent.com/8658164/94006264-80bd4c80-fd97-11ea-8e8f-dac4c408c98d.jpg" width="500px">
<img src="https://user-images.githubusercontent.com/8658164/94006266-81ee7980-fd97-11ea-9ddd-94c7f2b78b22.jpg" width="500px">

**Mobile Environment**
Please include:
- Device: moto e5 play
- Android version: 8.1.0
- WooCommerce Android version: 5.1-rc-1

cc @AmandaRiu

**Comment by AmandaRiu** [comment]
Fixed in #2916. Closing ticket.
