### ISSUE TITLE
Unified Login: Login doesn't proceed past username/password screen after being redirected there from email/password login

### ISSUE THREAD

**Issue by rachelmcr** [woocommerce/woocommerce-android#2900]
**Describe the bug**

If I try to log in with my email and password, and I'm redirected to log in with my username and password instead, I can't proceed past that screen. I enter my username/password, and the app gets stuck on the "Logging in" dialog. The only way to proceed is to force-close the app and reopen it.

**To Reproduce**

1. Start logged out.
2. Select "Continue with WordPress.com."
3. Enter the email address for a WordPress.com account that isn't allowed to log in with its email address. (Ping me in Slack if you need details about that scenario or a test account to use for it.)
4. Select the "Or type your password" option.
5. Enter your account password and tap "Continue."
6. Notice you're redirected to log in with your username and password.
7. Enter your username and password, and tap "Continue."
8. Notice the "Logging in" dialog appears and the app doesn't proceed past this point.

At this point the only solution is to force-close the app and reopen it, and then you can proceed.

**Screenshots**

<img src="https://user-images.githubusercontent.com/8658164/94008686-52417080-fd9b-11ea-8daf-b1c3f31cedd6.jpg" width="300px">

**Mobile Environment**
Please include:
- Device: moto e5 play
- Android version: 8.1.0
- WooCommerce Android version: 5.1-rc-1

cc @AmandaRiu

**Comment by AmandaRiu** [comment]
Fixed in #2910. Closng.
