### ISSUE TITLE
Unified Login: App switcher shows blue header during login

### ISSUE THREAD

**Issue by rachelmcr** [woocommerce/woocommerce-android#2901]
**Describe the bug**

If I'm in the login flow and I open my device's app switcher, the WooCommerce app shows a blue header color instead of purple.

**To Reproduce**

1. Start logged out of the app.
2. Open your device app switcher, as if to switch to another app.
3. Notice the header color is blue.

**Screenshots**

<img src="https://user-images.githubusercontent.com/8658164/94009306-2e325f00-fd9c-11ea-93f9-75fc042c6c3f.jpg" width="300px">

**Mobile Environment**
Please include:
- Device: moto e5 play
- Android version: 8.1.0
- WooCommerce Android version: 5.1-rc-1

cc @AmandaRiu

**Comment by AmandaRiu** [comment]
This is fixed. Closing.
