### ISSUE TITLE
Unified Login: Incorrect error message and overlapping buttons after entering email that doesn't match a WordPress.com account

### ISSUE THREAD

**Issue by rachelmcr** [woocommerce/woocommerce-android#2902]
**Describe the bug**

If I try to log in to a WordPress.com account, but I enter an email address that doesn't match a WordPress.com account, I get the following error:

> Hmmm, we can't find a WordPress.com account connected to this email address. Try the link below to log in using your site address.

However, there is no "link below" for site address login.

If I then tap back into the email field (at least on a small screen), and the keyboard comes up, the "Continue" and "Continue with Google" buttons overlap.

**To Reproduce**

1. Start logged out.
2. Select "Continue with WordPress.com."
3. Enter an email address that doesn't match a WordPress.com account and select "Continue."
4. Notice the error message includes instructions that don't match the options on screen.
5. Tap in the email address field and notice the buttons now overlap at the bottom of the screen (at least on a small device screen).

**Screenshots**

<img src="https://user-images.githubusercontent.com/8658164/94010770-499e6980-fd9e-11ea-870a-8a082e87df96.jpg" width="300px">
<img src="https://user-images.githubusercontent.com/8658164/94010772-4acf9680-fd9e-11ea-98b7-d173caf8bad2.jpg" width="300px">

**Mobile Environment**
Please include:
- Device: moto e5 play
- Android version: 8.1.0
- WooCommerce Android version: 5.1-rc-1

cc @AmandaRiu

**Comment by AmandaRiu** [comment]
Fixed in #2915 Closing ticket.
