### ISSUE TITLE
Products: Save as Draft option

### ISSUE THREAD

**Issue by ThomazFB** [woocommerce/woocommerce-android#2905]
Whenever a user is under the creation of a new product, we should make available the option to save the current creation as Draft. 

<img width="398" alt="image" src="https://user-images.githubusercontent.com/5920403/94098252-9dd93600-fdfe-11ea-9dee-16d79692529a.png">

**Comment by ThomazFB** [comment]
Hey @astralbodies, in order to reflect what was discussed around the Products M4, I'm moving this issue to the M4 board.

**Comment by nbradbury** [comment]
> in order to reflect what was discussed around the Products M4, I'm moving this issue to the M4 board.

Whoops, I moved this to M4 on the board itself but didn't change the milestone here. Thanks for doing that!
