### ISSUE TITLE
Unified Login: XMLRPC discovery error screens need styling

### ISSUE THREAD

**Issue by rachelmcr** [woocommerce/woocommerce-android#2913]
**Describe the bug**

While testing unified login with the site credentials / password flow, I ended up hitting this unstyled XMLRPC error screen:

![image](https://user-images.githubusercontent.com/8658164/94165620-51cfd500-fe82-11ea-8977-f1e95fcf6163.png)

This screen looks like it’s part of the [XMLRPC discovery errors](https://github.com/wordpress-mobile/WordPress-Login-Flow-Android/blob/a651591cab8b2bacdfa2d0a6c7d5b921237ff50a/WordPressLoginFlow/src/main/java/org/wordpress/android/login/LoginUsernamePasswordFragment.java#L404) in `WordPress-Login-Flow-Android` originally implemented for Woo in https://github.com/woocommerce/woocommerce-android/pull/1542. It works but needs styles for the unified login updates.

**To Reproduce**

1. Start with a Jetpack-connected site.
2. Open the app (start logged out).
3. Select "Enter your store address."
4. Enter your store address and select "Continue."
5. On the email screen, select "Continue with store credentials."
6. Before entering your store credentials, go to the web and block XML-RPC on the site (e.g. by activating the [Disable XML-RPC](https://wordpress.org/plugins/disable-xml-rpc/) plugin).
7. In the app, enter your store credentials.

Notice you are taken to an error screen without styling (either the one in the screenshot above or a similar screen with another error message).

(I encountered the issue in a scenario where this error popped up unexpectedly after trying to log in a few times in a row, but the steps above should consistently force one of those XML-RPC discovery error screens to appear.)

**Comment by anitaa1990** [comment]
Closed via #2926
