### ISSUE TITLE
In-app feedback: "I like it" feedback button stops working after rotating device

### ISSUE THREAD

**Issue by rachelmcr** [woocommerce/woocommerce-android#2922]
**Describe the bug**

On the My store screen's in-app feedback card:

If I tap the "I like it" button, I see a dialog with a prompt to review the app. However, if I rotate my device that dialog goes away and the "I like it" button stops working.

**To Reproduce**

1. Run the app on the device. If you already have the app installed for more than 3 months, skip to Step 5.
2. Forcefully terminate it.
3. Time-travel to 3 months (plus 1 day) from the current date.
4. Open the app again.
5. The in-app feedback card should now be visible in Stats → Today.
6. Tap "I like it" and notice the dialog appears with a prompt to review the app.
7. Rotate your device (e.g. from portrait to landscape) and notice the dialog disappears.
8. Tap "I like it" and notice the button is unresponsive even if you rotate the app back to portrait and/or pull to refresh.

**Screenshots**

Screencast: https://cloudup.com/c1Yr1h8tWfv

**Mobile Environment**
Please include:
- Device: moto e5 play
- Android version: 8.1.0
- WooCommerce Android version: 5.1-rc-1

**Comment by AmandaRiu** [comment]
@rachelmcr The alert dialog requesting a review will be going away in 5.2 as [this PR](https://github.com/woocommerce/woocommerce-android/pull/2859) changed the flow of the process. So this will no longer be an issue after 5.2 - are you okay with closing this ticket?

**Comment by rachelmcr** [comment]
Yep, this is a minor issue so if it won't be an issue at all after 5.2 let's leave it. 👍  Thanks!
