### ISSUE TITLE
Store picker screen flashed when logging in by store address

### ISSUE THREAD

**Issue by AmandaRiu** [woocommerce/woocommerce-android#2937]
The store picker screen is momentarily flashed as the login process completes when a user successfully logs in by site address (ie - the store picker is skipped altogether). This is because the `SitePickerActivity` is the one that works through and verifies the login and store before completing login. One thing we could do is hide the items on this screen so it's not so obvious:

<img src="https://user-images.githubusercontent.com/5810477/94606544-a0a5b200-0268-11eb-9a17-dfd741b8a0dc.gif" width="320"/>

**Comment by JorgeMucientes** [comment]
The login process has changed a lot since this feedback. This task doesn't apply anymore. Closing
