### ISSUE TITLE
Product details: cannot change product type

### ISSUE THREAD

**Issue by jaclync** [woocommerce/woocommerce-android#2968]
**Describe the bug**

After changing the product type, it stays on the product type bottom sheet after tapping “YES, CHANGE” on the confirmation alert.

**To Reproduce**

- Navigate to the products tab
- Tap on any product
- Tap on the product type row
- Select a different product type from the current one (maybe we can hide the existing product type from the menu)
- Tap "YES, CHANGE" --> it stays on the product type bottom sheet without any change

**Screenshots**

https://d.pr/free/v/xwXGTk

**Expected behavior**

After confirming the change, the product type bottom sheet is expected to dismiss and the product's product type is updated to the selected value.

**Isolating the problem (mark completed items with an [x]):**
- [ ] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [ ] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [x] I can reproduce this bug consistently using the steps above.

**Mobile Environment**
Please include:
- Device: Nokia 6.1 / emulator
- Android version: 9 
- WooCommerce Android version: 5.2-rc-1

**Comment by 0nko** [comment]
Fixed in #2997.
