### ISSUE TITLE
Update Home Screen "More Actions" menu so it differs from the Product Details settings menu

### ISSUE THREAD

**Issue by Garance91540** [woocommerce/woocommerce-android#2983]
Can we update the current "More Actions" menu on the Home screen to only display a settings icon, and nest the "Help & Support" section in the settings? 

This will help users differentiate between the Product Settings and the Global Settings

<img width="1046" alt="Screen Shot 2020-10-08 at 4 02 57 PM" src="https://user-images.githubusercontent.com/28450084/95469592-1e13a580-0980-11eb-947d-86f200c98623.png">

Designs in the "Home Screen Settings Icon" page of the Add/Edit Products Figma file

Background convo: https://a8c.slack.com/archives/CGPNUU63E/p1599661344075500

**Comment by nbradbury** [comment]
~~@Garance91540 I just want to verify that the gear icon should only appear on the home screen and not on the order list, product list, or review list.~~

Nevermind, I tried out the iOS app and I see the gear is only on the home screen.

**Comment by Garance91540** [comment]
> Nevermind, I tried out the iOS app and I see the gear is only on the home screen.

that's right 👍!
