### ISSUE TITLE
Products: Product with a single review shows "1 reviews" instead of "1 review" in product detail

### ISSUE THREAD

**Issue by rachelmcr** [woocommerce/woocommerce-android#2989]
**Describe the bug**
h/t @jaclync for reporting this:

> Edit product > reviews row: when the product has 1 review, it shows “1 reviews” (we show “1 review” in iOS).

Note that this can also make translation awkward for languages that have more grammatical distinctions for numbers than just singular/plural.

**To Reproduce**

1. Make sure you have a product with a single review.
2. Navigate to the products tab in the app.
3. Tap on that product.
4. Notice that the Reviews summary says "1 reviews" instead of "1 review."

**Screenshots**

<img src="https://user-images.githubusercontent.com/8658164/95487291-09d5a580-098c-11eb-9505-c16783fd606e.png" width="300px">

**Mobile Environment**
Please include:
- Device: moto e5 play
- Android version: 8.1.0
- WooCommerce Android version: 5.2-rc-1

**Comment by nbradbury** [comment]
Closing as this is addressed in #3000
