### ISSUE TITLE
[Products M5] Variable Products: Add variations

### ISSUE THREAD

**Issue by ThomazFB** [woocommerce/woocommerce-android#3001]
Ref p91TBi-2Ur-p2.

## Goals
- [ ] Create the capability of adding any kind of new variations to a given variable product.
- [ ] When tapping on `Add variations`, show a view that allows the user to create new attributes from scratch with the respective attribute value. 
- [ ] Hide behind M5 flag.

As it is right now we can only manage variations already defined through the Woo Site. If any attributes already exist in the store, then we list them on the `Add attribute` views.

<img width="874" alt="Screen Shot 2020-10-15 at 10 53 54 PM" src="https://user-images.githubusercontent.com/5920403/96266555-25990700-0f9d-11eb-8433-02f518b21a6b.png">
<img width="889" alt="Screen Shot 2020-10-15 at 10 54 17 PM" src="https://user-images.githubusercontent.com/5920403/96266549-2336ad00-0f9d-11eb-9b8b-98d26988fa3e.png">

**Comment by designsimply** [comment]
We received an app review requesting this back in May! 🙂

> Needs work, it's fine for basic products but doesn't give any info on the variations customers have chosen so is useless for any e-commerce selling products in multiple colours etc
> 
> <sup>3-star - May 6, 2020 at 11:44 AM - MAIMANG 7, WooAndroid 4.0, Android 8.1</sup>

<sup>play-store-reviewid=gp:AOqpTOEznjDPhOUD7PUbHkggLKo9JROf64zQ1GJ0-cUbcxre8gWwU57w3yrihMnph-7PgJGVIjyAPXgt3l3_XpE</sup>

**Comment by designsimply** [comment]
One more!

> Well thought out but no product additions.
> 
> <sup>3-star - Oct 24, 2030 at 10:39PM - Translated from Turkish - Vestel Z20, WooAndroid 15.8, Android 8.0</sup>

<sup>play-store-reviewid=gp:AOqpTOHKNHlog6x3y_H9-T35yhOXj-5knQCdunv1E1D3AebJvqt2r1cc1tclyU4CwnKBa4EkVxwLaYiNJhwKCKQ</sup>

**Comment by AliSoftware** [comment]
@ThomazFB Moving this to 5.5 since 5.4 is ❄️-ing today

**Comment by AliSoftware** [comment]
Seems this still hasn't got a chance to get picked before today's 5.5 ❄️  code freeze, so pushing it further to milestone 5.6

**Comment by ThomazFB** [comment]
Closing this issue since it doesn't correspond to the current Product Variations board configuration, but keeping it at the board to preserve the feedbacks reported here.
