### ISSUE TITLE
Top performers: support original date ranges

### ISSUE THREAD

**Issue by nbradbury** [woocommerce/woocommerce-android#301]
In #299 we added support for top performers, but we were unable to match the design because the backend didn't support the date ranges in the tabbed UI (7 days, 30 days, 90 days, 1 year), at least not in a way that didn't require making separate requests for product details.

The Woo team resolved this [here](https://github.com/woocommerce/woocommerce/pull/21045) by adding the missing product details. Once we're able to use the v3 Woo API in the app, we should update the UI to support the original date ranges.

**Comment by anitaa1990** [comment]
Given that we are going to be migrating to the v4 stats API soon and there is already an issue opened [here](https://github.com/woocommerce/woocommerce-android/issues/2451) for that, I'm closing ☝️ one
