### ISSUE TITLE
Shipping Labels M2 release: add option to add package details for a shipping label

### ISSUE THREAD

**Issue by anitaa1990** [woocommerce/woocommerce-android#3019]
Once the [shipping label addresses are displayed and validated](https://github.com/woocommerce/woocommerce-android/issues/3017), we would need to provide the option to add package details for the shipping label.

- [ ] Clicking on the **Continue** button on the Package details section, displays a list of products associated with the order under a single package. 
- [ ] Displays the package name previously used by the store and the option to add the weight of the package.  
- [ ] Clicking on the package name text field opens a new screen that displays a list of custom and default packages for the store.

<img width="582" alt="Screenshot 2020-10-14 at 9 28 08 AM" src="https://user-images.githubusercontent.com/22608780/95941944-999da880-0dff-11eb-9724-1f19b451ddc2.png">

**Note that the option to move a product to a different package will be taking place in Milestone 3**

**Comment by hichamboushaba** [comment]
@anitaa1990 @Garance91540 I need some clarification please regarding this task:
> Displays the package name previously used by the store and the option to add the weight of the package.

Does this mean saving the last used package in the app's preferences, and use it by default the next time?

**Comment by anitaa1990** [comment]
> Does this mean saving the last used package in the app's preferences, and use it by default the next time?

I believe this is available from the WC ship settings api, mentioned in this P2 post (`p91TBi-2xo`). This is the API endpoint:
```
/wc/v1/connect/account/settings
```

And I think you would need to use the `last_box_id` field under the `userMeta` object in the API response.

**Comment by hichamboushaba** [comment]
Thanks @anitaa1990 for the reply, and if this field is missing (for example first use of the feature), should we select the first package by default? or display something else? cc @Garance91540

**Comment by Garance91540** [comment]
Hi @hichamboushaba , for first-time WC ship users, please refer to the "Package creation flow" in Figma https://d.pr/i/HEljEo

**Comment by hichamboushaba** [comment]
@Garance91540 sorry, I think you misunderstood my question 🙂, as a user, I may have configured the Shipping extension in the web (selected the packages or/and created custom ones), but never created a shipping label, so the `last_box_id` mentioned before, will be empty.
In this case, we have some shipping packages to select from, which is different than the package creation flow, what should we do? display "Select Package" in the field, or select the first package of the list returned from the backend by default?

I'll try to test it on backend to see how core behaves here.

**Comment by Garance91540** [comment]
Ah good to know: I wasn't aware you could create packages without ever creating a shipping label, since you create packages when you create shipping labels 🤔

If packages already have been created, we display the last selected/created package in the "Package Selected" dropdown

**Comment by hichamboushaba** [comment]
Yes, you can create them in the settings menu (https://d.pr/i/2m8y8Y), I just managed to delete the `last_box_id` from my store, to simulate a new user who never created a shipping label, and core displays `Please select a package` in the dropdown (https://d.pr/i/4YJ1rs).

> If packages already have been created, we display the last selected/created package in the "Package Selected" dropdown

I don't think we can identify the last created package, but we can pick the first one in the list. Unless we want to follow what core does, and display "Select Package" in the dropdown, to force the user to open the package list screen.

**Comment by anitaa1990** [comment]
> Thanks @anitaa1990 for the reply, and if this field is missing (for example first use of the feature), should we select the first package by default? or display something else? cc @Garance91540

@hichamboushaba by default, if there is no last selected package, the Web displays `Select a package type`. I think we want to follow a similar approach iin the app as well.

<img width="544" alt="Screenshot 2021-02-02 at 11 51 57 AM" src="https://user-images.githubusercontent.com/22608780/106560544-315d0900-654d-11eb-8e65-1339b281013f.png">
