### ISSUE TITLE
Shipping Labels M2 release: add option to view how to create shipping labels

### ISSUE THREAD

**Issue by anitaa1990** [woocommerce/woocommerce-android#3020]
We need to provide a link below the **Create shipping label** to find out how to create shipping labels. This will only be displayed if the **Create shipping label button** is displayed.

<img src="https://user-images.githubusercontent.com/22608780/95946851-08ccca00-0e0b-11eb-8945-97e52d40b201.png" width="300"/>. <img src="https://user-images.githubusercontent.com/22608780/95946911-2a2db600-0e0b-11eb-8544-b5719ab9f957.png" width="300"/>

**Comment by 0nko** [comment]
Resolved by #3177.
