### ISSUE TITLE
Woocommerce Product add-ons compatibility 

### ISSUE THREAD

**Issue by toby12222** [woocommerce/woocommerce-android#3021]
Hello, how are you? Very good app, everything works perfectly, my only problem is that if you can make it compatible with the woocommerce product-add-ons extension, in order to see the customers' orders with the additional information, thank you very much

https://woocommerce.com/products/product-add-ons/
https://woocommerce.com/products/pdf-invoices/

**Comment by AmandaRiu** [comment]
Hi! 👋 Thank you for using the app. Please submit feature requests to our [feature request page](https://ideas.woocommerce.com/forums/133476-woocommerce?category_id=84283) so it can be upvoted and picked for future development.
