### ISSUE TITLE
Add swipe gestures to tabbed cards on the Dashboard

### ISSUE THREAD

**Issue by AmandaRiu** [woocommerce/woocommerce-android#303]
## Suggested Enhancement
The [Material Design guidelines for working with Tabs](https://material.io/design/components/tabs.html#behavior) suggests allowing the user to swipe between tabs. This would be a great for the dashboard cards specifically because users would want to quickly move between the different filters represented by the tabs. Also we use the overflow tab design and this is much friendlier when a user can swipe. 

## Current Behavior
Currently the cards do not support swipe gestures and require manually clicking tabs, as well as manually scrolling to overflow tabs. 

cc: @folletto for design review

**Comment by AmandaRiu** [comment]
The stats tab is going through a re-design so putting this ticket on hold for now. We can re-evaluate at a later time.

**Comment by anitaa1990** [comment]
The stats tab is going through a refactor and design changes so closing this issue since it is no longer applicable. We can definitely open new issues if we would like to support this feature in the future.
