### ISSUE TITLE
Support removing a product image from a product variation

### ISSUE THREAD

**Issue by anitaa1990** [woocommerce/woocommerce-android#3066]
Ref: p91TBi-34W-p2
iOS issue for reference: https://github.com/woocommerce/woocommerce-ios/issues/2576

There was an issue on removing a product image from a product variation in the API. This looks to be fixed in the latest [WooCommerce version (4.7)](https://github.com/woocommerce/woocommerce/pull/27299). This issue is to add back this feature into the app.

**Comment by AmandaRiu** [comment]
Functionality was added in #3312 - closing issue.
