### ISSUE TITLE
[Shipping Labels M1]: fix some text in the print shipping label info screens

### ISSUE THREAD

**Issue by anitaa1990** [woocommerce/woocommerce-android#3069]
<img src="https://user-images.githubusercontent.com/22608780/96867690-ad45b080-148a-11eb-9375-18e789adcb30.png" width="300"/>

A couple copy edits:
- ~Put periods at the end of every sentence.~
- Change wifi to WiFi (there are two).
- Change the title of the screen from “Print with your phone” to “Print with your device” as they might be using a tablet.

<img src="https://user-images.githubusercontent.com/22608780/96867681-aae35680-148a-11eb-9564-2bb9d180a442.png" width="300"/>

A few copy edits:

Change to terms of service (drop the pluralization on services).
Change to used the label on a package (instead of in).

**Comment by nbradbury** [comment]
> * Put periods at the end of every sentence.

I think we can skip this one since the [Material Guidelines](https://material.io/design/communication/writing.html#principles) suggest _not_ using periods at the end of single sentences.

**Comment by anitaa1990** [comment]
Closed via #3075
