### ISSUE TITLE
Product image upload fails

### ISSUE THREAD

**Issue by nbradbury** [woocommerce/woocommerce-android#3078]
@startuptester reported that uploading images from her Samsung device always fails. The log she supplied shows this:

```
[Oct-22 19:45 MEDIA d] productImagesService > Dispatching request to upload content://media/external/images/media/50
[Oct-22 19:45 WP d] API Dispatching action: MediaAction-UPLOAD_MEDIA
[Oct-22 19:45 WP e] MEDIA Media doesn't have required data: local file path for media does not exist
[Oct-22 19:45 MEDIA w] productImagesService > error uploading media: MALFORMED_MEDIA_ARG, local file path for media does not exist
```

The two `MEDIA` entries are from WCAndroid, while the two `WP` entries are from FluxC. The first FluxC entry comes from [here](https://github.com/wordpress-mobile/WordPress-FluxC-Android/blob/3a44520084671ff0018086933626075b5e323d98/fluxc/src/main/java/org/wordpress/android/fluxc/network/BaseUploadRequestBody.java#L61) and the second from [here](https://github.com/wordpress-mobile/WordPress-FluxC-Android/blob/b3b554c18becf990e904aa674af8bacd22692e97/fluxc/src/main/java/org/wordpress/android/fluxc/store/MediaStore.java#L753).

Earlier on in the app log, though, it has this for a different image:

```
[Oct-22 19:45 MEDIA d] productImagesService > Dispatching request to upload content://0@media/external/images/media/33
[Oct-22 19:45 WP d] API Dispatching action: MediaAction-UPLOAD_MEDIA
[Oct-22 19:45 WP d] MEDIA starting upload for: 20
[Oct-22 19:45 WP d] API Dispatching action: UploadAction-UPLOADED_MEDIA
[Oct-22 19:45 WP d] API Dispatching action: MediaAction-UPLOADED_MEDIA
[Oct-22 19:45 WP d] MEDIA media upload successful: Response{protocol=h2, code=200, message=, url=https://public-api.wordpress.com/rest/v1.1/sites/182262986/media/new/?locale=en_CA}
```

**Comment by itsmeichigo** [comment]
Similar problem: 4085491-zen

**Comment by wzieba** [comment]
I've linked Sentry issue with:

```
NullPointerException event.media.url must not be null
```

as I believe this ~is~ might be the same issue.

**Comment by anitaa1990** [comment]
Based on the discussion in Slack: `p1624426777374300-slack-CGPNUU63E`, @hichamboushaba fixed an issue in #4251 that could solve this problem. On the long run though, as we discussed, it would be better to perhaps implement our own Media picker instead of using external file readers, similar to the [MediaPickerFragment](https://github.com/wordpress-mobile/WordPress-Android/blob/35ac7d1f8ae5b6481237fc43e7333d0d56734100/WordPress/src/main/java/org/wordpress/android/ui/mediapicker/MediaPickerFragment.kt#L81) from WordPress.

**Comment by anitaa1990** [comment]
The issue with [Sentry](https://sentry.io/organizations/a8c/issues/1079436016/events/089ac3c343894ce6b130131e5e2d6af9/?environment=release&project=1459556&statsPeriod=14d) is happening when uploading a downloadable file for a product and not related to product image uploads so creating a separate issue for that.

**Comment by mokagio** [comment]
@anitaa1990, what is the separate issue? I can see Sentry automatically created #4336, is that it?

I'm seeing something that matches this in 4256078-zen.

**Comment by anitaa1990** [comment]
This issue should be fixed now that we've updated to using the internal media picker. The Sentry issues linked here are no longer available so I'll mark this issue as closed for now. We can certainly re-open if this happens again in the future.
