### ISSUE TITLE
[Unified Login - Continue with WP.com] Email entered isn't associated with an existing WP.com account

### ISSUE THREAD

**Issue by Garance91540** [woocommerce/woocommerce-android#3121]
If users enter an email that isn't associated with a WP.com account, they should see this screen:

<img width="663" alt="Screen Shot 2020-11-11 at 10 38 54 AM" src="https://user-images.githubusercontent.com/28450084/98795096-1f664100-240a-11eb-8a1d-10dc18c76a17.png">

**Comment by AmandaRiu** [comment]
Implemented in https://github.com/woocommerce/woocommerce-android/pull/2943. Closing ticket.
