### ISSUE TITLE
[Unified Login] - Site picker style updates

### ISSUE THREAD

**Issue by Garance91540** [woocommerce/woocommerce-android#3123]
Small styling updates to the site picker screen:
https://d.pr/i/VU4hKx

1. Update status bar background color to white
2. Update Buttons so there's no drop shadow under Primary button and button text font is subtitle 2
3. Keep the Home indicator background white like on the other screen

Thank you!

**Comment by AmandaRiu** [comment]
Reopening as not all the items have been addressed.

**Comment by AmandaRiu** [comment]
> Update status bar background color to white

This was actually done for us because the rest of the app now uses a white status bar. 

> Update Buttons so there's no drop shadow under Primary button and button text font is subtitle 2

Fixed in #3237 

> Keep the Home indicator background white like on the other screen

Fixed in https://github.com/woocommerce/woocommerce-android/pull/3294

**Comment by AmandaRiu** [comment]
All fixes have been implemented. Closing.
