### ISSUE TITLE
Order details: Shipping information is missing when order contains both physical and virtual, downloadable products

### ISSUE THREAD

**Issue by rachelmcr** [woocommerce/woocommerce-android#3125]
**Describe the bug**

When an order has both physical and downloadable virtual products, the Customer Information section only includes the billing information. (It should include both the shipping and billing information, but right now the shipping information only appears when an order has _only_ physical products.)

@anitaa1990 Maybe this is related to the refactor in https://github.com/woocommerce/woocommerce-android/pull/2860?

**To Reproduce**

1. Create a new order. Enter both shipping and billing addresses, and at least one physical product (no virtual products).
2. Open the app's Orders tab.
3. Select the new order and notice the Customer Information includes "Shipping details" and "Show billing" (which shows the billing details when you tap on it).
4. Create another new order. Enter both shipping and billing addresses, and at least one physical and one virtual, downloadable product.
5. Open the app's Orders tab.
6. Select the new order and notice the Customer Information only includes "Billing details" (no shipping details even though there's a physical product in the order).

**Mobile Environment**
Please include:
- Device: moto e5 play
- Android version: 8.1.0
- WooCommerce Android version: 5.4-rc-1

**Comment by ParaskP7** [comment]
Hi @rachelmcr 👋 

I have tried to reproduced this issue on `5.5-rc-1`. However, it seems to me that it is working as expected. I tried that by creating an order with one physical and one virtual product, see screenshots below:

<img src="https://user-images.githubusercontent.com/9729923/99968141-6c023280-2da1-11eb-9ae7-edeccb760509.png" width="250" height="500">   <img src="https://user-images.githubusercontent.com/9729923/99968154-71f81380-2da1-11eb-80b1-781318025300.png" width="250" height="500">

Am I missing something here? Can you verify that you can reproduce it on your side again? Would you be able to share some screenshots (expected and actual)?

**Comment by rachelmcr** [comment]
I confirmed I can still reproduce the issue. Here are screenshots from an order with both a virtual and a physical product:

<img src="https://user-images.githubusercontent.com/8658164/100212675-8fde8900-2f05-11eb-9787-9bc71e58d64a.png" width="300px"> <img src="https://user-images.githubusercontent.com/8658164/100212671-8e14c580-2f05-11eb-8988-1279dd5f27b0.png" width="300px">

I expect the order to look like yours, so I'm not sure what's causing the difference here. I'd be happy to give you access to my test site if it would help to take a closer look at the order and product details.

**Comment by rachelmcr** [comment]
Ah, actually I figured it out — it works as expected unless the virtual product is downloadable. The "Album" product in my screenshot above is both virtual and downloadable (both are in the General product settings in wp-admin web), and changing that downloadable setting changes the behavior in the Customer Information section here.

**Comment by ParaskP7** [comment]
Thanks so much for the further digging into this @rachelmcr , much appreciated! 🌟 

Many thanks for updating the title as well! Now the issue must be 100% reproducible and whoever picks-up this issue next should have no problem in progressing it further. 🙏

**Comment by hichamboushaba** [comment]
Hey @rachelmcr, I think this bug was fixed by Ondrej's work on the PR #3170, I can reproduce it in the 5.5 builds, bot not on the develop branch, and the APK of this PR.
Before this PR, there was an issue where an order that has only one virtual product, was considered as if all products are virtual, and the shipping section was hidden.
Can you please confirm by downloading the APK from the above PR?

**Comment by rachelmcr** [comment]
Thanks, @hichamboushaba! Sorry for the delay — I just tested in the 5.6 beta (since it includes that fix) and confirmed this is now resolved. I'll close the issue. 👍
