### ISSUE TITLE
ProductsM5: Tapping on Add Products should present the product selection page

### ISSUE THREAD

**Issue by shiki** [woocommerce/woocommerce-android#3126]
## Current Behavior

Right now, when adding a linked product to a product that has no pre-existing linked products, you would see the “Add Products” button. 

<img src="https://user-images.githubusercontent.com/198826/98030837-d6d9d280-1dce-11eb-95c0-ee8159a7d5a6.png" width="300">

Tapping on the button leads you to this page:

<img src="https://user-images.githubusercontent.com/198826/98030875-e6f1b200-1dce-11eb-9015-ee8bf23bb445.png" width="300">

And now you have to tap on the Add Products button again on that page to select a product to link. 

<img src="https://user-images.githubusercontent.com/198826/98030904-f07b1a00-1dce-11eb-93d1-8e0dee18a69f.gif" width="300">

### Steps to Reproduce

1. Navigate to a product with no linked products. 
2. Tap on Add More Details → Linked Products. 
3. Tap on an Add Product button (either Upsells or Cross-sells). 
4. Notice you will be led to an empty screen with just an “Add Product” button.

## Expected Behavior

Based on the design in Figma, the desired behavior is that when tapping on the “Add Products” button, the user should be navigated directly to the product selection page. 

<img src="https://user-images.githubusercontent.com/198826/98031149-55367480-1dcf-11eb-8be2-e7d22af33d21.png" width="500">

---

@Garance91540 Did I capture the expected behavior correctly?

**Comment by Garance91540** [comment]
> @Garance91540 Did I capture the expected behavior correctly?

That's right @shiki ! If there isn't any product selected yet, when users select "Add products", we should open the product list directly. However once this CTA becomes "Edit products" (because there are already products selected), then we should this page first: https://d.pr/i/6ZBMgh
