### ISSUE TITLE
Order: product attributes design changes

### ISSUE THREAD

**Issue by anitaa1990** [woocommerce/woocommerce-android#3145]
Some design changes from @Garance91540 after testing the product attributes in the Order detail screen:
- I’m not seeing the product picture in the order details screen
- Would it be possible to capitalize all variants selected? (so here “Blue”, “Feather”)?
- The interpunct between the variants and the quantities is really big. Could we decrease its font according to designs?

#### Current implementation
<img width="383" alt="1" src="https://user-images.githubusercontent.com/22608780/98502394-e5fdcc00-2277-11eb-85ad-c594e18289f9.png">

#### Actual Design
<img width="628" alt="2" src="https://user-images.githubusercontent.com/22608780/98502398-e72ef900-2277-11eb-9eb9-8d48cf62d5e9.png">

**Comment by AmandaRiu** [comment]
> I’m not seeing the product picture in the order details screen

This wasn't an issue related to product attributes and is currently working fine. 

> Would it be possible to capitalize all variants selected? (so here “Blue”, “Feather”)?

This was taken care of in this FluxC PR: https://github.com/wordpress-mobile/WordPress-FluxC-Android/pull/1768
