### ISSUE TITLE
New Order not trigerring notification when it is in "pending" status

### ISSUE THREAD

**Issue by mvarchdev** [woocommerce/woocommerce-android#3165]
Hello. I have customized store (repair services) where when order is created. it is not changed to processing state. My application on android is not triggering the new order notifcation when customer creates the order. Please, can you help me? What can I do to notify me via app when order is created? Thanks

**Comment by AmandaRiu** [comment]
Hi there! Please contact support by opening the WooCommerce app on your device and going to Settings and then clicking help. We don't offer support through GitHub. Thank you for using the app!
