### ISSUE TITLE
Enable searching products by SKU

### ISSUE THREAD

**Issue by anitaa1990** [woocommerce/woocommerce-android#3168]
Provide the option to search for products by SKU in the Products tab. This is one of the feature requested by users from the feedback survey.

Related iOS issue: woocommerce/woocommerce-ios#3157

**Comment by nbradbury** [comment]
Note that this appears to require a backend change.

**Comment by anitaa1990** [comment]
It looks like the backend supports this change:
```
/wc/v3/products/&_method=get&per_page=25&orderby=title&order=asc&offset=0&sku=woo-beanie
```

We could add the SKU query parameter when searching for products on FluxC to fetch a list of products supporting that SKU. But the only thing is we would need to enter the full sku in order to fetch the product. Entering something like `woo` would not return anything even if there is a SKU value available called "woo-beanie".

I have asked the API team on more clarification for this requirement [here](https://a8c.slack.com/archives/C0E1AV8T0/p1605703478419500).

**Comment by rossanafmenezes** [comment]
I had a user asking about this here 3913564-zen

**Comment by joshbetz** [comment]
Related: https://github.com/woocommerce/woocommerce/issues/28508

**Comment by nbradbury** [comment]
Just a note to point out that while adding this to the main product list, we should also add it to the order creation product list.
