### ISSUE TITLE
Centralize Milestone value representation on the app

### ISSUE THREAD

**Issue by ThomazFB** [woocommerce/woocommerce-android#3171]
We have on different corners of the app values representing the current milestone for Products and Shipping Labels features, as it is right now we have an error-prone situation since it's not easy to be aware of all the points we should update the Milestone value every time we upgrade the milestone number.

Here are some known classes that use Milestone values that aren't unified and some of them are already outdated:

- FeatureFlag
- SurveyType
- FeatureFeedbackSettings

**Comment by JorgeMucientes** [comment]
I think this ticket is stale doesn't apply anymore. No `milestone` value is use in `FeatureFlag` or `FeatureFeedbackSettings`. And none of the usages`SurveyType` constructor provide a `molestone` value. 

Closing
