### ISSUE TITLE
[Variations] “Edit Attributes” Button

### ISSUE THREAD

**Issue by shiki** [woocommerce/woocommerce-android#3206]
Refs p91TBi-3Oc-p2, p91TBi-2Ur-p2.

When the product has existing variations, then we should show an Edit button in the variations list. The button allows the user to edit the **attributes and options** and generate new variations again. 

<img src="https://user-images.githubusercontent.com/198826/100240992-75e67b80-2ef0-11eb-9985-40a282930c43.png" width="500">

## Goals

- [ ] Show the Edit Attributes button from the Options menu. 
- [ ] Tapping on Edit Attributes will forward the user to the #3493 flow. 

---

iOS: https://github.com/woocommerce/woocommerce-ios/issues/3194

**Comment by nbradbury** [comment]
Closed via #3521
