### ISSUE TITLE
[Variations] Renaming an Attribute

### ISSUE THREAD

**Issue by shiki** [woocommerce/woocommerce-android#3214]
Ref p91TBi-3Oc-p2.

From #3209 or #3493, users would be presented with the options management screen (#3208). On that screen, the user should be able to rename the attribute. 

<img src="https://user-images.githubusercontent.com/198826/100246519-784bd400-2ef6-11eb-9533-a0ca1438ec17.png" width="800">

## Goals 

- [ ] Add a Rename button in the options menu.
- [ ] Present the Rename Attribute screen.
- [ ] Tapping on Done will rename the attribute. 

---

iOS: https://github.com/woocommerce/woocommerce-ios/issues/3212

**Comment by nbradbury** [comment]
**Update:** note that renaming is only available to local attributes. Renaming global attributes will not be supported.
