### ISSUE TITLE
Hide the product downloadable files behind the M5 flag

### ISSUE THREAD

**Issue by hichamboushaba** [woocommerce/woocommerce-android#3250]
Currently on the app, we can see both sections of the downloadable files, the visibility of the new section should depend on the M5 flag:
<img width="400" alt="downloads" src="https://user-images.githubusercontent.com/1657201/100890394-7a92cd00-34b8-11eb-9d1e-e85d2f845254.png">

**Comment by shiki** [comment]
This was fixed in release 5.6 via #3269.

Thanks, Hicham!
