### ISSUE TITLE
Orders: Search field should show selected filter

### ISSUE THREAD

**Issue by rachelmcr** [woocommerce/woocommerce-android#3252]
**Describe the bug**

As @Garance91540 reported:

Once I select a search criteria (ie “Pending payment”), this is the screen I see but the selected filter should appear in the search bar (right now the search bar is empty)

**To Reproduce**
1. Go to Orders
2. Select the search icon
3. Select a filter on the search screen
4. Notice the search bar is empty

**Screenshots**

<img src="https://user-images.githubusercontent.com/8658164/100895358-5d103400-34b5-11eb-993d-e6df8d927d9c.png" width="300px">

**Mobile Environment**
Please include:
- Device: 
- Android version: 
- WooCommerce Android version: 5.6-rc-1

**Comment by Garance91540** [comment]
Hi @hichamboushaba , I'm still seeing this issue when testing Android 5.8, could we keep it open :) ?

The selected filter should appear in the search bar.

**Comment by hichamboushaba** [comment]
Thanks @Garance91540 for pointing it out, it was auto-closed when we merged #3274, as it mentioned it instead of the correct issue #3251.
