### ISSUE TITLE
Orders: Order details missing header when selected from search results

### ISSUE THREAD

**Issue by rachelmcr** [woocommerce/woocommerce-android#3253]
**Describe the bug**

As @Garance91540 reported:

Once I select an order in the search result list, this is the order details screen I see, which is missing a header (it should display the Order number)

**To Reproduce**
1. Go to Orders
2. Select the search icon
3. Select a filter on the search screen or search for an order
4. Select an order in the search results
5. Notice the order details screen is missing a header

**Screenshots**

<img src="https://user-images.githubusercontent.com/8658164/100895651-b6786300-34b5-11eb-9629-cb639a905c8d.png" width="300px">

**Mobile Environment**
Please include:
- Device: 
- Android version: 
- WooCommerce Android version: 5.6-rc-1

**Comment by shiki** [comment]
This was fixed in 5.6 by #3263.
