### ISSUE TITLE
Products: Extra divider appears under header after applying product filter(s)

### ISSUE THREAD

**Issue by rachelmcr** [woocommerce/woocommerce-android#3254]
**Describe the bug**

As @Garance91540 reported:

Once I select “Filters” on the product list, and then apply one or close the Filters screen, I land back on the product list where there’s a divider that shouldn’t be there.

**To Reproduce**
1. Go to Products
2. Tap on Filters
3. Select any filter and tap Show Products to apply it
4. Notice the product list now shows the extra divider

**Screenshots**

<img src="https://user-images.githubusercontent.com/8658164/100895919-fa6b6800-34b5-11eb-9622-1c7c76b4aaa4.png" width="300px">

**Expected behavior**

Design:

<img src="https://user-images.githubusercontent.com/8658164/100895932-fdfeef00-34b5-11eb-8d65-a3b1eee87657.png" width="300px">

**Mobile Environment**
Please include:
- Device: 
- Android version: 
- WooCommerce Android version: 5.6-rc-1

**Comment by shiki** [comment]
This was fixed in the 5.6 branch via #3264.
