### ISSUE TITLE
Products: Remove drop shadow from product list filter screen

### ISSUE THREAD

**Issue by rachelmcr** [woocommerce/woocommerce-android#3258]
**Describe the bug**

As @Garance91540 reported:

When I select “Filters” on the Product List, it opens the Filters screen, and it displays a dropshadow under the “Filters” Header bottom divider. Can we remove the dropshadow?

**To Reproduce**
1. Go to Products tab.
2. Tap on the Filters button at the top of the product list.
3. Notice the drop shadow under the "Filters" header.

**Screenshots**

<img src="https://user-images.githubusercontent.com/8658164/100909307-740a5280-34c4-11eb-99b8-e208e7fbd5b0.png" width="300px">

**Expected behavior**

Designs:

<img src="https://user-images.githubusercontent.com/8658164/100909338-7e2c5100-34c4-11eb-9bb1-b24a3a7a96ab.png" width="300px">

**Mobile Environment**
Please include:
- Device: 
- Android version: 
- WooCommerce Android version: 5.6-rc-1

**Comment by rossanafmenezes** [comment]
Hai @Garance91540, 

I am working on this issue and while I can see the dividers are not supposed to have a margin on Figma in the current design, it looks to me the dropshadow should be there. Could you please confirm? Maybe I am looking in the wrong place.

I have committed the changes for the dividers already. 

Thanks

**Comment by Garance91540** [comment]
Hi @rossanafmenezes , I'm referring to the drop shadows that's under the top nav: 

https://d.pr/i/syKxKj

It should not be there (only a flat divider)

https://d.pr/i/ikxSj7

Let me know if you have questions!

**Comment by rossanafmenezes** [comment]
Hi, @Garance91540.

I submitted the PR to change this [here](https://github.com/woocommerce/woocommerce-android/pull/4666) where it was pointed out this would change the drop shadow not only in the Filter screen.  Can you kindly let me know if this should apply to all non-top-level screens, please? Like the Product details screen for example. Thank you

**Comment by rossanafmenezes** [comment]
As discussed in this PR #4666 I have committed the changes to make the filter list pages dividers full-width but have reverted the changes for the appbar shadow for now, since this part will need a different approach.
