### ISSUE TITLE
Products: Design bugs on product search screen

### ISSUE THREAD

**Issue by rachelmcr** [woocommerce/woocommerce-android#3259]
**Describe the bug**

As @Garance91540 reported:

When selecting search in the Product list, can we:

- Remove the bottom nav bar that’s sticky at the top of the keyboard
- Remove the Sort and Filters CTA
- Remove the “Create Products” CTA
- Remove the search icon in the search bar
- Add a text indicator in the search bar to convey to users they can start typing in the bar directly
- This is an improvement and can be tackled later, but on Android I noticed we don’t start showing products in the product list until users have at entered at least 3 letters in the search field. On iOS, we start by displaying the full product list when the search bar is empty and then start updating it as soon as there’s one letter entered

**Screenshots**

This is the screen I see:

<img src="https://user-images.githubusercontent.com/8658164/100909587-d3686280-34c4-11eb-94d7-fe7d3cd140dc.png" width="300px">

**Expected behavior**

Design:

<img src="https://user-images.githubusercontent.com/8658164/100909594-d6635300-34c4-11eb-81b9-619e1e5b3b1c.png" width="300px">

**Mobile Environment**
Please include:
- Device: 
- Android version: 
- WooCommerce Android version: 5.6-rc-1

**Comment by shiki** [comment]
This was reported by @Garance91540 again in p5T066-2p8-p2#comment-8863. Though more specifically for the empty screen but I think they're related. 

> On product and order search empty states pages, can we:
> 
> hide the bottom nav bar
> remove the “Add product” CTA


<img src="https://user-images.githubusercontent.com/198826/123458916-d206a080-d5a2-11eb-962f-a790a8968c0b.png" width="300">
