### ISSUE TITLE
Chart legend text cut off when there is negative revenue displayed in the charts

### ISSUE THREAD

**Issue by 0nko** [woocommerce/woocommerce-android#3271]
My Store chart legend's bottom keys are cut off.

![image](https://user-images.githubusercontent.com/1522856/100992759-dad74c80-3554-11eb-9c30-a1b1554b91d9.png)

**Comment by anitaa1990** [comment]
We have recently shifted to a line chart and this issue seems to not occur anymore in the latest version of the app so will mark it as closed.
