### ISSUE TITLE
Inconsistent header dividers on detail screens (product, order, review)

### ISSUE THREAD

**Issue by rachelmcr** [woocommerce/woocommerce-android#3273]
**Describe the bug**

The headers on product details, order details, and review details are inconsistent:

* Product detail and review detail always show a drop shadow (unless you rotate the device)
* If you rotate the device, the drop shadow on product and review detail screens disappears (no divider appears at all)
* Order detail never shows a divider or drop shadow

**To Reproduce**
1. Go to the Products tab.
2. Select a product. Notice that a drop shadow is immediately visible (instead of a divider without drop shadow).
3. Rotate the device. Notice the drop shadow disappears and no divider appears even when you scroll.
4. Go back and navigate to the Reviews tab.
5. Select a review. Notice that a drop shadow is immediately visible (instead of a divider without drop shadow).
6. Rotate the device. Notice the same behavior as with product details.
7. Go back and navigate to the Orders tab.
8. Select an order. Notice there is no header divider, and no drop shadow appears when you scroll.

**Screenshots**

Order detail|Product detail|Review detail
-|-|-
<img src="https://user-images.githubusercontent.com/8658164/101012741-2f7dc600-355b-11eb-99ae-32d663ff5825.png" width="300px">|<img src="https://user-images.githubusercontent.com/8658164/101012733-2db40280-355b-11eb-85ae-a460f80976b0.png" width="300px">|<img src="https://user-images.githubusercontent.com/8658164/101012740-2ee52f80-355b-11eb-8433-792578dd6f99.png" width="300px">

**Expected behavior**

By default, the 3 headers should have a divider without drop shadow but on scroll, the drop shadow appears (similarly to the Order, Product and Review list behavior). (internal ref: p5T066-1Er-p2#comment-6472)

![image](https://user-images.githubusercontent.com/8658164/101012685-1b39c900-355b-11eb-822a-9c5a1d8ddb71.png)

**Mobile Environment**
Please include:
- Device: moto e5 play
- Android version: 8.1.0
- WooCommerce Android version: 5.6-rc-1

**Comment by anitaa1990** [comment]
I am no longer able to reproduce this issue in the Orders tab. I can see the drop shadow when clicking on the Order detail and rotating the device removes the drop shadow. I'll mark this issue as closed since it looks to be fixed 👍
