### ISSUE TITLE
Search: Missing cursor in search views

### ISSUE THREAD

**Issue by rachelmcr** [woocommerce/woocommerce-android#3275]
**Describe the bug**

In Products and Orders, the search field doesn't display a cursor or otherwise indicate when the search field has focus. It's still possible to type and perform a search, but that isn't obvious since there's no indication the field is selected.

**To Reproduce**
1. Go to the Products or Orders tab.
2. Tap the search icon in the top right.
3. Notice there is no cursor in the search field.
4. Try tapping in the search field and notice there is no change.
5. Confirm you can type to perform a search.

**Screenshots**

Orders search|Products search
-|-
<img src="https://user-images.githubusercontent.com/8658164/101037163-213ba400-3573-11eb-9822-09a59ccb0617.png" width="300px">|<img src="https://user-images.githubusercontent.com/8658164/101037181-226cd100-3573-11eb-97ea-b8d309dc59eb.png" width="300px">

**Mobile Environment**
Please include:
- Device: moto e5 play
- Android version: 8.1.0
- WooCommerce Android version: 5.6-rc-1 (confirmed this is a new issue as of 5.6)

**Comment by shiki** [comment]
Fixed in the 5.6 release branch (#3277). Thanks, Nick!
