### ISSUE TITLE
Search: Extra space appears under search field

### ISSUE THREAD

**Issue by rachelmcr** [woocommerce/woocommerce-android#3276]
**Describe the bug**

Scrolling to the top of the search screen makes extra space appear in the header under the search field.

**To Reproduce**
1. Go to the Products or Orders tab.
2. Tap the search icon in the top right.
3. Scroll down a little.
4. Scroll back to the top of the screen and notice some white space appears under the search field.

**Screenshots**

Screencast: https://cloudup.com/cECQjqb4HSH

Orders search|Products search
-|-
<img src="https://user-images.githubusercontent.com/8658164/101039549-c8b8d680-3573-11eb-885d-ecdbff39a2c3.png" width="300px">|<img src="https://user-images.githubusercontent.com/8658164/101039580-ca829a00-3573-11eb-8b37-7b78a0a774ec.png" width="300px">

**Mobile Environment**
Please include:
- Device: moto e5 play
- Android version: 8.1.0
- WooCommerce Android version: 5.6-rc-1

**Comment by shiki** [comment]
Fixed in the 5.6 release branch via #3278. Thanks, Nick!
