### ISSUE TITLE
MPAndroidChart library does not yet support RTL

### ISSUE THREAD

**Issue by AmandaRiu** [woocommerce/woocommerce-android#329]
There is already an [open ticket on their end](https://github.com/PhilJay/MPAndroidChart/issues/3109), this ticket is just to track and followup for eventual fixes (hopefully).

**Comment by nbradbury** [comment]
[The MPAndroidChart issue](https://github.com/PhilJay/MPAndroidChart/issues/3109) mentioned above received a reply from one of the devs:

> Graphs and Charts should not be mirrorred according to the RTL guidelines. So this seems expected. You can read more about what gets mirrorred and what not here - https://material.io/design/usability/bidirectionality.html#mirroring-layout

I checked that Material link and it does state not to mirror charts, so I'm closing this issue.

> <img width="492" alt="screen shot 2019-02-18 at 9 33 16 am" src="https://user-images.githubusercontent.com/3903757/52957709-4b9d7c80-3360-11e9-988b-edcfddb80ed8.png">
