### ISSUE TITLE
Android Accessibility - Ensure animations have RTL versions

### ISSUE THREAD

**Issue by AmandaRiu** [woocommerce/woocommerce-android#330]
Audit current animation/drawable's, and consider whether it needs to be mirrored in RtL mode (Use ldrtl drawable selector - example drawable-ldrtl-v18). Once that is complete, fill in the gif's to demonstrate this feature in the [wiki](https://github.com/woocommerce/woocommerce-android/wiki/Right-to-Left-layout-guidelines).

**Comment by anitaa1990** [comment]
This is being implemented as part of the current project work so will close this for now
