### ISSUE TITLE
AddOrderShipmentTrackingFragment "Add" menu item disappears upon rotation

### ISSUE THREAD

**Issue by nbradbury** [woocommerce/woocommerce-android#3308]
To reproduce:

- Go to order detail and choose to add tracking
- Choose a carrier
- Rotate the device
- Notice the "Add" menu no longer appears

**Comment by hichamboushaba** [comment]
This is related to #3296, and should be fixed when #3303 is merged.

**Comment by hichamboushaba** [comment]
Fixed by #3303
