### ISSUE TITLE
Order Details: Note list stuck in loading

### ISSUE THREAD

**Issue by AmandaRiu** [woocommerce/woocommerce-android#3313]
**Describe the bug**
Open an order that hasn't been downloaded yet and quickly scroll down to the notes list and a few things will happen: 
- The view jumps a couple times as other cards are loaded.
- The notes will load and display but then suddenly the order notes loading skeleton activates and stays that way indefinitely. 

**This issue is new in the `develop` branch (not a problem in 5.5 or 5.6 versions).**

**To Reproduce**
1. Start with a fresh install of the app and log in
2. Click on the orders tab and tap on an order to open it's detail
3. Quickly scroll to the bottom of the view - notice the loading jumps mentioned. 
4. Notice how the notes will load and become visible only to be replaced by the loading skeleton again

**Screenshots**
![ezgif com-gif-maker (2)](https://user-images.githubusercontent.com/5810477/101836378-4d26ce80-3b0b-11eb-913d-277d40855d33.gif)

**Expected behavior**
Order notes load and remain loaded and visible

**Comment by AmandaRiu** [comment]
Spent a bunch of time troubleshooting this and while I'm still mystified as to _why_ this is happening, I have been able to figure out what the change was that started causing this issue. This PR made a bunch of changes to `OrderDetailViewModel` but the one that seems to be causing the problem is calling `loadOrderProducts()` without wrapping it in `launch {  }`. This method eventually calls `WCProductStore.fetchProductListSynced()` and I'm not sure of the background of this method, but it does lead to StrictMode violations for writing to the db on the main thread. I'm not sure if that has anything to do with the issue, but that particular portion is definitely the culprit.

@0nko These changes happened in your[ PR for updating the order detail UI for shipping labels.](https://github.com/woocommerce/woocommerce-android/pull/3110). I know what fix will work, but I don't know why these changes were made so I don't want to mess something else up further down the line. Can you take a look at this one?

**Comment by hichamboushaba** [comment]
I noticed the same thing, and was planning to create an issue for it 🙂.

I think two things cause the issue, the fact that `loadOrderNotes` is not suspending anymore, and uses a `launch { }` to run its work, and this line of code here:
https://github.com/woocommerce/woocommerce-android/blob/06a75a17a4028593746d11b90714ef5c2e617524/WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/details/OrderDetailViewModel.kt#L162
Which means that we copy the state having `isOrderNotesSkeletonShown = true` in the local variable, and then use it for the next lines: https://github.com/woocommerce/woocommerce-android/blob/06a75a17a4028593746d11b90714ef5c2e617524/WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/details/OrderDetailViewModel.kt#L163-L164
And when we run `orderDetailViewState = viewState` we lose the fact that `isOrderNotesSkeletonShown` was changed to false.
I think the fix would be just to avoid saving the viewState in the local variable, and instead always pass it to the liveData, to make sure we use the latest value everywhere.

**Comment by 0nko** [comment]
Thanks @AmandaRiu, @hichamboushaba. Incidentally, I've noticed the issue yesterday myself :). 

Just to give you some background -- I've added the local `viewState` variable and passed it around multiple sources are changing what's visible and what's not. If the Shipping labels are available, then tracking is hidden. If all products are refunded, then the products card is hidden, etc. So when a user opened the order detail before (and there were already data in the DB), the views were jumping up and down as different data were being reloaded. To prevent this, I added the workaround to only update the view state once. This was meant as a temporary solution. I've been meaning to consolidate the whole loading logic so that it's split up by cards/sections to solve the problem.

**Comment by hichamboushaba** [comment]
I think we can also move the `isOrderNoteSkeletonShown` to a new state class, which holds this and the notes list, this should help avoiding race condition bugs, and would keep the main `viewState` smaller and easier to understand.

**Comment by AmandaRiu** [comment]
Removing myself as assignee. Talked to @0nko and since he's most familiar with this code he'll be taking a look at it to implement a fix.

**Comment by anitaa1990** [comment]
Fixed in #3330
