### ISSUE TITLE
Issue Refunds: Enable shipping refund

### ISSUE THREAD

**Issue by Ecarrion** [woocommerce/woocommerce-android#3319]
iOS has validated that refunding shipping via the rest API is possible.
We should enable this feature to provide the same experience as the iOS app.

Ref: p91TBi-3hR-p2

**Comment by hafizrahman** [comment]
Going to split this feature into smaller tasks/PRs:

- [x] Update FluxC Android to include shipping line items required to get the data. ([FluxC PR 1892](https://github.com/wordpress-mobile/WordPress-FluxC-Android/pull/1892))
- [x]  Update `Order.kt` to include information related to shipping line items ([PR 3648](https://github.com/woocommerce/woocommerce-android/pull/3648))
- [x] Work on the UI to support shipping refund ([PR 3666](https://github.com/woocommerce/woocommerce-android/pull/3666))
- [x] Add functionality to do the actual refund ([PR 3825](https://github.com/woocommerce/woocommerce-android/pull/3825))
- - [x] Discovered that API response from shipping refund treats refunded shipping line separately, so made a FluxC PR to handle it. ([FluxC PR 1948](https://github.com/wordpress-mobile/WordPress-FluxC-Android/pull/1948/))

**Comment by anitaa1990** [comment]
Closed via #3825
