### ISSUE TITLE
Pull-to-refresh Takes A Long Time To Finish

### ISSUE THREAD

**Issue by shiki** [woocommerce/woocommerce-android#3335]
I'm on version 5.7-rc-1 from Google Play (Beta?). I can confirm that this does not happen on 5.5 and 5.6.

## Steps to Reproduce

1. Pull to refresh on All Orders tab.

It takes forever on Android but about 4 seconds on iOS. 

However, if I do this, it finishes quickly:

1. Pull to refresh
2. Rotate to landscape.
3. Rotate back to portrait.

The loader animation disappears after 1 second. 

---

FYI @woocommerce/android-developers

**Comment by AmandaRiu** [comment]
Also noticed that when you scroll down the order list and then try to scroll back up, the list will not allow you to scroll up and instead initiates a PTR -- but the request is never submitted when looking at Flipper. 

Here's a gif:

![ezgif com-gif-maker](https://user-images.githubusercontent.com/5810477/102415513-4e05a780-3fc6-11eb-8de3-8f6d9e05f0dc.gif)

**Comment by anitaa1990** [comment]
Fixed in #3337
