### ISSUE TITLE
Login: Extra magic link login step & password option should be removed for passwordless accounts in site address/credentials login flow

### ISSUE THREAD

**Issue by rachelmcr** [woocommerce/woocommerce-android#3341]
**Describe the bug**

Per the changes in https://github.com/woocommerce/woocommerce-android/pull/3268, when logging in to the app with a passwordless WordPress.com account I expect to skip the extra magic link login step and not see a password option.

However, I still see the old login flow (with the extra magic link login step and password option) if I log in with a site address and enter my site credentials first.

**To Reproduce**
1. Start logged out of the app.
2. Select the site address login option.
3. Enter your site address.
4. Select the option to enter your site credentials.
5. Enter your site credentials.
6. Enter the email address for a passwordless WordPress.com account.
7. Notice you are taken to a screen where you can request a magic link or enter a password (which you don't have).
8. Request the magic link and notice on the next screen you also have the option to enter a password.

**Mobile Environment**
Please include:
- Device: moto e5 play
- Android version: 8.1.0
- WooCommerce Android version: 5.7-rc-1

**Comment by ravishanker** [comment]
This doesn't seem to happen anymore.  I've also confirmed with @rachelmcr by retesting it.  We've agreed to close it for now.
