### ISSUE TITLE
Dark done button on product selection fragment

### ISSUE THREAD

**Issue by nbradbury** [woocommerce/woocommerce-android#3347]
When selecting products (such as adding products to a grouped product), the Done button is dark and doesn't stand out. Either the toolbar needs to remain white, or the Done button needs to be made white.

![Screenshot_20201218_072346](https://user-images.githubusercontent.com/3903757/102614469-49460e00-4102-11eb-8e1d-ca2da7d1aef4.png)

**Comment by anitaa1990** [comment]
A separate issue was opened for this in #3431 so closing this one
