### ISSUE TITLE
Orders: Order list unexpectedly appears on other tabs after rotating device

### ISSUE THREAD

**Issue by rachelmcr** [woocommerce/woocommerce-android#3356]
**Describe the bug**

After loading the orders list in the app and rotating the device, the order list appears on other tabs (My store, Products, Reviews) while they are loading. The orders remain on screen on the My store and Reviews tab even after the tab finishes loading.

**To Reproduce**
1. Launch the app (the behavior is most visible if you force-close the app first and then relaunch it).
2. Open the Orders tab and wait for the order list to load.
3. Open the My store tab.
4. Rotate your device between landscape and portrait. Notice the order list now appears overlaying the store stats.
5. Open the Products tab. Notice the order list appears until the product list loads to replace it.
6. Open the Review tab. Notice the review list appears but it is overlaying the order list.

**Screenshots**

<img src="https://user-images.githubusercontent.com/8658164/102634995-92ba4b80-414a-11eb-990b-1db37839e71c.gif" width="300px">

**Mobile Environment**
Please include:
- Device: moto e5 play
- Android version: 8.1.0
- WooCommerce Android version: 5.7-rc-1

**Comment by shiki** [comment]
Fixed by @hichamboushaba in #3395
