### ISSUE TITLE
FAB appears on product category screen after rotating device

### ISSUE THREAD

**Issue by nbradbury** [woocommerce/woocommerce-android#3359]
Steps to reproduce:

- Open product detail
- Tap "Add more details" and choose Categories
- After categories appears, rotate the device

The FAB from the product list now shows on the Categories screen.

**Update:** This is happening on all the product detail screens, not just categories.

![Screenshot_20201218_134531](https://user-images.githubusercontent.com/3903757/102649721-b45e0780-4137-11eb-9bc9-112f8c9af424.png)

**Comment by anitaa1990** [comment]
Fixed in #3360
