### ISSUE TITLE
Hack Week: Editable text, labels and Grouping for Accessibility

### ISSUE THREAD

**Issue by AmandaRiu** [woocommerce/woocommerce-android#336]
Do an audit and verify the following rules are used where needed and fix if not compliant:

- When labeling editable elements, such as EditText objects, use the android:hint XML attribute for static elements and the setHint() method for dynamic elements to indicate each element's purpose.
- Group related view clusters for easier TalkBack navigation

**Comment by anitaa1990** [comment]
I'd prefer to close this issue since looking at and fixing accessibility related issues has become a part of the project process and we continue to prioritise and track those issues separately.
