### ISSUE TITLE
Top level fragments overlap when do not keep activities is enabled

### ISSUE THREAD

**Issue by anitaa1990** [woocommerce/woocommerce-android#3369]
There are a bunch of overlaps happening in the top level fragments (MyStore, Orders, Products, Reviews). This thread summarises some of the steps to reproduce the different overlaps happening.

**Enable `Do not keep activities`** 

#### Issue 1
- Enable Do not keep activities on the device and open the app.
- Click on the Orders tab.
- Click on the My Store tab.
- Click on the Reviews tab and rotate the screen.
- Notice there is an overlap between reviews and orders.

<img src="https://user-images.githubusercontent.com/22608780/102882810-0030e980-4475-11eb-9244-024319af314b.gif" width="300"/>

#### Issue 2
- Enable Do not keep activities on the device and open the app.
- Click on the Orders tab.
- Click on the My Store tab.
- Click on the Settings icon and click on the back button.
- Notice there is an overlap between the Orders and My Store tabs.

<img src="https://user-images.githubusercontent.com/22608780/102882978-3ff7d100-4475-11eb-8d01-26a81cc18dbb.gif" width="300"/>

**Comment by AmandaRiu** [comment]
I did some initial testing and it's hard to say 100% since it's difficult to reproduce, but it seems to have started in 5.6.3 (I can't seem to reproduce it in 5.6.2, but as I said it's difficult to reproduce so it may still be happening). That doesn't seem to make much sense since [very little happened between those two versions](https://github.com/woocommerce/woocommerce-android/compare/5.6.2...5.6.3).

**Comment by anitaa1990** [comment]
I updated the issue with some screenshots and better descriptions. I was able to replicate the overlap issue when I click on another tab before the data is loaded in the Products tab. (Keep note that we need to enable "Do not keep activities" as well).

**Comment by designsimply** [comment]
What a weird 🐛 ! I ran into it during 5.8-rc-1 beta testing and wrote down some testing steps and took a few screenshots.

1. In the app, go to Reviews.
1. On the device, go to Settings > Display > Advanced > Font size and set the font to the largest size available. 
1. On the device, go to Settings > System > Languages and input > Languages and switch to another language.
1. Go back to the app.
1. Observe that some of the elements from other screens overlap after the device screen refreshes.

**Result:** most of the time just the + icon at bottom right appears but at least once a few of the no results screens overlapped and looked jumbled. ([1m36s](https://cloudup.com/csmiKh9vFMf))

**Note:** the "Don't keep activities" setting is off in my case ([screenshot](https://user-images.githubusercontent.com/1119271/104516818-3237f600-55b2-11eb-8498-212ae0cff6af.png)), so the force refresh after the systems settings changes is probably what triggers it in my case.

Seems to happen periodically in different ways, here are a few examples: 

NoResults Overlap|Reviews+Stats Overlap|Add Product button overlaps Reviews
---|---|---
![Screenshot_20210113-134805](https://user-images.githubusercontent.com/1119271/104515736-6d392a00-55b0-11eb-8bb4-92b09ce2439f.png)|![Screenshot_20210113-140124](https://user-images.githubusercontent.com/1119271/104516524-b8077180-55b1-11eb-9e09-1873e88fb2e2.png)|![Screenshot_20210113-143823](https://user-images.githubusercontent.com/1119271/104516564-c786ba80-55b1-11eb-9f0b-ff00a8a22cc1.png)

<sup>
• Device: Pixel 3<br>
• Android version: Android 11<br>
• WooCommerce Android version: WordPress.com
</sup>

**Comment by designsimply** [comment]
This came up again during 5.8 beta testing. @nbradbury reported:

<blockquote>
* Go to the product list<br>
* Go back to My Store<br>
* Tap the settings icon<br>
* Change the Appearance<br>
* Go back to My Store again<br>
<br>
After doing this the FAB from product detail appears on My Store.</blockquote>

<img src="https://user-images.githubusercontent.com/1119271/104665689-4140a600-568f-11eb-8b6b-22cf69bf6439.png" width="270" alt="bug">

<sup>(internal reference: p5T066-1Ia-p2#comment-6747)</sup>

**Comment by anitaa1990** [comment]
Assigned the issue to @hichamboushaba since there's work being done in #3411 to fix this
