### ISSUE TITLE
switch on notification

### ISSUE THREAD

**Issue by cfranc3sc0s92** [woocommerce/woocommerce-android#3373]
Hi guys, i try to find a way to auto switch order tab when come notification of order.

I try to set a var on fcm message receive and then how can i switch tab if variable are 1(there are processing order)?

var = 1  processing
var= 0 no-processing (all-order)

thanks

**Comment by anitaa1990** [comment]
Thank you for using the Woo Mobile app @cfranc3sc0s92! I don't think this is possible with our current implementation of notifications. We don't process feature requests on GitHub but if you'd like to suggest something, please go to [this link](http://ideas.woocommerce.com/forums/133476-woocommerce?category_id=84283) to either up-vote this feature on the ideas board, or to add a new feature request if it doesn't already exist.
