### ISSUE TITLE
Settings menu option visible in Product Details when opened from My Store

### ISSUE THREAD

**Issue by AmandaRiu** [woocommerce/woocommerce-android#3377]
**Describe the bug**
The settings menu option is visible when opening a product from the Top Performers card on the My Store tab.

https://user-images.githubusercontent.com/5810477/103298626-bdb56280-49c8-11eb-93d3-ba4bc45569c4.mp4

**To Reproduce**
1. Go to **My Store** tab
2. Click on a product in the top performers list to open it's detail
3. Note the settings icon visible in the action bar

**Screenshots**
<img src="https://user-images.githubusercontent.com/5810477/103298563-a0809400-49c8-11eb-8e14-92bfcf3539a1.jpg" width="320"/>

**Expected behavior**
The settings menu option is not visible.

**Comment by anitaa1990** [comment]
I can confirm that this issue is fixed in #3446 from the top level fragment refactoring 👍

**Comment by 0nko** [comment]
Fixed by #3446.
