### ISSUE TITLE
New product displayed along with the empty screen and it is not clickable

### ISSUE THREAD

**Issue by anitaa1990** [woocommerce/woocommerce-android#3385]
When a new product is added to a store that has no products, the empty screen is displayed along with the product that is added.

### To reproduce
- Login to a store with no products.
- Click on the Products TAB and click on the `Add Product` button.
- Add a new product and click on `Save a draft`.
- Click on the back button and notice the new product is displayed along with the empty screen.
- Now try to click on the product and notice it is not clickable.

<img src="https://user-images.githubusercontent.com/22608780/103502801-6d327f00-4e78-11eb-8ba4-957bb4910dd7.gif" width="300"/>

**Comment by AliSoftware** [comment]
This might be related to https://github.com/woocommerce/woocommerce-android/issues/3046 that I opened back in 5.2?

**Comment by anitaa1990** [comment]
You're right 😅 I failed to check the backlog for open issues before opening this one. I'll close this in favour of #3046
