### ISSUE TITLE
When a product is trashed (and there are no products in the store), the product list screen is blank

### ISSUE THREAD

**Issue by anitaa1990** [woocommerce/woocommerce-android#3386]
#### To reproduce
- Login to a store with only 1 product.
- Click on the Products tab and click on the product.
- Trash this product.
- Notice the product list screen is blank when we should display the empty screen.

<img src="https://user-images.githubusercontent.com/22608780/103502993-fc3f9700-4e78-11eb-8d8e-55c8afdab8e3.gif" width="300"/>

**Comment by AliSoftware** [comment]
This might be related to https://github.com/woocommerce/woocommerce-android/issues/3046 that I opened back in 5.2?
