### ISSUE TITLE
Product is not downloadable but downloadable files option is displayed in the bottom sheet

### ISSUE THREAD

**Issue by anitaa1990** [woocommerce/woocommerce-android#3389]
#### To reproduce
- Click on `Add Product` button in the Products tab.
- Select a product type.
- Click on the `Add More details` button at the bottom of the screen.
- Notice the `Downloadable files` section is displayed but when you click on the Product Settings, the `downloadable` switch is turned off.

We should only display the `Downloadable` files section if the `downloadable` switch is turned on.

<img src="https://user-images.githubusercontent.com/22608780/103503899-cbad2c80-4e7b-11eb-838e-b607d79d363e.gif" width="300"/>

**Comment by hichamboushaba** [comment]
@anitaa1990 regarding this issue, I remember that we had a discussion about making the change to make the product downloadable automatically when the user adds some files, I think this was it: https://github.com/wordpress-mobile/WordPress-FluxC-Android/pull/1663#discussion_r469107332

So if this is still the UX behavior that we want, this is not a bug.

**Comment by anitaa1990** [comment]
@hichamboushaba, thanks for the context! If we want to align with Core, the web displays downloadable files section only if the downloadable switch is on. Should we follow a similar approach in the app as well @Garance91540 WDYT?

**Comment by Garance91540** [comment]
Given the fact that the downloadable switch is a bit hard to find (need to go to settings and then enable the switch before being able to add files), I think it might be more discoverable and intuitive to keep the UX as we have it (allow users to add downloadable files in all cases).

**Comment by anitaa1990** [comment]
Sounds good 👍 Will close this issue.
