### ISSUE TITLE
Clean up errant SDK < 21 version check switches

### ISSUE THREAD

**Issue by aforcier** [woocommerce/woocommerce-android#341]
With #340 merged, `minSdkVersion` is `21`, but we still have switches in several areas of the codebase checking for versions older than `21`. We can't remove those without creating lint errors, because the login library still has a lower `minSdkVersion`.

Once the login library has been updated to `minSdkVersion 21` as well, we can update the login subtree and then we can remove all our own checks.

**Comment by anitaa1990** [comment]
The login library `minVersion` has been updated to 21 and we no longer have checks in the app for versions below 21 so closing this issue 👍
