### ISSUE TITLE
Products: Cannot save changes to Downloadable files > Download Settings

### ISSUE THREAD

**Issue by designsimply** [woocommerce/woocommerce-android#3435]
Steps to reproduce:

1. Go to Products and tap on a product that has a downloadable file (add one if needed).
1. Tap on the "Downloadable files" detail.
1. Tap the overflow menu > Download Settings.
1. Make changes to "Download limit" and "Download expiration".
1. Tap "Done" at top right.
1. Tap the overflow menu > Download Settings again.
1. Observe that the changes from step 4 are gone.

**Results:** if you make changes to Downloadable files > Download Settings and tap DONE the changes are not saved. ([58s](https://cloudup.com/cSiZRC4IuX7))

<img src="https://user-images.githubusercontent.com/1119271/104670146-8ae1be80-5698-11eb-9f48-9756ea67c69f.png" width="270" alt="image">

<sup>Tested with WCAndroid 5.8-rc-1 on Pixel 3 Android 11 with site testingallthetime.com WordPress 5.6 WooCommerce 4.9.0 Jetpack 9.3.1 logged in as design5279.</sup>

**Comment by anitaa1990** [comment]
Fixed in #3441
