### ISSUE TITLE
FAB shows on My Store

### ISSUE THREAD

**Issue by nbradbury** [woocommerce/woocommerce-android#3442]
- Go to the product list
- Go back to My Store
- Tap the settings icon
- Change the Appearance
- Go back to My Store again

After doing this the FAB from product detail appears on My Store.

![fab](https://user-images.githubusercontent.com/3903757/104763318-afd73f80-5733-11eb-85b6-f1665b363c8f.png)

**Comment by anitaa1990** [comment]
Closed via #3443
