### ISSUE TITLE
Top Performers not filtering duplicated information

### ISSUE THREAD

**Issue by ThomazFB** [woocommerce/woocommerce-android#3460]
**Describe the bug**
Sometimes the Top Performers view at the `My Store` section shows the same Top Performer product twice.

**To Reproduce**
It still not clear when the site returns duplicated product information from the Top Performers endpoints, so there's no reliable way to reproduce that, so this step by step is just a suggestion about how normally this issue have been reproduced
1. Go to the Woo app at the `My Store` section and make sure the `Today` tab is selected (preferably make sure that no order was created)
2. Go to the Woo site and make a single order with a single product
3.Go back to the Woo app and do a scroll refresh
4. Verify if the same product shows up twice

**Screenshots**
![screenshot-1610706461726](https://user-images.githubusercontent.com/5920403/105244404-3d10fe80-5b4f-11eb-8cd2-91b3c5bb50d7.jpg)

**Comment by ThomazFB** [comment]
Fix merged on FluxC but still not updated on Woo, keeping the issue open until then.

**Comment by anitaa1990** [comment]
Thanks @ThomazFB! I opened a PR in #3514 to update Woo as well :)
