### ISSUE TITLE
Product and Order data loading issues when passing the search query parameter into a request

### ISSUE THREAD

**Issue by ThomazFB** [woocommerce/woocommerce-android#3470]
**Describe the bug**
Some merchants using our app are reporting of ocasional problems loading data from the site, this was caused by an issues between our app and the site where we request data passing the `search` parameter into the URL even when there's no search query to inform, causing some very specific sites to return.

**To Reproduce**
Sites affected by this aren't able to load Orders and Products properly so it's pretty easy to reproduce the problem,  the hard part is to be able to come up with a Woo Store site with the exact same configuration issue since it still not clear why only some sites behave like this. The main suspicion is plugin related problems.

**Comment by anitaa1990** [comment]
@ThomazFB @nbradbury should this issue be closed since the FluxC hash from [this PR](https://github.com/wordpress-mobile/WordPress-FluxC-Android/pull/1852) has not yet been updated to the Woo app?

**Comment by nbradbury** [comment]
@anitaa1990 Sorry, didn't realize merging that FluxC PR would close this. I'll reopen it.

**Comment by anitaa1990** [comment]
It looks like a new FluxC version was released ([1.9.0](https://github.com/wordpress-mobile/WordPress-FluxC-Android/releases/tag/1.9.0)) and this was updated to the [release branch in 5.9](https://github.com/woocommerce/woocommerce-android/blob/release/5.9/build.gradle#L88) so closing this issue. Thanks @ThomazFB and @nbradbury!
