### ISSUE TITLE
Remove IssueRefundFragment

### ISSUE THREAD

**Issue by nbradbury** [woocommerce/woocommerce-android#3489]
`IssueRefundFragment` is currently only used as a host for `RefundByItemsFragment`. It was kept around because we'll likely need it in the future, but we should remove it for now. If we need it again, we can always restore it from the git history.

**Comment by malinajirka** [comment]
We decided to close this issue - more info https://github.com/woocommerce/woocommerce-android/pull/3707#issuecomment-801225658
