### ISSUE TITLE
Restore the feature to display product SKU from order details

### ISSUE THREAD

**Issue by reginabally** [woocommerce/woocommerce-android#3513]
There are some support requests we received pertaining to the product SKU removal from the order details screen on WCAndroid app.

I'm opening this issue to keep track of the interests of the users after what's been discussed in p1611679715074100-slack-C6H8C3G23.

Requested in:

* 3649444-zen
* 3686017-zen
* 3661334-zen

For now, we'll suggest the users view the product SKUs through the new order notification emails.

**Comment by shiki** [comment]
@anitaa1990 I see that you assigned yourself to this. Have we decided to place it back? Do we have designs for them? 

I could not follow the Slack link. For some reason, it just leads me to a testing post but there's no mention of SKUs. 

cc @Garance91540

**Comment by rossanafmenezes** [comment]
I have another request from the Apps review 

User:TheBlackHero Global
Date: Jan 30, 2021, 19:23
Woo App on Google Reviews 
App version code: 185
App version name: 5.6.3
Android version (SDK): Android 9 (SDK 28)

**Comment by anitaa1990** [comment]
@shiki, There is an open Slack discussion in the `mobile-woo` channel `p1611679715074100?thread_ts=1603300396.040400`.

This is the updated design @Garance91540 shared:

<img src="https://user-images.githubusercontent.com/22608780/106548567-3f9f2b00-6535-11eb-80a6-40106c87eea3.png" width="300"/>

I also shared the Slack link to you in DM :)
