### ISSUE TITLE
Product search inconsistencies

### ISSUE THREAD

**Issue by 0nko** [woocommerce/woocommerce-android#3550]
The product search results are inconsistent. In the following video, you can see that the term "produ" first lists some products and then it doesn't. The point is to start typing right after the delay, while the search is in progress.

![Android-Emulator-Pixel-2-API-29](https://user-images.githubusercontent.com/1522856/107504794-1bc68f80-6b9c-11eb-90d6-42477d434a88.gif)

**Comment by anitaa1990** [comment]
I tested this with the latest version of the app and could not reproduce it. So will mark it closed for now
