### ISSUE TITLE
Implement Encrypted Logging

### ISSUE THREAD

**Issue by shiki** [woocommerce/woocommerce-android#3557]
C6H8C3G23-p1612984324336700-slack

Encrypted Logging is already implemented in iOS. We can probably use the WPAndroid implementation for reference https://github.com/wordpress-mobile/WordPress-Android/pull/12571. 

Available for consult: @oguzkocer

**Comment by wzieba** [comment]
Blocked by https://github.com/woocommerce/woocommerce-android/issues/3883
