### ISSUE TITLE
Add the app version to the in-app survey metadata

### ISSUE THREAD

**Issue by shiki** [woocommerce/woocommerce-android#3558]
Info about In-app Feedback: P91TBi-4rY-p2

This can be added as a custom tag like https://github.com/woocommerce/woocommerce-android/issues/3045. 

Please make sure that the same field is used for both iOS and Android.

---

iOS: https://github.com/woocommerce/woocommerce-ios/issues/3644

**Comment by momo-ozawa** [comment]
@wzieba (cc: @shiki) 
Just a heads up that I'm using`app-version` as the tag name!
iOS PR: https://github.com/woocommerce/woocommerce-ios/pull/3659

**Comment by wzieba** [comment]
thanks for the ping @momo-ozawa !

**Comment by shiki** [comment]
Thank you for working on the iOS task, @momo-ozawa! And thank you for communicating what needs to be added for Android. 🙏
