### ISSUE TITLE
Product Type: Display "Downloadable" if product is downloadable

### ISSUE THREAD

**Issue by momo-ozawa** [woocommerce/woocommerce-android#3569]
Show "Downloadable" when a product's `downloadable` flag is on. 

- If `downloadable` is on, show "Downloadable"
- If `downloadable` is off:
  - If `virtual` is on, show "Virtual"
  - If `virtual` is off, show "Physical"

iOS ref: https://github.com/woocommerce/woocommerce-ios/issues/3477

**Comment by hafizrahman** [comment]
I'm taking a look at this.
