### ISSUE TITLE
Notifications: no push notification is shown for a support request reply if there is no previous support ticket history

### ISSUE THREAD

**Issue by designsimply** [woocommerce/woocommerce-android#3574]
I noticed that I don't get a push notification the very first time I receive a reply from 'Help & Support' even though I get one for every reply after that.

Steps to reproduce:

1. Go to My Store > Settings > Help & support > Contact email.
1. Enter a new email address (this will have the effect of removing any past ticket history).
1. Create and send a new message.
1. Navigate to any other area of the app and background or close the app.
1. Log in to Zendesk and respond to the message or wait for a response from a happiness engineer.

**Result:** no push notification is received for the first reply to a support request. If you reply again to the same support ticket or create another one, push notifications start working at that point—it's only the first one that is missing the notification! (3m33s)

First message in message history|My message has been delivered|A reply has been sent from Zendesk but no push notification arrives|Browse to the tickets page and observe the message did get a reply
---|---|---|---
![image](https://user-images.githubusercontent.com/1119271/108004233-7d2e9a00-6fb2-11eb-9c61-fd85d02d8e9f.png)|![image](https://user-images.githubusercontent.com/1119271/108004255-89b2f280-6fb2-11eb-9b80-826c3b384b3f.png)|![image](https://user-images.githubusercontent.com/1119271/108004266-9df6ef80-6fb2-11eb-8327-03bb2c4f687f.png)|![image](https://user-images.githubusercontent.com/1119271/108004298-b9fa9100-6fb2-11eb-9c4d-99ce9065ffd9.png)

<sup>Tested with WCAndroid 6.0-rc-2 on Pixel 3 Android 11.</sup>

**Comment by shiki** [comment]
Upgrading the Zendesk SDK (https://github.com/woocommerce/woocommerce-android/issues/3555) might fix this. 

@wzieba Please also check if this is fixed after upgrading the SDK.
