### ISSUE TITLE
Order Details: shipment tracking rows are highlighted when tapped but they are not actionable

### ISSUE THREAD

**Issue by designsimply** [woocommerce/woocommerce-android#3576]
Steps to reproduce:

1. Install and activate the WooCommerce Shipment Tracking extension.
1. Open the order details for any order eligible for shipment tracking.
1. If there isn't already a tracking number, add one.
1. Try tapping on the row with the tracking number.

**Result:** rows with tracking details get highlighted when tapped which makes them seem actionable when they really aren't. ([56s](https://cloudup.com/cWfcxMntuuG))

<img src="https://user-images.githubusercontent.com/1119271/108008711-3a72bf00-6fbe-11eb-92b9-bac41bf0ca0c.gif" width="270" alt="order-details-tracking-number-row-interactions-wcandroid-6 0-rc-2">
<sup>Tested with WCAndroid 6.0-rc-2 on Pixel 3 Android 11.</sup>

**Comment by hafizrahman** [comment]
Solved in #3682
