### ISSUE TITLE
Order creation: Add order creation screen

### ISSUE THREAD

**Issue by 0nko** [woocommerce/woocommerce-android#3604]
![image](https://user-images.githubusercontent.com/1522856/108502014-6b027380-72b2-11eb-960c-928e5d6bc291.png)

The main order creation screen needs:

- [ ] New layouts and other relevant resources
- [ ] Fragment 
- [ ] ViewModel
- [ ] Data models (Customer)

**Comment by ThomazFB** [comment]
This will be tackled here for the new Order Creation project:
https://github.com/woocommerce/woocommerce-android/issues/5225
