### ISSUE TITLE
Decimal stock quantity numbers causes the products to not load

### ISSUE THREAD

**Issue by iamgabrielma** [woocommerce/woocommerce-android#3611]
Reported at 3753852-zd

Passing decimal numbers into the Stock variable causes the products page to no load in the WooCommerce app. 

While accepting integers as stock is WooCommerce's default and this enhancement request should go into the ideas forum instead, this is caused by a plugin that is sold in the WooCommerce Marketplace: https://woocommerce.com/products/measurement-price-calculator/ 

`This plugin allows you to add quantity and user-defined calculators to enable the listing of products that are sold per unit with a known measurement (for instance, tiles with an advertised square footage per box), or products which are priced by the foot, square meter, cubic yard, kilogram, etc and are purchased using a […]`

<img src="https://user-images.githubusercontent.com/3812076/108590876-5bf5f100-7398-11eb-8f50-0f390d92a2f8.jpg" width="270" alt="Screenshot_20210218-205729">

I'm not entirely sure if this is something that can be modified from the app directly, as this has been requested in WooCommerce core and the API as well, for example: https://github.com/woocommerce/woocommerce/issues/27375

**Comment by shiki** [comment]
We currently have no plans to support the Measurement Price Calculator plugin. What we can do for now is to fix the product loading problem but disable the stock quantity field. This is what we did for iOS https://github.com/woocommerce/woocommerce-ios/issues/3494. We found that we need changes from the API to fully support decimal stock quantities.

**Comment by shiki** [comment]
Related to https://github.com/woocommerce/woocommerce-android/issues/2838

**Comment by hafizrahman** [comment]
To tackle this, I'm splitting the work into multiple PRs:

- [x] Update FluxC to allow the models and API responses to accept decimal values. [Draft PR here](https://github.com/wordpress-mobile/WordPress-FluxC-Android/pull/1931).
- [x] Update Woo Mobile to make sure products with decimal values are shown properly in the app, instead of silently crashing. [Draft PR here](https://github.com/woocommerce/woocommerce-android/pull/3737).
- [x] Update Woo Mobile to make those decimal values be read-only, because updating / sending over a decimal value is not yet supported in Core API.

**Comment by designsimply** [comment]
I tested and confirmed this is happening using the WPC Product Quantity plugin as well. If I install that plugin and set any product to use a decimal stock quantity and then log out and back in on the app, no products are displayed on the product screen unless I view them elsewhere in the app, i.e. browse to order details and back to the product list. Note: products will also still be displayed if they were previously viewed (cached) in the app prior to making the decimal stock quantity change.

<sup>Tested with WCAndroid 6.3-rc-1 on Pixel 3 Android 11 on a site running WP 5.7 JP 9.5 WC 5.2-beta.1.</sup>
