### ISSUE TITLE
Bug: Product List screen loses its placeholder empty state after add new product bottom-sheet disappears

### ISSUE THREAD

**Issue by kidinov** [woocommerce/woocommerce-android#3614]
**Describe the bug**
When the user clicks on the “Add” button in the product section and then closes the bottom sheet, the empty state is gone. Just white background is displayed

**To Reproduce**
1. Login into the account without products
2. Go to the products screen
3. Click on add floating action button
4. Click anywhere above the bottom sheet

**Screenshots**
[video](https://user-images.githubusercontent.com/4923871/108634929-4ca49f80-748d-11eb-881b-0226684afc52.mp4)

**Expected behavior**
The empty state should stay after the bottom sheet is closed

**Isolating the problem (mark completed items with an [x]):**
- [x] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [x] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [x] I can reproduce this bug consistently using the steps above.

**Mobile Environment**
Please include:
- Device: Pixel emulator 26 API
- Android version: 8.0
- WooCommerce Android version: 199/6.0 from develop branch

[Similar issue](https://github.com/woocommerce/woocommerce-android/issues/3046)

**Comment by rossanafmenezes** [comment]
Tested this one and this seems to have been fixed already. Please see screen recording below:

https://user-images.githubusercontent.com/30724184/127697355-0a29fb60-6204-463e-af01-e2c2d5f48a50.mp4

Closing it.
