### ISSUE TITLE
Products: tapping "x" in Download Settings is unresponsive

### ISSUE THREAD

**Issue by designsimply** [woocommerce/woocommerce-android#3623]
Steps to reproduce:

1. Open any product with downloadable files.
1. Go to Downloadable Files > More > Download Settings.
1. Tap the x at top left.
1. Make any change.
1. Tap the x at top left.

**Result:** the "x" button in Download Settings is unresponsive.

<img src="https://user-images.githubusercontent.com/1119271/109046365-e3da4480-7691-11eb-804a-747bcacc4acc.png" width="270" alt="Screenshot_20210224-111119">
<sup>Tested with WCAndroid 6.1-rc-1 on Pixel 3 Android 11 on comparative-moth.jurassic.ninja (WP 5.7-RC1 JP 9.4 WC 5.1.0-beta.1) logged in as testuser01121.</sup>

**Note:** There is a small typo, "limk" should be "link". Should "the number of time" be "the number of times"?

**Comment by nbradbury** [comment]
Closed via #3625
