### ISSUE TITLE
Order creation: Add customer creation screen

### ISSUE THREAD

**Issue by 0nko** [woocommerce/woocommerce-android#3624]
![image](https://user-images.githubusercontent.com/1522856/109126127-36c50200-774d-11eb-8236-2f40a9035c0b.png)

The main order creation screen needs (just the bare boilerplate for now):

- [ ] New layouts and other relevant resources
- [ ] Fragment 
- [ ] ViewModel

**Comment by kidinov** [comment]
If it's on me, I'd like to know some details:

1. Search functionality part of this ticket? If yes, how it should look like?
2. Error state, empty state? What to show if the next page loading has failed?
3. Entry point to this screen is not available, should we add this (maybe just a button to lead here from  "new order" for now)?

**Comment by 0nko** [comment]
This issue was more for the boilerplate/infrastructure code, rather then the functionality (to split up the work into smaller units). I added the screenshot just for illustration. I'll add more issues for the actual feature tasks.

**Comment by rossanafmenezes** [comment]
resolved here https://github.com/woocommerce/woocommerce-android/pull/3665
