### ISSUE TITLE
[Settings] Re-organize sections and rows

### ISSUE THREAD

**Issue by allendav** [woocommerce/woocommerce-android#3628]
Light

<img src="https://user-images.githubusercontent.com/1595739/109199054-d5546180-7753-11eb-834b-401d6c8617a3.png" width=40%/>

Dark

<img src="https://user-images.githubusercontent.com/1595739/109199072-dab1ac00-7753-11eb-9a96-3b16114f5c34.png" width=40%/>

cc @Garance91540 

Related iOS issue: https://github.com/woocommerce/woocommerce-ios/issues/3746

**Comment by Garance91540** [comment]
Hi Allen, looking great, only one note: https://d.pr/i/P1Dbap We are missing the top divider above "Store Settings" on Dark mode

**Comment by SowmiaS** [comment]
Hello @allendav @Garance91540 👋
I feel "Image optimization" is missing. Is that intended to exclude it? 😕 
Thanks

**Comment by anitaa1990** [comment]
We have plans to update the Settings page as part of the Shipping labels onboarding project and the designs are currently being iterated on. So I'll close this issue for now since the designs are bound to some changes
