### ISSUE TITLE
Product Details: adding a new tag is very slow

### ISSUE THREAD

**Issue by designsimply** [woocommerce/woocommerce-android#3631]
Steps to reproduce:

1. Open any product.
1. Tap "Tags" or add it using the link at the bottom.
1. Add a new tag and tap enter.
1. Observe how long it takes to add a new tag.
1. Try the same test to add a new category.

**Result:** adding a new category is fast, but adding a new tag takes 30 to 40s each time. ([55s](https://cloudup.com/cVUTqKf5fGo), [1m34s](https://cloudup.com/cwZ4GwRMdNF))

**Note:** I tested this from a self-hosted Jetpack and a WordPress.com Business site with plugins installed and saw the same delay for both types of site. 

<img src="https://user-images.githubusercontent.com/1119271/109207674-9ed41200-7766-11eb-9697-2e8f7514a081.png" width="270" alt="image">
<sup>Tested with WCAndroid 6.1-rc-1 on Pixel 3 Android 11 on comparative-moth.jurassic.ninja (WP 5.7-RC1 JP 9.4 WC 5.1.0-rc.1) logged in as testuser01121.</sup>

**Comment by shiki** [comment]
Fixed in #3640.
