### ISSUE TITLE
Make the the “Update”/”Done”/Publish buttons Pink 50

### ISSUE THREAD

**Issue by designsimply** [woocommerce/woocommerce-android#3632]
> All CTAs in the app should be Pink 50. Can we update the “Update”/”Done”/Publish buttons in the edit views of the product screens so they are Pink 50?

<img src="https://user-images.githubusercontent.com/1119271/109212312-9b438980-776c-11eb-99ee-7417746aae5c.png" width="270" alt="Screenshot_20210225-130414"> <img src="https://user-images.githubusercontent.com/1119271/109212306-98489900-776c-11eb-917d-d20997ad4231.png" width="270" alt="Screenshot_20210225-130556">
<sup>Tested with WCAndroid 6.1-rc-1 on Pixel 3 Android 11 on comparative-moth.jurassic.ninja (WP 5.7-RC1 JP 9.4 WC 5.1.0-rc.1) logged in as testuser01121.</sup>

<sup>(internal reference: p5T066-1Ov-p2#comment-7141 hat tip @Garance91540)</sup>

**Comment by designsimply** [comment]
In 6.7 beta testing, it came up that the toggle button should also be pink when on:

<img src="https://user-images.githubusercontent.com/1119271/118908746-2bfab300-b8df-11eb-8d7b-d5d8ecc51451.png" width="270" alt="Screenshot_20210519-201554">

<sup>(internal reference: p5T066-2im-p2#comment-8286 /ht @adamzelinski)</sup>

**Comment by hichamboushaba** [comment]
Thanks @designsimply for flagging this, but it's not clear from the comment whether we meant just the "ADD" button in the toolbar or the toggle button as well.

@Garance91540 @adamzelinski can you please confirm if the toggle button color should be purple or pink? currently, it uses by default (as the rest of other UI actionable elements) the color primary (`woo_purple_60` #674399).

**Comment by ghost** [comment]
> can you please confirm if the toggle button color should be purple or pink?

Hey @hichamboushaba the toggle button color should be purple (`woo_purple_60` #674399) thanks.

**Comment by designsimply** [comment]
I may have misinterpreted! Here's a copy of what what the feedback from 6.7 beta testing said:

![image](https://user-images.githubusercontent.com/1119271/120722307-c71d8c00-c48c-11eb-81d6-47614eee5e80.png)

@adamzelinski could you just re-check that and confirm that no changes are needed on the add note screen? If you feel changes are needed, could you let me know so I can make a separate issue for that? 

@hichamboushaba the original note still applies where the “Update”/”Done”/Publish buttons in the edit views of the product screens should be Pink 50. If you'd like to update that to close out this issue, I can make a separate issue for the notes screen if anything is still needed there. Sound good?

<img src="https://user-images.githubusercontent.com/1119271/120722895-d94bfa00-c48d-11eb-84db-995db266d600.png" width="270" alt="image">
<sup>Tested with WCAndroid 6.8-rc-1 on Pixel 3 Android 11.</sup>

**Comment by ghost** [comment]
Hey @designsimply @hichamboushaba, yes we use woo purple 60 for the toggles and pink 50 for the action text in this case "add"
