### ISSUE TITLE
Make the Home Indicator transparent on all screens

### ISSUE THREAD

**Issue by designsimply** [woocommerce/woocommerce-android#3634]
> Could we make the Home Indicator of the device transparent on all screens? It’s what we’ve been doing on iOS and I find it way less disruptive this way: https://d.pr/i/KFdorF

<img src="https://user-images.githubusercontent.com/1119271/109213622-0e013480-776e-11eb-832b-156f6bdf6401.png" width="270" alt="Screenshot_20210225-133117"> <img src="https://user-images.githubusercontent.com/1119271/109213629-0f326180-776e-11eb-891f-186f49bc25db.png" width="270" alt="Screenshot_20210225-133108">
<sup>Tested with WCAndroid 6.1-rc-1 on Pixel 3 Android 11 on comparative-moth.jurassic.ninja (WP 5.7-RC1 JP 9.4 WC 5.1.0-rc.1) logged in as testuser01121.</sup>

Note: I am not sure whether it matters, but my device is currently using Gesture navigation ([screenshot](https://user-images.githubusercontent.com/1119271/109212897-3d637180-776d-11eb-8456-b96c7e3d3b8d.png)).

<sup>(internal reference: p5T066-1Ov-p2#comment-7141 hat tip @Garance91540)</sup>

**Comment by hichamboushaba** [comment]
Unless I'm mistaken, this was already implemented in 6.1 by @hafizrahman's PR: https://github.com/woocommerce/woocommerce-android/pull/3548, and we can already see it in the above screenshots 🙂.

**Comment by Garance91540** [comment]
You are right I just saw that in the app, thank you, all good!
