### ISSUE TITLE
Unable to edit product price in some cases

### ISSUE THREAD

**Issue by designsimply** [woocommerce/woocommerce-android#3651]
/hat tip @mdrockwell for the original report at https://github.com/wordpress-mobile/WordPress-Android/issues/14167 which I have copied below. 👍

### Expected behavior
After tapping on the price field, you're able to update it to a new value.

### Actual behavior
After tapping on the price field and tapping on the backspace key, the existing price will clear, but you aren't able to enter a new price.

### Steps to reproduce the behavior
1. Navigate to Products tab
2. Select product
3. Enter the price change view
4. Tap on backspace key
5. Attempt to enter new price

##### Tested on Honor 8A, Android 9, WooCommerce Android 6.1-rc-2, using Microsoft SwiftKey keyboard.

Video of this found here: 3783405-zen

**Comment by designsimply** [comment]
I did a really quick test so far but could not replicate. My device language is set to English (UK) and I did not test with the SwiftKey keyboard yet (the keyboard is my first guess but we should fix the title if that's not right because it could also be related to device language).

@hichamboushaba since this user is testing with 6.1-rc-2 and there was a recent change to the regex in that area in https://github.com/woocommerce/woocommerce-android/pull/3589 would you mind having a look at this one?

**Comment by hichamboushaba** [comment]
@designsimply I tried to reproduce this on my device using SwiftKey, but couldn't, but from the video in the ticket, I see that there is something wrong, as the suggestions bar is visible, while it shouldn't, because the field accepts only number input.

<img width="400" alt="Screen Shot 2021-03-04 at 12 28 50" src="https://user-images.githubusercontent.com/1657201/109957452-3d232300-7ce5-11eb-8c2f-8e001644177e.png">

I have a Huawei phone here, I'll charge it, and try to reproduce it with it and see if it's related to EMUI.

**Comment by hichamboushaba** [comment]
So I tested with my Huawey Y7p (EMUI 9.1.1, Android 9) using SwiftKey, and I couldn't reproduce the issue at all, on my case the suggestions bar is not visible, and the text is not underlined, which is the correct behavior, but I'm not sure if it's the cause of the issue or not.

I suggest we ask the user to confirm the below information:
1. When did this start? (to confirm if it's related to the regex change or not)
2. What's the language of typing of his keyboard?
3. Test using a different keyboard to confirm if it's related to SwiftKey or not.

**Comment by designsimply** [comment]
@hichamboushaba thank you! I will forward the questions. In the mean time, may I confirm with you that you tested with the 6.1-rc-2 version of the app?

**Comment by hichamboushaba** [comment]
> may I confirm with you that you tested with the 6.1-rc-2 version of the app?

Yes, I tested with 6.1-rc-2 version

**Comment by iamgabrielma** [comment]
It seems we have another case at 3812514-zen, however they're not using the SwiftKey keyboard:

- Standard Android keyboard.
- Language is danish
- oneplus 7 pro.
- Android version is 10
-  app version is 6.1
- _"I've also seen this bug on iPhone X"_

**Comment by designsimply** [comment]
This was reported again in an app review:

> Latest update has a bug ( i can't type the prices of all products)
> 
> <sup>March 31, 2021 for v6.2</sup>

* Device: Samsung Galaxy S20+ 5G
* Device language: English
* App version name: 6.2
* Android version: Android 11 (SDK 30)

<sup>(internal reference: play-store-reviewId=gp%3AAOqpTOHfCpcogZR6QPfcSXnvGDFLRSWREYf1UmyvT9B4JoNB98Uk4Gtw7Xn3LETfmhReEr-nn3wBcKeYECWKBVQ)</sup>

Note: I asked for more detail and we should update this comment if we find that they send back any additional details. 👍

**Comment by designsimply** [comment]
I think this is another report of this issue (even though they gave limited information):

> Error in add product price option
> 
> <sup>1-star review, Apr 3, 2021</sup>

* Device: Huawei Y9 Prime 2019
* Device language: English
* App version name: 6.2
* Android version: Android 10 (SDK 29)

<sup>(internal reference: play-store- reviewId=gp%3AAOqpTOGPCAX77cfmzWHsa82Rh_O5C9vmGzmM4xwpkgI3YLJb9iaITSZVB7gC0oeeBIYFpv5hczndjDDdaOuxCok)</sup>

**Comment by designsimply** [comment]
I found another app review mentioning they are having trouble updating prices:

> Unable to update price. Field does not accept any input
> 
> <sup>4-star review, Mar 1, 2021</sup>

* Device: Huawei Honor 8A
* Device language: English
* App version name: 6.1-rc-2
* Android version: Android 9 (SDK 28)

<sup>(internal reference: play-store-reviewId=gp%3AAOqpTOH0t9M5KDJwkK-mABCRyqsza9-uMbjzzv1he3-glbOXwgU_xb4O5lay-store-Tv2rRpcw7O9HTATVWVM51lU-aZ1UwbH9Q&corpus=BETA_FEEDBACK)</sup>
