### ISSUE TITLE
Order Details: consider showing "No address specified" for orders without a billing address

### ISSUE THREAD

**Issue by designsimply** [woocommerce/woocommerce-android#3709]
Steps to reproduce:

1. Create an order with no billing or shipping address.
1. Create an order with a shipping address but no billing address.
1. Compare how these orders look in the Android vs iOS apps.

**Result:** iOS always displays an option to view billing information and if none are available the next screen will say "No address specified." 

**Suggestion:** the billing details should shown and mention "No address specified" because the store owner may think there is an error if it is not displayed at all. /hat tip @pmusolino (internal reference p5T066-21o-p2#comment-7517)

 No billing or shipping address: 

Android|iOS|iOS
---|---|---
![Screenshot_20210317-131453](https://user-images.githubusercontent.com/1119271/111525983-c98d0700-8723-11eb-8a73-1ce19fc076a5.png)|![IMG_4825](https://user-images.githubusercontent.com/1119271/111525994-cc87f780-8723-11eb-9ed9-f10e5104e375.PNG)|![IMG_4826](https://user-images.githubusercontent.com/1119271/111525997-cc87f780-8723-11eb-8881-1abc6fcee93b.PNG)

Shipping address but no billing address: 

Android|iOS|iOS
---|---|---
![Screenshot_20210317-131506](https://user-images.githubusercontent.com/1119271/111526439-5d5ed300-8724-11eb-96c1-ce49a68235da.png)|![IMG_4829](https://user-images.githubusercontent.com/1119271/111526423-589a1f00-8724-11eb-8e4f-945dc7dd254e.PNG)|![IMG_4830](https://user-images.githubusercontent.com/1119271/111526430-5afc7900-8724-11eb-8063-9f0fb410f727.PNG)

<sup>Found while beta testing WCAndroid 6.2-rc-1 on Pixel 3 Android 11 and WCiOS 6.2.0.0 on iPhone 6S iOS 13.7.</sup>

**Note:** I think it would also be nice to say "No contact details specified" on the secondary screen if no phone or email is avail.

**Comment by malinajirka** [comment]
@nbradbury was this perhaps fixed in https://github.com/woocommerce/woocommerce-android/pull/5016? Tbh I'm not sure how to open detail of an order in read-only mode. It seems when it's editable mode, we display `+ Add Billing Address, + Add Shipping address` buttons.
<img src="https://user-images.githubusercontent.com/2261188/149527534-5f22f0f4-a6ad-4a2d-a6fc-a5deddbe9612.png" width="250px" />

**Comment by nbradbury** [comment]
@malinajirka There isn't a read-only order mode any more, as we removed the feature flag and enabled order editing for everyone. So, would think this issue can be closed.
