### ISSUE TITLE
Missing translations for grouped and external products when adding a new product

### ISSUE THREAD

**Issue by designsimply** [woocommerce/woocommerce-android#3710]
Steps to reproduce:

1. Set the device language to something other than English.
1. Go to Products > "+" to add a new product.

**Result:** string translation codes are showing where they should not for the Grouped and External product options in the bottom sheet.

<img src="https://user-images.githubusercontent.com/1119271/111529392-b67c3600-8727-11eb-819f-e33cda7fb975.png" width="270" alt="Screenshot_20210317-134304">
<sup>Tested with WCAndroid 6.2-rc-1 on Pixel 3 Android 11.</sup>

<sup>(internal reference: p5T066-21o-p2#comment-7519 /hat tip @pmusolino)</sup>

**Comment by shiki** [comment]
We should be adding `translatable="false"`  to the affected strings. 

Related: https://github.com/GlotPress/GlotPress-WP/issues/469

---

Internal ref: p1616112898074900-slack-CGPNUU63E
