### ISSUE TITLE
Set Status bar background to be white

### ISSUE THREAD

**Issue by anitaa1990** [woocommerce/woocommerce-android#3739]
The status bar’s background is black right now. 

<img width="270" alt="Screen Shot 2021-03-24 at 11 24 54 from https://d.pr/i/33Zh4V" src="https://user-images.githubusercontent.com/1119271/112359029-791f2780-8c96-11eb-9f2b-361d56365e1f.png">

We should set it to white to unify the changes to the top nav:

<img width="270" alt="Screen Shot 2021-03-24 at 11 27 10 from https://d.pr/i/SGZ586" src="https://user-images.githubusercontent.com/1119271/112359091-89370700-8c96-11eb-83da-c778ee12d17c.png">

Tested in Android 6.3 beta release. cc @woocommerce/android-developers

**Comment by nbradbury** [comment]
Woops, I could've sworn I did this! I'll assign this to myself.
