### ISSUE TITLE
Present a clearer message if the site's XML-RPC is blocked or the site cannot be reached

### ISSUE THREAD

**Issue by shiki** [woocommerce/woocommerce-android#3767]
Found in https://github.com/woocommerce/woocommerce-ios/issues/3883#issuecomment-809819474

## Describe the bug

The app responds with an indistinct message when logging in with a site that has one of these conditions:

- [x] ~Is password-protected via a basic HTTP auth.~ (moved to https://github.com/woocommerce/woocommerce-android/issues/4282) 
- [x] If the site blocks XML-RPC. (unmerged PR https://github.com/woocommerce/woocommerce-android/pull/4799)
- [x] If the device is offline (the app just says “site URL entered is invalid”) (PR https://github.com/wordpress-mobile/WordPress-Login-Flow-Android/pull/64)

Here is an example result:

<img src="https://user-images.githubusercontent.com/198826/112916639-2e4e4700-90be-11eb-89a2-fd5d1daa8311.png" width="300">

### XML-RPC 

This will probably work → [How to Disable XML-RPC in WordPress](https://www.wpbeginner.com/plugins/how-to-disable-xml-rpc-in-wordpress/)

### Offline

1. Enter the site address. 
2. After pressing “Continue”, quickly disable the internet connection. 
3. The app will say “Check that the site URL entered is invalid”. 

## Expected behavior

I would expect a more specific message so that I can troubleshoot further. 

This iOS PR shows what messages we should display: https://github.com/woocommerce/woocommerce-ios/pull/3957. 

### XML-RPC

If the site blocks XML-RPC, we can be more specific. Right now, iOS can present [a lot of them](https://github.com/wordpress-mobile/WordPressKit-iOS/blob/4062408fce1596b4744449fd950f9d47ddd4d7eb/WordPressKit/WordPressOrgXMLRPCValidator.swift#L16-L34) depending on how the site reacts. But we could probably just prioritize these error messages for XML-RPC problems:

> Couldn't connect. Your host is blocking POST requests, and the app needs that in order to communicate with your site. Contact your host to solve this problem.

> Couldn't connect. We received a 403 error when trying to access your site's XMLRPC endpoint. The app needs that in order to communicate with your site. Contact your host to solve this problem.

> Couldn't connect. Required XML-RPC methods are missing on the server.

Those “Contact your host” messages are good self-troubleshooting hints for our customers. 

### Offline

If offline, we should at least say “The Internet connection appears to be offline.”

---

iOS: https://github.com/woocommerce/woocommerce-ios/issues/3891

**Comment by shiki** [comment]
Related: https://github.com/woocommerce/woocommerce-android/issues/3977

**Comment by anitaa1990** [comment]
Just an update on the testing steps:

> Password-protected
I performed similar steps with my site:
Create a WooCommerce site that is connected to Jetpack.
I added a basic HTTP auth to the site. Here is an example for Nginx. Ask @shiki if you need help with setting up a site.
Log in by clicking on "Enter your Store Address" and enter the site address.

I use the [WP Basic authentication](https://wordpress.org/plugins/wp-basic-authentication) plugin on my test site to enable HTTP auth. 

Also @shiki what is the intended behaviour in this scenario? To display an error message? To allow folks to login via HTTP Auth? 

So when a site address is entered, the app calls the `/rest/v1.1/connect/site-info/` endpoint and this returns the below response:
```
{
  "exists": true,
  "isWordPress": true,
  "hasJetpack": true,
  "isJetpackActive": false,
  "isJetpackConnected": false,
  "isWordPressDotCom": false,
  "urlAfterRedirects": "https://huge-capybara.jurassic.ninja",
  "jetpackVersion": "9.8.1",
  "skipRemoteInstall": false
}
```
It shows that jetpack is not connected, even though it is. So how do we know when to display the HTTP Auth dialog? I get the same error when XML-RPC is blocked too 🤔 So not sure how to differentiate between the different errors that happen. 

Sorry, didn't mean to pick on you @shiki but since you worked on the iOS side wanted to better understand the intended behaviour 😅 

There is also a fieldguide with test sites to test all the scenarios mentioned in this issue:
`testing-self-hosted-discovery/`

**Comment by shiki** [comment]
Thanks for digging in, @anitaa1990. And thanks for the poke. This issue wasn't very descriptive, was it? 😅 

> Also @shiki what is the intended behavior in this scenario? To display an error message? To allow folks to login via HTTP Auth?

I only have questions about this. I did not have enough time to get this done for iOS. I created a separate issue for Android so we can tackle it separately. I have a feeling that sites protected with basic auth are rare so it's probably better to do this later. 

https://github.com/woocommerce/woocommerce-android/issues/4282

As for the other issues mentioned here, I **updated the description** ☝️  so it's clearer what needed to be done. Well, I hope it's clearer. So let me know if it's not. 

> I get the same error when XML-RPC is blocked too

That's interesting. I have not looked into the details of how this works. I only made sure that the WordPressKit-iOS errors are propagated to the UI. For iOS, there is a [`XMLRPCValidator`](https://github.com/wordpress-mobile/WordPressKit-iOS/blob/4062408fce1596b4744449fd950f9d47ddd4d7eb/WordPressKit/WordPressOrgXMLRPCValidator.swift#L41) which handles all of these. And then I just made sure that these errors are presented when they happen: [`WordPressOrgXMLRPCValidatorError`](https://github.com/wordpress-mobile/WordPressKit-iOS/blob/4062408fce1596b4744449fd950f9d47ddd4d7eb/WordPressKit/WordPressOrgXMLRPCValidator.swift#L4-L37). 

It looks like there is a similar validator and error enum in FluxC: [`SelfHostedEndpointFinder`](https://github.com/wordpress-mobile/WordPress-FluxC-Android/blob/766e0ae544de5d8b5e5d769d27f6bbb54bdf4f1d/fluxc/src/main/java/org/wordpress/android/fluxc/network/discovery/SelfHostedEndpointFinder.java#L25) and [`DiscoveryError`](https://github.com/wordpress-mobile/WordPress-FluxC-Android/blob/766e0ae544de5d8b5e5d769d27f6bbb54bdf4f1d/fluxc/src/main/java/org/wordpress/android/fluxc/network/discovery/SelfHostedEndpointFinder.java#L32-L42). Could we possibly use these? 

> Sorry, didn't mean to pick on you @shiki but since you worked on the iOS side wanted to better understand the intended behaviour 😅

No problem! It's my fault because I didn't update this issue. 🙂 

I just made sure that the errors are not generic and a bit more actionable. This PR shows what's been done: https://github.com/woocommerce/woocommerce-ios/pull/3957. I also updated the description of this issue.
