### ISSUE TITLE
Login: Invalid username or password - no error message is displayed

### ISSUE THREAD

**Issue by anitaa1990** [woocommerce/woocommerce-android#3776]
While testing login today, I noticed that if I enter an invalid username (that does not exist) in login with site credentials, no error message is displayed.

Note that this only happens when logging in with Site credentials.

When I entered my store address and chose to login with site credentials, I saw the "Logging in" progress dialog, but it disappeared after a few seconds and left me on the site credentials screen.

Flipper showed an HTTP 403 when posting to xmlrpc.php ("Incorrect username or password") but the app never showed an error message of any kind.

<img src="https://user-images.githubusercontent.com/22608780/113150698-f841cc00-9251-11eb-8c2d-284ccd46157b.gif" width="300"/>

**Comment by pmusolino** [comment]
TODO: Check if this is still a valid issue

**Comment by hichamboushaba** [comment]
This was fixed as part of the REST API project in both platforms, as we have a logic to detect login issues to allow the user to use the WebView to proceed

<img width=320 src="https://github.com/woocommerce/woocommerce-android/assets/1657201/f9bb17e6-1c58-41bc-b492-9e81da0052ec"/>

**Comment by pachlava** [comment]
Adding `MTTR-exclusion` label to avoid this issue getting into MTTR metric for October.2023.

The issue was indirectly fixed by REST API project, so it should not be included in the metric.
