### ISSUE TITLE
No error shown after login failure

### ISSUE THREAD

**Issue by nbradbury** [woocommerce/woocommerce-android#3789]
While testing #3772, I ran into the following issue.

When I entered my store address and chose to login with site credentials, I saw the "Logging in" progress dialog, but it disappeared after a few seconds and left me on the site credentials screen. 

Flipper showed an HTTP 403 when posting to xmlrpc.php ("Incorrect username or password") but the app never showed an error message of any kind.

**Comment by anitaa1990** [comment]
There is an open issue for this one in #3776 so closing this one 👍
