### ISSUE TITLE
Jumbled login epilogue

### ISSUE THREAD

**Issue by nbradbury** [woocommerce/woocommerce-android#3790]
I ran into this issue while testing #3772.

When I entered my store address and logged in with my password, the "Logging in" progress dialog appeared for several seconds, then took me to a weird-looking epilogue screen before showing the main activity. I recall that removing the epilogue screen from this flow was a problem, but if it has to appear it shouldn't be a jumble of views like this.

![epilogue](https://user-images.githubusercontent.com/3903757/113326823-2f62bc80-92e8-11eb-813d-fa7cddf3cc02.png)

**Comment by anitaa1990** [comment]
There is an open issue for this in #3445 so closing this one 👍
