### ISSUE TITLE
Spike: Research refund api endpoint and our current implementation

### ISSUE THREAD

**Issue by AmandaRiu** [woocommerce/woocommerce-android#380]
FluxC processes order status changes by posting to the /orders api endpoint with a "status" property set to the new status. This works fine for most statuses, but I noticed there is an api endpoint specific to refunds: http://woocommerce.github.io/woocommerce-rest-api-docs/#refunds

Since we have designs for displaying a refund button to the user, as well as implementing the ability to arbitrarily change an order status to any status available, we should research whether or not refunds should be handled differently. Do we have to directly use the refund api or can we just change the status to refunded?

**Comment by anitaa1990** [comment]
Closing this issue since the refund research spike is done 👍
