### ISSUE TITLE
Handle decimal quantities in order details

### ISSUE THREAD

**Issue by hichamboushaba** [woocommerce/woocommerce-android#3808]
Related to #3611, we need to display the quantity as is in the order details, today, we are converting the quantity to Int, the conversion is done when mapping from data model to the business model, so it won't impact FluxC.

**Comment by yuliiakorabelska** [comment]
Hi! 
I see there's no assignee so far. I was wondering if I could help and fix this issue?
Thanks in advance!

**Comment by hafizrahman** [comment]
@hichamboushaba Oh good point about the order details, I missed that when working on the original issue.

@juliafedosya For sure, thank you for offering to help!

**Comment by anitaa1990** [comment]
Hey @juliafedosya I've assigned the issue to you so everyone knows you're working on it 😄 Thank you! Feel free to reach out if you face any issues!
