### ISSUE TITLE
Shipping Labels: should I be allowed to reprint shipping labels that are more than 120 days old?

### ISSUE THREAD

**Issue by designsimply** [woocommerce/woocommerce-android#3845]
**To prepare:**

* Be on a site with the WooCommerce Shipping & Tax plugin installed that has a completed order with a shipping label created more than 120 days old (or several months up to a year).

**To test:** 

1. Open an order that contains a very old shipping label.
1. Tap "Reprint shipping label".

**Result:** it's possible to reprint shipping labels that are more than 120 days old. 

**Questions:** Should I be allowed to reprint shipping labels that are more than 120 days old? Will the number of days a shipping label is permitted to be reprinted vary depending on the shipping carrier?

<img src="https://user-images.githubusercontent.com/1119271/114785921-96e22880-9d3a-11eb-9098-35bbe46a62a6.png" width="440" alt="old-label">
<sup>Tested on a VANKYO S20 tablet running Android 9 h/t @allendav thank you for the report & screenshot!</sup>

<br><br>In comparison, the reprint option is disabled for the same shipping label in WP Admin.

<img src="https://user-images.githubusercontent.com/1119271/114785919-96499200-9d3a-11eb-9572-5748eb5adc90.png" width="320" alt="screen-shot-2021-04-14-at-2 18 29-pm">
<sup>(internal reference: p5T066-28r-p2#comment-7925 h/t @allendav)</sup>

**Comment by hichamboushaba** [comment]
Thanks for bringing this up, it was discussed internally p1612165574018200-slack-CGPNUU63E, but never made it to Github I think, and we forgot about it.
We need also to create a similar issue for iOS.
