### ISSUE TITLE
Update `ktlint`

### ISSUE THREAD

**Issue by wzieba** [woocommerce/woocommerce-android#3851]
We should use new version of `ktlint`. Current version, `0.29.0`, throws `Not a valid Kotlin file` error as it doesn't recognize `trailing comas` introduced in Kotlin `1.4`

**Comment by kidinov** [comment]
@wzieba it's not needed because detekt uses its own wrapper around ktlint so if we keep detekt up to date then it means that we use the relevant ktlint as well =)

**Comment by wzieba** [comment]
Ok great, thanks! Can't wait to finally be able to use trailing comas 😅.
