### ISSUE TITLE
Shipping Refund: Support Refunding Multiple Shipping Lines Inside An Order

### ISSUE THREAD

**Issue by hafizrahman** [woocommerce/woocommerce-android#3852]
#3825 is being worked on to support refunding shipping line payment inside the app. Currently, it only supports refunding if an Order has a single shipping line in it, at max.

That PR already has some code in place to support refunding multiple shipping lines, but there's a bug I still need to figure out related to it.

Since an Order most likely only has one shipping line, I opted to focus on shipping #3825 for now. This issue is meant to document the possibility to refund multiple shipping lines as a future enhancement.

**Comment by JorgeMucientes** [comment]
Shipping labels flow its being completely revamped. So I don't think this will apply anymore. Closing.
