### ISSUE TITLE
App language defaulted to English

### ISSUE THREAD

**Issue by reginabally** [woocommerce/woocommerce-android#3875]
**Describe the bug**

It was reported in 3925354-zd-woothemes that the app language changed to English after updating the app to version 6.4.

**To Reproduce**
1. Update the app to version 6.4
2. Change the device language to non-English, e.g. Dutch
3. Launch the app and notice almost all text in the app are in English

**Screen recording**

https://user-images.githubusercontent.com/40906847/115483852-29775000-a284-11eb-9284-2878ab2aa99f.mp4

**Expected behavior**

I would expect the app shows the app language according to the device's language setting.

**Isolating the problem (mark completed items with an [x]):**
- [X] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [X] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [X] I can reproduce this bug consistently using the steps above.

**Mobile Environment**
Please include:
- Device: Google Pixel 3 (emulated)
- Android version: 10
- WooCommerce Android version: 6.4

**Comment by reginabally** [comment]
Another report in 3925376-zd-woothemes for Spanish language.

**Comment by reginabally** [comment]
Another report in 3925532-zd-woothemes for Spanish language.

**Comment by reginabally** [comment]
Another report for Spanish: 3925545-zd-woothemes

**Comment by reginabally** [comment]
3921835-zd-woothemes for Portuguese language

**Comment by anitaa1990** [comment]
This should be fixed by a new release in v6.4.1 in #3876 👍

**Comment by designsimply** [comment]
<sup>(internal references: p1618968833145400-slack-C6H8C3G23 and paaHJt-20y-p2#comment-4263)</sup>
