### ISSUE TITLE
[Variations] Deleting or Creating a variation triggers draft changes on Product Details

### ISSUE THREAD

**Issue by ThomazFB** [woocommerce/woocommerce-android#3886]
Suppose any variation is created or deleted under a Variable Product. In that case, the `ProductDetailFragment` registers the changes considering that something changed inside the Product data. Still, Variation changes don't take part in the Product draft since they are models with separate endpoints, requiring no update to the store at the Product Details.

https://user-images.githubusercontent.com/5920403/115631019-691d5680-a2db-11eb-9dbf-e6a087c81456.mp4

**Comment by anitaa1990** [comment]
This is no longer happening, after testing the latest version of the app (8.5), so will mark this issue as closed.
