### ISSUE TITLE
[Variations] Attribute renaming doesn't submit when confirmed from virtual keyboard

### ISSUE THREAD

**Issue by ThomazFB** [woocommerce/woocommerce-android#3887]
When changing a Product Attribute name, if we hit the `Confirm` button at the virtual keyboard, the view is dismissed, but no change is submitted. The only way to finish the Attribute renaming is by hitting the back button.

https://user-images.githubusercontent.com/5920403/115631577-7be45b00-a2dc-11eb-8766-f606c8d64347.mp4

**Comment by nbradbury** [comment]
Note: I believe this is due to a problem with [WCMaterialOutlinedEditTextView](https://github.com/woocommerce/woocommerce-android/blob/0821552ebc66e4f352c00e8046382979731e72d2/WooCommerce/src/main/kotlin/com/woocommerce/android/widgets/WCMaterialOutlinedEditTextView.kt#L93).
