### ISSUE TITLE
Make the "fulfill order" checkbox checked by default when creating a shipping label

### ISSUE THREAD

**Issue by hichamboushaba** [woocommerce/woocommerce-android#3909]
As discussed in our last call, we should make the "Mark this order as complete and notify the customer" checkbox in the shipping label creation screen checked by default.

cc @Garance91540

**Comment by Garance91540** [comment]
Hi Hicham, actually I'd like to stay consistent with the experience on wp-admin, so if merchants have the habit of using wp-admin and then switch to the app we are doing the same thing. And I noticed that the checkbox isn't checked by default when creating shipping label, so I think we should do the same in the app: https://d.pr/i/fVdtOL

**Comment by hichamboushaba** [comment]
OK, thanks for the confirmation @Garance91540, closing this issue.
