### ISSUE TITLE
Global attribute terms shouldn't allow re-ordering

### ISSUE THREAD

**Issue by nbradbury** [woocommerce/woocommerce-android#3923]
Re-ordering global attribute terms isn't supported on the web or on iOS, but we have it enabled on Android. We should remove this since the re-ordering isn't retained.

**Comment by AliSoftware** [comment]
Submitting 6.6 to AppStore today for publication on Monday, so we'll need to move the milestone of this one. @shiki not sure if you want to move it to 6.7 (which we will cut on Monday, so quite short notice to fix the issue until then) or later, so I'll let you do the triaging and update the milestone 🙂

**Comment by nbradbury** [comment]
@AliSoftware This was actually addressed already in #3924 but we neglected to close this issue. Closing it now!
