### ISSUE TITLE
Wrong selection when filtering product list by type 

### ISSUE THREAD

**Issue by nbradbury** [woocommerce/woocommerce-android#3937]
If I go to the product list and choose to filter by product type, selecting "Simple" automatically selects "Virtual" as well.

![screen](https://user-images.githubusercontent.com/3903757/116548687-990fbf80-a8c2-11eb-9e2d-53d9ea52ec11.gif)

**Comment by anitaa1990** [comment]
Ohh, this might be because of the changes I did in #3900. @nbradbury do you plan to work on this or can I take this one up? It would be good to fix this before releasing this in v6.6 on Monday.

**Comment by nbradbury** [comment]
@anitaa1990 Feel free to take this one!

**Comment by nbradbury** [comment]
@anitaa1990 I'm not sure if this is related, but I just noticed if you tap the "X" icon in the filter screen, it asks whether to discard changes.

![Screenshot_1619702047](https://user-images.githubusercontent.com/3903757/116556420-6b7b4400-a8cb-11eb-9f3c-efec7434c154.png)
