### ISSUE TITLE
[Card Present Payments] Update reader's software

### ISSUE THREAD

**Issue by malinajirka** [woocommerce/woocommerce-android#3957]
This epic contains the work needed to update the software of the card reader when necessary.

Latests designs as of 5/3/21
<img width="736" alt="Screenshot 2021-05-03 at 10 54 36" src="https://user-images.githubusercontent.com/2261188/116900144-08a4e800-abfe-11eb-8d01-3abc0e03bc27.png">

### First iteration
- [x] Introduce SoftwareUpdateManager in CardReaderModule (PR https://github.com/woocommerce/woocommerce-android/pull/3963)
- [x] Check if an update is available and show "install update" button on CardReaderDetail screen (https://github.com/woocommerce/woocommerce-android/pull/4079)
- [x] Check for updates and show a dialog (with Update/Skip btns) after a connection to a reader is established (@kidinov in progress)
- [x] Add "install update" button when an update is available
- [x] Show un-cancelable progress when an update is in progress
- [x] Handle errors
- [x] Add "Please update ..." top bar (see designs) when an update is available
- [x] Turning the reader off while an update is in progress results in ANR - seems like an issue with the SDK -> I was able to reproduce the issue in the sample app (reported Issue-134 -> fixed in v2.x of the StripeTerminalSDK) (Will be fixed with migration to v2.0)
- [x] Add tracking (PR #4261 )
- [x] Prevent the user from leaving the dialog when an update is in progress - we decided to show a cancel button on back pressed and display a warning (PR https://github.com/woocommerce/woocommerce-android/pull/4264)
- [x] The "Update Reader's software" button doesn't disappear after a successful update

**Comment by kidinov** [comment]
Shell we close the epic? @malinajirka

**Comment by malinajirka** [comment]
Yeah, I moved the finished epics to the "done" column but I didn't realize I should have done it the other way round - close the issue and let the automation move it to the correct column.
