### ISSUE TITLE
Empty screen displayed when there are no sites

### ISSUE THREAD

**Issue by anitaa1990** [woocommerce/woocommerce-android#3965]
It looks like a blank screen is displayed when there are no sites available for the current login.

I had a support request where a user was unable to view any stores associated with their account. The GET Sites API returns an empty array i.e. `sites: []`. The app currently just displays a blank screen. We should display a valid error message.

<img src="https://user-images.githubusercontent.com/22608780/117112299-7ee44e80-ada6-11eb-8408-4b8a977a922e.png" width="300"/>

**Mobile Environment**
Please include:
- Device: Pixel 3
- Android version: 6.6-rc.2
- WooCommerce Android version: 

**WordPress Environment**
<details>
```
Copy and paste the system status report from **WooCommerce > System Status** in WordPress admin.
```
</details>

**Comment by selanthiraiyan** [comment]
@anitaa1990 I tested this in the latest trunk (version `9.3-rc-1`), and the following screen is displayed when there are no sites connected with an account. 

![Screenshot_20220614-055550_WooCommerce (Dev)](https://user-images.githubusercontent.com/524475/173469216-c5ea1ace-b1c9-4214-8618-5205ad2582f5.jpg)

I am closing this issue as we are no longer displaying an empty screen when there are no sites available for the current login.
