### ISSUE TITLE
Login to a site with site credentials and Disable XML-RPC-API plugin ends up with empty toast message

### ISSUE THREAD

**Issue by kidinov** [woocommerce/woocommerce-android#3977]
**Describe the bug**
Login to a site with site credentials and Disable XML-RPC-API plugin ends up with empty toast message

**To Reproduce**
1. Click "Enter your store address"
2. Enter http://testnojetpack.wordpress.com/
3. Click "Continue with store credentials"
4. Enter any credentials
5. Click continue

**Screenshots**
https://d.pr/v/fr10Hg

**Expected behavior**
At least a toast message with a short explanation of what's happened

**Mobile Environment**
Please include:
- Device: Emulator 
- Android version: 11
- WooCommerce Android version: 6.5

**Comment by shiki** [comment]
Related: https://github.com/woocommerce/woocommerce-android/issues/3767

**Comment by hichamboushaba** [comment]
This is no longer applicable, we don't hit the XMLRPC API anymore, the login with site-credentials uses only REST API.
