### ISSUE TITLE
Shipping labels: add new custom packages

### ISSUE THREAD

**Issue by hichamboushaba** [woocommerce/woocommerce-android#3993]
In the shipping label creation form, allow the user to add new service carrier packages:

<img width="518" alt="Screen Shot 2021-05-07 at 12 19 57" src="https://user-images.githubusercontent.com/1657201/117448669-8cc4db80-af2e-11eb-9213-d461c0c1e03f.png">

**Comment by hafizrahman** [comment]
I'm going to split this into two PRs:
1. Adding custom package on labels where existing packages are already activated. 👈🏼  Currently working on this ([working branch](https://github.com/woocommerce/woocommerce-android/tree/add/create-custom-package-on-existing-packages-case)).
2. Adding custom package on labels where there's no activated packages yet.

Both PRs will be merged first to the feature branch: [feature/sl-create-custom-package](https://github.com/woocommerce/woocommerce-android/tree/feature/sl-create-custom-package)

**Comment by hichamboushaba** [comment]
As there is a specific ticket for the second point #4000, and that the first part has been implemented in #4354, I'm closing this ticket.
