### ISSUE TITLE
Logging in With WordPress Sometimes Leads to Empty Screen

### ISSUE THREAD

**Issue by shiki** [woocommerce/woocommerce-android#4037]
**Describe the bug**

After logging in with a WordPress account, I got redirected to this empty screen.

**To Reproduce**

This does not happen often. Though it happened for a customer (3989604-zd-woothemes) due to issues with their Jetpack connection. 

1. Log in with WordPress.com 
2. After entering the email and password, I got redirected to the empty screen. 

**Screenshots**

<img src="https://user-images.githubusercontent.com/198826/118346183-dc8b4000-b4f6-11eb-94d7-bc14925dfe83.png" width="300">

**Expected behavior**

An error message could probably be displayed here.

**Isolating the problem (mark completed items with an [x]):**
- [ ] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [ ] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [ ] I can reproduce this bug consistently using the steps above.

**Mobile Environment**
Please include:
- Device: Pixel 3
- Android version: 6.6-rc.2
- WooCommerce Android version: 

**WordPress Environment**
<details>
```
Copy and paste the system status report from **WooCommerce > System Status** in WordPress admin.
```
</details>

**Comment by shiki** [comment]
Related: https://github.com/woocommerce/woocommerce-android/issues/4172

**Comment by anitaa1990** [comment]
Closing this issue since it's already being tracked in #3965. I've updated any relevant info from this issue to that one :)
