### ISSUE TITLE
[Card Present Payments] Receipts

### ISSUE THREAD

**Issue by malinajirka** [woocommerce/woocommerce-android#4039]
Goal of this ticket is to implement email/print receipt flows for payments which were collected using a card-reader.

- [x] Set customer's email in PaymentIntent (PR https://github.com/woocommerce/woocommerce-android/pull/4106/files)
- [x] Set payment description - see https://github.com/woocommerce/woocommerce-ios/issues/4206#issuecomment-841456798 (PR https://github.com/woocommerce/woocommerce-android/pull/4107)
- [x] Pass ReceiptData to the app from CardReaderModule
- [x] Introduce ReceiptCreator - produce HTML receipt
- [x] Show progress indicator after the user clicks on "Print" as it can take a few seconds before the remote receipts gets loaded (PR https://github.com/woocommerce/woocommerce-android/pull/4266)
- [x] Remove ReceiptCreator and leverage Stripe's receipts (PR https://github.com/woocommerce/woocommerce-android/pull/4129)
- [x] Start Email intent and pre-fill customer's email if we have it (PR https://github.com/woocommerce/woocommerce-android/pull/4129) 
- [x] Start Print intent (PR https://github.com/woocommerce/woocommerce-android/pull/4096)
- [x] Store receipt data into a persistent storage + add button(s) to invoke "email/print" flow again ( we plan to implement a backend solution, OrderModel will contain receiptUrl so we won't need to store the receipt locally -> implement this task only if the backend is not ready for the beta) (PR https://github.com/woocommerce/woocommerce-android/pull/4326)
- [x] Add Print Receipt button to OrderDetail screen (PR https://github.com/woocommerce/woocommerce-android/pull/4329)
- [x] Add tracking (PR https://github.com/woocommerce/woocommerce-android/pull/4254)

Out of Beta scope - GitHub is partially down and I can't create a separate "out of beta scope" issue at the moment
- [x] Add Printing tutorial dialog to order detail screen (@ctarda will probably work on this task) (PR #4168)

**Comment by kidinov** [comment]
It looks done. @malinajirka shell we close it?
