### ISSUE TITLE
ParseError: org.xmlpull.v1.XmlPullParserException: unexpected type (position:END_DOCUMENT null@1:1 in java.io...

### ISSUE THREAD

**Issue by AliSoftware** [woocommerce/woocommerce-android#4049]
**Sentry Url**: https://sentry.io/share/issue/e58612978143465cbe089bf1bada47c2/
**User Count**: 1
**Count**: 3
**First Release**: 6.6
**First Seen**: 2021-05-18T06:14:33.902000Z
**Last Seen**: 2021-05-18T06:14:38Z
**24 Hours**: 3
**30 Days**: 3

```
ParseError: org.xmlpull.v1.XmlPullParserException: unexpected type (position:END_DOCUMENT null@1:1 in java.io...

...
(6 additional frame(s) were not displayed)
```

**Comment by wzieba** [comment]
The attached URL is not pointing to the issue, let's close this one and if needed - open a new Github issue for a new Sentry one.
