### ISSUE TITLE
Fetch order(s) on incomming notification when app is not running. Reduce number of requests needed to fetch an order from notification.

### ISSUE THREAD

**Issue by wzieba** [woocommerce/woocommerce-android#4053]
**Current behavior** 

edit: **this happens only when app is killed**, when app runs in background, order is fetched as expected

When notification for a new order is received, we don't the rich-model of it. In the result, after clicking on a notification about new order, we're navigated to this order and then the order is fetched so it takes a few additional seconds to order to appear for the user. See video:

1. Notification is received
2. User waits ~10sec (in this time order should be fetched)
3. User clicks on the notification.
4. As you can see - order has not been fetched and user needs to wait ~10 seconds for an order to appear

https://user-images.githubusercontent.com/5845095/118696920-10c07280-b80f-11eb-9af8-7ded15a8da14.mov

**Expected behavior** 

When notification is received, if it's possible, app should fetch an order. Then, when user clicks on a notification, order will be shown without additional waiting. This scenario assumes that user won't click a notification immediately after receiving.

This way we can reduce wait time of a user and improve their experience.

**Comment by wzieba** [comment]
**How does it work now?**

- when app receives a notification, `FCMMessageService#onMessageReceived` is called and then `NotificationHandler#buildAndShowNotificationFromNoteData` builds a notification (meanwhile fetching its data)
- if app is in the background, `MainPresenter:onEventMainThread(event: NotificationReceivedEvent)` will be called and this will fetch the order for which notification has been received.

**What's wrong with this?**

1. Fetching an order in background doesn't work when app is killed as `MainPresenter` doesn't exist in such scenario so it can't react to received notification event.
2. Even if `MainPresenter` is alive and `MainPresenter:onEventMainThread(event: NotificationReceivedEvent)` is invoked, we have sub-optimal fetching strategy: instead of fetching a single order we fetch the whole list (even without diff as we use `WCOrderActionBuilder#newFetchOrdersAction` in this case). In my testing it adds ~5,3 second of waiting (note: my testing environment is deliberately a slow one). **Ideally, we should just fetch a single order** and reduce time for about 60% (my case: 8,7sec -> 3,4 sec)

**What am I working on now?**

Currently, I'm able to fetch a single order when app receives a notification. The challenge I'm working on now is that this order is not automatically displayed on the list on `Orders` tab - I'm talking here about case when app is in foreground.

The reason for that is that our diff/paging mechanism: fetching a single order (or: fetching orders by ids with only 1 element in the list) seems to not update `ListItemModel` in database and in result, presentation layer doesn't receive information about all orders stored in the database.

**Comment by wzieba** [comment]
>  Ideally, we should just fetch a single order

For now I moved it out of scope of this issue. This would take much more effort than I initially thought, as diff mechanism API doesn't allow for fetching a single event for now.

**Comment by AliSoftware** [comment]
Moved this issue's milestone to 6.9 as code freeze for 6.8 is happening today.
