### ISSUE TITLE
Shipping Labels: remove drop-down arrow indicator for Ship to > Country field as long labels are only available in the US

### ISSUE THREAD

**Issue by designsimply** [woocommerce/woocommerce-android#4071]
To prepare:

1. Install, activate, and setup the [WooCommerce Shipping & Tax plugin](https://wordpress.org/plugins/woocommerce-services/).
1. Currently, the store must be located in the US and be using USD currency.
1. The order must have at least one physical product.

Steps to reproduce:

1. Open an order with a physical product.
1. Tap the "Create shipping label" button.
1. Tap the "Ship to" option.
1. Try to change the Country field to something other than the United States.

**Result:** the early version of this feature only allows creating shipping labels for locations within the United States but the Country field has an arrow to the right of it which makes it seem like you can select a different country even though you cannot.

<img src="https://user-images.githubusercontent.com/1119271/119065982-f8319300-b99b-11eb-874c-e65598557ef9.png" width="270" alt="Screenshot_20210520-183247">
<sup>Tested with WCAndroid 6.7-rc-2 on Pixel 3 Android 11.</sup>

<sup>(internal reference: p5T066-2im-p2#comment-8330 /ht @pmusolino)</sup>

**Comment by hichamboushaba** [comment]
We now support international shipping labels, so this is not relevant anymore
