### ISSUE TITLE
App crashes when issuing a refund through the app

### ISSUE THREAD

**Issue by reginabally** [woocommerce/woocommerce-android#4099]
**Describe the bug**

There are multiple reports on WCAndroid 6.6 that issuing a refund will cause the app to crash.

**To Reproduce**
Steps to reproduce the behavior: (according to 4024514-zd-woothemes)
1. Go to Orders
2. Select an order
3. Tap on "ISSUE REFUND"
4. Select the product to refund
5. Specify the reason for refund
6. App crashes

I will add individual reports as comments below.

**Comment by reginabally** [comment]
[4-star app review](https://play.google.com/console/u/0/developers/7957760354032996428/app/4973018994742253387/user-feedback/review-details?reviewId=gp%3AAOqpTOGqH_C5_W5ojoufVMqkG2g85XBFwkbm0pmdGjMSTEzh6RA7ZLIVJ56fMpglZyVoFGo_lYZtctKMB8JjtvI)

Device: Huawei HUAWEI P smart+ 2019
App version: 6.6
OS: Android 10

**Comment by reginabally** [comment]
4019045-zd-woothemes

Device: SM-G960W
App version 6.6
OS: Android 10

[Sentry reports](https://sentry.io/organizations/a8c/discover/results/?field=title&field=event.type&field=project&field=user.display&field=timestamp&name=All+Events&project=1459556&query=user.display%3Agodelivery%40depanneurlivraisonlaval.com&sort=-timestamp&statsPeriod=14d&widths=-1&widths=-1&widths=-1&widths=-1&widths=-1)

**Comment by reginabally** [comment]
4024514-zd-woothemes

Device: SM-A505FN
App version: 6.6
OS: Android 11

[Sentry reports](https://sentry.io/organizations/a8c/discover/results/?field=title&field=event.type&field=project&field=user.display&field=timestamp&name=All+Events&project=1459556&query=user.display%3Ainfo%40benpieters.nl&sort=-timestamp&statsPeriod=14d&widths=-1&widths=-1&widths=-1&widths=-1&widths=-1)

**Comment by hafizrahman** [comment]
The last two tickets with Sentry reports have similar issue as the one that is resolved in #3983 (original issue in #3982).

The fix will be included in 6.7 (or also already available now in 6.7 beta).

**Comment by hichamboushaba** [comment]
I cross matched Sentry reports to the Google Play review, and it's also related to the issue #3982 ([Sentry report](https://sentry.io/organizations/a8c/discover/results/?field=title&field=event.type&field=project&field=user.display&field=timestamp&name=All+Events&project=1459556&query=device%3APOT-LX1&sort=-timestamp&statsPeriod=14d&widths=-1&widths=-1&widths=-1&widths=-1&widths=-1)), so I'll close this ticket as it's most probably already fixed, and I'll keep an eye on it during this sprint.
