### ISSUE TITLE
Check compatibility with Android 12

### ISSUE THREAD

**Issue by hichamboushaba** [woocommerce/woocommerce-android#4113]
We need to confirm that the app is compatible with Android 12 behavior changes before it's released.

Most [changes](https://developer.android.com/about/versions/12/behavior-changes-12) impacts only apps that target the API 31, but some are not, while testing the app on my device, I identified one, which is the change of the app's splash screen (https://developer.android.com/about/versions/12/features/splash-screen)

### Immediate changes
All of them are not blocking
- [x] #5241
- [x] #5250
- [x] #5342

### Changes when targeting Android 12
- [x] #5270
- [x] #5272
- [x] #5297
- [x] Confirm that "Notification trampoline restrictions" doesn't impact us
- [x] #5301
- [x] Revise the updated "Non-SDK API restriction list" and confirm we are safe

### Last Step
- [x] #5327

**Comment by hichamboushaba** [comment]
@anitaa1990 I'm not planning on increasing the targetSdkVersion until 8.2, to give us proper time to make sure I didn't miss any point.

**Comment by anitaa1990** [comment]
Ah, in that case feel free to update the milestone to 8.2 😄
