### ISSUE TITLE
Variations: design changes requested for the "Add attribute" screen when there are no attributes

### ISSUE THREAD

**Issue by designsimply** [woocommerce/woocommerce-android#4157]
Steps to reproduce:

1. Create a new variable product or edit an existing one and change the product type to variable.
1. Tap "Add variations"
1. Compare the "Add attribute" screenshot to the design.

Requested changes:

1. Add the following helper text at the top: 'To create a variation, you'll need to set its attributes (ie "Color", "Size") first'
1. Make the text that starts with "Or tap to select" subtitle 2.
1. Give dividers a 16px left margin.
1. Add a bottom divider.

<img width="710" alt="screen-shot-2021-05-06-at-11 52 13-am" src="https://user-images.githubusercontent.com/1119271/121443473-caac8980-c94a-11eb-8f6c-d41b17e6d0c5.png">

<sup>(internal reference: p5T066-2fU-p2#comment-8146 raised during 6.6 beta testing /hat tip @Garance91540)</sup>

**Comment by designsimply** [comment]
Based on the following additional feedback from beta testers, can we also change "DONE" to "NEXT" on this screen?

> It is not obvious how to create variations and that the “Done”  has to be clicked to actually proceed with the creation of the variations and then you have to edit those variations. 

<sup>(internal reference: p5T066-2fU-p2#comment-8260 /hat tip @devNigel cc @Garance91540)</sup>

**Comment by rossanafmenezes** [comment]
After testing I can see all the requests from this issue have been addressed already. 

<img width="397" alt="Screen Shot 2021-07-28 at 07 44 25" src="https://user-images.githubusercontent.com/30724184/127316858-531498b9-5b5e-4e57-8d3e-b2e75efbd924.png">


![Screen Shot 2021-07-28 at 07 22 52](https://user-images.githubusercontent.com/30724184/127316738-b3685abb-8cc7-49d5-808c-5257cef5ea9c.png)

Closing this ticket.
