### ISSUE TITLE
No useful information is shown when trying to login to a non-connected site

### ISSUE THREAD

**Issue by hichamboushaba** [woocommerce/woocommerce-android#4172]
When trying to login using a site URL, using an account that's not connected to this site, we don't show any useful information to the user to help them understand what's wrong

<img width="351" alt="Screen Shot 2021-06-11 at 12 54 24" src="https://user-images.githubusercontent.com/1657201/121682877-8b9a4780-cab4-11eb-885a-74f3cbc6b1fb.png">

It seems that `no_stores_view` is invisible at this step, while it should be visible, by changing its visibility in `showSiteNotConnectedAccountView` we get this screen:
<img width="351" alt="Screen Shot 2021-06-11 at 13 01 11" src="https://user-images.githubusercontent.com/1657201/121683372-2f83f300-cab5-11eb-83d0-e3ed18697147.png">

We just need to confirm if this doesn't cause any other regression.

**Comment by shiki** [comment]
Related: https://github.com/woocommerce/woocommerce-android/issues/4037

**Comment by hichamboushaba** [comment]
This was fixed as part of #4370, not sure why the PR didn't update the ticket's status.

**Comment by pachlava** [comment]
Adding `MTTR-exclusion` label to avoid this issue getting into MTTR metric for October.2023.

The issue was actually closed long ago, but the fix did not update the issue status.
