### ISSUE TITLE
Shipping Labels: Address fields validation warning doesn't go away

### ISSUE THREAD

**Issue by nbradbury** [woocommerce/woocommerce-android#4177]
In the shipping labels address form, if you fail to enter a required field, such as phone number or zip code, you get the warning that the field is required. But if you then type something, the warning doesn't go away. 

Also, the warning under the phone number is different than the rest and doesn't really make sense.

![customs](https://user-images.githubusercontent.com/3903757/121711485-a8c91900-caa8-11eb-824b-a5db383e1875.png)

**Comment by hichamboushaba** [comment]
A second issue mentioned in https://github.com/woocommerce/woocommerce-android/pull/4216#issuecomment-863120383, validation errors should be highlighted by default when the form is opened to make it easier for the user to know about them.
