### ISSUE TITLE
Orders: snackbars on the order review screen should be limited to one

### ISSUE THREAD

**Issue by designsimply** [woocommerce/woocommerce-android#4186]
> After selecting “Mark order as complete” on the Review order screen, I noticed we are showing two “Order completed” snackbars. Could we only display the one on the right with the emoji?
<sup>— from @Garance91540  as part of 6.8 beta testing 👍</sup>

<img src="https://user-images.githubusercontent.com/1119271/121745174-4c262800-cac1-11eb-9cd2-c570b7059f46.png" width="270" alt="image"> <img src="https://user-images.githubusercontent.com/1119271/121745186-50eadc00-cac1-11eb-9052-5d4812ae818d.png" width="270" alt="image">

<sup>(internal reference: p5T066-2mv-p2#comment-8602)</sup>

**Comment by anitaa1990** [comment]
This is completed and is no longer happening so I'll mark this as closed
