### ISSUE TITLE
Order Details: bottom divider missing from top nav on the main Order Details screen

### ISSUE THREAD

**Issue by designsimply** [woocommerce/woocommerce-android#4187]
> Not directly linked to the review order screen since it’s seems to happen to most of my Order Details screen: we are missing the bottom divider of the top nav.
<sup>— from @Garance91540  as part of 6.8 beta testing 👍</sup>

Design|Screenshot
---|---
<img src="https://user-images.githubusercontent.com/1119271/121746429-1da94c80-cac3-11eb-8fa6-3453467aab32.png" width="270" alt="image">|<img src="https://user-images.githubusercontent.com/1119271/121746448-226e0080-cac3-11eb-8a42-5f5cb69b9cf2.png" width="270" alt="image">

<sup>(internal reference: p5T066-2mv-p2#comment-8602)</sup>

**Comment by malinajirka** [comment]
I haven't dived into this issue. However, I noticed the following:
1. Open order list (do not scroll => keep y=0)
2. Open detail of an order
3. Notice the divider is visible
4. Go back to order list
5. Scroll down (y!=0)
6. Open detail of an order
7. Notice the divider is not visible

This seems related to our implementation of the "Big Header Toolbar" and the toolbar animation on scroll. Either case, it doesn't seem like a good first issue.

**Comment by malinajirka** [comment]
Fixed
