### ISSUE TITLE
Shipping Labels: price is not updated when selecting additional options on the "Carriers and rates" screen

### ISSUE THREAD

**Issue by designsimply** [woocommerce/woocommerce-android#4188]
> When selecting options like signature, the rates should automatically update to add the selected option. But currently, it stays the same after being selected (so in the screenshot below the price should update to $20.65
<sup>— from @Garance91540  as part of 6.8 beta testing 👍</sup>

Before selection|After selection
---|---
<img src="https://user-images.githubusercontent.com/1119271/121746316-ee92db00-cac2-11eb-9e00-16b2feb7d560.png" width="270" alt="image">|<img src="https://user-images.githubusercontent.com/1119271/121746402-141fe480-cac3-11eb-9d0b-3f9faaf40f53.png" width="270" alt="image">

<sup>(internal reference: p5T066-2mv-p2#comment-8602)</sup>

**Comment by designsimply** [comment]
@anitaa1990 do you think it would be good to fix this one for the 6.9 release even though code freeze for 6.9 begins on Monday?

**Comment by hichamboushaba** [comment]
Another issue to fix: pre-selecting the rate if there is only one single result.
