### ISSUE TITLE
Products: typo for “simple physical product” on the bottom sheet when adding a new product

### ISSUE THREAD

**Issue by designsimply** [woocommerce/woocommerce-android#4191]
> There’s a typo for “simple physical product”
<sup>— from @Garance91540  as part of 6.8 beta testing 👍</sup>

Add Product| Change Product Type
---|---
<img src="https://user-images.githubusercontent.com/1119271/121748394-16d00900-cac6-11eb-8a72-fa94919218a4.png" width="270" alt="image">|<img src="https://user-images.githubusercontent.com/1119271/121748724-b097b600-cac6-11eb-9bbe-1d65253bac41.png" width="270" alt="image">

<sup>(internal reference: p5T066-2mv-p2#comment-8602)</sup>

**Comment by designsimply** [comment]
@jkmassel any chance we can sneak in an update to change "Simple physical productt" to ""Simple physical product" in the translations before the public release of 6.8 is submitted to the play store?

**Comment by shiki** [comment]
@AliSoftware already fixed this in https://github.com/woocommerce/woocommerce-android/pull/4128 a week ago. 🙂

**Comment by shiki** [comment]
To clarify, it's not fixed in 6.8. Sorry, didn't read the latest comment. It's fixed in `develop` only. 

https://github.com/woocommerce/woocommerce-android/blob/a09f2cc3382996f0886653c599dec5ec666f053d/WooCommerce/src/main/res/values/strings.xml#L1333

**Comment by shiki** [comment]
Fixed in #4192
