### ISSUE TITLE
Products: Save as Draft Stopped Working in 6.9+

### ISSUE THREAD

**Issue by shiki** [woocommerce/woocommerce-android#4200]
**Describe the bug**

The _Save as Draft_ button that is shown when navigating away from a new product detail page no longer saves the product as draft. 

Works fine in 6.8.

**To Reproduce**

1. Tap Products tab  → Big plus button
2. Enter a product title.
3. Navigate back 
4. A dialog will be shown. Tap on Save as Draft. 

Check the website. The product that was supposed to be a draft has been published.

**Screenshots**

**Expected behavior**

The product should not be visible on the website. 

**Isolating the problem (mark completed items with an [x]):**
- [ ] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [ ] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [ ] I can reproduce this bug consistently using the steps above.

**Mobile Environment**
Please include:
- Device: Pixel 3
- Android version: 
- WooCommerce Android version: 

**WordPress Environment**
<details>
```
Copy and paste the system status report from **WooCommerce > System Status** in WordPress admin.
```
</details>

**Comment by anitaa1990** [comment]
Fixed in #4208
