### ISSUE TITLE
Variations: Generate New Variation should be displayed in Variations list

### ISSUE THREAD

**Issue by shiki** [woocommerce/woocommerce-android#4202]
These buttons are currently not visible in Android.

iOS | Android (missing Generate button)
--------|-------
<img src="https://user-images.githubusercontent.com/198826/121979680-e0a1bc00-cd47-11eb-9430-eba7187d7023.png" width="300">        |  <img src="https://user-images.githubusercontent.com/198826/121979802-1ba3ef80-cd48-11eb-90f1-cd11bf374101.png" width="300">

@Garance91540 Just wanna confirm that the iOS one is correct, right? ☝️

**Comment by Ecarrion** [comment]
Hi @shiki, this is true for the current released version of iOS. But after the variations changes, which are currently on code-freeze the screen does not have the "Edit attributes" button anymore. https://github.com/woocommerce/woocommerce-ios/pull/4350

<img width="308" alt="Screen Shot 2021-06-15 at 10 02 03 AM" src="https://user-images.githubusercontent.com/562080/122076944-ec7d9480-cdc0-11eb-86b4-9116f63c7515.png">
