### ISSUE TITLE
Variations: Number of Variations Disappears After Creating a Variation

### ISSUE THREAD

**Issue by shiki** [woocommerce/woocommerce-android#4210]
**Describe the bug**

The number of variations in the product details disappears after creating a variation. The variation is still there though, it's just not shown in the UI.

**To Reproduce**

1. Tap on Products tab → Big plus button. 
2. Choose Variable product. 
3. Add a variation and follow the flow until one variation is generated. 
4. When you're navigated back to the Product List, tap on “Variations (1 variation)”.
5. Navigate back. 
6. You'll notice that the “Variations (1 variation)“ button has been replaced by “Add variations“.

**Screenshots**

https://user-images.githubusercontent.com/198826/122105756-5eaca400-cdd6-11eb-9fe8-798439a0e35c.mov

**Expected behavior**

The “Variations (1 variation)” button should be displayed.

**Isolating the problem (mark completed items with an [x]):**
- [ ] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [ ] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [ ] I can reproduce this bug consistently using the steps above.

**Mobile Environment**
Please include:
- Device: Pixel 3
- Android version: 
- WooCommerce Android version: `develop` (1fcdc0336)

**WordPress Environment**
<details>
```
Copy and paste the system status report from **WooCommerce > System Status** in WordPress admin.
```
</details>

**Comment by shiki** [comment]
I tested this again in the recent `develop` (b012d1f2a) and it seems to be working fine now. 🤷

**Comment by shiki** [comment]
Actually, it still happens but it's quite inconsistent. So it's probably state-related.

**Comment by rachelmcr** [comment]
I am seeing this consistently in the 6.9-rc-2 beta release when I add a new attribute and also add a global attribute to a new variable product.
