### ISSUE TITLE
Payments: Manage reader timeout

### ISSUE THREAD

**Issue by nbradbury** [woocommerce/woocommerce-android#4276]
The manage readers screen doesn’t appear to have a timeout. When it can’t find the reader, it just stays there showing a progress bar. To reproduce, disconnect from the reader, disable bluetooth, then return to the manage readers screen. Or turn off the reader and return to that screen.

The problem appears to be that if you connect to a reader, then either disable bluetooth or power off the reader and return to manage readers screen, our `CardReaderManager` still shows the reader as connected. So that screen fires a request to check for updates, which sets the `Loading` state, and then the state never changes.

<img src="https://user-images.githubusercontent.com/3903757/123441705-25c4ba00-d5a2-11eb-9d05-3950e0694d15.png" width=320 />

**Comment by malinajirka** [comment]
I just tested this and it timed out +- after 30 seconds -> redirected me to the connected state and displayed a snackbar error message. I know showing the progress isn't ideal, but I think it's good enough for now. The v2.0 of Stripe Terminal SDK checks for updates during connection and contains `isUpdateAvailable` flag on the reader object itself. Wdyt @nbradbury ?

**Comment by nbradbury** [comment]
@malinajirka If I connect to a reader, back out of the manage reader screen, turn off bluetooth, then return to the manage reader screen, the progress keeps spinning indefinitely. I just tried that again and left it spinning for three minutes before backing out.

**Comment by AnirudhBhat** [comment]
@nbradbury @malinajirka I can't seem to reproduce this issue. Is this still happening or are we good to close this issue?

**Comment by malinajirka** [comment]
I just tested it and I wasn't able to reproduce the issue. Closing - we can reopen it if it appears again.
