### ISSUE TITLE
Payments: Update reader software progress

### ISSUE THREAD

**Issue by nbradbury** [woocommerce/woocommerce-android#4277]
When updating the reader software we show an indeterminate progress bar, which doesn't give the user any indication of how long the update will take. The Stripe example app has this implemented so we can use that for guidance.

<img src="https://user-images.githubusercontent.com/3903757/123441829-47be3c80-d5a2-11eb-98f9-de7cbf92c431.png" width=480 />

**Comment by kidinov** [comment]
It's been implemented. We do show progress at the moment
