### ISSUE TITLE
Payments: Show errors in red

### ISSUE THREAD

**Issue by nbradbury** [woocommerce/woocommerce-android#4279]
When the payments flow encounters an error, the error text is styled the same as it is for successful messages. Should we show error messages in red instead, or perhaps with a red error icon before them?

cc: @woocommerce/mobile-designers 

![try-again](https://user-images.githubusercontent.com/3903757/123442614-0da16a80-d5a3-11eb-9612-e7ae212ca166.png)

**Comment by ghost** [comment]
I think it's okay to be styled like this @nbradbury Do you have any thoughts @Garance91540

**Comment by nbradbury** [comment]
> I think it's okay to be styled like this @nbradbury

Do you mean show errors in red, or keep it as-is?

**Update:** I submitted #4295 so everyone could so how red errors would look.

**Comment by ghost** [comment]
We should keep as is (no red) thanks @nbradbury
