### ISSUE TITLE
[Card Present Payments] The sdk keeps being connected to the reader when bluetooth is disabled

### ISSUE THREAD

**Issue by kidinov** [woocommerce/woocommerce-android#4288]
To reproduce go to:
* Settings
* Manager Reader 
* Connect to a reader
* Turn off Bluetooth

Notice that a connected state is presented and the disconnect button does do anything

**Comment by malinajirka** [comment]
StripeSDK should emit `onUnexpectedReaderDisconnect` in this scenario. If it doesn't I think we should fill a bug report and wait for a fix in the SDK. In case we'd like to fix this on our side, we could listen to BT state and disconnect from the reader, but I'd personally like to avoid adding workarounds to our codebase.

**Comment by malinajirka** [comment]
This issue seems to be related to https://github.com/stripe/stripe-terminal-android/issues/98 which seems to be fixed in v1.0.22 of Stripe Terminal SDK. PR with a fix is [here](https://github.com/woocommerce/woocommerce-android/pull/4300).
