### ISSUE TITLE
Payments: Scanning description too wide

### ISSUE THREAD

**Issue by nbradbury** [woocommerce/woocommerce-android#4296]
The text on the "Scanning for readers" screen spans the width of the dialog. It needs margin/padding.

![too-long](https://user-images.githubusercontent.com/3903757/123689584-5e25fb80-d821-11eb-838a-1718f0a51276.png)

**Comment by kidinov** [comment]
It's been fixed:

<img width="346" alt="image" src="https://user-images.githubusercontent.com/4923871/166442791-ef159bc3-be5f-41f3-a6d6-d3b06165d6e4.png">
