### ISSUE TITLE
Payments: Show reader label after updating to v2 API

### ISSUE THREAD

**Issue by nbradbury** [woocommerce/woocommerce-android#4320]
The Stripe v2 API supports a descriptive label for a reader, which is much friendlier than the ID we currently show. Once we update to the v2 API, we should support showing and updating the label.

https://stripe.com/docs/api/terminal/readers/update

**Comment by kidinov** [comment]
I didn't find a way to do so using the SDK so apparently, the backend effort is needed. I put it on the shelf for now

**Comment by malinajirka** [comment]
This is currently not planned, we can reopen the issue if we receive feedback from users.
