### ISSUE TITLE
Support status NOACCOUNT for /payments/accounts

### ISSUE THREAD

**Issue by kidinov** [woocommerce/woocommerce-android#4338]
There is a comment in the IOS app:

```
    /// The WCPay account onboarding has not been completed.
    /// Note that NO fields are present in the API response in this situation. The response is simplay an empty array.
    static let noAccount              = "NOACCOUNT"
```

We need to add proper support of this state to [Fluxc](https://github.com/wordpress-mobile/WordPress-FluxC-Android/blob/develop/plugins/woocommerce/src/main/kotlin/org/wordpress/android/fluxc/model/pay/WCPaymentAccountResult.kt#L38)

**Comment by kidinov** [comment]
Starting 2.9.0 WCPAy should never return an empty array

**Comment by AnirudhBhat** [comment]
@kidinov Can we close this issue or this still needs to be fixed?

**Comment by kidinov** [comment]
@AnirudhBhat yep! Min supported version of WCPay for IPP is 3.2.1 so we should be good here
