### ISSUE TITLE
Potentially missing status from for /payments/accounts

### ISSUE THREAD

**Issue by kidinov** [woocommerce/woocommerce-android#4339]
Potentially missing status:

* `restricted_soon`

Comes from [this file](https://github.com/Automattic/woocommerce-payments/blob/f979a76094b9c207dcc7797e50e10c4b13764c0b/client/account-status-settings/index.js)

Maybe has to be added [there](https://github.com/wordpress-mobile/WordPress-FluxC-Android/blob/develop/plugins/woocommerce/src/main/kotlin/org/wordpress/android/fluxc/model/pay/WCPaymentAccountResult.kt#L38)

**Comment by AnirudhBhat** [comment]
@kidinov How about this? Can we close this issue?

> Maybe has to be added [there](https://github.com/wordpress-mobile/WordPress-FluxC-Android/blob/develop/plugins/woocommerce/src/main/kotlin/org/wordpress/android/fluxc/model/pay/WCPaymentAccountResult.kt#L38)

The link referenced is expired.

**Comment by kidinov** [comment]
That's actually been addressed by mr @malinajirka in [e0fc2c716268a458f52ee033c61a28e759f26ca8](https://github.com/wordpress-mobile/WordPress-FluxC-Android/commit/e0fc2c716268a458f52ee033c61a28e759f26ca8)
