### ISSUE TITLE
Run connected tests on CI via emulator

### ISSUE THREAD

**Issue by aforcier** [woocommerce/woocommerce-android#435]
If possible, we should configure Travis to run our connected (UI) tests automatically. A parallelized build config with an emulator should hopefully do it, though we may have to look at running them via Firebase instead of an emulator.

**Comment by aforcier** [comment]
Update: Now that we're using CircleCI, Firebase is almost certainly the way to go based on @jtreanor's experiences with emulation on CircleCI.

**Comment by anitaa1990** [comment]
Based on internal discussion, we had decided to remove all the UI tests from the app. Currently, we only have screenshots tests running and those are already configured in CI. So maybe we can close this issue for now and reopen it, if we end up adding UI tests in the future.
