### ISSUE TITLE
Products: Add Prominent “Publish” Button for Draft Products

### ISSUE THREAD

**Issue by shiki** [woocommerce/woocommerce-android#4361]
Ref p91TBi-5oi-p2#comment-5224. 

When editing a draft product, the iOS app displays a prominent “Publish” button beside the options menu. We should do the same for Android.

![image](https://user-images.githubusercontent.com/198826/124501888-9e383180-dd7f-11eb-84c4-19d2c6977860.png)

The Publish button should only be visible if there are **no unsaved changes** to the draft product. If there are unsaved changes, the currently existing “Update” button should be displayed. The Publish button should be shown in the options menu in this case.

![image](https://user-images.githubusercontent.com/198826/124502215-45b56400-dd80-11eb-9302-7103de75a8c2.png)

## Specs 

- [ ] The Publish button should only be visible if there are **no unsaved changes**. If there are unsaved changes, the current “Update” button should be displayed. 
- [ ] The Publish button should be shown in the options menu if there are unsaved changes.

## Why This is Important

Right now, when you want to publish a draft product, customers have to navigate to Product Settings and change the Product Status and then press Update. It's a long process. Having a prominent Publish button would save them time.

**Comment by SowmiaS** [comment]
Hello 👋 ,
I would like to look into this issue. Kindly assign this issue to me.
Thanks.

**Comment by shiki** [comment]
Hi, @SowmiaS! That's awesome! Thank you.

**Comment by SowmiaS** [comment]
@shiki 

As per code, the product might have 4 product statuses. 

| Product Status     |     Actions possible				  |
|------------------|------------------------------|
| Draft 	   |  Save / Publish / Submit for Review (pending Review state)					            |
| Privately published   | Update	|
| Published   | Update	|
| Pending Review   | Save / Publish	|

**query for this issue #4361**

>When editing a draft product, the iOS app displays a prominent “Publish” button beside the options menu. We should do the same for Android.

Don't we need to have a "publish" option for pending review status as well? 😕 

**query for closed related issue #4362**

From issue #4362  
> When changes are made on a **draft product**, the app shows "Update" at the top right. This should be changed to "Save" to match iOS. 

From the above quote, I understand that the change is requested only for DRAFT products.

Understanding from PR #4639
> This PR changes the text from Update to Save in the Product Detail screen to match iOS.

From the above quote and code changes, I understand that the change from "update" to "save" is even for published products. Is the change only for DRAFT products or all products❓ 

Thanks.

**Comment by shiki** [comment]
Hi, @SowmiaS! Thanks for the detailed analysis.

> Don't we need to have a "publish" option for pending review status as well? 😕

Good question! Let's do that. It looks like that's what iOS does as well: 

<img src="https://user-images.githubusercontent.com/198826/141190416-0d23dd50-1613-4dae-a43b-e71777e30220.png" width="300">

> From the above quote, I understand that the change is requested only for DRAFT products.

iOS also changes the button to "Save" if the status is Pending Review. So we can do the same here.

<img src="https://user-images.githubusercontent.com/198826/141190545-5eafe317-ab87-4b0f-ba00-9ea564996e79.png" width="300">

Needless to say, I have not considered the Pending Review status at all. 😅  Sorry about that! 

> From the above quote and code changes, I understand that the change from "update" to "save" is even for published products. Is the change only for DRAFT products or all products❓

It should be for all product statuses. 

--- 

Please let me know if you have more questions!

**Comment by SowmiaS** [comment]
Thank you for the clarification @shiki 😀
