### ISSUE TITLE
[Card Present Payments] Finalize updating software flow

### ISSUE THREAD

**Issue by kidinov** [woocommerce/woocommerce-android#4367]
The BBPOS Chipper 2X BT does not auto-update, so it’s important for your application to support updates. Although they’re rare, updates usually contain important features or critical fixes. Make sure your app supports the following:
* If an update is available, display in the UI the estimated time to complete the update, along with options to continue or cancel.
* While the update is in progress, have the UI tell the user to leave the reader powered on and nearby. Block the user from navigating away from the page.
* Display a visual indicator of the update progress (e.g., percentage, progress bar).

From the doc - https://stripe.com/docs/terminal/checklist

**Comment by kidinov** [comment]
This probably should be done during our work on SDK 2.0

**Comment by malinajirka** [comment]
@kidinov Can we close this ticket or do we still plan to improve the update flow?

**Comment by kidinov** [comment]
@malinajirka nope, this pretty much implemented in the SDK v2 branch
