### ISSUE TITLE
Products: "Save as draft" option does not appear in the overflow menu if the very first change you make to a new product is to change the status to "Draft" in the product settings

### ISSUE THREAD

**Issue by designsimply** [woocommerce/woocommerce-android#4373]
Steps to reproduce:

1. Go to Products > Add new product ("+" at bottom right).
1. Immediately change the status to a draft by going to More > Product settings > Status > Draft.
1. Add a title, description, and price.
1. Observe that the "Save as draft" never appears.
1. Repeat the steps above except add the product details before trying to save the new product as a draft.
1. Observe that now you can see a "Save as draft" option.

**Result:** if you change the status in product settings to "Draft" as the _very first step_ when creating a new product, then you are never offered the option to "Save as draft" in the overflow menu. ([3m43s](https://user-images.githubusercontent.com/1119271/124664121-37db0e00-de68-11eb-93c3-9d3bfe25ed1c.mp4))

New product > Product settings|Change status to draft|"Save as draft" never appears<br>even after making other changes
---|---|---
<img src="https://user-images.githubusercontent.com/1119271/124663447-568cd500-de67-11eb-8dbe-2d59137b756a.png" width="250" alt="image">|<img src="https://user-images.githubusercontent.com/1119271/124663431-4ffe5d80-de67-11eb-894e-cd4a2bdf4c8d.png" width="250" alt="image">|<img width="250" alt="Screen Shot 2021-07-06 at Jul 6 2 35 34 PM" src="https://user-images.githubusercontent.com/1119271/124663733-b2575e00-de67-11eb-88bb-b4d2e2423ab9.png">

<sup>Tested with WCAndroid 7.0-rc-1 on Pixel 3 Android 11.</sup>

<sup>(internal reference: p5T066-2sv-p2#comment-8976 /ht @anitaa1990)</sup>

**Comment by shiki** [comment]
This is still valid as of 75db038807.
