### ISSUE TITLE
[Mobile Payments] Uncertainty around available actions on post-payment receipt modal 

### ISSUE THREAD

**Issue by malinajirka** [woocommerce/woocommerce-android#4389]
Refer to https://github.com/woocommerce/woocommerce-ios/issues/4584

**Comment by malinajirka** [comment]
Fixed - we currently show "Save receipt & continue" button instead.

**Comment by joshheald** [comment]
@malinajirka Is the "Save receipt & continue" button shown in addition to the print/email options, in place of the previous "No thanks" button?

**Comment by malinajirka** [comment]
@joshheald Yes, that's correct ;).
