### ISSUE TITLE
Ability to add products

### ISSUE THREAD

**Issue by astralbodies** [woocommerce/woocommerce-android#44]
Based on: 575277-zd-woothemes

**Comment by gemmagarner** [comment]
There have been several requests for this feature on the WooCommerce Facebook page:

> When would u launch mobile app for adding new products and editing the products thru mobile app

**Comment by AmandaRiu** [comment]
@gemmagarner We are actively working towards this goal. We just finished up the ability to view product details in the app. This is going out in the next release (version 1.7). The designers are still working on product listing for displaying all products and editing a product should come after.

**Comment by AmandaRiu** [comment]
Closing this ticket as a new one will be created when the designs are finished and approved, and the project is ready to be developed on.
