### ISSUE TITLE
[Product Add-ons] Create Product Add-ons standard data list view

### ISSUE THREAD

**Issue by ThomazFB** [woocommerce/woocommerce-android#4408]
After all Product Add-ons data are available through #4407, we should display the add-on data inside a dedicated view now including global add-ons data.

Figma:
<img width="371" alt="Screen Shot 2021-07-12 at 23 59 28" src="https://user-images.githubusercontent.com/5920403/125383199-6f1c5400-e36d-11eb-8402-c0e01d701aa9.png">

**Comment by wzieba** [comment]
@ThomazFB Here we should show Product-specific _and_ global add ons right?

**Comment by ThomazFB** [comment]
@wzieba, correct! I updated the issue description to make this clear. Thanks!
