### ISSUE TITLE
[Product Add-ons] [FluxC] Make Add-on Groups data available

### ISSUE THREAD

**Issue by ThomazFB** [woocommerce/woocommerce-android#4410]
Once #4406 is done, we want to make Global Add-ons available. Global Add-ons are the ones that aren't specifically bound to a Product and can be list to every Product available at the store. 

To do so, we should create the Add-on Groups entity through remote fetching of site data, these groups will store all global Add-ons so we can list every Order add-on correctly.

We should sync these Global Add-ons everytime the app starts or the store gets switched

**Comment by wzieba** [comment]
@ThomazFB WDYT about doing this task _after_ #4407? My argument would be that by doing #4406 and #4410 first, we would have all sources of data in order to combine them in #4407.

**Comment by ThomazFB** [comment]
I think it makes total sense, let's go with this strategy! I'll update the description to match this.

**Comment by ThomazFB** [comment]
@wzieba I think it makes total sense, let's go with this strategy! I'll update the description to match this.

**Comment by ThomazFB** [comment]
Closed after https://github.com/wordpress-mobile/WordPress-FluxC-Android/pull/2099
