### ISSUE TITLE
[Card Present Payments] Add call out for support

### ISSUE THREAD

**Issue by ctarda** [woocommerce/woocommerce-android#4421]
Add a callout in the app for support, aside from the standard place.

We need to add the following rules to the request:
pbUcTB-kn-p2#comment-1333

**Comment by ctarda** [comment]
FieldIds are here: pbUcTB-kn-p2#comment-1521

**Comment by malinajirka** [comment]
Related PR on iOS https://github.com/woocommerce/woocommerce-ios/pull/4667

**Comment by kidinov** [comment]
P2 with details pdfdoF-L-p2
