### ISSUE TITLE
[Product Add-ons] Remove Add-ons feature flag

### ISSUE THREAD

**Issue by ThomazFB** [woocommerce/woocommerce-android#4424]
Remove the Product Add-ons feature flag once the project is ready to be delivered.

## Action Items

- [ ] Test the flows before opening the feature flag. See #4439. 
- [ ] Compare with iOS to make sure we're delivering the same things. Whatever comes up may or may not be done after the feature flag is opened. 
- [ ] Place the Experimental toggle switch to control the Add-ons feature instead of the code Feature flag at #4686

**Comment by shiki** [comment]
☝️ @ThomazFB I added a couple of items that we can probably do before opening the feature flag. Let me know if it makes sense or not. 🙂

**Comment by ThomazFB** [comment]
Makes total sense, thanks for the addition, @shiki!

**Comment by ThomazFB** [comment]
@shiki I've updated the description with the Experimental Toggle action item we discussed earlier.
