### ISSUE TITLE
[Product Add-ons] Write test plan

### ISSUE THREAD

**Issue by shiki** [woocommerce/woocommerce-android#4439]
From p91TBi-5B4-p2#comment-5534 by Sheri:

> My next step will be to create a draft test plan for full flows around add-ons and also note any gotchas I can think of or pull in from the iOS side (since it was launched already, which is nice to have!).

**Comment by shiki** [comment]
Something to note: All field types are supported. Images are only shown as text though. 

p91TBi-5B4-p2#comment-5534

**Comment by designsimply** [comment]
I wrote up some test scenarios and expected outcomes for Product Add-ons. They can go into a testing guide or just guide how the feature is tested on PRs and in beta. And it's expected that we may iterate on these lists as the product matures, so we will continue to work together on them. 

#### Product Add-ons Scenarios to Consider

* All add-on types (Multiple Choice, Checkboxes, Short Text, Long Text, File Upload, Customer Defined Price, Quantity, Heading) are viewable in order details and editable in product details, including text and image files.
* Add-on prices appear correctly in order details and match what the user saw it during checkout.
* Products with add-ons should not be grouped if more than one of the same item is ordered with different add-ons. 
* Add-ons should work well combined with variations, i.e. if each size has it’s own add-ons.
* Add-ons can be applied to all products or by category in product details.
* The order the add-ons appear on a product can be set in product details.

#### Product Add-ons Outcomes To Pay Attention To

* I expect any refunded items to also reflect any pricing included in that item’s add-ons.
* I shouldn’t be able to edit add-ons in a product and see those changes in past orders.
* Any changes to add-ons in orders should notify users of a change via email. (Double check this.)
* Any changes made in the app should be reflected remotely.
