### ISSUE TITLE
Shipping label refunds will not work if the order contains a total product decimal quantity of less than one [INVALID]

### ISSUE THREAD

**Issue by designsimply** [woocommerce/woocommerce-android#4441]
Steps to reproduce:

1. Plugin requirements: [WooCommerce Shipping & Tax](https://wordpress.org/plugins/woocommerce-services/) and [WPC Product Quantity for WooCommerce](https://wordpress.org/plugins/wpc-product-quantity/).
1. Go to WP Admin > WPClever > Product Quantity, change Decimal Quantities to Yes, add a Minimum and a Step of 0.5.
1. Submit an order that contains a decimal quantity of less than one, such as 0.5.
1. In the app, purchase a shipping label for the order from the previous step.
1. Try to get a refund for the shipping label.

**Result:** refunding a shipping label if the total product quantity for an order is less than one will fail with a notice that says to try again. Trying again will not help though because the WooCommerce Shipping & Tax plugin only supports refunding by whole item quantities (internal reference:  p5T066-2uV-p2#comment-9152).

> Something went wrong with the refund. Please try again

Decimal quantity >1|Should this be eligible for refund?|Refund request fails, <br>trying again will never work
---|---|---
<img src="https://user-images.githubusercontent.com/1119271/125717079-33f3334e-fd2d-4d4e-86fb-6fe3d605a0ba.png" width="270" alt="Screenshot_20210714-193825">|<img src="https://user-images.githubusercontent.com/1119271/125716759-7d16ba89-6c13-4d10-ab5e-cf88915b4744.png" width="270" alt="Screenshot_20210714-193653">|<img src="https://user-images.githubusercontent.com/1119271/125716756-e5c9971d-396e-4be9-8f61-486c34d295d3.png" width="270" alt="Screenshot_20210714-193714">

**Note:** I understand this may be quite an edge case, and I am comfortable either closing this issue as wontfix or keeping it open just long enough to see if any user reports reach us mentioning it as a point of confusion.

**Comment by hichamboushaba** [comment]
The cause of this is that shipping labels refunding against the staging connect server requires that the refunding has to be requested within 2 minutes of the shipping label creation, it's not related to the order item's quantity.

**Comment by designsimply** [comment]
I didn't know about the 2-minute limit! 

I re-tested and confirmed that I could get a shipping label refund in the scenario noted above if I did it within 2 minutes. 👍
