### ISSUE TITLE
Add-ons: pricing below items incorrect in order details if products ordered are using a decimal quantity

### ISSUE THREAD

**Issue by designsimply** [woocommerce/woocommerce-android#4442]
Steps to reproduce:

1. Install and activate the [Product Add-Ons](https://woocommerce.com/products/product-add-ons/) extension.
1. Install and activate a plugin that supports decimal quantities, such as [WPC Product Quantity for WooCommerce](https://wordpress.org/plugins/wpc-product-quantity/). To use this plugin as an example, go to WP Admin > WPClever > Product Quantity, change Decimal Quantities to Yes, add 0.5 for Minimum and Step.
1. Make sure your store has at least one product with at least one add-on available that changes the price.
1. Start a new order.
1. Add a decimal quantity of an item.
1. Add a decimal quantity of the same item except include an optional add-on as well.
1. Submit the order.
1. View the order details in the app and check to see if the calculations below each product with add-on(s) is correct or not.

**Result:** total amounts for each line item appear correct and match the web (except sometimes there are rounding errors) and the add-on calculations listed below each product are incorrect in the app if the products contain decimal quantities.

### Example: Order #1464 (incorrect pricing below each product with add-ons)

<img height="340" alt="Screen Shot 2021-07-14 at Jul 14 8 54 27 PM" src="https://user-images.githubusercontent.com/1119271/125726365-c42c45fb-dc5b-4b6b-8098-f6ae8e6a8f2d.png"> <img src="https://user-images.githubusercontent.com/1119271/125726348-f3758603-1a9d-4e64-b689-df25114474b1.png" height="340" alt="Screenshot_20210714-205158">

### Example: Order #1465 (incorrect add-on pricing, also contains a strange rounding error) 

<img height="340" alt="Screen Shot 2021-07-14 at Jul 14 9 07 07 PM" src="https://user-images.githubusercontent.com/1119271/125726758-efd4d169-d92c-4501-a0eb-c635de78111b.png">  <img src="https://user-images.githubusercontent.com/1119271/125727136-9d293fc4-82fc-40c8-aad7-37ab9dc9bd78.png" height="340" alt="Screenshot_20210714-210712">

<sup>Tested with WCAndroid 7.1-rc-1 on Pixel 3 Android 11 using site `worthwhile-seahorse.jurassic.ninja` running WordPress 5.7.2, Jetpack 9.9, WooCommerce 5.5.1.</sup>

**Comment by hichamboushaba** [comment]
Can you please clarify what's wrong for each screenshot, from what I see the app is displaying the correct pricing if the totals are correct?
For example, the product `Buttercup` total is `1$`, and its quantity is `0.5`, so the item's price is `2$`, and that's what the app is displaying.

**Comment by designsimply** [comment]
Of course! You are correct that the product total on the right in the first example is correct and matches the web for the line item total of $7, but the line item total for the same product/add-on combination in the 2nd example is incorrect—it shows a line item total of $12.98 when it should be $13.00. Also, the prices showing below the add-ons (not the totals on the right) don't make sense to me. 

On order 1464, the product cost is $2 with on add-on of gift wrapping for $6. In this example, I ordered 0.5 of $2 and one add-on for $6, that means `(0.5 x $2) + $6 = $7` and that is shown correctly on the right but the $14 below the item doesn't make sense to me. Why does it say $14 for 0.5 quantity of that item? 

<img src="https://user-images.githubusercontent.com/1119271/125792395-6da9d760-9be0-4b2a-a7ad-61a35d3894b5.png" width="270" alt="Screenshot_20210714-205158">

On order 1465, I again ordered the product for $2 plus an add-on for $6—except I ordered a quantity of 3.5 this time. In this case, I expected the total on the right to be `(3.5 x $2) + $6 = $13` but the app shows the total on the right as `$12.98` (off by $0.02) and below the item it says "Gift Wrapping ･ 3 x US$3.71". Why does it say $3.71 for 3.5 quantity of a $2 item? Also note that the quantity showing is `3` but I ordered a quantity of `3.5`. The $3.71 number appears to be the the total (off by $0.02) divided by the quantity but it doesn't make sense to me to list it like that.

<img src="https://user-images.githubusercontent.com/1119271/125796989-90445f96-7bf0-4946-83e1-9c7d4758bd21.png" width="270" alt="Screenshot_20210714-210712">

I expected to see no rounding errors (i.e. the missing $0.02 in the 2nd example) and I expected the lines below each item to show a list of the add-on names and prices similar to how the web displays it.

**Comment by hichamboushaba** [comment]
> In this example, I ordered 0.5 of $2 and one add-on for $6, that means (0.5 x $2) + $6 = $7 and that is shown correctly on the right but the $14 below the item doesn't make sense to me. Why does it say $14 for 0.5 quantity of that item?

Yes, you are right here, but IMO this can wait for the addons project, as we don't support them in the Android app.
And this is not a regression because of the previous PR, ~because if you check the screenshot you posted here p5T066-2uV-p2#comment-9200, in 7.0 the app was showing `22$` for the item!!~ because previously the products were completely hidden.

> On order 1465, I again ordered the product for $2 plus an add-on for $6—except I ordered a quantity of 3.5 this time. In this case, I expected the total on the right to be (3.5 x $2) + $6 = $13 but the app shows the total on the right as $12.98 (off by $0.02) and below the item it says "Gift Wrapping ･ 3 x US$3.71". Why does it say $3.71 for 3.5 quantity of a $2 item? Also note that the quantity showing is 3 but I ordered a quantity of 3.5. The $3.71 number appears to be the the total (off by $0.02) divided by the quantity but it doesn't make sense to me to list it like that.

Similar to the above, the cause is not changing to decimal quantities support, but because we don't support addons yet, which means we don't handle where the price is for individual item or for addons, and as the above point, it's not a regression, as even in 7.0 the price was wrong (11.13 vs 13)

Fixing those bugs would require the same amount of work we need from the addons project, and it just started now in Android https://github.com/woocommerce/woocommerce-android/pull/4436

**Comment by hichamboushaba** [comment]
Some updates to this, we can fix this partially pretty easily, check the PR #4446.

The other issue would require bigger changes, and I'm not even sure if they can be fixed after working on the addons project or not, they may need some changes from core with proper API support, as for now, they impact core as well https://d.pr/i/6Jn4vP
