### ISSUE TITLE
Replace "An unexpected error occurred" with "Something went wrong"

### ISSUE THREAD

**Issue by nbradbury** [woocommerce/woocommerce-android#4449]
There are several places where we say "An unexpected error occurred," which is kind of silly. It's an error, so of course it's unexpected. Let's replace these with "Something went wrong." Although that's as equally unhelpful as "unexpected error," it is at least friendlier.

**Comment by rossanafmenezes** [comment]
While searching the codebase for the “An unexpected error occurred.” string I was not able to find any:

![Screen Shot 2022-02-08 at 11 47 50 AM](https://user-images.githubusercontent.com/30724184/152978808-058f944e-3a58-4234-ad61-5995355b5337.png)

Even though I was not able to find any PRs that have addressed this specific issue, the proposed string "Something went wrong" can actually be found in several different files. So, after confirming it with @nbradbury, I will close this issue.
