### ISSUE TITLE
Shipping Labels: incorrent weight when the products are not synchronized

### ISSUE THREAD

**Issue by pmusolino** [woocommerce/woocommerce-android#4461]
It happened to me during a test that the weight of all products in the Package Details screen was `0.0 kg` instead of `3.4 kg`.

In a [discussion](https://a8c.slack.com/archives/C026HH75ECA/p1626693302001800) with @anitaa1990 , we weren't able to replicate the issue, but I think that when the data of products are not synced properly, they are causing incorrect weights to be displayed. In this specific case, the product was added from `wp-admin`, I created the order and with the app already open, I tried to create the shipping label.

**Comment by hichamboushaba** [comment]
I think the only case where this can happen is if the products were already cached with a different weight, as to avoid long loading times in the form, we don't re-fetch cached products in the form, but if they are not cached, we will fetch them, and we will show an error if fetching them fails.

I think we should close this issue, WDYT @anitaa1990 @pmusolino?

**Comment by pmusolino** [comment]
Not sure this was the case, because the product was created just 1 minute before the order, and it was not yet stored in the app (that was opened while I was creating the product from the web). So, I directly refreshed the order list, opened the order and tried to create the shipping label.

**Comment by hichamboushaba** [comment]
I think we fetch products when we open the order details, not sure though.
Anyway, if we fail to fetch any non-cached product, and it's not deleted in the store, we will show an error: https://github.com/woocommerce/woocommerce-android/blob/9597597f929868b669f0f2407cfff84cc28e3f4f/WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/shippinglabels/creation/EditShippingLabelPackagesViewModel.kt#L127-L132

Unless there is a way to reproduce this, I don't see how we can investigate it more 🙂

**Comment by pmusolino** [comment]
Feel free to close the issue, since it's not easy to reproduce it. As far I remember, I'm pretty sure I didn't saw any error about fetching the products. 👍
