### ISSUE TITLE
Card Reader Tutorial is broken on tablets

### ISSUE THREAD

**Issue by malinajirka** [woocommerce/woocommerce-android#4478]
**Describe the bug**
The layout of the tutorial is broken on tablets - content drawn on top of each other and outside borders of the view.

**To Reproduce**

- Use tablet
1. Clear app data or set the ` SHOW_CARD_READER_CONNECTED_TUTORIAL` flag to true using Flipper
2. Click on App settings
3. Click on "Manage card reader"
4. Click on "Connect to card reader"
5. Finish the connection and notice the tutorial looks broken

**Screenshots**
![Screenshot_1627022756](https://user-images.githubusercontent.com/2261188/126747366-43609f44-bee8-4e9e-9da5-18957bf1ca47.png)

**Comment by nbradbury** [comment]
Note that this is broken on portrait tablets, too.

![portrait](https://user-images.githubusercontent.com/3903757/126789561-b626b53e-60ff-446c-88de-a82c0560accd.png)
