### ISSUE TITLE
Linked Products: consider filtering out the current product from the list when linking products

### ISSUE THREAD

**Issue by designsimply** [woocommerce/woocommerce-android#4521]
Should Android match with iOS regarding filtering out the current product from the list when adding linked products?

Steps to reproduce:

1. Open any product for editing.
1. Go to the Linked products detail.
1. Attempt to add the product you are currently editing as an Upsell.
1. Attempt to add the product you are currently editing as a Cross-sell.

**Result:** it's possible to add a linked product to itself on Android ([1m7s](https://user-images.githubusercontent.com/1119271/127563097-418d2d74-ec28-4d3d-90a1-181a761e77e6.mp4)) but on iOS the current product is filtered out of the "Add product" screen so you cannot link a product to itself ([52s](https://user-images.githubusercontent.com/1119271/127563136-1fa736db-4c9e-481d-8c47-ed6609a466fb.mp4)).

<img src="https://user-images.githubusercontent.com/1119271/127563706-59e7453c-6258-47db-8ad5-5a144f55cb1c.png" width="270" alt="image"> <img width="270" alt="Screen Shot 2021-07-29 at Jul 29 2 50 15 PM" src="https://user-images.githubusercontent.com/1119271/127564016-ec7812d9-82d8-4248-b42e-f294d4569f59.png">
<sup>Tested with WCiOS 7.2.0.0 TestFlight beta on iPhone 11 iOS 14.7.1.</sup>

<sup>(internal reference: p5T066-2wI-p2#comment-9355 /hat tip @pmusolino)</sup>

**Comment by SowmiaS** [comment]
Hello 👋 
I would like to look into this issue. Please assign this issue to me.
Thanks
