### ISSUE TITLE
Reviews: button for flagging all the reviews as read is missing

### ISSUE THREAD

**Issue by pmusolino** [woocommerce/woocommerce-android#4531]
Under the Reviews tab, on iOS on the top right corner https://github.com/woocommerce/woocommerce-ios/issues/4295, there is a button for flagging all the reviews as read, but on Android, the functionality is missing.
We should add it also on Android. The design is on Figma.

**Comment by anitaa1990** [comment]
This is available in Android too so will close this issue 👍
