### ISSUE TITLE
Long store names in My Store

### ISSUE THREAD

**Issue by nbradbury** [woocommerce/woocommerce-android#4540]
If a store has a name long enough to wrap to another line, it overlaps the "My Store" heading.

![long-name](https://user-images.githubusercontent.com/3903757/127915401-485b81d3-3cca-4690-a56b-342390f5628f.png)

**Comment by kidinov** [comment]
Probably adding "ellipsis - end" will be an ok solution for this edge case

**Comment by hafizrahman** [comment]
Unless this introduces some technical or design issue, I feel the app should give ample space (say maybe allow three or four lines) to display a full name before adding ellipsis. This is not scientific but a store name is likely something that is important, personal, and valuable to the store owner, and it will be nice if they can see it in the app without being cut-off.

**Comment by samiuelson** [comment]
I verified this is already fixed - store name is placed under the screen title.
