### ISSUE TITLE
Improve copy for the help center

### ISSUE THREAD

**Issue by kidinov** [woocommerce/woocommerce-android#4542]
Based on the comment - https://github.com/woocommerce/woocommerce-ios/pull/4667#issuecomment-891172650

> Hi there, as we are adding more text, I find all this text a bit overwhelming and I wonder if we could play with visual hierarchy to make this a bit clearer:
> 
> Could we keep displaying the Row title (ie "Help Center") in System Label / Primary Label Color and display the subtitle ("Get answers to question you have") as System Label / Secondary Label Color? (in both light and dark mode) Thanks!
>

**Comment by AnirudhBhat** [comment]
Fix for this has already been implemented in Android. Closing this issue.

<br>
<img src="https://user-images.githubusercontent.com/1331230/129679324-2bf873e5-7faa-470c-9851-2434c1c67d9e.png" width="300" height="600"> |  <img src="https://user-images.githubusercontent.com/1331230/129679338-1b40bc94-4caf-4d94-9613-42e50fbd0d19.png" width="300" height="600">
