### ISSUE TITLE
Shipping Labels: Should check for US military states and US domestic territories to require customs form

### ISSUE THREAD

**Issue by itsmeichigo** [woocommerce/woocommerce-android#4555]
**Describe the bug**
As [pointed out by](https://github.com/woocommerce/woocommerce-ios/pull/4711#discussion_r681470281) @koke - we should follow the web implementation to require customs form when creating shipping labels to / from one of [US military states](https://github.com/Automattic/woocommerce-services/blob/dbeed610f336f8db7995743765dbcd0ff2e18474/client/extensions/woocommerce/woocommerce-services/state/shipping-label/constants.js#L1).

Current on the Android app this has not been taken to consideration, therefore the shipping label creation form is missing customs row when one of the addresses shipping labels to / from one of the US military states.

**Updated**: The check for customs form should also consider domestic territories like the [plugin's implementation](https://github.com/Automattic/woocommerce-services/blob/dbeed610f336f8db7995743765dbcd0ff2e18474/client/extensions/woocommerce/woocommerce-services/state/shipping-label/selectors.js#L191).

**To Reproduce**
1. Go to Orders tab
2. Click on an order with Processing status and select Create Shipping Label
3. Update destination address to one of the US military states.
4. Notice that customs row is not present in the shipping label creation form

**Screenshots**
<img src="https://user-images.githubusercontent.com/5533851/128162627-5f3d5e97-b969-4b67-92b2-b3b56f56297f.png" width=400 />

**Expected behavior**
Customs row should be present, origin address should require a phone number if empty.

**Mobile Environment**
Please include:
- Device: Pixel 3a XL
- Android version: 10
- WooCommerce Android version: 7.2-rc-1

**Comment by hichamboushaba** [comment]
There is no need for any additional logic for domestic territories: https://github.com/Automattic/woocommerce-services/pull/2432
