### ISSUE TITLE
Payment onboarding starts over

### ISSUE THREAD

**Issue by nbradbury** [woocommerce/woocommerce-android#4569]
* Enable "Don't keep activities"
* Switch to a store that will cause onboarding to show an error screen
* Tap "In-person payments" in settings
* Wait for the loading screen to disappear and for the error screen to show
* Tap "Contact support"
* Hit the back button
* Notice the onboarding flow starts all over again

**Comment by malinajirka** [comment]
@nbradbury I'm on the edge if we should fix this. Unless I'm missing something I believe the most appropriate solution would be to store the state into SavedState. However, it has imho two downsides
1. It increases the complexity of the code even though the end result is still identical -> only the user won't see the loading screen for 0-2 seconds.
2. System can restore killed/destroyed activity even two months after the app is moved into background -> the onboarding state might be completely different by then, so I think starting the flow from the beginning when the activity is restored is a valid approach.

I understand that the behavior feels weird when the user opens "contact support" and come back, but this flow should happen only in a very very edge cases on an extremely low end devices. Usually the system kills the activity when it's in the background for several hours or days. 

Wdyt?

**Comment by nbradbury** [comment]
> I understand that the behavior feels weird when the user opens "contact support" and come back, but this flow should happen only in a very very edge cases on an extremely low end devices

I think that's a fair point, and I'm fine to close this.
