### ISSUE TITLE
Shipping labels: improve scrolling behavior for address form

### ISSUE THREAD

**Issue by hichamboushaba** [woocommerce/woocommerce-android#4614]
We need to improve scrolling behavior for the address form:

1. When there is a general error about the form, the label may be hidden if it was scrolled to the bottom, we should scroll to the top.
2. When there are local field errors, we should scroll to them to highlight them.

**Comment by jd-alexander** [comment]
Based on my investigation, I'm planning to tackle the issue of automatically scrolling to the first input field with an error by introducing a new method in the `EditShippingLabelAddressFragment.kt`. This method will be responsible for identifying the first field with a validation error and checking if it's currently off-screen. If it is, I'll execute a smooth scroll action on the `ScrollView` to bring the field into view. To achieve this, I'll leverage the `viewStateData` observer within the `observeViewState` function, which will trigger the scrolling method whenever the view state changes and an error is present. This approach ensures that any validation errors are immediately brought to the user's attention, enhancing the overall user experience by eliminating the need for manual scrolling to find the problematic field.
