### ISSUE TITLE
Add support for a reader location registration

### ISSUE THREAD

**Issue by kidinov** [woocommerce/woocommerce-android#4641]
- [x] #4818
- [x] #4825
- [x] #4876
- [x] #4878
- [x] #4881

https://stripe.com/docs/terminal/sdk-migration-guide#bluetooth-reader-locations

https://github.com/Automattic/woocommerce-payments/pull/2830

**Comment by anitaa1990** [comment]
Closing since all the issues mentioned in the description is marked as Done
