### ISSUE TITLE
Shipping labels: app crash after entering "." in any numeric field on the Add new package screen

### ISSUE THREAD

**Issue by designsimply** [woocommerce/woocommerce-android#4656]
Steps to reproduce:

1. Create a label for any order, confirm addresses, and move on to package selection.
1. Tap "Package selected".
1. Observe that you arrive at the "Add a new package" screen
1. Note that the store in this example did not have any packages to start with (though I'm not sure if that's relevant).
1. Tap any numeric field, i.e. "Length" or "Empty package weight".
1. Add a "." to the field.
1. Crash.

**Result:** the app will crash after entering "." in any numeric field. ([41s](https://cloudup.com/cUOAQ5t2Z5d))

<img src="https://user-images.githubusercontent.com/1119271/130193275-f630a547-5079-403c-8a17-8082a6e4d794.png" width="270" alt="Screenshot_20210820-004609">
<sup>Tested with WCAndroid 7.2-rc-2 and WooCommerce-pr-4596-build-45290.apk on Pixel 3 Android 11 logged in as testuser011121 using site hilarious-sea.jurassic.ninja running WordPress 5.8, Jetpack 10.0, WooCommerce 5.6.0, WooCommerce Shipping & Tax 1.25.18.</sup>

**Comment by hafizrahman** [comment]
Thanks for the report! Looking.

**Comment by hichamboushaba** [comment]
Closed by #4658
