### ISSUE TITLE
Small non-blocking issues to cover

### ISSUE THREAD

**Issue by kidinov** [woocommerce/woocommerce-android#4659]
- [x] #4848
- [x] #4847
- [x] Consider making force update cancelable
- [x] #4859
- [x] Add proper support for the update dialog in the dark theme
- [x] Check if we still need to open optional update dialog if available right after user enters card reader details screen
- [x] Check if it's possible to update a reader connected to a charger with <50% of a battery (NO, not possible)

**Comment by anitaa1990** [comment]
Closing since all the issues mentioned in the description is marked as Done
