### ISSUE TITLE
Small blocking issues to cover

### ISSUE THREAD

**Issue by kidinov** [woocommerce/woocommerce-android#4661]
- [x] #4732
- [x] #4749
- [x] #4740
- [x] #4767
- [x] #4765
- [x] #4718
- [x] #4699
- [x] #4754
- [x] #4778
- [x] #4725
- [x] Sometimes I end up "stuck" on "Connecting to Reader" screen. I see that the CardReaderDetail already displays "connected" reader, but the connection flow doesn't disappear. (P.S. I did not click on "cancel"). I was able to reproduce this bug just once 🤷.
- [x] This bug probably exists in the v1 implementation: When I click on "disconnect" it sometimes fails but still displays "Card Reader not connected" screen -> when I click on connect it always fails with "You must disconnect from reader before discovering readers.". I think we might want to leave the "manage card reader/cardReaderDetail" screen when the user taps on disconnect to make sure we always display the up-to-date screen.
- [x] Sometimes the log say E/WooCommerce-CARD_READER: Connecting to reader succeeded. but "not connect" state is still shown. (seems like a bug in the SDK since according to the logs I didn't receive class=ProxyTerminalListener message=onConnectionStatusChange(CONNECTED))
- [x] #4764

**Comment by AnirudhBhat** [comment]
>Disconnect button doesn't work from the first time

Here's my observation regarding this issue. We have the below logic for disconnecting from the reader
```private fun onDisconnectClicked() {
        tracker.track(AnalyticsTracker.Stat.CARD_READER_DISCONNECT_TAPPED)
        launch {
            clearLastKnowReader()
            val disconnectionResult = cardReaderManager.disconnectReader()
            if (!disconnectionResult) {
                WooLog.e(WooLog.T.CARD_READER, "Disconnection from reader has failed")
                showNotConnectedState()
            }
        }
    }
```
    
If I press `disconnect`, `cardReaderManager.disconnectReader`  will return true on successful disconnect. But, I don't see any code for moving the state from `connected` to `not connected` when disconnection is successful. It happens only in the case of disconnection failure. Which should ideally stay on the same `connected` state on failure. Now it's happening the other way around.

**Comment by malinajirka** [comment]
@AnirudhBhat I believe that when the disconnect succeeds [this code](https://github.com/woocommerce/woocommerce-android/blob/7051c80dbdbfb481bf20a49e38ab17ea6d46eef1/WooCommerce/src/main/kotlin/com/woocommerce/android/ui/prefs/cardreader/detail/CardReaderDetailViewModel.kt#L59) should take care of changing the `connected` state to `not connected` state. Wdyt?

**Comment by AnirudhBhat** [comment]
@malinajirka I see that the for reader disconnection, `readerStatus` gets updated only when `onUnexpectedReaderDisconnect` gets called in `TerminalListenerImpl`. Does the same callback gets called in case of normal disconnect as well (By normal I mean, user clicking disconnect button)?

**Comment by malinajirka** [comment]
I mean, I tested clicking on the disconnect button and it works without issues for me - so I'd say yes, but I haven't verified which code path updates the "connected" to "not connected" state.

**Comment by AnirudhBhat** [comment]
@malinajirka You are right. It is working fine in `develop` branch. I have explained why it wasn't working when we migrated to Stripe SDK v2 in this PR https://github.com/woocommerce/woocommerce-android/pull/4716

**Comment by malinajirka** [comment]
Ahh, I see - sorry, I missed that ;)!

**Comment by anitaa1990** [comment]
Are we good to close this issue @kidinov @malinajirka @AnirudhBhat ?
