### ISSUE TITLE
Tapping Support Reply Notification Opens to My Store instead of the Tickets screen.

### ISSUE THREAD

**Issue by hafizrahman** [woocommerce/woocommerce-android#4691]
**Describe the bug**
While testing #4655, I discovered that when an incoming support reply notification is tapped, it opens to the My Store page.

The culprit seems to be `null` notification value in `viewModel.handleIncomingNotification(localPushId, notification)` in the MainActivity, but I'm not sure why it's null.

And because it is null, here in  MainActivityViewModel the notification just moves the app to the My Store page instead of opening :
```
    fun handleIncomingNotification(localPushId: Int, notification: Notification?) {
        notification?.let {
            when (localPushId) {
                it.channelType.getGroupId() -> onGroupMessageOpened(it.channelType)
                it.noteId -> onZendeskNotificationOpened(localPushId, it.noteId.toLong())
                else -> onSingleNotificationOpened(localPushId, it)
            }
        } ?: run {
            triggerEvent(ViewMyStoreStats)
        }
    }
```
the passed notification parameter is null so it just goes to `triggerEvent(ViewMyStoreStats)`.
In my test for 

**To Reproduce**
1. Go to Settings > Help & support > Contact support
2. Send a support question, and ask a Happiness Engineer to reply to your ticket
3. Wait for notification to appear, and meanwhile exit the Contact support screen
4. Tap notification 
5. It will open to "My store" screen

**Expected behavior**
On step 5, it should open to the tickets screen instead.

Thank you to @erricgunawan for helping troubleshoot this.

**Comment by anitaa1990** [comment]
Fixed in #4673
