### ISSUE TITLE
[Card Present Payments] Make changes to the several readers found the screen as per new Figma design

### ISSUE THREAD

**Issue by kidinov** [woocommerce/woocommerce-android#4692]
vaw3DvewbUwuQnPXpdNGGH-fi-62%3A29548

**Comment by malinajirka** [comment]
I believe it's the other way round - the dark mode designs in figma are outdated. The latest design is
<img width="322" alt="Screenshot 2021-09-07 at 14 47 46" src="https://user-images.githubusercontent.com/2261188/132347148-d04e8a99-7d38-43ee-b853-a6b27022e00c.png">

Wdyt @kidinov ?

**Comment by kidinov** [comment]
Yes, probably. I was confused by the IOS implementation which I was thinking is the most relevant
