### ISSUE TITLE
[Mobile Payments] Tell users to briefly press reader power button to turn it on

### ISSUE THREAD

**Issue by allendav** [woocommerce/woocommerce-android#4745]
Right now we display:

> Press the power button of your reader until you see a flashing blue light

That's not quite right. Merchants that press (and hold) the button that way may actually turn a reader off if they hold the button long enough.

Related iOS PR: https://github.com/woocommerce/woocommerce-ios/pull/4948

cc @woocommerce/mobile-designers

**Comment by Garance91540** [comment]
Hi Allen, to confirm: are you referring to this modal below:

<img width="296" alt="Screen Shot 2021-09-08 at 3 59 03 PM" src="https://user-images.githubusercontent.com/28450084/132523497-61563cdc-52c8-4c55-9b02-d8dc29b14929.png">

and suggesting to update the current text ("Press the power button of your reader until you see a flashing 
blue light") with "Turn on your card reader by briefly pressing its power button. When powered on, the LED will blink blue." 

That makes sense to me!

**Comment by AnirudhBhat** [comment]
This is no longer applicable. Right now the message we display is
`Press the power button of your reader`
