### ISSUE TITLE
Update Login Email Style

### ISSUE THREAD

**Issue by theck13** [woocommerce/woocommerce-android#479]
### Expected
The login email screen input field label (i.e. Email Address text) and icons (i.e. site address button icon and username button icon) are a consistent style with the rest of the app.  The input field label uses sentence case.  The icons use `wc_grey_dark` (`#3c3c3c`) tint.

### Observed
The login email screen input field label (i.e. Email Address text) and icons (i.e. site address button icon and username button icon) are not a consistent style with the rest of the app.  The input field label uses title case.  The icons use `grey`(`#87a6bc`) tint.

### Reproduced
0. Clear app data.
1. Launch app.
2. Tap ***Log In with Jetpack*** button.
3. Notice input field uses title case.
4. Notice icons use `grey`(`#87a6bc`) tint.

##### Tested
Google Pixel 3 on Android 9.0 with WooCommerce 0.18

**Comment by anitaa1990** [comment]
Fixed via #2286
