### ISSUE TITLE
Refactor OrderDetailResitory into stateless repository

### ISSUE THREAD

**Issue by malinajirka** [woocommerce/woocommerce-android#4806]
The goal of this PR is to make OrderDetail repository stateless. We'll convert all methods which need to store "continuations" into suspendable functions which don't need to store any state. This will make the repository stateless and will remove usages of [deprecated event bus architecture](https://github.com/wordpress-mobile/WordPress-FluxC-Android/wiki/%5BDeprecated%5D-Architecture). 

- [x] FetchSingleOrder (fixed in https://github.com/woocommerce/woocommerce-android/pull/4791)
- [x] newFetchOrderNotesAction (fixed in https://github.com/woocommerce/woocommerce-android/pull/4808)
- [x] newFetchOrderShipmentTrackingsAction (fixed in https://github.com/woocommerce/woocommerce-android/pull/4812)
- [x] newUpdateOrderStatusAction
- [x] newPostOrderNoteAction
- [x] newAddOrderShipmentTrackingAction
- [x] newDeleteOrderShipmentTrackingAction
cc @wzieba @hichamboushaba

**Comment by wzieba** [comment]
Closed in #5013
