### ISSUE TITLE
Update Drawable Resources

### ISSUE THREAD

**Issue by theck13** [woocommerce/woocommerce-android#481]
Update drawable resources throughout the app by doing the following:
- Remove `vectorDrawables.useSupportLibrary = true` from `build.gradle` file
- Rename files to follow naming convention (e.g. [WordPress-Android: drawable naming conventions](https://github.com/wordpress-mobile/WordPress-Android/wiki/Using-Android-Resources))
- Update `app:srcCompat` attribute to `android:src` for all views
- Add `android:tint` attribute to all views with drawable icons
- Consolidate drawable icons with same path and size into single version
- Update all drawable icons to use same fill color (e.g.  `white`)

This helps improve development, minimize drawable resources, and optimize APK size consequently.

**Comment by anitaa1990** [comment]
Some of the issues mentioned here have been completed as part of the Dark mode project and other enhancements are part of the design resource updates project that is currently in discussion. So I will close this issue for now
