### ISSUE TITLE
Tab bar randomly changes background color

### ISSUE THREAD

**Issue by rossanafmenezes** [woocommerce/woocommerce-android#4872]
**To Reproduce**

Open the app 
Move between My Store, Orders, open any order, Products back and forward
Note that sometimes the background color for the tabs bar changes. 

**Screenshots**

![Screen Capture on 2021-09-28 at 13-17-35](https://user-images.githubusercontent.com/30724184/135164297-39eaac78-f830-4948-a43a-b6f87e918d5e.gif)

**Expected behavior**

The color of the Tabs bar should be consistent throughout the app regardless of the screen you are selecting.

**Isolating the problem (mark completed items with an [x]):**
- [ x] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [ x] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [x ] I can reproduce this bug consistently using the steps above.

**Mobile Environment**
Please include:
- Device: Pixel 2 and 3 (physical device ) and 3 and 4 on the emulator
- Android version: 11
- WooCommerce Android version: 7.5 and 7.6-rc-1

**Comment by JorgeMucientes** [comment]
We don't have this tabs anymore in the app's UI. So, this theming issue doesn't apply anymore. Closing.
