### ISSUE TITLE
Bump minimum wcpay plugin version to 3.2.0 for Locations endpoint

### ISSUE THREAD

**Issue by AnirudhBhat** [woocommerce/woocommerce-android#4873]
Why? Because connecting to readers with SDK 2.x requires Locations, and the [Locations endpoint was first available in woocommerce-payments plugin version 3.0.0](https://github.com/Automattic/woocommerce-payments/pull/2830)

- [x] #4875

**Comment by kidinov** [comment]
@AnirudhBhat should we split this into 2 tasks, one goes to the COD project and the second onto the SDK 2.0 one?
