### ISSUE TITLE
Display an in-app notice (where?) for a release or two if a merchant using in-person payments is running a version < 3.0.0 

### ISSUE THREAD

**Issue by AnirudhBhat** [woocommerce/woocommerce-android#4874]
Display an in-app notice (where?) for a release or two if a merchant using in-person payments is running a version < 3.0.0- that notice should warn them that they need to update the plugin or they will lose the ability to collect payments when the app is updated to SDK 2.x

**Comment by allendav** [comment]
Since the number of users potentially impacted by this is very very small, we've elected to close this issue cc @ctarda
