### ISSUE TITLE
Research the case when a reader was attached to a location created by another WC store  

### ISSUE THREAD

**Issue by kidinov** [woocommerce/woocommerce-android#4881]
Is this even possible?

The flow:
* A reader is used by WC store 1
* A reader was sold, gifted to an owner of WC store 2
* Anything should be handled in this case? At the moment we won't even fetch a new location id, but in the next iteration a location management feature will be available and then reattaching will be possible

**Comment by malinajirka** [comment]
The SDK fetches connection token before it start discovery - the location registered with the reader is tied to the connection token which is tied to the account. So if a reader is used with a different account it's considered as not-registered to a location.

**Comment by kidinov** [comment]
@malinajirka Please confirm that I got it right - the card reader object doesn't contain the location id in this case and we just fetch a new location id and the reader is "reatached" ?

**Comment by malinajirka** [comment]
>  the card reader object doesn't contain the location id in this case

That is correct. If you switch back to the original store, the original location id is set on the card reader object.

> and we just fetch a new location id and the reader is "reatached" ?

This part is currently failing with NPE - it seems `wcPayStore.getStoreLocationForSite(selectedSite)` returns null. I plan to look into it now.

**Comment by malinajirka** [comment]
Just to loop back - my store wasn't gated into the beta and it seems WCPay was failing with 500 as the currently released version of the plugin still contains a check for store's eligibility.
