### ISSUE TITLE
[Order Editing] Handle Customer Provided Notes text editing

### ISSUE THREAD

**Issue by ThomazFB** [woocommerce/woocommerce-android#4887]
After #4891 the view dedicated view to present the Customer Provided Notes will exist but no proper text editing handling will be there, to deliver this issue we need to successfully be able to detect text input changes and enable the `Done` button if any modification is detected, the `Done` button should also be able to submit the changes.

Depends on #4891 and needs #4888 to be finished to deliver the entire edit flow, but this issue development can be started without it.

![Android-Edit Note](https://user-images.githubusercontent.com/5920403/135336611-78f2d2f2-7ae2-4126-ae04-710f3d39290a.png)

**Comment by nbradbury** [comment]
Closed via #4940, #4959, and #4975.
