### ISSUE TITLE
[Order Editing] Customer Provided Notes request response feedback

### ISSUE THREAD

**Issue by ThomazFB** [woocommerce/woocommerce-android#4889]
When submitting notes changes to the site we want to display to the user a Snackbar informing if the submission succeeded or not, in order to achieve this we will need to connect the view done in #4887 with the Order Details view with the submission result response.

⚠️ ~We may not need to tackle this task since we'll be performing optimistic updates inside the Order editing operations, so this issue stays open just as a reminder to decide if we want to do add it or not.~ Following @nbradbury statement below the issue description, we'll be implementing the feedback only for failed requests

This issue depends on #4887 to be delivered.

![Android-order-details](https://user-images.githubusercontent.com/5920403/135351054-5a9154fd-bf19-4130-8c1d-e8c8a39fcaf3.png)

**Comment by nbradbury** [comment]
Just noting that on Slack we decided to only show the snack when the update fails, and this is being handled as part of #4975.

**Comment by nbradbury** [comment]
Closed via #4975
