### ISSUE TITLE
[Order Editing] Shipping Address form tracks

### ISSUE THREAD

**Issue by ThomazFB** [woocommerce/woocommerce-android#4899]
Description pending

Depends on #4894

**Comment by shiki** [comment]
@rachelmcr found out that there were a few mismatches in how the Variations Tracks events were implemented on iOS and Android. Let's make sure to test and compare both platforms once the Tracks events are implemented.

**Comment by ThomazFB** [comment]
Thanks for this heads-up, @shiki, I'll keep a close watch on how iOS did each track and replicate it on the Android side 🙇

**Comment by nbradbury** [comment]
@ThomazFB Just a heads up that I discussed some of the order editing tracks events with iOS devs on Slack here: p1634563811100200-slack-C70PAM3RA
