### ISSUE TITLE
Do not register FCM token on app resume

### ISSUE THREAD

**Issue by wzieba** [woocommerce/woocommerce-android#4932]
Currently, we run `FCMRegistrationIntentService#enqueueWork` on every single `AppInitializer#onAppComesFromBackground` which happens on `Activity#onResume`. 

This is probably unwanted behaviour as we flood our backend and influence clients throughput. Also, we started to receive `TOO_MANY_REGISTRATION` error from Firebase.

**Comment by anitaa1990** [comment]
@wzieba 👋 Thank you for logging this issue! Do you have any ideas on how to prevent this unnecessary call from happening? We seem to be storing the FCM token locally in `SharedPreferences`. Perhaps we could check if the token retrieved from Google, matches the token stored locally and only update if the tokens don't match 🤔 ?

**Comment by wzieba** [comment]
👋 My initial idea was to:
- [ ] check *presence* of FCM token in `SharedPreferences` but do this when app starts (not on resume). I think that every time we get token from FCM, we get a new one so comparing it with a locally stored will always result with update. Also it won't fix `TOO_MANY_REGISTRATION` - we'll still experience that
- [ ] place this check for `FCMRegistrationIntentService` and not for `FCMMessageService` - the second one re-generates token when previous token has been compromised.
