### ISSUE TITLE
[Order Editing] Create Country/State filter through search bar

### ISSUE THREAD

**Issue by ThomazFB** [woocommerce/woocommerce-android#4956]
Whenever we're under the Country or State selection, we want to make it possible to filter what's in the list through a search bar and make it easier to find the desired option.

Depends on #4908.

![ios-countrypicker](https://user-images.githubusercontent.com/5920403/136218508-dcb70f70-30d0-4588-9596-6f01a624d665.png)

**Comment by nbradbury** [comment]
Note: I'm using this as a trial project.
