### ISSUE TITLE
[Order Editing] Country & State selection data source

### ISSUE THREAD

**Issue by ThomazFB** [woocommerce/woocommerce-android#4957]
In order to make #4908 and #4909 possible, we need to define a data source where we can fetch Country and the respective State list to properly feed the selection list. This is an investigation issue and it might be closed without further development in case there's already a way to acquire the data inside the Woo app.

Edit: Looks like Shipping Label views already have ways to acquire Country & State data, we should only make sure if this data is always available or only when any Shipping Label feature is activated, if not, we probably must load the data ourselves and make sure we're always up to date.

![ios-countrypicker](https://user-images.githubusercontent.com/5920403/136220071-cf3ad8d7-64b3-485e-9053-214b72e6bead.png)

**Comment by nbradbury** [comment]
I looked into this, and we can use FluxC's [WCDataSource](https://github.com/wordpress-mobile/WordPress-FluxC-Android/blob/5f2fb2f652ec711d17c5b7392c54491b1259f370/plugins/woocommerce/src/main/kotlin/org/wordpress/android/fluxc/store/WCDataStore.kt) to get a list of states and countries.

If we use the same logic as [EditShippingLabelAddressViewModel](https://github.com/woocommerce/woocommerce-android/blob/1b6bd981ec6fb5c99bbe32f8912a98a822bba954/WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/shippinglabels/creation/EditShippingLabelAddressViewModel.kt#L114), we would only update the list of states/countries if they're empty. This is probably a safe approach given how infrequently these lists would change, but we may want to consider re-fetching them after a certain period of time.
