### ISSUE TITLE
Shipping Labels: Incorrect number of items in purchased labels

### ISSUE THREAD

**Issue by itsmeichigo** [woocommerce/woocommerce-android#4961]
**Describe the bug**
The number of items listed in purchased labels seems to be incorrect on Order Details screen.

**To Reproduce**
1. Make sure that your test store has installed and activated WCShip plugin.
2. Create an order with 10 items of the same product.
3. On Orders tab, select the new order and select Create Shipping Label.
4. Configure Ship From and Ship To. 
5. On Package Details screen, move some items to another package.
6. Proceed to complete other fields and purchase the labels.
7. Navigate to Order Details, notice that the number items on both labels is the total items.

**Screenshots**
<img src="https://user-images.githubusercontent.com/5533851/136354249-e4b7f466-998a-4dd1-ab56-e25fe65922bd.png" width=320 /> <img src="https://user-images.githubusercontent.com/5533851/136354265-948deb2a-65c4-4b39-8bce-271b7d282dff.png" width=320 />

**Expected behavior**
The correct number of each item should be displayed correctly.

**Comment by JorgeMucientes** [comment]
The WC shipping label flow is being completely revamped, so I don't think this GH issue applies anymore. 
Feel free to open it again @itsmeichigo if you think differently :)
