### ISSUE TITLE
[Order Editing] Handle empty Editable Order field

### ISSUE THREAD

**Issue by ThomazFB** [woocommerce/woocommerce-android#4973]
Based on feedbacks of iOS implementation here: https://github.com/woocommerce/woocommerce-ios/issues/5112, it was suggested that when we have an empty editable field, like the Customer Provided Notes, we should display a different suggestion of interaction to add info. 

On Android, we currently hide the entire Notes section if the Customer Provided Notes are empty:
https://github.com/woocommerce/woocommerce-android/blob/4d0ebae36d116cb313474df360036ea999decfa3/WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/details/views/OrderDetailCustomerInfoView.kt#L126

 Because of that, we end up having a quite different behavior in comparison to how iOS deals with it, so we should look to do the same and align the experience, not only for the Customer Provided Notes, but also the Shipping and Billing address sections:

![Android-order-details](https://user-images.githubusercontent.com/74938219/137071380-2f4b7bd3-b217-4ec8-bf1d-f79e86b87461.png)

**Comment by ThomazFB** [comment]
@nbradbury after Adam clarification about the expected behavior in this section, I've updated the issue to reflect what's expected based on Figma designs. I'll remove the iOS screenshot and replace it with the Android one after @adamzelinski updates the designs.

**Comment by ghost** [comment]
Thanks for your great work on this @nbradbury @ThomazFB here is the updated Android design
![Android-order-details](https://user-images.githubusercontent.com/74938219/137071380-2f4b7bd3-b217-4ec8-bf1d-f79e86b87461.png)

**Comment by ThomazFB** [comment]
Thank you so much @adamzelinski! 

@nbradbury, just one question, I was thinking about creating a second issue out of this one to tackle the Shipping Details suggestion too, or do you think we should tackle everything at once?

**Comment by nbradbury** [comment]
> I was thinking about creating a second issue out of this one to tackle the Shipping Details suggestion too, or do you think we should tackle everything at once?

Since I added a custom widget in #4997 that simplifies this, I think we can tackle both at once. But I'm fine with two issues as well.

**Comment by ThomazFB** [comment]
@nbradbury nice! Since the PR is still under review and it's not a big one, would you mind adding the support for the Shipping Details too then? I guess it would be simpler this way instead of opening a second issue and another PR

**Comment by nbradbury** [comment]
@ThomazFB It turns out adding shipping & billing address to that PR requires more changes than I would like. If it's okay with you, I'd like to submit a separate PR for address editing.

**Comment by ThomazFB** [comment]
Sure thing @nbradbury! Do you want to keep this issue to track both PRs?
