### ISSUE TITLE
Fix the issue when a reader is not possible to discover when a user comes from WP Web view after missing address error

### ISSUE THREAD

**Issue by kidinov** [woocommerce/woocommerce-android#5009]
https://github.com/woocommerce/woocommerce-android/pull/5001#issue-757279101

1. Remove WC pay address via wp-admin
2. Adjust `CardReaderConnectViewModel::connectToReader:332` to `val cardReaderLocationId = if (cardReader.locationId != null) null else cardReader.locationId` (this way we always fetch a location id from the backend)
3. Try to connect to a reader
4. Notice specific dialog 
1. Tap on Enter site address
2. Press back
3. Tap on "Connect to reader"
4. Notice the reader is never found - when you cancel the discovery and start it again, it works (it seems we don't cancel the discovery when the user leaves the webview)

**Comment by kidinov** [comment]
I spent a few hours trying to figure out what's going on here. Giving up for now. My observations:
1. If you manually cancel the connection dialog then it works
2. Sometimes it works even in the flow described in the ticket and if it does work then it will be working till you restart the app
3. I think this is somehow connected to the GC activity

**Comment by malinajirka** [comment]
Fixed in https://github.com/woocommerce/woocommerce-android/pull/5183
