### ISSUE TITLE
Add analytics tracking for order shipping address

### ISSUE THREAD

**Issue by nbradbury** [woocommerce/woocommerce-android#5062]
In #5017 we added editing the order shipping address, but it's not being tracked. We're currently only tracking `ORDER_EDIT_CUSTOMER_NOTE`.

**Comment by ThomazFB** [comment]
@nbradbury, correct me if I'm wrong, but wouldn't that be a duplicate issue of #4899? 🤔  Also, there's one for the Billing address view too: #4906

**Comment by nbradbury** [comment]
@ThomazFB Bah, you're right - I hadn't noticed the separate issues for tracks. I'll close this.
