### ISSUE TITLE
Order's badge disappears on app restore

### ISSUE THREAD

**Issue by wzieba** [woocommerce/woocommerce-android#5069]
**To Reproduce**
Steps to reproduce the behaviour:
1. Open app
2. Assert you can see badge on the `Orders` bottom navigation icon
3. Go to phone launcher / lock screen
4. Go back to app
5. **Assert there's no badge on the `Orders` bottom navigation icon anymore**

**Screenshots**
https://user-images.githubusercontent.com/5845095/138692584-af93c52e-b907-4f5b-9c54-0c81f1008c2a.mov

**Expected behavior**
Badge should be restored.

**Comment by hichamboushaba** [comment]
This may be linked to the changes done on this PR https://github.com/woocommerce/woocommerce-android/pull/2481
