### ISSUE TITLE
Shipping label state selection shows list of countries

### ISSUE THREAD

**Issue by nbradbury** [woocommerce/woocommerce-android#5074]
If there's no country for a shipping label address, tapping States shows a list of countries.

![label](https://user-images.githubusercontent.com/3903757/138742869-2cc56710-2167-4c9a-8aa0-5dc2b4b1cd84.png)

**Comment by nbradbury** [comment]
See #5118 for a similar problem in order address editing.

**Comment by anitaa1990** [comment]
@hichamboushaba do you know if this is still an issue? I see a similar issue fixed in #4530 but not sure if it's related 😅

**Comment by hichamboushaba** [comment]
I was under the impression this was fixed, but I was actually able to reproduce it 😕, I'll try to work on a fix this week.

**Comment by nbradbury** [comment]
@hichamboushaba Are you still planning to work on this? I can take it if you're busy.

**Comment by hichamboushaba** [comment]
@nbradbury yes, I'm busy with the coupons project, if you can take it it would be awesome, thanks so much 🙏

**Comment by nbradbury** [comment]
Update: the bug is [on the FluxC side](https://github.com/wordpress-mobile/WordPress-FluxC-Android/issues/2393), but in WCAndroid we still need to fix the disabled state of the shipping state. It remains enabled even when a country hasn't been chosen.
