### ISSUE TITLE
Add icons to CardReaderHub screen

### ISSUE THREAD

**Issue by malinajirka** [woocommerce/woocommerce-android#5086]
Add icons to rows on the Card Reader Hub screen
<img width="250" alt="Screen Shot 2021-10-27 at 2 27 14 pm" src="https://user-images.githubusercontent.com/2261188/139010528-bcde2e34-a547-4ca5-9aa8-21d401c23048.png">

**Comment by AnirudhBhat** [comment]
It looks better now with the icons! Thank you for creating the issue @jirka However, I was wondering now that we have two card reader manual options (BBPOS chipper and Stripe M2), adding the same manual icon to both of those might look a bit off? Attached is a screenshot for reference.
@adamzelinski WDYT?

<img src="https://user-images.githubusercontent.com/1331230/139011296-596376df-37b5-4288-a9c5-fe2a4548ab7d.png" width="250px" />

**Comment by ghost** [comment]
@AnirudhBhat I'm happy to use the same icon for both manual options thanks.
