### ISSUE TITLE
In-Person Payments Accessibility check

### ISSUE THREAD

**Issue by AnirudhBhat** [woocommerce/woocommerce-android#5088]
We have done zero intentional work in terms of accessibility.

Scope

1. Testing the new UI related to Payments (settings, order details, and modals) with TalkBack
2. Log the issues that we find so that we can start getting them into our regular sprint work

Issues
- [x] #5133
- [x] #5153
- [x] #5154
- [x] #5155
- [x] #5171
- [x] #5172

**Comment by AnirudhBhat** [comment]
- [ ] Announce the different payment states that the merchant goes through while collecting payment (Initiated, capturing, processing..etc)

**Comment by anitaa1990** [comment]
Closing this issue since it looks like all the issues addressed in the description is completed 😄
