### ISSUE TITLE
Handle wrong ZIP code used

### ISSUE THREAD

**Issue by kidinov** [woocommerce/woocommerce-android#5131]
The backend returns 500 with some error data in case if ZIP doesn't match the country. We need to handle it properly and explain to a user why this happens.

To reproduce:
* On the web open payments -> settings
* Enter any US address using wrong (NON US) Zip code
* Try to connect to a reader which doesn't have a location id attached

- [x] #5174
```
{
	"error": "postal_code_invalid",
	"message": "Error: Invalid US postal code"
}
```

- [x] #5175

**Comment by anitaa1990** [comment]
Closing this issue since it looks like the two issues mentioned is fixed 🎉
