### ISSUE TITLE
The readers manual can not be open on android 12. Instead, we download a PDF file

### ISSUE THREAD

**Issue by kidinov** [woocommerce/woocommerce-android#5134]

**Comment by kidinov** [comment]
I tried the workaround with opening the pdf in google docs and it works... sometimes
You need to refresh the page several times. Some weird caching is going on somewhere
I also noticed that other apps also stopped opening PDF files in chrome, instead if downloads it. Not sure if this is bug or a feature of android 12, but probably better to leave it as it is, because it's better clear to show that the manual was downloaded instead of sometimes show empty screen with google doc page

**Comment by kidinov** [comment]
```
    /**
     * Starting Android 12 Chrome doesn't open PDF files, but downloads it
     * This is a workaround for this case
     */
    fun launchUrlWithPdfFile(context: Context, url: String) {
        if (android.os.Build.VERSION.SDK_INT >= android.os.Build.VERSION_CODES.R) {
            launchUrl(context, "https://docs.google.com/gview?url=$url")
            disconnect(context)
        } else {
            launchUrl(context, url)
        }
    }
```

**Comment by malinajirka** [comment]
Note: It seems the change is related to an update of Chrome, I'm seeing the same behavior on Android 11.

**Comment by malinajirka** [comment]
This seems like an intentional change in Chrome not our app => closing.
