### ISSUE TITLE
Jetpack CP: add Jetpack installation entry to the app's settings

### ISSUE THREAD

**Issue by hichamboushaba** [woocommerce/woocommerce-android#5185]
Add an entry that allows accessing the Jetpack installation screen from the application's settings:

<img width="248" alt="Screen Shot 2021-11-08 at 12 33 09" src="https://user-images.githubusercontent.com/1657201/140734912-fa0bf383-9cd4-47db-8dce-bc070507dd94.png">

We need to check the user's role before displaying this, it should be displayed only to admin users.

**Comment by hichamboushaba** [comment]
@hafizrahman just a reminder about this small task 🙂

**Comment by anitaa1990** [comment]
Closed via #5656
