### ISSUE TITLE
Card Reader gets stuck when a payment is canceled

### ISSUE THREAD

**Issue by malinajirka** [woocommerce/woocommerce-android#5265]
**Describe the bug**
When I press back button right after the card reader reads my card the reader gets into a weird state - I can't collect any other payments and I can't even disconnect from the reader.

**To Reproduce**
1. Go to  order detail screen
2. Click on collect payment
3. Wait until the reader is ready to collect payment
4. Tap a card and press back right after the reader reads the card/beeps
5. Try to collect payment again and notice the UI is stuck on "Connecting to reader"

**Screenshots**

https://user-images.githubusercontent.com/2261188/142418518-28ab51e0-7e23-40c0-9bb8-ae10248f1c17.mp4

**Expected behavior**
I'd expect the reader to cancel the payment and continue working without issues

P.S. Tested with both Chipper 2X and M2 readers

**Comment by malinajirka** [comment]
This seems like a bug in the SDK, I was able to reproduce it in the official example app - reported [an issue here](https://github.com/stripe/stripe-terminal-android/issues/181).

**Comment by kidinov** [comment]
@malinajirka It's been fixed in 2.5.2 👏 I can not reproduce this anymore
