### ISSUE TITLE
[Order Creation] Create `Add a different shipping address` toggle

### ISSUE THREAD

**Issue by ThomazFB** [woocommerce/woocommerce-android#5289]
When editing the Billing address of the Order customer, we may want to define a specific Shipping Address. To achieve this we want to define a toggle that expands the Shipping Address form when activated.

Depends on #5288

<img width="388" alt="Screen Shot 2021-11-11 at 22 14 44" src="https://user-images.githubusercontent.com/5920403/142572667-f8764ba5-619d-4ea2-99a6-b9de0116f627.png">

**Comment by wzieba** [comment]
In scope of this issue, I'm moving handling state of the input fields from `view` to `viewmodel`.
