### ISSUE TITLE
[Order Creation] Edit Customer information with summary view

### ISSUE THREAD

**Issue by ThomazFB** [woocommerce/woocommerce-android#5290]
After the Customer address data is submitted, we should be able to edit the information whenever needed, to achieve we want to create an `Edit` button inside the Customer section and display the Customer information summary to allow specific data modification

Please note that these designs are iOS-based, so there's a good chance this summary UI can be substantially different from what it's detailed here. We should discuss this further.

Depends on #5288 

![image](https://user-images.githubusercontent.com/5920403/142573449-eae62b3b-ff3d-4474-8673-9cd5ea33db1c.png)

**Comment by rachelmcr** [comment]
A couple details about the summary screen were raised in Slack (p1640849649018800-slack-C02KUCFCSFP):

1. How to display empty data: If the user clears all fields for one of the addresses, we can display placeholder text instead. The suggested placeholders are `Guest` in the Contact section and `No address specified.` in the address sections.
2. There should be additional confirmation when "Remove customer" is tapped.
