### ISSUE TITLE
Update location and Bluetooth permissions handling.

### ISSUE THREAD

**Issue by hichamboushaba** [woocommerce/woocommerce-android#5297]
The handling of bluetooth permissions is different for apps that are targeting Android 12, it [requires](https://developer.android.com/guide/topics/connectivity/bluetooth/permissions#declare-android12-or-higher) handling new runtime permissions now.

But even though this shouldn't impact the apps that don't target Android 12, the app crashes now when using an Android 12 device (check https://github.com/woocommerce/woocommerce-android/issues/5267#issuecomment-974652157).

**Comment by malinajirka** [comment]
cc @kidinov since I believe you are working on IPP support for Android 12.

**Comment by kidinov** [comment]
Yep, [that](https://github.com/woocommerce/woocommerce-android/issues/5267#issuecomment-974652157) ticket is pretty much about that

**Comment by hichamboushaba** [comment]
I already started working on updating the permissions' handling in https://github.com/woocommerce/woocommerce-android/pull/5298, but if you are actively working on it I can close the PR, and assign the ticket to you @kidinov 🙂
