### ISSUE TITLE
Display selected filter date range in the order list

### ISSUE THREAD

**Issue by JorgeMucientes** [woocommerce/woocommerce-android#5313]
When a custom date range is selected we should display the selected range in the order list: 

![Screenshot 2021-11-23 at 09 13 52](https://user-images.githubusercontent.com/2663464/142989924-5c35e3f6-5a8d-46e4-a2f1-d9420be97105.png)

**Comment by anitaa1990** [comment]
@JorgeMucientes one thing to keep in mind when working on this is also to add release notes under 8.1 so merchants using the app know this feature is released 😄  (I always forget that part!)

**Comment by JorgeMucientes** [comment]
Closing this issue. After talking it with @adamzelinski we are going to leave the behavior as it is now: 
 - Display different date range row headers depending on how old the following orders are. Like in this video: 

https://user-images.githubusercontent.com/2663464/144083726-ccc3ed00-86cd-41c3-bc45-6ea5b39a9c0b.mp4
