### ISSUE TITLE
Order Filters: add custom statuses

### ISSUE THREAD

**Issue by pmusolino** [woocommerce/woocommerce-android#5321]
@jaclync suggested to implement a way to filter orders also by custom statuses. 

We are already [fetching statuses](https://github.com/woocommerce/woocommerce-android/blob/501a4af7eb5d3d756c113065889c81df627a84a3/WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/filters/domain/GetOrderStatusFilterOptions.kt#L14-L33) from the API, but once they are cached, we are not updating them anymore. So this task will consist on applying some kind of expiry policy so that order statuses options are fetched every now and then from the API a therefore custom order statuses refreshed. 

iOS issue: https://github.com/woocommerce/woocommerce-ios/issues/5498

**Comment by JorgeMucientes** [comment]
Something to keep in mind when working in on this is to check what happens when a custom status is deleted and there are existing orders associated to the deleted status

**Comment by JorgeMucientes** [comment]
To be aware of before implementing this: p91TBi-6Nv-p2

**Comment by hichamboushaba** [comment]
@JorgeMucientes I think this one should be fixed now that we are fetching the statuses on each launch of the order list https://github.com/woocommerce/woocommerce-android/pull/5493, WDYT?

**Comment by JorgeMucientes** [comment]
Yes! that is right! Custom order status filters are supported already on Android. Closing this issue.
