### ISSUE TITLE
Order Filters: show the order statuses instead of a number in the initial screen

### ISSUE THREAD

**Issue by pmusolino** [woocommerce/woocommerce-android#5322]
Maybe we can show the order statuses instead of a number in the initial filters screen? It feels a bit odd seeing "2" here.

<img src="https://user-images.githubusercontent.com/1945542/142959916-1ae05d00-9c6b-4d6f-ba6b-84ce78238eb2.png" width="300" />

Related iOS issue: https://github.com/woocommerce/woocommerce-ios/issues/5499

**Comment by backwardstruck** [comment]
Looks like the related iOS [issue](https://github.com/woocommerce/woocommerce-ios/issues/5499#issuecomment-1240211459) was closed as "won't fix" so I don't think it makes sense to only change Android. Feel free to reopen if we think both platforms should make this change.
