### ISSUE TITLE
Simple Payments: Consider showing the keyboard right away

### ISSUE THREAD

**Issue by shiki** [woocommerce/woocommerce-android#5344]
When the Take Payment screen is shown, the keyboard is not shown right away. We tried to do this before but faced some challenges. 

From @nbradbury 

> On some screens the keyboard overlays the Done button, which looks really odd when the screen appears.

We can look into this again in the future. 

<img src="https://user-images.githubusercontent.com/198826/143311434-138d4a7f-2af3-49a6-b254-15ef782a9cb4.png" width="300">

**Comment by nbradbury** [comment]
Closed via #5372.
