### ISSUE TITLE
Replace ProgressDialogs with a better UX

### ISSUE THREAD

**Issue by aforcier** [woocommerce/woocommerce-android#537]
In several parts of the app, we're using the now-deprecated `ProgressDialog` to block the UI while a time-consuming action happens:

![device-2018-11-30-165513](https://user-images.githubusercontent.com/9613966/49316997-ce7d0c80-f4c0-11e8-878f-b66222e5754d.png)

 This is mainly used in the login library, but we're also using it in the main app for login-related things: the `MainActivity` displays one when handling fetching user data after login via magic link, and https://github.com/woocommerce/woocommerce-android/pull/535 introduced one to the login epilogue while the supported version is check for each WooCommerce site.

The UI-blocking of `ProgressDialog` is not a great user experience (this is why it's deprecated), and we should look at replacing it with friendlier UX. We can use a progress bar, or adapt our loading skeletons for the purpose.

**Comment by rossanafmenezes** [comment]
Closing this since the whole login flow was replaced a while ago.
