### ISSUE TITLE
Reviews: New reviews retain unread decoration in list after marking all as read, until next refresh

### ISSUE THREAD

**Issue by rachelmcr** [woocommerce/woocommerce-android#5385]
**Describe the bug**

When I view the Reviews tab, unread reviews are marked with a purple decoration on the left side of the review. Tapping the "mark all as read" checkmark marks them all as read, but the decoration remains until I refresh the screen (e.g. with a pull to refresh).

cc @0nko - not sure if this is related to the changes in https://github.com/woocommerce/woocommerce-android/pull/5349.

**To Reproduce**
1. Create a new review on your store.
2. Open the Reviews tab in the app.
3. Tap the checkmark in the top right.
4. Notice there is a toast message confirming all reviews were marked as read, but the purple decoration remains on the new review.
5. Pull to refresh. Notice the purple decoration disappears.

**Screenshots**

<img src="https://user-images.githubusercontent.com/8658164/144243701-7250a338-b0b9-4cd2-8232-cad1c63f9f2b.png" width="300px">

**Mobile Environment**
Please include:
- Device: moto e5 play
- Android version: 8.1.0
- WooCommerce Android version: 8.1-rc-1

**Comment by anitaa1990** [comment]
I tested this in the latest version (v8.8) and it looks like it was fixed during the home screen update and review list changes. Will close this issue 🎉
