### ISSUE TITLE
Simple Payments: The amount gets cut off when it's larger than 5 digits

### ISSUE THREAD

**Issue by shiki** [woocommerce/woocommerce-android#5394]
Reported p1638451166068900-slack-C70PAM3RA

https://user-images.githubusercontent.com/198826/144452733-8bb4c806-50a9-4ac2-9d55-122974588cec.mp4

**Comment by shiki** [comment]
@malinajirka Do you have a suggestion on how this should be fixed? 

I'm now thinking that it may not be important. I wouldn't expect more than 10,000 to be entered in Simple Payments. 

How about you, @Ecarrion? Any suggestions? I see that the iOS's amount also gets cut off eventually. Though, in a much better position than Android. 

iOS: 

<img src="https://user-images.githubusercontent.com/198826/145079363-a656be16-7b3c-4a03-a3f2-789ae0aadbb8.png" width="300">

**Comment by Ecarrion** [comment]
> @malinajirka Do you have a suggestion on how this should be fixed?
> 
> I'm now thinking that it may not be important. I wouldn't expect more than 10,000 to be entered in Simple Payments.
> 
> How about you, @Ecarrion? Any suggestions? I see that the iOS's amount also gets cut off eventually. Though, in a much better position than Android.
> 
> iOS:
> 
> <img alt="" width="300" src="https://user-images.githubusercontent.com/198826/145079363-a656be16-7b3c-4a03-a3f2-789ae0aadbb8.png">

Hey @shiki, I just spent 30 minutes trying to auto-shrink the font instead of overflowing the screen but `SwiftUI` wasn't playing nice with that idea 🙃 

I could be smarter and set a custom fon based on the number of characters the user has entered but maybe is not worth it right now!

**Comment by malinajirka** [comment]
> Do you have a suggestion on how this should be fixed?

It's a shame autosizing is not supported on EditTextView only on TextView 🤷. 

> I'm now thinking that it may not be important. I wouldn't expect more than 10,000 to be entered in Simple Payments.

I agree, as long as we support only USD I think we are fine. I'd maybe consider changing the font size from `text_major_150` to `text_major_100`. It imho still looks good and we could fit $999 999 which would be enough even for a lot of different currencies.

<img width="250" alt="Screenshot 2021-12-08 at 8 36 59" src="https://user-images.githubusercontent.com/2261188/145167701-7667d3d8-7e8b-402d-82b2-8b4a92e5f4da.png">
