### ISSUE TITLE
Orders Badge Count does not show

### ISSUE THREAD

**Issue by minitaq** [woocommerce/woocommerce-android#5411]
Orders Badge Count does not show in the android app.

However, when rotating the screen, then it shows the badge count.

[minitaq](https://minitaq.com)

**Comment by hichamboushaba** [comment]
@minitaq can you please give more details about the bug? what's the version of the app on your device?

We are tracking a related issue #5069, but the steps to reproduce it are different than what you described.

**Comment by anitaa1990** [comment]
This could be fixed in #5069 . @minitaq can you confirm please?

**Comment by hichamboushaba** [comment]
Closing as the cause was fixed in the above PR.
