### ISSUE TITLE
[Order Creation] Display list of current customers

### ISSUE THREAD

**Issue by wzieba** [woocommerce/woocommerce-android#5444]
### Not milestone 1!

As stated in https://github.com/woocommerce/woocommerce-ios/issues/5412 and https://github.com/woocommerce/woocommerce-android/issues/5288

> When the Add Customer button is tapped, it opens a form to enter the customer details. For milestone 1, we will only create orders for guest customers (with no UI to select existing customers).

### Description

We should display selectable list of currently available customers.

<img src=https://user-images.githubusercontent.com/5845095/145803584-4de988ed-b7ab-43a4-9dba-aedfdfd64054.png width=300>

**Comment by wzieba** [comment]
I see that `CustomerSqlUtils` is used only in `WCCustomerStore` which is not used anywhere in WooCommerce codebase. It might be a good moment, if time allows, to migrate `WCCustomerModel` from WellSql into Room.

**Comment by shiki** [comment]
Let's not work on this yet since there's a big chance that we won't allow customer selection. 🙂

**Comment by shiki** [comment]
@wzieba I'm just going to close this since we're not doing this. 😁 It's better to have the board clean.
