### ISSUE TITLE
Inform users with A8c associated mail that Zendesk messages won't work for them

### ISSUE THREAD

**Issue by wzieba** [woocommerce/woocommerce-android#5464]
### Description

If using A8c mail Zendesk won't send any messages to support, causing confusion if someone doesn't know that mail is the blocker.

Citing @rachelmcr :
> In iOS we do have an alert that pops up if you’re using an a8c email address. (...)

See discussion for details: p1638890438054400-slack-C6H8C3G23

<img src=https://user-images.githubusercontent.com/5845095/146201302-31df8c5c-1321-4cdd-919f-acfbbce0325a.png width=300>

**Comment by rachelmcr** [comment]
Here's how it's done in iOS, for reference: We do [a simple check for an a8c email address](https://github.com/woocommerce/woocommerce-ios/blob/4fe952211777fad134084cbc19d4db229a37c8c9/WooCommerce/Classes/Tools/Developer/DeveloperEmailChecker.swift) and [display an alert](https://github.com/woocommerce/woocommerce-ios/blob/b2a9ad51300819d8c00cce60983ee3804c50a64a/WooCommerce/Classes/ViewRelated/Dashboard/Settings/Help/HelpAndSupportViewController.swift#L169-L184) if the account email is an a8c email address.

**Comment by wzieba** [comment]
Thanks!
