### ISSUE TITLE
[Card Present Payments] Pass reader model to backend when creating PaymentIntent

### ISSUE THREAD

**Issue by ctarda** [woocommerce/woocommerce-android#5483]
For context: pbUcTB-r9-p2#comment-2153

Pass the reader model in the metadata when creating a payment intent.

See also https://github.com/woocommerce/woocommerce-ios/issues/5706

**Comment by kidinov** [comment]
[iOS PR ](https://github.com/woocommerce/woocommerce-ios/pull/5750) and [iOS PR 2](https://github.com/woocommerce/woocommerce-ios/pull/5707)
