### ISSUE TITLE
[Coupons] Display list of active/expired coupons for a store

### ISSUE THREAD

**Issue by anitaa1990** [woocommerce/woocommerce-android#5527]
We want to display list of coupons for a store in two separate tabs: Active & Expired.
- [x] Create repository class + unit tests.
- [ ] Create use case class + unit tests.
- [x] Create ViewModels + unit tests.
- [x] Add UI - list for the active/expired coupons. #6059
- [ ] Error Snackbar if there is an error when fetching coupons. 
- [x] Add feedback area #6067 

<img width="520" alt="Screen Shot 2022-03-18 at 15 11 57" src="https://user-images.githubusercontent.com/266376/158962498-0fef414b-c434-480c-b1bb-1a8d12f19647.png">

**Comment by hafizrahman** [comment]
I updated the main post with the latest iteration of the designs and modified the task list as well.
