### ISSUE TITLE
[Coupons] Add an empty view if there are no coupons for a store

### ISSUE THREAD

**Issue by anitaa1990** [woocommerce/woocommerce-android#5528]
I want to view an empty screen if there are no coupons available for a store.

- [x] M1 version #6066
- [ ] M2 version

<img width="271" alt="Screen Shot 2022-03-18 at 15 17 57" src="https://user-images.githubusercontent.com/266376/158962748-988e7853-e084-41a1-8acb-ad0f9c7d1b39.png">

**Comment by hafizrahman** [comment]
I updated the design with the latest iteration.
