### ISSUE TITLE
[Coupons] Add the performance section for a coupon

### ISSUE THREAD

**Issue by anitaa1990** [woocommerce/woocommerce-android#5530]
I want to view the performance section, including the order count that used this coupon.

- [x] UI Design #6100
- [x] Functionality #6181 

<img width="244" alt="Screenshot 2021-12-27 at 11 16 03 AM" src="https://user-images.githubusercontent.com/22608780/147438627-c1e4870e-8507-47ef-a8e9-36df8735765a.png">

Updated design:

<img src="https://user-images.githubusercontent.com/266376/160364218-0ff56766-8ef0-4efd-8b62-85a53457eeff.png" width="35%">

**Comment by hafizrahman** [comment]
Added updated design.
