### ISSUE TITLE
[Coupons] Restrictions: Add screen for viewing/editing usages restriction for a coupon

### ISSUE THREAD

**Issue by anitaa1990** [woocommerce/woocommerce-android#5532]
I want to view and edit the usage restrictions of the coupon, including the exclusions and usage limits.

![Create Coupon - Usage Restrictions](https://user-images.githubusercontent.com/266376/168190538-6102f129-7286-42d4-8278-65b4a60f8a33.png)

**Comment by hichamboushaba** [comment]
After updating tickets, this seems like a duplicate of #5532

**Comment by hafizrahman** [comment]
Updated original post with the latest design.
