### ISSUE TITLE
[Coupons] Add option to share/copy a coupon

### ISSUE THREAD

**Issue by anitaa1990** [woocommerce/woocommerce-android#5533]
I want to be able to share the coupon.
I want to be able to copy the coupon code.

<img width="245" alt="Screenshot 2021-12-27 at 11 33 44 AM" src="https://user-images.githubusercontent.com/22608780/147439785-4483fa6f-effd-4a92-892a-3d48393a3208.png">

Updated design (second and third screen specifically):

<img width="608" alt="screenshot_2022-03-23_at_10 36 04_am" src="https://user-images.githubusercontent.com/266376/160381828-9ee81060-f9b3-4c05-93ce-35fc04af1d90.png">

**Comment by hafizrahman** [comment]
Added the updated design to the main post.

**Comment by hafizrahman** [comment]
Done in #6175
