### ISSUE TITLE
[Coupons] Restrictions: Add options to change the usage restrictions for a coupon

### ISSUE THREAD

**Issue by anitaa1990** [woocommerce/woocommerce-android#5539]
- I want to change minimum spend and maximum spend of a coupon.
- I want to change the usage limit per coupon.
- I want to be able to limit usage to X items.

![Screen Shot 2022-05-19 at 10 20 40](https://user-images.githubusercontent.com/266376/169197346-3f55b3e7-9302-4bf3-9ab4-5c2d64dbaeed.png)

**Comment by hafizrahman** [comment]
Updated original post with latest design.
