### ISSUE TITLE
[Coupons] Add option to include products for a coupon.

### ISSUE THREAD

**Issue by anitaa1990** [woocommerce/woocommerce-android#5541]
I want to be able to include products for a coupon.

<img width="360" alt="Screen Shot 2022-04-25 at 17 17 16" src="https://user-images.githubusercontent.com/1657201/165140196-5677361b-bf6c-42cb-b39d-7404be177b1b.png">

**Comment by 0nko** [comment]
Seems like a duplicate of #5537.
