### ISSUE TITLE
[Coupons] Add option set coupon for individual use only

### ISSUE THREAD

**Issue by anitaa1990** [woocommerce/woocommerce-android#5543]
- I want to be able to set a coupon for individual use only

<img width="203" alt="Screen Shot 2022-05-20 at 11 44 28 AM" src="https://user-images.githubusercontent.com/1657201/169512269-47e85484-2fbf-4baa-a1a8-31026e6bc9ff.png">

**Comment by hichamboushaba** [comment]
After updating tickets, this is a duplicate of #5532
