### ISSUE TITLE
Convert bar chart to line chart

### ISSUE THREAD

**Issue by JorgeMucientes** [woocommerce/woocommerce-android#5555]
We currently display a bar chart in the home screen tab, this chart should be updated to new design using a line chart: 
![Screenshot 2021-12-27 at 10 12 08](https://user-images.githubusercontent.com/2663464/147455985-e47f7807-db5f-47db-9a7d-06bf27b6fcea.png)

Main changes to be applied: 
- Convert the chart view from bar chart to line chart
- Disable circles for data points in the line chart (enabled by default, where each data point has a circle drawn)
- Update the color and width of the data line and highlighted line
- Create a MarkerImage subclass for the circle marker shown when highlighting a data point (the pink circle in the screenshots above)
- Add a gradient to the line chart

Current spike can be used to start with: https://github.com/woocommerce/woocommerce-android/compare/spike/home-screen-charts

**Comment by wzieba** [comment]
Thanks @JorgeMucientes for working on this! Do you think that in scope of this issue you could also close https://github.com/woocommerce/woocommerce-android/pull/5189 ? Maybe it's not a lot of effort and this bump keeps blocking new updates.
