### ISSUE TITLE
[Order Creation] Payment Section with product and order totals

### ISSUE THREAD

**Issue by rachelmcr** [woocommerce/woocommerce-android#5595]
For milestone 1, we want to display a basic, read-only Payment section (no buttons to add payment details). This should appear after at least one product is added to the order, and should include the Products Total and Order Total.

If it doesn't cost much to do, we should also include this info text below the order total to explain that taxes will be added to the order total:

> Total excluding taxes. Taxes will be automatically calculated based on your store settings.

We can remove that text once taxes are supported in order creation.

Ref: p91TBi-6xc-p2#comment-7236 / p1641317781008900-slack-C02KUCFCSFP

Design | iOS implementation
-|-
<img src="https://user-images.githubusercontent.com/8658164/141468799-3a3fb88d-8b7c-4457-a278-7e73d1b59453.png" width="300px">|<img src="https://user-images.githubusercontent.com/8658164/148221711-0a6b004f-a981-4a16-8b9f-936fe4fb2dd0.png" width="300px">

**Comment by ThomazFB** [comment]
Thanks for creating this task, @rachelmcr 👍
