### ISSUE TITLE
Implement the notification badge in the Hub Menu and inside the hub menu cell in case there is a new notification

### ISSUE THREAD

**Issue by JorgeMucientes** [woocommerce/woocommerce-android#5631]
The Hub menu tab will show: 

- A badge with no number on the tab itself 
- A numbered badge for each of the items in the hub menu that have unread/pending notifications

Designs TTSzMdVvx5A00PsElOc9tI-fi-422%3A51547: 
![Screenshot 2022-01-13 at 09 01 06](https://user-images.githubusercontent.com/2663464/149289817-c00c77e7-5d09-4bef-a1a0-a75f07da2a4d.png)

**Comment by wzieba** [comment]
👋 Related issue (bug in current implementation) is: #5069 . cc: @hichamboushaba as I briefly mentioned this task internally.

Btw a small nitpick, @JorgeMucientes do you have Tampermonkey setup? It makes internal communication links easily clickable right away on Github. I'll link to the conversation that I think you linked above: p1641219365007800-slack-C02N7N92DEV

**Comment by JorgeMucientes** [comment]
Thanks for checking this out @wzieba. I just copied pasted the text from an iOS issue, and I'm not sure Paolo is using TamperMonkey. I am using it (super useful tool 🙂 ) 

Anyway I've updated the info for this issue as well as for the [iOS one](https://github.com/woocommerce/woocommerce-ios/issues/5874) With new information and removing the Slack discussion reference.

**Comment by wzieba** [comment]
Thanks! 

Yeah, TamperMonkey is very cool 😃 , so small yet improving daily experience by a lot !
