### ISSUE TITLE
Improvements to the CI Dependency Tree Diff step 

### ISSUE THREAD

**Issue by kidinov** [woocommerce/woocommerce-android#5639]
* As for the standalone .jar usage - it's outside of the Gradle toolchain, so I have our typical concerns about using including a binary in our repo. Since it's in the CI process, maybe we can consider downloading it from the source instead.
* if it's easy to do, run this only if PR contains changes in *.gradle file. I can't see the possibility for dependencies to be changed by editing any other type of file.
* It would be good if we can merge trunk into the PR's branch before running the CI task, to allow having a more robust check

**Comment by wzieba** [comment]
Adding a new improvement:

- step fails always on merge commit with:
```
./tools/dependency-tree-diff/dependency-tree-diff.sh: line 9: CIRCLE_PULL_REQUEST: unbound variable
```
