### ISSUE TITLE
[Mobile Payments] Research a bit about how refunds work today in the app

### ISSUE THREAD

**Issue by AnirudhBhat** [woocommerce/woocommerce-android#5704]
Understand how refunds work in the WooCommerce Android app

**Comment by anitaa1990** [comment]
@AnirudhBhat, is this issue completed? It's marked as done in the Moose of the Loose project 😅

**Comment by AnirudhBhat** [comment]
@anitaa1990 Yes! Thanks for reminding me! I'll close this issue.
