### ISSUE TITLE
[Mobile Payments] Skip the capture step for Interac payments

### ISSUE THREAD

**Issue by AnirudhBhat** [woocommerce/woocommerce-android#5708]
Interac payments are authorized and captured in a single step:

Unlike Visa, Mastercard, and American Express transactions, Interac transactions are authorized and automatically captured in a single step. Your application shouldn’t continue to capture the PaymentIntent – if you attempt to capture an interac_present payment, the Stripe API returns an error. Be careful to prevent unintended and duplicate payments in your integration; if failures or declines occur while processing Interac, you can attempt to re-use the same PaymentIntent from the original transaction to safeguard against double-charging.

The app should still notify the store about the successful charge in a way that doesn't attempt to capture the charge a second time.

**Comment by malinajirka** [comment]
Just a note: [I think the current implementation will skip the capture step automatically](https://github.com/woocommerce/woocommerce-android/blob/1f19597206df69ca379f321ce43c5b37d6f264f5/libs/cardreader/src/main/java/com/woocommerce/android/cardreader/internal/payments/PaymentManager.kt#L82). However, it won't inform the store about a successful charge.
