### ISSUE TITLE
[Mobile Payments] Adding the purchase link for WisePad 3

### ISSUE THREAD

**Issue by AnirudhBhat** [woocommerce/woocommerce-android#5710]
For stores in Canada, we need a link to order a WisePad 3 from In-Person Payments settings.

We'll have to confirm the exact woocommerce.com product URL to show

**Comment by malinajirka** [comment]
Just a note that we added a different purchase reader link when Stripe extension is installed in https://github.com/woocommerce/woocommerce-android/pull/5892. We'll need to somehow handle this even after the release of support for IPP in Canada.
