### ISSUE TITLE
(WPLoginFlow) Already managing a GoogleApiClient

### ISSUE THREAD

**Issue by jkmassel** [woocommerce/woocommerce-android#574]
This one comes from Fabric: http://crashes.to/s/6efb6866862

The same issue is over in WPAndroid (http://crashes.to/s/aab765a1feb), so there's a good chance the fix for this belongs in https://github.com/wordpress-mobile/WordPress-Login-Flow-Android.

**Relevant bits:**

```
Fatal Exception: java.lang.IllegalStateException: Already managing a GoogleApiClient with id 100
[...]
at org.wordpress.android.login.LoginEmailFragment.onCreate(LoginEmailFragment.java:249)
```

Looks like we try to initialize the Google client more than once. Possibly something where a user went back to this screen, so the code ran again?

**Comment by nbradbury** [comment]
Possible fix: https://stackoverflow.com/a/37025744/1673548

**Comment by nbradbury** [comment]
This is a bug in `WordPress-Login-Flow-Android`. I'm closing this issue here and have filed [this issue](https://github.com/wordpress-mobile/WordPress-Login-Flow-Android/issues/7) in that repo.
