### ISSUE TITLE
[Order Creation] Products are doubled after order is Created

### ISSUE THREAD

**Issue by thehenrybyrd** [woocommerce/woocommerce-android#5742]
**Describe the bug**
After creating an order, I notice the new order has twice as many products as I expected, and the price is adjusted accordingly. 
Initially, I assumed this might be something weird with my test store (and it still might be), so I tested on 3 different stores. I tested with multiple different products, with multiple of the same product, and with both simple and variable products. Each time, the whole order is doubled.

**To Reproduce**
1.  In Orders, tap "+" and select "Create Order" (if both Simple Payments and Order Creation are selected in Beta features).
2. Add a product, or multiple. Note how many products you added, and the total price.
3. Add customer details (they can be totally fake, but should imitate a US address)
4. Tap "Create" to create the order.
5. The Single Order screen loads. Note the product is listed twice. Note the total is also doubled.

**Screenshots**
Here's an example, see the product list before and after Creating the order.
<img src="https://user-images.githubusercontent.com/15107387/151771561-70522a3d-2b42-41bb-9ed7-ea020346dc20.png" width="75%">

**Expected behavior**
I expected to see the exact number of items I initially added.

**Isolating the problem (mark completed items with an [x]):**
- [ ] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [x] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [x] I can reproduce this bug consistently using the steps above.

**Mobile Environment**
- Device: Nokia 2
- Android version: 11
- WooCommerce Android version: trunk-build-61695 (273)

**Tested on Pressable w/Jetpack and on a WordPress.com Atomic site.**

**Comment by shiki** [comment]
I can confirm that when I turned off the M2 flag, I could not reproduce this issue anymore. So this shouldn't block M1. 

cc @ThomazFB @hichamboushaba
