### ISSUE TITLE
Fix screenshot tests before merging more menu feature branch

### ISSUE THREAD

**Issue by JorgeMucientes** [woocommerce/woocommerce-android#5764]
### Description
We've recently added a new screen to the app: More Menu. This has several implications over the app navigation that break the screenshots and UI tests:

- This screen is a new tab in the bottom nav bar that replaces ReviewListScreen tab.
- Settings screen is now accessed from MoreMenuScreen instead of MyStoreScreen
- New MoreMenuScreen uses Android Jetpack Compose to display the UI. This means we need a new composeTestRule inside Espresso tests to be able to "click" or "match" UI components.

**Comment by anitaa1990** [comment]
Closed via #5795
