### ISSUE TITLE
[Order Creation] Display selected variation attributes

### ISSUE THREAD

**Issue by ThomazFB** [woocommerce/woocommerce-android#5766]
When adding a variation, the attributes are not displayed in the Order creation form products list. This can be a problem for our merchants since hiding the Attributes from the Variation leaves no space for identifying which variation was selected for the order.

Order Creation (Missing Attributes) | Order Details (Correct)
--------|-------
![IMG_8744](https://user-images.githubusercontent.com/198826/151844450-a863ec10-5608-4269-8548-c25ed615654e.PNG)        |      ![image](https://user-images.githubusercontent.com/198826/151844599-a5dae2b5-e60f-4bab-a1cf-ba6a001a4389.png)

---

iOS: https://github.com/woocommerce/woocommerce-ios/issues/6031

**Comment by shiki** [comment]
Just wanted to highlight this decision on iOS: https://github.com/woocommerce/woocommerce-ios/issues/6031#issuecomment-1032246796

> let's just show the variation attributes but not the stock status for this. Thanks!

**Comment by thehenrybyrd** [comment]
I ran into this in beta testing - glad to see we are already thinking about it!

**Comment by shiki** [comment]
Oh, thanks for noticing this, Alicia. 

@hichamboushaba @wzieba @ThomazFB I think this is important to be delivered sooner than the rest of M2. 

From https://github.com/woocommerce/woocommerce-ios/issues/6031#issuecomment-1026249410:

> The side effect that I see is that this will decrease our merchant's confidence in using the app. If they add a variation, they're not sure if they picked the correct product. It gets more troublesome if they have lots of variations with the same picture. This will cost time too since they'll have to double-check.

Would one of you be able to take this? 🙂

**Comment by hichamboushaba** [comment]
> Would one of you be able to take this? 🙂 

@shiki I can take it.

**Comment by ThomazFB** [comment]
Thanks @shiki and @thehenrybyrd for highlighting the priority for this fix, and @hichamboushaba for the quick response, I'll soon start reviewing your fix.
