### ISSUE TITLE
play-services-tasks Issue

### ISSUE THREAD

**Issue by jkmassel** [woocommerce/woocommerce-android#5800]
From Google:

>play-services-tasks v18.0.0 has known issues that can lead to runtime NPEs (NullPointerException) when handling Task<Void> results in Kotlin code. We strongly recommend that you avoid using this version. This also impacts the SDKs listed in the December 9, 2021 release, because they all depend on play-services-tasks. A fix for this issue is included in play-services-tasks v18.0.1. See https://developers.google.com/android/guides/releases#december_16_2021

Might be worth upgrading to avoid this potential issue.

**Comment by anitaa1990** [comment]
Closed via #5835
