### ISSUE TITLE
[Simple Payments]: Add payment link

### ISSUE THREAD

**Issue by nbradbury** [woocommerce/woocommerce-android#5801]
The iOS app adds a payment link to the simple payments take payment screen and WCAndroid should do the same. Note that this feature must be marked as BETA - explanation [in this iOS PR](https://github.com/woocommerce/woocommerce-ios/pull/6064)

**Comment by shiki** [comment]
As Ernesto stated in p91TBi-6cR-p2#comment-8687, it's probably easier for us to wait until 6.4 is released.

**Comment by shiki** [comment]
The Payment Link issue has been fixed and implemented by @Ecarrion in https://github.com/woocommerce/woocommerce-ios/pull/6594. 

Related: https://github.com/woocommerce/woocommerce-ios/issues/6087
