### ISSUE TITLE
[Order Creation] Accessibility → Create button should not be hidden

### ISSUE THREAD

**Issue by shiki** [woocommerce/woocommerce-android#5814]
Just like https://github.com/woocommerce/woocommerce-android/issues/5813, the Create button should not be hidden. It should instead be initially disabled so it is discoverable via TalkBack.

<img src="https://user-images.githubusercontent.com/198826/152882681-9ae769a0-820c-4dc8-abea-72a5ecb9ff6b.png" width="300">

**Comment by nbradbury** [comment]
Looks like this has already been resolved. The only time the Create button is hidden now is when the order draft is being created, which I believe is expected.
