### ISSUE TITLE
[Order Creation] Accessibility → The Customer Edit button can have more context

### ISSUE THREAD

**Issue by shiki** [woocommerce/woocommerce-android#5817]
When navigating using TalkBack, it's not clear what "Edit" means. It is too similar to the Edit status button. We can change it to say “Edit Customer Details" instead. 

<img src="https://user-images.githubusercontent.com/198826/152884534-cf115b44-bcc9-4110-b08a-1b403f2fdd1a.png" width="300">

**Comment by RenanLukas** [comment]
Hi @shiki  👋 
Would it make sense to also change the talkback text for the other `Edit` buttons in the same screen?
We have edit order status and edit customer note.

**Comment by shiki** [comment]
@RenanLukas That would be great too!

**Comment by RenanLukas** [comment]
WDYT about the following TalkBack text?

Edit order status button: `"Edit order status"`
Edit customer note button: `"Edit customer note"`

**Comment by shiki** [comment]
@RenanLukas Those look good to me. 🙂
