### ISSUE TITLE
[Order Creation] Enable Create button immediately for new orders

### ISSUE THREAD

**Issue by rachelmcr** [woocommerce/woocommerce-android#5846]
The `Create` button should be available immediately when starting to create a new order, to match Core behavior (where orders can be created with only an order status set). Related internal discussion: p5T066-2Zd-p2#comment-11239

Related iOS issue: https://github.com/woocommerce/woocommerce-ios/issues/6150

**Comment by ThomazFB** [comment]
I believe the issue https://github.com/woocommerce/woocommerce-android/issues/5767 is already tracking this improvement, including a bug we found during the WCAndroid 8.5 tests. WDYT?

**Comment by rachelmcr** [comment]
Yes, thanks! I thought there was already an issue related to this, but then I couldn't find it again. Closing this as a dupe.
