### ISSUE TITLE
[Simple Payments] Consistent crash after creating a payment




### ISSUE THREAD

**Issue by shiki** [woocommerce/woocommerce-android#5849]
# Steps

1. Create a simple payment order
2. Use cash to mark it as paid
3. Navigate to My Store
4. Navigate back to Orders

I can consistently reproduce the crash using the steps. I cannot reproduce it if I create an order using the Order Creation feature. 

https://user-images.githubusercontent.com/198826/153678817-681bce8e-5f23-455c-a2c7-795ea4763f55.mp4

**Comment by nbradbury** [comment]
@shiki I'm unable to reproduce this. Are you able reproduce it using a newer build, such as [the APK on this PR](https://github.com/woocommerce/woocommerce-android/pull/5880#issuecomment-1041925662)?

**Comment by shiki** [comment]
Indeed. Something might have changed along the way and I cannot reproduce it anymore. 😌
