### ISSUE TITLE
[Simple Payments] Customer Note is  sometimes truncated

### ISSUE THREAD

**Issue by shiki** [woocommerce/woocommerce-android#5850]
Not quite sure how consistent this is. I added a note that spans more than 6 lines. It gets truncated both on portrait and landscape. 

If this is intentional, please close! 

<img src="https://user-images.githubusercontent.com/198826/153680094-59624d87-b961-4532-82cb-aa166e700c27.png" width="300">
<img src="https://user-images.githubusercontent.com/198826/153680076-64b654e2-60a2-4242-930c-a8b147288942.png" width="300">
<img src="https://user-images.githubusercontent.com/198826/153680066-e2b4c01b-55bd-4adb-bc3e-177adf919579.png" width="300">

**Comment by nbradbury** [comment]
@shiki I'm afraid I'm not able to reproduce this. I added a large customer note, and the entire note shows for me.

https://user-images.githubusercontent.com/3903757/154324376-2d967ad3-614e-47df-9604-7cb48035ed8d.mp4

**Comment by shiki** [comment]
I can still reproduce it. I'll find better reproduction steps.

But I found a different problem. The note can disappear after placing the app in the background. 

1. Add a note. 
2. Press Done.
3. Place the app in the background.
4. Open it again. 
5. Notice that the note that you entered is no longer shown on the screen.

https://user-images.githubusercontent.com/198826/154332952-60684486-5149-4147-8343-d2f3aaf4bdfc.mp4

**Comment by nbradbury** [comment]
> But I found a different problem. The note can disappear after placing the app in the background.

Oof, that I can reproduce, provided that "Don't keep activities" is enabled in developer options. I'll look into it!

**Comment by shiki** [comment]
@nbradbury I'm using this on a fresh emulator, Pixel 4 API 32. Currently using `trunk` (4c936ed3af). I entered this text:

```
Alpha

Bravo

Charlie

Delta

Echo

Foxtrot

Golf

Hotel

Juliett
```

The text gets cutoff at the “Hotel” part. You can see me trying to pull the screen to show it but it doesn't work. 

https://user-images.githubusercontent.com/198826/154340772-93d5c74b-6579-4588-9aea-239d90e9122a.mov

Does this help? Also, this is probably low priority. We don't need to rush this. There are probably more important tasks than this.

**Comment by nbradbury** [comment]
Thanks @shiki, I can reproduce with that text and I think I know what's happening. Fix coming soon 🤞
