### ISSUE TITLE
Fix crash happening on the Card reader Onboarding screen

### ISSUE THREAD

**Issue by AnirudhBhat** [woocommerce/woocommerce-android#5854]
Fix crash happening on the Card reader Onboarding screen because of the CardReaderConfig class throwing `invalid country code` error for any merchant outside the US and CA

Sentry link: https://sentry.io/organizations/a8c/issues/3006574197/?environment=release&environment=debug&project=1459556

**To Reproduce**
1. Navigate to the In-Person Payments screen when your store location is outside of the US or CA

**Comment by jkmassel** [comment]
I think this is was resolved by #5855 – can this be closed?

**Comment by AnirudhBhat** [comment]
@jkmassel Yes. Thank you!
