### ISSUE TITLE
Order Creation: Update the feedback banner to mention Order Creation + Simple Payments

### ISSUE THREAD

**Issue by shiki** [woocommerce/woocommerce-android#5861]
When releasing Order Creation, we should also update the banner so it mentions both Order Creation and Simple Payments. 

Here is the suggested copy:

<img src="https://user-images.githubusercontent.com/198826/154102709-e72fc0ca-e769-44d6-a1ba-89c5bfcab97d.png" width="300">

I think we can use the same survey URL. But let's discuss this first. 

---

p1644885330517869-slack-C02KUCFCSFP

https://github.com/woocommerce/woocommerce-ios/issues/6177

**Comment by ThomazFB** [comment]
I believe this issue is tied up with removing the experimental toggle, so I'll be tackling this later alongside it the same PR.
