### ISSUE TITLE
[Order Creation] Country List not translated

### ISSUE THREAD

**Issue by thehenrybyrd** [woocommerce/woocommerce-android#5866]
**Describe the bug**
When entering (or editing) billing/shipping details, the Country List invariably appears in English. This is the case whether the app settings are set to another language, or the whole phone.

**To Reproduce**
1. Open Settings and head to General management > Language.
2. Change Language to another language (add a language if necessary). 
3. Head back into the app, and either create a new order or edit an existing order.
4. Open Customer Details and tap "Country".
5. Note that the names of the countries are all in English, regardless of the language you selected.

**Screenshots - Korean, Arabic, Spanish**
![countrylistandroid](https://user-images.githubusercontent.com/15107387/154258566-f45678e2-e15b-476c-b8af-3b55245ffc8d.png)

**Expected behavior**
I expected the country list to be in the language I am using the app in.

**Isolating the problem:**
- [ ] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [ ] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [x] I can reproduce this bug consistently using the steps above.

**Mobile Environment**
Please include:
- Device: Samsung Galaxy S21
- Android version: 11
- WooCommerce Android version: 8.5-rc-1

**Comment by thehenrybyrd** [comment]
The same issue exists on iOS: https://github.com/woocommerce/woocommerce-ios/issues/6192

**Comment by hichamboushaba** [comment]
Check https://github.com/woocommerce/woocommerce-ios/issues/6192#issuecomment-1041536012
