### ISSUE TITLE
[Order Creation] Review test coverage

### ISSUE THREAD

**Issue by shiki** [woocommerce/woocommerce-android#5893]
Related p91TBi-7v0-p2.

- Do we have sufficient coverage? 
- What else should we include?

**Comment by shiki** [comment]
I forgot. @wzieba, are you the one looking into this? 😄

**Comment by wzieba** [comment]
One can say that, yes! 😄 . Thanks, I'll assign myself.

**Comment by shiki** [comment]
@wzieba Would you mind posting a summary about this? Or linking it here if I just missed it?

**Comment by shiki** [comment]
Gonna move this to TODO for now since we're focusing on other things at the moment.

**Comment by wzieba** [comment]
Sorry @shiki , I forgot about this. I'll summarize the job done and we can close this issue.

In its scope, we integrated the needed toolkit:
- https://github.com/woocommerce/woocommerce-android/pull/6049
- https://github.com/woocommerce/woocommerce-android/pull/6075
- https://github.com/woocommerce/woocommerce-android/pull/6106
- https://github.com/woocommerce/woocommerce-android/pull/6251
- https://github.com/woocommerce/woocommerce-android/pull/6324

followed by P2 posts:
- p91TBi-7VU-p2
- p91TBi-8aE-p2

The results can be seen in the CodeCov dashboard: https://app.codecov.io/gh/woocommerce/woocommerce-android/

---

For code coverage of Order Creation specific classes, we could improve for sure but it's not bad.

<img width="1155" alt="image" src="https://user-images.githubusercontent.com/5845095/167591754-c247fd73-40a6-4b89-b620-8c37a989a4ef.png">

The no brainers for a good candidate for adding unit tests are `OrderCreationRepository` and `CreateOrderItem`.

**Comment by shiki** [comment]
Thanks, @wzieba! 

> The no brainers for a good candidate for adding unit tests are OrderCreationRepository and CreateOrderItem.

Should we create follow-up tasks for this or do you think it's not critical?

**Comment by wzieba** [comment]
It'd be great if we'd cover that - I'll create a task, good idea!
