### ISSUE TITLE
Add Suggestions URL to the app settings

### ISSUE THREAD

**Issue by jkmassel** [woocommerce/woocommerce-android#590]
It'd be nice to give users the ability to provide new feature feedback right within the app.

Woo uses this board: http://ideas.woocommerce.com/forums/133476-woocommerce?category_id=84283 for that purpose – it'd be simple enough to add a button to the Settings screen (pending approval from our friendly design folks) that would link there!

One concept for how it could look (sorry, iOS, boo hiss)
![sample](https://user-images.githubusercontent.com/1123407/50038425-a91df180-ffdc-11e8-96d2-136d138c7f14.gif)

**Comment by AmandaRiu** [comment]
Closing this ticket as a new one will be created when the designs are finished and approved, and the project is ready to be developed on. Added feature request to the feature backlog in our PM software so it won't get missed.
