### ISSUE TITLE
[Hub Menu] Store info and Switch Store Enhancement

### ISSUE THREAD

**Issue by hafizrahman** [woocommerce/woocommerce-android#5927]
Two great feedbacks that will improve the Hub menu screen:

- [x]  Make entire Store info on top left be clickable for Switch Store action, not just the "Switch Store" text: #5939
- [x]  Remove Store info in the “Settings” screen, since it is already shown on the Hub screen: #5941

see: p1645615288945139-slack-CGPNUU63E

**Comment by anitaa1990** [comment]
Closed via #5941 and #5939
