### ISSUE TITLE
Refactor ProductImagesFragment

### ISSUE THREAD

**Issue by nbradbury** [woocommerce/woocommerce-android#5933]
I’ve been researching [this crash](https://github.com/woocommerce/woocommerce-android/issues/2594) and have decided it’s likely due to passing large sets of data as fragment arguments. When `onSaveInstanceState` is called, internally Android adds the arguments to the bundle, resulting in a crash if it involves more than 512KB of data (or 1MB, depending on the device).

Looking through the code there are several places where we pass lists of models, which could certainly result in the crash with a large enough list. The most conspicuous area is in `ProductImagesFragment`, whose arguments include a list of product image models. I used [TooLargeTool](https://github.com/guardian/toolargetool) while viewing the product images for a product with a lot of images, and can confirm that several hundred KB is being passed.

We should redo that fragment so less data is passed to the arguments. In addition, we should move the lists of images out of the `ProductImagesViewModel.viewState`.

**Comment by JorgeMucientes** [comment]
I'm closing this for now, the [crash is referencing](https://github.com/woocommerce/woocommerce-android/issues/2594) is barely happening anymore (2 users impacted in total and 3 crashes in the last 30 days). So, the reasoning to tackle a refactor might not apply anymore.
