### ISSUE TITLE
Accidentally, showing inbox button in more menu

### ISSUE THREAD

**Issue by JorgeMucientes** [woocommerce/woocommerce-android#5951]
**Inbox** screen is a WIP section from more menu  so it should not be displayed in release versions yet. There is a feature flag to hide this option, but there was a bug in the implementation and the feature flag is being ignored. 

Fix this to ensure **Inbox** button is not displayed as an option inside more menu

**Comment by jkmassel** [comment]
I believe this was resolved by #5952 – @JorgeMucientes can you confirm? 🙂

**Comment by JorgeMucientes** [comment]
Yes @jkmassel ! Sorry about not closing the issue!
