### ISSUE TITLE
Inform user about automatically send receipts

### ISSUE THREAD

**Issue by malinajirka** [woocommerce/woocommerce-android#5967]
Hide "Send receipt" and display "A receipt has been emailed to test@test.com" when billingEmail is not empty (needs design).

This is the current look of the screen.
<img src="https://user-images.githubusercontent.com/2261188/156298631-fd0caaa1-54b0-46c3-a26d-a7c5ac255e27.jpg" width="250px" />

This has been discussed several months ago but never implemented. I think it's an improvement worth implementing. Wdyt @ctarda @adamzelinski ? If we decide it's worth implementing, @adamzelinski could you please add the designs to figma?

**Comment by ctarda** [comment]
It looks like an improvement to me, if we do this on Android I think we should do it on iOS as well 😄

**Comment by ghost** [comment]
Sounds good to me too thanks @malinajirka [here are the designs](https://www.figma.com/file/vaw3DvewbUwuQnPXpdNGGH/Orders---Card-Present-Payments?node-id=2801%3A234067) for iOS & Android

<img width="1408" alt="Screen Shot 2022-03-03 at 1 59 49 pm" src="https://user-images.githubusercontent.com/74938219/156488006-404e279d-70b0-4985-88ac-c46bc6971381.png">

**Comment by malinajirka** [comment]
> It looks like an improvement to me, if we do this on Android I think we should do it on iOS as well 😄

Completely agree, I just didn't want to start the same discussion in two repos :). Here is the ticket for ios:
https://github.com/woocommerce/woocommerce-ios/issues/6358
