### ISSUE TITLE
[Order Creation] Validate email address

### ISSUE THREAD

**Issue by shiki** [woocommerce/woocommerce-android#5975]
Entering an invalid email address can prevent the order from being created. To mitigate this, we added validation for the email address in iOS. We should do the same for Android. 

https://user-images.githubusercontent.com/198826/156448500-b2aedce6-ecbc-496d-82cc-e249e3daf49c.mov

**Comment by ThomazFB** [comment]
Fixed by https://github.com/woocommerce/woocommerce-android/issues/6010
