### ISSUE TITLE
Navigating back from Settings makes screen blink with purple colour

### ISSUE THREAD

**Issue by wzieba** [woocommerce/woocommerce-android#6044]
**Describe the bug**
When navigating back from Settings, the screen blinks for a moment with purple colour (for alpha builds, it's a green colour).

**Screenshots**
### Wasabi

https://user-images.githubusercontent.com/5845095/158861915-894efd29-56b6-4065-b229-aadfc12d886d.mov

### Jalapeno

https://user-images.githubusercontent.com/5845095/158861953-31988c08-7830-4488-95a3-d9b8ba82bd6a.mov

**Expected behavior**
There shouldn't be a blink.

**Comment by Mayuresh0072** [comment]
@wzieba @anitaa1990 Hello, I want to work on this issue and contribute.. Please assign me this issue. Thanks

**Comment by backwardstruck** [comment]
As far as I can tell, this is fixed. Tested on emulator and my device and I didn't see any flash when backing out of settings.
