### ISSUE TITLE
[Order Creation] Add unit test coverage for `OrderCreationViewModel`

### ISSUE THREAD

**Issue by ThomazFB** [woocommerce/woocommerce-android#6047]
As it is, the `OrderCreationViewModel` contains a lot of critical rules for the Order creation feature, but most of what's contained there still don't have unit test coverage. We should fix that by adding proper tests to the ViewModel.

**Comment by wzieba** [comment]
@ThomazFB 👋 as #6049 has been merged, you can now run `./gradlew jacocoTestReport` task and see results of code coverage for `OrderCreationViewModel` and other Order Creation-related classes.

**Comment by ThomazFB** [comment]
That's awesome! Thank you @wzieba! I'll definitely take advantage of it.
