### ISSUE TITLE
Investigate whether we need a NotificationsUpdateService

### ISSUE THREAD

**Issue by aforcier** [woocommerce/woocommerce-android#613]
We have a [TODO](https://github.com/woocommerce/woocommerce-android/blob/585134abf382ddd31e2ef0e7d08a4ce247a9279d/WooCommerce/src/main/kotlin/com/woocommerce/android/ui/login/LoginActivity.kt#L330) around spinning up a `NotificationsUpdateService` on login, which is something the WPAndroid app uses to update the notifications list in the background at certain times (new login, app restarted, etc.).

We should investigate whether we need to add any of this logic to WooAndroid on top of what we've already implemented, and clean up the TODO.

**Comment by anitaa1990** [comment]
@AmandaRiu, do you know if this is something that we still need to investigate? I'm a bit new to notifications and not really sure if there is a pending item here that we might want to tackle 😅

**Comment by AmandaRiu** [comment]
@anitaa1990 I'm not 100% sure honestly, but since we've been running the app in production without issues (other than the missing notification sound you've been looking into), I'd say we probably don't need it. If we find we do in the future we could always open another ticket. WDYT?

**Comment by anitaa1990** [comment]
Sounds good! Thanks for confirming @AmandaRiu 🙇‍♀️
