### ISSUE TITLE
[Order Creation] Products and Payments section layouts break when a huge value is added

### ISSUE THREAD

**Issue by ThomazFB** [woocommerce/woocommerce-android#6133]
Summary
==========
When adding a Product with a price that contains more than 20 digits, the Products and Payments section layouts break with no margins controlling the amount of space consumed by those values.

![expensive](https://user-images.githubusercontent.com/3903757/161085531-75be9692-4efe-4ba0-8830-6390ccda5a83.png)

Steps to Reproduce
==========
1. Go to the Order Creation view
2. Select a Product with a price that contains more than 20 digits
3. Verify that now both Products and Payments sections layouts are completely out of order with the margins

**Comment by nbradbury** [comment]
@ThomazFB I know I was the one who reported this, but I'm thinking it's not worthwhile to correct it. The formatting is just fine even with a price over a million dollars and the device set to the largest font size. WDYT?
![Screenshot_20220507_085915](https://user-images.githubusercontent.com/3903757/167257608-58977b09-1021-4d69-87b4-902123da6221.png)

**Comment by ThomazFB** [comment]
It makes perfect sense, @nbradbury! It seems unlikely that we need to support such large numbers 😄  Thanks for revisiting this issue! I'm closing it.
