### ISSUE TITLE
[Order Creation] Audit Order Creation views RTL support

### ISSUE THREAD

**Issue by ThomazFB** [woocommerce/woocommerce-android#6134]
Summary
==========
When using the RTL layout mode some views around the Order Creation flow don't correctly follow the layout rule.

Screenshots
==========
| Add Shipping view  | Add Product view |
| ------------- | ------------- |
| ![shipping](https://user-images.githubusercontent.com/3903757/161087985-18086047-836b-4940-9d54-5b3c716af95a.png) | ![product](https://user-images.githubusercontent.com/3903757/161088008-94e41dc1-c415-4d78-9f29-f684ca121ade.png) |

Steps to Reproduce
==========
1. Modify the device to use any language that reconfigure the layout to RTL mode
2. Go to the Order Creation flow
3. Verify that some views don't follow the RTL layout rule.

**Comment by hichamboushaba** [comment]
As discussed in the PR #6154, the screenshots above are the correct and expected ones, the text should be RTL only if the content is using an RTL language too.
