### ISSUE TITLE
[Order Creation] Order list creation bottom sheet is not correctly displayed in tablets

### ISSUE THREAD

**Issue by ThomazFB** [woocommerce/woocommerce-android#6135]
Summary
==========
When displaying the Creation bottom sheet inside the Order list view on a tablet, the layout can be cut, making it difficult to select some of the options displayed.

![tablet](https://user-images.githubusercontent.com/3903757/161088678-276b9dd8-6d5a-494e-92f5-5244cb86fc28.png)

Steps to Reproduce
==========
1. Go to the Order list
2. Hit the `+` FAB
3. Verify that the bottom sheet is not correctly displayed, cutting some parts of the layout

**Comment by nbradbury** [comment]
Note that products has the same issue.

![products](https://user-images.githubusercontent.com/3903757/166743739-737f80ed-9a75-4dde-a666-671ab3009d74.png)
