### ISSUE TITLE
Use `wasabi` variant for running `quicklogin`

### ISSUE THREAD

**Issue by wzieba** [woocommerce/woocommerce-android#6139]
**Current behaviour**
Running `quicklogin` script installs `jalapeno` variant which is more CI-centric (source: p1648716318570869-slack-CGPNUU63E). 

**Expected behaviour**
As `wasabi` is a developer build, we should run `quicklogin` on it.

@kidinov - does it sound good to you?

**Comment by kidinov** [comment]
@wzieba totally. Ill pick this up, because it was my mistake at the beginning
