### ISSUE TITLE
Order Creation: Add UI test for creating an order

### ISSUE THREAD

**Issue by atorresveiga** [woocommerce/woocommerce-android#6186]
Create some UI tests for order creation based on [iOS plan for UI Tests](https://github.com/woocommerce/woocommerce-ios/issues/6524)

> Add some UI tests for order creation. We can focus on a functional UI test (the ability to navigate through the UI to create an order) rather than data verification. Depending on time, we can make the test more or less detailed:
> 
> 1. Create an empty order.
> 2. Create an order with a product and customer details.
> 3. Create an order with a product, shipping, fee, customer details, and a customer note.
> 
> Depending on time, we can also go one step further with assertions:
> 
> 1. Only assert that navigation from screen to screen works (using the assertions built into the screen objects) through the entire order creation flow.
> 2. As things are added to the order, assert that the New Order screen UI updates as expected.

### Progress

- [x]  Create an empty order.
- [x]  Create an order with a product 
- [x]  Create an order with a product updating the order status.
- [x]  Create an order with a product and customer details updating the order status.
- [x] Create an order with a product, shipping, fee, customer details, and a customer note updating the order status.

**Comment by shiki** [comment]
@atorresveiga If you're not actively working on this right now, would you mind moving it back to To Do? TIA! I just want the board to be clear about what's currently in progress.

**Comment by jostnes** [comment]
Hey, @atorresveiga do you mind if I continue the rest of the test cases here?

**Comment by atorresveiga** [comment]
> do you mind if I continue the rest of the test cases here?

Not at all. Please continue the rest of the test cases, and I will try to give you a hand as soon as possible. Thanks for taking care of this 🙏

**Comment by jostnes** [comment]
Just to let you know that I've picked this up and it's in progress.
