### ISSUE TITLE
Order Creation: Unclear behavior adding $0 fee to new order

### ISSUE THREAD

**Issue by rachelmcr** [woocommerce/woocommerce-android#6209]
**Describe the bug**

When you tap the "add fee" button in order creation, the "Done" button on the Add Fee screen is already enabled. Tapping "Done" doesn't show any fee added to the order, but the order acts like the fee was added (it syncs remotely and shows the "remove fee" option when you visit the Add Fee screen again).

**To Reproduce**
1. Go to the Orders tab and create a new order.
2. Select "Add fee".
3. Notice the amount is pre-filled with a 0 value and the "Done" button is enabled; tap "Done."
4. Notice the "add fee" button still appears in the Payment section, but the order syncs remotely.
5. Select "Add fee" again and notice the "Add fee" screen now shows a "Remove fee from order" button.

**Screenshots**

Add Fee with Done button enabled|No fee added but order syncs|Remove fee button
-|-|-
![Screenshot_20220408-125627](https://user-images.githubusercontent.com/8658164/162434064-b56e7534-1c34-4f57-b979-7449c6e3dc58.png)|![Screenshot_20220408-125631](https://user-images.githubusercontent.com/8658164/162434071-2cd20598-512c-43ce-8d09-b4a29e2a3b70.png)|![Screenshot_20220408-125635](https://user-images.githubusercontent.com/8658164/162434076-3e0fc040-4542-42b1-86e7-87bee5fa8fc9.png)

**Comment by shiki** [comment]
Related discussion p91TBi-8c4-p2#comment-9450.

**Comment by hichamboushaba** [comment]
@nbradbury @ThomazFB just for visibility before merging the linked PR, as I explained in the P2 (p91TBi-8c4-p2#comment-9451), wp-admin allows `0` fees, so we should decide if it's worth aligning with it or not, and then decide on what's the right fix, which would be one of:
1. Either go ahead with disallowing `0` as fee.
2. Fix the behavior of the UI when a fee with `0` amount exists (I mean changing the UI from `Add Fee` to displaying the current fee).

**Comment by ThomazFB** [comment]
Hey @hichamboushaba, thanks for this reminder about the wp-admin behavior. I agree with your two options. I considered that what was decided for Android would be the option 1, after Rachel's P2 comment linking to this very issue here (p91TBi-8c4-p2#comment-9450). @shiki @rachelmcr thoughts on Hicham's suggestion? Can we move forward with @nbradbury fix or should we follow wp-admin behavior?

**Comment by nbradbury** [comment]
@ThomazFB I think it's fine to merge the related PR. Prior to that PR, adding a zero fee was broken. The PR corrects that and syncs with the iOS experience of disallowing zero fees. We can change both platforms to support zero fees if that's what we decide.

**Comment by shiki** [comment]
Yes, let's merge it. Thanks for highlighting that, @hichamboushaba. 

I think it's okay to wait for user feedback on this.

**Comment by ThomazFB** [comment]
Awesome! Thank you both for the follow-up! It's merged now!
