### ISSUE TITLE
Order Creation: Add accessibility hint for product quantity in order

### ISSUE THREAD

**Issue by rachelmcr** [woocommerce/woocommerce-android#6212]
In Order Creation, once a product is added to the order you can change its quantity. However, when using TalkBack the controls to change the quantity are unclear. When the +/- buttons are selected, they are labeled "minus 1 button" and "plus 1 button" but don't say what those actions apply to (the quantity). There is also no confirmation about the change in quantity after tapping them.

It would be helpful to add hints around that to help TalkBack users get more context/feedback about those controls.

Quantity: minus button|Quantity: plus button
-|-
![Screenshot_20220408-124724](https://user-images.githubusercontent.com/8658164/162436282-3bdfdc29-8329-441c-87f2-78e0a52a3323.png)|![Screenshot_20220408-124727](https://user-images.githubusercontent.com/8658164/162436283-dfa2094e-9523-4722-8046-a6d7a90c78d9.png)

**Comment by nbradbury** [comment]
@rachelmcr How does the iOS app handle this? I figure I should mimic that.

**Comment by rachelmcr** [comment]
In iOS the quantity controls are a single accessibility element. It has the label `[Product name]: Quantity`, gives the current quantity value, and has a custom control to swipe up/down to increase/decrease the quantity. For the "Album" product, for example, VoiceOver reads it out like this:

`Album: Quantity, 1, adjustable, Swipe up or down with one finger to adjust the value.`

Then, as you swipe, it reads out the new value.

If TalkBack has similar options for the controls here I think it'd be great to have similar behavior on both platforms.

<img src="https://user-images.githubusercontent.com/8658164/163357704-ffd375cc-88e7-441a-8304-99320ebea92f.PNG" width="300px">
