### ISSUE TITLE
Order Creation: Navigation animations go the wrong direction in RTL

### ISSUE THREAD

**Issue by rachelmcr** [woocommerce/woocommerce-android#6214]
**Describe the bug**

With your device set to an RTL language (e.g. Arabic), the navigation during Order Creation from the New Order screen to its sub-screens (Add Shipping, Add Fee, etc.) goes the wrong direction.

LTR languages should animate the screens so they come in from/go out to the right side of the screen, while RTL languages should animate the screens so they come in from/go out to the left side of the screen. However, both languages have the same (LTR) animation for navigation:

https://user-images.githubusercontent.com/8658164/162462618-b39d56cd-52d8-4037-9419-757265788561.mp4

https://user-images.githubusercontent.com/8658164/162462631-d878be71-1927-4524-b15f-b096d1255523.mp4

**Comment by nbradbury** [comment]
Just an FYI that this isn't specific to order creation. We use this for many of our fragment transitions:

```
app:enterAnim="@anim/activity_slide_in_from_right"
app:exitAnim="@anim/activity_slide_out_to_left"
```
