### ISSUE TITLE
Order Creation: Add thousand separator to quantity

### ISSUE THREAD

**Issue by shiki** [woocommerce/woocommerce-android#6346]
This can be an enhancement to #6268.

## Steps to reproduce

1. Tap Create order
2. Add a product with an inventory quantity of over 1000. 

Notice that the Order Creation page does not show a comma (or the configured thousand separator). 

<img src="https://user-images.githubusercontent.com/198826/164861628-db25768b-2a22-40ca-a596-8f9a482037c7.png" width="300"><img src="https://user-images.githubusercontent.com/198826/164861645-e8055513-f4c8-402f-8e5c-4dc95b44c16e.png" width="300">

**Comment by jd-alexander** [comment]
This seems like it was resolved.

<kbd><img src="https://github.com/woocommerce/woocommerce-android/assets/1509205/0fddb199-8279-457b-9aa8-f742e607b8eb" width="320"></kbd>
