### ISSUE TITLE
Products: Adding multiple images at the same time creates duplicate images

### ISSUE THREAD

**Issue by shiki** [woocommerce/woocommerce-android#6348]
## Steps to reproduce

1. Create a new product. I used a variable product during my testing.
2. Tap Add a product image.
3. Choose 2 different images.

After uploading, notice that duplicate images are created instead of the 2 different images.

https://user-images.githubusercontent.com/198826/164863326-44c8d3c4-5f61-4eef-8f98-5df5edb49c38.mp4

---

Pixel 3. Android 11. WC version 9.0-rc-1

**Comment by shiki** [comment]
Not sure who to tag on this so I'm tagging multiple people who may have an idea. 😁 

@wzieba @ThomazFB @anitaa1990 @0nko

**Comment by hichamboushaba** [comment]
I spent some time investigating this, and I found the cause, I'll submit a PR with a fix soon.
