### ISSUE TITLE
Copy addresses so it can be pasted elsewhere.

### ISSUE THREAD

**Issue by shiki** [woocommerce/woocommerce-android#6382]
Ref p91TBi-8ma-p2.

This is already available on iOS.

**Comment by shiki** [comment]
@nbradbury This issue is closed by https://github.com/woocommerce/woocommerce-android/pull/6430, right?

**Comment by nbradbury** [comment]
> @nbradbury This issue is closed by #6430, right?

It is, I'll close this.
