### ISSUE TITLE
Order Creation: Remove taxes warning

### ISSUE THREAD

**Issue by shiki** [woocommerce/woocommerce-android#6388]
This message is outdated and should be removed.

<img src="https://user-images.githubusercontent.com/198826/165413227-0baec9e0-1c7a-4c85-aadb-b16a0dffd2bc.png" width="300">

**Comment by nbradbury** [comment]
@shiki There's a similar message on the simple payment screen. Should that be removed, too?

![simple](https://user-images.githubusercontent.com/3903757/168099805-6ae14fe5-cbab-45a1-a610-1df814efe95b.png)

**Comment by shiki** [comment]
The decision for Simple Payments was a bit different for Simple Payments since we originally wanted to show a tax rate picker (p91TBi-6Hn-p2). At first glance, it looks like we don't need that anymore. But that would mean removing the message on iOS too. 

Maybe it's best if we just remove the message in Order Creation for now. Is that possible?
