### ISSUE TITLE
Order Creation: Show price and SKU in products list

### ISSUE THREAD

**Issue by shiki** [woocommerce/woocommerce-android#6390]
When choosing a product while creating an order, the displayed products list do not show the price and SKU. The price and SKU should be displayed.

The product variations list should also be the same.

Android | iOS (correct) 
--------|-------
![image](https://user-images.githubusercontent.com/198826/165418933-0af6f6a6-a83e-43df-bea7-d7adde8ccb52.png)        |    ![image](https://user-images.githubusercontent.com/198826/165418941-16605d44-046f-4925-8228-ec96069f31f4.png)

## Steps

1. Tap FAB
2. Create an order
3. Tap Add product

Ref p91TBi-8c4-p2

**Comment by nbradbury** [comment]
@shiki On Android we're re-using the product list from the products tab. I think if we add SKU & price to the order creation product list they should appear in the main product list, too. WDYT?

**Comment by shiki** [comment]
@nbradbury Is it possible to have separate UIs? Hicham mentioned this in p91TBi-8c4-p2#comment-9451:

> Yes, this was a decision that we took on the first days of the project, to reuse the Adapters from the Product and Variation list screens temporary, and update them one the project is in a good shape, since it was a minor point. But I guess we forgot about them.

**Comment by nbradbury** [comment]
@shiki Yes, we can have separate UIs. It just seems to me that if SKU and price are important enough to show in order creation, then it makes sense to include them in the main list.

**Comment by shiki** [comment]
It's not a bad idea. I'm open to trying it. 😁 Would you mind creating a follow-up issue so iOS can be changed too?

**Comment by nbradbury** [comment]
@shiki I'll start a thread in the async channel about this to make sure there's not a reason to hide SKU & price in the main product list.
