### ISSUE TITLE
Order Creation: Make product row and product deletion UI consistent

### ISSUE THREAD

**Issue by shiki** [woocommerce/woocommerce-android#6391]
The product details shown in the main order creation screen is not the same as the one shown when removing the product. Let's make sure that the product removal screen is showing the same details as the main screen.

<img src="https://user-images.githubusercontent.com/198826/165419585-f9c63bb0-71a0-429c-b731-f5f5fcdcbdd5.png" width="300"><img src="https://user-images.githubusercontent.com/198826/165419651-a65911ea-8068-41e4-9869-cfc658c05540.png" width="300">

Ref p91TBi-8c4-p2

**Comment by nbradbury** [comment]
@shiki Looking at this, I'm wondering if we simply need to strive for consistency for all our product item views. We started this with #6504 which unified the various product lists, and maybe we should reuse the same product view here?  That means if we change something in our product view, those changes show up everywhere a product item is shown.

**Comment by shiki** [comment]
Thanks for looking at this holistically, @nbradbury. If it's possible to reuse them everywhere, that would be great!
