### ISSUE TITLE
"Payment already paid" snackbar shown even when the order is not paid

### ISSUE THREAD

**Issue by malinajirka** [woocommerce/woocommerce-android#6403]
**Describe the bug**

The "The order is already paid" snackbar is shown even when the payment hasn't been completed - eg. when it fails during the capture step and is moved to `on hold` state.

**To Reproduce**

1. Install both WooCommerce Stripe Gateway and Payment Plugins for Stripe WooCommerce (these two plugins has a known plugin conflict - pdfdoF-GM-p2)
2. Connect both of them to the same Stripe account (using test publishable and secret keys)
3. Try to collect an IPP
4. The collection fails Capturing payment failed-generic error
5. Tap on retry
6. Notice the snackbar (the order is not collectible because it's in "on hold" state)

**Expected behavior**
I expect the snackbar won't say that "The order is already paid" - the app either shouldn't display any snackbar or the message should not be misleading/wrong.

**Comment by kidinov** [comment]
Apparently, in the latest SDK, it's not the case anymore, although still some fixing is needed and was performed via https://github.com/woocommerce/woocommerce-android/issues/6489 da
