### ISSUE TITLE
[Order Creation] Add Tracks event when new order fails to sync remotely

### ISSUE THREAD

**Issue by rachelmcr** [woocommerce/woocommerce-android#6493]
The following analytics event should be added:

Event Name|Properties|Trigger
-|-|-
`order_sync_failed`|error_context: $initiated-classname<br />error_type: $errorType<br />error_description: $errorDescription|When a remote sync fails on the New Order screen.

This will help us better understand why some merchants don't finish creating a new order. Internal ref: p91TBi-8Ag-p2

**Comment by nbradbury** [comment]
@rachelmcr Just so I'm clear, we want to track when the user does something like adding a fee, etc., and it fails?

**Comment by rachelmcr** [comment]
Yep, any time an action on the new order screen triggers a remote sync (like adding a fee, shipping, product) and the sync request fails. 👍
