### ISSUE TITLE
Order Details: Display date and time in the order details screen 

### ISSUE THREAD

**Issue by rossanafmenezes** [woocommerce/woocommerce-android#6511]
Based on the conversation here p1652266668998749-slack-CGPNUU63E and [here ](https://github.com/woocommerce/woocommerce-android/pull/6501#issuecomment-1125707656) we should display date and time on the order details screen to make things easier for the user.

![fixed 2](https://user-images.githubusercontent.com/30724184/168320848-2c4a8170-6853-42fb-89a6-cec82dac51d0.png)

**Comment by nbradbury** [comment]
As noted in p1654018664622669/1652266668.998749-slack-CGPNUU63E , we're also going to remove the order id from the date/time since it's already in the toolbar.
