### ISSUE TITLE
Settings: Sync Tracks Opt Out setting

### ISSUE THREAD

**Issue by mindgraffiti** [woocommerce/woocommerce-android#654]
WPAndroid issue Ref. https://github.com/wordpress-mobile/WordPress-Android/issues/7523, implementation Ref. https://github.com/wordpress-mobile/WordPress-Android/pull/7637.
 
## Sync global opt-out preference
As part of the GDPR efforts, WordPress.com recently introduced a new setting to opt-out. We want to sync the opt-out in the apps with that value whenever the user is signed in.

The setting is stored as tracks_opt_out in me/settings.

The toggle would still be in app settings. It would show the value for the primary account if there’s one, otherwise the local per-app setting. When the user changes the setting, it would change the local value and for all the WordPress.com accounts in the app.

**Comment by nbradbury** [comment]
Closing this as we've had this in WCAndroid since last August - see https://github.com/woocommerce/woocommerce-android/blob/f81583364bb67c861cc8c47343e4324b26bcf03c/WooCommerce/src/main/kotlin/com/woocommerce/android/ui/prefs/PrivacySettingsPresenter.kt#L43

**Comment by mindgraffiti** [comment]
Thank you Nick!
