### ISSUE TITLE
[Simple Payments] Payment link can't be used after copying it from app

### ISSUE THREAD

**Issue by rachelmcr** [woocommerce/woocommerce-android#6547]
**Describe the bug**

After creating a Simple Payment, copying the payment link on the "Take Payment" screen changes the order status to `completed`. This stops the payment link from working so payment can't be collected for that order. (A message appears on the checkout page noting that the order's status is "completed" so it can't be paid for.)

We've had a couple user reports of this issue via the in-app survey.

**To Reproduce**
1. Go to the Orders tab.
2. Tap the + button and select Simple Payment.
3. Enter an amount and proceed to the Take Payment screen.
4. Select "Share Payment Link."
5. Copy the link and open it in Chrome. Notice that you cannot make any payment because of the order status. (You can also go back to the Orders tab in the app and confirm that the order has the  `completed` status.)

**Screenshots**

Take Payment screen|Payment link
-|-
![Screenshot_20220519-135848](https://user-images.githubusercontent.com/8658164/169299925-d8646f75-a8ec-49a9-a79e-a804911917f7.png)|![Screenshot_20220519-140013](https://user-images.githubusercontent.com/8658164/169299946-9657e504-534c-4550-a8a9-2279c5f75d1b.png)

**Expected behavior**

Sharing the payment link should not mark the order as completed. It shouldn't be completed until payment is received for the order.

**Comment by nbradbury** [comment]
Thanks for reporting this @rachelmcr, I'll tackle it today!
