### ISSUE TITLE
Simplify Simple Payment VM

### ISSUE THREAD

**Issue by nbradbury** [woocommerce/woocommerce-android#6563]
As @ThomazFB suggested [here](https://github.com/woocommerce/woocommerce-android/pull/6550#issuecomment-1133191976), there are some simplifications we could make to the simple payment view model.

**Comment by ThomazFB** [comment]
@nbradbury I just opened this PR right here addressing this issue: https://github.com/woocommerce/woocommerce-android/pull/6562. Sorry for going ahead upfront, since I had the changes in my changelog, I just committed everything and pushed 😅

**Comment by nbradbury** [comment]
No worries, I'm looking over the changes now!

**Comment by nbradbury** [comment]
Closed via #6562
