### ISSUE TITLE
Refine magic link e-mail content

### ISSUE THREAD

**Issue by aforcier** [woocommerce/woocommerce-android#658]
With https://github.com/woocommerce/woocommerce-android/issues/310, the server side for magic links was updated to mention the 'WooCommerce mobile app' instead of the WordPress app in the e-mail body copy.

We can make further refinements to Woo-ize the magic link e-mail further. Per @kyleaparker (https://github.com/woocommerce/woocommerce-android/issues/310#issuecomment-451774624):

Not sure how much of this is possible but here is a quick mockup using more WooCommerce specific branding:

![magic-sign-in](https://user-images.githubusercontent.com/712873/50741528-1aab3180-1263-11e9-9cf4-e755cf9b684c.png)

- Replace WP logo with Woo logo
- In the main copy change WordPress to WooCommerce
- Instead of **Sign in to WordPress.com** say **Sign in with WordPress.com**
- Title could either be:
   - Magic sign in link for WooCommerce
   - Sign in to WooCommerce on your mobile device

cc @astralbodies

**Comment by joshbetz** [comment]
@AmandaRiu Can you help me understand what needs to be done in the API to support this request?

**Comment by AmandaRiu** [comment]
> @AmandaRiu Can you help me understand what needs to be done in the API to support this request?

Hrm, I'm not sure - looks like I added that label over 2 years ago and I no longer work on this project. Looking at the details of this issue it looks like _server_ work is needed, not API work. So it's probably safe to remove this label. WDYT?

**Comment by joshbetz** [comment]
Ok! I'll double check with @anitaa1990 who might have some more recent context. Thanks!

**Comment by anitaa1990** [comment]
Hey @joshbetz This issue talks about changing the email branding during the login process. So if use the magic link option to login from the app, the email that is sent looks like this:

<img src="https://user-images.githubusercontent.com/22608780/156754316-fd255681-246f-492b-b21b-0fb6a95870aa.PNG" width="300"/>

It mentions WordPress as the logo and the button is blue. It would be nice to maybe use the Woo colors here since the user is logging in from the Woo app.

**Comment by coreymckrill** [comment]
I believe this is now complete, as part of the project to requesting magic login links from WC Admin for logging into the app.

More context: pe5uwI-3u-p2
