### ISSUE TITLE
WCStatsStore: Remove cache buster from fetchRevenueStats?

### ISSUE THREAD

**Issue by coreymckrill** [woocommerce/woocommerce-android#6595]
My understanding is that [including a random number](https://github.com/wordpress-mobile/WordPress-FluxC-Android/blob/f72e5d145dcfcf6e6875863e874496c1866676e7/plugins/woocommerce/src/main/kotlin/org/wordpress/android/fluxc/store/WCStatsStore.kt#L654) in the API request for revenue stats was added in order to prevent fetching stale cached data, due to a bug on the WC Admin side. The same workaround [was implemented](https://github.com/woocommerce/woocommerce-ios/issues/1183) in wc-ios, but was recently [removed](https://github.com/woocommerce/woocommerce-ios/pull/6640) because the bug has since been fixed. Would it be possible to remove the workaround here as well?

**Comment by ThomazFB** [comment]
Fixed in https://github.com/wordpress-mobile/WordPress-FluxC-Android/pull/2455
