### ISSUE TITLE
Update OnboardingChecker - Navigate to the payment gateway selection screen

### ISSUE THREAD

**Issue by malinajirka** [woocommerce/woocommerce-android#6625]
The goal of this task is to navigate to the payment gateway selection screen when `there are two payment gateways installed` and `selection isn't stored in SharedPreferences` and `both payment gateways are supported in store's country`, otherwise, continue the onboarding with the selected payment gateway. Only when the FF is enabled.

**Comment by kidinov** [comment]
Moved to done in the project so closing
