### ISSUE TITLE
Track the payment gateway the user selected

### ISSUE THREAD

**Issue by malinajirka** [woocommerce/woocommerce-android#6631]
Introduce new CARD_PRESENT_ONBOARDING_PAYMENT_GATEWAY_SELECTED event. Add parameter indicating which payment gateway was selected - heads up that it might be already included on all IPP related events. Sync with iOS folks.

**Comment by toupper** [comment]
@rossanafmenezes @AnirudhBhat On iOS I used the string (`card_present_payment_gateway_selected`, properties: `"payment_gateway": "WooCommerce Payments"|"WooCommerce Stripe Gateway"`) Please use it or let me know if you think of a better name so we can synchronize :)
