### ISSUE TITLE
Track taps on "Manage Payment Gateways" row

### ISSUE THREAD

**Issue by malinajirka** [woocommerce/woocommerce-android#6632]
Introduce new tracking event - CARD_PRESENT_MANAGE_PAYMENT_GATEWAYS_TAPPED. Track the event when the user taps on "Change Payment Provider" row on the Hub screen. Consider if we need to track any params with it and sync with iOS folks.

**Comment by toupper** [comment]
@rossanafmenezes @AnirudhBhat On iOS I used the string `settings_card_present_select_payment_gateway_tapped`. Please use it or let me know if you think of a better name so we can synchronize :)
