### ISSUE TITLE
[Order Details] Refund lines should be shown chronologically in their groups

### ISSUE THREAD

**Issue by joshheald** [woocommerce/woocommerce-android#6643]
![Image](https://user-images.githubusercontent.com/2472348/170694592-4e8cc3b7-3320-4228-acf7-f94638727d80.png)

> If two separate refunds occur, they are presented in chronological top-to-bottom order on iOS and the reverse on Android.
>
> The payment section is presented so that you read it from top-to-bottom. This implies that newer items will appear below older ones. Android should copy iOS.
>
> – p91TBi-8P0-p2#line-items-in-the-payment-section

 - [ ] Display refund lines oldest first in chronological order.

**Comment by kidinov** [comment]
From my testing, this works already this way. Asked Joe to verify, maybe there is a misunderstanding on my side p91TBi-8P0-p2#comment-10435

**Comment by joshheald** [comment]
Joe verified that this is actually something we need to do on iOS, not Android
