### ISSUE TITLE
[Mobile Payments] Show a cancel button while searching for a card reader

### ISSUE THREAD

**Issue by joshheald** [woocommerce/woocommerce-android#6644]
![Image](https://user-images.githubusercontent.com/2472348/170694900-7279e47a-3939-4983-813f-d8d0654339fa.png)

> **CPP Inconsistencies**
>
> While searching for a card reader, iOS shows a Cancel button, while Android does not.
> While searching for a card reader, show a Cancel button on Android.
>
> – p91TBi-8P0-p2#cpp-inconsistencies

- [ ] Add a cancel button to the searching for reader CPP modal

**Comment by kidinov** [comment]
Probably was tested on the old build, because now we do have a cancel on the scanning state



https://user-images.githubusercontent.com/4923871/172163879-ce6f4fbb-e3fc-48ce-af0b-cc3ecc743612.mp4
