### ISSUE TITLE
[Unified Order Editing] Remove feature flag usage from Order Editing

### ISSUE THREAD

**Issue by Ecarrion** [woocommerce/woocommerce-android#6657]
# Description

Once the order can be successfully edited from the order details screen, we can remove the feature flag that guards it.

# Task

- [ ] Remove feature flag guard (Don't remove feature flag yet)
- [ ] Update changelog
- [ ] Make sure the test plan is considered and attached.

**Comment by shiki** [comment]
@Ecarrion Can you make sure that customer search (https://github.com/woocommerce/woocommerce-android/pull/6826) is also added in the changelog? TIA!
