### ISSUE TITLE
Shipping label image needs end margin

### ISSUE THREAD

**Issue by nbradbury** [woocommerce/woocommerce-android#6674]
The image to the right of the shipping label banner needs margin so it's not "stuck" to the end of the display.

![screen](https://user-images.githubusercontent.com/3903757/171233933-03e9a464-21be-4e6a-a610-2c3e0af3464f.png)

**Comment by hichamboushaba** [comment]
@nbradbury this is how it looks on the design:

<img width="290" alt="Screen Shot 2022-06-22 at 14 50 40" src="https://user-images.githubusercontent.com/1657201/175045792-5800500e-fe1b-4281-868b-3c8e537f7ce1.png">

And this is similar to the screenshot you shared on the [comment](https://github.com/woocommerce/woocommerce-android/pull/6797#issuecomment-1163117074), so I'd say it's working as expected, and lets' close the ticket.

And just for more context, there was a long discussion regarding how to scale the image on different scenarios in the PR https://github.com/woocommerce/woocommerce-android/pull/6594.
