### ISSUE TITLE
Prompt for app review

### ISSUE THREAD

**Issue by astralbodies** [woocommerce/woocommerce-android#668]
Stealing from the WP app, let's prompt users already logged in for reviewing the app. Try to not reinvent the wheel and time-box this to minimal effort for now.

iOS issue: https://github.com/woocommerce/woocommerce-ios/issues/580

**Comment by nbradbury** [comment]
The RatingsManager library looks promising, but I noticed there's no license in its repo so I'm not sure we can use it. Regardless, it should be easy enough to roll our own.

**Comment by aforcier** [comment]
Added in #701.
