### ISSUE TITLE
[Mobile Payments] Figure out how to track Simple payments separately and normal payments when SelectPayment screen is reused

### ISSUE THREAD

**Issue by kidinov** [woocommerce/woocommerce-android#6695]
We rename current Simple payments events to PAYMENTS_ and add property inside to reflect the flow:

* PAYMENTS_FLOW_COLLECT
* PAYMENTS_FLOW_COMPLETED
* PAYMENTS_FLOW_FAILED

And add params:

* flow -> simple_payment 
* flow -> order_payment

pdfdoF-TT-p2

- [x]  Add a note to the tracks that  3 events were renamed pdfdoF-TT-p2#comment-1818

**Comment by kidinov** [comment]
// cc @joshheald  I think the same has to be done on iOS?

**Comment by joshheald** [comment]
> // cc @joshheald I think the same has to be done on iOS?

Thank you, good shout. I'll add an iOS issue.

**Comment by joshheald** [comment]
I just added it to https://github.com/woocommerce/woocommerce-ios/issues/6782, which is the reuse ticket. We should co-ordinate on naming the events though.
