### ISSUE TITLE
[Order Details] Show refunded shipping lines in refund summary

### ISSUE THREAD

**Issue by kidinov** [woocommerce/woocommerce-android#6714]
⛔️ Awaiting design confirmation: p91TBi-8P0-p2#comment-10438

Refunded shipping is not displayed anywhere on the Order Details screen, nor in the refund details that you can tap through to.

> There’s an [outstanding issue on Android](https://github.com/woocommerce/woocommerce-android/issues/3853) from last year to add a line for shipping refunds within the Refunded Products section.
> – @joshheald

> The shipping cost is only referred to in the Payments section – so it seems more natural to me that we’d indicate a shipping refund somewhere here, rather than in the products section.
> maybe “Refunded: 2 products and shipping ––– $33.00”?
> – @joe-keenan

> ![Image](https://user-images.githubusercontent.com/2472348/172662855-44dbe918-3ade-4091-ae97-e3a435a52acb.png)
>
> I think it’s the right place but I also think that we’ll have problems with larger Dynamic Type sizes and some localizations.
> – @joshheald

For context: p91TBi-8P0-p2#comment-10327

- [ ] Include refunded shipping lines on Order Details

**Comment by kidinov** [comment]
For the reference p91TBi-8P0-p2#comment-10263

**Comment by kidinov** [comment]
![image](https://user-images.githubusercontent.com/4923871/172611326-9a8559ab-2e11-40a8-bdb6-3b2733f6c438.png)

**Comment by joshheald** [comment]
@kidinov In case you've not started yet, I'd avoid working on this one until we get confirmation of the design. I think it will have to change because of localization/dynamic type issues as per p91TBi-8P0-p2#comment-10438

**Comment by kidinov** [comment]
@joshheald oops, I just noticed that after I raised [a PR](https://github.com/woocommerce/woocommerce-android/pull/6721) =(. But it's ok, if wording has to be changed it's a small change Btw, I used a bit different (shorter) wording there so we might consider this too

Also, can't you just split the line when it's too long due to a larger font?

**Comment by joshheald** [comment]
> Also, can't you just split the line when it's too long due to a larger font?

Yes, it just looks pretty bad and will happen fast on iOS, possibly even at default sizes in some localizations. Here it is forced onto two lines (in code, not due to length or font size.)

![image](https://user-images.githubusercontent.com/2472348/172817538-3b6126f0-b4e0-477d-a03d-3a5746426ef0.png)

**Comment by kidinov** [comment]
Done so far this way - https://github.com/woocommerce/woocommerce-android/pull/6721
