### ISSUE TITLE
Scrolling to the bottom of lists doesn't show the proper animation hint

### ISSUE THREAD

**Issue by astralbodies** [woocommerce/woocommerce-android#688]
### Expected behavior
When reaching the bottom of a screen or list I expect to see that funky curved animation that tracks the finger to indicate you're at the bottom.

### Actual behavior
Some screens are missing it (like the order list, dashboard) and some don't track with the finger only showing it upon scrolling hitting the bottom (like the notifications screen).

### Steps to reproduce the behavior
1. Go to the order list with a site having at least a screenful +1 of orders.
2. Scroll to the bottom.
3. No visual indicator given when scrolling stops or attempting to scroll further.
4. Go to the dashboard.
5. Scroll to the bottom.
6. See the visual indicator that the bottom is reached but nothing if you attempt to scroll further.

**Comment by nbradbury** [comment]
We thought this was fixed in #900 but as noted [here](https://github.com/woocommerce/woocommerce-android/pull/955#issuecomment-478748405), the fix caused PTR to stop working in the dashboard so we reverted it.
