### ISSUE TITLE
Remove IPP_SELECT_PAYMENT_GATEWAY feature flag completely

### ISSUE THREAD

**Issue by rossanafmenezes** [woocommerce/woocommerce-android#6900]
As discussed here p1657222006561719-slack-C03HQTLS1HA adding the issue to remove the feature flag completely to avoid issues since we have removed the WcpayAndStripe activated state

**Comment by AnirudhBhat** [comment]
This issue is taken care by [this PR](https://github.com/woocommerce/woocommerce-android/pull/6885)
