### ISSUE TITLE
When adding a new note, track if its private or public

### ISSUE THREAD

**Issue by wzieba** [woocommerce/woocommerce-android#6986]
According to the Tracks documentation, we should track if created note is either private or public. 

This resolves comment: https://github.com/woocommerce/woocommerce-android/blob/4e7066c66e4f532054fc050f7111c486d08d88ee/WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/notes/AddOrderNoteViewModel.kt#L86

**Comment by shiki** [comment]
I don't think we've ever used this information. I'm gonna close it for now. Let me know if you disagree.
