### ISSUE TITLE
Banner dismiss dialog get's disappeared on device rotation 

### ISSUE THREAD

**Issue by AnirudhBhat** [woocommerce/woocommerce-android#7008]
In the main app settings screen, when the upsell card reader banner is being shown, trying to dismiss will pop up an alert dialog. At this point, rotating the device would cause the dismissal of the alert dialog. This shouldn't happen. 

The reason for this bug is that we are not handling the state restoration on device rotation for the main settings screen. The reason in turn for that is because the main settings screen is developed using MVP and needs some modification before we actually handle the state restoration on device rotation. 

The goal of this task is to maintain the state on device rotation.

https://user-images.githubusercontent.com/1331230/180398911-8f8bcb58-74e4-425e-ab9d-4e36078ca2a0.mp4

**Comment by kidinov** [comment]
The banner was removed from the settings
