### ISSUE TITLE
[Elevate] Update analytics for ExPlat experiment

### ISSUE THREAD

**Issue by rachelmcr** [woocommerce/woocommerce-android#7053]
We need to make the following updates to analytics for running the ExPlat experiment:

* The event `connected_products_list` needs to be registered and validated in Tracks. This is a **prerequisite** for setting up the experiment.
* The event `product_detail_loaded`:
   * Should be updated to ensure it's triggered when the product detail screen is first loaded, including when a new product is added, and not when the product is re-fetched (see discussion: p1659023340627739-slack-CGPNUU63E).
   * Needs a new custom property `has_linked_products: true | false`, where the prop is `true` when the product that is loaded in product detail has linked products (upsells or cross-sells).

Experiment design (internal ref): pbxNRc-1Pp-p2

**Comment by nbradbury** [comment]
@rachelmcr For tracking `product_detail_loaded` for a new product, I'm wondering if we should wait until the product is published to determine whether it has linked products?

**Comment by rachelmcr** [comment]
When a new product is being added, the `has_linked_products` prop should just always be `false` (since there's no detail yet when the screen is loaded).

In the context of this experiment, the event `product_detail_loaded` will be used just to track when the product detail screen is opened for a product that doesn't yet have any linked products. For new products, that's all of them. Then, we'll measure the `connected_products_list` event to see how many merchants go on after that to add a linked product.

**Comment by rachelmcr** [comment]
> The event `connected_products_list` needs to be registered and validated in Tracks.

I was just taking a closer look at this event and it doesn't seem to be triggered everywhere it should be. In my testing, we don't track events on the "Linked Products" screen; we only track them on the "Upsells" and "Cross-sells" screens:

1. Open a product with no linked products.
2. Select Add more details > Linked products.
3. On the Linked products screen, under Upsells, tap "Add products" (you can repeat these steps with Cross-Sells with the same results). **Expected: `connected_products_list` is tracked with `action: add_tapped`. Actual: Event is not tracked.**
4. Select a product from the list and tap the check box to confirm. **Expected: `connected_products_list` is tracked with `action: added`. Actual: Event is not tracked.**
5. Tap "Edit products" under Upsells.
6. On the Upsells screen, tap "Add products". Notice `connected_products_list` is tracked with `action: add_tapped` as expected.
7. Select a product from the list and tap the check box to confirm. Notice `connected_products_list` is tracked with `action: added` as expected.
8. On the Upsells screen, tap the "X" to remove a linked product. Notice `connected_products_list` is tracked with `action: delete_tapped` as expected.

As a result, we aren't tracking the first upsell or cross-sell added to a product.

**Comment by rachelmcr** [comment]
Reopening this; it was closed by a PR but isn't complete yet.

**Comment by nbradbury** [comment]
> I was just taking a closer look at this event and it doesn't seem to be triggered everywhere it should be. In my testing, we don't track events on the "Linked Products" screen; we only track them on the "Upsells" and "Cross-sells" screens:

@rachelmcr I just looked into this and saw that `connected_products_list` is being tracked on the **grouped** products screen. Is it different on iOS?

**Comment by rachelmcr** [comment]
@nbradbury It's the same on iOS, but we have a custom prop that tracks which context triggers the event (upsells, cross-sells, or grouped) so we'll be able to filter our tracking to just the linked products context.
