### ISSUE TITLE
My Store: Dates Tabs are misaligned

### ISSUE THREAD

**Issue by thehenrybyrd** [woocommerce/woocommerce-android#7137]
**Describe the bug**
When I open the app, in My store the "Today" tab and following tabs are not left-aligned as I'd expect.

**To Reproduce**
1. Open the app
2. Note where the Today/This Week/This Month/This Year tabs appear

**Screenshots**
<img src="https://user-images.githubusercontent.com/15107387/183610644-116f21d5-be20-4405-b0ee-ad10955cd41b.png" width="70%">

**Expected behavior**
Expected the "Today" tab and following tabs to align left, with the "My store" heading.

**Mobile Environment**
Samsung Galaxy S21, Android 12, WC Android 9.8-rc-1

**Comment by wzieba** [comment]
hi @thehenrybyrd ! I think it's expected on Android, it follows Material Design guidelines: https://material.io/components/tabs#usage - please see `Scrollable tabs` fragment.

**Comment by thehenrybyrd** [comment]
Hi @wzieba! 😄 
😮 wow, I had no idea!
I have to admit, it looks very strange to me, I notice every time I open the app. Maybe that's because we don't follow this guideline in WP or JP for scrollable tabs. And it seems Google doesn't follow these guidelines, for instance on scrollable tabs in the Play Store or Chrome:

![scrollable](https://user-images.githubusercontent.com/15107387/183623683-9f9fe335-a2ac-4259-a71a-d761930ecb74.png)
hmm, maybe they're _very slightly_ offset in Chrome, but not in Play Store.

Maybe we could use a smaller offset? 
You're totally right that we're following Material Design guidelines though. And I'm not an Android user in real life, so my instincts are perhaps not reliable here, so feel free to close if you disagree.

**Comment by wzieba** [comment]
> And it seems Google doesn't follow these guidelines

😄 

You're right. I don't know which approach will be the best, the smaller offset should also work. I think we could make a design request for that. Thanks for starting this discussion and research! 🙏

**Comment by hichamboushaba** [comment]
This is not relevant anymore after releasing the dynamic dashboard
