### ISSUE TITLE
IPP Banner: Text of "dismiss" notice doesn't display in dark mode

### ISSUE THREAD

**Issue by thehenrybyrd** [woocommerce/woocommerce-android#7138]
**Describe the bug**
When I want to dismiss the IPP banner, a notice comes up asking to "remind me later" or "don't show again". In Dark mode, the text "No worries! You can always..." is not visible.

**To Reproduce**
1. In Menu > Settings > Appearance, select Dark mode.
2. In Menu > Settings, or in Orders, tap the "x" to dismiss "Accept payments easily" banner
3. Note that a notice pops up with the options "remind me later" and "don't show again", but it has a big black space in the middle.

**Screenshots**
<img src="https://user-images.githubusercontent.com/15107387/183620701-8a86639f-4e0b-4d16-82ce-c8b5fbfa1640.png" width="70%">

**Expected behavior**
I expected the text "No worries! You can always..." to be visible in dark mode, as it is in light mode.

**Mobile Environment**
Samsung Galaxy S21, Android 12, WC Android 9.8-rc-1

**Comment by AnirudhBhat** [comment]
This issue is taken care of by [this PR](https://github.com/woocommerce/woocommerce-android/pull/7136). Thank you!
