### ISSUE TITLE
Extend PUT/POST endpoint in fluxc to support renaming the "Cash on Delivery" title

### ISSUE THREAD

**Issue by AnirudhBhat** [woocommerce/woocommerce-android#7144]
The goal of this task is to extend an endpoint added [here](https://github.com/woocommerce/woocommerce-android/issues/7141) to support renaming the "Cash on Delivery" title.

**Comment by rossanafmenezes** [comment]
This has been addressed here https://github.com/wordpress-mobile/WordPress-FluxC-Android/pull/2492
