### ISSUE TITLE
Notifications: Empty state doesn't show "waiting for customers"

### ISSUE THREAD

**Issue by astralbodies** [woocommerce/woocommerce-android#728]
**Describe the bug**
When the user's site has no data we show the waiting for customers visualization. Notifications doesn't show this when there aren't any notifications yet.

**To Reproduce**
1. Connect to a site with no orders/notifications/products.
2. Click on Notifications.
3. See the blank screen without the placeholder.

**Screenshots**
![screenshot_20190129-143337](https://user-images.githubusercontent.com/373903/51986694-6ae27180-2466-11e9-8d7c-8454b7e59f45.png)

**Mobile Environment**
Please include:
- Device: Pixel 2
- Android version: 9
- WooCommerce Android version: 1.1-rc1

**Comment by nbradbury** [comment]
Closed via #731
