### ISSUE TITLE
Stats: Sales totals do not match in some cases

### ISSUE THREAD

**Issue by astralbodies** [woocommerce/woocommerce-android#740]
**Describe the bug**
There are cases where the sales totals for a time period don't match what Calypso and wp-admin report.

**To Reproduce**
Steps to reproduce the behavior on @juliaamosova's test site:
1. Click on Years.
2. Click on the 2017 bar.
3. Notice in the app it says $9.8k total.
4. Do the same in Calypso and wp-admin and notice it says $8,066.73.

**Screenshots**
<img width="1155" alt="2019-02-01_15-30-24" src="https://user-images.githubusercontent.com/373903/52151816-ee07f100-2639-11e9-9287-8c268aa6f014.png">
<img width="711" alt="2019-02-01_15-38-26" src="https://user-images.githubusercontent.com/373903/52151819-efd1b480-2639-11e9-884b-c812cea3f7aa.png">

**Expected behavior**
Totals should match across platforms including web.

**Comment by astralbodies** [comment]
Target 1.1 code frozen release with this fix.

**Comment by bummytime** [comment]
iOS PR → https://github.com/woocommerce/woocommerce-ios/pull/654

**Comment by nbradbury** [comment]
This will need to be fixed on the FluxC side. Note that @bummytime found the solution - we should be showing total *gross* sales rather than total sales.
