### ISSUE TITLE
Order Details: Shipping method title/Local Pickup Plus compatibility

### ISSUE THREAD

**Issue by IanMisnerThough** [woocommerce/woocommerce-android#741]
We've received a user report that shipping details are "inaccurate" while using [Local Pickup Plus](https://woocommerce.com/products/local-pickup-plus). 

The order details provide a "Shipping address" and show no indication that the order is to be picked up. 

Ideally, this area would display the pickup location along with indication that the order is intended for pickup. Here's [how it's handled in wp-admin by Local Pickup Plus](https://github.com/woocommerce/woocommerce-shipping-local-pickup-plus/blob/master/templates/orders/order-pickup-details.php). 

Alternatively, displaying the shipping method title would provide the minimum amount of useful information. 

[Related iOS issue
](https://github.com/woocommerce/woocommerce-ios/issues/655)

**Comment by AmandaRiu** [comment]
Closing this ticket as a new one will be created when the designs are finished and approved, and the project is ready to be developed on. Added to feature backlog.
