### ISSUE TITLE
Widget Improvements

### ISSUE THREAD

**Issue by nbradbury** [woocommerce/woocommerce-android#7440]
- [x] Change instructions (some devices don't enable long pressing on app icon for adding a widget)
- [x] Ellipsize the store name
- [x] Switch to a horizontal layout so revenue doesn't wrap (design below)
- [x] Update preview when above is completed

![android](https://user-images.githubusercontent.com/3903757/191272170-920eb858-f446-4c32-9484-974ce1ccb9a3.png)

**Comment by Ecarrion** [comment]
Hey @nbradbury can I close this one?

**Comment by nbradbury** [comment]
@Ecarrion Closing it!
