### ISSUE TITLE
Uploading multiple images for product is buggy

### ISSUE THREAD

**Issue by JorgeMucientes** [woocommerce/woocommerce-android#7453]
**Describe the bug**
When uploading multiple images for a product at the same time, the upload process is buggy. Sometimes it duplicates images (happens when they are reordered), some others the image results in being completely black. 

Note that the bug does not happen all the time. But we've got some users in Zendesk complaining about the issue: 5582722-zd-woothemes 
I was able to reproduce it easily. 

**To Reproduce**
Steps to reproduce the behaviour:
1. Open product detail
2. Click on add images
3. Select multiple images from gallery
4. Wait for all of them to upload and watch for duplicated or buggy behaviour. 

**Screenshots**

https://user-images.githubusercontent.com/2663464/192289278-89d77054-d935-42eb-bd2d-cf81f479091b.mp4

**Mobile Environment**
Please include:
- Device: Pixel 6
- Android version: 13
- WooCommerce Android version: 10.4

**Comment by hichamboushaba** [comment]
@JorgeMucientes I think this is the same as https://github.com/woocommerce/woocommerce-android/issues/6348, my bad for forgetting about the fix 🤦.
I know the cause, there is a race condition, and I can fix it this week, let me know how you want to proceed? 🙂

**Comment by JorgeMucientes** [comment]
Oh nice @hichamboushaba. It's great that you already investigated this and have a fix for it, that'll make things faster. 
Happy to review the PR if you want :) 

Closing this issue as it is duplicated from #6348.
