### ISSUE TITLE
New order does not appear in order list (refresh is needed)

### ISSUE THREAD

**Issue by toupper** [woocommerce/woocommerce-android#7463]
**Describe the bug**
After creating a new order and going back to the order list, the list is not refreshed thus not showing the new order. We have to refresh by pulling it in order to see it.

**To Reproduce**
1. Go to Orders
2. Create a new order
3. Once is created, go back to the order list
4. Order is not in the list

**Screenshots**

https://user-images.githubusercontent.com/1864060/192978793-2f452dc4-7f9d-4ffb-881e-dc2b402d5724.mp4

**Expected behavior**
The new order is on top of the list

**Comment by kidinov** [comment]
Duplicate https://github.com/woocommerce/woocommerce-android/issues/7167
