### ISSUE TITLE
[Elevate] Remove A/B test code and release banner to everyone

### ISSUE THREAD

**Issue by rachelmcr** [woocommerce/woocommerce-android#7473]
The linked product promo banner tested in the Elevate project A/B test (`woocommerceandroid_product_details_linked_products_banner`, added in https://github.com/woocommerce/woocommerce-android/pull/7226) was successful. We should remove that A/B test and release the treatment behavior to everyone.

Internal ref: pe5pgL-7v-p2#comment-853

**Comment by ThomazFB** [comment]
@rachelmcr does make sense to make this removal right now? Looks like a really small effort since we already reached a conclusion, I can do that if it makes sense. cc @shiki

**Comment by shiki** [comment]
Yep. Do it.
