### ISSUE TITLE
Zendesk icon takes you out of app from "My Tickets"

### ISSUE THREAD

**Issue by FreshPhil** [woocommerce/woocommerce-android#749]
**Is your feature request related to a problem? Please describe.**
From the "My Tickets" section, if you tap the Zendesk icon you are taken out of the app an to a landing page for Zendesk Elements

**Describe the solution you'd like**
- Remove the icon if possible
- Make icon not clickable

**Additional context**
http://cld.wthms.co/iZSblk

**Comment by nbradbury** [comment]
As much as I'd like to remove that icon, the Zendesk docs say it's not possible:

> It is not possible to move elements of the UI around, remove parts of the UI, or add new parts.
