### ISSUE TITLE
Misleading UI when using site URL to login

### ISSUE THREAD

**Issue by FreshPhil** [woocommerce/woocommerce-android#750]
**Describe the bug**
When logging in with the Site Address URL, you require a WordPress.com username and password.

This is not obvious as the way the page is designed seems to ask for the username/password from the user's admin account on their website. 

**To Reproduce**
- Click "Log in by entering your site address"
- Enter site URL
- Note the request for username/password under the site url
- Try entering the user/pass for an account on your website

Note that there is no indication on the page or in the login error that you are asking for a WordPress.com login.

**Isolating the problem (mark completed items with an [x]):**
- [X] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [X] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [X] I can reproduce this bug consistently using the steps above.

**Comment by nbradbury** [comment]
For reference, here's the screen in question.

![screenshot_1550503966](https://user-images.githubusercontent.com/3903757/52961303-a33fe600-3368-11e9-95df-125e34d1e7e8.png)

**Comment by nbradbury** [comment]
Asked for designer input on whether to re-label that as "WordPress.com username." Will follow up after they reply.

**Comment by kyleaparker** [comment]
@nbradbury agreed that we should clarify this. We can either add "WordPress.com username" or add a label above the form that says "Log in with your WordPress.com account to manage your WooCommerce stores"
