### ISSUE TITLE
Add property to product_list_searched event to distinguish between SKU and All Products search

### ISSUE THREAD

**Issue by shiki** [woocommerce/woocommerce-android#7517]
<img src="https://user-images.githubusercontent.com/198826/195217499-7b90765d-8210-454c-bfdc-2c6c06831db0.png" width="300">

As it is right now, `products_list_searched` is triggered when searching. But you can't tell if it's for searching using SKU or the regular search.

```
🔵 Tracked: product_list_searched, Properties: {"search":"axp","blog_id":186855689,"is_wpcom_store":false,"is_debug":true}
```

**Comment by nbradbury** [comment]
Note: The events spreadsheet shows this:

<img width="689" alt="event" src="https://user-images.githubusercontent.com/3903757/195391518-c1db41c7-2d7a-43e3-b367-c55db7b815ab.png">

**Comment by shiki** [comment]
@nbradbury Thanks. Would you mind double-checking the implementation? I tried it yesterday in `trunk`, and it didn't show that property.

**Comment by nbradbury** [comment]
@shiki Sorry, that was a note to myself - that's the event in the spreadsheet to make sure I do the same as iOS.

**Comment by shiki** [comment]
No worries. 

I haven't realized this was implemented on iOS. Is it? I didn't see it yesterday. 😅

**Comment by nbradbury** [comment]
I guess I assumed that since it's in the event spreadsheet, then iOS must've implemented it. It looks like it was added [here](https://github.com/woocommerce/woocommerce-ios/blob/401163eb092b071d67302d9d5809e1ad5e3180e6/WooCommerce/Classes/ViewRelated/Search/Product/ProductSearchUICommand.swift#L171-L178).
