### ISSUE TITLE
API: Support decimal quantities

### ISSUE THREAD

**Issue by astralbodies** [woocommerce/woocommerce-android#755]
Related to this issue on iOS that prevents syncing when a site has an extension installed to support decimal quantities: https://github.com/woocommerce/woocommerce-ios/issues/662

**Is your feature request related to a problem? Please describe.**
Sites with decimal quantities in orders may not sync properly. Extensions like [Measurement Price Calculator](https://woocommerce.com/products/measurement-price-calculator/) change the quantity field into a decimal.

**Describe the solution you'd like**
Support decimal quantities for scenarios where customers have extensions installed permitting that data type.

**Describe alternatives you've considered**
Instead of changing the storage to accept integers we could nullify the data upon import and present the user with a visual artifact showing an unsupported quantity.

**Additional context**
There are paid extensions providing this functionality so I figured we should probably support it in a way that isn't too much change.

**Comment by nbradbury** [comment]
Closing this - it was already fixed in [this FluxC PR](https://github.com/wordpress-mobile/WordPress-FluxC-Android/pull/1056).
