### ISSUE TITLE
Order list custom date range filter wrong start date

### ISSUE THREAD

**Issue by nbradbury** [woocommerce/woocommerce-android#7566]
Steps to reproduce:

* Go to the order list 
* Tap filters
* Tap Date Range
* Tap Custom range
* Choose a range then tap Save to return to the Date range screen
* Notice the start date is day earlier than selected

@atorresveiga Pinging you since you worked on this. Note that I'm also seeing this in the analytics custom date range picker, and my guess is it's a UTC issue.

https://user-images.githubusercontent.com/3903757/196801959-a3e1c048-00df-4584-9ccf-7a0f7a53307b.mp4

**Comment by nbradbury** [comment]
**Update:** This was a UTC issue, which I resolved in analytics by setting the date formatter's timezone to UTC.

```
       val startDate = Date(startDateMillis)
        val endDate = Date(endDateMillis)

        val dateFormat = SimpleDateFormat("EEE, LLL d, yy", Locale.getDefault())
        dateFormat.timeZone = TimeZone.getTimeZone("UTC")

        val fromDateStr = dateFormat.format(startDate)
        val toDateStr = dateFormat.format(endDate)
```

**Comment by kidinov** [comment]
Seems to be it's been fixed
