### ISSUE TITLE
[Analytics Hub] Remap entities usage inside the Analytics trial code VM to a entity defined inside WCAndroid namespace

### ISSUE THREAD

**Issue by ThomazFB** [woocommerce/woocommerce-android#7571]

**Comment by wzieba** [comment]
I was wrong with this suggestion.

The `AnalyticsRepository` returns mapped classes like [`OrdersStat`](https://github.com/woocommerce/woocommerce-android/pull/7556/files#diff-254682ce03ac46785b787c493793d74577c2e53de80e3f96c819e8c1f9841390R3), [`ProductsStat`](https://github.com/woocommerce/woocommerce-android/pull/7556/files#diff-8c0ab2553f0a5bf07bee748a419e6e2a8af84aabef16d8b5cd0a8a4d291a434cR3) or [`RevenueStat`](https://github.com/woocommerce/woocommerce-android/pull/7556/files#diff-a5734b7fce48f7b4e9829383043033e381fccff9c8fd95e0749205de4691f99cR3) to `AnalyticsViewModel`. The entities and payloads are mapped. I'll close it as "not planned".
