### ISSUE TITLE
We set StatementDescriptor as it is, while it has strict requirements

### ISSUE THREAD

**Issue by kidinov** [woocommerce/woocommerce-android#7586]
On the @pachlava website, during intent creation we get from the SDK:

> com.stripe.stripeterminal.external.models.TerminalException: The statement descriptor must be at most 22 characters. [NOODLEFINGERS.WPCOMSTAGING.COM](http://noodlefingers.wpcomstaging.com/) is 30 characters long.

It happens because we set StatementDescription as it is, while it has strict [requirements](https://stripe.com/docs/account/statement-descriptors#requirements)

We should check what iOS does here and align in the way we handle this

**Comment by samiuelson** [comment]
Here's how iOS is processing statement descriptor text: https://github.com/woocommerce/woocommerce-ios/blob/trunk/Hardware/Hardware/CardReader/StatementDescriptor.swift
