### ISSUE TITLE
[Analytics Hub] Add Analytics Events

### ISSUE THREAD

**Issue by shiki** [woocommerce/woocommerce-android#7588]
Please see pe5pgL-153-p2

- [x] Update `used_analytics`
- [x] Add the other new events (see post)

**Comment by shiki** [comment]
@ThomazFB Can you confirm that we've added triggers to the `used_analytics` event? I don't see it in #7649.

**Comment by ThomazFB** [comment]
I've added it but made a mistake when rearranging the commits after the rebase between all the branches I had to combine. The second patch with the `used_analytics` got left out and I inserted only the first patch with the new tracks. 

I opened a hotfix PR containing the patch changes targeting the release branch opened today [right here](https://github.com/woocommerce/woocommerce-android/pull/7682). Let me see if I can put that code in time for the release candidate.

Thanks for detecting this, @shiki.
