### ISSUE TITLE
Track `*_jitm_fetch_success` event with props `source: my_store`, `jitm: {FIRST_RECEIVED_JITM_ID}`, `count: {NUMBER_OF_JITMs_IN_RESPONSE}`

### ISSUE THREAD

**Issue by AnirudhBhat** [woocommerce/woocommerce-android#7621]
The goal of this task is to add a track event when the JITM fetch API succeeds.

Properties:
`source` : `my_store`
`jitm` : `{FIRST_RECEIVED_JITM_ID}`
`count` : `{NUMBER_OF_JITMs_IN_RESPONSE}`

**Comment by joshheald** [comment]
@AnirudhBhat I've updated this to match the decision/discussion in P2: pdfdoF-1zc-p2#comment-2681
