### ISSUE TITLE
Log card reader battery level when logging errors

### ISSUE THREAD

**Issue by AnirudhBhat** [woocommerce/woocommerce-android#7651]
**Describe the bug**
A clear and concise description of what the bug is. Please be as descriptive as possible; issues lacking detail, or for any other reason than to report a bug, may be closed without action.

It would be helpful to analyze the IPP support queries if we log the card reader battery level along with the error information. 

Stripe terminal SDK sometimes throws a [cryptic error](p91TBi-9sD-p2#comment-10903) when the card reader battery is low and this would be confusing to figure out where the problem lies.

**Expected behavior**
The card reader battery level would be logged along with the card reader errors

**Comment by malinajirka** [comment]
@AnirudhBhat @samiuelson Is this implemented on iOS too? In case it's not, we might want to consider creating a task there to make sure the platforms stay consistent.

Also, I noticed it seems we haven't updated the internal spreadsheet with all tracking events and their properties - check out P91TBi-6GE-p2 for more context. Could one of you update it please, thanks!

**Comment by samiuelson** [comment]
@malinajirka I've updated the spreadsheet and added info about the new property in the events.
