### ISSUE TITLE
[Analytics Hub] Fix the device Timezone difference when requesting analytics from the store

### ISSUE THREAD

**Issue by ThomazFB** [woocommerce/woocommerce-android#7665]

**Comment by nbradbury** [comment]
@ThomazFB I think there was some miscommunication regarding this. I'm not convinced there's a timezone issue - the real problem turned out to be using the wrong date ranges for Today and Yesterday. After I fixed that, I tested with Jayson's site which is GMT+0 and the numbers matched `wp-admin`.

**Comment by ThomazFB** [comment]
Oh, looks like I misunderstood our conversation after that fix! Thanks for highlighting it! 🙇 I'll close this, then.
