### ISSUE TITLE
[Analytics Hub] Fix duplicate `Year to Date` in the date range selection

### ISSUE THREAD

**Issue by ThomazFB** [woocommerce/woocommerce-android#7680]
The `Year to Date` option in the date range selection of the Analytics Hub is showing twice

![Image](https://user-images.githubusercontent.com/5920403/198692637-66d48414-a90c-455e-ac15-92a8331cbc3b.png)

**Comment by nbradbury** [comment]
I can't believe we all missed this!

**Comment by ThomazFB** [comment]
Right?! 😅
