### ISSUE TITLE
Add platform identifier, version name, and phone's locale as query parameters while fetching JITM

### ISSUE THREAD

**Issue by AnirudhBhat** [woocommerce/woocommerce-android#7733]
## Description
In Project Salas, we've added the ability to send Just In Time Messages to all Woo Mobile users, initially displayed on the dashboard. A single message definition will be picked up both on iOS and Android. This is beneficial as we don't need to define the same messages multiple times for different platforms...

However, there will definitely be cases when we want to send a message to a smaller subset of our users, or define test JITMs which are not yet ready for production. The `with_query_string` and `without_query_string` JITM rules can help here, but only if we pass useful data in the query.

These rules were intended to work on the query string in a browser's url bar, when accessed from PHP web code. Since we request JITMs through the REST API, we also need to pass the "query string" in the request. The JITM engine doesn't check the REST request's query string for these parameters.

See pdfdoF-1Fe-p2 for full context.

## Locale

`locale=en_US` or other phone locale code. This is unused and for future proofing. It should be added at the same level as the named `path` and `query` URL Query Parameters (see example request below.)

## JITM query parameters to add:

- `platform` = `android`
- `version` = `11.1`: use `BuildConfig.VERSION_NAME`. This changes to e.g. `11.1.1` for hot fix builds.
- `build_type` = `developer` when `isDebug==true`, i.e. local development and CI builds. N.B. don't include this parameter on production/beta/alpha builds.
- `device` = `phone` or `pad`. Optional, may be put off or not done if too challenging on Android

## Request format:

These JITM parameters should be constructed as a query string, before inclusion in the JSON payload of the `GET /jetpack/v4/jitm/` request. This is unlike the locale parameter, which is a top level URL query parameter. Be careful to check all this, because the name `query` is used in several places!

### Example JITM query:

- Before URL encoding: `platform=android&version=11.1&build_type=developer&device=phone`
- URL encoded: `platform%3Dandroid%26version%3D11.1%26buildType%3Ddeveloper%26device%3Dphone`
- JSON: `{"message_path": "woomobile:my_store:admin_notices", "query": "platform%3Dios%26version%3D11.1%26build_type%3Ddeveloper%26device%3Dphone"}`
- URL Query Param: `query=%7B%22message_path%22%3A%20%22woomobile%3Amy_store%3Aadmin_notices%22,%20%22query%22%3A%20%22platform%3Dandroid%26version%3D11.1%26build_type%3Ddeveloper%26device%3Dphone%22%7D`

This will lead to a request like this:

```
curl "https://public-api.wordpress.com/rest/v1.1/jetpack-blogs/{SITE_ID}/rest-api?path=jetpack%2Fv4%2Fjitm&query=%7B%22message_path%22%3A%20%22woomobile%3Amy_store%3Aadmin_notices%22,%20%22query%22%3A%20%22platform%3Dandroid%26version%3D11.1%26build_type%3Ddeveloper%26device%3Dphone%22%7D&locale=en_US" \
     -H 'Host: public-api.wordpress.com' \
     -H 'Authorization: Bearer {TOKEN}' \
     -H 'Content-Type: application/x-www-form-urlencoded; charset=utf-8'
```

**Comment by joshheald** [comment]
@AnirudhBhat FYI I've updated the build type parameter to be named `build_type` not `buildType`, to better fit with conventions of these objects/query strings. Apologies I didn't get that right first time.

**Comment by joshheald** [comment]
@AnirudhBhat I've also realised that there's no such thing as double-url encoded...! So you can construct the JSON with a normal string, and it will get encoded when it's added as a parameter. That's what happens on iOS, anyway.
