### ISSUE TITLE
NumberFormatException on bulk update variations

### ISSUE THREAD

**Issue by atorresveiga** [woocommerce/woocommerce-android#7760]
**Describe the bug**
While bulk updating variations, the app will crash when a not valid `Double` value is entered. Using the `android:inputType="number|numberSigned"` tag helps allowing the user to enter signed/number values only, but it doesn't prevent the case of a single `-` value (not a double but valid for the EditTextControl)

**To Reproduce**

1. Have a variable product with two variations. One variation not tracking stock quantity, and the other variation with a stock quantity of -1. (This also happens if both variations have a quantity of -1.)
2. Bulk update the stock quantity with a negative value and check that the app crashes for input string: "-".

**Expected behavior**
The doesn't crash when a "-" char is entered on the EditText control

**Isolating the problem (mark completed items with an [x]):**
- [x] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [x] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [x] I can reproduce this bug consistently using the steps above.

**Comment by shiki** [comment]
@atorresveiga Is #7764 enough to close this issue?
