### ISSUE TITLE
Fatal Exception: java.util.NoSuchElementException List is empty

### ISSUE THREAD

**Issue by jkmassel** [woocommerce/woocommerce-android#781]
There's a error in this method that doesn't handle a case where there may be no Order Status items in the database: 

https://github.com/wordpress-mobile/WordPress-FluxC-Android/blob/758e870799948a9b4efa16fd76c180eb7353983c/plugins/woocommerce/src/main/kotlin/org/wordpress/android/fluxc/persistence/OrderSqlUtils.kt#L148-154

**Similar to:** https://github.com/woocommerce/woocommerce-android/issues/645
**Source:** fabric-5c625cfff8b88c296384c98d
**First found in:** `1.2-rc-1`

**Comment by nbradbury** [comment]
Closed via #7917
