### ISSUE TITLE
Show product detail from order detail

### ISSUE THREAD

**Issue by nbradbury** [woocommerce/woocommerce-android#783]
Users should be able to tap a product in the order detail to view details about that product. This is on hold pending design work.

**Comment by jkmassel** [comment]
This has already been bumped twice, so removing the milestone for now – I suspect this'll be closed when https://github.com/woocommerce/woocommerce-android/issues/913 is.

**Comment by AmandaRiu** [comment]
This was all implemented in #913. Closing.
