### ISSUE TITLE
Due to usage wrong Lifecycle state for MenuProvider the dropdown menu disappears on cofiguration change

### ISSUE THREAD

**Issue by kidinov** [woocommerce/woocommerce-android#7845]
More details on that - https://github.com/woocommerce/woocommerce-android/pull/7798#discussion_r1021309336

The goal is to find when in the app we use MenuProvider and the fragment shows dropdown menu and check if lifecycle used for the registration of this MenuProvider is Started or Created

**Comment by bunyodrafikov** [comment]
I am going to solve this issue now
