### ISSUE TITLE
Impossible to clear filters because clear button disappears 

### ISSUE THREAD

**Issue by kidinov** [woocommerce/woocommerce-android#7846]
* Open Products
* Click on filters
* Add filters and go back to the list of filters
* Notice that the clear button is gone

![image](https://user-images.githubusercontent.com/4923871/201660015-ebf6c5e6-903e-405c-83d9-b925b8353617.png)

**Comment by rossanafmenezes** [comment]
Closing this in favour of #7465  since it's the same issue.
