### ISSUE TITLE
[Products] Message about variations without price is shown only after opening variations list.

### ISSUE THREAD

**Issue by pachlava** [woocommerce/woocommerce-android#7917]
Reported by @itsmeichigo 

**Describe the bug**
When a variable product is created, but the price for variation is not set, the app will show this message:

<img width="367" alt="Screenshot 2022-11-22 at 15 41 04" src="https://user-images.githubusercontent.com/73365754/203328554-a92c55ec-4b7e-4de7-8b12-736032b5d4da.png">

only after going to Variations screen and back (happens on 45th second):

https://user-images.githubusercontent.com/73365754/203328226-64d2633d-7c33-43a3-813b-b3247fd34a64.mp4

**To Reproduce**
1. Create a new variable product
2. Add an attribute and options names
3. Tap `Generate variation` ~> note that you don't see the message in question
4. Open variations list and go back ~> now you see it

**Expected behavior**
The message should be shown after step `3`.

**Mobile Environment**
- Device: Samsung A31
- Android version:  11
- WooCommerce Android version: 11.3-rc-1

**Comment by rossanafmenezes** [comment]
Hi @pachlava 👋 

I was testing this issue to start working on it but it looks like it has been addressed already:

<img src="https://github.com/woocommerce/woocommerce-android/assets/30724184/fca0eab6-3ad1-41a8-a773-a03628e15bc6" width="350"/> 

Could you kindly confirm if you can still reproduce this issue on your end?

Thanks

**Comment by pachlava** [comment]
Yes, this is the case @rossanafmenezes 👍 It's not reproducbile any longer (I checked with the latest `14.3-rc-1`). I'm closing this one. Thank you!
