### ISSUE TITLE
Implement "selection state" of products list view

### ISSUE THREAD

**Issue by wzieba** [woocommerce/woocommerce-android#7929]
### Description

This task is about enabling a selectable state of the products list view. It contains the following scope:

- [ ] [code] I'm suggesting using similar approach to the one in `ProductImagesViewModel`: https://github.com/woocommerce/woocommerce-android/blob/trunk/WooCommerce/src/main/kotlin/com/woocommerce/android/ui/products/ProductImagesViewModel.kt#L259-L264
- [ ] [UI] After enabling the "selection state" user should be able to select a product as on design:
<img width=300 src=https://user-images.githubusercontent.com/5845095/203562645-7616498e-ef3d-4e1c-ba58-b9ddc1cbced7.png>

- [ ] [UI] After enabling the "selection state" user should see menu button with some options

![Image](https://user-images.githubusercontent.com/5845095/203563079-7d03b8f5-1a75-496b-a7ad-fb6c38bac283.png)

- [ ] [UI] Hide FAB

**Comment by wzieba** [comment]
Should we enable "selection state" after long-press on a list item?

**Comment by atorresveiga** [comment]
> Should we enable "selection state" after long-press on a list item?

I believe we should. Long-press a list item is a common pattern for entering the **selection mode** on mobile

**Comment by ParaskP7** [comment]
FYI @wzieba that I've just moved this issue's milestone to `11.7` as I'll be starting code freeze on `11.6` soon.
