### ISSUE TITLE
Change bar chart colors

### ISSUE THREAD

**Issue by nbradbury** [woocommerce/woocommerce-android#793]
As per our Slack conversation, we should change the chart so all the bars are gray (no separate weekend color), and use purple to highlight the tapped bar.

[Related iOS issue](https://github.com/woocommerce/woocommerce-ios/pull/680)

**Comment by mindgraffiti** [comment]
Ref. #439 and Ref. https://github.com/woocommerce/woocommerce-ios/issues/386
