### ISSUE TITLE
Implement "select all" feature

### ISSUE THREAD

**Issue by wzieba** [woocommerce/woocommerce-android#7930]
### Description

_It's a nice to have feature_

After tapping on "Select all", all products should be selected.

It's a nice-to-have feature as stated here: pe5pgL-1oz-p2

**Comment by atorresveiga** [comment]
Select all should be **select all products** or **all visible products** (products already loaded in the app). I will vote for loading all visible/loaded products in the app, as the first iteration.

**Comment by ParaskP7** [comment]
FYI @wzieba that I've just moved this issue's milestone to `11.7` as I'll be starting code freeze on `11.6` soon.
