### ISSUE TITLE
Support products bulk status update

### ISSUE THREAD

**Issue by wzieba** [woocommerce/woocommerce-android#7932]
### Description

This task is about enabling users to provide a status update for multiple products. In the scope of this task, we should:

- link networking/persistence layer
- support error handling
- provide necessary UI widgets (dialog?)
- success message (Snackbar)

![Image](https://user-images.githubusercontent.com/5845095/203565811-755a9efd-e5b8-48b9-8e4f-743e65c72a37.png)

**Comment by ParaskP7** [comment]
FYI @wzieba that I've just moved this issue's milestone to `11.7` as I'll be starting code freeze on `11.6` soon.
