### ISSUE TITLE
Support products bulk price update

### ISSUE THREAD

**Issue by wzieba** [woocommerce/woocommerce-android#7933]
### Description

This task is about enabling users to provide a price update for multiple products. In the scope of this task, we should:

- link networking/persistence layer
- support error handling
- provide necessary UI widgets (dialog?)
- success message (Snackbar)

<img src=https://user-images.githubusercontent.com/5845095/203566418-7f456572-1660-45da-ab94-eb0721745441.png width=300>

**Comment by ParaskP7** [comment]
FYI @wzieba that I've just moved this issue's milestone to `11.7` as I'll be starting code freeze on `11.6` soon.
