### ISSUE TITLE
[Simplified Login] Remove XMLRPC checks from the app during login

### ISSUE THREAD

**Issue by hichamboushaba** [woocommerce/woocommerce-android#7961]
As discussed internally: pe5sF9-KS-p2, we want to remove the XMLRPC checks during login with site credentials, this will increase success rate for both signing in using site credentials, and Jetpack installation.

- [ ] Add a new Origin type to the `SiteModel` table. https://github.com/wordpress-mobile/WordPress-FluxC-Android/pull/2583
- [ ] Add a network implementation for fetching site data using the Rest API. https://github.com/wordpress-mobile/WordPress-FluxC-Android/pull/2583
- [ ] Update the app's implementation to use the new implemenation.

**Comment by audreyspency** [comment]
What's the ultimate solve to this

**Comment by hichamboushaba** [comment]
This was done as part of https://github.com/woocommerce/woocommerce-android/pull/8289
