### ISSUE TITLE
Pass `customer_id` while creating a new order

### ISSUE THREAD

**Issue by wzieba** [woocommerce/woocommerce-android#7968]
When creating an order for a predefined customer, we should pass `customer_id` in the request. This will assert the correct association between the customer and the order. 

### Current behavior
When creating an order from the app, there's no association between order and selected customer:
<img width="662" alt="image" src="https://user-images.githubusercontent.com/5845095/204530435-81fe9e85-4915-411d-a5d7-411451e448fa.png">

### Expected behavior 
When creating an order from the app, there's an association between order and selected customer:
<img width="681" alt="image" src="https://user-images.githubusercontent.com/5845095/204530573-8820a7ba-1ab6-4825-adb2-e4cbabcd02a4.png">

**Comment by shiki** [comment]
Linking related discussion: pe5pgL-1sT-p2
