### ISSUE TITLE
Order Details: Address exists but does not display

### ISSUE THREAD

**Issue by mindgraffiti** [woocommerce/woocommerce-android#800]
**Describe the bug**
Internal ref: 1780813-zen and p99K0U-Wk-p2

**To Reproduce**
1. In your store's site, edit an order and delete the country from the shipping and billing addresses. Note the order number.
2. Go to the app and navigate to Orders > {order number}
3. Under the Customer Information section, find the Shipping Address heading. It will report "No address specified"
4. If you're running the simulator in Xcode, an error is thrown and reports that the address has no country.

**Screenshots**
<img width="355" alt="screen shot 2019-02-14 at 10 26 17 am" src="https://user-images.githubusercontent.com/1062444/52821007-3203e880-3073-11e9-89df-daa96d7dfa4c.png">

**Expected behavior**
The address should display. Even if the address is a partial address, display it. See the internal refs for the solution to implement.

**Isolating the problem (mark completed items with an [x]):**
- [x] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [x] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [x] I can reproduce this bug consistently using the steps above.

**Mobile Environment**
Please include:
- Device: all 
- Android version: (n/a)
- WooCommerce Android version: 1.2 ??

**WordPress Environment**
N/A

**Comment by nbradbury** [comment]
@mindgraffiti I'm not seeing this issue on WCAndroid. When the country is missing, we still display the address. And we don't show "No address specified" anywhere.

I'm going to close this, but please re-open if I'm misunderstanding the problem.

![screenshot_1550246389](https://user-images.githubusercontent.com/3903757/52868324-f1f34300-3110-11e9-80b5-6f32c193b99d.png)
