### ISSUE TITLE
Add Tracks events

### ISSUE THREAD

**Issue by wzieba** [woocommerce/woocommerce-android#8004]
### Description

This issue is about adding tracking events as described internally: pe5pgL-1oo-p2

**Comment by ParaskP7** [comment]
FYI @wzieba that I've just moved this issue's milestone to `11.7` as I'll be starting code freeze on `11.6` soon.

**Comment by ParaskP7** [comment]
FYI @wzieba that I've just moved this issue's milestone to `11.8` as I'll be starting code freeze on `11.7` soon.

**Comment by wzieba** [comment]
Hi @ParaskP7 - I'll revert this back to `11.7` as it was resolved in attached PR. I don't know why Github didn't close this issue automatically.

**Comment by ParaskP7** [comment]
Ah coolio, thank you so much for that @wzieba ! 🥇 🙇 🌟
