### ISSUE TITLE
Toolbar Back Arrow Shown on Top-Level Navigation

### ISSUE THREAD

**Issue by theck13** [woocommerce/woocommerce-android#806]
### Expected
The back arrow is hidden when going to the ***My store***, ***Orders***, or ***Notifications*** tab from an order details screen.

### Observed
The back arrow is shown when going to the ***My store***, ***Orders***, or ***Notifications*** tab from an order details screen.

#### Orders
1. Go to ***Orders*** tab.
2. Tap order in list.
3. Notice back arrow is shown in toolbar.
4. Tap ***My store*** or ***Notifications*** tab.
5. Notice back arrow is shown in toolbar.

#### Notifications
1. Go to ***Notifications*** tab.
2. Tap notification in list.
3. Notice back arrow is shown in toolbar.
4. Tap ***My store*** or ***Orders*** tab.
5. Notice back arrow is shown in toolbar.

#### Tested
Google Pixel 3 on Android 9.0 with WooCommerce 1.2-rc-2

**Comment by nbradbury** [comment]
Thanks for catching this, @theck13!
