### ISSUE TITLE
[Mobile Payments] Card reader manuals are downloaded but not shown when opened via browser

### ISSUE THREAD

**Issue by pachlava** [woocommerce/woocommerce-android#8109]
Spotted by @toupper

**Describe the bug**
When opening a card reader manual via browser (it was `Samsung Internet` in my case), the PDF will be downloaded, but the browser view will get closed right after the download is finished:

https://user-images.githubusercontent.com/73365754/210547912-762760a2-001c-46c3-8ae5-3d1c2783d847.mp4

Even though I had Chrome installed, it was not in the list. Opening with G-Drive worked the way I'd expect it to work (PDF being rendered on screen).

**To Reproduce**
1. Navigate to Payments section of the app
2. Tap `Card Reader Manuals` and select a manual to open
3. When asked about the way to open, select a browser (It was `Samsung Internet` for me). 
4. You will be asked where to download the file, once the file is downloaded, the browser window will be closed.

**Expected behavior**
I'd expect to see the manual opened in the browser

**Mobile Environment**
- Device: Samsung A31
- Android version: 11
- WooCommerce Android version: 11.7-rc-2

**Comment by toupper** [comment]
@kidinov This might be interesting to you :)

**Comment by kidinov** [comment]
@pachlava @toupper 

We fire intent with URL to the system, and all apps that support that schema are shown to a user. The user picks the app that they want to use to handle this action. 

So, in short, that's just how this browser handles URLs with PDF files - we can not do anything about that. A user should click on the file from the downloads and open in the app that reads PDF files on their's device
