### ISSUE TITLE
Retain the state of the "My Store" tab when the activity is destroyed

### ISSUE THREAD

**Issue by anitaa1990** [woocommerce/woocommerce-android#812]
**Describe the bug**
Currently on MyStore screen, if app is resumed from the background, the current state of the screen is not maintained. So if I select the YEARS/MONTHS/WEEKS tab in MyStore screen, minimize the app and then bring it back to the foreground it will just revert back to the DAYS tab.

**To Reproduce**
1. After logging into your WordPress account, go to MyStore screen. 
2. Click on 'MONTHS' tab
3. Click Home button
4. Open WooCommerce app again
5. Notice that the current tab is 'DAYS'

**Screenshots**
<img src="https://user-images.githubusercontent.com/22608780/52998296-f5f0cf00-3448-11e9-9984-7ce419bff4bd.gif" width="300"/>

**Isolating the problem (mark completed items with an [x]):**
- [x] I can reproduce this bug consistently using the steps above.

**Comment by nbradbury** [comment]
Note that this only occurs when the activity is destroyed when it goes to the background. To repro, enable the "Don't keep activities" developer option on the device.
