### ISSUE TITLE
Help & Support: When sending a ZD ticket, attach a list of plugins

### ISSUE THREAD

**Issue by AmandaRiu** [woocommerce/woocommerce-android#820]
**Is your feature request related to a problem? Please describe.**
Android gets the list of plugins "for free" and attaches the list to Zendesk when a ticket is created. iOS needs this ability as well. 

**Describe the solution you'd like**
This will require:
- [x] A separate API call that requests the plugins list. (Possibly firing off at the same time as the Site Settings API call.)
- [ ] The plugins list will need put in Storage - probably a new entity in SiteSettings?
- [ ] The plugins list will need attached to the Zendesk ticket

**Describe alternatives you've considered**
Our current situation is that we have no plugins list. It slows down troubleshooting / debugging for HEs and devs because we have to go find that information manually.

**Additional context**
Bring parity between the apps! 👍 

cc: @bummytime @astralbodies

**Comment by jkmassel** [comment]
This has already been bumped twice, so I'm removing the milestone for now :)

**Comment by rossanafmenezes** [comment]
We are already pulling the full SSR to ZD support tickets when available. Closing this.
