### ISSUE TITLE
Send Tracks event when exiting price, inventory, shipping or image

### ISSUE THREAD

**Issue by wzieba** [woocommerce/woocommerce-android#8209]
### Description

As a result of some refactoring, a few editable areas on the Product Detail screen are not sending Tracks events upon exiting.

This leads to invalid conclusions about the usage of those features. Those areas are:

- price
- inventory
- shipping
- image

![Image](https://user-images.githubusercontent.com/5845095/213149246-b1640a0e-b3e2-4b53-bf2d-6099a0b0a642.png)

#### Expected behavior

When the user exits any of those screens, we should send a Tracks event. We also should not forget the `hasChanges` property, which determines if a user edited any data on the screen they exit from.

#### iOS

iOS is not affected by this bug.

**Comment by shiki** [comment]
I think this is intentional. We had discussions in the past about removing the Done buttons. We never got to finish that though.

**Comment by shiki** [comment]
Found the issue: https://github.com/woocommerce/woocommerce-android/issues/3627

I think we only made the changes in Android.

**Comment by wzieba** [comment]
> I think this is intentional.

Are you referring to removing "Done" buttons or to removing tracking events?

I agree with you if you're referring to removing the "Done" buttons. It was intentional, and thanks for the context (I'll change the description of this issue).

If you're referring to removing tracking events, though, I think it was not intentional. We have other events on the screens on Product Details that don't have the "Done" button and still send tracking events when leaving.

E.g. tags screen. We send `woocommerceandroid_product_tag_settings_done_button_tapped` with the property `has_changed_data` when a user exits this screen. This screen doesn't have the "Done" button:

<img width="250" alt="Screenshot 2023-01-23 at 11 11 41" src="https://user-images.githubusercontent.com/5845095/214014244-39713bb1-22db-425e-87eb-c5d880409738.png">

The information if the user exited any Product settings screen with or without changes is IMO crucial for a precise measure of the impact of Simplify Product Editing project. I'd opt to continue with fixing the app and sending events described in the issue.

**Comment by shiki** [comment]
That's true. We should still get those events fixed.
