### ISSUE TITLE
TTP description text gets cut off in smaller devices in landscape mode

### ISSUE THREAD

**Issue by AnirudhBhat** [woocommerce/woocommerce-android#8248]
![landscame_mode_bug](https://user-images.githubusercontent.com/1331230/214502462-1d7f5117-f915-49a3-bfe1-fdaccccfeedb.png)

This happens in the card reader type selection screen.

**Comment by lmischner** [comment]
For reproducing the issue, note that your device needs to have a larger than default text size.

**Comment by Mayuresh0072** [comment]
@AnirudhBhat Hello, I want to work on this issue and contribute.. Please assign me this issue. Thanks

**Comment by rossanafmenezes** [comment]
Hi @Mayuresh0072 !

Thank you for your interest in fixing this. I have assigned the issue to you.

**Comment by dipankarupd** [comment]
Hey. @Mayuresh0072 I would like to know if you are still working on this issue. In case you are not, I would like to work on it.
Thank you

**Comment by Mayuresh0072** [comment]
@dipankarupd yes , go for it.

**Comment by dipankarupd** [comment]
Hey could you please assign this issue to me. I look forward to working on it

**Comment by AnirudhBhat** [comment]
@dipankarupd Thank you for your interest! I've assigned the issue to you.

**Comment by kidinov** [comment]
@dipankarupd sorry, I have made this change in this PR - https://github.com/woocommerce/woocommerce-android/pull/8339
