### ISSUE TITLE
Hide shipping address for virtual products

### ISSUE THREAD

**Issue by nbradbury** [woocommerce/woocommerce-android#826]
Right now we show the shipping address even for virtual products. We should hide the shipping address in this situation.

@kyleaparker Is the above correct? If so I'll file an issue for iOS.

**Comment by kyleaparker** [comment]
>Right now we show the shipping address even for virtual products. We should hide the shipping address in this situation.

Yep this makes sense, if no address is entered in the checkout there is no need to show this section 👍

**Comment by nbradbury** [comment]
[Related iOS issue](https://github.com/woocommerce/woocommerce-ios/issues/705)

**Comment by jkmassel** [comment]
This has already been bumped twice, so I'm removing the milestone for now! :)

**Comment by anitaa1990** [comment]
Based on the comments [here](https://github.com/woocommerce/woocommerce-ios/issues/705#issuecomment-474050203) for the same issue in iOS, it seems there is no way to identify if a product is virtual or not using the fetch order api. We would need to make a separate api call to verify if the product is virtual or as mentioned [here](https://github.com/woocommerce/woocommerce-ios/issues/705#issuecomment-476653337), we could also check the local cache to see if the product is virtual. If so, just hide the shipment tracking. 

cc @AmandaRiu and @nbradbury  on your thoughts here?

**Comment by nbradbury** [comment]
@anitaa1990 We could make a separate call to get the product, but that wouldn't solve the initial problem - the shipping section would still appear until the product is fetched. I'm good with doing what @kyleaparker suggested and leave it visible with "No address specified.' But if we do have the product cached, we can hide this section for virtual products.

**Comment by AmandaRiu** [comment]
> @anitaa1990 We could make a separate call to get the product, but that wouldn't solve the initial problem - the shipping section would still appear until the product is fetched. I'm good with doing what @kyleaparker suggested and leave it visible with "No address specified.' But if we do have the product cached, we can hide this section for virtual products.

Makes sense to me!

**Comment by anitaa1990** [comment]
Thanks for the clarification @nbradbury and @AmandaRiu. I wanted to run by the implementation plan before starting work on this. 

I am assuming that, if there are multiple products for an order and only one of them is virtual, then we still display the shipping card. This would mean iterating through all the `LineItem` in an order and checking if it were a virtual product. I didn't realise that there is no type in `WcOrderModel.LineItem` though. So at the moment, we have to iterate through all the line items in an order, fetch the corresponding product from the `productId` in `LineItem` and then check if it is a virtual product.

This would mean, if there are 10 products, we would iterate 10 times and call the FluxC db 10 times, which seems wasteful. I was thinking of adding a method in FluxC in `WcProductStore` instead. This method would fetch the list of products in local cache and then compare that with the list of `LineItem` passed to the method. That way the db call happens only once and the iteration logic takes place in fluxC. Does that make sense?

**Comment by AmandaRiu** [comment]
>  I was thinking of adding a method in FluxC in WcProductStore instead. This method would fetch the list of products in local cache and then compare that with the list of LineItem passed to the method. That way the db call happens only once and the iteration logic takes place in fluxC. Does that make sense?

I think that makes perfect sense @anitaa1990
