### ISSUE TITLE
[Products List] "Product moved to trash" banner text is partly hidden

### ISSUE THREAD

**Issue by pachlava** [woocommerce/woocommerce-android#8299]
**Describe the bug**
When moving a product to trash, the text in the banner is 50% cut off vertically (same for landscape mode / dark theme):

<img width="362" alt="Screenshot 2023-02-02 at 20 27 14" src="https://user-images.githubusercontent.com/73365754/216415671-89428d8e-15f6-4320-91a9-e4e8da7f3891.png">

Video:

https://user-images.githubusercontent.com/73365754/216413588-fd0a924d-0f1e-4bdc-b89c-acd9dcd96ec2.mp4

**To Reproduce**

0. Make sure you have at least two products
1. Open any product details
2. Trash the product
3. The bottom part of "Product moved to trash" banner text is partly hidden

**Expected behaviour**
Text is fully visible, and the banner is shown at the page bottom. Currently, this happens if it's the last product in products list that is trashed:

https://user-images.githubusercontent.com/73365754/216562399-d35e8f46-bc99-4105-af25-cbbfd2082973.mp4

**Mobile Environment**
- Device: Samsung A31
- Android version: 12
- WooCommerce Android version: 12.1-rc-2

**Comment by pachlava** [comment]
The same is true for the `Status updated!` banner (part of bulk products update process):

<img width="366" alt="Screenshot 2023-02-03 at 13 50 07" src="https://user-images.githubusercontent.com/73365754/216596344-cfa26fa0-8696-47ea-a5b2-3d90ae351d1d.png">

**Comment by 0nko** [comment]
@pachlava I can't reproduce it anymore. Can you please check if you can still see it on your device?

[device-2023-05-08-181620.webm](https://user-images.githubusercontent.com/1522856/236875929-a375ec0d-c2cb-4d77-b047-751044d45a28.webm)

**Comment by pachlava** [comment]
@0nko 👋 

It's not reproducible for me too, with `13.5-rc-1` on `Pixel 7 Android 13` and `Samsung A31 Android 12`. Thanks for the ping! I'm closing the issue. 🙇
