### ISSUE TITLE
[Support Requests] Replace & Clean up

### ISSUE THREAD

**Issue by ThomazFB** [woocommerce/woocommerce-android#8335]
# Task

- [x] Replaces usages of the old form with the new form
- [ ] Remove unused code

**Comment by wzieba** [comment]
hi @ThomazFB 👋 is there any unused code you specifically considered removing?

**Comment by ThomazFB** [comment]
Oh, this was addressed during the last HACK week, I think it's safe to close this issue! Thanks for the reminder @wzieba!
