### ISSUE TITLE
Analytics Hub performance transactions report false results.

### ISSUE THREAD

**Issue by wzieba** [woocommerce/woocommerce-android#8355]
**Describe the bug**

The reason for false reports is that the conditions of transactions are marked as executed prematurely. Let's take e.g. fetching data about Orders.

We run `onOrdersFetched` method as soon as `ordersState` is of type `Available` ([here](https://github.com/woocommerce/woocommerce-android/blob/trunk/WooCommerce/src/main/kotlin/com/woocommerce/android/ui/analytics/hub/AnalyticsHubViewModel.kt#L162)) but the `Available` is a state that this `Flow` starts with ([here](https://github.com/woocommerce/woocommerce-android/blob/trunk/WooCommerce/src/main/kotlin/com/woocommerce/android/ui/analytics/hub/sync/UpdateAnalyticsHubStats.kt#L31)).

So instead of measuring network communication, we only measure how quickly the device renders a default, empty view.

This ends up with measuring not what we really want to measure - an end to end user experience when opening this screen.

**Screenshots**
<img width="1104" alt="image" src="https://user-images.githubusercontent.com/5845095/219686341-d4e02e4f-11d9-45b1-8357-b2e92ddbe13d.png">

**Comment by shiki** [comment]
I don't recall us using the performance metrics anymore. Do we still need it? Should we remove it instead?

**Comment by wzieba** [comment]
We can remove them, but at the same time, we don't remove Tracks events from features we don't currently observe. I find value in keeping performance metrics to be aware of regressions. But if you prefer otherwise, sure we can remove it.
