### ISSUE TITLE
[Support Requests] Update Zendesk SDK version to 5.1.1

### ISSUE THREAD

**Issue by ThomazFB** [woocommerce/woocommerce-android#8358]

**Comment by shiki** [comment]
@ThomazFB Do you remember why this is important to do? What are the benefits?

**Comment by ThomazFB** [comment]
Not important @shiki. It was a reminder to not miss the opportunity to update the Zendesk library since the Support Requests project was dealing with it. But we postponed, the Free Trial project came in and we never did it. I think we can close this.
