### ISSUE TITLE
[REST API] WPCom OTP screen for Jetpack connection

### ISSUE THREAD

**Issue by hichamboushaba** [woocommerce/woocommerce-android#8397]

**Comment by hafizrahman** [comment]
Adding the design from Jetpack app just for reference:
| main | when requesting sms |
| - | - |
| ![photo_2023-03-01_12-07-16](https://user-images.githubusercontent.com/266376/222050544-a7f65a1a-fa04-4cda-b1a0-372123090296.jpg) | ![photo_2023-03-01_12-07-18](https://user-images.githubusercontent.com/266376/222050536-7dff0b20-bc95-4c92-b491-3ea211fb58a7.jpg) |

Meanwhile here's the design from Figma:
<img width="452" alt="Screenshot 2023-03-01 at 12 22 40" src="https://user-images.githubusercontent.com/266376/222052389-866c022e-65a9-46c8-aa51-a29e27f330af.png">
