### ISSUE TITLE
[Product Bundles] Display product bundle information in the product detail screen

### ISSUE THREAD

**Issue by atorresveiga** [woocommerce/woocommerce-android#8402]
Display product bundle information on the product detail screen. We can use wp-admin design as a reference

![Image](https://user-images.githubusercontent.com/18119390/221003655-d8745668-bfcd-4832-b6ce-0fd3a574377b.png)

**Comment by rachelmcr** [comment]
Here's the iOS UI, for reference:

Product list|Product detail|Bundled Products
-|-|-
![Image](https://user-images.githubusercontent.com/8658164/230416521-d7501d4f-09ed-4f12-819e-ed5f48f18145.png)|![Image](https://user-images.githubusercontent.com/8658164/230416540-9b242ff6-911a-4a95-9952-e4b1b5d96864.png)|![Image](https://user-images.githubusercontent.com/8658164/230416552-51971761-a0fc-4cc0-a28f-cd6f36a01c19.png)

Notes:
1. On the product list and product detail > Inventory card, make sure the product stock displays the `bundle_stock_status` or `bundle_stock_quantity` for the product bundle.
2. In the Bundled Products list, everything you need to display is in the API response except the product image, which must be fetched separately.
