### ISSUE TITLE
[Composite Products] Display composite product information in the product detail screen

### ISSUE THREAD

**Issue by atorresveiga** [woocommerce/woocommerce-android#8405]
Display composite product information on the product detail screen. We can use wp-admin design as a reference

![Image](https://user-images.githubusercontent.com/18119390/221009366-7a5b6611-7b9e-465a-9d42-d14e632faea1.png)

**Comment by rachelmcr** [comment]
For reference, here is the discussion about the UI: pe5pgL-2wF-p2

And here's how it was implemented on iOS:

Product detail|Components|Component Settings: Products|Component Settings: Categories|Component Settings: Empty options data
-|-|-|-|-
![Image](https://user-images.githubusercontent.com/8658164/230421215-78d4f909-bb24-4596-ad26-6248fe25a406.png)|![Image](https://user-images.githubusercontent.com/8658164/230420868-b8e49870-d64f-47ab-8f15-0a861384c9ca.png)|![Image](https://user-images.githubusercontent.com/8658164/230420917-28c704fe-bb4e-4092-8286-42c862227597.png)|![Image](https://user-images.githubusercontent.com/8658164/230420934-c1d309a8-eb11-4514-99e4-990591772962.png)|![Image](https://user-images.githubusercontent.com/8658164/230420946-4eeadd47-be75-40a2-9120-dc4d98ddd390.png)


Component Settings: Loading options data




https://user-images.githubusercontent.com/8658164/230421460-3ceb9ca8-d885-4833-9c2a-589532b3a31c.mp4





Notes:
1. On the Components screen, all of the data can be parsed from the product API response.
2. On the Component Settings screen, you need to fetch the information in the Component Options section and the Default Option separately. (The default option is always a product.) The API response includes the option type (products or categories), the option IDs, and the default option ID, which you can use to fetch the options and default option.
3. On iOS I decided to optimistically show the available data for Component Settings right away, while the options data is being fetched (see the screencast above).
4. I'm only fetching images for the product options, not category options (see https://github.com/woocommerce/woocommerce-ios/pull/9374).
