### ISSUE TITLE
UI updates

### ISSUE THREAD

**Issue by samiuelson** [woocommerce/woocommerce-android#8441]
1. Change label of "+ Add product" button to "+ Add products"

**Comment by ParaskP7** [comment]
FYI: @samiuelson I moved the `12.8` milestone to `12.9` in order to proceed with the code freezing process. Do let me know if you still need this issue to be part of the `12.9` release.

**Comment by samiuelson** [comment]
This one is already in trunk and on its way to 12.8 as well.
