### ISSUE TITLE
Designs i7: Show account name instead of username

### ISSUE THREAD

**Issue by AmandaRiu** [woocommerce/woocommerce-android#847]
Update the following areas to use the full user account name instead of the username:

**Current**

Settings:
<img width="350" alt="screen shot 2019-02-26 at 11 18 17 am" src="https://user-images.githubusercontent.com/5810477/53433385-e7129b00-39b9-11e9-9d0b-6be0d6518c5a.png">

Logout Confirmation
<img width="305" alt="screen shot 2019-02-26 at 11 19 02 am" src="https://user-images.githubusercontent.com/5810477/53433451-04e00000-39ba-11e9-9dbf-ca7c7970f670.png">

**Updated designs**
<img width="358" alt="screen shot 2019-02-26 at 11 18 22 am" src="https://user-images.githubusercontent.com/5810477/53433386-e843c800-39b9-11e9-9ffb-9123b79dac77.png">

<img width="300" alt="screen shot 2019-02-26 at 11 19 08 am" src="https://user-images.githubusercontent.com/5810477/53433474-10332b80-39ba-11e9-8390-f43d4f3b240d.png">

**Comment by nbradbury** [comment]
@AmandaRiu I think we're already doing this. These areas are using the `account.displayName`, which is the "public display name"

![screenshot_1551384438](https://user-images.githubusercontent.com/3903757/53595184-98583300-3b6a-11e9-8295-b624cec9341a.png)
 in your WP profile. Perhaps your display name is set to `droidtester2018`?

**Comment by AmandaRiu** [comment]
@nbradbury Ah my bad, I guess I didn't have my display name set up on my account. Closing.
