### ISSUE TITLE
[Free Trial] Add Tracks events for Free Trial creation

### ISSUE THREAD

**Issue by wzieba** [woocommerce/woocommerce-android#8495]
### Description

The added Tracks events should allow us to answer those questions:

> The metrics will be to understand how many users are subscribing to a free trial plan during the store creation flow. How many of them are eventually upgrading to a paid plan from the app? How many of them end their free trial but no longer upgrading to paid plan.

Internal source: pe5pgL-2lN-p2#comment-1944

**Comment by ThomazFB** [comment]
We decided to go by adding the following two Analytics tracks:

1. When the Start your free trial button is clicked (start_free_trial_tapped)
2. When the Free trial store is created (free_trial_store_created)

Internal source: pe5pgL-2zD#comment-2127
