### ISSUE TITLE
Filter out draft and variable products from product list

### ISSUE THREAD

**Issue by samiuelson** [woocommerce/woocommerce-android#8503]
The product list in `ProductSelectorFragment` should not display draft products and variable products with no variations defined. We should show only the products we can actually add to the order.

```[tasklist]
### Tasks
- [ ] `ProductSelectorFragment` should not display draft products
- [ ] `ProductSelectorFragment` should not display variable products with no variations defined.
```

Note: originally found by @jostnes in https://github.com/woocommerce/woocommerce-android/pull/8475#issuecomment-1459997141
![image](https://user-images.githubusercontent.com/4527432/223716592-e40dedaf-2b73-4e03-a8a7-b87994b0fd72.png)

**Comment by ParaskP7** [comment]
FYI: @samiuelson I moved the `12.8` milestone to `12.9` in order to proceed with the code freezing process. Do let me know if you still need this issue to be part of the `12.9` release.

**Comment by samiuelson** [comment]
@ParaskP7 Sorry for the confusion. This feature is merged into the trunk already. I'm closing the issue.
