### ISSUE TITLE
`ProductSelectorFragment` landscape issues

### ISSUE THREAD

**Issue by samiuelson** [woocommerce/woocommerce-android#8505]
When the filter returned no results, the user would need to scroll to view the "clear filter" button, would it be possible to display it on screen without scrolling when in landscape mode (also a UI defect on the header, it's cut off on the top left)?
![image](https://user-images.githubusercontent.com/4527432/223716169-e77da502-9f10-4fd2-a304-680ce11ea5d0.png)

Note: originally added by @jostnes in https://github.com/woocommerce/woocommerce-android/pull/8475#issuecomment-1459997141

**Comment by ParaskP7** [comment]
FYI: @samiuelson I moved the `12.9` milestone to `13.0` in order to proceed with the code freezing process. Do let me know if you still need this issue to be part of the `12.9` release.
