### ISSUE TITLE
[Free Trial] Update the log in / get started screen

### ISSUE THREAD

**Issue by wzieba** [woocommerce/woocommerce-android#8544]
### Description

In scope of this task we should match UI of the very first screen a user can see, to the design presented below:

<img src="https://user-images.githubusercontent.com/198826/227241197-17b25c5c-ce57-4ca2-9f9a-23073c27f63e.jpg" width="400">

**Comment by shiki** [comment]
@ThomazFB Note that we're changing the content of the home screen. Please see pecCkj-mB-p2#comment-227

<img src="https://user-images.githubusercontent.com/198826/227241197-17b25c5c-ce57-4ca2-9f9a-23073c27f63e.jpg" width="400">

**Comment by ThomazFB** [comment]
After discussing internally (p1679608787304799-slack-C02KUCFCSFP), we decided to keep the changes here to a bare minimum and just modify the view center text message and get started button while keeping the other login buttons text as it is.

CC: @shiki

**Comment by shiki** [comment]
Updating just the prologue was my original thought. Sorry that wasn't clear. :)
