### ISSUE TITLE
`ProductSelectorViewModel` issue when we filter the product, for a few seconds, we display the "no orders" screen and then load the products. This seems to be present in the coupons screen as well.

### ISSUE THREAD

**Issue by samiuelson** [woocommerce/woocommerce-android#8566]
https://user-images.githubusercontent.com/1331230/225545288-641d99d8-b68e-4459-ad75-09274f691c57.mp4

**Comment by ParaskP7** [comment]
FYI: @samiuelson I moved the `12.9` milestone to `13.0` in order to proceed with the code freezing process. Do let me know if you still need this issue to be part of the `12.9` release.
