### ISSUE TITLE
Add UI for most popular products

### ISSUE THREAD

**Issue by AnirudhBhat** [woocommerce/woocommerce-android#8570]
This task aims to add a UI for displaying the most popular products in the product selection screen. 

This task is not about integrating the UI with the business logic. It's just about adding a UI.

For more context: pdfdoF-2ud-p2

**Comment by ParaskP7** [comment]
FYI: @AnirudhBhat I moved the `13.0` milestone to `13.1` in order to proceed with the code freezing process. Do let me know if you still need this issue to be part of the `13.0` release.

**Comment by ParaskP7** [comment]
FYI: @AnirudhBhat I moved the `13.1` milestone to `13.2` in order to proceed with the code freezing process. Do let me know if you still need this issue to be part of the `13.1` release.

**Comment by AnirudhBhat** [comment]
@ParaskP7 I apologize for not updating the ticket. The task has already been merged to trunk. Closing the issue

https://github.com/woocommerce/woocommerce-android/pull/8685
