### ISSUE TITLE
Add UI for recently sold products

### ISSUE THREAD

**Issue by AnirudhBhat** [woocommerce/woocommerce-android#8571]
This task aims to add a UI for displaying the recently sold products in the product selection screen.

This task is not about integrating the UI with the business logic. It's just about adding a UI.

For more context: pdfdoF-2ud-p2

**Comment by ParaskP7** [comment]
FYI: @AnirudhBhat I moved the `13.0` milestone to `13.1` in order to proceed with the code freezing process. Do let me know if you still need this issue to be part of the `13.0` release.

**Comment by ParaskP7** [comment]
FYI: @AnirudhBhat I moved the `13.1` milestone to `13.2` in order to proceed with the code freezing process. Do let me know if you still need this issue to be part of the `13.1` release.

**Comment by ParaskP7** [comment]
FYI: @AnirudhBhat I moved the `15.1` milestone to `15.2` in order to proceed with the code freezing process. Do let me know if you still need this issue to be part of the `15.1` release.

**Comment by AnirudhBhat** [comment]
@ParaskP7 I'm closing this issue since it's already been taken care of. 

ps: I'm on parental leave. I'll take a look later today if there are any other issue on my name and comment on those tickets so that it'll be easy for you. Thank you!
