### ISSUE TITLE
[Free Trial] Address shortcuts and increase code coverage

### ISSUE THREAD

**Issue by wzieba** [woocommerce/woocommerce-android#8574]
### Description

During the implementation of the first milestone, we made a few shortcuts (code-wise) and did not assert the proper code coverage. This task addresses both issues.

**Comment by ThomazFB** [comment]
Just to keep track, some improvements towards this issue goal have been achieved in the `UpgradesViewModel` through https://github.com/woocommerce/woocommerce-android/pull/8607 and https://github.com/woocommerce/woocommerce-android/pull/8617

**Comment by wzieba** [comment]
I see we increase code coverage continuously in PRs for tasks from Scope D. I think we don't need a separate task for this. I'll close this now, but if you prefer us to keep it open, please feel free to re-open @ThomazFB !
