### ISSUE TITLE
[Free Trial] [Test Plan Request] Correctly pluralize Free Trial remaining days message

### ISSUE THREAD

**Issue by ThomazFB** [woocommerce/woocommerce-android#8587]
Summary
==========
When there is 1 day left for a trial it says 1 days instead of 1 day both in the banner and in the upgrades view

![Image](https://user-images.githubusercontent.com/5920403/226222232-96944c63-6f19-4e8b-814e-ed697213c9e3.png)

**Comment by shiki** [comment]
This also happens in the Upgrades screen. 



<img src="https://user-images.githubusercontent.com/198826/226440019-6a277244-3592-4808-b5dd-02ecf00a19b4.png" width="300">
