### ISSUE TITLE
[Free Trial] [Test Plan Request] Adjust Free Trial banner behavior when offline

### ISSUE THREAD

**Issue by ThomazFB** [woocommerce/woocommerce-android#8592]
Summary
==========
If a merchant is viewing a Free Trial site without internet connectivity, and they tap on the Upgrade Now link/button, on returning to the app, the banner no longer appears even though they weren't able to upgrade.

**Comment by wzieba** [comment]
I think we should not show the "Trial banner" if a user is offline. WDYT?

**Comment by shiki** [comment]
@wzieba That sounds like a good idea. :) 

What does iOS do (or plan to do), @Ecarrion?

**Comment by wzieba** [comment]
For now, iOS will stack both banners but in iteration 4, we'll adjust it to match Android. Context: p1678891202089759/1678853193.765609-slack-C02KUCFCSFP
