### ISSUE TITLE
Notifications: Have the ability to change the Cha-Ching push notification sound to something else

### ISSUE THREAD

**Issue by stuartduff** [woocommerce/woocommerce-android#8656]
I've had a customer asking if it would be possible to implement a feature where they could change the sale notification sound to something different than the default "Cha-Ching". Therefore, I'm adding it as a feature request to be considered over time for a future app update.

Ref: 6072569-zen

**Comment by hichamboushaba** [comment]
@stuartduff this is already supported in the app:

1. Open the app's settings.
2. Click on "Manage notifications"
3. This should open the notification settings of the app (system screen).
4. Choose the "New order" category.
5. Click on the "Sound" entry.
6. Select a different sount.
