### ISSUE TITLE
Add Tracks

### ISSUE THREAD

**Issue by hafizrahman** [woocommerce/woocommerce-android#8702]

**Comment by ParaskP7** [comment]
FYI: @hafizrahman @0nko I moved the `13.1` milestone to `13.2` in order to proceed with the code freezing process. Do let me know if you still need this issue to be part of the `13.1` release.

**Comment by 0nko** [comment]
Thanks! It's actually already merged to another branch, which will get merged in 13.1. I'll update the issue and close it.
