### ISSUE TITLE
Add events to track products selected from popular and recent sections

### ISSUE THREAD

**Issue by AnirudhBhat** [woocommerce/woocommerce-android#8716]
The goal of this task is to add an event/property to track adding products from the popular or recent sections. 

Event: `product_selector_confirm_button_tapped`
Property: `{"source" : "["popular", "recent", "other"]"}`

More info: pdfdoF-2A0-p2

**Comment by ParaskP7** [comment]
FYI: @AnirudhBhat I moved the `13.1` milestone to `13.2` in order to proceed with the code freezing process. Do let me know if you still need this issue to be part of the `13.1` release.

**Comment by AnirudhBhat** [comment]
@ParaskP7 I apologize for not updating the ticket. The task has already been merged to trunk. Closing the issue

https://github.com/woocommerce/woocommerce-android/pull/8738
