### ISSUE TITLE
[Free Trial] WooCommerce logo gets cutoff in Google Pixel 3

### ISSUE THREAD

**Issue by shiki** [woocommerce/woocommerce-android#8727]
<img src="https://user-images.githubusercontent.com/198826/229643084-5a56361e-ac94-4747-8cc3-7c657908bfc0.png" width="300">

**Comment by shiki** [comment]
@ThomazFB @wzieba This may be good to fix earlier.

**Comment by ThomazFB** [comment]
@wzieba do you have the availability to look at it?  Sorry to ask you this since I'm the one who introduced the problem in https://github.com/woocommerce/woocommerce-android/pull/8641, but since I already started the summary as our highest priority task, it would be great if can tackle this.

**Comment by wzieba** [comment]
I've tried to fix this issue today, unfortunately, I haven't found a solution in my timebox. As I'm going AFK, I'll unassign myself from this task for now.

### Notes 

I've noticed that it's present when a user uses a 2- or 3-button navigation (no hand gestures)

| Gesture navigation | 3-buttons navigation |
| --- | --- |
| <img width="603" alt="Screenshot 2023-04-04 at 18 48 10" src="https://user-images.githubusercontent.com/5845095/229861505-b61f3aa6-abbb-4249-90c7-d7e87ab0a306.png"> | <img width="603" alt="Screenshot 2023-04-04 at 18 47 48" src="https://user-images.githubusercontent.com/5845095/229861523-cbc9f136-44d6-4f80-a35b-43083ca576b9.png"> |
