### ISSUE TITLE
Variable Subscriptions cannot be chosen anymore

### ISSUE THREAD

**Issue by joashrajin** [woocommerce/woocommerce-android#8730]
**Describe the bug**

AFAIK, WC Subs isn't supported, but as of v12.8 - something seems to have changed with the way variable subscription products are shown in the app. 
When you add a Variable Subscription product to an order, it is treated as a simple product, and you aren't allowed to choose the variation. 

**To Reproduce**
1. Ensure you have a variable subscription set up
2. Open the app and add it to an order
3. Notice how it treats it as a simple product and does not allow you to choose the variation
4. Compare the way it works on the iOS app (that is how it was working previously)

**Screen Recordings**

Behaviour on iOS v13.0:

https://user-images.githubusercontent.com/16253818/229715802-aedc790e-008a-4da5-9688-a28db61493e7.MP4

Behaviour on Android v13.0-rc-1

https://user-images.githubusercontent.com/16253818/229716017-f685557e-c7a1-4eef-8537-bbce269404ea.mp4

**Expected behavior**

**Isolating the problem (mark completed items with an [x]):**
- [x] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce and WC Subs is active.
- [x] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [x] I can reproduce this bug consistently using the steps above.

**Mobile Environment**
Please include:
- Device: Samsung S21 FE
- Android version: 13
- WooCommerce Android version: 13.0 rc-1

Reported in 6171208-zd-woothemes

**Comment by joashrajin** [comment]
Here's another related issue which I reported for iOS: https://github.com/woocommerce/woocommerce-ios/issues/9157

In that case, it was due to the fact that Subscription Products were still possible to choose when creating an order. I was told that this should not be the case since WCSubs isn't supported yet

**Comment by azollafox** [comment]
Our user let us know they used to be able to do this, but haven't in the update:

>When ordering a product with variations was working till last week’s Android version update, I think there maybe a inadvertent change to not let the user choose the variation of the product they want when adding a product to an order.. This is not a new feature request.

**Comment by hafizrahman** [comment]
Sorry I haven't had a chance to take a deeper look yet. But if you're sure the issue starts from v.12.8, here's a list of added items for that version:

https://github.com/woocommerce/woocommerce-android/milestone/146?closed=1

Perhaps anything catches your attention there that might be relevant?

**Comment by samiuelson** [comment]
The fix is merged and will be included in the upcoming 13.2 release. cc @joashrajin @azollafox
