### ISSUE TITLE
[REST API] JP connection edge case: Handle sites with JCP

### ISSUE THREAD

**Issue by hafizrahman** [woocommerce/woocommerce-android#8732]
Edge case:

1. Initially site has no Jetpack or other plugins with Jetpack Connection Package
2. user logs in to app via REST API
3. in wp-admin, user installs a plugin with Jetpack Connection Package and connected their account
4. back in the app, user wants to install JP via jetpack benefits dialog
5. At the moment, the app will start over with the JP install process, which is not accurate.

We should handle it by checking if site has plugin with JCP, in which case we should move the flow to the existing install JP via Jetpack Connection Package flow.

IT'S WORTH TO CHECK IF A USER WITH ALREADY JCP CONNECTED, COULD JUST INSTALL JETPACK TO ENABLE PUSH NOTIFICATIONS WITHOUT THE NEED TO RECONNECT THE ACCOUNT

**Comment by hichamboushaba** [comment]
I'm just checking the backlog, and the goal of the issue is not clear to me, the Jetpack benefits dialog is meant to bring all of the app's features, so having JCP or not is not relevant, we want the user to install Jetpack the plugin itself, am I missing something?
