### ISSUE TITLE
Notifications: Can't email customer from an order notification detail

### ISSUE THREAD

**Issue by rachelmcr** [woocommerce/woocommerce-android#874]
**Describe the bug**

If you get a notification about a new order, and view the order details in the Notifications tab, the email icon in the customer information section doesn't do anything. You have to go to the order details in the Orders tab to get that email icon to work.

**To Reproduce**
1. Get a new order in your store.
2. Open the Notifications tab.
3. Tap the "You have a new order!" notification to open the order details.
4. Scroll down to the Customer information section.
5. Tap "Show billing" to see the customer's full details.
6. Next to the customer's email address, tap the email icon. Result: The icon is highlighted but nothing else happens.
7. Open the Orders tab.
8. Tap the same order to open the order details.
9. Scroll down to the Customer information section.
10. Tap "Show billing" to see the customer's full details.
11. Next to the customer's email address, tap the email icon. Result: The email app opens to send an email to that customer.

**Expected behavior**

I expect the email icon to work the same in both places (Notifications and Orders tabs).

**Isolating the problem (mark completed items with an [x]):**
- [ ] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [ ] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [x] I can reproduce this bug consistently using the steps above.

**Mobile Environment**
Please include:
- Device: moto e5 play
- Android version: 8.1.1
- WooCommerce Android version: 1.3-rc-2

h/t to a beta tester who submitted this bug report, happening on their DTEK60 (argon), Android 6.0, WCAndroid 1.3-rc-2

**Comment by nbradbury** [comment]
I can repro this. The email client is launched when the order is shown from the order list, but not when it's shown from the notifications list.
