### ISSUE TITLE
[Free Trial] Add track events when a store times out or is out of sync

### ISSUE THREAD

**Issue by wzieba** [woocommerce/woocommerce-android#8742]
### Description

We should send a Track event if a user experiences the time-out error during site creation.

Also, let's add a separate event when the user experiences out-of-sync behavior.

Internal context: pe5pgL-2Cd-p2#comment-2204

**Comment by Ecarrion** [comment]
Heads up: [these are the events](https://github.com/woocommerce/woocommerce-ios/pull/9417) implemented on iOS
