### ISSUE TITLE
Improve the UI in the product selector screen

### ISSUE THREAD

**Issue by AnirudhBhat** [woocommerce/woocommerce-android#8750]
Improve the UI in the product selector screen which is visible when we go back from search results to the base product list. Please refer to the video for a better understanding.

https://user-images.githubusercontent.com/1331230/230097071-f3ac1d45-b905-4c05-af48-a655d20f1910.mp4

**Comment by malinajirka** [comment]
@AnirudhBhat Could you please elaborate on the proposal - I don't anything wrong on the video 😕.

**Comment by AnirudhBhat** [comment]
@malinajirka I believe it's the display of shimmer that gets shown for a split second after canceling the search. Samuel suggested [here](https://github.com/woocommerce/woocommerce-android/pull/8685#pullrequestreview-1372852800) that it looks like some kind of UI glitch because it happens so fast.

**Comment by malinajirka** [comment]
Ohh I see, thanks for the clarification! I've added a "good first issue" tag as I believe a good enough fix would be adding +-200ms minimal time interval for which we show the shimmer effect.

**Comment by backwardstruck** [comment]
I was not able to reproduce and @AnirudhBhat confirmed the same so it looks like this has already been fixed.
