### ISSUE TITLE
Help > View Application Logs: update text

### ISSUE THREAD

**Issue by mindgraffiti** [woocommerce/woocommerce-android#876]
Per the My Store & Offline i7 Designs, update text to be uniform with the other destructive button styles. Change `Clear old activity logs` to `Reset Activity Log` (note the use of Title Case)

**Comment by nbradbury** [comment]
Looks like the iOS application log is much different than on Android. On Android we only maintain the current log, so there's no button to reset old logs.

Old iOS screenshot for reference:

<img width="584" alt="Screen Shot 2019-03-10 at 2 40 48 PM" src="https://user-images.githubusercontent.com/3903757/54089765-e7f4e680-4342-11e9-9060-bbcd84da0223.png">

**Comment by mindgraffiti** [comment]
Oops. Apologies, I forgot that Android has a single activity log. The only reason WCiOS has multiple days' worth of logs is because the code was stolen/taken/borrowed from the WordPress-iOS activity log. Closing since the issue doesn't exist for Android.
