### ISSUE TITLE
[Prologue screen] The "Get started" is adjacent to the bottom border

### ISSUE THREAD

**Issue by pmusolino** [woocommerce/woocommerce-android#8837]
In the prologue screen, the "Get Started" button is positioned adjacent to the bottom border of the screen.

<img src="https://user-images.githubusercontent.com/495617/232495870-fd968180-9da2-4bcf-a937-30c522102fd8.jpg" width=300 />

**Comment by Hitoli** [comment]
can I work on this issue?

**Comment by pmusolino** [comment]
@Hitoli, yes, feel free to jump on this issue.

**Comment by backwardstruck** [comment]
Assigning myself this one unless there is already a branch in progress.

**Comment by backwardstruck** [comment]
It looks like this was already fixed actually:

![Screenshot_20240109_160024](https://github.com/woocommerce/woocommerce-android/assets/947561/7bfc5721-6702-4f69-8d47-eaa55c9c50e8)
