### ISSUE TITLE
Inconsistent states for launch store task

### ISSUE THREAD

**Issue by JorgeMucientes** [woocommerce/woocommerce-android#8846]
**Describe the bug**
There's currently a backend issue where a site can result in having the following state: 
- `"blog_public": 1,` (Where 1 = site being public)
- `"launch_status": "unlaunched"`

Among other things, this will lead to having public sites displaying "Launch your site" task from the onboarding list as pending. Note the problem is not specific to mobile, it happens in both the web and the mobile apps. We are getting negative feedback in the app regarding this issue though:
- `It's saying my store isn't published. Yet it is. It made me panic thinking something happened. In attempts to publish it via your button it states it's already published. Yet, it won't change and reflect that. Which means to me bugs. May need to look at what's going on. Thanks for the Sunday funday panic. All is well. So I'm good. Otherwise app works nice!`
- `My store is public, however your app wizard says it still needs to be published so I think you have a bug.`

Since the backend fix might take a while to get fixed we intend to release a workaround to mitigate the impact of this bug in the apps. 

Additional context and discussion can be found here: p1681200289275869-slack-CNA89KY6M

**To Reproduce**
1. Create a site `public`. To do that trigger a POST request to https://public-api.wordpress.com/rest/v1.1/sites/new endpoint setting the field "public": 1, (1 = public).
2. Upgrade the site to the eCommerce plan
3. Check the "Launch store" task is displayed as if there store wasn't already launched. 

**Screenshots**

![Screenshot 2023-04-14 at 13 46 48 (1)](https://user-images.githubusercontent.com/2663464/232788136-b46fffe8-00fb-4e03-8c11-c537fe9bc0ac.png)

![Screenshot 2023-04-14 at 13 37 30 (1)](https://user-images.githubusercontent.com/2663464/232788150-b903d2a6-4595-4a98-8cf6-e0d69e549384.png)

**Expected behavior**
Under the scenario described earlier, the mobile apps should show the "Launch store" tasks within the onboarding list as completed.

**WordPress Environment**
This is a problem only related to WP.com sites.

**Comment by spencertransier** [comment]
@JorgeMucientes I closed this issue since it was added to the 13.2 milestone and the #8847 PR was merged into `release/13.2`. Just wanted to let you know in case there is more work to be done here.

**Comment by JorgeMucientes** [comment]
Thanks for the ping @spencertransier. Nothing else to do. So, good call on closing it 👍🏼
