### ISSUE TITLE
[Free Trial] Add default avatar on Non Jetpack sites

### ISSUE THREAD

**Issue by Ecarrion** [woocommerce/woocommerce-android#8851]
# Description

The new hub menu design does not look good when the site is a non-jetpack site. 

![Image](https://user-images.githubusercontent.com/562080/233095586-9dce3dd2-1b6e-4705-9cdf-84819d9503cd.png)

# Tasks

- [ ] Add default avatar icon next to the store name.
- [ ] Hide the "Chevron-down" icon

**Comment by wzieba** [comment]
This is how it looks currently on Android:



<img width=300 src=https://user-images.githubusercontent.com/5845095/233117037-9bb75f7e-3d1f-4ddf-b184-3a843e0a2dc1.png>

@ThomazFB I'll leave this task to you as you work on the whole redesign, so I don't want to interfere. Is that ok?
