### ISSUE TITLE
Stats bar height is way off

### ISSUE THREAD

**Issue by nbradbury** [woocommerce/woocommerce-android#891]
A user reported that the height of bars in the stats chart is incorrect. The screenshot below shows the stats in the app vs the web. As you can see, the 2019 bar is **much** shorter than it should be.

![screenshot_20190307-084949](https://user-images.githubusercontent.com/3903757/54028394-d230c700-4172-11e9-9312-1a9fee7e31ad.png)

**Comment by jkmassel** [comment]
I'm cutting the `1.5` release today, but let me know if we need a hotfix release for this! 🙂
