### ISSUE TITLE
[Privacy Choices] Get synced "Analytics" value for banner

### ISSUE THREAD

**Issue by Ecarrion** [woocommerce/woocommerce-android#8947]
# Task

- [ ] Before presenting the banner we should fetch the latest state of the [`me/settings`](https://href.li/?https://developer.wordpress.com/docs/api/1.1/post/me/settings/) endpoint in order to honor the current merchant choice

- [ ] Make sure we start/stop allowing tracks events according to that initial sync.

**Comment by wzieba** [comment]
> Before presenting the banner we should fetch the latest state of the [me/settings](https://href.li/?https://developer.wordpress.com/docs/api/1.1/post/me/settings/) endpoint

When the application is opened, we already trigger the latest state of `me/settings` - I believe there's no need to duplicate this call. WDYT?

**Comment by Ecarrion** [comment]
> > Before presenting the banner we should fetch the latest state of the [me/settings](https://href.li/?https://developer.wordpress.com/docs/api/1.1/post/me/settings/) endpoint
> 
> When the application is opened, we already trigger the latest state of `me/settings` - I believe there's no need to duplicate this call. WDYT?

Agree!
