### ISSUE TITLE
[Privacy Choices] Adjust to improved design

### ISSUE THREAD

**Issue by wzieba** [woocommerce/woocommerce-android#9010]
### Description

In scope of this ticket:
- change layout margins/font types and sizes
- introduce new row "Privacy and Cookie Polices"
- introduce new screen "Privacy and Cookie Polices" with clickable elements

![Image](https://user-images.githubusercontent.com/5845095/237622111-b8e5be98-d92a-4611-8d28-b656c32d28f8.png)

**Comment by Ecarrion** [comment]
Hey @wzieba, just a quick note that the latest designs have a new **Usage Tracker** option. 


![Image](https://github.com/woocommerce/woocommerce-android/assets/562080/a2f64389-f00e-4bf8-bb9e-51c1c66068f1)

Here is the iOS counterpart https://github.com/woocommerce/woocommerce-ios/issues/9702

**Comment by wzieba** [comment]
Thank you @Ecarrion 🙌 great awareness, I'll adjust the PR ASAP
