### ISSUE TITLE
Back button shouldn't log users out

### ISSUE THREAD

**Issue by jkmassel** [woocommerce/woocommerce-android#904]
**Describe the bug**
When pressing the "back" button, it's possible to go so far back that you log yourself out of the app.

**To Reproduce**
1. Log into the app using a username and password
2. Tap the "orders" tab
3. Press back – you'll now be back in the login flow and will no longer be logged in

**Screenshots**
![mobizen_20190312_112144 mp4](https://user-images.githubusercontent.com/1123407/54222758-ac315c80-44bb-11e9-9f54-7207360ddd08.gif)

**Expected behavior**
I'd expect that I can't go back farther than the first screen I see after login.

**Isolating the problem (mark completed items with an [x]):**
- [x] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [x] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [] I can reproduce this bug consistently using the steps above.

**Mobile Environment**
Please include:
- Device:  Galaxy S9
- Android version: P
- WooCommerce Android version: 1.4 

**WordPress Environment**
Not Applicable

**Comment by AmandaRiu** [comment]
@jkmassel were you ever able to figure out how to reliably replicate this issue? I've tried on several devices using regular login and google login and am unable to get the app to log me out using the back button.

**Comment by jkmassel** [comment]
I wasn't! I suspect it may have something to do with first launch after upgrading, but without a version to update to, I'm a little stuck. Feel free to mark low-priority and I can try to replicate it on the next cycle?

**Comment by AmandaRiu** [comment]
Ok, I'll do that. Thanks @jkmassel

**Comment by AmandaRiu** [comment]
@jkmassel just a reminder this ticket is still open

**Comment by nbradbury** [comment]
Closing this as its not reproducible.
