### ISSUE TITLE
[UI Tests] Move all test data for real API e2e tests to a single file.

### ISSUE THREAD

**Issue by pachlava** [woocommerce/woocommerce-android#9142]
Move all test data for real API e2e tests to a single file.

**Comment by ParaskP7** [comment]
FYI: @pachlava I moved the `15.1` milestone to `15.2` in order to proceed with the code freezing process. Do let me know if you still need this issue to be part of the `15.1` release.

**Comment by pachlava** [comment]
Oh, thank you, @ParaskP7, and sorry for making you adjust the milestone. I totally lost the track of this task... 🤦
