### ISSUE TITLE
Update the "Cancel" button in the Domain purchase view

### ISSUE THREAD

**Issue by pmusolino** [woocommerce/woocommerce-android#9217]
It's unclear why we display the button "Cancel" to dismiss the Domain purchase view under the Onboarding list. It would be better to show a button "Done" on the top right side of the view.

**Comment by hichamboushaba** [comment]
This is not applicable to Android, we use a back button there, which seems a good choice, can you confirm @pmusolino?

<img width=320 src="https://github.com/woocommerce/woocommerce-android/assets/1657201/2fbcba15-d042-4ba2-a6b6-ff8c9b94fbf8"/>

**Comment by pmusolino** [comment]
@hichamboushaba sounds good, we can do the same on iOS, or follow what I mentioned in this issue if the view is presented modally.

**Comment by hichamboushaba** [comment]
@pmusolino this is already fixed in iOS in https://github.com/woocommerce/woocommerce-ios/pull/10091.

I'll close this issue for Android too.
