### ISSUE TITLE
[REST API] Incorrect endpoint used for checking Jetpack installation status

### ISSUE THREAD

**Issue by hafizrahman** [woocommerce/woocommerce-android#9397]
### Description:
WooCommerce 7.9+ added `/jetpack/v4/connection/data/` endpoint as part of the Jetpack Connection Package effort. This has a undesired side-effects, since the Android app uses this endpoint to determine whether Jetpack is installed on the side. The app expects 404 code to be returned when Jetpack is not installed, however, the endpoint on Woo 7.9+ returns an answer.

The iOS uses `/wp/v2/plugins/jetpack/jetpack` endpoint to determine if Jetpack is installed.

For the moment, there's an existing workaround on the backend side which returns 404 for mobile requests when full Jetpack plugin is NOT installed. Ideally, we’d remove this workaround after we update the Android app.

More context in peaMlT-7P-p2

**Comment by malinajirka** [comment]
Hicham brought a good point that `/wp/v2/plugins` might be available only to admin users. We might want to double check if that's the case and consider how we can ensure the app continues working for shop managers.
