### ISSUE TITLE
Jetpack AI: Improve prompts to make better use of delimiters

### ISSUE THREAD

**Issue by hafizrahman** [woocommerce/woocommerce-android#9399]
The current prompts in the app needs to be reviewed and updated to make proper use of delimiters as outlined in the OpenAI documentation:

https://platform.openai.com/docs/guides/gpt-best-practices/tactic-use-delimiters-to-clearly-indicate-distinct-parts-of-the-input

**Comment by ghyaud** [comment]
A great content niche mirroring this that no-one hit on yet is how to test if the output from context is being biased by the underlying model. For example, I'm adding context from Carl Jung's books to the Davinci Model to try and understand his writing better, but many of his ideas are not politically correct and I can't tell when the model is 'self-censoring.' I think this will be a growing problem with pretrained models and many of the more interesting use cases.

**Comment by JorgeMucientes** [comment]
Closing this, as it doesn't seem to provide any clear improvements in the prompts and and prevents us from using Kotlin multiline strings. Full discussion here: p1699267681106779-slack-C03L1NF1EA3
