### ISSUE TITLE
With 1.5-rc-1 version it isn't possible to fulfill orders (change the order status from "processing" to "completed")

### ISSUE THREAD

**Issue by grigorijurasov** [woocommerce/woocommerce-android#942]
**Describe the bug**
With 1.5-rc-1 version it isn't possible to fulfill orders (change the order status from "processing" to "completed")

Reported in 1914823 zen

**To Reproduce**
1. Install 1.5-rc-1 on Android simulator (using an actual device should result in same results)
2. Log in, head to "Orders"
3. Select any order with "Processing" label/status
4. Click "Fulfill order"
5. Click "Mark order as complete"
6. Nothing happens.

**Screenshots**

![Screenshot](https://cld.wthms.co/nuYsnp+)
Screenshot direct link: https://cld.wthms.co/nuYsnp

I see this in both my own and customer's app log:

>[Mar-28 08:17 UTILS i] 🔵 Tracked: orders_list_loaded, Properties: {"status":"processing","is_loading_more":false,"blog_id":152453224,"is_wpcom_store":false}

**Expected behavior**
I expected the order status to change to "Completed" both in the app and on the site.
**Isolating the problem (mark completed items with an [x]):**
- [x] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [x] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [x] I can reproduce this bug consistently using the steps above.

**Mobile Environment**
Please include:
- Device: Android simulator Google Pixel 2
- Android version: 8.0.0
- WooCommerce Android version: 1.5-rc-1

**WordPress Environment**
<details>
```
Copy and paste the system status report from **WooCommerce > System Status** in WordPress admin.
```
</details>

**Comment by nbradbury** [comment]
Closed via #943
