### ISSUE TITLE
[Scan to Pay] Scan to Pay option not formatted for RTL languages

### ISSUE THREAD

**Issue by lmischner** [woocommerce/woocommerce-android#9429]
**Describe the bug**
When the app language is set to Arabic (or another RTL language), the "Scan to Pay" payment option is both still in English and not properly formatted.

**To Reproduce**
1. Set app language to Arabic
2. Start simple payment
3. On collect payment screen, note that Scan to Pay is the only option both not in Arabic and that is left-justified

**Screenshots**
![Screenshot_20230717-134328](https://github.com/woocommerce/woocommerce-android/assets/103850310/1f573d7f-e2eb-47a2-89dc-dd66c740e978)

**Expected behavior**
Even if the string hasn't been translated yet (should it be by this point?), it should follow the proper formatting at least

**Isolating the problem (mark completed items with an [x]):**
- [x] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [x] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [X] I can reproduce this bug consistently using the steps above.

**Mobile Environment**
Please include:
- Device: Pixel 7
- Android version:  13
- WooCommerce Android version: 14.3

**Comment by kidinov** [comment]
@lmischner 

I may think that this is not a bug. "Scan To Pay" was not translated to Arabic, probably because it was decided that its a "name". Not LTR languages are written as they are even in RTL mode. It looks like that not much we can do, maybe only consider translating "Scan To Pay" to Arabic?

**Comment by lmischner** [comment]
My understanding is that, even if the string isn't translated yet, it should still follow RTL formatting. You can see we do this for iOS:
<img src="https://github.com/woocommerce/woocommerce-android/assets/103850310/8e5b92e1-2fbf-4f57-afd8-96864dd3c07d" width=250px>


I think you're right, though, that the better fix would be to translate it. Do we track those requests in Github or elsewhere?

**Comment by kidinov** [comment]
@lmischner

I looked into this again and found out that you are right - that should go on the right, even with nonarabic text. I changed the layout so it'll behave correctly now -  https://github.com/woocommerce/woocommerce-android/pull/9556
