### ISSUE TITLE
[Shipping & Tax] Can't activate new service package for shipping label

### ISSUE THREAD

**Issue by rachelmcr** [woocommerce/woocommerce-android#9486]
On Android, new service packages can't be activated while creating a shipping label:

1. Start creating a new shipping label for an order
2. On the "Packaging details" step, go to the selected package and select "Create new package."
3. Switch to the Service Package tab and select a new service package.
4. Tap "Done" and notice that nothing happens.

It doesn't seem to matter if you already have other service packages activated yet; any time you try to activate a new service package, nothing happens. Creating new custom packages works as expected.

I don't see anything in the logs related to the issue.

**Comment by Ecarrion** [comment]
@rachelmcr is this still relevant within the new shipping labels project?

**Comment by rachelmcr** [comment]
🤔 I think it will still be relevant, at least for now, because we'll be using the legacy endpoint for getting packages. That said, I'm not sure what the cause was for this behavior so it might not be an issue in the new flow.

At the very least we should include this as a test case in the test plan.

**Comment by Ecarrion** [comment]
> At the very least we should include this as a test case in the test plan.

Agree

Let's close this(since I don't think we will be working on it at least for now) and make sure it is included in the test plan.
