### ISSUE TITLE
Dashboard stats refresh too often

### ISSUE THREAD

**Issue by nbradbury** [woocommerce/woocommerce-android#951]
Right now the dashboard stats refresh whenever you return to them, which means any time the user switches tabs and then switches back to the dashboard they end up seeing the loading skeletons.

We may be fine refreshing the data, but we shouldn't be showing skeletons in this situation. Instead, we should show skeletons only at startup or when the user performs a pull-to-refresh.

@kyleaparker Does this sound good to you?

**Comment by AmandaRiu** [comment]
> This sounds good to me, but will the data still be correct when they return to the dashboard?
@kyleaparker technically no, since the data would not be refreshed every time the tab is loaded. We could instead opt to refresh this view, but do so silently and not while showing loading skeletons...so that new data just replaces the current data.

**Comment by kyleaparker** [comment]
> We could instead opt to refresh this view, but do so silently and not while showing loading skeletons...so that new data just replaces the current data.

👍 sounds like that could work

**Comment by nbradbury** [comment]
> We could instead opt to refresh this view, but do so silently and not while showing loading skeletons...so that new data just replaces the current data.

I updated PR #955 to include this.

**Comment by AmandaRiu** [comment]
This was fixed in #955 . Closing
