### ISSUE TITLE
Login with username instead of email error

### ISSUE THREAD

**Issue by AmandaRiu** [woocommerce/woocommerce-android#952]
In certain (probably rare) circumstances, a user logging into wpcom with their email address might encounter an error prompting them to "log in using your WordPress.com username instead of your email address". Since we don't allow a username login in the wpcom flow, its not obvious to a user what to do next.

We should be checking for `email_login_not_allowed` for the type of error and perhaps send the user to the self-hosted flow with the site set to "wordpress.com".

iOS has already fixed this issue in this PR: https://github.com/wordpress-mobile/WordPressAuthenticator-iOS/pull/42

**Comment by nbradbury** [comment]
Closed via #991
