### ISSUE TITLE
Store Creation: the keyboard is displayed when the user should select the selling category

### ISSUE THREAD

**Issue by pmusolino** [woocommerce/woocommerce-android#9537]
In the store creation flow, we display the keyboard when the user should press the category where they sell. It doesn't make sense to display the keyboard here, and it would be great to now show it.

<img src="https://github.com/woocommerce/woocommerce-android/assets/495617/dceb6878-12d0-4ff5-a8ff-b0ed3c376dc3" width=300 />

**Comment by hafizrahman** [comment]
This is not happening anymore in my checks, not sure which PR fixed it but will close the issue for now. Happy to re-open and check again if there's another report.
