### ISSUE TITLE
Product description generation with AI: an empty title will generate inaccurate description

### ISSUE THREAD

**Issue by pmusolino** [woocommerce/woocommerce-android#9538]
When attempting to generate a product description using AI, providing only a description and omitting the title results in an inaccurate output.

Additionally, shouldn't we make the title field visible on this screen, similar to how it is on iOS, and require it to be filled out?

<img src="https://github.com/woocommerce/woocommerce-android/assets/495617/01086f8a-d2d0-4108-84cc-e6c025bac7c1" width=300 />

**Comment by hafizrahman** [comment]
Solved in https://github.com/woocommerce/woocommerce-android/pull/9522
