### ISSUE TITLE
Product List Loading Screen Issues: Blaze Banner is visible

### ISSUE THREAD

**Issue by pmusolino** [woocommerce/woocommerce-android#9539]
The loading screen of the product list seems to be broken because:

- The blaze banner is shown in background.
- It's possible to tap the actions in the Blaze banner, like "Try Blaze now".
- At the same time, It's possible to see the loading cells.
- I entered in a state where other screens (like Orders) load correctly, here it's impossible to go out of this loading state.

Not easy to replicate.
Version 14.8 beta.

<img src="https://github.com/woocommerce/woocommerce-android/assets/495617/e787c940-fb7a-4a2b-ad66-4b82dd2362ee" width=300 />

**Comment by hichamboushaba** [comment]
Fixed by #10021
