### ISSUE TITLE
Product Bundles support during order creation

### ISSUE THREAD

**Issue by atorresveiga** [woocommerce/woocommerce-android#9541]
Adding product bundles' support during order creation will provide a consistent experience for merchants, and it could increase the app’s revenue and engagement.

> Need to support variable items, composite items, and bundled items. I can add these to the order via the website and the order shows up correctly in the app, but I can’t add them to the order via the app because they show up as $0.00 items.

- [ ] Display the configuration button https://github.com/woocommerce/woocommerce-android/pull/9646
- [ ] Change configuration text to Edit when bundled is configured
- [ ] Add a new bundle using the app
- [ ] Edit a new bundle using the app
- [ ] Remove a bundle from the app

**Comment by jaclync** [comment]
@shiki the iOS issue is https://github.com/woocommerce/woocommerce-ios/issues/10428
