### ISSUE TITLE
Promote extensions through the product filter

### ISSUE THREAD

**Issue by atorresveiga** [woocommerce/woocommerce-android#9550]
> If someone has the Product Bundles extension, they can filter their product list that way. But if they don’t have the extension installed, and they filter on that product type, we could show a promo for the extension.

This task is for showing an ad for merchants trying to filter products by an extension they have not installed

**Comment by jaclync** [comment]
Joe' recommendation:

> For the product filter, I think it will be pretty simple.
- An extra element on the row in the filter, on the right, pe5pgL-3rO-p2#comment-2892.
- Not an install button, though – a simple link to an in-app sheet with information, or a webview, is better.
- It may be worth giving the whole row a different visual style, or separating it from the rest of the list – to make it easy to see at a glance which rows are filters and which aren’t (yet)

**Comment by atorresveiga** [comment]
Closed here https://github.com/woocommerce/woocommerce-android/pull/10270
