### ISSUE TITLE
[Variable Product] - Existing options for an attribute are not displayed in add options if more than 10 options available

### ISSUE THREAD

**Issue by jostnes** [woocommerce/woocommerce-android#9583]
**Describe the bug**
Attributes are not displayed fully in add attribute option screen and only show up to 10 options, i.e. if there are more than 10 options, only the last 10 are displayed. 

This was first reported in 6605997-zen and I was able to reproduce the same issue with the steps below.

**To Reproduce**
1. Log in to a store that has more than 10 options for an attribute type in a variable product (e.g. 25 different colors)
2. Create New Variable Product > Add Variations > Select existing attribute (e.g. Color)
3. Scroll down on the attribute screen to select an existing option
4. See that not all options are displayed for that attribute

**Screenshots**

https://github.com/woocommerce/woocommerce-ios/assets/17252150/7ffebfba-bab3-4085-961d-a70184d547d1

**Expected behavior**
All options should be displayed and selectable from the add options screen

**Isolating the problem (mark completed items with an [x]):**
- [ ] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [ ] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [x] I can reproduce this bug consistently using the steps above.

**Mobile Environment**
Please include:
- Device: Pixel 6a
- OS version: Android 12
- WooCommerce version: v14.8-rc-1 (current beta)

**WordPress Environment**
<details>
```
Copy and paste the system status report from **WooCommerce > System Status** in WordPress admin.
```
</details>

**Comment by shiki** [comment]
CUW: peaMlT-an-p2
