### ISSUE TITLE
Feature Request - Add ability to bulk edit product inventory status

### ISSUE THREAD

**Issue by jostnes** [woocommerce/woocommerce-android#9604]
Reported in 6660207-zen

Currently, it's not supported on the app to bulk update the inventory status of the product. Merchant is requesting to add the ability to mark all of a category of items sold out at one time.

**Comment by samiuelson** [comment]
More context – https://github.com/woocommerce/woomobile-private/issues/88

**Comment by malinajirka** [comment]
I would like to propose the following approach as an MVP we can iterate later on. 

1. Add 'Update Stock Status' item into the overflow menu on the product multi-selection list.
2. Show a fullscreen with 
- The available statues 'In stock', 'Out of stock', 'On backorder'
- A note with the current status of the selected items 'Current stock status is [status]' when all the selected products have the same status or 'Current stock statuses are mixed' when the selected products' statuses differ.
- A note stating how many products will be updated 'Stock status will be updated for N products.'. Items which have 'Manage Stock' enabled (aka stock quantity is managed for them) will be ignored during the bulk update. When the selected items contain such products, we'll want to add a note 'Stock status will be updated for N products. Y products with managed stock  quantity will be ignored.'

(Check Product Variation bulk updates for reference - we want to use the same designs as we are using there)

<img src="https://github.com/woocommerce/woocommerce-android/assets/2261188/d1f29cec-50c5-4209-a2fb-ef6336c9dd55" width="150px" />
