### ISSUE TITLE
Shipping labels: add a source parameter to the purchase request for revenue attribution

### ISSUE THREAD

**Issue by jaclync** [woocommerce/woocommerce-android#9626]
Ref: paJDVv-2BY-p2

Currently, we don't have a formal way to track the source of each shipping label purchase (mobile apps or web). As in the p2, we plan to support a `source` parameter (`wc-ios|wc-android`) in the purchase API request body to be recorded in a Tracks event `woocommerceconnect_server_label_purchase` and the billing table entry as a tag.

In the mobile client, we just need to pass a `source: wc-android` parameter in the shipping label purchase API request body **after** the server-side changes are deployed.

**Comment by kidinov** [comment]
iOS draft - https://github.com/woocommerce/woocommerce-ios/pull/10509

**Comment by kidinov** [comment]
Done here -  https://github.com/wordpress-mobile/WordPress-FluxC-Android/pull/2817
