### ISSUE TITLE
Reorder store creation steps: show “Create your store” screen as the first step followed by profiler steps, all while we keep loading progress in the background

### ISSUE THREAD

**Issue by JorgeMucientes** [woocommerce/woocommerce-android#9638]
Reorder store creation steps following this design: 8sNT07kW3VEdnor4baI6ft-fi-387%3A40366

![Screenshot 2023-08-23 at 15 25 15](https://github.com/woocommerce/woocommerce-android/assets/2663464/5a3e25f9-4b76-4ef6-917f-21c3dcb2b028)

- [x] Start store creation flow from free trial store summary step: #9641
- [x] Link all profiler steps together including the 2 new screens and navigate to store loading: #9640

**Comment by hichamboushaba** [comment]
@JorgeMucientes just a FYI, in my last [PR](https://github.com/woocommerce/woocommerce-android/pull/9633), I had to update the `BaseStoreProfilerViewModel` to allow saving the answers before moving to the next step, I'm not sure this would impact your work in this task, but just wanted to let you know in case you need to make any adjustments to the ViewModels.

**Comment by JorgeMucientes** [comment]
Thanks for the heads up @hichamboushaba. No, I don't think that should impact the reordering of the flow.
