### ISSUE TITLE
Change FAQ support link to docs.woocommerce.com page

### ISSUE THREAD

**Issue by astralbodies** [woocommerce/woocommerce-android#964]
Change the FAQ link in support to point at the Android documentation at https://docs.woocommerce.com/document/android/.

@kyleaparker Should we update the copy for that row to not specifically say "FAQ" since this support page isn't a FAQ?

iOS issue: https://github.com/woocommerce/woocommerce-ios/issues/836

**Comment by kyleaparker** [comment]
@astralbodies yea I would suggest either "Help Center", "App Help", or "Documentation"

**Comment by AmandaRiu** [comment]
I like "Help Center" 👍

**Comment by astralbodies** [comment]
I vote for Help Center too.

**Comment by jkmassel** [comment]
This is being bumped to 1.7. If it needs to ship sooner, please merge it to release/1.6, and let me know when you're ready for a hotfix release!
