### ISSUE TITLE
[Product Details] `Write with AI` button is hard to access when writing highlights.

### ISSUE THREAD

**Issue by pachlava** [woocommerce/woocommerce-android#9687]
### What

When using `Write with AI` as shown below, I found it quite hard to access the mentioned button, because it was hidden by the keyboard. The only way to tap this button is hiding the keyboard, and the merchant might not even remember that the button is there.

https://github.com/woocommerce/woocommerce-android/assets/73365754/6384014e-4555-4dfc-b8f6-d4d0ab9db611

(shot with Pixel 7 / Android 13 / WCA 15.1)

### How

Either have the button placed above the keyboard 
or make the 'return' key close the keyboard (if paragraphs are not really needed for the highlights)
or make the container with an editbox and button scrollable, so the button can be shown while keyboard is still there.

**Comment by hichamboushaba** [comment]
This should be fixed by https://github.com/woocommerce/woocommerce-android/pull/12311
