### ISSUE TITLE
IllegalArgumentException with tracking date

### ISSUE THREAD

**Issue by nbradbury** [woocommerce/woocommerce-android#969]
On an API 21 emulator I'm seeing this exception when viewing order detail for an order that has tracking data:

<img width="1163" alt="Screen Shot 2019-04-06 at 7 50 09 AM" src="https://user-images.githubusercontent.com/3903757/55669196-812ff380-5842-11e9-91e9-20c3d4f846a2.png">

Viewing the exception in the debugger I see this:

<img width="494" alt="Screen Shot 2019-04-06 at 8 01 11 AM" src="https://user-images.githubusercontent.com/3903757/55669214-b0466500-5842-11e9-9308-6dac18a263eb.png">

**Comment by jkmassel** [comment]
This is being bumped to `1.7`. If it needs to ship sooner, please merge it to `release/1.6`, and let me know when you're ready for a hotfix release!

**Comment by AmandaRiu** [comment]
@nbradbury it's so weird because the error prints out what the argument is, and the argument is "2019-04-04" - which is indeed in the format of "YYYY-MM-DD" and doesn't contain a "Y" in the string. Are you able to replicated this reliably? If so, can you give me access so I can step through it myself?

**Comment by nbradbury** [comment]
Apologies, @AmandaRiu - I didn't see your reply until now. I'm unable to reproduce this anymore, but according to [this SO post](https://stackoverflow.com/questions/25337241/java-lang-illegalargumentexception-illegal-pattern-character-y-for-simpledate) an uppercase "Y" isn't a valid pattern on devices < API 24 (see [docs](https://developer.android.com/reference/java/text/SimpleDateFormat.html)). Possibly related?

**Comment by AmandaRiu** [comment]
Yup, that seems like it would definitely be the culprit. The reason it's not happening now is it was inadvertently fixed in in this PR: https://github.com/woocommerce/woocommerce-android/pull/996

Closing ticket.
