### ISSUE TITLE
Subscreen for adding product name

### ISSUE THREAD

**Issue by hafizrahman** [woocommerce/woocommerce-android#9800]

**Comment by JorgeMucientes** [comment]
Hey @hafizrahman ! Just a heads up that there's these main ticket as reference #9785 for all the tasks or issues related to Product Creation with AI project. I'd suggest adding this there and assign yourself to it, so we can easily check who is working on what and avoid overlapps 🙂

**Comment by hafizrahman** [comment]
@JorgeMucientes yup, I generated this issue directly from the task on #9785
