### ISSUE TITLE
[Application Passwords] Add ability to manage product passwords

### ISSUE THREAD

**Issue by hichamboushaba** [woocommerce/woocommerce-android#9801]
In WooCommerce 8.1, the REST API has been [improved](https://github.com/woocommerce/woocommerce/pull/39438) by adding a new field for the `products` response to allow managing the visibility password, this will allow the mobile apps to support this feature when the site is accessed using Application Passwords.

**Comment by dangermattic** [comment]
🚫 Please add a type label (e.g. **type: enhancement**) and a feature label (e.g. **feature: stats**) to this issue.

**Comment by hichamboushaba** [comment]
Already implemented in https://github.com/woocommerce/woocommerce-android/pull/12642
