### ISSUE TITLE
Purchase Shipping labels – error fetching shipping rates

### ISSUE THREAD

**Issue by anitaa1990** [woocommerce/woocommerce-android#9848]
**Describe the bug**
A user in support complained that they are unable to purchase shipping labels from the mobile apps because the app is unable to fetch shipping rates for the given addresses and packages. They were able to purchase labels from the web dashboard.

**To Reproduce**
1. Go to any pending/processing order & click on "Create shipping label".
2. Enter a valid US From & To address.
3. Select package details.
4. See error.

I was able to replicate this issue from the app using Postman. This is the request body sent from the mobile app.
```
{"destination":{"address":"366 Karen LN Unit E","name":"STATS TESTING1","phone":"343434343","company":"","city":"Woodbury","country":"US","state":"MN","postcode":"55129-3016","address_2":""},"packages":[{"hazmat":"none","weight":4,"id":"C5C6523A-B943-4AAD-B8DA-FE2BE167BA27","is_letter":true,"width":9.5,"length":12.5,"height":0.5,"box_id":"flat_envelope"}],"origin":{"address_2":"","postcode":"55125-8212","country":"US","name":"Midwest Eye Labs","company":"","city":"Woodbury","address":"7582 CURRELL BLVD STE 109","state":"MN","phone":"45658464"}}
```
If I remove the field: `"hazmat":"none"` from the request body, the API returned 200 response.

For reference, this is what the web request body looks like:
```
{"origin":{"company":"","name":"MIDWEST EYE LABS","country":"US","state":"MN","address":"7582 CURRELL BLVD STE 109","address_2":"","city":"WOODBURY","postcode":"55125-8212","phone":"456589846"},"destination":{"company":"","address_2":"","city":"WOODBURY","state":"MN","postcode":"55129-3016","country":"US","name":"STATS TESTING1","address":"366 KAREN LN UNIT E","phone":"343434343"},"packages":[{"id":"default_box","box_id":"test","length":1,"width":1,"height":1,"weight":4,"is_letter":false}]}
```

**Isolating the problem (mark completed items with an [x]):**
- [x] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [x] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [x] I can reproduce this bug consistently using the steps above.

**Comment by ThomazFB** [comment]
I can confirm this problem is iOS-exclusive:

https://github.com/woocommerce/woocommerce-android/assets/5920403/e9256759-0ef3-4cf3-b1cc-6a99360454fd
