### ISSUE TITLE
[Passkeys] Handle generic errors

### ISSUE THREAD

**Issue by Ecarrion** [woocommerce/woocommerce-android#9913]
# Context

Errors returned by the server are not user-friendly. Additionally, nonces can't be reused across requests. Every time we encounter an error the flow should be restarted to recreate nonces.

# Task

- [ ] If the server returns an error, show a friendly message.
- [ ] After the error is presented, exit the flow to the previous screen. 

# Copy
> Whoops, something went wrong. Please try again!

**Comment by ThomazFB** [comment]
Implemented in https://github.com/wordpress-mobile/WordPress-Login-Flow-Android/pull/123
