### ISSUE TITLE
Empty view displayed after a few seconds when stats are zero

### ISSUE THREAD

**Issue by anitaa1990** [woocommerce/woocommerce-android#994]
## Describe the issue
When there are zero stats for a site,

After connecting to the site, the stats skeleton view is first displayed while we were fetching the stats, then the visitor stats was displayed and the orders were 0. But then, after a few seconds, the empty view is displayed. 

<img src="https://user-images.githubusercontent.com/22608780/56125116-ce743980-5f95-11e9-8c1c-3e80d77cdd84.gif" width="300"/>

This does not seem to be the best user experience. One idea would be to not show the stats at all when they are zero and just display the empty view.

**Comment by nbradbury** [comment]
Update: we had a customer report this issue, saying he didn't have any orders but he did have visitors.  He was bothered by how the "Waiting for customers" view made it impossible to see how many visitors he had.

**Comment by nbradbury** [comment]
I discussed this with @kyleaparker and she suggested we handle this situation like this:

<img width="416" alt="Woo MVP Android-iOS i8 20190218 2019-05-10 16-56-41" src="https://user-images.githubusercontent.com/3903757/57583161-bb249300-749b-11e9-8e21-8b2d6b4f21ce.png">
