### ISSUE TITLE
Add missing tracking for store creation profiler steps

### ISSUE THREAD

**Issue by JorgeMucientes** [woocommerce/woocommerce-android#9960]
## Description

Back when we worked on the new store creation flow, we added to new profiler steps: 
- Challenges step
- Features step 

We also refactored the logic to upload the profiler data, but we missed adding the new properties and values for challenges and features: https://github.com/woocommerce/woocommerce-android/pull/9633. We need to fix this that.

**Comment by pachlava** [comment]
Adding a priority label to avoid this issue getting into the list for the MTTR metric.
See pdcxQM-2Su-p2

I'm setting `priority: low` since the issue is about analytics and is not user-facing. Correct me if I'm wrong.
