### ISSUE TITLE
Fix store creation flow tracking to ensure we always track when flow is started

### ISSUE THREAD

**Issue by JorgeMucientes** [woocommerce/woocommerce-android#9967]
We rely on `site_picker_create_site_tapped` event as a starting point for creating flows related to store creation. This event is fired when tapping on “Create a new store” from the bottom sheet in site picker. See the screen recording below.

https://github.com/woocommerce/woocommerce-android/assets/2663464/2dfec835-5c0f-47be-b6a4-8aaac97839cd

However, there is one other place where the store creation flow is triggered but we are not tracking `site_picker_create_site_tapped` : when the users signs up for the first time, and we automatically trigger the store creation flow. This means that any funnel that sets `site_picker_create_site_tapped` event as starting point will miss out all the new users signing up.

The solution is to create a new event that we ensure is tracked ALWAYS when triggering store creation flow, independly of where is the store creation triggered from or which is the first step of the store creation. 

- Event name: `site_creation_flow_started`
- Properties: `source`: `store_picker` | `prologue` | `login_email_error` | `login`

**Comment by pachlava** [comment]
Adding a priority label to better align with the rules for MTTR metric.
See pdcxQM-2Su-p2

I'm setting `priority: low` since the issue is about analytics (not user-facing). Correct me if I'm wrong.
